### ISSUE TITLE
Perceptual weighting is limited to dB(A) standard

### ISSUE THREAD

**Issue by beasteers** [librosa/librosa#1007]
Since there's A weighting, we could also support C weighting 🤷‍♀️

**Comment by lostanlen** [comment]
Yes, i'm down for adding B, C, D weighting in addition to A.
The way i would see it would be to add a kwarg to `perceptual_weighting`, named `letter` (or `standard`, or `curve` ...) that would default to `A` for backwards compatibility and that could take values `B`, `C`, `D`. 
See: 
'https://github.com/librosa/librosa/blob/master/librosa/core/spectrum.py#L1747

Also worth reading if you haven't already done so: #463

**Comment by bmcfee** [comment]
I like this proposal.  Historically, we only implemented A-weighting to reproduce @mattmcvicar 's chroma pipeline.

Filling out @lostanlen's suggestion a bit, how about the following:

- Generalize `core.A_weighting` to support `B,C,D,Z` modes, and rename it to something like `loudness_curve`.  We could also use `None` to support a flat response
- Add a deprecation-rename for `core.A_weighting` to be removed in 0.9.
- Add the corresponding parameter to `perceptual_weighting`

**Comment by beasteers** [comment]
Sgtm! 😊

**Comment by lostanlen** [comment]
@bmcfee do you have an opinion on the best name for the kwarg? (with A/B/C/D/Z values)

**Comment by nullmightybofo** [comment]
> [...]
>     * Generalize `core.A_weighting` to support `B,C,D,Z` modes, and rename it to something like `loudness_curve`.  We could also use `None` to support a flat response
> [...]

May I suggest a different term than `loudness_curve`? That term makes me think of a time-series of e.g. per-frame loudness values (though the context should make it clear that this is not what is meant).

Wouldn't  `frequency_weighting` or `weighting_curve` be more appropriate?

https://en.wikipedia.org/wiki/A-weighting

**Comment by bmcfee** [comment]
> Wouldn't `frequency_weighting` or `weighting_curve` be more appropriate?

I like both of those, thanks.
