### ISSUE TITLE
phase_vocoder: Why adding 2 to time_steps?

### ISSUE THREAD

**Issue by stefan-falk** [librosa/librosa#1009]
I would like to know/understand why we add `2` at this line:

https://github.com/librosa/librosa/blob/571a2a0e6cc5e1f920d619f147d2a9d30f9e67c2/librosa/core/spectrum.py#L1331

Wouldn't it also be correct to have `D[:, int(step):int(next_step)]` instead of adding `2` here?

**Comment by dpwe** [comment]
We're specifically trying to extract a pair of adjacent time samples in
order to interpolate between them. `step` is a real-valued point along the
time axis indicating the desired "sample" from the original spectrogram, so
step=3.1 means 10% of the way between columns 3 and 4.  So we extract
columns int(step) and int(step) + 1, then use alpha = step - floor(step) as
the interpolation factor between them.

  DAn.

**Comment by stefan-falk** [comment]
@dpwe Ah, that makes perfectly sense and now I see that of course it has to be +2 in order to get the two vectors which we want to interpolate. Thanks for clarification. 👍
