### ISSUE TITLE
AttributeError: module 'librosa' has no attribute 'lpc'

### ISSUE THREAD

**Issue by Jaspreet-Sian** [librosa/librosa#1011]
Hello guys, I am trying to import lpc using following code:
> import librosa
> y, sr = librosa.load(librosa.util.example_audio_file(), offset=30, duration=0.020)
> a = librosa.lpc(y, 2)

But it gives the following error: 
> AttributeError: module 'librosa' has no attribute 'lpc'

I have also tried to implement lpc through following code:
> import librosa
> from librosa.core import audio
> y, sr = librosa.load(librosa.util.example_audio_file(), offset=30, duration=0.020)
> a = audio.lpc(y, 2)

But it didn't make any sense. So how can I use librosa.core.lpc?

**Comment by bmcfee** [comment]
Please fill out the issue template completely, including versions and dependencies, otherwise we can't diagnose your problem.

**Comment by Jaspreet-Sian** [comment]
> Please fill out the issue template completely, including versions and dependencies, otherwise we can't diagnose your problem.

Python version: 3.6.8
librosa: 0.6.2
dependecies made by using pip3 command 
> pip3 install --user librosa

**Comment by bmcfee** [comment]
lpc was added in version 0.7.0, as documented here: https://librosa.github.io/librosa/changelog.html#v0-7-0

You'll have to upgrade to get it.

**Comment by Jaspreet-Sian** [comment]
> lpc was added in version 0.7.0, as documented here: https://librosa.github.io/librosa/changelog.html#v0-7-0
> 
> You'll have to upgrade to get it.

I sincerely appreciate your help :+1:
