### ISSUE TITLE
The return of resample will out of valid range

### ISSUE THREAD

**Issue by wizardk** [librosa/librosa#1023]
#### Description
the return of resample will out of valid range

#### Steps/Code to Reproduce

[16k.zip](https://github.com/librosa/librosa/files/3895173/16k.zip)

```
import librosa

print(librosa.__version__)  # '0.6.3'

y, _ = librosa.load(path='16k.wav', sr=16000)
print(y.min(), y.max())  # [-1, 0.9999695]
y = librosa.resample(y, 16000, 8000)
print(y.min(), y.max())  # [-1.955016, 1.5530436]
```

**Comment by bmcfee** [comment]
This is not an error. sinc interpolation is not constrained to preserve l_infinity (min/max) bounds, and there is generally no hard requirement that signals lie in +-1.

The librosa resample function allows you to pass `scale=True`, in which case, the RMS energy is (approximately) preserved before and after resampling.

**Comment by wizardk** [comment]
@bmcfee Hi, thanks for your reply. But imagine the following process:

```
import librosa

y, _ = librosa.load(path='16k.wav', sr=16000)
print(y.min(), y.max())  # [-1, 0.9999695]
y = librosa.resample(y, 16000, 8000, scale=True)  # [-2.7648103, 2.1963353]
print(y.min(), y.max())  # [-1.955016, 1.5530436]
mfcc = librosa.feature.mfcc(y, 8000, n_mfcc=24)
print(mfcc.min(), mfcc.max())  # [-400.1866924488449, 244.55393112049154]

librosa.output.write_wav(path='8k.wav', y=y, sr=8000)
y, _ = librosa.load(path='8k.wav', sr=8000)
print(y.min(), y.max())  # [-1, 0.9999695]
mfcc = librosa.feature.mfcc(y, 8000, n_mfcc=24)
print(mfcc.min(), mfcc.max())  # [-432.8691863345103, 219.0563636310527]
```

This will result in inconsistent results of subsequent operations.

**Comment by bmcfee** [comment]
> This will result in inconsistent results of subsequent operations.

Yes, that's true.  Resampling (especially downsampling) is an inherently destructive operation, so I don't think it's right to expect MFCCs to look the same before and after.  Remember: min and max are extremely brittle operations, as they depend entirely on a single sample.  It helps to look at the bigger picture here.

Imagine if your signal was a perfect square wave at 16K, and you downsample to 8K, like so:
![image](https://user-images.githubusercontent.com/1190540/69877696-db2d6f80-1290-11ea-9ced-8e56c7496659.png)

Of course there will be over-shoot at the discontinuities; this is an inherent limitation of band-limited signals.  The above was done with resampy (time-domain sinc interpolation), but setting `mode='fft'` or `polyphase` gives similar results:
![image](https://user-images.githubusercontent.com/1190540/69877754-0ca63b00-1291-11ea-8697-c2f8ee39de37.png)
![image](https://user-images.githubusercontent.com/1190540/69877763-1465df80-1291-11ea-90ab-717982e7c735.png)

**Comment by wizardk** [comment]
Your answer is clear and helpful, thanks a lot!
