### ISSUE TITLE
de-emphasis (↔ preemphasis)

### ISSUE THREAD

**Issue by keunwoochoi** [librosa/librosa#1025]
I feel like why not when we have `preemphasis`. A use case would be when people use librosa as a preprocessor of a system (speech analysis/enhancement for example) where they'd need to recover the preemphasis-ed input signals. Any thoughts?

**Comment by bmcfee** [comment]
Yeah, this seems doable.

The preemph filter uses `b=[1, -coef], a = [1]`, which gives zeros, poles, and gain `z=[coef], p=[], k=1`.  The inverse filter would exchange poles and zeros, putting a pole at `coef` and producing coefficients `b'=a, a'=b`.  The inverse filter then has a pole at `0 < coef < 1` (for nontrivial filters) which is stable.

I tested this out and it seems to work well enough for default settings, at least after the filter warms up for a bit.  The hiccup here is getting the initial conditions right.

**Comment by keunwoochoi** [comment]
> The hiccup here is getting the initial conditions right.

What do you mean by initial conditions?

**Comment by bmcfee** [comment]
> What do you mean by initial conditions?

Pre-emphasis is a weighted first-order difference, which is undefined at the first input sample.  Our implementation uses `lfilter_zi` to initialize the filter to steady-state, which would need to be inverted to recover the initial `x[0]` (or something close to it).

**Comment by keunwoochoi** [comment]
👍 thanks for the update and the answers!

**Comment by bmcfee** [comment]
Reopening this issue because we haven't implemented it yet.
