### ISSUE TITLE
AttributeError: module 'librosa.feature' has no attribute 'fourier_tempogram'

### ISSUE THREAD

**Issue by hideodaikoku** [librosa/librosa#1035]
#### Description
Module not found when trying to implement fourier_tempogram

#### Steps/Code to Reproduce
```python
import librosa
import librosa.display
filename = librosa.util.example_audio_file()
y, sr = librosa.load(filename)
oenv = librosa.onset.onset_strength(y=y, sr=sr, hop_length=hop_length)
tempogram = librosa.feature.tempogram(y=y,sr=sr)
f_tempogram = librosa.feature.fourier_tempogram(onset_envelope=oenv, sr=sr, hop_length=512)
plt.figure(figsize=(8, 8))
plt.subplot(3, 1, 1)
plt.plot(oenv, label='Onset strength')
plt.xticks([])
plt.legend(frameon=True)
plt.axis('tight')
plt.subplot(3, 1, 2)
librosa.display.specshow(np.abs(f_tempogram), sr=sr, x_axis='time', y_axis='fourier_tempo', cmap='magma')
plt.title('Fourier tempogram')
plt.subplot(3, 1, 3)
librosa.display.specshow(tempogram, sr=sr, x_axis='time', y_axis='tempo', cmap='magma')
plt.title('Autocorrelation tempogram')
plt.tight_layout()
plt.show()
```

#### Expected Results
Should produce a visualization of the Fourier Tempgram

#### Actual Results

AttributeError                            
Traceback (most recent call last)
<ipython-input-56-c08b1c7eb547> in <module>()
----> 1 f_tempogram = librosa.feature.fourier_tempogram(onset_envelope=oenv, sr=sr, hop_length=512)
module 'librosa.feature' has no attribute 'fourier_tempogram'

#### Versions
Linux-4.14.137+-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
NumPy 1.17.4
SciPy 1.3.3
librosa 0.6.3

**Comment by bmcfee** [comment]
Fourier tempogram was added in version 0.7.0, but you're using 0.6.3.  You need to upgrade.
