### ISSUE TITLE
`power_to_db` default setting of `top_db` not ideally chosen

### ISSUE THREAD

**Issue by gerazov** [librosa/librosa#1039]
The default setting of `top_db` in `power_to_db` currently set to 80 dB causes unexpected behaviour.

I want to get a minimum value of the MFCC energy coefficient from a selection of `wav` files for normalisation purposes. For this reason I concatenate all the files and calculate the MFCC on this `master_wav`. What I get is higher than the minimum for C0 for one of the files, even though all of the files are normalised to -1 dB. 

I tracked down the problem to the `top_db` default setting. Here is a comparison of the minimum and maximum values I get for the master file and 0th file:

| feature/file | max | min | min `top_db=80`|
| --- | --- | ---| --- |
| log spectrogram master  | 39.3 | **-100** (from `amin`)| **-40.7** | 
| log spectrogram 0th file  | 33.15 | **-83.66** |  **-46.85** |
| Mel spectrogram master | 25.38 | **-88.33** | **-54.62** | 
| Mel spectrogram 0th file | 18.69 | **-83.52** | **-61.31** |

And this transfers to the MFCCs.

Even though I understand the rationale of setting `top_db = 80`, it leads to the presented inconsistencies. Maybe setting it to `None` is a better option.

**Comment by bmcfee** [comment]
> The default setting of `top_db` in `power_to_db` currently set to 80 dB causes unexpected behaviour.

I don't think it's unexpected -- the documentation is pretty explicit on this point.



>  Maybe setting it to `None` is a better option.

I don't think we should change the default setting here.  If it's so cumbersome to explicitly set this parameter, you may want to try out the [presets](https://librosa.github.io/librosa/auto_examples/plot_presets.html#sphx-glr-auto-examples-plot-presets-py) package.

**Comment by gerazov** [comment]
+1 for [presets](https://librosa.github.io/librosa/auto_examples/plot_presets.html#sphx-glr-auto-examples-plot-presets-py)!

I still think it's weird that a part of an audio file would have a different MFCC minimum than the whole file. A less informed user might not know where to look ...

**Comment by lostanlen** [comment]
Right. Another option is to use a nonlinear function for loudness compression that does not involve a reference, such as cubic root.

I am in favor of closing this issue. It's a caveat to keep in mind, but not enough to warrant a break in backwards compatibility.
I prefer to have an MFCC that is not exactly intensive* than to have NaN-valued MFCCs in every silent frame of every recording.

[*: https://en.wikipedia.org/wiki/Intensive_and_extensive_properties]
