### ISSUE TITLE
Problems importing librosa

### ISSUE THREAD

**Issue by limapedro** [librosa/librosa#1046]
#### Description

Hi librosa seems to have a bug, I'm using Windows 10 and after I've installed librosa 0.7.1 I can't import librosa, basically the my program enter an infinite loop while importing librosa, here's a screeshot, does anyone have this problem before?

![image](https://user-images.githubusercontent.com/16644771/71536356-db02ad00-28ec-11ea-9b78-3357bd5f7e3c.png)

**Comment by bmcfee** [comment]
This is impossible for us to debug without more details about your environment.  My guess is that some upstream dependency (eg scikit-learn, numba, or joblib) is hanging on import.

I suggest going through our list of dependencies https://github.com/librosa/librosa/blob/2c0f7fa1acc4dd7e04072581a0269244afb3865f/setup.py#L46-L57 and trying to import each one.  If they all import successfully, but librosa still fails to import, then we'll have to do some more debugging.

**Comment by limapedro** [comment]
@bmcfee Hi thanks for answering, I was testing earlier and it seems that I have some problems with my environment, I can import librosa while running CMD with admin privileges. I'm gonna clean my env and post updates. Thank you again.

**Comment by limapedro** [comment]
Got this error in my new env:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python36\lib\site-packages\librosa\__init__.py", line 12, in <module>
  File "C:\Program Files\Python36\lib\site-packages\librosa\core\__init__.py", line 123, in <module>
  File "C:\Program Files\Python36\lib\site-packages\librosa\core\time_frequency.py", line 11, in <module>
  File "C:\Program Files\Python36\lib\site-packages\librosa\util\__init__.py", line 77, in <module>
  File "C:\Program Files\Python36\lib\site-packages\librosa\util\utils.py", line 1825, in <module>
  File "C:\Program Files\Python36\lib\site-packages\numba\decorators.py", line 194, in wrapper
    disp.enable_caching()
  File "C:\Program Files\Python36\lib\site-packages\numba\dispatcher.py", line 679, in enable_caching
    self._cache = FunctionCache(self.py_func)
  File "C:\Program Files\Python36\lib\site-packages\numba\caching.py", line 614, in __init__
    self._impl = self._impl_class(py_func)
  File "C:\Program Files\Python36\lib\site-packages\numba\caching.py", line 349, in __init__
    "for file %r" % (qualname, source_path))
RuntimeError: cannot cache function '__shear_dense': no locator available for file 'C:\\Program Files\\Python36\\lib\\site-packages\\librosa\\util\\utils.py'

**Comment by limapedro** [comment]
Updates incoming:

![image](https://user-images.githubusercontent.com/16644771/71548474-78adb900-298d-11ea-9299-1af39a9eef06.png)

So this is here I'm at right now, I was able to import all of these libraries through normal privileges, but it fails to do so with librosa, the error seems to be in getting permission to create temp files in the package folder as you can see in this print.

![image](https://user-images.githubusercontent.com/16644771/71548503-da6e2300-298d-11ea-9f00-7933bc9a6af5.png)

**Comment by bmcfee** [comment]
> So this is here I'm at right now, I was able to import all of these libraries through normal privileges, but it fails to do so with librosa, the error seems to be in getting permission to create temp files in the package folder as you can see in this print.

Ah, that's interesting.  I think this is a problem with numba: any other package that uses `@numba.jit` to compile functions with caching enabled should have the same behavior.  Can you try changing the [numba cache directory environment variable](https://numba.pydata.org/numba-doc/dev/reference/envvars.html#envvar-NUMBA_CACHE_DIR) to something that you have write permission to?

**Comment by limapedro** [comment]
Sure, but where do I find NUMBA_CACHE_DIR to change it?

**Comment by bmcfee** [comment]
It's an environment variable -- there are instructions for setting it at the top of the doc page that I linked.

**Comment by lostanlen** [comment]
@limapedro Happy New Year. Did you sort out your import issue?

**Comment by limapedro** [comment]
@lostanlen Happy new year, no I haven't I created the .yml as @bmcfee  told me so, but it didn't work at end.

**Comment by limapedro** [comment]
I`m migrating my env to Python 3.7, doing so solved my problem with librosa, thank you guys.

**Comment by banda13** [comment]
Giving modify privilige to users on the librosa folder solved my problem.
