### ISSUE TITLE
MFCC function throws error when dct_type=None

### ISSUE THREAD

**Issue by ShawnHymel** [librosa/librosa#1051]
#### Description

From my vague understanding of MFCC, the DCT is needed to compute the final values. However, according to the docs at [https://librosa.github.io/librosa/generated/librosa.feature.mfcc.html](https://librosa.github.io/librosa/generated/librosa.feature.mfcc.html), you should be able to compute the MFCC (or get some kind of return) with dct_type set to none.

> dct_type:None, or {1, 2, 3}

At this time, setting dct_type to none throws an error. Is there a way to get MFCCs (or something like it) without the DCT step? If not, maybe remove None as an option in the docs?

#### Steps/Code to Reproduce

Example:

```
import librosa

# Make some random data
S = (np.random.random(1024) * 2) - 1

mfccs = librosa.feature.mfcc(y=S, sr=16000, dct_type=None)
print(mfccs)
```

#### Expected Results

Array of MFCC (or MFCC-like) values.

#### Actual Results

TypeError: %d format: a number is required, not NoneType

#### Versions

Windows-10-10.0.18362-SP0
Python 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)]
NumPy 1.17.4
SciPy 1.3.1
librosa 0.7.1

**Comment by bmcfee** [comment]
Thanks for noting this -- I would class this as a documentation error.  `None` should not be a supported value.

If you want to skip the DCT step, you can just call `librosa.power_to_db(librosa.feature.melspectrogram(...))`.

**Comment by ShawnHymel** [comment]
Good to know, thanks!
