### ISSUE TITLE
Beats are slightly late

### ISSUE THREAD

**Issue by hpx7** [librosa/librosa#1052]
I was noticing that the beats detected using the beat module (both `plp` and `beat_track`) were a fraction of a second delayed compared to where I'd expect them to be.

Graphing librosa's onset strength envelope against [madmom](https://github.com/CPJKU/madmom)'s beat module outputs, I saw that the beats typically occur just before the onsets:
![image](https://user-images.githubusercontent.com/5400947/71947754-d61ae480-319b-11ea-9280-dfa89b31e235.png)

Thus by using onset peaks as the primary method of beat detection, we end up reporting late beats.

Indeed, by playing clicks at the beat positions, the madmom beats feel more correct than the librosa ones. Obviously, madmom uses entirely different techniques compared to the onset-based ones that librosa uses, but I found it interesting that I found a consistent bias (late by 0.02-0.06s) amongst several songs I tested. The bias persisted with both 22050 and 44100 sampling rates.

Since I couldn't find anything in the literature about this, wanted to check if anyone had come across this before or had any hypotheses for why it could be happening. Perhaps beats typically occur at the beginning of the offsets rather than the peak?

**Comment by hpx7** [comment]
It looks like there's a difference in madmom's spectral flux calculation as well which shows the same bias:
![image](https://user-images.githubusercontent.com/5400947/71955420-446ca080-31b6-11ea-882d-04dbe4d4b547.png)

**Comment by bmcfee** [comment]
> I was noticing that the beats detected using the beat module (both `plp` and `beat_track`) were a fraction of a second delayed compared to where I'd expect them to be.

Can you say more about where your expectation comes from?

I'm pretty confident that there's nothing intrinsically "wrong" about how the beat tracker and onset strength are working.  Frame alignment and time conversion are very thoroughly tested.  Of course, the default parameterization is certainly not optimal, and madmom is much better at these things. You should be able to match their superflux onset envelope with a bit of parameter tuning, see [this example](https://librosa.github.io/librosa/auto_examples/plot_superflux.html#sphx-glr-auto-examples-plot-superflux-py)


> The bias persisted with both 22050 and 44100 sampling rates.

Sampling rate is less relevant here than frame rate.  Madmom's frame rate (determined by samplingr ate and hop length) is much finer than librosa's, and that might account for the discrepancy you're seeing.

> I found a consistent bias (late by 0.02-0.06s)

This is between 1 and 3 frames at librosa's default rate, so it's not terrible surprising.  Note also that librosa uses centered frames (by input padding), and (I think?) madmom has left-aligned frames, so you will need to be careful in doing the unit conversion to plot onset envelopes with a horizontal axis measured in seconds.

**Comment by hpx7** [comment]
> Can you say more about where your expectation comes from?

It came from manually annotating some songs and finding that the librosa onset peaks were typically 20-60ms after my beat annotations (whereas the madmom beats were accurate)

> Note also that librosa uses centered frames (by input padding), and (I think?) madmom has left-aligned frames, so you will need to be careful in doing the unit conversion to plot onset envelopes with a horizontal axis measured in seconds.

If I compute the onset envelope with `center=False` then the peaks appear to align!
![image](https://user-images.githubusercontent.com/5400947/72013758-83d5d400-322c-11ea-9730-cbd451b5d0f2.png)


Here's how I'm computing and plotting the onsets:
```
y, sr = librosa.core.load(filename, sr=None)
onset_env = librosa.onset.onset_strength_multi(y=y, sr=sr, center=False)[0]
times = librosa.times_like(onset_env, sr=sr)
```

Is there some special consideration I should be taking for the unit conversion for centered frames?

**Comment by bmcfee** [comment]
> Is there some special consideration I should be taking for the unit conversion for centered frames?

That seems fine to me, since the default parameters are all internally consistent, and the time converter assumes centered frames.  However, if madmom uses left-aligned frames, you'll need to handle that differently.

**Comment by lostanlen** [comment]
@hpx7 thank you for all the good sleuthing 🕵 
shall we close the issue at this point?

**Comment by lostanlen** [comment]
To recap, `center=False` seems to have solved the problem. Another option is just to increase frame rate (reduce `hop_length`).

Closing.
