### ISSUE TITLE
Error with librosa.load

### ISSUE THREAD

**Issue by chankh1208** [librosa/librosa#1058]
#### Steps/Code to Reproduce
<
import numpy, scipy, matplotlib.pyplot as plt, sklearn, librosa, mir_eval, IPython.display, urllib
plt.rcParams['figure.figsize'] = (100, 100)
import librosa.display
import librosa
filename = 'audio/1362.wav'
x, sr = librosa.load(filename)
-->

#### Expected Results
<It should be loaded properly. I have tried another wav audio file, and it works for Librosa. They are in the same directory so I think I have the correct path.   >

#### Actual Results
<---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/opt/anaconda3/lib/python3.7/site-packages/librosa/core/audio.py in load(path, sr, mono, offset, duration, dtype, res_type)
    128     try:
--> 129         with sf.SoundFile(path) as sf_desc:
    130             sr_native = sf_desc.samplerate

~/opt/anaconda3/lib/python3.7/site-packages/soundfile.py in __init__(self, file, mode, samplerate, channels, subtype, endian, format, closefd)
    626                                          format, subtype, endian)
--> 627         self._file = self._open(file, mode_int, closefd)
    628         if set(mode).issuperset('r+') and self.seekable():

~/opt/anaconda3/lib/python3.7/site-packages/soundfile.py in _open(self, file, mode_int, closefd)
   1181         _error_check(_snd.sf_error(file_ptr),
-> 1182                      "Error opening {0!r}: ".format(self.name))
   1183         if mode_int == _snd.SFM_WRITE:

~/opt/anaconda3/lib/python3.7/site-packages/soundfile.py in _error_check(err, prefix)
   1354         err_str = _snd.sf_error_number(err)
-> 1355         raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
   1356 

RuntimeError: Error opening 'audio/1362.wav': System error.

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-6-62940e66fc65> in <module>
      4 import librosa
      5 filename = 'audio/1362.wav'
----> 6 x, sr = librosa.load(filename)

~/opt/anaconda3/lib/python3.7/site-packages/librosa/core/audio.py in load(path, sr, mono, offset, duration, dtype, res_type)
    145         if isinstance(path, six.string_types):
    146             warnings.warn('PySoundFile failed. Trying audioread instead.')
--> 147             y, sr_native = __audioread_load(path, offset, duration, dtype)
    148         else:
    149             six.reraise(*sys.exc_info())

~/opt/anaconda3/lib/python3.7/site-packages/librosa/core/audio.py in __audioread_load(path, offset, duration, dtype)
    169 
    170     y = []
--> 171     with audioread.audio_open(path) as input_file:
    172         sr_native = input_file.samplerate
    173         n_channels = input_file.channels

~/opt/anaconda3/lib/python3.7/site-packages/audioread/__init__.py in audio_open(path, backends)
    109     for BackendClass in backends:
    110         try:
--> 111             return BackendClass(path)
    112         except DecodeError:
    113             pass

~/opt/anaconda3/lib/python3.7/site-packages/audioread/rawread.py in __init__(self, filename)
     60     """
     61     def __init__(self, filename):
---> 62         self._fh = open(filename, 'rb')
     63 
     64         try:

FileNotFoundError: [Errno 2] No such file or directory: 'audio/1362.wav'>

**Comment by lostanlen** [comment]
Hello,
* are you 100% that the file exists and that you have UNIX permissions to open it?
* have you tried opening the file on a separate media reader?
* please run pysox's `file_info` on the file and copy-paste what you find:
https://pysox.readthedocs.io/en/latest/_modules/sox/file_info.html

**Comment by chankh1208** [comment]
Hi, 

Thank you for your remind. I did make silly mistakes.
