### ISSUE TITLE
Cannot provide a (Hamming) window to extract mfccs on Windows

### ISSUE THREAD

**Issue by Keanri828** [librosa/librosa#1060]
Hello, guys. I am not sure wether this is a librosa or general Python issue, but:
#### Description
I tried to extract mfccs using a Hamming-window for my thesis' machine learning project, but my script ran into a TypeError (Traceback below). This behaviour occured (in my case) **only on Windows** so far (tried it out with two different computers now), on Mac it worked like a charm. I tried finding a solution by posting a question on Stackoverflow, but there's no solution yet. Another person commented this week that it also happens on Google Collab, but I have no further information related to his environment.

#### Steps/Code to Reproduce
```
import librosa

from scipy.signal import get_window

# load file
filename = librosa.util.example_audio_file()
y, sr = librosa.load(filename)

# calculate mfccs
melspec_args = {"n_fft": 160, "hop_length": 80, "window":  get_window("hamming", 160)}
mfccs = librosa.feature.mfcc(y=y, sr=sr, S=None, n_mfcc=12, **melspec_args)

print(mfccs.shape)
```

#### Expected Results
The script should print the dimension of a multidimensional numpy-array created by librosa.feature.mfcc().

#### Actual Results
Error-Traceback:
```
Traceback (most recent call last):
  File "C:/Users/Fiona/PycharmProjects/librosaTest/mfcc_test.py", line 7, in <module>
    mfccs = librosa.feature.mfcc(y=y, sr=sr, S=None, n_mfcc=12, **meltspec_args)
  File "C:\Users\Fiona\Anaconda3\envs\librosaTest\lib\site-packages\librosa\feature\spectral.py", line 1442, in mfcc
    S = power_to_db(melspectrogram(y=y, sr=sr, **kwargs))
  File "C:\Users\Fiona\Anaconda3\envs\librosaTest\lib\site-packages\librosa\feature\spectral.py", line 1534, in melspectrogram
    mel_basis = filters.mel(sr, n_fft, **kwargs)
TypeError: mel() got an unexpected keyword argument 'window'
```

#### Versions
Windows-10-10.0.18362-SP0
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
NumPy 1.17.3
SciPy 1.3.1
librosa 0.6.3

Thank you very much. :-)

Edit/PS: I also created a GitHub repository to share the example and my environment's configuration. It can be found at https://github.com/Keanri828/librosa_mfcc_WindowsError .

**Comment by bmcfee** [comment]
Support for all STFT parameters was added in version 0.7.0: https://librosa.github.io/librosa/changelog.html#v0-7-0  but you're still on 0.6.3.

**Comment by Keanri828** [comment]
> Support for all STFT parameters was added in version 0.7.0: https://librosa.github.io/librosa/changelog.html#v0-7-0 but you're still on 0.6.3.

Interesting. Then Conda-Forge is not up-to-date. I installed my whole Python development environment **today** on this computer. And you're right, I looked into my thesis and looked it up in my table of used packages which I wrote considering my Mac's environment. "Surprise! It's 0.7.1!" 
My Anaconda was not up-to-date though updating did not help. It looks like I somehow only get 0.6.3 via conda install/update. 
Now I have to learn how to install packages without conda in a conda environment. Or how to fix Windows-Anaconda. Great. :-/

But thank you anyway. :)

**Comment by bmcfee** [comment]
> Then Conda-Forge (for Windows?!) is not up-to-date.

That's very strange.  The conda-forge package for librosa is now platform-neutral, so you should get 0.7.2 on all platforms.  I wonder if maybe your conda install itself (ie the package/environment manager) needs to be updated?

**Comment by Keanri828** [comment]
> > Then Conda-Forge (for Windows?!) is not up-to-date.
> 
> That's very strange. The conda-forge package for librosa is now platform-neutral, so you should get 0.7.2 on all platforms. I wonder if maybe your conda install itself (ie the package/environment manager) needs to be updated?

Yes. It's really strange. ``conda search librosa`` is able to find librosa 0.7.2, but I cannot install it at all. This still happens after updating conda. I'm running out of ideas.

**Comment by Keanri828** [comment]
@bmcfee ...And the conda-team asserted that this is a librosa-issue that should be posted in conda-forge/librosa-feedstock... :-| (https://github.com/conda/conda/issues/9607) I saw that you're working on that repository. Shall I open another issue there or is this one enough?

**Comment by bmcfee** [comment]
I'm actually not sure it's a problem with librosa or conda-forge, but it looks from your install log (pasted in the conda repo issue) like you have other packages in your environment that are incompatible with some of librosa's dependencies?

**Comment by Keanri828** [comment]
I don't know. I only installed pandas before trying to install librosa. And why does it work on my Mac then? It was the only computer that could execute my mfcc-extraction-code. In the beginning of my thesis' phase I added the information extracted via librosa to a pandas.DataFrame and filtered them / created subsets for training/evaluation. I really have no more ideas what the underlying problem is.

**Comment by bmcfee** [comment]
I think this has to be something deeper in the dependency chain of conda-forge packages on windows.

Let's migrate the issue over to the librosa feedstock, and then I can maybe tag in some conda-forge folks to help diagnose it.  Sorry for the hassle here!
