### ISSUE TITLE
Detecting pitch - finding the first beat of a bar

### ISSUE THREAD

**Issue by SKempin** [librosa/librosa#1065]
I need to find the pitch of notes so I can detect the first beat of each bar in a [click track.](https://www.dropbox.com/s/6dhwanjafzgaes4/test.mp3?dl=0)

I am using `peak_pick` to detect all the beats, which is working well. However I need to detect the specific beats that have a different pitch.

I have tried a `piptrack` but I am just getting arrays of 0? Is it possible to detect these specific beats that have a different pitch? My current code:

    y, sr = librosa.load("./sounds/input/test.mp3")
    pitches, magnitudes = librosa.piptrack(y=y, sr=sr)
    print("pitches: ", pitches)
    print("magnitudes: ", magnitudes)
    
This results in:

        ('pitches: ', array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32))
        
        ('magnitudes: ', array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32))

**Comment by lostanlen** [comment]
Hello @SKempin, welcome to librosa. For future reference, what you are describing is generally known as "downbeat" tracking in music information retrieval.

I have listened to your example. Although it is true that the downbeats sound a little bit higher in put, a more robust option in your case would be to rely on loudness, not pitch, to detect downbeats.

Here's how: (i recommend you run this in a Jupyter notebook)


```python
import librosa
import matplotlib
%matplotlib inline
from matplotlib import pyplot as plt
import numpy as np
import os
import scipy.signal

threshold = 0.1
hop_length = 512
input_path = 'test.mp3'

y, sr = librosa.load(input_path, sr=None)
rms = librosa.feature.rms(y, hop_length=hop_length)[0, :]
peak_locs = scipy.signal.find_peaks(rms, height=threshold)[0]
peak_heights = rms[peak_locs]

times = librosa.times_like(rms, hop_length=hop_length, sr=sr)
plt.plot(times, rms, label="Energy (RMS)");
plt.plot(times, threshold*np.ones_like(rms), '--', label="Threshold")
plt.plot(times[peak_locs], peak_heights, 'o', label="Detected peaks")

plt.xlim(0, np.ceil(librosa.get_duration(y, sr)))
plt.xlabel("Time (s)")
plt.ylim(0, 2*threshold)
plt.title("Downbeat tracking of {}".format(os.path.split(input_path)[1]))
plt.legend()
```


Result:
![downbeat_tracking](https://user-images.githubusercontent.com/3943142/73690946-6b2bd300-469f-11ea-9762-92cc9773941f.png)


I hope this helps!

**Comment by SKempin** [comment]
@lostanlen Hugely appreciated! I will try this out and let you know. And yes it is the downbeat I am looking, apologies I should have stated this :)

**Comment by SKempin** [comment]
@lostanlen can this be utilized to detect the specific timings of the downbeats? I need he ms timings of all the beats in the sample, and the downbeats specifically.

**Comment by lostanlen** [comment]
@SKempin yes, the downbeat timings are stored in `times[peak_locs]` and are measured in seconds.
to get all beats, simply lower the threshold from 0.1 to something like 0.05
