### ISSUE TITLE
how to trim and re-export a stereo file at 44.1kHz?

### ISSUE THREAD

**Issue by dschiller** [librosa/librosa#1067]
#### Description
Error when saving a trimmed Audio File.

#### Steps/Code to Reproduce

Example:
```
import librosa

subtype = 'PCM_16'
file = 'testStream.wav'

y, sr = librosa.load(file, mono=False)
yt, index = librosa.effects.trim(y)
sf.write(file.split('.')[0]+'2.wav', yt, sr, subtype)
```

#### Expected Results
File will be saved

#### Actual Results

Traceback (most recent call last):
  File "E:\Work\Recordings\PySampleRobot\Sandbox\Basics\Sampler.py", line 85, in <module>
    sf.write(file.split('.')[0]+'2.wav', yt, sr, subtype)
  File "C:\Users\Setgol\AppData\Local\Programs\Python\Python38\lib\site-packages\soundfile.py", line 314, in write
    with SoundFile(file, 'w', samplerate, channels,
  File "C:\Users\Setgol\AppData\Local\Programs\Python\Python38\lib\site-packages\soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Users\Setgol\AppData\Local\Programs\Python\Python38\lib\site-packages\soundfile.py", line 1183, in _open
    _error_check(_snd.sf_error(file_ptr),
  File "C:\Users\Setgol\AppData\Local\Programs\Python\Python38\lib\site-packages\soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening 'testStream2.wav': Format not recognised.

#### Versions
Windows-10-10.0.18362-SP0
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)]
NumPy 1.18.1
SciPy 1.4.1
librosa 0.7.2

**Comment by bmcfee** [comment]
I don't think this has anything to do with `trim`.  Are you able to save any audio using this scheme?

**Comment by dschiller** [comment]
Yes I am. I fixed it by not using librosa instead using my own Function to measure Threshold in the Callback. https://github.com/dschiller/PySampleRobot/blob/master/src/Sampler.py

Maybe someone can provide an Example of reading a File, trim it and save it back.

**Comment by lostanlen** [comment]
Hello @dschiller, my understanding is that you are trying to trim and export a stereophonic audio file. In this case, make sure to transpose the numpy array before calling sf.write. The `shape` should be `(N, 2)`, not `(N, T)`, with `N` the number of samples.

Can you tell me if the following works better for you?

```
import librosa

subtype = 'PCM_16'
file = 'testStream.wav'

y, sr = librosa.load(file, mono=False)
yt, index = librosa.effects.trim(y)
sf.write(file.split('.')[0]+'2.wav', yt.T, sr, subtype)
```

**Comment by dschiller** [comment]
@lostanlen Thanks, that works for sure. I didn't know that I need to transfrom the Data. Thank's for that ! But the Trim doesn't work that good. Befor using the librosa Trim Function I have 200 Samples Silence at Wav File Start after librosa Trim I have still 100 Samples. I thought librosa Trim will remove all silent Samples ?

**Comment by lostanlen** [comment]
@dschiller this is because librosa resamples on load: https://librosa.github.io/blog/2019/07/17/resample-on-load/


To disable this, pass `sr=None` to `librosa.load`

```
import librosa

subtype = 'PCM_16'
file = 'testStream.wav'

y, sr = librosa.load(file, mono=False, sr=None)
yt, index = librosa.effects.trim(y)
sf.write(file.split('.')[0]+'2.wav', yt.T, sr, subtype)
```

That factor of 2 between 44,100 Hz and 22,050 Hz is also where the 100 vs 200 silent samples discrepancy comes from.

**Comment by dschiller** [comment]
@lostanlen Thanks for that as well. Now the File Format is correct but librosa.effect.trim() does nothing anymore. How does it work to remove the Silent from Beginnning ?

**Comment by lostanlen** [comment]
@dschiller try reducing `top_db`. The default is 60 dB below the peak instantaneous power.
If you set it to something lower, like 30 dB or even 10 dB, trim should cut more drastically.

Sincerely,
Vincent.

**Comment by dschiller** [comment]
Thanks for that Vincent. Unfortunetly that doesn't work for the Start. The End is quite cutted with ``top_db=20`` even to much but the Start left. How can I instead cut / trim the start and let the end untouched ?

![image](https://user-images.githubusercontent.com/3144986/73884203-a37d0e00-4865-11ea-968d-cb9ed086a6d5.png)

**Comment by dschiller** [comment]
I also recognized when using librosa my App goes crazy. Could it be that librosa has serious performance Issues ? Eg. I record Wav Files continuously and librosa.trim just need to trim the recorded File afterwards before the next Sample get recorded. When I ignore librosa everything works fine except the trimming I need in the beginning. When I activate librosa the first sampled Wav File has massive Issues in the recorded Portion like a Timewarp or similar which could happen because of performance Issues and the first Wav Fiel also doesn't get trimmed by librose. Not sure how serious librosa is. Does somebody use it in Production ?

**Comment by lostanlen** [comment]
@dschiller ok, so that's a tiny amount of silence: roughly 300 samples.
Note that the librosa default is a frame size of 2048 and a hop size of 512.
I would recommend that you reduce those values in your application.

Try: 
`librosa.effects.trim(y, frame_size=128, hop_size=32)`
or something like that.

Then, how to remove the beginning but not the end? Note that librosa gives you not only the trimmed result but also a second output called `index` which has the start and end time of trimming.
If you want to disable trimming at the end, just do:

```python
_, index = librosa.effects.trim(y, frame_size=128, hop_size=32)
yt = y[index[0]:]
```

(the usual librosa trimming is equivalent to `yt = y[index[0]:index[1]]`)

I hope this helps!

**Comment by dschiller** [comment]
Thank you Vincent!
