### ISSUE TITLE
Coding style updates

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#1070]
#### Description

In implementing #1064, I noticed that our coding style is a bit inconsistent in places.  As much as I dislike automated style checking, it might be good to give it a once over with black using some sane parameters (eg, 120 line length because it's not 1987).

To be clear, I don't think we should automate this in CI, or require that new contributors always stick strictly to this style, but we are overdue IMO for a cleanup. (Expecially in tests!)

**Comment by lostanlen** [comment]
> 120 line length

Really? Isn't that a bit long? I remember Raymond Hettinger advocating for "90-ish". It's also what black adheres too.

**Comment by bmcfee** [comment]
> Really? Isn't that a bit long?

Ehh fine :)  i just want to make sure we don't go into that ridiculous 78-char limit nonsense.

**Comment by bmcfee** [comment]
Fixed by #1193
