### ISSUE TITLE
util.files should support pathlib objects

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#1071]
#### Description
Title says it all: now that #896 is implemented, we can support pathlib natively.

#### Steps/Code to Reproduce
```python
import librosa
librosa.util.find_files(pathlib.Path('foo', 'bar'))  # search in foo/bar
```
ought to work.  Right now it fails.

**Comment by SuperKogito** [comment]
@bmcfee I can take on this but can you please elaborate/explain, what is the expected output?  is it just a list of all available `.mp3` files?

**Comment by bmcfee** [comment]
@SuperKogito cool, thanks for volunteering!

Essentially, yes, it gives you a list of audio files in the given path.  There are several options though (extensions, subdirectory search, case-sensitivity, etc), so it's a bit more complex than one might expect at a first glance.  Hopefully the documentation explains things thoroughly enough, but feel free to ask for clarification on the expected behavior.

**Comment by SuperKogito** [comment]
I am a little confused about this task, either I am doing it wrong (most probably) or it is really simple. Currently, I thought I can simply use  [ find_files()](https://github.com/librosa/librosa/blob/e94287ad98872f823868844f9e411fe7a61b4277/librosa/util/files.py#L44) as follows: 
```
def files(pathlib_obj, recurse=True, case_sensitive=False, limit=None, offset=0):
    '''Return a list of all available files based on a given pathlib object.

    Parameters
    ----------
    pathlib_obj : pathlib object
        pathlib object for a certain path.

    recurse : boolean
        If `True`, then all subfolders of `directory` will be searched.

        Otherwise, only `directory` will be searched.

    case_sensitive : boolean
        If `False`, files matching upper-case version of
        extensions will be included.

    limit : int > 0 or None
        Return at most `limit` files. If `None`, all files are returned.

    offset : int
        Return files starting at `offset` within the list.

        Use negative values to offset from the end of the list.
    Returns
    --------
    files : list of str
        The list of audio files.
    '''
    return find_files(directory=pathlib_obj.parent,
                      ext=pathlib_obj.suffixes,
                      recurse=recurse,
                      case_sensitive=case_sensitive,
                      limit=limit,
                      offset=offset)
```

**Comment by bmcfee** [comment]
Sorry, my initial post was perhaps unclear and/or misleading.

The proposed change is to modify `find_files` so that a user can supply either a string or a pathlib.Path object, and have things work as expected.  The proposed change is not to add a new function that wraps `find_files`.

**Comment by bmcfee** [comment]
It turns out that this just works out of the box, and no changes are necessary.  Closing this one out.
