### ISSUE TITLE
[Discussion] CQT, VQT, energy preservation, and frequency band alignment

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#1073]
I wanted to make a separate issue to consolidate the discussion around a number of related points that have popped up in the implementation of VQT #1018, inverse CQT #165, and so on.  @lostanlen and I have discussed these things in various places (often offline), but it would be helpful to have a more permanent record.

# Frequency band definitions

In the CQT implementation, we follow the SK2010 definition of the frequency bands, which are essentially left-aligned: `[f, a * f]` (for some constant `a`).  This works well enough, but it makes some calculations awkward, eg in the VQT.  Later on in the CQT toolbox, the definition shifted to a centered representation, eg `[f / sqrt(a), f * sqrt(a)]` (again for some constant `a`), so that the  frequency of each filter is centered within the band.

Some questions:

- Should we add support for centered frequency bands?  I don't think it would change much, except possibly some boundary effects at the top end of octaves.
- Should we make centering the default?  Should we even bother with left-aligned bands anymore?

# Energy preservation

Our CQT implementation has historically had a bunch of headaches around normalization and energy preservation.  Of course we can't exactly preserve energy with a lossy frequency representation, but our current cqt/icqt round trip gets pretty close.  However, other feature representations (notably Mel) are not so forgiving, and it would be nice if we could strive for consistency here.

**Comment by YolandaFeng1995** [comment]
![image](https://user-images.githubusercontent.com/46066608/81365873-e75d0900-911b-11ea-9c42-ec82f0c8defd.png)
Hi I want to know why there is a 'Transition Zone ' in the CQT spectrum, especially in the low freqs.

**Comment by lostanlen** [comment]
@YolandaFeng1995 it's hard to tell unless we have your signal and the code to reproduce your display.
Potentially worth reading: https://github.com/librosa/librosa/issues/341

**Comment by YolandaFeng1995** [comment]
> @YolandaFeng1995 it's hard to tell unless we have your signal and the code to reproduce your display.
> Potentially worth reading: #341

Audio  and code in ZIP.
[communicate_with_librosa_CQT.zip](https://github.com/librosa/librosa/files/4603385/communicate_with_librosa_CQT.zip)

**Comment by lostanlen** [comment]
@YolandaFeng1995 thank you for sharing. The issue is with the parameter `w=0.1`. Maybe you didn't realize this, but you're passing the value `0.1` as the beta parameter of the Kaiser window.
(https://librosa.github.io/librosa/generated/librosa.filters.get_window.html)

It's better to leave `window` to the default value.
Also, make sure to pass `sr` to CQT.
Lastly, your fmin is unnecessarily low.

I rewrote your script and got to this: 

```python
import librosa
from librosa.display import specshow
import numpy as np
import os
import matplotlib.pyplot as plt
import scipy.ndimage


audio_path = './piano_sample.wav'
min_midi = 40
fmin = librosa.midi_to_hz(min_midi)
hop_length = 256

bins_per_semitone = 3
bins_per_octave = 12 * bins_per_semitone
n_octaves = 6
n_bins = bins_per_octave * n_octaves

y, sr = librosa.load(audio_path, sr=None, dtype=np.float64)

y_cqt = librosa.core.cqt(
    y, sr=sr,
    hop_length=hop_length,
    bins_per_octave=bins_per_octave,
    n_bins=n_bins,
    fmin=fmin,
)
y_cqt_db = librosa.amplitude_to_db(np.abs(y_cqt))
plt.figure(figsize=(15, 3))

x_coords = librosa.times_like(y_cqt_db, sr=sr, hop_length=h)
y_coords = librosa.cqt_frequencies(
    n_bins=n_bins, fmin=fmin, bins_per_octave=bins_per_octave)
specshow(
    y_cqt_db,
    x_coords=x_coords, x_axis='time',
    y_coords=y_coords, y_axis='cqt_note',
    cmap='magma'
)
```

Before:
![test_CQT](https://user-images.githubusercontent.com/3943142/81476533-ac89cc80-9212-11ea-9e7f-a66135b2911e.png)


After:
![cqt_yolandafeng](https://user-images.githubusercontent.com/3943142/81476550-bf040600-9212-11ea-9882-0c06433715cc.png)


I hope this helps!

**Comment by YolandaFeng1995** [comment]
THX! Really helps. But still do not know why different windows result in the different spectrums in  low freqs. If I need a suitable frequency resolution in the low freqs, e.g. midi 24-36, could U plz offer me suggestions for the window tradeoff ?

**Comment by lostanlen** [comment]
@YolandaFeng1995 `window='hann'` is probably going to be your safest bet, whatever be the frequency resolution. 
If you want to improve time resolution (at the detriment of frequency resolution), consider passing `filter_scale` as a keyword argument. The default value is `1`. Passing `filter_scale=0.5` will increase the time resolution by a factor 2. Passing `filter_scale=0.25` will increase it by a factor 4. I don't recommend going beyond that factor 4.

If you really struggle with getting good time resolution in the low frequencies, consider replacing the CQT by a VQT (variable-Q transform). See this open PR: #1018

**Comment by YolandaFeng1995** [comment]
THX ！ One more question, is the CQT or VQT  implement suitable for stream processing, i.e. implementing CQT with audio signal as a continuous input?

**Comment by lostanlen** [comment]
@YolandaFeng1995 Yes. In this case, use `pseudo_cqt` inside a `librosa.stream` block.
See: https://librosa.github.io/blog/2019/07/29/stream-processing/
and https://librosa.github.io/librosa/generated/librosa.core.pseudo_cqt.html

**Comment by YolandaFeng1995** [comment]
Hi ~ Scale is a representation of frequency in CQT.  How does the  frequency bandwidth differences result in the energy spectrum?  Is the low frequency, e.g. midi 24  more likely to result in energy loss than high frequency e.g. midi80?  And is it necessary to make the energy spectrum  normalized by frequency bandwidth?

**Comment by lostanlen** [comment]
@YolandaFeng1995 the default normalization should work well.
If you care about a precise measurement of energy as a function of time, use RMS

https://librosa.org/librosa/0.7.2/generated/librosa.feature.rms.html

**Comment by bmcfee** [comment]
I noticed that this issue got derailed, but I would like to resolve the initial questions raised in time for the 0.9.0 release.

**Comment by bmcfee** [comment]
Re-upping these:

> 
>     * Should we add support for centered frequency bands?  I don't think it would change much, except possibly some boundary effects at the top end of octaves.

This is probably how we (and SK10) should have done it in the first place, but retrofitting it will be kind of a pain.  For example, threading the frequency centering (tencering?) API through downstream functions like chroma could get messy.

> 
>     * Should we make centering the default?  Should we even bother with left-aligned bands anymore?

If we implement centering, we should still provide an option for the current style (for backward compatibility).  I'm on the fence about making it the default.  I think it's unambiguously better that way, but I'm also wary of introducing too many subtle but breaking API changes in one go.  Maybe we should do it as a deprecation cycle? Introduce the feature first as an option, and then switch the default at the next major?

**Comment by bmcfee** [comment]
To follow up on the above, the only place where this becomes important is in the construction of filter lengths here:

https://github.com/librosa/librosa/blob/9732ae0775d359e24172bd396e98b44b7cddf19a/librosa/filters.py#L639-L649

**Comment by bmcfee** [comment]
Took a moment to experiment with this a bit.  We can simulate the proposed change (at least when `gamma=0`, ie the CQT case) by modifying the `filter_scale` parameter to `filter_scale = 2.0**(0.5/bins_per_octave)`.  That is, the proposed centering would slightly increase the length (in time) of the filters and sharpen the frequency resolution, but the effect is minimal when `bins_per_octave` is large.

For bpo=12, there's a maximum of about 23dB change in CQT amplitude due to this change on the trumpet example at 44K.  That's pretty substantial, though the average difference is small (~-90dB).  The effect diminishes with higher bpo: 36 gives -30dB, as does 60bpo.

**Comment by bmcfee** [comment]
In light of #1402 , it seems like there's ample justification here for defining the filter-bank constructor to support actually variable Q's (not just variable lengths) deriving from unevenly spaced frequencies.  (As an aside, this might finally implement #18 , albeit in a weird way!)

So instead of 
https://github.com/librosa/librosa/blob/9732ae0775d359e24172bd396e98b44b7cddf19a/librosa/filters.py#L639-L649
we might have something more like
```python  
# Compute the frequencies 
freq = fmin * (2.0 ** (np.arange(n_bins, dtype=float) / bins_per_octave)) 
  
# Derive Q-factors
# alpha = 2.0 ** (1.0 / bins_per_octave) - 1.0  # SK'10 version
# alpha = 2.0 ** (0.5 / bins_per_octave) - 2.0**(-0.5 / bins_per_octave)  #SK'14 version, proposed change above
alpha = (freq[+1] - freq[-1]) / freq  # not literal python here, but imagine a proper centered difference in the numerator
Q = float(filter_scale) / alpha 

if freq[-1] * (1 + 0.5 * window_bandwidth(window) / Q) > sr / 2.0: 
    raise ParameterError("Filter pass-band lies beyond Nyquist") 
  
# Convert frequencies to filter lengths 
lengths = Q * sr / (freq + gamma / alpha) 
```
The result would have `alpha` and `Q` be a vector of length matching `freq`, and the rest works itself out naturally.  It does raise a question of how we should determine the bandwidth at the edges `freq[0]` and `freq[-1]` though.  If we have geometric bin spacing, we can just keep stacking up factors of `2**(1/bpo)`, but with a variable frequency spacing this assumption will not hold.  I suppose we could reflect the spacing at the boundaries, so that the first bin has `alpha = (freq[1] - (freq[1] - freq[0]))/freq[0] = 1`, and the last bin has `alpha = (freq[-1] - (freq[-1] - freq[-2]))/freq[-1] = freq[-2]/freq[-1]`, but that seems a bit hacky to me.  @lostanlen any thoughts?

**Comment by lostanlen** [comment]
@bmcfee Yes, i approve this. Reflecting the spacing is a good idea. But i think that this "reflection" should happen in the log-frequency domain, not the linear-frequency domain

```python
freq_low = freq[0]**2/freq[1]
alpha_low = (freq[1]-freq_low)/freq[0]

freq_high = freq[-1]**2/freq[-2]
alpha_high = (freq_high-freq[-1])/freq[-1]
```

this way `freq_low/freq[0] = freq[0]/freq[1]` and `freq[-2]/freq[-1]=freq[-1]/freq_high`.

In the important particular case of a geometric sequence ...
```python
freq = fmin * (2.0 ** (np.arange(n_bins, dtype=float) / bins_per_octave)) 
```

... and denoting `f0 = freq[0]` and `q = 2**(1/Q)`, we have 
```
freq_low = f0**2 / (f0 * q) = f0 / q
alpha[0] = alpha_low = (f0*q - f0/q) / f0 = q - 1/q

alpha[1] = (f0*(q**2) - f0) / (f0*q) = q - 1/q
# etc.
alpha[k] = (f0*(q**(k+1) - (f0*(q**(k-1)))) / (f0**(q**k)) = q - 1/q
# etc.

freq_high = fmax**2 / (fmax/q) = fmax*q
alpha[-1] = alpha_high = (fmax*q - fmax/q) / fmax = 1 - 1/q
```

So the CQT with geometric spacing produces a constant `alpha`.

**Comment by bmcfee** [comment]
> But i think that this "reflection" should happen in the log-frequency domain, not the linear-frequency domain

Absolutely, good catch.  Thanks for the derivation there: I think it clarifies for me what was going on in SK14 as well.

Now, going back to the earlier parts of the discussion, I'm not actually sure where I originally got the `f/sqrt(a), f*sqrt(a)` idea from (can't find it in the paper), though I guess I was trying to keep things roughly similar to the present implementation.  The proposed change would significantly widen the bandwidths compared to the current default, and that will have plenty of downstream effects.

**Comment by bmcfee** [comment]
>  The proposed change would significantly widen the bandwidths compared to the current default, and that will have plenty of downstream effects.

Following up on this, we can simulate the proposal by using the existing filterbank constructor with `filter_scale=1/(1+2**(-1/bins_per_octave))` ~= 0.5.  As expected, the resulting filters are ~1/2 shorter in time and ~2x broader in frequency, and the difference is quite noticeable.

If we want to make this the new default, we'll probably want to inspect any downstream functions (eg chroma) for basic compatibility.  We should also provide some documentation about how to recover the <=0.8.x style by setting `filter_scale=1+2**(-1/bins_per_octave)`.

Thinking back a bit though, I guess the initial reasoning (SK10) and my proposed adaptation (above) was to have the main lobes of the filters be approximately disjoint: SK10 inferred bandwidth as distance between neighboring frequencies, and my proposal above uses the (geometric) midpoints between (k-1, k) and (k, k+1).  This still does appear to leave enough overlap between frequencies to ensure reconstruction.  It seems to me that defining the bandwidth to span +-1 filters is overkill, but maybe (probably) I'm missing something here?

**Comment by lostanlen** [comment]
>  This still does appear to leave enough overlap between frequencies to ensure reconstruction. It seems to me that defining the bandwidth to span +-1 filters is overkill, but maybe (probably) I'm missing something here?

What's important for reconstruction is not so much the amount of overlap as the peak-to-trough ratio of the "Littlewood-Paley sum": that is, the sum of squared magnitudes of all frequency responses. (This peak-to-trough ratio is related to the condition number of the linear operator associated to the filter bank).

Quoting Andén and Mallat "Deep Scattering Spectrum"

<img width="569" alt="Screenshot 2021-11-15 at 17 39 26" src="https://user-images.githubusercontent.com/3943142/141819776-bb0e920d-c3aa-4828-bd7e-89295e69a863.png">

Unfortunately there is no clear consensus in the audio/wavelet community as to how what an acceptable worst-case `A(omega)` should be. Clearly, if `A(omega)=0` for some omega in the audible range, then inversion will not be possible. But once we've said that we must guarantee `A(omega)>0` for every omega, i'm not sure at to what the librosa default should be.

(for the sake of completeness i should add that Gabor filters are not very well-designed to minimize Littlewood-Paley fluctuations. Cubic splines do a much better job for that matter, at the detriment of Heisenberg time-frequency tradeoff. we can't win on every metric ...)

**Comment by bmcfee** [comment]
> What's important for reconstruction is not so much the amount of overlap as the peak-to-trough ratio of the "Littlewood-Paley sum": that is, the sum of squared magnitudes of all frequency responses.

Perfect, exactly what I needed to know.

Here's a plot of the aggregated power across filters for the current (blue) implementation (`2**(1/bpo) - 1`) and the proposed (`2**(1/bpo) - 2**(-1/bpo)` with bpo=60:

![image](https://user-images.githubusercontent.com/1190540/141822261-9eb2798b-f245-441e-bcd4-5be8256bb1bf.png)

Fmin and fmax are included for clarity.  Within the passband, it's all basically flat and centered at the bandwidth determined by the window function (hann=> ~1.5).  The proposed change doubles that, as expected since each filter is now twice as wide, but A(omega) essentially remains flat.  You do get a bit of ripple at the high end, but it's very small: eyeballing it, I'd put your alpha in the range of 0.01 or 0.001.  This comes down if you use complex128 instead of complex64, but in both cases we do see a bit of overshoot and the upper bound of 1 is violated.  I expect this is just floating point math biting us.

With bpo=12, it's a bit more severe, and you can see the roll-off kicking in before the cutoff frequency:

![image](https://user-images.githubusercontent.com/1190540/141822732-428cc760-af56-41db-abb1-0c9ba878d4a4.png)

> Unfortunately there is no clear consensus in the audio/wavelet community as to how what an acceptable worst-case `A(omega)` should be.

Going back to bpo=60, if we use the approximately disjoint filters (ie `2**(0.5/bpo) - 2**(-0.5/bpo))`) in the above plot, we get
![image](https://user-images.githubusercontent.com/1190540/141825146-65d502d0-92b9-4898-998e-ae4b2af9bb39.png)

And zooming in, it looks pretty good to me:
![image](https://user-images.githubusercontent.com/1190540/141825234-f71a1bea-df06-44d8-9958-925604170d2d.png)
with no obvious gaps in the passband.

For bpo=12, it looks as follows:
![image](https://user-images.githubusercontent.com/1190540/141825512-13e119db-b66e-41fb-9b09-395ab06a3efc.png)
zoomed in:
![image](https://user-images.githubusercontent.com/1190540/141825568-da7630df-5345-415c-848d-342eec7a01ef.png)
Definitely some ripple between filters, but it's down in the 1e-4 territory which seems acceptable to me.

**Comment by lostanlen** [comment]
> Definitely some ripple between filters, but it's down in the 1e-4 territory which seems acceptable to me.

yes, very much so. What happens if `bpo` is much lower, though? Like `bpo=3` for example (third-octave spectrograms are very common in environmental noise monitoring). I expect the ripples to be ampler

**Comment by bmcfee** [comment]
BPO=3:
![image](https://user-images.githubusercontent.com/1190540/141826768-99a14196-14f4-4274-bf79-3dcd1193df40.png)

enhanced:
![image](https://user-images.githubusercontent.com/1190540/141826826-aa46d37c-8e15-4ab4-ae9e-840c71afa09f.png)

Still pretty good IMO, though that high-end roll off is a little extreme.

**Comment by lostanlen** [comment]
🤔 are you sure that the orange and green curves are within a factor 2 of each other?

**Comment by bmcfee** [comment]
Oh they're definitely not. Green is what happens when bandwidth is calculated from the midpoints instead of the centers of neighboring filters.

**Comment by lostanlen** [comment]
Ah my bad. I misinterpreted `proposed/half` as `proposed*0.5`.

Yes, there is a gradual decay of energy in the upper octave but there's not much we can do about it considering that the filters are Gabor. Personally i can live with it

**Comment by bmcfee** [comment]
Alright.  So I think we can go ahead with a minor adaptation that uses the centered / midpoint calculation for bandwidth here?  It will still be pretty easy to revert to the <=0.8 series version by setting filter_scale and we can provide a recipe in the release notes.

I think we have a plan now, I'll try to hack this together some time soon.

**Comment by bmcfee** [comment]
Side note: the plots above were off by one bin in the fmax calculation; the rolloff isn't as bad as it looks.

Circling back to how this relates to #18: I think this will essentially resolve it, with the caveat that filter shapes (windows) are specified in the time domain here instead of the frequency domain (which is what I think @craffel originally wanted).  If you really really want to determine windows in the frequency domain, I guess that could be done by supplying a function to calculate the idft of the chosen window and use that in the time domain.  (I expect the number of people who really want that functionality could be counted on one finger, but just noting it here for posterity!)

**Comment by craffel** [comment]
Wow, 8 years on, good dedication. I imagine the reason I wrote that was because I stumbled across at least one paper that used a triangle filterbank for chroma or some such thing. It sounds like this would cover that for anyone who cares enough to do it.

**Comment by lostanlen** [comment]
>  I think @lostanlen's post above had a typo in the alpha_high calculation, where it should subtract freq[-2] not freq[-1].

Yes, sorry, i hadn't tested it. `freq[-2]` of course

**Comment by bmcfee** [comment]
Sneak preview, here's what happens when we plug in the 5-limit interval generator of #1402 to the above and compare to the ET-based frequency grid:

![image](https://user-images.githubusercontent.com/1190540/142048340-a8679c0f-3589-4a9f-ac4a-3205f0d37419.png)
(Vertical lines indicate octave boundaries.)

The JI interval set here is:
```python
[1.     , 1.06667, 1.11111, 1.125  , 1.13778, 1.18519, 1.2    ,
 1.25   , 1.28   , 1.33333, 1.35   , 1.40625, 1.42222, 1.44   ,
 1.5    , 1.6    , 1.66667, 1.6875 , 1.70667, 1.77778, 1.8    ,
 1.875  , 1.8963 , 1.92   ]
```
So where the gaps between intervals are bigger (first couple of bins) we need less frequency resolution and get away with shorter filters.  When the gaps are smaller (1.125 -> 1.13778, or 1.6666 -> 1.6875) we need higher frequency resolution and use longer filters.

**Comment by bmcfee** [comment]
And here's the same with 24-bin Pythagorean intervals included:
![image](https://user-images.githubusercontent.com/1190540/142063178-8f6e88ce-3b22-4cc6-a239-ec04dda5b6b5.png)

Zooming in on the bottom octave shows the general pattern in more detail:
![image](https://user-images.githubusercontent.com/1190540/142063385-28fa516a-2e2b-4c1d-a04d-868de39beee4.png)

Generally, Pythagorean (positive powers of 3, eg wrapped circle of fifths) hugs ET pretty closely.  The 5-limit tuning has more irregular spacing, which forces more deviations from the ET bandwidths.

**Comment by bmcfee** [comment]
One slight hiccup in implementing this refactor.  Currently, we have a bit of redundancy in the vqt function:
https://github.com/librosa/librosa/blob/65270447f4bdbf67c32ab9bb5b25eef7def84062/librosa/core/constantq.py#L877-L888
where we need to compute alpha again if `gamma=None`.  This was originally kept in the vqt function because we need it to estimate early downsampling limits here:
https://github.com/librosa/librosa/blob/65270447f4bdbf67c32ab9bb5b25eef7def84062/librosa/core/constantq.py#L904-L909

One way around this would be to have the wavelet length calculator return the max frequency cutoff, but that seems a little hacky.

As an aside: what should the gamma estimation be now if alpha is no longer constant across frequencies?  Should we have a separate gamma for each frequency?  That's easy enough to implement, but I'm not sure of the implications yet.

**Comment by lostanlen** [comment]
How about this:

0. (define freqs)

1. make the utility function return alpha instead of lengths

```python
def freq_to_alpha(freqs):
   
    if np.any(freqs <= 0):
        raise ParameterError("frequencies must be strictly positive")

    # Filters have ~1bin bandwidth centered at the current frequency
    alphas = np.empty(len(freqs))
    alphas[1:-1] = (freqs[2:]**0.5 - freqs[:-2]**0.5) / freqs[1:-1]**0.5
    
    freq_low = freqs[0]**2/freqs[1]
    alphas[0] = (freqs[1]**0.5-freq_low**0.5)/freqs[0]**0.5

    freq_high = freqs[-1]**2/freqs[-2]
    alphas[-1] = (freq_high**0.5-freqs[-2]**0.5)/freqs[-1]**0.5

    return alphas
```

2. (potentially skip this step)
```python
if gamma is None:
    gamma = 24.7 * alpha / 0.108
```

3. check gamma and filter_scale
```python
if gamma < 0:
        raise ParameterError(f"gamma={gamma} must be non-negative")
        
 
if filter_scale <= 0:
    raise ParameterError(f"filter_scale={filter_scale} must be positive")
```

4. define `Q` and `filter_cutoff`
```python
fmax_t = np.max(freqs)

# Determine Q, estimate required resampling quality
Q = float(filter_scale) / alpha
filter_cutoff = (
    fmax_t * (1 + 0.5 * filters.window_bandwidth(window) / Q) + 0.5 * gamma
)
```

5. check topmost frequency
```python
if max(freqs * (1 + 0.5 * window_bandwidth(window) / Q)) > sr / 2.0:
        raise ParameterError(f"Maximum filter frequency={max(freqs):.2f} would exceed Nyquist={sr/2}")
```

6. define lengths in terms of Q, sr, freqs, gamma, and alpha
```python
lengths = Q * sr / (freqs + gamma / alpha)
```

**Comment by bmcfee** [comment]
Yeah, that's loosely speaking what I had in mind.  A couple of caveats:

1. We can't just take the max frequency anymore, because the max frequency could have a narrower bandwidth than the one below it.  Instead, we can do something like this inside `wavelet_length`:

```python
    f_cutoff = max(freqs * (1 + 0.5 * window_bandwidth(window) / Q) + 0.5 * gamma)
    
    if f_cutoff > sr / 2.0:
        raise ParameterError(f"Filter at frequency={???:.2f} would exceed Nyquist={sr/2}")
```

(I guess we're cool with a per-frequency gamma?)

2. We actually need this `f_cutoff` in `vqt` to enable early downsampling.  Actually, it might make sense to migrate the Nyquist check out of the filter constructor and into the `vqt` function itself.  This would effectively mean that `wavelet_lengths` should return both the filter lengths and the cutoff frequency.  A little awkward, but probably a better compromise overall.

**Comment by bmcfee** [comment]
Just one more follow-up on the bandwidth calculation, this plot shows the frequency response in dB, with colors clipping at [-3, -6], for different irregularly spaced 24-bpo filterbanks: ET, Pythagorean, and JI5.  (Frequency is vertical, filter index is horizontal.)

![image](https://user-images.githubusercontent.com/1190540/142255369-4f7faf0c-ea1a-4621-9540-53ae7d31be2d.png)

Basically this shows that we do have good >=-3dB coverage of all frequencies using the geometric mean bandwidth calculation rule above.
