### ISSUE TITLE
to_mono - how to normalize it correctly

### ISSUE THREAD

**Issue by keunwoochoi** [librosa/librosa#1080]
Just saw `to_mono` use `np.mean` for downmixing the stereo (or any multiple) channels. This means practically, we almost always reduce the energy by downmixing it because it means `(left + right) / 2`instead of `(left + right) / sqrt(2)`.

As far as I know, the latter is more commonly used (if not always) in implementations where the downmixed signal is supposed to be played and - i.e., for the case of audio processing rather than analysis or information retrieval. Therefore maybe it's okay for Librosa to divide it by 2, but I think it's still a valid point to discuss. 

To say the least, I might want to make a PR so that it is mentioned in the doc :)

**Comment by dpwe** [comment]
Sqrt(2) would preserve total energy if the two channels were uncorrelated,
but in many stereo signals there is very substantial coherence between L
and R.

If L == R (often approximately true), dividing only by sqrt(2) leads to a
sqrt(2) amplitude boost of the mixdown compared to a single channel of the
original.

  DAn.

**Comment by keunwoochoi** [comment]
Yup, but shouldn't the stereo audio be produced to be robust with those... well ok I also don't do that when I make music so 🙄

Thanks for a quick reply :) I'm fine with closing this issue but will leave it for the maintainers.

**Comment by lostanlen** [comment]
thank you for such an instructive reply, DAn !
