### ISSUE TITLE
The default physical length is 23ms instead of 93ms

### ISSUE THREAD

**Issue by bojobo** [librosa/librosa#1084]
#### Description
As stated in the [documentation](https://librosa.github.io/librosa/generated/librosa.core.stft.html#librosa.core.stft) the default physical length should be 93ms. Using default values to compute the mel-spectrogram does not result in a physical window length of 93ms, but rather 23ms. 
#### Steps/Code to Reproduce
```
import librosa

# Load 5 seconds of audio example 
y, sr = librosa.load(librosa.util.example_audio_file(), duration=5)
# Calculate the melspctrogram with default values
S = librosa.feature.melspectrogram(y, sr)
# Print out shape of spectrogram
print(S.shape)
```

#### Expected Results
`print(S.shape)` should output `(128,54)` as 54*93ms = 5022ms = 5.022s
#### Actual Results
Output of the print is `(128,216)`, but 216*93ms = 20088ms = 20.088s
#### Versions
Python 3.8.2
NumPy 1.18.1
SciPy 1.4.1
librosa 0.7.2

**Comment by bmcfee** [comment]
The documentation is correct; you're forgetting to account for window overlap (75% by default).

This is why we have a `frames_to_time` conversion function, instead of multiplying directly.
