### ISSUE TITLE
Librosa.load() gives Malformed 'fmt ' chunk (worked in python3.7)

### ISSUE THREAD

**Issue by RouaL312** [librosa/librosa#1086]
data = pd.read_csv('50_speakers_audio_data/dataset4.csv')
data.head(2513)

valid_data = data[['Name','Full Path','Size','ClasseID','Fold']]

valid_data.shape

valid_data['path'] = valid_data['Fold'].astype('str')+ '/' + valid_data['Name'].astype('str')
D = [] # Dataset

for row in valid_data.itertuples():
    y, sr = librosa.load('50_speakers_audio_data/'+row.path, duration=2.97)
    ps = librosa.feature.melspectrogram(y=y, sr=sr)
    if ps.shape != (128, 128): continue
    D.append( (ps, row.ClasseID) )

**Comment by bmcfee** [comment]
redundant to #1087
