### ISSUE TITLE
Librosa.load() gives Malformed 'fmt ' chunk (worked in python3.7) 

### ISSUE THREAD

**Issue by RouaL312** [librosa/librosa#1087]
data = pd.read_csv('50_speakers_audio_data/dataset4.csv')
data.head(2513)

valid_data = data[['Name','Full Path','Size','ClasseID','Fold']]

valid_data.shape

valid_data['path'] = valid_data['Fold'].astype('str')+ '/' + valid_data['Name'].astype('str')
D = [] # Dataset

for row in valid_data.itertuples():
    y, sr = librosa.load('50_speakers_audio_data/'+row.path, duration=2.97)
    ps = librosa.feature.melspectrogram(y=y, sr=sr)
    if ps.shape != (128, 128): continue
    D.append( (ps, row.ClasseID) )
''''
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~\Anaconda3\envs\tensorflow-session\lib\site-packages\librosa\core\audio.py in load(path, sr, mono, offset, duration, dtype, res_type)
    128     try:
--> 129         with sf.SoundFile(path) as sf_desc:
    130             sr_native = sf_desc.samplerate

~\Anaconda3\envs\tensorflow-session\lib\site-packages\soundfile.py in __init__(self, file, mode, samplerate, channels, subtype, endian, format, closefd)
    628                                          format, subtype, endian)
--> 629         self._file = self._open(file, mode_int, closefd)
    630         if set(mode).issuperset('r+') and self.seekable():

~\Anaconda3\envs\tensorflow-session\lib\site-packages\soundfile.py in _open(self, file, mode_int, closefd)
   1183         _error_check(_snd.sf_error(file_ptr),
-> 1184                      "Error opening {0!r}: ".format(self.name))
   1185         if mode_int == _snd.SFM_WRITE:

~\Anaconda3\envs\tensorflow-session\lib\site-packages\soundfile.py in _error_check(err, prefix)
   1356         err_str = _snd.sf_error_number(err)
-> 1357         raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
   1358 

RuntimeError: Error opening '50_speakers_audio_data/Speaker0035/Speaker0035_000.wav': Error in WAV/W64/RF64 file. Malformed 'fmt ' chunk.

During handling of the above exception, another exception occurred:

NoBackendError                            Traceback (most recent call last)
<ipython-input-187-fbf864adcaa1> in <module>
      3 
      4 for row in valid_data.itertuples():
----> 5     y, sr = librosa.load('50_speakers_audio_data/'+row.path, duration=2.97)
      6     ps = librosa.feature.melspectrogram(y=y, sr=sr)
      7     if ps.shape != (128, 128): continue

~\Anaconda3\envs\tensorflow-session\lib\site-packages\librosa\core\audio.py in load(path, sr, mono, offset, duration, dtype, res_type)
    160         if isinstance(path, six.string_types):
    161             warnings.warn('PySoundFile failed. Trying audioread instead.')
--> 162             y, sr_native = __audioread_load(path, offset, duration, dtype)
    163         else:
    164             six.reraise(*sys.exc_info())

~\Anaconda3\envs\tensorflow-session\lib\site-packages\librosa\core\audio.py in __audioread_load(path, offset, duration, dtype)
    184 
    185     y = []
--> 186     with audioread.audio_open(path) as input_file:
    187         sr_native = input_file.samplerate
    188         n_channels = input_file.channels

~\Anaconda3\envs\tensorflow-session\lib\site-packages\audioread\__init__.py in audio_open(path, backends)
    114 
    115     # All backends failed!
--> 116     raise NoBackendError()

NoBackendError:

**Comment by bmcfee** [comment]
Thanks for raising this issue.  Could you please fill out the issue template?

From a quick inspection, I think the problem here is in the data, not librosa. Librosa offloads all audio decoding to other libraries, and if they can't handle the file in question, it's probably because the file is corrupted.

**Comment by bmcfee** [comment]
Closing this out, as it's either a data issue or upstream of us (soundfile).
