### ISSUE TITLE
v0.8.0 design: Simplify file path checking (move to Pathlib?) or remove checking on Librosa's side

### ISSUE THREAD

**Issue by NumesSanguis** [librosa/librosa#1089]
#### Description
In Librosa v0.7.1 there was a regression due to stricter filepath checking, which rejected Pathlib objects (which was fixed in v0.7.2): https://github.com/librosa/librosa/issues/1019

This fix contains a lot of if-statements, that can be removed in v0.8.0 since support for Python 2.7 is dropped: https://github.com/librosa/librosa/blob/7feb1efdbc9f0c61fbee623fc03fa62410113927/librosa/core/audio.py#L142-L164

The question however is how Librosa wants to approach file path handling:
1. Move away from strings and rewrite everything to Pathlib
2. Keep it like this, but simplify the code to `isinstance(path, (six.string_types, pathlib.PurePath))`
3. Don't do anything at all
4. Remove file path checking on Librosa's side (and use try except RuntimeError)

Personally I would suggest option 4 (in optionally with 1) as it matches Python's philosophy of not checking type and instead just try if it works (https://www.reddit.com/r/Python/comments/26irhg/why_is_type_checking_not_pythonic/).
We can just let `audioread` complain if it cannot parse the arguments it's given. In the case of `SoundFile`, no `isinstance()` checking is done.

What to do about file path checking?

**Comment by bmcfee** [comment]
I agree that we should generally err on the side of duck-typing.  However, the if statement here is intended to differentiate between different kinds of failures that are not necessarily detectable by checking the exception type.  I don't think we can safely pass file-handles to audioread and expect it to fail gracefully (though this should be verified); moreover, when we fall back to audioread from a failed decoding, the warning is issued to indicate to the user what's going on.

One possible solution here might be to take option 1, and try to cast as pathlib.  If this cast fails (ie input is not a string-like or path-like object), it will raise a new exception which we can catch and propagate upwards.  If the cast succeeds, we can still throw the warning and proceed into the audioread loader.

Does this sound reasonable?

**Comment by NumesSanguis** [comment]
You can also put Librosa in the position of the informer. Librosa will not make the call whether a given argument is acceptable or not, but it gives a warning on why it's likely to fail. Which could be done with something similar to:

```python
try:
    Path(path)
except TypeError as e:
    warnings.warn(f"Attempted to convert path argument to Path-object, but failed with error:\n{e}")
    warnings.warn("Audioread will likely fail as argument is not a Path.")

y, sr_native = __audioread_load(path, offset, duration, dtype) 
```

Also, in terms of consistency, if going for option 1, should the whole library be checked? I don't know how often string paths are used in this library.

> when we fall back to audioread from a failed decoding, the warning is issued to indicate to the user what's going on.

Small note: Currently, this warning is only shown when path passes the type check.

```python
if isinstance(path, six.string_types): 
    warnings.warn('PySoundFile failed. Trying audioread instead.') 
    y, sr_native = __audioread_load(path, offset, duration, dtype) 
else: 
    six.reraise(*sys.exc_info()) 
```

**Comment by bmcfee** [comment]
> I don't know how often string paths are used in this library.

The only times we deal with paths are `load`, `stream`, and `example_audio_file`.



> Currently, this warning is only shown when path passes the type check.

Right, because it will only try audioread if the input can be reasonably interpreted as a path (and not an open handle, which is not supported by audioread).


---
Having come back to this issue, we've already cleaned this bit of code up per the 3.6+ migration:
https://github.com/librosa/librosa/blob/164d4c641687823c915263c864bfeb44227fdb3c/librosa/core/audio.py#L140-L146

So I'm not sure that any further action on this is necessary.

**Comment by bmcfee** [comment]
Gave this some more thought, and I don't think there's anything to do here.
