### ISSUE TITLE
warnings.warn('PySoundFile failed. Trying audioread instead.')

### ISSUE THREAD

**Issue by shanethomas1029** [librosa/librosa#1097]
**OS : Ubuntu 18**

**Error :** 
/home/user/.local/lib/python3.6/site-packages/librosa/core/audio.py:161: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn('PySoundFile failed. Trying audioread instead.')
/home/user/project/deep_impression-master/anc.webm
Extraversion,Agreeableness,Conscientiousness,Neurotisicm,Openness
[0.43463087 0.49977684 0.38452235 0.4162821  0.46707755]
Gdk-Message: 18:48:09.718: ui2.py: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.

**Python File:**

import tkinter as tk
import tkinter.filedialog
from tkinter import *
from util import load_model, predict_trait
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from matplotlib.figure import Figure
from matplotlib import pyplot as plt
import numpy as np

def print_path():
    f = tkinter.filedialog.askopenfilename(
        parent=root,
        title='Choose file',
        filetypes=[("jpeg files","*.jpg"),("all files","*.*")])
    data = f
    y = predict_trait(data, model)

    label = Label(root, text="The file selected is:")
    label1 = Label(root, text=f)
    label2 = Label(root, text="\n \n The values for your personality traits are:")
    label3 = Label(root, text="Extraversion,Agreeableness,Conscientiousness,Neurotisicm,Openness")
    label4= Label(root, text=y)
    label.pack() 
    label1.pack() 
    label2.pack() 
    label3.pack() 
    label4.pack() 
    print(f)
    print('Extraversion,Agreeableness,Conscientiousness,Neurotisicm,Openness')
    print(y)
    fig = plt.figure()
    ax = fig.add_axes([0,0,1,1])
    ax.axis('equal')
    langs = ['Extraversion', 'Agreeableness', 'conscientiousness', 'Neurotisicm' , 'Openness']
    students = [y[0],y[1],y[2],y[3],y[4]]
    ax.pie(students, labels = langs,autopct='%1.2f%%')
    plt.show()
     
  #  print(f)
root = Tk()
root.geometry("800x600")
main = Tk()
photo = PhotoImage(file = "wel.png")
w = Label(root, image=photo)
w.pack()

b1 = tkinter.Button(root, text='Select the file', command=lambda:print_path())
b1.pack(fill='x')
frame = tk.Frame(root)
frame.pack()
button = tk.Button(frame, 
                   text="QUIT", 
                   fg="red",
                   command=quit)
button.pack(side=tk.LEFT)
model = load_model()

root.mainloop()

**Comment by bmcfee** [comment]
This is intended behavior, and a warning (not an error) that happens when you attempt to load a file with a format that is not supported by libsndfile.

The "Fatal IO error" that is causing your program to fail is unrelated to librosa.

**Comment by shanethomas1029** [comment]
Thank You.!
