### ISSUE TITLE
Error when using rms with magphase from stft using n_fft option.

### ISSUE THREAD

**Issue by bastian-f** [librosa/librosa#1101]
#### Description
Error when using rms with magphase from stft using n_fft option:

I am using rms on a wave file of a length of 2048 samples and when I use the rms method as described in this way it works fine:

```
S, phase = librosa.magphase(librosa.stft(y))
rms = librosa.feature.rms(S=S)
```
But when I add the option n_fft to the stft method it gives an error which it did not give with an older version of librosa:

```
S, phase = librosa.magphase(librosa.stft(y, n_fft=512))
rms = librosa.feature.rms(S=S)
```

The error I get is:

```
librosa.util.exceptions.ParameterError: Since S.shape[0] is 257, frame_length is expected to be 512 or 513; found 2048
```

#### Steps/Code to Reproduce

```
import librosa
y, sr = librosa.load(librosa.util.example_audio_file())
y = y[:2048]
S, phase = librosa.magphase(librosa.stft(y, n_fft=512))
rms = librosa.feature.rms(S=S)
```

#### Expected Results

rms calculated with success.

#### Actual Results

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bastian/miniconda3/envs/machine_learning/lib/python3.6/site-packages/librosa/feature/spectral.py", line 863, in rms
    frame_length))
librosa.util.exceptions.ParameterError: Since S.shape[0] is 257, frame_length is expected to be 512 or 513; found 2048
```

#### Versions

Linux-5.5.8-arch1-1-x86_64-with-arch
Python 3.6.10 | packaged by conda-forge | (default, Apr  6 2020, 14:52:36) 
[GCC 7.3.0]
NumPy 1.18.1
SciPy 1.4.1
librosa 0.7.2

**Comment by bmcfee** [comment]
I think this is intended behavior.  If you want to use shorter frames, you can pass `frame_length=512` to `rms` and it should work as expected.  We can't in general infer the frame length from the spectrogram shape, so rather than guess and be wrong, it throws an exception and asks you to specify exactly what the frame length was.

See #1040 for related discussion on this point.

**Comment by bastian-f** [comment]
I am very sorry for not having been able to get back later. Thank you @bmcfee, it worked!
