### ISSUE TITLE
Keyword-only arguments

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#1114]
#### Description

Since we're now a python3-only package, what do people think about moving to [keyword-only arguments](https://www.python.org/dev/peps/pep-3102/) wherever possible?

Some arguments off the top of my head:

### Pro
- Forces users to be explicit about their parameters
- Improves code readability / reduces bugs from implicit parameter ordering
- Allows us to change the ordering of keyword arguments at any point in the future without fear of breaking things for users

### Con
- Existing code using positional parameter values will break
- Code will be necessarily more verbose
- Soft support for legacy python will definitely break. (Right now, things mostly work on 2.7, but we make no promises of support.)

---
If we do this, it will need to be at a major revision point.  0.8 seems like a logical place to do it (sooner being better), but I could be convinced otherwise.

**Comment by lostanlen** [comment]
I'm 100% for it.
200% for it when librosa provides a default value
400% for it when that default value is `None` ...

**Comment by bmcfee** [comment]
Should we roll it into 0.8?

**Comment by keunwoochoi** [comment]
Sounds not bad to me, but..

> wherever possible?

when is it possible and not?

**Comment by bmcfee** [comment]
![image](https://user-images.githubusercontent.com/1190540/132237429-f1a03795-6f75-430c-af37-8ecba559dd04.png)

> when is it possible and not?

I think it's pretty much always possible.  I was initially concerned about required (currently positional) arguments, but then remembered you can do
```python
def foo(*, bar, baz=qux):
   # bar is required by name
   # baz is optional by name
   ...
```

**Comment by bmcfee** [comment]
Gave this a bit more thought, and I think we probably want to leave some functions as not (entirely) keyword-only.

Mainly I'm thinking functions like `load` where the first argument is unambiguously the thing to load, but the name we use for it (`path`) isn't always obvious or accurate (eg when loading from a stream).

Similarly, when we have uninformative placeholder names like `data` (eg in specshow, or some of the utils functions), I don't see a benefit to making the user specify that at the call site, since it conveys no additional meaning.  Is
```python
librosa.display.specshow(data=S)
```
really any better than
```python
librosa.display.specshow(S)
```
?  I'd argue that it isn't.  Note that this differs meaningfully from similar functionality in seaborn or matplotlib, where `data=S` provides an alternative interface to something like `x=foo, y=bar`, and in that case it does convey information.

**Comment by lostanlen** [comment]
> Gave this a bit more thought, and I think we probably want to leave some functions as not (entirely) keyword-only.

I agree. As i wrote earlier, the priority in my opinion would be to turn arguments defaulting to `None` as keyword.

Quizz: which of these function calls return the same value?

```python
(A) librosa.stft(y)
(B) librosa.stft(y, 2048)
(C) librosa.stft(y, 2048, None)
(D) librosa.stft(y, 2048, 2048)
(E) librosa.stft(y, 2048, 512)
(F) librosa.stft(y, 2048, None, 2048)
(G) librosa.stft(y, 2048, 2048, 2048)
(H) librosa.stft(y, 2048, 512, 2048)
(I) librosa.stft(y, 2048, 512, 512)
(J) librosa.stft(y, 2048, 512, None)
```

Answer (i hope i'm right!): `(A) == (B) == (C) == (E) == (F) == (H) == (J)` and `(D) == `(G)`

This sort of quizz would be much easier if we had
`(H) librosa.stft(y, n_fft=2048, hop_length=512, win_length=2048)`

**Comment by bmcfee** [comment]
> I agree. As i wrote earlier, the priority in my opinion would be to turn arguments defaulting to `None` as keyword-only.

Oh I'd be much more aggressive about it than that, and force it wherever the parameter under consideration has a specific meaning that's legible at the call site.  So things like `n_fft` would be kw-only, but `x` or `data` would not be.  (An exception for the latter would be in the case of multiple-dispatch functions, eg accepting *either* `(y,sr)` or `S` in feature extractors.)

The `None` thing is a bit tricky, because we use it for different reasons in different places.  Sometimes it's a placeholder for a parameter where the reasonable default value would be obtuse, dynamically constructed, or potentially passed-by-reference (window functions are a good example).  Other times, `None` means to disable an option (like in normalization).

**Comment by lostanlen** [comment]
>  So things like n_fft would be kw-only, but x or data would not be. (

Yes. It's also that if you happen to confuse `data` for `x_coords` in `specshow`, you get a `TypeError`. But if you mix `win_length` and `hop_length` in `stft`, RTTI won't help you catch that mishap.

```python
foo = 512
bar = None

S1 = librosa.stft(y, n_fft, foo, bar)
S2 = librosa.stft(y, n_fft, bar, foo)
```

`S1` and `S2` are both reasonable and yet they return very different answers.
`S1` has a hop length of 512 and a window length of 2048
`S2` has a hop length of 512 and a window length of 512

This potential confusion creates bugs which are hard to chase and fix.

I am far less worried about
```python
foo = ...
bar = ...

fig1 = specshow(foo, bar)
fig2 = specshow(bar, foo)
```

because i don't imagine a use case in which none of the calls (`fig1`,  `fig2`) would raise an error.
So making it `data=foo` or `data=bar` would "fix what's not broken" (as far as i can tell).

**Comment by bmcfee** [comment]
Yup, I think we're all in agreement.  I'll hold off on proscribing any hard rules about which args should and should not be KWO; probably this will become obvious during implementation.

**Comment by lostanlen** [comment]
What is coming to mind today is the prototype of feature extractors which may either take `y` or `S` as input. Example: `spectral_centroid` and friends, `mfcc`.

https://librosa.org/doc/main/generated/librosa.feature.mfcc.html

Do i understand correctly that all arguments of these functions should in the future be passed by name? Either `mfcc(y=foo)` or `mfcc(S=bar)`.


Whereas for the inverses, `mel_to_stft` and`mel_to_audio`, we can leave the first argument (`M`) as positional. Example:

```python
def mel_to_stft(M, sr=22050, n_fft=2048, power=2.0, **kwargs):
```

would become
```python
def mel_to_stft(M; sr=22050, n_fft=2048, power=2.0, **kwargs):
```

yes?

**Comment by bmcfee** [comment]
@lostanlen yes, that's correct.  In the inverse case, the input (M) is unambiguously a mel spectrogram, and it can never be anything else.  In the forward case, we basically have to contend with multiple dispatch, so the input is somewhat ambiguous and therefore would require keyword arguments.

I understand that this isn't 100% internally consistent: some common parameters will be kw-only in one place but not in another, but I think I'm generally okay with that when the usage is clear in context.

Did you have some particular issue in mind coming?

**Comment by lostanlen** [comment]
> Did you have some particular issue in mind coming?

No, just to make sure i understood the idea; and confirm that this would result in some asymmetry between "forward" functions like `melspectrogram` (all args are kw-only) vs. "inverse" functions like `mel_to_audio`, `mel_to_stft` (first arg may be positional, others must be kw).
