### ISSUE TITLE
DEBUG messages

### ISSUE THREAD

**Issue by srubey** [librosa/librosa#1115]
#### Description

I'm getting inundated with DEBUG messages when I run Librosa.  I'm presuming this is a problem with my Numba environment, but thought I'd ask here since I'm getting nowhere in my research.  Specifically, when I call Librosa's pitch_shift function, I get literally thousands of lines of DEBUG messages, beginning with the following:

DEBUG:numba.byteflow:bytecode dump:
           0    NOP(arg=None, lineno=10)
           2    LOAD_GLOBAL(arg=0, lineno=10)
           4    LOAD_CONST(arg=1, lineno=10)
           6    LOAD_FAST(arg=2, lineno=10)
                     ...
                     ...
label 476:
    jump 478                                 []
label 478:
    $const478.0 = const(NoneType, None)      ['$const478.0']
    $480return_value.1 = cast(value=$const478.0) ['$480return_value.1', '$const478.0']
    return $480return_value.1                ['$480return_value.1']

I've attempted the following:
import os
os.environ['NUMBA_DEBUG'] = '0'
os.environ['NUMBA_DUMP_BYTECODE'] = '0'

...but these don't seem to work.  Is this something you have experience with and might be able to comment to?  I really like Librosa's features for my little application, but the error messages are making it unusable.  Any thoughts would be much appreciated.

**Comment by lostanlen** [comment]
Hello, thanks for reporting. What version of librosa and numba are you using?
Possibly related: #157 and #1105

**Comment by srubey** [comment]
Thanks for getting back to me.  I'm using Librosa version 7.2 and Numba version 48.0.  I've tried using Numba version 49.1 as well, but that produces even more error messages.
