### ISSUE TITLE
Needs a way to set color range of spectrogram in librosa.display.specshow()

### ISSUE THREAD

**Issue by root20** [librosa/librosa#1121]
As far as I know, the color range of spectrogram can be varied according to the maximum and minimum magnitude. This is problematic when I want to compare the two spectrograms.

In matplotlib library, the color range can be fixed by setting vmax and vmin arguments. (See the link below.) And adding vmin, vmax argument to fix color range in librosa.display.specshow() in the same way will be helpful.
[https://stackoverflow.com/questions/3373256/set-colorbar-range-in-matplotlib](url)

If there is a better way to solve this problem, it will be great.

**Comment by bmcfee** [comment]
All arguments to `pcolormesh` can be passed through from specshow, so you can set vmin and vmax directly already.

**Comment by root20** [comment]
Thank you, I didn't know about that.
