### ISSUE TITLE
'fft' not in _coord_map in librosa.display.__mesh_coords

### ISSUE THREAD

**Issue by JulianFerry** [librosa/librosa#1135]
[The documentation for specshow](https://librosa.github.io/librosa/generated/librosa.display.specshow.html) mentions 'fft' as a valid frequency type for `y_axis`. However using this throws `ParameterError: Unknown axis type: fft`
I'm assuming this should be mapped to `__coord_fft_hz` in the same way as `hz`, `linear` and `log`?

**Comment by bmcfee** [comment]
How embarrassing!

Yeah, it should be an alias for `hz` or `linear`.

Thanks for catching it!
