### ISSUE TITLE
specshow: warn when frequency axis seems implausible

### ISSUE THREAD

**Issue by JulianFerry** [librosa/librosa#1136]
**Describe the bug**

`librosa.display.specshow` malfunctions for y_axis=`cqt_hz`. If I double the number of CQT bins in the example at [librosa.display.specshow](https://librosa.github.io/librosa/generated/librosa.display.specshow.html), then the y axis blows up to incorrect Hz values. If I triple it then they blow up to infinity

**Reproducible example**

```
import matplotlib.pyplot as plt
y, sr = librosa.load(librosa.util.example_audio_file())
plt.figure(figsize=(12, 8))

# Calculate CQT with twice the default frequency resolution
resolution = 2
CQT = librosa.cqt(y, sr=sr, n_bins=84*resolution, bins_per_octave=12*resolution)
CQT = librosa.amplitude_to_db(np.abs(CQT), ref=np.max)

# CQT note as y axis
plt.subplot(4, 2, 3)
librosa.display.specshow(CQT, y_axis='cqt_note')
plt.colorbar(format='%+2.0f dB')
plt.title('Constant-Q power spectrogram (note)')

# CQT Hz as y axis
plt.subplot(4, 2, 4)
librosa.display.specshow(CQT, y_axis='cqt_hz')
plt.colorbar(format='%+2.0f dB')
plt.title('Constant-Q power spectrogram (Hz)')
```

**Outputs:**
- resolution = 1 (the example in the docs)
![image](https://user-images.githubusercontent.com/24207830/83117165-08869900-a0cd-11ea-951f-82d645f1f977.png)

- resolution = 2
![image](https://user-images.githubusercontent.com/24207830/83117087-edb42480-a0cc-11ea-9770-45c0e9f548d2.png)

- resolution = 3
```
/usr/local/Caskroom/miniconda/base/envs/myproject/lib/python3.6/site-packages/librosa/core/time_frequency.py in midi_to_note(midi, octave, cents)
    601                 'G#', 'A', 'A#', 'B']
    602 
--> 603     note_num = int(np.round(midi))
    604     note_cents = int(100 * np.around(midi - note_num, 2))
    605 

OverflowError: cannot convert float infinity to integer
```

**Software versions**

```
Darwin-19.4.0-x86_64-i386-64bit
Python 3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)]
NumPy 1.18.4
SciPy 1.4.1
librosa 0.7.2
INSTALLED VERSIONS
------------------
python: 3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)]

librosa: 0.7.2

audioread: 2.1.8
numpy: 1.18.4
scipy: 1.4.1
sklearn: 0.23.1
joblib: 0.15.1
decorator: 4.4.2
six: 1.15.0
soundfile: 0.10.3
resampy: 0.2.2
numba: 0.49.1

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
sphinxcontrib.versioning: None
sphinx-gallery: None
pytest: 5.4.2
pytest-mpl: None
pytest-cov: None
matplotlib: 3.2.1
presets: None
```

**Comment by bmcfee** [comment]
This behavior is expected and correct.  If you change your CQT resolution, you also need to tell specshow that you've done so by setting the `bins_per_octave` parameter.

**Comment by JulianFerry** [comment]
Thanks for the response, but if you look again at my example, I have also multiplied bins_per_octave by the resolution.

**Comment by bmcfee** [comment]
> librosa.display.specshow(CQT, y_axis='cqt_hz')

No, you need to say `bins_per_octave=` in specshow as well.

**Comment by JulianFerry** [comment]
Yes sorry I realised after re-reading your comment that's why I deleted it!

I see, thanks. Would it perhaps be appropriate to have a warning message in `librosa.display.specshow` if the following conditions apply?
- if `bins_per_octave` hasn't been set by the user
- and `CQT.shape[0]/bins_per_octave` is larger than a reasonable number of octaves? I'm trying to figure out if is possible to estimate a reasonable number of octaves from fmin and assuming fmax would be something like 22k/2

Failing that, an error message here would help. Sorry I feel like I'm asking for too many error messages but in this case it's not immediately obvious (to me) which parameters are critical to keep across function calls and their plots or inverse. I'm happy to be proven wrong

**Comment by bmcfee** [comment]
>     * if `bins_per_octave` hasn't been set by the user

This is generally hard to detect given that we have default values.  I don't think requiring an explicit setting to avoid a warning is a good pattern here.



>     * and `CQT.shape[0]/bins_per_octave` is larger than a reasonable number of octaves?

I'm not so sure about this specific idea, but more generally I think we can do something useful here.  Eg: if the chosen parameters and input data would produce a frequency range that exceeds nyquist, that's a good sign that something is wrong and we should warn about it.  It's not foolproof, but it would catch really obvious errors.



> Sorry I feel like I'm asking for too many error messages but in this case it's not immediately obvious (to me) which parameters are critical to keep across function calls and their plots or inverse.

That's fair -- there are a lot of parameters involved, and the data structures we use (vanilla numpy ndarrays) provide no means to carry them along for the ride.  This means that it's on the user to keep track of these things, and that takes a bit of familiarity with the library and underlying methods.  I don't see any immediate technical solutions to that problem, though [presets](https://librosa.github.io/librosa/auto_examples/plot_presets.html#sphx-glr-auto-examples-plot-presets-py) can be helpful.

On the non-technical side, do you think it would help to have a documentation page that lists common pitfalls (like not carrying over analysis parameters)?  I usually find these things to be less helpful than fixing things at the API level, but not all things can (or should) be fixed at the API level IMO.

What do people think?

**Comment by JulianFerry** [comment]
> I'm not so sure about this specific idea, but more generally I think we can do something useful here. Eg: if the chosen parameters and input data would produce a frequency range that exceeds nyquist, that's a good sign that something is wrong and we should warn about it. It's not foolproof, but it would catch really obvious errors.

I didn't notice until now that the function uses a sampling rate - I agree with nyquist.

> On the non-technical side, do you think it would help to have a documentation page that lists common pitfalls (like not carrying over analysis parameters)? I usually find these things to be less helpful than fixing things at the API level, but not all things can (or should) be fixed at the API level IMO.

It could be useful... but I agree with you about making the API as straightforward as possible, or the existing docs. Here for example, a simple note in the documentation for [librosa.display.specshow](https://librosa.github.io/librosa/generated/librosa.display.specshow.html) would have helped. Something like:
```
y_axis:None or str
...
    Frequency types:
    ...

    All frequency types are plotted in units of Hz.
    For Mel and CQT scales, the parameters `fmin`, `fmax` and `hop_length`
    should be identical to those used to generate the spectrogram.
```

> the data structures we use (vanilla numpy ndarrays) provide no means to carry them along for the ride

I was actually thinking a solution could be to use classes. E.g.
- One for Spectrogram, which would track things like the sampling rate, fmin and fmax (in the case of Mel and CQT), which could have its own .plot() method with much fewer parameters.
- Add an Audio class with its own methods to display and pitch shift etc...
- Audio and Spectrogram methods would generally return an Audio or Spectrogram object

But this would be a major API overhaul which would be quite a bit of work and may be frustrating for existing users. I've also only just started using librosa so I don't want to crash the party and request a complete do-over haha

**Comment by bmcfee** [comment]
> a simple note in the documentation for [librosa.display.specshow](https://librosa.github.io/librosa/generated/librosa.display.specshow.html) would have helped.

Sure, I think that + a warning if the frequency range exceeds Nyquist would be easy and improve usability.


> I was actually thinking a solution could be to use classes.

We're not going to classes; Gael Varoquaux's [scipy 2017 keynote](https://www.youtube.com/watch?v=eVDDL6tgsv8) lays out many good arguments for why (and is full of good advice overall).
