### ISSUE TITLE
[Feature Request] cache removal

### ISSUE THREAD

**Issue by beasteers** [librosa/librosa#1139]
**Is your feature request related to a problem? Please describe.**
I'm looking into librosa cache for the first time and it looks really helpful, but I'm worried about there being no cache eviction at all which feels like it's asking for trouble.

I'm the type of person who would enable caching in my bashrc then forget about it, forget to call `librosa.cache.clear()` and then wonder why my disk space keeps filling up.

**Describe the solution you'd like**
Ideally, I'd like to be able to do something like this:

```python
import librosa
librosa.cache.enable('~/.librosa/cache', byte_limit=100*1024**2, ttl=60*60*24)
```
Though I see that with the current implementation, you can't enable caching after importing. So I guess this would be fine:
```python
import os
os.environ['LIBROSA_CACHE_DIR'] = '~/.librosa/cache'
os.environ['LIBROSA_CACHE_BYTE_LIMIT'] = str(100*1024**2)
os.environ['LIBROSA_CACHE_TTL'] = str(60*60*24)
import librosa
```

**Possible steps**
Flipping through the `joblib.Memory` implementation a bit, they have a parameter `byte_limit` already and they have a function `reduce_size` that will remove files that exceed `byte_limit`.

So the first course of action would be to add `LIBROSA_CACHE_BYTE_LIMIT` as an environment variable and find some place to call `.reduce_size()` periodically. My thought would be to call it at the end of a cached function if the time since the previous call exceeds some threshold (call reduce_size every 2 minutes) or something.

Then later for ttl, we could override the `get_cache_items_to_delete` behavior in joblib to check `datetime.now() - cache_item.last_access < os.getenv('LIBROSA_CACHE_TTL')`

I just wouldn't know how to fiddle with the `FunctionMaker` stuff.

**Describe alternatives you've considered**
I suppose one stopgap would be to automatically clear the librosa cache at the top/bottom of a script, but that feels a bit annoying and may not always be what you want to do.

**Comment by bmcfee** [comment]
I agree this would be a great feature, but I think it's better implemented in joblib.  Cache eviction policies are tricky business though, and require serious thought.  https://github.com/joblib/joblib/issues/313 works through some of the difficulties of making this work.

**Comment by beasteers** [comment]
>but I think it's better implemented in joblib.

Tbh I agree, and I'm surprised that it's not already part of the core. I was just looking at 4 years of inactivity on the issue and it seems like they just provided the `reduce_size` method and are expecting users to take it from there. 

I just don't think end users should have to think about when to trim their cache so if it could be wrapped into the cache decorator in some way that would be ideal.

I'm willing to let TTL go for now because it's not part of joblib core already.

I'd say this feature request involves 2 things:
 - add `bytes_limit=os.environ.get('LIBROSA_CACHE_BYTES_LIMIT', None),` to `librosa.cache` instantiation
 - inside `cache.__call__ ... wrapper()`, call `reduce_size` (and throttle the calls so that they aren't called too frequently).
