### ISSUE TITLE
the deference between tf.signal.stft and librosa.stft

### ISSUE THREAD

**Issue by DaerTaeKook** [librosa/librosa#1151]
I try to use tensorflow to reproduce the work of calculating Mel features. But I found that my calculation result is different from that of librosa. It is found by dubug that STFT results in different results. So I would like to consult:
How do you implement STFT?  Has the RFFT been normalized?

**Comment by bmcfee** [comment]
> How do you implement STFT?

This is probably a bigger question than you intend to ask.  There are many, many parameters that go into an STFT, and it's probably a better use of time to go into the code than to try to enumerate them all here.



>  Has the RFFT been normalized?

No, we use the unnormalized forward transform.

**Comment by DaerTaeKook** [comment]
Dear Sir：
Thanks for  your help。

发自我的iPad

在 2020年6月5日，02:37，Brian McFee <notifications@github.com> 写道：

﻿

How do you implement STFT?

This is probably a bigger question than you intend to ask. There are many, many parameters that go into an STFT, and it's probably a better use of time to go into the code than to try to enumerate them all here.

Has the RFFT been normalized?

No, we use the unnormalized forward transform.
