### ISSUE TITLE
RuntimeError: cannot cache function '__shear_dense': no locator available for file '/usr/local/lib/python3.6/dist-packages/librosa/util/utils.py'

### ISSUE THREAD

**Issue by theairbend3r** [librosa/librosa#1156]
**Describe the bug**
Cache issue on importing Librosa in a docker container when not run as root. ie. 

I get the error when I run my docker container as - `docker run -u $(id -u):$(id -g) ...`.

No error when I run - `docker run  ...`

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-989066361697> in <module>
----> 1 import librosa

~usr/local/lib/python3.6/dist-packages/librosa/__init__.py in <module>
     10 # And all the librosa sub-modules
     11 from ._cache import cache
---> 12 from . import core
     13 from . import beat
     14 from . import decompose

~usr/local/lib/python3.6/dist-packages/librosa/core/__init__.py in <module>
    123 """
    124 
--> 125 from .time_frequency import *  # pylint: disable=wildcard-import
    126 from .audio import *  # pylint: disable=wildcard-import
    127 from .spectrum import *  # pylint: disable=wildcard-import

~usr/local/lib/python3.6/dist-packages/librosa/core/time_frequency.py in <module>
      9 import six
     10 
---> 11 from ..util.exceptions import ParameterError
     12 from ..util.deprecation import Deprecated
     13 

~usr/local/lib/python3.6/dist-packages/librosa/util/__init__.py in <module>
     75 """
     76 
---> 77 from .utils import *  # pylint: disable=wildcard-import
     78 from .files import *  # pylint: disable=wildcard-import
     79 from .matching import *  # pylint: disable=wildcard-import

~usr/local/lib/python3.6/dist-packages/librosa/util/utils.py in <module>
   1823 
   1824 @numba.jit(nopython=True, cache=True)
-> 1825 def __shear_dense(X, factor=+1, axis=-1):
   1826     '''Numba-accelerated shear for dense (ndarray) arrays'''
   1827 

~usr/local/lib/python3.6/dist-packages/numba/decorators.py in wrapper(func)
    191                           **dispatcher_args)
    192         if cache:
--> 193             disp.enable_caching()
    194         if sigs is not None:
    195             # Register the Dispatcher to the type inference mechanism,

~usr/local/lib/python3.6/dist-packages/numba/dispatcher.py in enable_caching(self)
    677 
    678     def enable_caching(self):
--> 679         self._cache = FunctionCache(self.py_func)
    680 
    681     def __get__(self, obj, objtype=None):

~usr/local/lib/python3.6/dist-packages/numba/caching.py in __init__(self, py_func)
    612     def __init__(self, py_func):
    613         self._name = repr(py_func)
--> 614         self._impl = self._impl_class(py_func)
    615         self._cache_path = self._impl.locator.get_cache_path()
    616         # This may be a bit strict but avoids us maintaining a magic number

~usr/local/lib/python3.6/dist-packages/numba/caching.py in __init__(self, py_func)
    347         else:
    348             raise RuntimeError("cannot cache function %r: no locator available "
--> 349                                "for file %r" % (qualname, source_path))
    350         self._locator = locator
    351         # Use filename base name as module name to avoid conflict between

RuntimeError: cannot cache function '__shear_dense': no locator available for file '/usr/local/lib/python3.6/dist-packages/librosa/util/utils.py'
```

**To Reproduce**
`sudo apt install libsndfile1`
`pip install librosa`

```
import librosa
```

**Expected behavior**
No error should occur.

**Screenshots**
NA

**Software versions***
```
Linux-5.3.0-53-generic-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.9 (default, Apr 18 2020, 01:56:04)   [GCC 8.4.0]
NumPy 1.18.4
SciPy 1.4.1 
librosa 0.7.2 

INSTALLED VERSIONS
------------------
python: 3.6.9 (default, Apr 18 2020, 01:56:04)
[GCC 8.4.0]

librosa: 0.7.2

audioread: 2.1.8
numpy: 1.18.4
scipy: 1.4.1
sklearn: 0.23.1
joblib: 0.15.1
decorator: 4.4.2
six: 1.14.0
soundfile: 0.10.3
resampy: 0.2.2
numba: 0.49.1

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
sphinxcontrib.versioning: None
sphinx-gallery: None
pytest: None
pytest-mpl: None
pytest-cov: None
matplotlib: 3.2.1
presets: None
```

**Additional context**
 I'm using tensorflow latest-gpu-jupyter (taken from official tf website) docker image to install these packages.

**Comment by lostanlen** [comment]
Hello @theairbend3r, thank you for reporting.
Phew, this looks like a weird interaction between numba and docker/jupyter/tensorflow

Tagging @andreasjansson: perhaps you have experience on this you'd be willing to share?

**Comment by lostanlen** [comment]
Hello @theairbend3r, there's a chance that this error stems from the same cause as https://github.com/librosa/librosa/issues/1155, which you raised yesterday.
Perhaps https://github.com/librosa/librosa/pull/1107/files solves both your issues?

**Comment by theairbend3r** [comment]
To solve #1155, I pip installed Numba 0.48.0 and the warning went away.

This issue might be related to it, I'm not sure. I can't understand what the take-away from issue  #1107 is ie. what should I do to make this error go away. Is it installing a lower version of Numba?

For the current issue, is it because of some permission errors? Because I installed librosa as a root user in the docker container. When I start the container again as root, librosa works perfectly. But when I run the docker container as non-root (I get this error).

**Comment by bmcfee** [comment]
I don't think this issue is related to #1155 , but I could be mistaken.



> For the current issue, is it because of some permission errors? Because I installed librosa as a root user in the docker container.

That sounds like it's almost certainly the culprit!  Probably you can circumvent this by overriding numba's cache directory https://numba.pydata.org/numba-doc/latest/reference/envvars.html#numba-envvars-caching .. but this seems like it's a bigger problem for numba with system-wide installations.

**Comment by theairbend3r** [comment]
Yeah, I'll check that out.

**Comment by bmcfee** [comment]
@theairbend3r any progress on this one?

**Comment by theairbend3r** [comment]
Nope, I ended using it as a root user.

**Comment by bmcfee** [comment]
Ok .. well if running as root fixed it for you, I think that confirms my diagnosis, and places it out of scope for librosa.  I'll close this out, but if more people bump into this in the future, perhaps we can add a bit to the troubleshooting documentation.

**Comment by hongwenxie** [comment]
Add this to python file to solve this problem:

import os
os.environ[ 'NUMBA_CACHE_DIR' ] = '/tmp/'

**Comment by seaniedan** [comment]
Thank you for this, hongwenxie.  In case it helps anyone: I put the following in my Dockerfile:
ENV NUMBA_CACHE_DIR=/tmp/

This worked, however I get this warning, which may be useful for debugging by someone clever:
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-de97eo76 because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.

**Comment by lkaino** [comment]
I had this same issue happen in a docker container when there was no free disk space on the host system.
