### ISSUE TITLE
Librosa won't load with numba>=0.50

### ISSUE THREAD

**Issue by jakepoz** [librosa/librosa#1158]
**Describe the bug**
Setup a fresh environment Python 3.8, and pip install librosa, and just try to import librosa
Numba just released version 0.50.0: https://pypi.org/project/numba/#history which is breaking things

```python
  File "/usr/local/lib/python3.8/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/usr/local/lib/python3.8/site-packages/librosa/core/__init__.py", line 125, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.8/site-packages/librosa/core/time_frequency.py", line 12, in <module>
    from ..util.deprecation import Deprecated
  File "/usr/local/lib/python3.8/site-packages/librosa/util/__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.8/site-packages/librosa/util/utils.py", line 15, in <module>
    from .decorators import deprecated
  File "/usr/local/lib/python3.8/site-packages/librosa/util/decorators.py", line 9, in <module>
    from numba.decorators import jit as optional_jit
ModuleNotFoundError: No module named 'numba.decorators'
```

**Additional context**
Librosa works fine with numba 0.49.1 for me.

**Comment by bmcfee** [comment]
Thanks for reporting, but this issue has already been fixed and will be included in the next release.

**Comment by jakepoz** [comment]
Thanks @bmcfee , do you know when the next release will go out on pypi?

**Comment by bmcfee** [comment]
We usually do a major release around July, so hopefully we can stick to the target.

**Comment by jakepoz** [comment]
Is there something we can do to pin the current version of numba to < 0.50 until that release? Currently install librosa on a fresh python environment leads to an error:
```
conda create -n test python=3.8
conda activate test
python
import librosa
```

I can submit a PR if that would help.

**Comment by bmcfee** [comment]
> Is there something we can do to pin the current version of numba to < 0.50 until that release? Currently install librosa on a fresh python environment leads to an error:

You can pin your own environment, but we won't be putting out a release just for this issue.
