### ISSUE TITLE
Invariant features to compare pronunciation

### ISSUE THREAD

**Issue by trypag** [librosa/librosa#1163]
Hello,

New user here, 100% unfamiliar with audio processing :)
Asking for an advice : I would like to measure similarity between two pronunciations of the same word (it's not voice recognition, rather audio comparison), I am afraid age and/or gender can have too much influence on the result. So far I used mfcc features + dtw, it works fine on my own voice and not tested on others yet. 
Some of you with experience in the audio processing field might bring some smart ideas. Do you have recommendations on which features / approaches would work best ?

EDIT :
mfcc + dtw clearly not able to match pronunciations of small words on male / female samples. Any help welcomed ^^

Thanks :)

**Comment by lostanlen** [comment]
This kind of question would be better targeted at a research mailing list such as AUDITORY
http://auditory.org/

Also see the lab of Björn Schuller at TU Münich, notably the OpenSMILE software
https://www.audeering.com/opensmile/

**Comment by trypag** [comment]
Thanks for the feedback, that's really appreciated !

**Comment by mehdimashayekhi** [comment]
@trypag I am working on similar problem, do you mind sharing your code ?

**Comment by trypag** [comment]
Sorry this project was killed due to poor performances, it revealed to be a
real challenge to compare word pronunciations of my own voice.
