### ISSUE TITLE
LUFS?

### ISSUE THREAD

**Issue by jsl303** [librosa/librosa#1167]
Is there a function to calculate LUFS using librosa?

**Comment by bmcfee** [comment]
No, there is not.  LUFS is a rather delicate operation to implement, but I wouldn't be opposed to adding it in the future.

Meanwhile, your best bet is probably to use the implementation provided in sox.

**Comment by lostanlen** [comment]
@jsl303 no, there isn't. I recommend using Justin Salamon's `scaper`:

See `scaper.audio.get_integrated_lufs`
https://github.com/justinsalamon/scaper/blob/master/scaper/audio.py#L58

**Comment by jsl303** [comment]
Thanks for the suggestion! It would be awesome for Librosa to have pure 
python lufs!

**Comment by bshall** [comment]
@jsl303, there also is [pyloudnorm](https://github.com/csteinmetz1/pyloudnorm), which is pure python. I haven't used it extensively so I can't vouch for it, but it might be worth checking out.

**Comment by jsl303** [comment]
Wow, that's awesome! Thanks for that. It can even normalize to target 
LUFS. Exactly what I was looking for!
