### ISSUE TITLE
Issue in example code for LPC

### ISSUE THREAD

**Issue by HBadertscher** [librosa/librosa#1169]
**Describe the bug**
The second example of `librosa.core.lpc` shows how to create the LPC estimate of a time series:
```
>>> a = librosa.lpc(y, 2)
>>> y_hat = scipy.signal.lfilter([0] + -1*a[1:], [1], y)
```
For this, one has to create a vector `[0, -a[1], -a[2], ...]`. However, this doesn't happen here, instead a vector `[-a[1], -a[2], ...]` is created.

The reason is that `List + List` is a concatenation (which is what we want here), but `List + NumPy Array` converts the List to a NumPy Array first, thus adding 0 to each element. The estimated filter coefficients of `librosa.core.lpc` are a NumPy Array. Simple example:
```
>>> a = np.array([1, 2, 3])
>>> [0] + a
array([1, 2, 3])
```
Possible solutions would be:

1) Convert the NumPy Array to a List, then the plus operator will perform concatenation:
```
>>> [0] + a.tolist()
[0, 1, 2, 3]
```
2) Use the `np.hstack` function:
```
>>> np.hstack([[0], a])
array([0, 1, 2, 3])
```

**To Reproduce**
The effect of this can be seen best when using LPC to estimate a sinusoidal signal:
```
import librosa
import numpy as np
import scipy
import matplotlib.pyplot as plt

y = np.sin(2.0 * np.pi * 0.1 * np.arange(100))
a = librosa.lpc(y, 2)
y_hat_old = scipy.signal.lfilter([0] + -1*a[1:], [1], y)
y_hat_new = scipy.signal.lfilter(np.hstack([[0], -1*a[1:]]), [1], y)

plt.figure()
plt.plot(y, '-*')
plt.plot(y_hat_old, '--*')
plt.plot(y_hat_new, ':*')
plt.legend(['y', 'y_hat_old', 'y_hat-new'])
plt.show()
```
The resulting plot is:
![LPC Issue Plot](https://user-images.githubusercontent.com/2952672/84860873-26ae3c00-b070-11ea-8d8c-6588fd9005cb.png)

**Expected behavior**
I'd expect `y_hat` to exactly match `y` after the transient-in at the beginning. With the proposed new code, this happens. With the existing code, `y_hat` has an offset in the time-domain by one sample, making the resulting signal appear "too early".

**Software versions***
```
>>> import platform; print(platform.platform())
Linux-4.15.0-106-generic-x86_64-with-Ubuntu-18.04-bionic
>>> import sys; print("Python", sys.version)
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.18.5
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.4.1
>>> import librosa; print("librosa", librosa.__version__)
librosa 0.7.2

>>> librosa.show_versions()
INSTALLED VERSIONS
------------------
python: 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]

librosa: 0.7.2

audioread: 2.1.8
numpy: 1.18.5
scipy: 1.4.1
sklearn: 0.23.1
joblib: 0.15.1
decorator: 4.4.2
six: 1.15.0
soundfile: 0.10.3
resampy: 0.2.2
numba: 0.48.0

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
sphinxcontrib.versioning: None
sphinx-gallery: None
pytest: None
pytest-mpl: None
pytest-cov: None
matplotlib: 3.2.1
presets: None
```

Thanks for the nice library! Best regards.

**Comment by bmcfee** [comment]
Thanks for catching this! I'll be sure to include a fix in the next documentation audit.

**Comment by HBadertscher** [comment]
Great, thanks a lot!
