### ISSUE TITLE
Change default bins_per_octave in chroma_cqt?

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#1170]
The `chroma_cqt` function has a default of 12 bins per octave in its underlying CQT call.  This produces a pretty noisy chroma feature, which can be significantly cleaned up by increasing the CQT resolution, as documented in our chroma example notebook.  For example:

```python
y, sr = librosa.load(librosa.ex('nutcracker'), duration=5, offset=10)
C12 = librosa.feature.chroma_cqt(y=y, sr=sr)
C24 = librosa.feature.chroma_cqt(y=y, sr=sr, bins_per_octave=24)
C36 = librosa.feature.chroma_cqt(y=y, sr=sr, bins_per_octave=36)
```
produces the following:
![image](https://user-images.githubusercontent.com/1190540/85144328-053c8400-b219-11ea-99ac-5414cb2ca62f.png)
(**EDIT: updated 2020-06-19 to correct the third plot**)

What do folks think about increasing the default resolution in 0.8?  I see no downside to this, other than a slight break of backward compatibility.  But it seems worth it to me.

**Comment by lostanlen** [comment]
> "We can correct for minor tuning deviations by using 3 CQT bins per semi-tone, instead of one"

I'm not sure how this works? This is relegated to a separate function, `cq_to_chroma`, whose docstring doesn't explain how it corrects tuning. Is there something nonlinear in the way CQT bins are aggregated? Or is it an effect of having longer in time (finer in bandwidth) time--frequency atoms before taking the modulus?

**Comment by bmcfee** [comment]
> whose docstring doesn't explain how it corrects tuning.

Tuning correction is just a shift of the filters.



> Is there something nonlinear in the way CQT bins are aggregated?

Nope, it's (by default) a simple box filter in the freq domain to aggregate CQ bins.



> Or is it an effect of having longer in time (finer in bandwidth) time--frequency atoms before taking the modulus?

That's almost certainly it.
