### ISSUE TITLE
Why are features at STFT based upon n_fft and not fft_size?

### ISSUE THREAD

**Issue by turian** [librosa/librosa#1174]
**Describe the bug**

https://librosa.org/librosa/generated/librosa.core.stft.html

'n_fft:int > 0 [scalar]
length of the windowed signal after padding with zeros. The number of rows in the STFT matrix D is (1 + n_fft/2). The default value, n_fft=2048 samples, corresponds to a physical duration of 93 milliseconds at a sample rate of 22050 Hz, i.e. the default sample rate in librosa. '

How can n_fft=2048 samples, corresponds to a physical duration of 93 milliseconds at a sample rate of 22050 Hz unless you assume n_samples = 190464?

Or is n_fft actually the fft_size, which would in fact correspond to 93 ms per window? Is the documentation wrong?

https://librosa.org/librosa/glossary.html indicates that n_fft is the window_size. But with 2.5 seconds or 22050 Hz audio, we get 109 frames from every feature extractor (except fourier_tempogram which bizarrely has 110 frames), using the default params for every feature extractor. This corresponds to 505.7339 as the window_size, which doesn't make sense to us.

Expected behavior
The documentation should be updated to describe the behavior of n_fft assuming different audio lengths, or changed to fft_size.

If I use `512` or `2048` with 2.533 sec of audio, I shouldn't have 109 windows for both. But I do:

```
        if feat in [chroma_cqt, chroma_cens]:
            z = feat(x, window=512)
        elif feat in [rms, zero_crossing_rate]:
            z = feat(x, frame_length=512)
        elif feat in [tonnetz]:
            z = feat(x, chroma=chroma_cqt(x, window=512))
        else:
            z = feat(x, n_fft=512)
```
and I get 109 windows, same as if I change this to 2048. However, I expect the number of windows to change.

**Software versions**
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.7 (default, Mar 10 2020, 15:43:03)
[Clang 11.0.0 (clang-1100.0.33.17)]
NumPy 1.18.5
SciPy 1.4.1
librosa 0.7.2
INSTALLED VERSIONS
python: 3.7.7 (default, Mar 10 2020, 15:43:03)
[Clang 11.0.0 (clang-1100.0.33.17)]

librosa: 0.7.2

audioread: 2.1.8
numpy: 1.18.5
scipy: 1.4.1
sklearn: 0.22.2.post1
joblib: 0.15.1
decorator: 4.3.0
six: 1.15.0
soundfile: 0.10.2
resampy: 0.2.2
numba: 0.43.0

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
sphinxcontrib.versioning: None
sphinx-gallery: None
pytest: None
pytest-mpl: None
pytest-cov: None
matplotlib: 3.2.1
presets: None

**Additional context**
We want to change all https://librosa.org/librosa/feature.html feature extractors to extract 100ms windows.

**Comment by bmcfee** [comment]
> How can n_fft=2048 samples, corresponds to a physical duration of 93 milliseconds at a sample rate of 22050 Hz unless you assume n_samples = 190464?
> 
> Or is n_fft actually the fft_size, which would in fact correspond to 93 ms per window? Is the documentation wrong?

Yes, it's the *n*umber of samples per *fft*.  I don't think the documentation is wrong, but it could perhaps be worded more carefully.


> https://librosa.org/librosa/glossary.html indicates that n_fft is the window_size. But with 2.5 seconds or 22050 Hz audio, we get 109 frames from every feature extractor (except fourier_tempogram which bizarrely has 110 frames), using the default params for every feature extractor. This corresponds to 505.7339 as the window_size, which doesn't make sense to us.

I think you're forgetting to account for the hop.  The FFT size controls the duration of each frame, but not (directly) how much overlap there is between successive frames.  Without that information, you can't convert between # frames and signal or frame duration.

Also note that tempogram features are different from things like chroma or mel.  Tempograms are derived from analysis of the spectrograms. typically operating in much longer windows (~8-9 seconds per "frame").



> We want to change all https://librosa.org/librosa/feature.html feature extractors to extract 100ms windows.

I don't think that's a good idea for tempo features, as that would only be able to measure tempi >= 600bpm.  For every other feature, it already uses ~93ms windows, so there's nothing to do here.

**Comment by bmcfee** [comment]
One more point: CQT features (e.g. chroma_cqt) do not use fixed window lengths, but adapt the window length for each analysis frequency.  You can of course change the hop length though, and this is what actually controls the output frame rate.

> or changed to fft_size.

We're not changing the parameter name.

**Comment by turian** [comment]
Okay thank you, I understand.

So what I want to adjust is hop_size. And when it comes to window:

"Smaller values improve the temporal resolution of the STFT (i.e. the ability to discriminate impulses that are closely spaced in time) at the expense of frequency resolution (i.e. the ability to discriminate pure tones that are closely spaced in frequency). This effect is known as the time-frequency localization tradeoff and needs to be adjusted according to the properties of the input signal y."

I understand about the tempo features.

By the way, all of the spectral features except tonnetz have hop_length. Why can tonnetz not use this parameter? It seemed fixed at 512.

**Comment by lostanlen** [comment]
> By the way, all of the spectral features except tonnetz have hop_length. Why can tonnetz not use this parameter? It seemed fixed at 512.

That's a good point. It would be good to have hop_length as a kwarg in tonnetz, if only for the sake of consistency.

**Comment by turian** [comment]
Would you like me to close this, and file it as a separate issue?

**Comment by bmcfee** [comment]
>  It would be good to have hop_length as a kwarg in tonnetz, if only for the sake of consistency.

Yes, in general I think we should set this up to do pass-thru kwargs for the underlying chroma extraction.



> Would you like me to close this, and file it as a separate issue?

Nah, we can keep it linked to this issue since it's a minor thing.  Thanks for catching it!

**Comment by bagustris** [comment]
I got this warning which I believe is related to discussion in this issue.

~~~
tonnetz = np.mean(librosa.feature.tonnetz( 
    ...:         y=librosa.effects.harmonic(X), sr=sample_rate).T, axis=0)      
/home/bagus/.local/lib/python3.7/site-packages/librosa/core/spectrum.py:224: UserWarning: n_fft=512 is too small for input signal of length=361
  n_fft, y.shape[-1]
~~~

I set n_fft for STFT to 1024 but it seems there is no n_fft argument for tonnetz.
As in other features, it would be beneficial if we can add arguments for tonnetz including n_fft.

**Comment by bmcfee** [comment]
Tonnetz is not directly STFT-based; it uses chroma, which in turn uses CQT with varying frame lengths.  This is why it does not have a parameter for setting the frame size.
