### ISSUE TITLE
decorators.py update for numba structure change

### ISSUE THREAD

**Issue by artibyrd** [librosa/librosa#1177]
**numba.decorators** has changed names to **numba.core.decorators** in the latest version.
decorators.py needs to be updated to reflect this change to work with the current version of numba.

**Comment by artibyrd** [comment]
Found here:
https://github.com/deezer/spleeter/issues/419

Appears to be a change after numba version 0.48

**Comment by stuartarchibald** [comment]
Think this was fixed here https://github.com/librosa/librosa/pull/1164 ?

**Comment by bmcfee** [comment]
Yes, this has been reported several times and already fixed.
