### ISSUE TITLE
A way of forcing to use Audioread

### ISSUE THREAD

**Issue by vlavorini** [librosa/librosa#1181]
**Is your feature request related to a problem? Please describe.**
When I load an mp3, I get the warning `UserWarning: PySoundFile failed. Trying Audioread instead.`

**Describe the solution you'd like**
Instead of just silencing the warning, force the loading process to use Audioread via a flag (ex. `librosa.load(filename, audioread=True)`)

**Describe alternatives you've considered**
Just telling python to ignore the warnings

**Additional context**
Not needed

**Comment by bmcfee** [comment]
Thanks for the suggestion.  I understand that the warnings are annoying, but I'd prefer to not add to the API just to work around them.

Our longer term plan is to drop audioread support once libsndfile gets mp3 support, at which point this issue will go away.  So in the meantime, I think suppressing the warnings (via filter) is the best solution.

**Comment by vlavorini** [comment]
Ok, Thank you!
