### ISSUE TITLE
Display module not available

### ISSUE THREAD

**Issue by Anriod** [librosa/librosa#1184]
**Describe the bug**
In both versions 0.7 and 0.7.2 it tells me that librosa has no attribute display. I've installed via pip.

**To Reproduce**
<!--
Example:
```
import librosa

librosa.display.specshow(D, y_axis='linear')
-->
Expected behavior : 
Displays spectogram
Actual behaviour: 
`AttributeError: module 'librosa' has no attribute 'display
`

```

import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import librosa; print("librosa", librosa.__version__)
librosa.show_versions()
Darwin-18.7.0-x86_64-i386-64bit
Python 3.6.8 (default, Jan 13 2019, 14:36:45) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.4)]
NumPy 1.16.4
SciPy 1.4.1
librosa 0.7.0
INSTALLED VERSIONS
------------------
python: 3.6.8 (default, Jan 13 2019, 14:36:45) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.4)]

librosa: 0.7.0

audioread: 2.1.6
numpy: 1.16.4
scipy: 1.4.1
sklearn: 0.21.2
joblib: 0.13.2
decorator: 4.3.0
six: 1.12.0
soundfile: 0.10.3
resampy: 0.2.2
numba: 0.43.1

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
sphinxcontrib.versioning: None
sphinx-gallery: None
pytest: None
pytest-mpl: None
pytest-cov: None
matplotlib: 3.0.1
presets: None

```

**Comment by lostanlen** [comment]
Hello @Anriod,

`import librosa.display` will solve your problem. The display submodule is not imported automatically because it has matplotlib as an external dependency, unlike the rest of the library.

I hope this helps!

**Comment by Anriod** [comment]
Thanks!
