### ISSUE TITLE
ValueError: cannot reshape array of size 15183 into shape (1,8000,1)

### ISSUE THREAD

**Issue by moataz-beheta** [librosa/librosa#1188]
I am building a speech recognition model

after training the model with .wav file (mono)(16000 sampling rate)
I tried to test it using a recorded audio
the recorded audio's parameter was like the parameter of the audio files which with the model was trained (.wav file) (mono)(16000 sampling rate) and the length is 1 sec

but I got this error
```
Traceback (most recent call last):
  File "Testing.py", line 21, in <module>
    print(predict(samples))
  File "Testing.py", line 13, in predict
    prob=model.predict(audio.reshape(1,8000,1))
ValueError: cannot reshape array of size 15183 into shape (1,8000,1)
```
this is the code used for testing

```
model=load_model('/home/moataz-beheta/Desktop/speech/Model/best_model.hdf5')
filepath='/home/moataz-beheta/Desktop/speech/input/Testing'
def predict(audio):
    prob=model.predict(audio.reshape(1,8000,1))
    index=np.argmax(prob[0])
    return classes[index] #return labels

#reading the voice commands
samples, sample_rate = librosa.load(filepath + '/' + 'PTT-20200625-WA0035.wav', sr = 16000)
samples = librosa.resample(samples, sample_rate, 8000)
ipd.Audio(samples,rate=8000)  
print(predict(samples))
```

so how can I solve it ?

**Comment by bmcfee** [comment]
The problem appears to be that the file in question is longer than exactly one second (8000 samples at your target sampling rate).

**Comment by moataz-beheta** [comment]
So if I putted the sampling rate as a variable depending on the length, for example if the length is 2 sec, so the sampling is 16000, if 3 sec, so sampling 24000
this will work ?

**Comment by bmcfee** [comment]
> So if I putted the sampling rate as a variable depending on the length, for example if the length is 2 sec, so the sampling is 16000, if 3 sec, so sampling 24000
> this will work ?

I'm not really sure what you're trying to accomplish here.  It sounds like you have some model trained on one-second fragments of audio at a particular rate (8KHz), and it can only accept inputs of exactly that length.

If my read is correct, then you should always resample to the rate expected by the model, and if you have too many samples, just crop the input (`audio[:8000]`) or stride through it (`audio[0:8000], audio[8000:16000], ...`).  Changing the sampling rate to match the target number of samples will fundamentally change the sound, and your model probably won't work.
