### ISSUE TITLE
improved chroma features

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#12]
Include some other chroma variants, as described in [Mueller and Ewert, 2011](http://ismir2011.ismir.net/papers/PS2-8.pdf):
- [x] Pitch
- [x] Chroma
- [x] CENS
- [ ] CRP
- [ ] LBC [Ni, Y.; McVicar, M.; Santos-Rodriguez, R.; De Bie, T., 2012](http://arxiv.org/pdf/1107.4969)

**Comment by stefan-balke** [comment]
Is this still of any interest? I have something for the CENS features.

**Comment by vahndi** [comment]
CENS and CRP features would be useful imo

**Comment by bmcfee** [comment]
Sure.  I'm for it as long as we can provide numerical regression tests against the chroma toolbox implementations, as is done for the METlab features.

When I last looked into this, it seemed like the chroma toolbox code wasn't factored in such a way as to make this easy, but it shouldn't be impossible either.

**Comment by stefan-balke** [comment]
Okay, the chroma toolbox delivers "pitch features" (logarithmic freq. axis with 12 bands per octave) using filterbanks.
For numerical regression tests, we could go with CQT features from librosa.
Load them in Matlab and calculate the chroma features.
I think that might be the hardest part to compare.

I'm not too familiar with CQT and the comparison to the filters used in the chroma toolbox.

**Comment by bmcfee** [comment]
> Okay, the chroma toolbox delivers "pitch features" (logarithmic freq. axis with 12 bands per octave) using filterbanks.

Do you mean filters applied to STFT?

> For numerical regression tests, we could go with CQT features from librosa.

I'm guessing it'll be easier to go the other direction: save the intermediate representation (ie spectrogram) from chroma toolbox and make that the input to the python implementation.  That way, you're comparing apples to apples and isolating the filter and post-processing instead of the low-level dsp.  This is how most of the rastamat regression tests are set up

Of course, the best option would be to perfectly simulate the chroma toolbox operations all the way through, that way you don't have to modify any matlab code.  I got this to work out with the metlab code ([see here](https://github.com/bmcfee/librosa/blob/master/tests/test_met_features.py#L29-L41)), though it wasn't exactly easy.

**Comment by stefan-balke** [comment]
> Do you mean filters applied to STFT?
No.
The chroma toolbox takes the time domain.
Loads filter coefficients for all musical pitches.
And convolves it with the time domain signal.

For the chroma toolbox the following pipeline is used :
wav_to_audio(): downsample and downmix to mono
audio_to_pitch_via_FB (): apply filterbank as described above
{pitch_to_chroma(), pitch_to_CENS(), pitch_to_CRP()}

So we could take the output from audio_to_pitch() which is a 120xN matrix (N varies with features per second) and put this into the librosa CENS/CRP computation.

**Comment by bmcfee** [comment]
Oh, I see.  Sorry, it's been a while since I read the paper! :)

In that case, yeah, caching the ``audio_to_pitch()`` output and feeding it into the python routines as a CQT matrix makes sense.

**Comment by stefan-balke** [comment]
Okay, one last thing:
There are two Chroma versions in librosa (chroma_cqt and chroma_stft).
CENS and CRP are just post processing steps to normal Chroma features.
Should those live in `spectral.py` and take a Chroma matrix as input?

**Comment by bmcfee** [comment]
> Okay, one last thing:
> There are two Chroma versions in librosa (chroma_cqt and chroma_stft).
> CENS and CRP are just post processing steps to normal Chroma features.
> Should those live in spectral.py and take a Chroma matrix as input?

Good question.  There's precedent for chroma-post-processing in the ``tonnetz()`` function, but I'm not sure it makes sense in this context.  Since the whole point of this stuff is to implement specific forms of dynamic range and normalization, it makes sense to push the interface toward input as raw as possible.  I worry that allowing a ``chroma`` input here will encourage users to pass the (default) output of ``chroma_cqt`` into ``cens`` and get garbage out due to the default max-normalization.

Also, for consistency's sake, I think providing the usual ``(y, sr) || C`` interface makes sense here, and conveys the right calling semantics.

**Comment by stefan-balke** [comment]
All right,
will put this on my Dagstuhl Todo. :)

**Comment by bmcfee** [comment]
I think merging #320 gets us enough of the way there to close this out.  LBC and CRP would be nice, but I don't see them as completely necessary.  Any objections?

**Comment by stefan-balke** [comment]
> Any objections?

I hope adding more features from the Chroma toolbox is now easier since the infrastructure of generating the test data is there. CRP is a little magic anyway... :)

**Comment by bmcfee** [comment]
Well, I'm in no particular hurry to implement CRP or LBC, since they both behave pretty differently from the other chroma features.  Maybe we can punt the remaining features down the road?

**Comment by bmcfee** [comment]
It's been 3 years since the last comment on this issue.  I think it's safe to say that there isn't much interest in pursuing it further.  Shall we close it out?

**Comment by stefan-balke** [comment]
Yes, close please.
