### ISSUE TITLE
Librosa seems to write files with `y.dtype=float64` default.

### ISSUE THREAD

**Issue by texzone** [librosa/librosa#1200]
***BEFORE POSTING A BUG REPORT*** Please look through [existing issues (both open and closed)](https://github.com/librosa/librosa/issues?q=is%3Aissue) to see if it's already been reported or fixed!

**Describe the bug**
One of the options that librosa offers is to load a audio time series' `dtype` as a certain type (usually only 'float32' or 'float64' works for writing which is understandable). However, I have noticed that when I alter a `y` to be of `dtype=float32`, once loading the file, it is in `float64`. My question is: does librosa actually write the file as float64 regardless using my machine, or does it just load the file as float64?

Look at the code below to display what I mean:

**To Reproduce**

Example:
```
y, sr = librosa.load("audio_file", mono=False, sr=None, dtype='float32')
print(y.dtype) # float32
librosa.output.write_wav("output_audio_path", y, sr)
y, sr = librosa.load("output_audio_path", mono=False, sr=None, dtype=None)
print(y.dtype) #float64
```

I load the file to be dtype=float32, and verify that it is, but when I write the file and load it again (this time saying dtype=None to avoid any modification), it loads `y` with `dtype=float64`. Why is that?

**Expected behavior**
I think I've clearly explained?

**Software versions***

Please run the following Python code snippet and paste the output below.
```
Linux-4.15.0-108-generic-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]
NumPy 1.18.5
SciPy 1.4.1
librosa 0.7.2
INSTALLED VERSIONS
------------------
python: 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]

librosa: 0.7.2

audioread: 2.1.8
numpy: 1.18.5
scipy: 1.4.1
sklearn: 0.23.1
joblib: 0.15.1
decorator: 4.4.2
six: 1.15.0
soundfile: 0.10.3
resampy: 0.2.2
numba: 0.49.1

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
sphinxcontrib.versioning: None
sphinx-gallery: None
pytest: 5.4.3
pytest-mpl: None
pytest-cov: None
matplotlib: None
presets: None
```

**Additional context**
If the file that I'm using matters, it does that with everything, but here is a file that I use that the problem occurs with (you can download anything): https://file-examples.com/index.php/sample-audio-files/

**Comment by bmcfee** [comment]
The `output` module was deprecated in 0.7 and has already been removed for the upcoming 0.8 release.

Is it possible to produce this behavior by using a different output mechanism, eg soundfile.write?

**Comment by texzone** [comment]
Thank you for the prompt response. I will try and let you know
