### ISSUE TITLE
File contains data in an unknown format (.wav format). librosa 0.7.2

### ISSUE THREAD

**Issue by NoeMelo** [librosa/librosa#1201]
My code:

x,sr = librosa.load("temp.wav")
--------------------------------------------

The Error:

C:\Users\nnn\miniconda3\envs\nnn\lib\site-packages\librosa\core\audio.py:161: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn('PySoundFile failed. Trying audioread instead.')

RuntimeError                              Traceback (most recent call last)
~\miniconda3\envs\tesis\lib\site-packages\librosa\core\audio.py in load(path, sr, mono, offset, duration, dtype, res_type)
    128     try:
--> 129         with sf.SoundFile(path) as sf_desc:
    130             sr_native = sf_desc.samplerate

~\miniconda3\envs\tesis\lib\site-packages\soundfile.py in __init__(self, file, mode, samplerate, channels, subtype, endian, format, closefd)
    628                                          format, subtype, endian)
--> 629         self._file = self._open(file, mode_int, closefd)
    630         if set(mode).issuperset('r+') and self.seekable():

~\miniconda3\envs\tesis\lib\site-packages\soundfile.py in _open(self, file, mode_int, closefd)
   1182             raise TypeError("Invalid file: {0!r}".format(self.name))
-> 1183         _error_check(_snd.sf_error(file_ptr),
   1184                      "Error opening {0!r}: ".format(self.name))

~\miniconda3\envs\tesis\lib\site-packages\soundfile.py in _error_check(err, prefix)
   1356         err_str = _snd.sf_error_number(err)
-> 1357         raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
   1358 

RuntimeError: Error opening 'temp.wav': File contains data in an unknown format.

During handling of the above exception, another exception occurred:

NoBackendError                            Traceback (most recent call last)
<ipython-input-2-0be943c72b9c> in <module>
----> 1 x,sr = librosa.load("temp.wav")

~\miniconda3\envs\tesis\lib\site-packages\librosa\core\audio.py in load(path, sr, mono, offset, duration, dtype, res_type)
    160         if isinstance(path, six.string_types):
    161             warnings.warn('PySoundFile failed. Trying audioread instead.')
--> 162             y, sr_native = __audioread_load(path, offset, duration, dtype)
    163         else:
    164             six.reraise(*sys.exc_info())

~\miniconda3\envs\tesis\lib\site-packages\librosa\core\audio.py in __audioread_load(path, offset, duration, dtype)
    184 
    185     y = []
--> 186     with audioread.audio_open(path) as input_file:
    187         sr_native = input_file.samplerate
    188         n_channels = input_file.channels

~\miniconda3\envs\tesis\lib\site-packages\audioread\__init__.py in audio_open(path, backends)
    114 
    115     # All backends failed!
--> 116     raise NoBackendError()

NoBackendError:

**Comment by lostanlen** [comment]
Hello @NoeMelo. Could you share your file `temp.wav`? Does it open normally on an audio browsing software?

**Comment by NoeMelo** [comment]
Hi. I can play this audio (temp.wav) in a music player, I can even load it from the Google Colab platform using the Librosa 0.6.3. But I can't load it on my laptop, I get an error.

I have loaded the compressed audio (temp.wav) in .zip (temp.zip)

Thank you very much!

[temp.zip](https://github.com/librosa/librosa/files/4868688/temp.zip)

**Comment by bmcfee** [comment]
The problem is that your file is not a .wav, but a .webm with the wrong filename extension:

```
$ file temp.wav 
temp.wav: WebM
$ soxi temp.wav 
soxi FAIL formats: can't open input file `temp.wav': WAVE: RIFF header not found
```
