### ISSUE TITLE
librosa does not work with numba. v 0.49 and higher

### ISSUE THREAD

**Issue by anandaswarup** [librosa/librosa#1202]
***BEFORE POSTING A BUG REPORT*** Please look through [existing issues (both open and closed)](https://github.com/librosa/librosa/issues?q=is%3Aissue) to see if it's already been reported or fixed!

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Software versions***

**Additional context**

**Comment by bmcfee** [comment]
1. Please fill out the issue template.
2. Please *read* the issue template.
3. Please follow directions: this issue has been reported many times over, and long since fixed in the development branch.
