### ISSUE TITLE
NameError: 'librosa' is not  defined

### ISSUE THREAD

**Issue by Anirudh-Srinivasan** [librosa/librosa#1206]
I created a new virtual environment in anaconda (version 4.8.3)
packages in environment at C:\Users\Anirudh\anaconda3\envs\dcase2018:
[Packages_Dependencies.txt](https://github.com/librosa/librosa/files/4902229/Packages_Dependencies.txt)

After activating the environment using `conda activate dcase2018`
i tried to execute the following code 
`filename = librosa.util.example_audio_file()`
`y, sr = librosa.load(filename)`
`print(y, sr, sep = '\n')`

i ended up with the following error
**Traceback (most recent call last):
     filename = librosa.util.example_audio_file()
NameError: name 'librosa' is not defined**

The error persists with the newest versions of librosa too. 
I have looked at following issues
#1204 
#1205 
#1202 
#1195 
and hence downgraded to the 0.6.1 version.

**Comment by bmcfee** [comment]
Did you remember to `import librosa` first?

**Comment by Anirudh-Srinivasan** [comment]
Thanks it worked. I just realized how silly a mistake it was. Thanking you for your time.

**Comment by bmcfee** [comment]
Glad to hear it was something easy to fix!
