### ISSUE TITLE
Adaptive waveplot

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#1207]
**Is your feature request related to a problem? Please describe.**

`display.waveplot` works by downsampling the input waveform to get an amplitude envelope, rather than the raw samples.

This is great when we want a big-picture view of a long signal, but it's pretty lousy when we're looking at a signal close up.  The `max_points` parameter sets a threshold of sample counts, below which the raw signal is displayed.

The problem is that there's no easy way to switch between the two modes based on the actual display limits of plot in question.  For example, it'd be nice to be able to just `waveplot` some data, set the axis limits later, and have the plot decide dynamically whether to show the aggregated envelope or the raw samples.   Even better, for interactive backends (ipympl, qt), a user could zoom in or out, and the plot should update automatically.

**Describe the solution you'd like**

The [matplotlib example gallery](https://matplotlib.org/3.3.0/gallery/event_handling/resample.html?highlight=resample) shows how to do this kind of thing using a callback for whenever the display limits change.  The example there isn't perfect: it recomputes the downsampled signal on any limit change, including panning (not just zooming), so it's likely pretty slow.  But I think we could adapt it to be more efficient.

**Comment by bmcfee** [comment]
See also #676

**Comment by phdodds** [comment]
Hi Brian, 
If this is still open, I could take a crack at it. I recently had to solve a similar problem.

**Comment by bmcfee** [comment]
@phdodds that would be great, thanks!

**Comment by bmcfee** [comment]
Circling back on this one, I think it should be pretty doable for mono signals, but we might have some trouble in handling multichannel.

For mono signals, I think a reasonable approach is to maintain two artists on the figure: one fill_between (as we currently do) and one limited buffer of samples (probably a step plot), as well as a handle to the audio buffer.  By default, the fill_between is drawn and visible and the sample buffer is invisible; whenever the viewport covers a time extent below the specified buffer length (say, 1000 samples), we toggle the visibility and set the step plot's time and vertical values to whatever part of the signal covers the view port.  If the viewport zooms back out, then we toggle visibility back.  I think this should work pretty easily, and if we're careful with the bookkeeping about what's currently paged in, it should be quite efficient.

The catch here is multi-channel (specifically stereo).  For fill_between, we use the left and right channel's envelopes as upper and (negated) lower bounds on the curve.  I'm not sure what the semantics should be here when switching to samples on multi-channel buffers: just show one channel?  maintain sample buffers for each channel?

This also points to a subtler API issue: what should the return value of adaptive waveplot be?  Right now, we return the fill_between object, which is I think what should be expected from idiomatic matplotlib code.  In the adaptive case, this wouldn't necessarily make sense, and we might want to return the callback object instead (analogous to `DataDisplayDownsampler` in the mpl example), which can provide handles to the artists in question.  But this is an API-breaking change, so it would have to wait until 0.9 if we modify `waveplot`.

Or would it make sense to replace `waveplot` with this new adaptive plotter and do a deprecation cycle?

**Comment by bmcfee** [comment]
Got a prototype working without too much effort.  Github's lousy at video embeds, but here's a tweet with a short demo: https://twitter.com/functiontelechy/status/1391772722024394758

<details>
<summary>Here's the code</summary>

```python
class AdaptiveWaveplot:
    def __init__(self, times, y, sr=22050, max_samples=1024):
        self.times = times
        self.samples = y
        self.sr = sr
        self.max_samples = max_samples
        
    def update(self, ax):
        lims = ax.viewLim
        
        if lims.width * self.sr <= self.max_samples:
            self.envelope.set_visible(False)
            self.steps.set_visible(True)
            
            # Now check that our viewport
            xdata = self.steps.get_xdata()
            if lims.x0 <= xdata[0] or lims.x1 >= xdata[-1]:
                # Viewport expands beyond current data in steps; update
                # we want to cover a window of self.max_samples centered on the current viewport
                midpoint_time = (lims.x1 + lims.x0) / 2
                idx_start = np.searchsorted(self.times, midpoint_time - max_samples / sr)
                self.steps.set_data(self.times[idx_start:idx_start+self.max_samples],
                                        self.y[idx_start:idx_start+self.max_samples])
        else:
            self.envelope.set_visible(True)
            self.steps.set_visible(False)
            
        ax.figure.canvas.draw_idle()

from librosa import util, core
from librosa.display import __envelope, __check_axes, __decorate_axis

def adwaveplot(
    y,
    sr=22050,
    max_points=1e4,
    x_axis="time",
    offset=0.0,
    max_sr=1000,
    ax=None,
    **kwargs,
):

    util.valid_audio(y, mono=False)

    if not (isinstance(max_sr, int) and max_sr > 0):
        raise ParameterError("max_sr must be a non-negative integer")

    target_sr = sr
    hop_length = 1

    # Pad an extra channel dimension, if necessary
    if y.ndim == 1:
        y = y[np.newaxis, :]

    if max_points is not None:
        if max_points <= 0:
            raise ParameterError("max_points must be strictly positive")

        if max_points < y.shape[-1]:
            target_sr = min(max_sr, (sr * y.shape[-1]) // max_points)

        hop_length = sr // target_sr

    # Create the adaptive drawing object
    axes = __check_axes(ax)

    kwargs.setdefault("color", next(axes._get_lines.prop_cycler)["color"])
    
    times = offset + core.times_like(y, sr=sr, hop_length=1)
    adaptor = AdaptiveWaveplot(times, y[0], sr=sr, max_samples=max_points)

    adaptor.steps, = axes.step(times, y[0], marker='', **kwargs)
    
    # Reduce by envelope calculation
    y_env = __envelope(y, hop_length)

    y_top = y_env[0]
    y_bottom = -y_env[-1]

    locs = offset + core.times_like(y_top, sr=sr, hop_length=hop_length)

    adaptor.envelope = axes.fill_between(locs, y_bottom, y_top, **kwargs)

    axes.set_autoscale_on(False)  # Otherwise, infinite loop
    axes.callbacks.connect('xlim_changed', adaptor.update)
    axes.set_xlim([locs.min(), locs.max()])
    axes.set_ylim([y_bottom.min(), y_top.max()])

    # Construct tickers and locators
    __decorate_axis(axes.xaxis, x_axis)

    return adaptor
```

</details>

**Comment by bmcfee** [comment]
Having implemented this, I think it's doable to implement it for 0.8.1.  Coming back to my previous comment, I think the way to do it is as an entirely new function that will eventually replace `waveplot` after a deprecation cycle.  Maybe `librosa.display.waveshow` (rhymes with `specshow`)?

A couple of things we should hammer out:

1. Do we still want `max_samples` and `max_sr`?  Or should we just have `max_samples` apply to the number of points in both the step plot and the `fill_between`?
2. How do we want to handle artist properties?  My hack implementation above just sends kwargs through to both artists, but there are some properties that would only make sense on `step` and some that only make sense on `fill_between`.  I'm not thrilled about the idea of going full seaborn-style with `step_kws={}` and `fill_between_kws={}` parameters.
3. What should we do about multi-channel?  Prototype uses left-right for envelopes and left-only for samples.  This seems non-ideal to me, but I don't know of a better solution.  Should we drop the left-right support entirely, and only handle mono signals?

**Comment by bmcfee** [comment]
>     1. Do we still want `max_samples` and `max_sr`?  Or should we just have `max_samples` apply to the number of points in both the step plot and the `fill_between`?

Hacked at this a bit, and I think it can be simplified to a single parameter: larger values = higher threshold for when sample plot transitions to envelope plot.



>     2\. How do we want to handle artist properties?

This gets even more tricky with things like `label=`.  Prototype passes this to both artists, which produces a redundant legend.  The two options I see are 1) totally separate kwargs, or 2) filtered kwargs (mir_eval style).  Option 1 is bad for usability, option 2 is bad for maintenance.  A compromise might be to prioritize the step plot, and only pull in a few specific args for the envelope plot (eg color) to match style.  Both artists will be accessible in the returned object, so they can always be updated later.



>     3\. What should we do about multi-channel?

This got a little trickier on us.  It turns out that we can't actually have multiple adaptive wave plots on the same axes object right now because matplotlib will only support one callback function at a time. (This may change in the future.) If this was not the case, I would suggest simplifying the function to only support mono, and recommending users to overlay plots on the same axes for each channel.  But, since that's not an option, I think we'll need to just keep it as is for now.  At some point in the future (eg #1130 ) we may want to revisit that decision.

**Comment by bmcfee** [comment]
Looks like multi-plotting actually does work!

```python
y, sr = librosa.load(librosa.ex('trumpet'))
yh, yp = librosa.effects.hpss(y, margin=2)

fig, ax = plt.subplots(figsize=(6, 3))
o1 = waveshow(yh, sr=sr, ax=ax, alpha=0.75, label='Harmonic')
o2 = waveshow(yp, sr=sr, ax=ax, alpha=0.75, label='Percussive')
o3 = waveshow(y-yp-yh, sr=sr, ax=ax, alpha=0.75, label='Residual')
ax.legend(loc='upper right', labelcolor='markerfacecolor', ncol=1)
```
when zoomed out (envelope mode):

![waveshow-multi-1](https://user-images.githubusercontent.com/1190540/118261955-39004800-b482-11eb-8fc3-2effe18e8e11.png)

and then zoomed in (samples mode):

![waveshow-multi-2](https://user-images.githubusercontent.com/1190540/118261966-3c93cf00-b482-11eb-8dd8-57e8bdfa317d.png)

And here's a video embed of it running interactively:

https://user-images.githubusercontent.com/1190540/118262220-94cad100-b482-11eb-8131-ff875cf8797b.mp4


At this point I'm pretty happy with the implementation.  There are still a few rough edges to work out, mostly around how kwargs are handled for the different artists, and how axes limits are set.  I'll try to smooth these out in the coming days and then open a PR.
