### ISSUE TITLE
Support notation in STFT plots

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#1210]
**Is your feature request related to a problem? Please describe.**
`specshow` allows STFT to be shown in linear or logarithmic scales, with Hz formatting on the frequency axis.

If a user wants a pitch-based decoration (notes or svara), they currently have to use a CQT spectrogram rather than an STFT.  There's no good technical reason for that though, as they all render the data in natural coordinates.

**Describe the solution you'd like**
Add axis modes to specshow:

- `fft_note`
- `fft_svara`

which work like their CQT counterparts, but applied to STFT data.

**Describe alternatives you've considered**
A savvy user could probably hack this by manually constructing the axis decoration objects, but we should make it easier for them.

**Comment by P-bibs** [comment]
I haven't contributed before, but would love to try to tackle this one if that's ok (seeing as its marked "good for beginners").

I believe I've found the relevant sections of `specshow` that would need to be altered. It seems like `fft_note` won't be too bad. `fft_svara` may be harder since I'm not familiar with Indian music theory, but hopefully a little bit of research and drawing on the existing code for `cqt_svara` will help.

**Comment by lostanlen** [comment]
Hello @P-bibs, welcome to librosa.

> One question I have: the specshow documentation lists "fft" as a supported axis type but there's no mention of it in the code and trying to call the following code causes an error:

It looks like you're right! The string `fft` is missing from this line in `__decorate_axis`:

https://github.com/librosa/librosa/blob/main/librosa/display.py#L1097

It would be good to bugfix this before adding new features `fft_note` and `fft_svara`

**Comment by bmcfee** [comment]
@lostanlen that bug was already fixed, check the coord_map data structure.

**Comment by P-bibs** [comment]
@bmcfee I see the inclusion of `"fft"` in `coord_map` but it seems like another change is needed as @lostanlen mentioned otherwise the above code will produce the following error. Although, maybe I'm misunderstanding you and a change has been implemented on some other branch I'm not seeing.

```python
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    img = librosa.display.specshow(S_db, y_axis='fft', x_axis='time', ax=ax)
  File "/home/paul/Development/librosa/librosa/display.py", line 860, in specshow
    __decorate_axis(axes.yaxis, y_axis, key=key, Sa=Sa, mela=mela, thaat=thaat)
  File "/home/paul/Development/librosa/librosa/display.py", line 1151, in __decorate_axis
    raise ParameterError("Unsupported axis type: {}".format(ax_type))
librosa.util.exceptions.ParameterError: Unsupported axis type: fft
```
If this quick change needs to be made, is it ok to include in this PR or should it be saved for another?

**Comment by bmcfee** [comment]
Sorry, you're correct!  And yeah, it'd be great to roll in the fix for that in this issue.

**Comment by NThande** [comment]
Has this been resolved? I'm also new here and figured I'd give it a shot if progress has stalled out.

**Comment by bmcfee** [comment]
Not yet resolved -- @P-bibs are you still interested in working on this?

**Comment by P-bibs** [comment]
Yep, sorry about the radio silence. I think I have the functionality in a good place, but I was wondering if there was anything else required regarding tests/documentation/etc. before opening a pull request? For reference [here's my branch](https://github.com/librosa/librosa/compare/main...P-bibs:main)

**Comment by NThande** [comment]
Alright. I can take a look at your branch @P-bibs instead of starting fresh.

**Comment by lostanlen** [comment]
@P-bibs and @NThande this is your time, step up! 🎷🎺

**Comment by bmcfee** [comment]
I also just noticed that we never answered @P-bibs 's question:


> but I was wondering if there was anything else required regarding tests/documentation/etc. before opening a pull request?

We'll need unit tests and expanded documentation for the new functionality.  I'm also happy to put that together based on what you've already implemented in your branch.  I'd like to get 0.8.1 off my plate so we can get on to bigger and better things, and this is the last functionality-related issue on the stack.

**Comment by P-bibs** [comment]
Sorry for the hold up on this. Yep, the only remaining blocker was the testing and documentation. Not entirely sure where the documentation goes but I can take a crack at some unit tests this afternoon. Of course, if you think you can do it faster you're more than welcome to.

**Comment by bmcfee** [comment]
Yes, please open a PR!

For documentation, it would mainly be an issue of adding the relevant lines to the docstring for `specshow` under `x_axis`/`y_axis`, eg this block:

https://github.com/librosa/librosa/blob/95f494583203d6055f3bce6ea1d1cfd766b9a4da/librosa/display.py#L781-L797

For tests, it might need to be something done on my side so that we can ensure consistent settings for the generated reference images.  But I'm happy to build on your PR to get that done.

Thanks again!

**Comment by P-bibs** [comment]
Ahh I see. And just to double check, is there anything else that needs to be done to update the online documentation, or does that build directly from the docstrings?

**Comment by bmcfee** [comment]
> Ahh I see. And just to double check, is there anything else that needs to be done to update the online documentation, or does that build directly from the docstrings?

It's auto-generated from docstrings; I generally only update when we ship a release.
