### ISSUE TITLE
module scipy has no attribute __version__

### ISSUE THREAD

**Issue by AlwaleedAlduies** [librosa/librosa#1212]
**Describe the bug**
I am using Anaconda (Spyder) I am trying to importing librosa library
I was getting this error when importing librosa **ModuleNotFoundError: No module named 'scipy.ndimage'**
then I wrote this command in Anaconda prompt (conda install scipy) to reinstall scipy now I get this error **AttributeError: module 'scipy' has no attribute 'version'** I tried to figure out how to solve but i couldn't

Notice : When I use anaconda prompt  no error occur while importing librosa but when I use spyder , the error occur

**Software versions***
`
python: 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]

librosa: 0.8.0

audioread: 2.1.8
numpy: 1.18.5
scipy: 1.5.0
sklearn: 0.23.1
joblib: 0.15.1
decorator: 4.4.2
soundfile: 0.10.3
resampy: 0.2.2
numba: 0.50.1

numpydoc: 1.0.0
sphinx: 3.0.4
sphinx_rtd_theme: None
sphinxcontrib.versioning: None
sphinx-gallery: None
pytest: None
pytest-mpl: None
pytest-cov: None
matplotlib: 3.2.2
presets: None
`

**Comment by lostanlen** [comment]
This is very probably an issue with your local Python environment in Spyder. I don't think it's related to librosa at all.
Please see: https://docs.spyder-ide.org/installation.html#installing-with-anaconda-recommended

**Comment by AlwaleedAlduies** [comment]
Thanks all 
Problem solved by updating spyder using this command in Anaconda prompt 
`
     conda update spyder
`
