### ISSUE TITLE
Sample rate can not been changed

### ISSUE THREAD

**Issue by AlwaleedAlduies** [librosa/librosa#1213]
**Describe the bug**
I am using Anaconda , I am trying to change sample rate of audio file to get length 8000
but it couldn't as shown below

**To Reproduce**
`
>>> import os
>>> import librosa
>>> audio_path = "train_voice/1.wav"
>>> samples , sample_rate = librosa.load(audio_path , sr = 16000)
>>> print(len(samples))
18205
>>> samples = librosa.resample(samples , sample_rate , 8000)
>>> print(len(samples))
9103

`

**Software versions***
```

librosa: 0.6.2

audioread: 2.1.8
numpy: 1.18.5
scipy: 1.5.0
sklearn: 0.23.1
joblib: 0.16.0
decorator: 4.4.2
six: 1.15.0
resampy: 0.2.2

numpydoc: 1.1.0
sphinx: 3.1.2
sphinx_rtd_theme: None
sphinxcontrib.versioning: None
matplotlib: 3.3.0
numba: 0.48.0
```

**Comment by bmcfee** [comment]
This is because your input signal is not exactly one second long.
