### ISSUE TITLE
htk and norm for librosa.feature.melspectrogram

### ISSUE THREAD

**Issue by turian** [librosa/librosa#1216]
**Is your feature request related to a problem? Please describe.**

librosa.filters.mel allows parameters htk and norm. I would like librosa.feature.melspectrogram to accept those parameters too.

**Describe the solution you'd like**
librosa.feature.melspectrogram passes the parameters htk and norm along to librosa.filters.mel

**Describe alternatives you've considered**
Use librosa.filters.mel directly.

**Comment by bmcfee** [comment]
This is already supported.  See [the melspectrogram docs](https://librosa.org/doc/latest/generated/librosa.feature.melspectrogram.html?highlight=mel%20spectrogram#librosa.feature.melspectrogram) under the parameter heading for `kwargs`.
