### ISSUE TITLE
get_duration fails on .wav when not loaded into memory v0.8

### ISSUE THREAD

**Issue by NumesSanguis** [librosa/librosa#1217]
**Describe the bug**
`get_duration` should be able to get the length of an audio file without loading it into memory, according this solved issue: https://github.com/librosa/librosa/issues/345
However, when I try it on a .wav from the CREMA-D dataset, it fails with: `ParameterError: Audio data must be floating-point`

**To Reproduce**
```python
import librosa

librosa.get_duration("1001_IEO_NEU_XX.wav")
```

Audio file(s):
- git clone CREMA-D with only .wav files (not video/MP3): `git clone --config lfs.fetchexclude='AudioMP3,VideoFlash' https://github.com/CheyneyComputerScience/CREMA-D.git`
- Download this sample file: [1001_IEO_NEU_XX.zip](https://github.com/librosa/librosa/files/5032716/1001_IEO_NEU_XX.zip)

**Expected behavior**
Output the length of the audio file in seconds: `1.2832199546485261`

**Error**

**Software versions***
```python
Linux-4.15.0-112-generic-x86_64-with-debian-buster-sid
Python 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 20:28:53) 
[GCC 7.3.0]
NumPy 1.18.5
SciPy 1.5.0
librosa 0.8.0
INSTALLED VERSIONS
------------------
python: 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 20:28:53) 
[GCC 7.3.0]

librosa: 0.8.0

audioread: 2.1.8
numpy: 1.18.5
scipy: 1.5.0
sklearn: 0.23.1
joblib: 0.16.0
decorator: 4.4.2
soundfile: 0.10.2
resampy: 0.2.2
numba: 0.50.1

numpydoc: None
sphinx: 2.3.1
sphinx_rtd_theme: 0.4.3
sphinxcontrib.versioning: None
sphinx-gallery: None
pytest: 5.4.3
pytest-mpl: None
pytest-cov: None
matplotlib: 3.1.1
presets: None
```

**Additional context**
The following code does work, showing it shouldn't be an issue with the .wav itself:
```python
signal, sr = librosa.load("1001_IEO_HAP_HI.wav", sr=None)
librosa.get_duration(signal)
```

Might it be related to the change in default audio parser since v0.7.0?

**Comment by bmcfee** [comment]
This is because you're using positional augments rather than keyword arguments. The first positional argument is assumed to be a waveform, so it will try to interpret the string input (file name) as a sequence of samples.

Use `filename='...'` instead.

**Comment by lostanlen** [comment]
Thank you for raising, @NumesSanguis 
Related: #1114  :)

**Comment by NumesSanguis** [comment]
@bmcfee I see, thank you. Would it be worth to simplify this function's API? Like having `y` accept both np.array and string/Path? Then with a simple `if type(y) is in [str, pathlib.Path]` (untested code), run filename code. Might run into issues if a function subclasses from a type though.

**Comment by lostanlen** [comment]
@NumesSanguis the recommended prototypes are:
 `get_duration(y=signal, sr=sr)`
`get_duration(filename=filename)`

It's less about the type of the first argument that about the number of arguments.

**Comment by NumesSanguis** [comment]
I guess if I checked the documentation more carefully, I would have noticed the `filename` keyword. Therefore, the possible breaking of people's code to reduce one argument might not be worth it. If you want to keep it like this, I'll close the issue (or you can close it).
