### ISSUE TITLE
event classification / detection using Librosa

### ISSUE THREAD

**Issue by VtlNmnk** [librosa/librosa#1219]

**Comment by VtlNmnk** [comment]
Hey Brian! I am grateful to you for your work. 
My task is to classify events in the audio signal, preferably in real time. Visually, the signal can be divided into ringing sounds (frequency from 400 to 500) alternating with silence, a voice sound and a beep at a frequency of about 1000-1050. ![waveplot](https://user-images.githubusercontent.com/33348597/89649619-c1d1ce00-d8c9-11ea-9b77-fae3b287f515.jpg)
The mel power spectrogram also shows well-separated areas. 
![mel_power_spectrogram](https://user-images.githubusercontent.com/33348597/89649663-d01fea00-d8c9-11ea-8f49-50f210e410f5.jpg)
Perhaps you have an example of event classification / detection? 
I searched [here](https://gist.github.com/bmcfee

)  but couldn't find anything like this.

**Comment by lostanlen** [comment]
@VtlNmnk these questions are better suited to the librosa google group.
Librosa is not ideal for processing audio in real time.
If you don't know it already, i recommend you check out contributions by DCASE (Detection and Classification of Acoustic Scenes and Events) http://dcase.community/
