### ISSUE TITLE
Multitrack support

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#122]
The current loader has an option to convert stereo to mono, assuming interleaving of two channels.  This could be generalized to support general mixing of multi-tracks by using the `frame` function.

**Comment by romino666** [comment]
@piem I could extract a stereo track in multitrack using librosa, but I would like the multitrack to be unfiltered.

**Comment by lostanlen** [comment]
@romino666 if by unfiltered you mean non-resampled, consider passing `sr=None`

https://librosa.org/blog/2019/07/17/resample-on-load

**Comment by romino666** [comment]
@lostanlen thanks, unfiltered and surely uncut

**Comment by romino666** [comment]
For Example, if i can import a Michael Jackson song, like Dirty Diana, i can try to convert stereo to mono using `Frame` function to make complete "non-resampled" multitracks with 48 tracks with this solution `sr=None`

**Comment by romino666** [comment]
@dpwe i can convert Dirty Diana into non-resampled multitracks next week.

**Comment by romino666** [comment]
Microsoft Visual Studio Code is free ?
