### ISSUE TITLE
issue while importing librosa in python 3.6,windows 10

### ISSUE THREAD

**Issue by jashiag** [librosa/librosa#1220]
***BEFORE POSTING A BUG REPORT*** Please look through [existing issues (both open and closed)](https://github.com/librosa/librosa/issues?q=is%3Aissue) to see if it's already been reported or fixed!

**ImportError                               Traceback (most recent call last)
<ipython-input-9-989066361697> in <module>
----> 1 import librosa

~\Anaconda3\envs\Python3.6Test\lib\site-packages\librosa\__init__.py in <module>
    209 # And all the librosa sub-modules
    210 from ._cache import cache
--> 211 from . import core
    212 from . import beat
    213 from . import decompose

~\Anaconda3\envs\Python3.6Test\lib\site-packages\librosa\core\__init__.py in <module>
      4 
      5 from .convert import *  # pylint: disable=wildcard-import
----> 6 from .audio import *  # pylint: disable=wildcard-import
      7 from .spectrum import *  # pylint: disable=wildcard-import
      8 from .pitch import *  # pylint: disable=wildcard-import

~\Anaconda3\envs\Python3.6Test\lib\site-packages\librosa\core\audio.py in <module>
      9 import audioread
     10 import numpy as np
---> 11 import scipy.signal
     12 import resampy
     13 

~\Anaconda3\envs\Python3.6Test\lib\site-packages\scipy\signal\__init__.py in <module>
    289 from __future__ import division, print_function, absolute_import
    290 
--> 291 from . import sigtools, windows
    292 from .waveforms import *
    293 from ._max_len_seq import max_len_seq

~\Anaconda3\envs\Python3.6Test\lib\site-packages\scipy\signal\windows\__init__.py in <module>
     39 """
     40 
---> 41 from .windows import *
     42 
     43 __all__ = ['boxcar', 'triang', 'parzen', 'bohman', 'blackman', 'nuttall',

~\Anaconda3\envs\Python3.6Test\lib\site-packages\scipy\signal\windows\windows.py in <module>
      7 
      8 import numpy as np
----> 9 from scipy import linalg, special, fft as sp_fft
     10 from scipy._lib.six import string_types
     11 

~\Anaconda3\envs\Python3.6Test\lib\site-packages\scipy\linalg\__init__.py in <module>
    193 from .linalg_version import linalg_version as __version__
    194 
--> 195 from .misc import *
    196 from .basic import *
    197 from .decomp import *

~\Anaconda3\envs\Python3.6Test\lib\site-packages\scipy\linalg\misc.py in <module>
      3 import numpy as np
      4 from numpy.linalg import LinAlgError
----> 5 from .blas import get_blas_funcs
      6 from .lapack import get_lapack_funcs
      7 

~\Anaconda3\envs\Python3.6Test\lib\site-packages\scipy\linalg\blas.py in <module>
    213 import functools
    214 
--> 215 from scipy.linalg import _fblas
    216 try:
    217     from scipy.linalg import _cblas

ImportError: DLL load failed: The file cannot be accessed by the system.

​
**
ImportError                               Traceback (most recent call last)
<ipython-input-9-989066361697> in <module>
----> 1 import librosa

~\Anaconda3\envs\Python3.6Test\lib\site-packages\librosa\__init__.py in <module>
    209 # And all the librosa sub-modules
    210 from ._cache import cache
--> 211 from . import core
    212 from . import beat
    213 from . import decompose

~\Anaconda3\envs\Python3.6Test\lib\site-packages\librosa\core\__init__.py in <module>
      4 
      5 from .convert import *  # pylint: disable=wildcard-import
----> 6 from .audio import *  # pylint: disable=wildcard-import
      7 from .spectrum import *  # pylint: disable=wildcard-import
      8 from .pitch import *  # pylint: disable=wildcard-import

~\Anaconda3\envs\Python3.6Test\lib\site-packages\librosa\core\audio.py in <module>
      9 import audioread
     10 import numpy as np
---> 11 import scipy.signal
     12 import resampy
     13 

~\Anaconda3\envs\Python3.6Test\lib\site-packages\scipy\signal\__init__.py in <module>
    289 from __future__ import division, print_function, absolute_import
    290 
--> 291 from . import sigtools, windows
    292 from .waveforms import *
    293 from ._max_len_seq import max_len_seq

~\Anaconda3\envs\Python3.6Test\lib\site-packages\scipy\signal\windows\__init__.py in <module>
     39 """
     40 
---> 41 from .windows import *
     42 
     43 __all__ = ['boxcar', 'triang', 'parzen', 'bohman', 'blackman', 'nuttall',

~\Anaconda3\envs\Python3.6Test\lib\site-packages\scipy\signal\windows\windows.py in <module>
      7 
      8 import numpy as np
----> 9 from scipy import linalg, special, fft as sp_fft
     10 from scipy._lib.six import string_types
     11 

~\Anaconda3\envs\Python3.6Test\lib\site-packages\scipy\linalg\__init__.py in <module>
    193 from .linalg_version import linalg_version as __version__
    194 
--> 195 from .misc import *
    196 from .basic import *
    197 from .decomp import *

~\Anaconda3\envs\Python3.6Test\lib\site-packages\scipy\linalg\misc.py in <module>
      3 import numpy as np
      4 from numpy.linalg import LinAlgError
----> 5 from .blas import get_blas_funcs
      6 from .lapack import get_lapack_funcs
      7 

~\Anaconda3\envs\Python3.6Test\lib\site-packages\scipy\linalg\blas.py in <module>
    213 import functools
    214 
--> 215 from scipy.linalg import _fblas
    216 try:
    217     from scipy.linalg import _cblas

ImportError: DLL load failed: The file cannot be accessed by the system.

​

**To Reproduce**

**Expected behavior**

**Screenshots**

**Software versions***

**Additional context**

**Comment by bmcfee** [comment]
It appears that your scipy installation is broken, not anything to do with librosa.

**Comment by jashiag** [comment]
Initially Librosa and tensorflow was working fine.But after system updation,tensorflow stopped working.
'3.8.5 (default, Aug  5 2020, 09:44:06) [MSC v.1916 64 bit (AMD64)]'
I reinstalled the Scipy and librosa is now working fine but tensor  in python 3.8.5

To solve the issue of tensor flow,i created another enviroment by downgrading to python 3.6.0 which fixed the issue of tensorflow and tried to fixed the issue for librosa as mentioned by you in the same wa.But it has error.Please suggest.
'3.6.10 |Anaconda, Inc.| (default, May  7 2020, 19:46:08) [MSC v.1916 64 bit (AMD64)]'
In any Python,i need Librosa and Tensorflow working.That would be a quick fix for me.
import tensorflow as tf
tf.__version__
'1.15.0'

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-989066361697> in <module>
----> 1 import librosa

~\Anaconda3\envs\Python3.6Test\lib\site-packages\librosa\__init__.py in <module>
    209 # And all the librosa sub-modules
    210 from ._cache import cache
--> 211 from . import core
    212 from . import beat
    213 from . import decompose

~\Anaconda3\envs\Python3.6Test\lib\site-packages\librosa\core\__init__.py in <module>
      3 """ Core IO and DSP functions"""
      4 
----> 5 from .convert import *  # pylint: disable=wildcard-import
      6 from .audio import *  # pylint: disable=wildcard-import
      7 from .spectrum import *  # pylint: disable=wildcard-import

~\Anaconda3\envs\Python3.6Test\lib\site-packages\librosa\core\convert.py in <module>
      5 import re
      6 import numpy as np
----> 7 from . import notation
      8 from ..util.exceptions import ParameterError
      9 

~\Anaconda3\envs\Python3.6Test\lib\site-packages\librosa\core\notation.py in <module>
      6 import numpy as np
      7 from .._cache import cache
----> 8 from ..util.exceptions import ParameterError
      9 
     10 __all__ = [

~\Anaconda3\envs\Python3.6Test\lib\site-packages\librosa\util\__init__.py in <module>
     85 from .matching import *  # pylint: disable=wildcard-import
     86 from .deprecation import *  # pylint: disable=wildcard-import
---> 87 from ._nnls import *  # pylint: disable=wildcard-import
     88 from . import decorators
     89 from . import exceptions

~\Anaconda3\envs\Python3.6Test\lib\site-packages\librosa\util\_nnls.py in <module>
     11 
     12 import numpy as np
---> 13 import scipy.optimize
     14 from .utils import MAX_MEM_BLOCK
     15 

~\Anaconda3\envs\Python3.6Test\lib\site-packages\scipy\optimize\__init__.py in <module>
    387 from __future__ import division, print_function, absolute_import
    388 
--> 389 from .optimize import *
    390 from ._minimize import *
    391 from ._root import *

~\Anaconda3\envs\Python3.6Test\lib\site-packages\scipy\optimize\optimize.py in <module>
     35                    asarray, sqrt, Inf, asfarray, isinf)
     36 import numpy as np
---> 37 from .linesearch import (line_search_wolfe1, line_search_wolfe2,
     38                          line_search_wolfe2 as line_search,
     39                          LineSearchWarning)

~\Anaconda3\envs\Python3.6Test\lib\site-packages\scipy\optimize\linesearch.py in <module>
     16 from warnings import warn
     17 
---> 18 from scipy.optimize import minpack2
     19 import numpy as np
     20 from scipy._lib.six import xrange

ImportError: DLL load failed: The file cannot be accessed by the system.

[issue.txt](https://github.com/librosa/librosa/files/5046763/issue.txt)

**Comment by bmcfee** [comment]
Again, these are problems with either dependencies (scipy) or tensorflow, not librosa.  Aside from generally recommending to stick to conda packages (including our conda-forge package for librosa), I don't have much to offer here.
