### ISSUE TITLE
Example source code links are broken in the docs

### ISSUE THREAD

**Issue by bshall** [librosa/librosa#1222]
Clicking on the source code links at the end of examples gives a page not found error.
For example, see the link at the bottom of this page https://librosa.org/doc/latest/generated/librosa.feature.chroma_stft.html.

**Comment by lostanlen** [comment]
You are correct. Worse, the problem does not only affect the docs of the latest version, but also the docs of previous stable versions such as 0.7.2

GitHub repository of the librosa website: https://github.com/librosa/librosa.github.io

For future reference, here's the 404
https://librosa.org/tmp/tmpnt58hyic/b0064fe7dbe8048b1d4148e61a568b6fe3fca91b/docs/generated/librosa-core-stft-1.py

@bmcfee perhaps related to the recent migration to librosa.org ?

**Comment by bmcfee** [comment]
Oh how weird.

The `[source]` links at the function signature level work fine, but not the ones at the end of the doc (which I didn't even realize existed!).

I don't think this has anything to do with the .org migration though, as all sphinx artifacts use relative URLs.  This seems like a bug upstream somewhere in sphinx, possibly from multiversion.  I'll do a little digging into it when I have some time.

**Comment by bmcfee** [comment]
I dug into this a little, and it turns out the source links at the *top* are also broken, and link to old versions of the source code :scream: 

This is almost certainly a bug in sphinx-multiversion.

**Comment by bmcfee** [comment]
Update: the top source links are fixed by smv 0.2.4; the bottom links are still broken, but hopefully we can get that fixed in time for the next release.

**Comment by bmcfee** [comment]
Reference issue: https://github.com/Holzhaus/sphinx-multiversion/issues/40

**Comment by bmcfee** [comment]
I'm removing this from the 0.8.1 milestone because the fix will be upstream of us, and won't require any changes to the librosa code or a new release.  We just need to remember to rebuild the doc site when smv gets fixed.

**Comment by bmcfee** [comment]
One more update here, it looks like this can be traced to a bad interaction between `sphinxext.plot_directive` and `sphinx-multiversion`.  The good news is that the bottom links can be removed from the build through a config option, which I'll apply for the next release.  This should fix the issue, with the slight drawback that there won't be individual download links for example source-code fragments.  I think this is okay, as example code is generally small enough to fit in a copy-paste buffer anyway.
