### ISSUE TITLE
Not able to Install librosa in Windows 10

### ISSUE THREAD

**Issue by Debagnik** [librosa/librosa#1224]
Hi,
I am very new to python.

I was trying to install librosa on Windows 10 platform by the following command
`python -m pip install librosa` 
and also this command
`pip install librosa`

both the time the command window exits with exit status 1. and I Can't figure out what is happening. Please help.

In case you need to see the error
`ERROR: Command errored out with exit status 1:
     command: 'c:\users\kiit\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-install-ykowbexr\\librosa\\setup.py'"'"'; __file__='"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-install-ykowbexr\\librosa\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-pip-egg-info-9am2023l'
         cwd: C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-ykowbexr\librosa\
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by lostanlen** [comment]
Hello @Debagnik,
The important line is
` No module named 'setuptools'`

This means that something is amiss in pip (Python's package manager). Try to see if `pip install setuptools` or `easy_install setuptools` solves your problem. If it doesn't, consider reinstalling Python from scratch.

On a related note, i see that your distribution of Python is `\users\kiit\appdata\local\programs\python\python38`. It would probably be easier to install Python via a miniconda distribution:

please visit https://docs.conda.io/projects/conda/en/latest/user-guide/install/windows.html

**Comment by Debagnik** [comment]
@lostanlen Thanks for the help.
