### ISSUE TITLE
Adding `write` support into librosa

### ISSUE THREAD

**Issue by jbitton** [librosa/librosa#1226]
**Is your feature request related to a problem? Please describe.**
Librosa's `load` function works well and with a variety of different audio formats. However, there is no functionality for writing files within librosa, and thus I am forced to use `soundfile`'s write function which doesn't support popular audio formats such as MP3. This has been quite frustrating for me.

**Describe the solution you'd like**
Ideally, it would be amazing if librosa had a built-in function, perhaps similar to the format of `librosa.load` for writing -- i.e. try soundfile's write and if it doesn't work, resort to something else. This function would support popular audio format types such as MP3, AAC, etc.

**Describe alternatives you've considered**
I've looked around *extensively* for other options for writing audio files with no luck. I've looked at FFMPEG (which in my experience hasn't worked well with audio numpy arrays), at pydub (that has been supremely buggy), and all kinds of libraries on the internet. 

Thanks in advance for your help! If you are incapable of adding this feature, I'd greatly appreciate some pointers for libraries that will take as input an audio array, the sample rate, and the output file and save the audio.

**Comment by bmcfee** [comment]
Thanks for raising this, but *removing* audio output has been a [long-standing issue](https://github.com/librosa/librosa/issues?q=is%3Aissue+is%3Aclosed+label%3AIO) in the package that we recently resolved #1062 .  Audio encoding would be too difficult to maintain and support across platforms, and is already served by other packages (namely `soundfile` / `libsndfile`).

If the only problem is that soundfile doesn't support mp3, I'd suggest using sf to write to a temp file and then calling out to an external encoder of your choice (eg gogo or lame) through a subprocess interface.  Note: soundfile does have an open PR to add mp3 support: https://github.com/erikd/libsndfile/pull/499 , so this problem may go away sometime in the future.
