### ISSUE TITLE
Different shades of spectrograms are plotted for PCEN spectrograms for different librosa versions

### ISSUE THREAD

**Issue by kunakl07** [librosa/librosa#1232]
Here is the [colab notebook](https://colab.research.google.com/drive/1gLNLoF52QjLy7yl_IugYPJvLPYQlgsCI?usp=sharing) where I have shown how different versions of librosa library(i.e 0.6.3 has different PCEN spectrogram as compared to spectrogram plotted in 0.8.1) are plotting different shades of PCEN spectrograms. Could you please take a look and suggest a solution for that issue. Moreover, in the older versions(i.e. 0.6.3) there is a vertical line that is being generated on the left while using PCEN, how to remove it?

**Comment by bmcfee** [comment]
I suggest that you consult the [changelog](https://librosa.org/doc/latest/changelog.html), which specifically lists all modifications for each version.  There have been several releases between 0.6.3 and now, and many changes to PCEN.
