### ISSUE TITLE
Search engine optimization of librosa doc

### ISSUE THREAD

**Issue by keunwoochoi** [librosa/librosa#1234]
Googling something like "librosa mfcc" doesn't do a very good job at finding librosa documentation. The first result is this dubious website (http://man.hubwiz.com/docset/LibROSA.docset/Contents/Resources/Documents/generated/librosa.feature.mfcc.html) that copied librosa 0.6.0 documentation. At the moment, the 8th result is the first librosa webpage and it's librosa 0.7.1 documentation and the link is broken. 

I don't have any knowledge about how, but is it something we want to fix a bit?

**Comment by bmcfee** [comment]
Yes, this issue has been raised several times already. I've tried flagging the site to be reindexed, but Google is taking their sweet time with it.
