### ISSUE TITLE
librosa.load does not work with pathlib.Path

### ISSUE THREAD

**Issue by jonashaag** [librosa/librosa#1236]
**Describe the bug**

```pycon
# OK:
>>> librosa.load(str(Path("...")))
# Not OK:
>>> librosa.load(Path("..."))
Traceback (most recent call last):
...
  File ".../soundfile.py", line 1263, in _open
    raise TypeError("Invalid file: {0!r}".format(self.name))
TypeError: Invalid file: PosixPath('...')
>>> soundfile.__version__
'0.9.0'
>>> librosa.__version__
'0.8.0'
```

**Software versions**

python: 3.8.5 (default, Jul 21 2020, 10:48:26)
[Clang 11.0.3 (clang-1103.0.32.62)]

librosa: 0.8.0

audioread: 2.1.8
numpy: 1.18.5
scipy: 1.4.1
sklearn: 0.22.2.post1
joblib: 0.16.0
decorator: 4.4.2
soundfile: 0.9.0
resampy: 0.2.2
numba: 0.50.1

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
sphinxcontrib.versioning: None
sphinx-gallery: None
pytest: 6.0.1
pytest-mpl: None
pytest-cov: None
matplotlib: 3.3.0
presets: None

**Comment by bmcfee** [comment]
The problem is that we didn't update the minimum soundfile version necessary for this to work.  If you upgrade soundfile to >=0.10.2, Path works as expected.

We should revise the requirements spec accordingly, but there are no code changes necessary to address this.

**Comment by jonashaag** [comment]
:O I did `pip install -U soundfile` before reporting this issue, and pip reported v0.10.2 to be installed, but `soundfile.__version__` still gave 0.9.0. Not sure what was going on there. Still, the librosa dependency is still at 0.9.0 so should be updated.

**Comment by f-fritz** [comment]
I have the same issue and no fix either. ´
But one workaround appears to be converting the Path to string. Like
`y,sr = librosa.load(str(path))`
