### ISSUE TITLE
Librosa extract audio by video frame

### ISSUE THREAD

**Issue by HitsujiAura** [librosa/librosa#1238]
I am have taken some videos (.mp4) and extracted the frames using cv2.

Now, I want the corresponding audio representation (melspect or mfcc) for each of those frames. I am confused by how to use the fft_size and hop size to sample the audio at the exact timing of each frame extracted from the video.

Here are some data pointers.

    Video (.mp4) duration: 11.995316666666668s
    Video fps: 59.94005994005994
    Video frame count: 719
    
    Audio Sampling Rate: 22050 Hz

I am trying to create a ML dataset that has a video frame and its corresponding audio features. 

Any help would be appreciated.

**Comment by bmcfee** [comment]
This question is really more appropriate for our google group, but a couple of suggestions:

- The frame rate of any of our spectral features will be `fps = sr / hop_length` [frames / second].
- If you fix the sampling rate to 22050, and have a target frame rate (59.94...), you can solve for the hop length as `hop_length = sr / fps`.
- Hop length needs to be an integer (it counts samples between frames), but `sr / 59.94...` may not be, depending on your audio sampling rate.  You may need to resample your audio stream to a rate that does give an integer multiple of your target fps.

**Comment by HitsujiAura** [comment]
Thank you.
That helped.
