### ISSUE TITLE
[question] Constant Q Cepstral Coefficients(CQCCs)

### ISSUE THREAD

**Issue by lsq357** [librosa/librosa#1239]
I want to extract  [Constant Q Cepstral Coefficients(CQCCs) feature](https://www.researchgate.net/publication/301199823_A_New_Feature_for_Automatic_Speaker_Verification_Anti-Spoofing_Constant_Q_Cepstral_Coefficients) using librosa, how can I do ? 

- [matlab code](https://github.com/rosrad/asvspoof2017/blob/master/baseline/CQCC_v1.0/cqcc.m)

**Comment by bmcfee** [comment]
We don't have a function for this, but you can piece it together from existing functions:

1. Compute a CQT `C = librosa.cqt(...)`
2. Apply decibel scaling: `logC = librosa.amplitude_to_db(np.abs(C))`
3. Use `logC` as the "spectrogram" input to `feature.mfcc`: `librosa.feature.mfcc(S=logC)`

**Comment by lsq357** [comment]
Thank you !
