### ISSUE TITLE
specshow has incorrect mel axis for non-default sr

### ISSUE THREAD

**Issue by beasteers** [librosa/librosa#1240]
**Describe the bug**
When you call `librosa.display.specshow(..., y_axis='mel', sr=sr)` where `sr != 22050` and you leave `fmax=None`, the mel to Hz conversion is incorrect. 

Basically, in `__coord_mel_hz`, if `fmax is None`, it assumes that `fmax = 22050 / 2`, but it really should be `sr / 2`

Looping in @cmydlarz since he pointed it out to me.

(At first I thought #1235 was discussing this as well, but on closer read it's not the same issue.)

**To Reproduce**

```python
import librosa
import librosa.display
import matplotlib.pyplot as plt

fname = librosa.util.example('brahms')
srs = 44100, 16000, 8000

plt.figure(figsize=(15, 5))
for i, sr in enumerate(srs, 1):
    y, sr = librosa.load(fname, sr=sr)
    
    S = librosa.feature.melspectrogram(y, sr=sr)

    plt.subplot(1, len(srs), i)
    librosa.display.specshow(
        librosa.power_to_db(S), 
        y_axis='mel', x_axis='time', 
        cmap='magma', sr=sr)
    plt.title(f'sr={sr}')
```
![image](https://user-images.githubusercontent.com/6741720/93398497-b15a2f00-f849-11ea-843b-c103e799b080.png)

**Expected behavior**
(see y ticks vs title)
![image](https://user-images.githubusercontent.com/6741720/93398542-c20aa500-f849-11ea-9f33-ae263e672cf0.png)

**Solution**
Temporary workaround
```python
librosa.display.specshow(..., y_axis='mel', sr=sr, fmax=sr/2.)
```
Code patch
```python
def __coord_mel_hz(n, fmin=0, fmax=None, sr=22050, **_kwargs):
    '''Get the frequencies for Mel bins'''

    if fmin is None:
        fmin = 0
    if fmax is None:
        fmax = sr / 2.

    basis = librosa.mel_frequencies(n, fmin=fmin, fmax=fmax)
    basis[1:] -= 0.5 * np.diff(basis)
    basis = np.append(np.maximum(0, basis), [fmax])
    return basis
librosa.display.__coord_mel_hz = __coord_mel_hz
```

**Software versions***
```
Darwin-19.2.0-x86_64-i386-64bit
Python 3.7.7 (default, Mar 26 2020, 10:32:53) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
NumPy 1.18.4
SciPy 1.4.1
librosa 0.8.0
INSTALLED VERSIONS
------------------
python: 3.7.7 (default, Mar 26 2020, 10:32:53) 
[Clang 4.0.1 (tags/RELEASE_401/final)]

librosa: 0.8.0

audioread: 2.1.8
numpy: 1.18.4
scipy: 1.4.1
sklearn: 0.23.1
joblib: 0.15.1
decorator: 4.4.2
soundfile: 0.10.3
resampy: 0.2.2
numba: 0.51.0

numpydoc: 1.0.0
sphinx: 3.1.1
sphinx_rtd_theme: None
sphinxcontrib.versioning: None
sphinx-gallery: None
pytest: 5.4.1
pytest-mpl: None
pytest-cov: None
matplotlib: 3.2.1
presets: installed, no version number available
```

**Comment by bmcfee** [comment]
Well that's embarrassing, given how old this particular bit of the code is.  Should be an easy fix though.  Thanks!

**Comment by beasteers** [comment]
Lol! Yeah I was checking the git blame to see if it was new to 0.8.0 or something but I couldn't find anything 👀

I'm surprised it's never come up before tho!

But yayyy
