### ISSUE TITLE
Require backends argument in librosa.core.load()

### ISSUE THREAD

**Issue by qiuqiangkong** [librosa/librosa#1241]
When reading the same mp3 file, Mac and linux are returning different results. This is caused by Mac is using macca for default. It would be great to add a backends argument to librosa.core.load() for users to select "audioread.ffdec.FFmpegAudioFile".

**Comment by bmcfee** [comment]
I'd prefer not to get into the under-the-hood details of the audioread API -- in the long term, we hope to abandon audioread and rely entirely on libsndfile (once they get mp3 support).  Since audioread is only a secondary backend for librosa, exposing this API all the way up to the user level seems like it's inviting trouble.

**Comment by lostanlen** [comment]
Agreed. If portability is an issue, just use the codec in the command line (via `os.system`) and store to a temporary file (via a `with` context manager)

**Comment by qiuqiangkong** [comment]
Thanks Brian! Btw, just let you know I met the problem of, when reading a
1-second audio fo 44.1 kHz sampling rate, the librosa.core.load('.wav')
returns an array with a length of 44100, and librosa.core.load('.wav')
returns an array with a length of 45600.

**Comment by lostanlen** [comment]
@qiuqiangkong 44100 vs 45600 looks like a huge difference in length. Could it be that one of the two function calls returns the signal at a different sample rate?

(friendly reminder that l[ibrosa resamples on load](https://librosa.org/blog/2019/07/17/resample-on-load/) unless otherwise specified)

**Comment by bmcfee** [comment]
Closing this issue out, since I think we're in agreement that it's not an API change that we're keen on making.  If you need direct control over your audio backend, it's recommended to use a more low-level library directly rather than going through librosa.load.
