### ISSUE TITLE
Resample round trip may change number of samples

### ISSUE THREAD

**Issue by jonashaag** [librosa/librosa#1242]
**Describe the bug**

```pycon
>>> d1 = np.zeros(16000)
>>> d1.shape
(16000,)
>>> d2 = librosa.resample(d1, 16000, 43779)
>>> d2.shape
(43779,)
>>> d3 = librosa.resample(d2, 43779, 16000)
>>> d3.shape
(16001,)
```

The reason is that the accuracy of `ratio` in `resample` is limited by floating point resolution:

```pycon
>>> 16000/43779 * 43779
16000.000000000002
```

We can fix it by changed the computation from

```py
ratio = float(target_sr) / orig_sr
n_samples = int(np.ceil(y.shape[-1] * ratio))
```

to

```py
duration = y.shape[-1] / orig_sr
n_samples = int(np.ceil(target_sr * duration))
```

But I have no considered possible other floating point errors introduced by that change.

This is with latest librosa.

**Comment by bmcfee** [comment]
I'm not sure we can solve this problem entirely (nor should we).  In general, [floating point math is sensitive to the order of operations](https://discourse.julialang.org/t/array-ordering-and-naive-summation/1929).  Your proposed change of order helps in this example, but it may hurt in others.

More generally, we're always going to have round-off issues when doing fractional sample rate conversion, and I think this should be expected.  If a user is really finnicky about round-trip length preservation, it's probably best to pad the signal and trim accordingly at the end to the desired number of samples.

**Comment by jonashaag** [comment]
Agreed. In this case maybe we could also provide a parameter to explicitly set the expected size. Would be nothing more than a convenience shortcut for wrapping it in another fix_length though.

**Comment by lostanlen** [comment]
@jonashaag note that this is already the case in stft/istft.
Note that sample rate conversion relies on resampy as an external library: https://github.com/bmcfee/resampy
