### ISSUE TITLE
【Bug】Something went wrong in `y-axis` ; and the ticks are not in the middle of the retangle.

### ISSUE THREAD

**Issue by unbadfish** [librosa/librosa#1243]
**Describe the bug**

Something went wrong in `y-axis` when zoom in;
and the ticks are not in the middle of the retangle.

**To Reproduce**

```python
import numpy as np
import matplotlib.pyplot as plt
import librosa
import librosa.display

y, sr = librosa.load("music\\txj.flac", sr=None, duration=30.0)
f0, voiced_flag, voiced_probs = librosa.pyin(y, sr=sr, fmin=librosa.note_to_hz('C1'), fmax=librosa.note_to_hz('C8'))
times = librosa.times_like(f0, sr=sr)
C = librosa.cqt(y=y, sr=sr)
C_db = librosa.amplitude_to_db(np.abs(C), ref=np.max)
fig, ax = plt.subplots()
img = librosa.display.specshow(C_db, sr=sr, x_axis='time', y_axis='cqt_note', ax=ax, cmap='gray_r')
fig.colorbar(img, ax=ax, format="%+2.f dB")
ax.plot(times, f0, label='f0', color='cyan', linewidth=2)
ax.legend(loc='upper right')
ax.set(title='CQT - Time & f0')
plt.show()
```
and zoom in after plt show the fig

**Expected behavior**
The `y-axis` shou be like `G#4`, not `G#4-48`;
and the ticks should be placed in the middle of each retangle.

**Screenshots**

![Screenshot_2020-09-20_19-54-55](https://user-images.githubusercontent.com/61961263/93710801-cf8e9a80-fb7b-11ea-857d-7d163147ea03.png)

![Screenshot_2020-09-20_19-35-49](https://user-images.githubusercontent.com/61961263/93710810-dddcb680-fb7b-11ea-8669-c36dc8467cdf.png)

**Software versions***

```
Windows-7-6.1.7601-SP1
Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]
NumPy 1.19.1
SciPy 1.5.2
librosa 0.8.0
INSTALLED VERSIONS
------------------
python: 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]

librosa: 0.8.0

audioread: 2.1.8
numpy: 1.19.1
scipy: 1.5.2
sklearn: 0.23.2
joblib: 0.16.0
decorator: 4.4.2
soundfile: 0.10.3
resampy: 0.2.2
numba: 0.50.1

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
sphinxcontrib.versioning: None
sphinx-gallery: None
pytest: None
pytest-mpl: None
pytest-cov: None
matplotlib: 3.3.0
presets: None
```

**Comment by lostanlen** [comment]
Hello @unbadfish. I don't think that there is a bug. The ticks are placed exactly where the tick labels say they are.

Note that every yticklabel is a pitch name: for example `G#4-39`, which means the pitch class G#, at the fourth octave, minus 39 cents of a semitones. Those 39 cents correspond to the distance between the tick and the middle of the rectangle.

I'm not sure if there is an easy way in librosa to constrain matplotlib to only place yticks at equal-tempered semitone ("middle of the rectangle"), and never at microtonal locations.

However, @unbadfish, you can enforce this manually via the functions `ax.set_yticks` and `ax.set_yticklabels`
