### ISSUE TITLE
Difference in spectograms generated using `matplotlib` and `librosa`

### ISSUE THREAD

**Issue by AakashKumarNain** [librosa/librosa#1248]
**Describe the bug**

I have a 10 sec  audio file . If I generate the spectrogram using matplotlib, then I get a different number of timesteps as compared to the spectrogram generated by librosa.

**To Reproduce**
```python
import librosa
import numpy as np
import matplotlib.pyplot as plt

fs = 8000
nfft = 200
noverlap = 120
hop_length = 120

audio = librosa.core.load(path, sr=fs)

# Spectogram generated using matplotlib
spec, freqs, bins, _ = plt.specgram(audio, nfft, fs, noverlap = noverlap)

print(spec.shape)  # (101, 5511)


# Using librosa
spectrogram_librosa = np.abs(librosa.stft(audio,
                                              n_fft=nfft,
                                              hop_length=hop_length,
                                              win_length=nfft,
                                              window='hann')) ** 2
spectrogram_librosa_db = librosa.power_to_db(spectrogram_librosa, ref=np.max)

print(spectrogram_librosa_db.shape)   # (101, 3676)
```

**Expected behavior**
Both should be same if the parameters are same

**Software versions***
```
Python -> 3.7
numpy -> 1.17.4
librosa ->0.7.2
```

**Comment by bmcfee** [comment]
This is not a bug.  These are entirely different implementations, each with well documented behavior.

**Comment by AakashKumarNain** [comment]
@bmcfee Thank you for the response. Can you please tell which parameter is mainly responsible for such a huge diff? Maybe I have misundertsood something

**Comment by dpwe** [comment]
In plt.specgram, you're determining the spectrogram frame rate with
noverlap (overlap between successive windows); in librosa.stft, you use
hop_length (advance in the start point of successive windows).  You set
them both to be 120, but in fact they are constrained to sum to the window
length of 200.  So the librosa result of 3676 frames should correspond to
the plt.specgram output with noverlap = (200 - hop_length) = 80 points.

noverlap and hop_length encode the same parameter, but from different
perspectives, so you have to make them consistent.

  DAn.

**Comment by AakashKumarNain** [comment]
That makes sense. Thanks @dpwe
