### ISSUE TITLE
Loading stereo .mp3 with mono=False fails

### ISSUE THREAD

**Issue by lpryszcz** [librosa/librosa#125]
<pre><code>
> y, sr = librosa.load(audio_path, sr=sr, mono=False)

/usr/lib/python2.7/dist-packages/IPython/lib/display.pyc in _make_wav(self, data, rate)
    109             data = np.array(data,dtype=float)
    110             if len(data.shape) > 1:
--> 111                 raise ValueError("encoding of stereo PCM signals are unsupported")
    112             scaled = np.int16(data/np.max(np.abs(data))*32767).tolist()
    113         except ImportError:

ValueError: encoding of stereo PCM signals are unsupported
</code></pre>

version: 0.3.1

**Comment by vlkare** [comment]
data, sampling_rate = librosa.load('RawData/f11 (2).wav')
On ruuning the above code I am getting the Error given below:

ImportError                               Traceback (most recent call last)
<ipython-input-77-2d646e60b394> in <module>()
----> 1 data, sampling_rate = librosa.load('C:/Users/karev/Desktop/Yahoo/Speech-Emotion-Analyzer-master/Rawdata/f11 (2).wav')

C:\ProgramData\Anaconda3\lib\site-packages\librosa\core\audio.py in load(path, sr, mono, offset, duration, dtype, res_type)
    147 
    148             # tack on the current frame
--> 149             y.append(frame)
    150 
    151     if y:

C:\ProgramData\Anaconda3\lib\site-packages\librosa\core\audio.py in resample(y, orig_sr, target_sr, res_type, fix, scale, **kwargs)
    517     >>> np.vstack([y, z]).T
    518     array([[  0.000e+00,   1.000e+00],
--> 519            [  9.694e-01,   0.000e+00],
    520            [  4.759e-01,   0.000e+00],
    521            [ -7.357e-01,   1.000e+00],

C:\ProgramData\Anaconda3\lib\site-packages\resampy\core.py in resample(x, sr_orig, sr_new, axis, filter, **kwargs)
    118     x_2d = x.swapaxes(0, axis).reshape((x.shape[axis], -1))
    119     y_2d = y.swapaxes(0, axis).reshape((y.shape[axis], -1))
--> 120     resample_f(x_2d, y_2d, sample_ratio, interp_win, interp_delta, precision)
    121 
    122     return y

C:\ProgramData\Anaconda3\lib\site-packages\numba\dispatcher.py in _compile_for_args(self, *args, **kws)
    358                 val = arg.value if isinstance(arg, OmittedArg) else arg
    359                 try:
--> 360                     tp = typeof(val, Purpose.argument)
    361                 except ValueError as typeof_exc:
    362                     failed_args.append((i, str(typeof_exc)))

C:\ProgramData\Anaconda3\lib\site-packages\numba\dispatcher.py in _compile_for_args(self, *args, **kws)
    309         return call_template, pysig, args, kws
    310 
--> 311     def get_overload(self, sig):
    312         """
    313         Return the compiled function for the given signature.

C:\ProgramData\Anaconda3\lib\site-packages\numba\dispatcher.py in compile(self, sig)
    616         Reduce the instance for pickling.  This will serialize
    617         the original function as well the compilation options and
--> 618         compiled signatures, but not the compiled code itself.
    619         """
    620         if self._can_compile:

C:\ProgramData\Anaconda3\lib\site-packages\numba\dispatcher.py in compile(self, args, return_type)
     81 
     82     def _compile_cached(self, args, return_type):
---> 83         key = tuple(args), return_type
     84         try:
     85             return False, self._failed_cache[key]

C:\ProgramData\Anaconda3\lib\site-packages\numba\compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    868                      "inline calls to locally defined closures")
    869         pm.add_stage(self.stage_annotate_type, "annotate type")
--> 870         pm.add_stage(self.stage_ir_legalization,
    871                      "ensure IR is legal prior to lowering")
    872         pm.add_stage(self.stage_objectmode_backend, "object mode backend")

C:\ProgramData\Anaconda3\lib\site-packages\numba\compiler.py in __init__(self, typingctx, targetctx, library, args, return_type, flags, locals)
    269                         status.fail_reason = patched_exception
    270                         break
--> 271             else:
    272                 return None
    273 

C:\ProgramData\Anaconda3\lib\site-packages\numba\typing\context.py in refresh(self)
    140     def refresh(self):
    141         """
--> 142         Refresh context with new declarations from known registries.
    143         Useful for third-party extensions.
    144         """

C:\ProgramData\Anaconda3\lib\site-packages\numba\typing\context.py in load_additional_registries(self)
    596             #  and you call it with (int16, int16) arguments)
    597             return best
--> 598 
    599     def unify_types(self, *typelist):
    600         # Sort the type list according to bit width before doing

ImportError: cannot import name 'operatordecl'

**Comment by bmcfee** [comment]
@vlkare your issue is unrelated to the issue reported above, and appears to be due to a broken numba installation.
