### ISSUE TITLE
Shortcut/convenience layer

### ISSUE THREAD

**Issue by jonashaag** [librosa/librosa#1250]
**Is your feature request related to a problem? Please describe.**

When doing exploratory work, I always end up typing a lot of the same librosa spectrogram related commands over and over again. As an example, to visualize the log magnitude spectrogram of a file, you have to type:

```py
data, sr = librosa.core.load(filename, sr=None)
librosa.display.specshow(
  librosa.amplitude_to_db(
    np.abs(
      librosa.stft(data, ...)
    )
  ), y_axis="log", sr=sr, x_axis="time")
```

**Describe the solution you'd like**

I would like to start a discussion around adding a bunch of convenience shortcuts to librosa that span multiple abstractions, similar to `django.shortcuts`.

Magnitude spectrogram visualization in particular is the most common situation where I'm frustrated by the lack of such a convenience layer. Maybe we can add something along the lines of

```py
librosa.short.magspecshow(data, sr=sr)
librosa.short.magspecshow(data, sr=sr, y_axis="mel")
librosa.short.magspecshow(data, sr=sr, scale=None)  # scale defaults to "dB" which wraps amplitude_to_db(...)
# or even this?
librosa.short.magspecshow(filename)
```

This would also be helpful for other kinds of visualization at the least, for example

```
librosa.short.waveplot(filename)
```

Or for spectrogram loading as well:

```
spec, sr = librosa.short.magspec(filename)
```

**Describe alternatives you've considered**

The convenience layer could live in a separate library, with all its advantages and disadvantages.

**Comment by lostanlen** [comment]
Hello @jonashaag. As you say, starting your own module (`librief`? :D) and seeing how you like it is the best way to resolve this. 

It's true that pipelines such as
load -> stft -> abs -> amplitude_to_db -> specshow
are very common, and typing them in the command line may result cumbersome.

However, each of these functions have multiple keyword arguments, and many values are provided by default for convenience. A wrapper such as `magspecshow(filename)` will bundle all of these keyword arguments in a single function, whose docstring will be extremely long and complex. The net gain in user-friendliness is not obvious to me.

**Comment by bmcfee** [comment]
I'm intrigued by this suggestion. I think it will take quite a bit of thought and research to implement it well.

It seems like display is the main reason to implement something like this. I wonder if we could leverage GitHub code search to get a sense of the most common boilerplate code surrounding specshow calls?

**Comment by bmcfee** [comment]
Agreed.  I do think there's value in having a shortcut layer, but maybe it would be better as an external package.
