### ISSUE TITLE
Load mp3 file

### ISSUE THREAD

**Issue by jainilparikh** [librosa/librosa#1256]
HI,
I am trying to load a mp3 file using liborsa but I get the following error.

The issue started when I installed MAD package. Before that it worked fine.
I have uninstalled it in the current runtime .Still I face this issue.

I wasnt able to find a suitable solution on other sites.

AttributeError                           Traceback (most recent call last)

<ipython-input-46-bccb56f81763> in <module>()
----> 1 x, sr = librosa.load("Path_to_mp3", sr=44100)
      2 #print(SongLength)

2 frames

/usr/local/lib/python3.6/dist-packages/audioread/maddec.py in __init__(self, filename)
     26     def __init__(self, filename):
     27         self.fp = open(filename, 'rb')
---> 28         self.mf = mad.MadFile(self.fp)
     29         if not self.mf.total_time():  # Indicates a failed open.
     30             self.fp.close()

AttributeError: module 'mad' has no attribute 'MadFile
`

**Comment by lostanlen** [comment]
Hello @jainilparikh, this section from the README is potentially useful:
https://github.com/librosa/librosa#audioread-and-mp3-support

> 
> 
> To fuel `audioread` with more audio-decoding power (e.g., for reading MP3 files),
> you may need to install either *ffmpeg* or *GStreamer*.
> 
> *Note that on some platforms, `audioread` needs at least one of the programs to work properly.*
> 
> If you are using Anaconda, install *ffmpeg* by calling
> ```
> conda install -c conda-forge ffmpeg
> ```
> 
> If you are not using Anaconda, here are some common commands for different operating systems:
> 
> * Linux (apt-get): `apt-get install ffmpeg` or `apt-get install gstreamer1.0-plugins-base gstreamer1.0-plugins-ugly`
> * Linux (yum): `yum install ffmpeg` or `yum install gstreamer1.0-plugins-base gstreamer1.0-plugins-ugly`
> * Mac: `brew install ffmpeg` or `brew install gstreamer`
> * Windows: download binaries from this [website]( https://gstreamer.freedesktop.org/) 
> 
> For GStreamer, you also need to install the Python bindings with 
> ```
> pip install pygobject
> ```

**Comment by jainilparikh** [comment]
Thanks I was able to resolve it.
