### ISSUE TITLE
Working out (i) the key signature of a song and (ii) rhythm discontinuities /changes and variation in speed

### ISSUE THREAD

**Issue by AnthonyTheKoala** [librosa/librosa#1257]
I have two areas of interest, key signature of a song and on tempo - discontinuities/changes in rhythm and varying tempo.

**Key signature of a song**
When I studied music theory (a few years ago), the key signature of a tune was the last chord in the tune. 
* How does one using librosa determine the key signature of a tune where the tune fades down = never concludes or where the tune ends in a chord unexpectedly in a different chord from the rest of the melody, To illustrate an unexpected key signature at the end of the song is "Summer Samba" played by keyboardist Walter Wanderley where the ending is different from main melody.

Question how key signature achieved in librosa especially where the tune fades down or ends in a key not part of the main body of the tune ?

**Changes/discontinuities in the music, a change in the rhythm and varying tempo.**
To illustrate in the tune "Do You Know The Way To San Jose" there are abrupt changes in rhythm from bossa nova to another rhythm style. And where there is no rhythm = brake in music.
Another case of rhythm changes is the acceleration and deceleration of the tempo of a tune.

Question. Do you have to break the tune in segments in order to analyse the rhythm in librosa. 
Question; If a tune has a regular rhythm but accelerates and/or decelerates, how can librosa keep track of that.

Thank you
Anthony of Sydney

**Comment by lostanlen** [comment]
Hello @AnthonyTheKoala, these questions are better suited to the librosa forum:
https://groups.google.com/d/forum/librosa

I recommend you read

Pauwels, J; O'Hanlon, K; Gómez, E; Sandler, M; Proceedings of the 20th Conference of the International Society for Music Information Retrieval (ISMIR), 2019.
"20 Years of Automatic Chord Recognition from Audio"
https://qmro.qmul.ac.uk/xmlui/handle/123456789/62088

and

Fuentes, M; McFee, B; Crayencour, H; Essid, S; Bello, J.P. ; Proceedings of the 20th Conference of the International Society for Music Information Retrieval (ISMIR), 2019.
"Analysis of common design choices in deep learning systems for downbeat tracking"
https://hal.archives-ouvertes.fr/hal-02943467/document
