### ISSUE TITLE
spectral_bandwidth magnitude is reduced in half when using magnitude spectrogram as input 

### ISSUE THREAD

**Issue by fkutsukos** [librosa/librosa#1259]
Hey guys

I am trying to understand why librosa.feature.spectral_bandwidth is giving me different magnitude values of bandwidth when the input used is a magnitude spectrogram, instead of the typical input signal.

```

import matplotlib.pyplot as plt
import librosa

y, sr = librosa.load(librosa.ex('trumpet'))
spec_bw_from_audio = librosa.feature.spectral_bandwidth(y=y, sr=sr)

S, phase = librosa.magphase(librosa.stft(y=y))
spec_bw_from_specgram = librosa.feature.spectral_bandwidth(S=S)

print(spec_bw_from_audio.shape)
print(spec_bw_from_specgram.shape)
plt.figure(figsize=(15,4));
plt.plot(spec_bw[0,:]);
plt.plot(spec_bw2[0,:]);

```

![image](https://user-images.githubusercontent.com/26121077/97309113-e8b4f600-1861-11eb-9037-644a1fde98bf.png)

**Comment by bmcfee** [comment]
Very strange.  I was unable to reproduce this.   It looks like your plotting code uses different variables, maybe from a different run?  `spec_bw` instead of `spec_bw_from_audio`, and `bw2` instead of `from_specgram`.

Executing the code snippet you provided, I get the following:

```python
In [8]: import librosa 
   ...:  
   ...: y, sr = librosa.load(librosa.ex('trumpet')) 
   ...: spec_bw_from_audio = librosa.feature.spectral_bandwidth(y=y, sr=sr) 
   ...:  
   ...: S, phase = librosa.magphase(librosa.stft(y=y)) 
   ...: spec_bw_from_specgram = librosa.feature.spectral_bandwidth(S=S) 
   ...:  
   ...:                                                                         

In [9]: import numpy as np                                                      

In [10]: np.allclose(spec_bw_from_specgram, spec_bw_from_audio)                 
Out[10]: True
```

**Comment by fkutsukos** [comment]
@bmcfee you were right the plot was coming from another run. However i managed to reproduce the problem when i loaded the audio with **sr=None** , a sample rate different from the the native sampling rate (i.e. 44100 instead of 22050).
So, the problem was actually in the following line of code, where the sample rate was not provided and the result was having the bandwidth scaled down to half values.

spec_bw_from_specgram = librosa.feature.spectral_bandwidth(S=S)
spec_bw_from_specgram = librosa.feature.spectral_bandwidth(S=S, sr=sr)

![image](https://user-images.githubusercontent.com/26121077/97314411-fcfbf180-1867-11eb-8d29-17978f3a6361.png)

![image](https://user-images.githubusercontent.com/26121077/97314637-33397100-1868-11eb-8dad-775c30b0a87a.png)

Thank you for the feedback!

**Comment by bmcfee** [comment]
> when i loaded the audio with **sr=None** , a sample rate different from the the native sampling rate (i.e. 44100 instead of 22050).

Right, that's because your input signal will be twice as long, and the DFT frequencies will go from [0, 22050] instead of [0, 11025].
