### ISSUE TITLE
【Feature request】Provide a simplified cqt-f0 fig.

### ISSUE THREAD

**Issue by unbadfish** [librosa/librosa#1261]
# Provide a simplified `cqt-f0` fig

Is your feature request related to a problem? Please describe.
 I'm always frustrated when reading a cqt-f0 fig. I even treat it as a bug. See #1243 
1. Whether zoom in or not, some ticks may be placed near the edges of two rectangles, so each of them may refer to TWO different rectangles, which leads to confusion and inconvenience.
2. As I zoom in, some ticks are placed with “-48” like message, I have read the reason, but,I do think it need to be changed.
![截图_2020-09-20_19-54-55](https://user-images.githubusercontent.com/61961263/98464125-a2657c80-21fb-11eb-8663-a850ab276307.png)

Describe the solution you'd like
Now I’m going to repeat what I said:

Expected behavior:
The y-axis should be like `G#4`, not `G#4-48`;
and the ticks should be placed in the middle of each rectangle.

Describe alternatives you've considered
A paper, hand-made “ruler” with proper ticks is mentioned in #1243, I use a wide paper tape now. It’s NOT A JOKE.

Additional context
In fact, what I described is almost everything an amateur musician (maybe they are called “beginners” before) need when dealing our works.
I clearly know that some programmers may need old kind cqt-f0  fig, so I think Librosa should provide a simplified `cqt-f0` fig, instead of change the origin one.

**Comment by bmcfee** [comment]
> The y-axis should be like `G#4`, not `G#4-48`;

I disagree with this in general.  CQT frequencies may or may not line up to 12TET pitches.  We hide the cent deviations when the vertical axis spans more than one octave right now, but when zoomed in this close, it's helpful to know exactly what bin centers are being used.



> and the ticks should be placed in the middle of each rectangle.

This one is a bit subtle.  Matplotlib only recently (version 3 maybe?) added support for center-positioning non-uniformly spaced colormesh bins.  I think it may require incrementing our minimum matplotlib version dependency to make it work.  I'm not opposed to it in principle, but I do think it requires a bit of careful thought and planning around release cycles to do it properly.

**Comment by bmcfee** [comment]
Is there anything still needing work on this issue, or did #1290 resolve this sufficiently?
