### ISSUE TITLE
Tempo comes out to be twice the ground truth value

### ISSUE THREAD

**Issue by yashSingodia** [librosa/librosa#1262]
The tempo in BPM calculated through librosa.beat_track function comes out to be twice or half the ground truth BPM

**Comment by bmcfee** [comment]
1. Please use the issue templates we provide.
2. This is not a bug.  Tempo estimation is exactly that: an estimation.  If the tempo returned by the method is not what you expect, try changing the the prior (eg, start_bpm=60 instead of 120).
