### ISSUE TITLE
Question - Octave Error

### ISSUE THREAD

**Issue by yashSingodia** [librosa/librosa#1263]
I have a dataset of 1000 songs and my task is to find tempo of those songs. I tried librosa.beat_track function. It works fine for most of the songs but in some cases the tempo in BPM is a fraction of the ground truth value (OCTAVE ERROR).

It would be really grateful if someone could tell me how to resolve this issue of OCTAVE ERROR for some songs.
Thanks

**Comment by lostanlen** [comment]
Hello @yashSingodia, consider using the tempo estimator of Essentia:
https://essentia.upf.edu/reference/std_TempoTapDegara.html

(duplicate of #1262)
