### ISSUE TITLE
Misleading documentation

### ISSUE THREAD

**Issue by OverLordGoldDragon** [librosa/librosa#1265]
[stft docs](https://github.com/librosa/librosa/blob/main/librosa/core/spectrum.py#L86) state `hop_length` does not affect frequency resolution; this isn't true. The _per-point_ resolution is unaffected, but that of the _time-frequency plane_ is, and any `hop_length` greater than 1 guarantees loss of analysis information for most practical signals, and loss of reconstruction information except for certain windows with specific `hop_length`s.

**Comment by bmcfee** [comment]
Sorry, but I don't understand your comment.

The frequency resolution is `sr/nfft`, and this does not depend on the hop length in any way.

**Comment by lostanlen** [comment]
Hello @OverLordGoldDragon,

The documentation is correct.

The frequency resolution of a windowed Fourier atom is defined as inversely proportional to the energy spread around its center frequency. This energy spread is independent from the choice of discretization, whether orthogonal or redundant. A fortiori, the impact of `hop_length` on the reconstruction error is an entirely separate question.

In practice, if you wish to estimate empirically the frequency resolution of a time--frequency representation, what you can do is to pass a sine wave of frequency f and measure the energy spread around f. Denoting by Delta(f) this energy spread, the frequency resolution can be defined as 1/Delta(f). Note that Delta(f) is constant for STFT and is proportional to f for CQT.

Conversely:

> any hop_length greater than 1 guarantees loss of analysis information for most practical signals

it's not that simple. I suggest you read on Non-Stationary Gabor Transform (NSGT) to see how the hop_length may be above 1 while still allowing perfect reconstruction. 

P. Balazs, M. Dörfler, F. Jaillet, N. Holighaus, and G. A. Velasco. Theory, implementation and applications of nonstationary Gabor frames. J. Comput. Appl. Math., 236(6):1481--1496, 2011
https://www.univie.ac.at/nonstatgab/pdf_files/badohojave11_04042011.pdf

**Comment by OverLordGoldDragon** [comment]
@lostanlen I distinguished between _analysis_ information and _reconstruction_ information; take STFT of amplitude-modulated signal with sufficiently high modulation frequency, and its instantaneous frequency will not be captured by any window unless `hop_length = 1`. Whether or not `hop_length != 1` allows perfect reconstruction is window-dependent, which also is unstated. If the library defines "frequency resolution" only per-point, that should be explicitly stated, as it isn't the sole definition.

**Comment by bmcfee** [comment]
> If the library defines "frequency resolution" only per-point, that should be explicitly stated, as it isn't the sole definition.

If we meant "time-frequency resolution", we would have said "time-frequency resolution".  "Frequency resolution", insofar as I've ever seen it used and what I take to be most people's expectation, would be the resolution in the frequency direction.  This, as previously stated, is `sr/nfft` and not a function of hop length.

I'm not really sure what you mean by "per point", but I see no reason to change the documentation here.

**Comment by OverLordGoldDragon** [comment]
@bmcfee There's "frequency" in "time-frequency"; methods like [synchrosqueezing](https://arxiv.org/abs/0912.2437) rely on instantaneous frequency information to accurately extract components per modulation model (AM+FM-decoupled).

Regardless, strictly speaking you're correct; resolution purely along frequency axis, disregarding its higher order derivatives or other analysis parameters, is unaffected. It's why I titled "misleading" rather than "wrong"; part of what motivated my post is a few questions I've seen on Stack Exchange being surprised or confused about results when using high `hop_length`. 

Experienced users don't need docs to know said frequency resolution's unaffected, but it's those less familiar that might trip on "frequency is captured equally well". This is more of a design decision - feel free to proceed as you see fitting.

**Comment by OverLordGoldDragon** [comment]
@lostanlen A nice paper, thanks for referring; I did wonder what an invertible time- & frequency-adaptive transform would look like. From a glance around `librosa` I didn't find NSGT, but there is fortunately a [Python port](https://github.com/grrrr/nsgt).
