### ISSUE TITLE
Can't read mp3 from BytesIO: File contains data in an unknown format.

### ISSUE THREAD

**Issue by ttencate** [librosa/librosa#1267]
**Describe the bug**
An MP3 file that can be loaded just fine from disk fails to be loaded when offered as an `io.BytesIO` object.

If this is a known restriction, it could be documented better.

**To Reproduce**
```
import librosa
import io

# This works fine.
print(librosa.load('/tmp/test.mp3'))

# This doesn't.
with open('/tmp/test.mp3', 'rb') as f:
    data = f.read()
print(librosa.load(io.BytesIO(data)))
```

**Actual output**

```
/.../.venv/lib/python3.8/site-packages/librosa/core/audio.py:162: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
(array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), 22050)
Traceback (most recent call last):
  File "/tmp/test.py", line 10, in <module>
    print(librosa.load(io.BytesIO(data)))
  File "/.../.venv/lib/python3.8/site-packages/librosa/core/audio.py", line 165, in load
    raise (exc)
  File "/.../.venv/lib/python3.8/site-packages/librosa/core/audio.py", line 146, in load
    with sf.SoundFile(path) as sf_desc:
  File "/.../.venv/lib/python3.8/site-packages/soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/.../.venv/lib/python3.8/site-packages/soundfile.py", line 1183, in _open
    _error_check(_snd.sf_error(file_ptr),
  File "/.../.venv/lib/python3.8/site-packages/soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening <_io.BytesIO object at 0x7ff3086254f0>: File contains data in an unknown format.
```

**Software versions**

```
Linux-5.8.14-arch1-1-x86_64-with-glibc2.2.5
Python 3.8.6 (default, Sep 30 2020, 04:00:38) 
[GCC 10.2.0]
NumPy 1.18.2
SciPy 1.5.4
librosa 0.8.0
INSTALLED VERSIONS
------------------
python: 3.8.6 (default, Sep 30 2020, 04:00:38) 
[GCC 10.2.0]

librosa: 0.8.0

audioread: 2.1.9
numpy: 1.18.2
scipy: 1.5.4
sklearn: 0.23.2
joblib: 0.17.0
decorator: 4.4.2
soundfile: 0.10.3
resampy: 0.2.2
numba: 0.51.2

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
sphinxcontrib.versioning: None
sphinx-gallery: None
pytest: None
pytest-mpl: None
pytest-cov: None
matplotlib: 3.2.1
presets: None
```

**Comment by bmcfee** [comment]
The problem here is that mp3 is not supported by soundfile (yet), so librosa will fall back to audioread.  Audioread doesn't generally support BytesIO input (because it in turn wraps several possible decoder backends, like ffmpeg, gstreamer, etc).

I'd be open to expanding the documentation here, but don't have the bandwidth to handle it myself right now.

**Comment by gabriben** [comment]
is there a workaround for this? thx

**Comment by gabriben** [comment]
thx @ttencate. Here is my solution for a gcs bucket. I couldn't figure out for sure, but I hope `blob.download_to_file` doesn't somehow force save to disk.
`%%time 
blobs_iterator = bucket.list_blobs(prefix=prefix)

i = 1
for blob in blobs_iterator:
    if blob.name.endswith('.mp3'):
        b = blob.download_as_bytes()
        with tempfile.NamedTemporaryFile(suffix='.mp3', prefix=os.path.basename("thisSong")) as tf:
            tf_directory = os.path.dirname(tf.name)
            blob.download_to_file(tf)
        print(os.listdir(tf_directory))
        y, sr = librosa.load(tf_directory + "/thisSong.mp3")
        i += 1
    if i > 10:
        break`

I need to do that over millions of songs, I wonder if converting them to .mp3 to .wav first via ffmpeg isn't faster. I'll try that and compare

**Comment by gabriben** [comment]
Just compared with writing the ten songs on disk. This is > 2x slower. The solution above probably works then to avoid writing on disk
```
%%time 
blobs_iterator = bucket.list_blobs(prefix=prefix)

i = 1
for blob in blobs_iterator:
    if blob.name.endswith('.mp3'):
        fn = "../../music/" + blob.name.split("/")[2]
        blob.download_to_filename(fn)
        y, sr = librosa.load(fn)
        i += 1
    if i > 10:
        break  
```

**Comment by xuboot** [comment]
In the end how did you solve it, I currently have this need to stream binary audio data from http requests for librosa analysis，
![image](https://user-images.githubusercontent.com/54123895/156965990-9928f6b1-a1ea-4612-8a61-88b2e8ee510e.png)

I read that I need to read the audio file from http, but if this is not possible, is there a good solution

error:
     
![image](https://user-images.githubusercontent.com/54123895/156966025-dea5e63c-6915-4f5d-8900-dea1c43ee619.png)

Do you need to modify the source code, but this is a bit complicated！
how to solve this problem？

**Comment by ttencate** [comment]
@xuboot See my [earlier comment](https://github.com/librosa/librosa/issues/1267#issuecomment-1054032412).
