### ISSUE TITLE
pip install fails on llvmlite while installing Librosa in MacOS BigSur

### ISSUE THREAD

**Issue by SamratDe** [librosa/librosa#1270]
llvmlite is showing error while installing librosa. I am using MacOS BigSur and the latest version of pip. The exact error is pasted below -

```
Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tq/7h23qgpn7pvcgr4thxpwxjph0000gn/T/pip-install-jz4vwh7l/llvmlite_7b78f3eaa3f44d6bb0fcc7816cc1635b/setup.py'"'"'; __file__='"'"'/private/var/folders/tq/7h23qgpn7pvcgr4thxpwxjph0000gn/T/pip-install-jz4vwh7l/llvmlite_7b78f3eaa3f44d6bb0fcc7816cc1635b/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/tq/7h23qgpn7pvcgr4thxpwxjph0000gn/T/pip-record-qqe38zm7/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.9/include/python3.9/llvmlite
         cwd: /private/var/folders/tq/7h23qgpn7pvcgr4thxpwxjph0000gn/T/pip-install-jz4vwh7l/llvmlite_7b78f3eaa3f44d6bb0fcc7816cc1635b/
    Complete output (29 lines):
    running install
    running build
    got version from file /private/var/folders/tq/7h23qgpn7pvcgr4thxpwxjph0000gn/T/pip-install-jz4vwh7l/llvmlite_7b78f3eaa3f44d6bb0fcc7816cc1635b/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 /private/var/folders/tq/7h23qgpn7pvcgr4thxpwxjph0000gn/T/pip-install-jz4vwh7l/llvmlite_7b78f3eaa3f44d6bb0fcc7816cc1635b/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/private/var/folders/tq/7h23qgpn7pvcgr4thxpwxjph0000gn/T/pip-install-jz4vwh7l/llvmlite_7b78f3eaa3f44d6bb0fcc7816cc1635b/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 420, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 501, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 947, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1819, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/private/var/folders/tq/7h23qgpn7pvcgr4thxpwxjph0000gn/T/pip-install-jz4vwh7l/llvmlite_7b78f3eaa3f44d6bb0fcc7816cc1635b/ffi/build.py", line 191, in <module>
        main()
      File "/private/var/folders/tq/7h23qgpn7pvcgr4thxpwxjph0000gn/T/pip-install-jz4vwh7l/llvmlite_7b78f3eaa3f44d6bb0fcc7816cc1635b/ffi/build.py", line 185, in main
        main_posix('osx', '.dylib')
      File "/private/var/folders/tq/7h23qgpn7pvcgr4thxpwxjph0000gn/T/pip-install-jz4vwh7l/llvmlite_7b78f3eaa3f44d6bb0fcc7816cc1635b/ffi/build.py", line 107, in main_posix
        raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tq/7h23qgpn7pvcgr4thxpwxjph0000gn/T/pip-install-jz4vwh7l/llvmlite_7b78f3eaa3f44d6bb0fcc7816cc1635b/setup.py'"'"'; __file__='"'"'/private/var/folders/tq/7h23qgpn7pvcgr4thxpwxjph0000gn/T/pip-install-jz4vwh7l/llvmlite_7b78f3eaa3f44d6bb0fcc7816cc1635b/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/tq/7h23qgpn7pvcgr4thxpwxjph0000gn/T/pip-record-qqe38zm7/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.9/include/python3.9/llvmlite Check the logs for full command output.
```

**To Reproduce**
```
pip install librosa
```

**Expected behavior**
Expected librosa to install but it is showing error while installing llvmlite

**Software versions***
```
macOS-10.16-x86_64-i386-64bit
Python 3.9.0 (v3.9.0:9cf6752276, Oct  5 2020, 11:29:23) 
[Clang 6.0 (clang-600.0.57)]
NumPy 1.19.4
SciPy 1.5.4
```

**Comment by bmcfee** [comment]
This is an llvmlite problem, not a librosa problem.  You may want to consult this thread: https://github.com/numba/numba/issues/6345

**Comment by SamratDe** [comment]
Yes they don't have wheels for Python version 3.9 yet. I downgraded my Python version to 3.6 and it worked.

**Comment by musicnerd** [comment]
I'm sorry developers, but I don't think it's acceptable to build your software with multiple dependencies, but then when _those_ dependencies can't install (and therefore people can't use/access your software without significant headache) you simply wipe your hands and say "not our problem"?? Either remove the dependencies or work with those teams to fix the issue.  Having to compile a dependency package from source is unacceptable for beginners.  For the record, I had no problem installing on MacOS (Mojave), but can't install on Windows10 due to same issue as OP.

**Comment by bmcfee** [comment]
@musicnerd LLVM (lite) is an enormous package and well beyond the scope of what we can reasonably contribute to, even if we had infinite bandwidth. (We don't.)  It's also too far down the dependency stack for us to "remove" as a dependency.

We've pushed the issue upstream to the people best equipped to manage it, and yes, it's "not our problem".  Please be patient: open source is a collaborative effort.

**Comment by lostanlen** [comment]
For future reference, here is the open pull request enabling Python 3.9 support in numba: https://github.com/numba/numba/pull/6579
At the time of writing, build 90 passes CPU smoketest on all platforms except for Python 3.9, linux-ppc64le, NumPy 1.19

**Comment by stuartarchibald** [comment]
For the future, `librosa` depends on `numba` which depends on `llvmlite` (which encapsulates the `LLVM` compiler).

From a Numba point of view, Python 3.9 support turned out to be somewhat challenging, some of the details are here: https://github.com/numba/numba/issues/6345#issuecomment-738696458, it took a while to figure everything out. Good news is that some development packages should ship soon (PR https://github.com/numba/numba/pull/6579 has just been approved, `llvmlite` PR was approved a while back https://github.com/numba/llvmlite/pull/671). Thanks for your understanding and patience.

**Comment by bmcfee** [comment]
Thanks @stuartarchibald !   Glad to know a fix is in the works.

**Comment by stuartarchibald** [comment]
@bmcfee no problem :) The build is running now, there should be conda packages available in Numba's `dev` channel soon (may be a day for everything to build and test), I anticipate test wheels will follow in due course.
```bash
conda install -c numba/label/dev numba
```
(usual caveats about development versions apply!).

**Comment by minons1** [comment]
If someone stumbled upon this, try to downgrade your numpy version between v1.22 - v2.0.2, this solve my issue on installing librosa on python3.11.9

you can read more on my [gist](https://gist.github.com/minons1/dc37e042939c8c60689af86fdb4b580f)
