### ISSUE TITLE
Librosa.fearture.mfcc run out the cpu resource

### ISSUE THREAD

**Issue by yanghongjiazheng** [librosa/librosa#1271]
When I  run the code below, this process run out the cpu resource.
There are 32 processors. And the 'top' command  results is shown  
 %CPU %MEM     TIME+ COMMAND
  3198  0.1   6:53.12 python extractor.py

`  
files=os.listdir("mfcc_wav")
for i in files:
  audio,sr=soundfile.read("mfcc_wav/"+i)
  mfcc=librosa.feature.mfcc(audio,sr=sr,n_mfcc=40,hop_length=int(0.010*sr),n_fft=int(0.025*sr))`
`python: 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56)
[GCC 7.3.0]

librosa: 0.5.1

audioread: 2.1.8
numpy: 1.14.5
scipy: 1.5.1
scikit-learn: None
joblib: 0.16.0
decorator: 4.4.2
six: 1.15.0
resampy: 0.2.2

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
sphinxcontrib-versioning: None
matplotlib: None
numba: 0.42.0`

**Comment by yanghongjiazheng** [comment]
Can you help to figure out the reason causing this problem

**Comment by bmcfee** [comment]
We can only help if you include an error message or log demonstrating the failure.  Your post does not include anything that looks like an error message.

**Comment by lostanlen** [comment]
Hello @yanghongjiazheng, we haven't heard from you in a month. Hopefully you've managed to fix the problem.
For future reference, here's an example of parallel computation in librosa:
https://stackoverflow.com/questions/55487391/unable-to-use-multithread-for-librosa-melspectrogram

i suggest we close this issue. feel free to reopen if the problem persists.
