### ISSUE TITLE
Enhancement: Return the residual in median-filtering HPSS

### ISSUE THREAD

**Issue by sevagh** [librosa/librosa#1272]
There is a variant of the Drieger/Mueller/Disch HPSS algorithm (implemented by librosa) which does 2 passes:
1. The first pass does the harmonic, percussive, residual decomposition with a large t-f resolution (4096)
2. The second pass does the decompsition with a small t-f resolution (256), using the residual + percussive output of the first pass as an input

To support this, decompose.hpss function needs to return a residual component as well: https://github.com/librosa/librosa/blob/ceb862f6117f959bda0ecc04f6891ea2c80b0ce0/librosa/decompose.py#L171

That seems like a breaking change to the API (unless there's a more user-friendly way of doing that).

I'm willing to do the work if you agree it's OK to change the return values of decompose.hpss

**Comment by sevagh** [comment]
On second thought, I think it's fair to say anybody who wants to use the iterative version can write it themselves by using `decompose.hpss` in their own loop.

So the only real code change is to return the residual in decompose.hpss (to enable subsequent iterative implementations).

**Comment by sevagh** [comment]
Also, a key component of the Drieger 2014 paper is the use of a hard/binary mask instead of soft mask. This can also be incorporated into the hpss function (if the maintainers agree).

**Comment by bmcfee** [comment]
> On second thought, I think it's fair to say anybody who wants to use the iterative version can write it themselves by using `decompose.hpss` in their own loop.

Yeah, that was the thinking originally when we added residual support.



> So the only real code change is to return the residual in decompose.hpss (to enable subsequent iterative implementations).

I don't think we need this?  Residual is defined implicitly as `R = S - (H + P)`.

**Comment by sevagh** [comment]
Ah, true. I guess I was stuck on the literal paper computation of `Mask_R = 1 - (Mask_H + Mask_P)` before computing the residual. I never considered that using the spectra directly would be equivalent.

**Comment by sevagh** [comment]
I just realized that even going by the mask definition, I can simply return the masks and then use that to compute the residual mask. So it looks like the original API is already maximally flexible. I just had to read the documentation more carefully.
