### ISSUE TITLE
What is the latest python version librosa support?

### ISSUE THREAD

**Issue by underdogliu** [librosa/librosa#1274]
***BEFORE POSTING A BUG REPORT*** Please look through [existing issues (both open and closed)](https://github.com/librosa/librosa/issues?q=is%3Aissue) to see if it's already been reported or fixed!

**Describe the bug**
I am simply trying to call a program that is using librosa under python 3.8.3. But when I was trying to simply call `import librosa`, it failed with following error message shown below. 

I tried same configuration but using python 3.7.9 then the bug disappeared. importing and basic function is working like a charm. But I think it can be an issue anyway and I speculate that it may be mostly related to Numba, which recently has trouble on python >= 3.8. So I would like to confirm that before turning to Numba side.

**To Reproduce**
Simply open a python terminal and run below:
```
import librosa
```

**Expected behavior**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xuechen/miniconda3/envs/pytorch/lib/python3.8/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/home/xuechen/miniconda3/envs/pytorch/lib/python3.8/site-packages/librosa/core/__init__.py", line 6, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "/home/xuechen/miniconda3/envs/pytorch/lib/python3.8/site-packages/librosa/core/audio.py", line 12, in <module>
    import resampy
  File "/home/xuechen/miniconda3/envs/pytorch/lib/python3.8/site-packages/resampy/__init__.py", line 7, in <module>
    from .core import *
  File "/home/xuechen/miniconda3/envs/pytorch/lib/python3.8/site-packages/resampy/core.py", line 9, in <module>
    from .interpn import resample_f
  File "/home/xuechen/miniconda3/envs/pytorch/lib/python3.8/site-packages/resampy/interpn.py", line 7, in <module>
    @numba.jit(nopython=True, nogil=True)
AttributeError: module 'numba' has no attribute 'jit'
```

**Software versions***

```
Python 3.8.3
NumPy 1.19.2
SciPy 1.4.1
librosa 0.8.0 (with error, cannot import)
Numba 0.50.1 (latest from pip)
```

**Comment by bmcfee** [comment]
We do support python 3.8, which is included in our continuous integration build matrix.

It looks like you may have an outdated version of resampy installed though.  Can you try reinstalling that and see if it fixes the problem?

**Comment by underdogliu** [comment]
@bmcfee Hi thanks for the reply! I tried re-installing resampy 0.2.2 and updating numba to 0.52.0 and it works. I think we can close this issue but maybe some notices on latest version on all latest dependecies will be good at README will be good.

For pyhton 3.9, I have not tested but since numba has not finished its support on it I highly sspect it will work. Any hints on this one?

**Comment by bmcfee** [comment]
> I tried re-installing resampy 0.2.2 and updating numba to 0.52.0 and it works. I think we can close this issue but maybe some notices on latest version on all latest dependecies will be good at README will be good.

The install requirements already list 0.2.2 as the minimum, so I don't think there's much to be done documentation-wise. Were you on 0.2.2 previously?  If so, there might have just been an issue with old cached binaries; not sure we have a good way in general to detect or work around that.  (Seems like more of a numba issue, but I could be wrong.)



> For python 3.9, I have not tested but since numba has not finished its support on it I highly sspect it will work. Any hints on this one?

This is covered in the discussion on #1270 ; we're blocked on official support until the numba release drops.  But there's no other barrier that I'm aware of.

**Comment by hubinghan010102** [comment]
python3.11.2能安装librosa吗
