### ISSUE TITLE
Would support on more numpy integer types be a good idea?

### ISSUE THREAD

**Issue by underdogliu** [librosa/librosa#1275]
**Is your feature request related to a problem? Please describe.**
When playing with librosa especially with other audo libraries and numpy functions, I always meet erros from time to time by type errors where for example, `n_bins` requires `int` (as reflected by `isinstance()` in source code), but other integer types are not acceptable, for example `np.int64`. Would it be a good idea to support more integer types instead of asking users to transfer a numpy integer to a "pythonic" integer? I know it is a small thing but it can avoid some unexpected behaviors and additional bothering for users if done properly. 

**Describe the solution you'd like**
I can implement it and do tests if @bmcfee you think it's a good idea.

**Comment by bmcfee** [comment]
This is an interesting question, but I think it needs to be pinned down a bit more.

The short version: almost everywhere we check for `isinstance(..., int)`, it's because we intend to use the variable as a length (eg when allocating an output buffer) or as an index into an array.  These spots have mostly come up in response to futurewarnings or exceptions raised by numpy when we were less strict about types.

I'd be open to relaxing the type constraints to be more appropriate for each use case, but I do think it needs to be handled on a case-by-case basis.  It's probably a larger job than you're anticipating. :)

**Comment by dpwe** [comment]
Internet suggests

isinstance(b, (int, np.integer))

  DAn.

**Comment by underdogliu** [comment]
@dpwe sorry I don't understand. I don't think there is type like `np.integer` lol.

@bmcfee I believe that most of librosa data, if not all of them (don't know too much about this one, am I right?), are developed and transformed as numpy arrays. I am not having anything more like tensor integers for example, but adding several numpy integer types would be good I think. **But I do agree that they should be handled case-by-case.**

**Comment by bmcfee** [comment]
>  I don't think there is type like `np.integer`

np.integer is an abstract base class of integer dtypes, so @dpwe's proposed solution would work.



>  are developed and transformed as numpy arrays. I am not having anything more like tensor integers for example, but adding several numpy integer types would be good I think.

Not necessarily; many of the places where this comes up have to do with scalars, which may be python builtins or numpy scalars which quack like the builtins anyway.

Going back to the initial post, I'd like to see some examples of where our current implementation is problematic though.

**Comment by underdogliu** [comment]
@bmcfee yeah for `np.integer` I do found reference after replying. 

@dpwe sorry for lacking knowledge on that. I think your solution would work.

"I'd like to see some examples of where our current implementation is problematic though." -> an example can be as simple as `lpcs = librosa.lpc(frame, int(lp_order))`, where I have to add `int()` to transfer data type from `np.int64` to `int`, in order to make it work.

**Comment by bmcfee** [comment]
> where I have to add `int()` to transfer data type from `np.int64` to `int`, in order to make it work.

Indeed, that case is an exception to what I wrote earlier about our use of int types, and I agree that here we should relax it.  That said, if you're doing LPC with order ~ 2^63, you may be in for a bad time :laughing:
