### ISSUE TITLE
installing at jetson xavier nx 

### ISSUE THREAD

**Issue by ddoron9** [librosa/librosa#1276]
I'm getting trouble with installing librosa to jetson xavier nx (ubuntu 18.04) . expecting any help,.,.

(base) jetson@jetson-desktop:~$ pip install librosa
Collecting librosa
  Using cached librosa-0.8.0-py3-none-any.whl
Requirement already satisfied: numpy>=1.15.0 in ./miniforge3/lib/python3.8/site-packages (from librosa) (1.19.5)
Collecting audioread>=2.0.0
  Using cached audioread-2.1.9-py3-none-any.whl
Collecting decorator>=3.0.0
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting joblib>=0.14
  Using cached joblib-1.0.0-py3-none-any.whl (302 kB)
Collecting numba>=0.43.0
  Using cached numba-0.52.0.tar.gz (2.1 MB)
Requirement already satisfied: setuptools in ./miniforge3/lib/python3.8/site-packages (from numba>=0.43.0->librosa) (49.6.0.post20201009)
Collecting llvmlite<0.36,>=0.35.0
  Using cached llvmlite-0.35.0.tar.gz (121 kB)
Collecting pooch>=1.0
  Using cached pooch-1.3.0-py3-none-any.whl (51 kB)
Requirement already satisfied: requests in ./miniforge3/lib/python3.8/site-packages (from pooch>=1.0->librosa) (2.25.1)
Collecting resampy>=0.2.2
  Using cached resampy-0.2.2-py3-none-any.whl
Requirement already satisfied: six>=1.3 in ./miniforge3/lib/python3.8/site-packages (from resampy>=0.2.2->librosa) (1.15.0)
Collecting scikit-learn!=0.19.0,>=0.14.0
  Using cached scikit-learn-0.24.1.tar.gz (7.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting scipy>=1.0.0
  Using cached scipy-1.6.0-cp38-cp38-manylinux2014_aarch64.whl (26.1 MB)
Collecting soundfile>=0.9.0
  Using cached SoundFile-0.10.3.post1-py2.py3-none-any.whl (21 kB)
Requirement already satisfied: cffi>=1.0 in ./miniforge3/lib/python3.8/site-packages (from soundfile>=0.9.0->librosa) (1.14.4)
Requirement already satisfied: pycparser in ./miniforge3/lib/python3.8/site-packages (from cffi>=1.0->soundfile>=0.9.0->librosa) (2.20)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
Collecting appdirs
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting packaging
  Using cached packaging-20.8-py2.py3-none-any.whl (39 kB)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Requirement already satisfied: certifi>=2017.4.17 in ./miniforge3/lib/python3.8/site-packages (from requests->pooch>=1.0->librosa) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in ./miniforge3/lib/python3.8/site-packages (from requests->pooch>=1.0->librosa) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in ./miniforge3/lib/python3.8/site-packages (from requests->pooch>=1.0->librosa) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./miniforge3/lib/python3.8/site-packages (from requests->pooch>=1.0->librosa) (1.26.2)
Building wheels for collected packages: numba, llvmlite, scikit-learn
  Building wheel for numba (setup.py) ... error
  ERROR: Command errored out with exit status -4:
   command: /home/jetson/miniforge3/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cevd6w_e/numba_a35c8b6698e04aa49896c4dc950210c5/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cevd6w_e/numba_a35c8b6698e04aa49896c4dc950210c5/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-h3qcvksk
       cwd: /tmp/pip-install-cevd6w_e/numba_a35c8b6698e04aa49896c4dc950210c5/
  Complete output (0 lines):
  ----------------------------------------
  ERROR: Failed building wheel for numba
  Running setup.py clean for numba
  ERROR: Command errored out with exit status -4:
   command: /home/jetson/miniforge3/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cevd6w_e/numba_a35c8b6698e04aa49896c4dc950210c5/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cevd6w_e/numba_a35c8b6698e04aa49896c4dc950210c5/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /tmp/pip-install-cevd6w_e/numba_a35c8b6698e04aa49896c4dc950210c5
  Complete output (0 lines):
  ----------------------------------------
  ERROR: Failed cleaning build dir for numba
  Building wheel for llvmlite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/jetson/miniforge3/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cevd6w_e/llvmlite_9ac4f46a0fd9419f8f079fc4495b483c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cevd6w_e/llvmlite_9ac4f46a0fd9419f8f079fc4495b483c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-huo71ul2
       cwd: /tmp/pip-install-cevd6w_e/llvmlite_9ac4f46a0fd9419f8f079fc4495b483c/
  Complete output (15 lines):
  running bdist_wheel
  /home/jetson/miniforge3/bin/python3.8 /tmp/pip-install-cevd6w_e/llvmlite_9ac4f46a0fd9419f8f079fc4495b483c/ffi/build.py
  LLVM version... 6.0.0
  
  Traceback (most recent call last):
    File "/tmp/pip-install-cevd6w_e/llvmlite_9ac4f46a0fd9419f8f079fc4495b483c/ffi/build.py", line 191, in <module>
      main()
    File "/tmp/pip-install-cevd6w_e/llvmlite_9ac4f46a0fd9419f8f079fc4495b483c/ffi/build.py", line 181, in main
      main_posix('linux', '.so')
    File "/tmp/pip-install-cevd6w_e/llvmlite_9ac4f46a0fd9419f8f079fc4495b483c/ffi/build.py", line 143, in main_posix
      raise RuntimeError(msg)
  RuntimeError: Building llvmlite requires LLVM 10.0.x or 9.0.x, got '6.0.0'. Be sure to set LLVM_CONFIG to the right executable path.
  Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.
  
  error: command '/home/jetson/miniforge3/bin/python3.8' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
  Building wheel for scikit-learn (PEP 517) ... |

**Comment by bmcfee** [comment]
This is an issue with llvmlite, not librosa.  I'm not sure what their support status is for jetson, but I suggest checking over there.

**Comment by stuartarchibald** [comment]
Suggest following the instructions here for getting Numba installed https://numba.readthedocs.io/en/latest/user/installing.html#installing-on-linux-armv8-aarch64-platforms, packages are available from the `numba` channel.

[This post](https://numba.discourse.group/t/fixing-filenotfounderror-errno-2-no-such-file-or-directory-llvm-config/510) covers the specific error above, what to do next depends on your use case.
