### ISSUE TITLE
Cropping and resampling leads to inconsistent results

### ISSUE THREAD

**Issue by dpwe** [librosa/librosa#128]
I would like to be able to read and concatenate subranges with librosa.load, and have them be exactly what you'd get with a seemingly-equivalent single load, e.g.

> > > y1, sr = librosa.load(librosa.util.example_audio_file(), sr=40000, duration=0.1)
> > > y2, sr = librosa.load(librosa.util.example_audio_file(), sr=40000, duration=0.1, offset=0.1)
> > > y3, sr = librosa.load(librosa.util.example_audio_file(), sr=40000, duration=0.2, offset=0.0)
> > > print sum(np.append(y1, y2) != y3)
> > > 38

I was thinking "0" would be better.

.. but this has more serious challenges than the last sample, it also depends on the adjusting the starting sample due to offset to be consistent.

  DAn.

**Comment by bmcfee** [comment]
Following up on this:

- Testing this bug should disable resampling (`sr=None`), just to eliminate all the irrelevant variables.
- It seems to be codec-dependent.  Using wav-file input, either stereo or mono, I get bit-level precision.
- With ogg and mp3, I still get failure as originally reported.  I suspect this is down to how the different codecs batch up frames, and it's really not something that I think we should invest in circumventing.

Any objections to closing this one?

**Comment by bmcfee** [comment]
A bit more investigation:

- wav, au, and m4a give total agreement
- mp3 messes up only in the first frame; trimming everything past the first 1364 samples (at 44KHz) gets bit precision
- flac and ogg are messed up all the way through

In terms of audioread backend, I get:

- :+1: wav : MadFile
- :+1: au : MadFile
- :+1:  m4a : subprocess
- :-1: mp3 : MadFile
- :-1:  flac : subprocess
- :-1:  ogg : subprocess

So... it's a total mixed bag.  I still think we should punt this one, and maybe it will resolve itself through switching over to pysoundfile?

**Comment by dpwe** [comment]
I agree with punting on this for now.  But I want to clear up a confusion.

The basic problem is that reading a sound file is not stateless in some
circumstances.  One obvious case is if reading the data involves some kind
of filtering, in which case the impulse response of that filter will make
the current samples depend on the past.  The reconstruction filter of
subband encoding schemes such as MP3 introduces some of this, so typically
you have to back up a few 10s of ms to "warm up" when seeking into such a
stream.  I suspect this is the somehow the source of the codec-specific
problems you report.

But the original problem I was raising was when reading sound files *with
resampling*, as provided by librosa.  Then, there is a deeper problem: the
start sample index specified by a "seek" in the resample stream does not
necessarily map to an exact sample boundary in the original stream.

For example, let's say I have a sound file whose native sampling rate is 8
kHz.  But I use librosa to resample-on-read to 8001 Hz (I'm perverse like
that).  If I ask for 1 sec from the beginning, librosa loads in 8000
samples, then passes them through an 8000->8001 resampler - which
effectively interpolates the original waveform and delivers 8001 samples.
Importantly, output sample 4000 is an estimate of the waveform more or less
midway between samples 3999 and 4000 of the input.

Now,  If I ask for 0.5 sec from 0.5 sec in, librosa loads the second half
of what it loaded last time, and puts it through the resampler.  But now
the first output sample, which we probably want to correspond to the 4000th
sample of the previous read (or maybe 4001, but one or the other) is now,
to first order, exactly sampled from sample 4000 of the input - *not*
midway between two input samples as in the previous case.

Here, the sub-sample offset incurred when mapping from an input seek point
specified in seconds to an actual frame offset in a discrete time stream is
inconsistent, and depends on the start time.

Put this way, it's not that obvious what the "right" solution is.  One
approach would be to always interpolate waveforms on read to match the
sub-sample delay implied by a start time that is not an exact multiple of
the sampling period.  But this seems desperately inefficient.

What I had in mind was keeping track of the rational resampling factor
(e.g., 8001/8000 in my example), then, when asked to seek to a particular
point in a resampled stream, the library backs up to the preceding integer
multiple of input sample blocks, which is the closest preceding input
sample that exactly aligns with an output sample.  Then, provided that
backs us up at least the forward-length of the resampling filter's impulse
response, we can read, resample, then discard the appropriate number of
samples in the resampled domain, to end up with samples that line up
correctly with the resampled stream we'd get by reading from the very
beginning of the file.

This is not trivial to get right, but it's not a huge inefficiency, and it
avoids a nasty surprise when someone reads in their 22,050 Hz wav file at
16 kHz, reading 1/8th of a second (2000 output samples, 2756.25 input
samples) at a time, concatenates them, then wonders where the clicks every
0.125 sec are coming from.

(BTW, I recently came across a bug very much like this in a production
system.  The glitches are quite audible if the input is something like a
sine tone.)

A work-around is insist that sampling rate is an integer number of samples
per second, and always use seek times that are a whole number of seconds,
*and* discard the first second of data you get, to avoid any
codec/resampling impulse response issues while you're at it.

  DAn.

**Comment by bmcfee** [comment]
Ok, that definitely clarifies things, thanks!

I was mainly concerned with the native sampling rate problem (if we can't get that right, we have zero hope of debugging with resampling), and lost track of the resampling issue.

I'm still seriously considering rewriting the load code to use pysoundfile ( #140 ), which might obviate any solutions we come up with, or introduce other problems of its own.  I suggest: A) we revisit this issue after deciding on (and/or porting to) pysoundfile, and B) not worry about it.  If a user (ie you) wants to be super careful about this, it wouldn't be difficult to write a function on top of load that buffers around the targeted chunk of data, resamples, and then does the appropriate slicing.  (Assuming that these quantities are easy to work out, that is.)

Sound good?

**Comment by dpwe** [comment]
Sounds good.

  DAn.

**Comment by bmcfee** [comment]
Resolved for now by merging #480

**Comment by turabihasan** [comment]
my example sound sr=44100 if i use sr=22050 in plotting using librosa what will be the problem?

**Comment by lostanlen** [comment]
Hello @turabihasan, make sure to pass `sr` to `librosa.get_duration`. It's 22050 by default
https://librosa.org/doc/latest/generated/librosa.get_duration.html
