### ISSUE TITLE
stft changes time resolution when center=False and n_fft changes

### ISSUE THREAD

**Issue by Feulo** [librosa/librosa#1280]
I am having a problem performing two stft for a signal with the same hop and window lengths but with a different number of fft points.
The problem occurs with the `frames_to_time` function too.

**To Reproduce**
```
import librosa
import numpy as np

# generates a signal with sr=100 and f0=10
sr=100
ts = np.arange(0, 1, 1/sr)
x = np.sin(2*np.pi*10*ts)

# computes the stft with n_fft=win_length=hop_length
n_fft = win_length = hop = 10
s1 = lb.stft(x, n_fft=n_fft, win_length=win_length, hop_length=hop,  center=False)
f1 = lb.fft_frequencies(sr, n_fft)
t1 = lb.frames_to_time(range(s1.shape[1]), sr=sr, hop_length=hop)
print(s1.shape, f1.shape, t1.shape)
#computes the stft with more points and fft but not changing win_length and hop_length
n_fft = 20
s2 = lb.stft(x, n_fft=n_fft, win_length=win_length, hop_length=hop,  center=False)
f2 = lb.fft_frequencies(sr, n_fft)
t2 = lb.frames_to_time(range(s2.shape[1]), sr=sr, hop_length=hop, n_fft=n_fft)
print(s2.shape, f2.shape, t2.shape)
```

I expected de output to be:
```
(6, 10) (6,) (10,)
(11, 10) (11,) (10,)
```
Since I'm still dividing the 100 samples into 10 windows of length 10,  but instead I got:

```
(6, 10) (6,) (10,)
(11, 9) (11,) (9,)
```
if I inspect the content of `t1`, `t2`, `f1` and `f2`:

```
f1 = [ 0. 10. 20. 30. 40. 50.]
f2 = [ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]
t1 = [0.05 0.15 0.25 0.35 0.45 0.55 0.65 0.75 0.85 0.95]
t2 = [0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
```
I can see that the frequency resolution has increased, but the time resolution has decreased instead of remaining the same.

I've tested in different environments but here's where I've tested last
```
Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0]
NumPy 1.19.5
SciPy 1.4.1
librosa 0.8.0
```
I know that are other issues related to this, but they don't include the `frames_to_time` part so I posted again.

**Comment by bmcfee** [comment]
This is expected and correct behavior. It is not changing time resolution, which depends on the hop length and sampling rate. What is changing is the duration as measured by frames. This is because centered analysis involves padding the signal with zeros, which generally increases the length of the signal.

**Comment by Feulo** [comment]
In the [STFT documentation](https://librosa.org/doc/0.8.0/generated/librosa.stft.html) it says:

> win_lengthint <= n_fft [scalar]

>    Each frame of audio is windowed by window of length win_length and then padded with zeros to match n_fft. 

So I was expecting that in both cases the 100 samples will be splited into blocks of 10 samples (`window_length`). The in the first case it will not be zero padded, but in the second one each block of 10 samples will be zero padded to have the length of 20 (`n_fft`) samples.

If it is not this way it works, what is de difference between `n_fft` and `win_length`?

**Comment by bmcfee** [comment]
> If it is not this way it works, what is de difference between `n_fft` and `win_length`?

`n_fft` is the number of analysis frequencies, or equivalently, the number of samples in each frame given to `fft()`.

`win_length` is the length of the window, which is typically the same as `n_fft`, but may be smaller if you want.  Samples outside the window (but within the frame) will be treated as zeros, and this allows you to get a higher (frequency) resolution FFT for a fixed window length.

Neither of these has anything to do with the time resolution (frames per second) of the spectrogram, which is entirely determined by the hop length and the sampling rate.

**Comment by Feulo** [comment]
>win_length` is the length of the window, which is typically the same as n_fft, but may be smaller if you want. Samples outside the window (but within the frame) will be treated as zeros, and this allows you to get a higher (frequency) resolution FFT for a fixed window length.

So, just to confirm I understood, when `win_length = n_fft` the signal is divided this way
![frame(1)](https://user-images.githubusercontent.com/12126743/107663055-b3de7a80-6c69-11eb-8ee0-e89d54075d96.png)

And when `2*win_length = n_fft`:

![frame_2](https://user-images.githubusercontent.com/12126743/107663057-b4771100-6c69-11eb-9f5f-770463de089f.png)

In the second case, I got 9 instead of 10 frames because the last frame finishes after the end of the signal, so it is not computed.
The time value for each frame is different because it is calculated at the center of the frame and not at the center of the window.

Is there any advantage of this implementation compared to the MATLAB/OCTAVE implementation where it divides the signal in windows and then complete each window with zeros until It has `n_fft` size? 

It will be possible to change the frame-window alignment? So I could have the windows left-aligned to the signal but the frame centered in the window?

**Comment by bmcfee** [comment]
> So, just to confirm I understood, when `win_length = n_fft` the signal is divided this way

Almost.  Your example also assumes `n_fft = hop_length` so the frames do not overlap.

> The time value for each frame is different because it is calculated at the center of the frame and not at the center of the window.
> ... 
> It will be possible to change the frame-window alignment?

This is what the `center=` option is for.



> Is there any advantage of this implementation compared to the MATLAB/OCTAVE implementation where it divides the signal in windows and then complete each window with zeros until It has `n_fft` size?

Our implementation decouples the frame length from the hop length.  You could equivalently express this as an overlap fraction, but that parametrization could introduce rounding errors, whereas ours is always exact.

**Comment by Feulo** [comment]
>Almost. Your example also assumes n_fft = hop_length so the frames do not overlap.
`n_fft=hop_length` only in the first case, in the second one `n_fft = 2*hop_length` so the frames do overlap, but `win_length=hop_length` so the windows don't overlap in both

>This is what the center= option is for.
I guess I found why I was not understanding: In librosa you first extract the frames of `n_fft` size( begging or centered at `y[t * hop_length]`) and then apply the window to frame (if `win_length < n_fft` samples outside the window are 0) and computes the FFT for the frame.
I was thinking that the first you extracted `win_length` frames beginning or centered at `y[t * hop_length]`), applied the window to it, and then if `n_fft > win_length` the frame was completed with zeros to match size `n_fft` (That's the way Matlab works if I remember well)
This way the `center=` option aligns both, window and frame, at the beginning or centered at `y[t * hop_length]`, because first, you extract the frame and then apply the window function. And that's why the end of the signal is discarded when `center=False`, because there is no padding in the end to complete the last frame.

If I understood, I guess we can close this issue. I was trying to create a set of spectrograms with the same frames but computing the DFT with a different number of points (completing the frames with zero) for each spectrogram. I guess I'll have to make it by hand instead of using the stft. Thanks for the explanations!

**Comment by bmcfee** [comment]
Ah, I see the confusion here.  The relevant code snippet is here:

https://github.com/librosa/librosa/blob/a53fa56bdb6695a994008d5b6ccd0100870a6036/librosa/core/spectrum.py#L208-L211

To clarify: what we actually do is construct the window, then pad it out to `n_fft` samples with zeros (symmetrically), and then apply it to each frame.  The window is always centered within the frame.  Calling with `center=False` means that we do not left-pad the signal prior to framing, so the first frame *starts* at sample 0 rather than being *centered* around sample 0.  (Or, more generally, starting or being centered at sample index `t * hop_length`.)

**Comment by Feulo** [comment]
I see, so for the example where the signal y has length 40, `n_fft = 20`, `hop_length = win_length = 10`, and `center=False` the frames will look like this:

![frame_2(1)](https://user-images.githubusercontent.com/12126743/107696971-5d853200-6c91-11eb-9d34-3d6217bb11c1.png)

I have 3 frames starting at samples 0, 10 and 20. The frame that would start at sample 30 is not created because the signal ends at sample 39 and there is no padding at the end of the signal

Because ` win_length < n_fft` the `(n_fft - win_length)/2 = 5` samples in the beginning of the signal won't be used, the same for the last (n_fft - win_length)/2 = 5`.

Finally, the `n_fft` parameter sets the frame size to be used and it's the number of points used in the DFT, therefore I can't have a number of points in the DFT greater than the frame size (using the stft function)

Thank you one more time for the clarifications, I will you the stft code as base for a custom function where I  can change the number of points in the DFT without changing the frame size.

**Comment by bmcfee** [comment]
Yes, that's correct.  A maybe simpler approach would be to just calculate how much padding you need on the right edge of the signal up front, pad it out, and then call the unmodified stft.  Whether or not that's better for you is ultimately down to your specific use case, but I wanted to float it as an option.

**Comment by Feulo** [comment]
Thanks for the hint. I will need to pad the left part of the signal  too, so I can compute the DFT of the first `(n_fft-win_length)/2` samples (especially if `n_fft` >> `win_length`) and then adjust the time 0 to the  real signal start (when using the `frames_to_time` function)
I'll try this approach first, I guess its simplier than reimplementing the stft.

**Comment by bmcfee** [comment]
Seems like this one is resolved, so I'm closing it out.  Feel free to reopen if it warrants further discussion.
