### ISSUE TITLE
Question about number of frames with center parameter in librosa.stft

### ISSUE THREAD

**Issue by SolomidHero** [librosa/librosa#1288]
Number of frames is different based on `center` parameter.
This difference distracts a little since there is also behaviour of dropping last windows if there are not enough points till `n_fft` (when `center=False`). With `center=True` for several last fft windows there even won't be enough samples, but it produces anyway.

For neural networks which produce some constant upsampling for each frame it is also crucial to use `center=False` (but tricky enough).

At this point, as I understand:
**with `center=True`: (match number window centers)**
```python
n_frames = len(wav) // hop_length
```
**with `center=False`: (drop all incomplete by `n_fft` windows)**
```python
n_frames = (len(wav) - n_fft) // hop_length + 1
```

So **that is why you may want** (in case of `center=False`) to pad your output/input/generated/etc wav with either:
- `n_fft - win_length` zeros to get only stft frames produced by windows with all valued points
- `n_fft` zeros to match number of frames as in `center=True` case
- `n_fft - hop_length` zeros to match network upsample factor

**Example:** Assume having ~1s of 24kHz wav (24042 samples) and network (upsample factor 100) that produce the same wav from stft features. We could either [`center=True` for stft and use slice [:-1]] or [zero pad end of wav with `n_fft - hop_length` points and `center=False` for stft]. If no pad in later, stft produce less by 1-5 frames. And network will produce 24000 samples. If we even wanted to use loss with some ground truth stft we use stft with could use pad to match its size.

Am I right? (I use both librosa and torch for stft extraction and ask here as torch implementation of stft is consistent with librosa). Also I wonder why with `center=False` stft uses `n_fft` as limiter, but not `win_length`?

**Comment by bmcfee** [comment]
I'm not exactly sure what the question is here, but I'll respond to the points as I interpret them.


> Number of frames is different based on `center` parameter.
> This difference distracts a little since there is also behaviour of dropping last windows if there are not enough points till `n_fft` (when `center=False`). With `center=True` for several last fft windows there even won't be enough samples, but it produces anyway.

When `center=True`, the signal is padded with zeros, so yes, there may be more frames.  This is correct and expected behavior.



> For neural networks which produce some constant upsampling for each frame it is also crucial to use `center=False` (but tricky enough).

I don't understand why this would matter. As long as you're correctly interpreting the data under whatever parameterization of the STFT was used, there should be no problem here.



> At this point, as I understand:
> **with `center=True`: (match number window centers)**
> n_frames = len(wav) // hop_length

The frame calculation is given [here](https://librosa.org/doc/latest/_modules/librosa/util/utils.html#frame):

```python
# Compute the number of frames that will fit. The end may get truncated.
    n_frames = 1 + int((len(y) - frame_length) / hop_length)
```
If `center=True`, then `len(y)` will have `n_fft // 2` samples padded to either side (for a total of `n_fft=frame_length` extra samples) prior to framing.

**Comment by SolomidHero** [comment]
Thank you! Now these semantics are more evident for me.
