### ISSUE TITLE
Cannot make Librosa run in Mac M1 in arm64 mode

### ISSUE THREAD

**Issue by albertojulian** [librosa/librosa#1292]
I have a Mac M1 and want to use tensorflow (which in a Mac M1 only runs in arm64 mode, AFAIK) and librosa. After installing miniforge, I could install numba and llvmlite for arm64:

```
conda install numba -c conda-forge
conda install llvmlite -c conda-forge
```

and then I could (apparently) install librosa with pip:

```
pip install librosa

```

But when trying to import librosa in python, it crashes:

```

>>> import librosa
Traceback (most recent call last):
  File "/Users/ajulian/miniforge3/envs/TF24_A3/lib/python3.8/site-packages/soundfile.py", line 143, in <module>
    _snd = _ffi.dlopen(_libname)
OSError: cannot load library '/usr/local/lib/libsndfile.dylib': dlopen(/usr/local/lib/libsndfile.dylib, 2): no suitable image found.  Did find:
	/usr/local/lib/libsndfile.dylib: mach-o, but wrong architecture
	/usr/local/Cellar/libsndfile/1.0.31/lib/libsndfile.1.dylib: mach-o, but wrong architecture

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ajulian/miniforge3/envs/TF24_A3/lib/python3.8/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/Users/ajulian/miniforge3/envs/TF24_A3/lib/python3.8/site-packages/librosa/core/__init__.py", line 6, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "/Users/ajulian/miniforge3/envs/TF24_A3/lib/python3.8/site-packages/librosa/core/audio.py", line 8, in <module>
    import soundfile as sf
  File "/Users/ajulian/miniforge3/envs/TF24_A3/lib/python3.8/site-packages/soundfile.py", line 162, in <module>
    _snd = _ffi.dlopen(_os.path.join(
OSError: cannot load library '/Users/ajulian/miniforge3/envs/TF24_A3/lib/python3.8/site-packages/_soundfile_data/libsndfile.dylib': dlopen(/Users/ajulian/miniforge3/envs/TF24_A3/lib/python3.8/site-packages/_soundfile_data/libsndfile.dylib, 2): image not found
>>>

```

**Software versions**

```
macOS-11.2-arm64-i386-64bit
Python 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 15:50:57) 
[Clang 11.0.1 ]
NumPy 1.20.1
SciPy 1.6.0
Numba 0.52.0
llvmlite 0.35.0

```

**Comment by bmcfee** [comment]
This looks like an upstream problem with the conda-forge build of libsndfile.  Tagging @wolfv as the most recent contributor on that feedstock -- sorry if I should be tagging someone else!

Meanwhile, @albertojulian you might want to try compiling libsndfile for your specific platform until the conda-forge packages get up to date on the M1.

**Comment by wolfv** [comment]
You need to rebuild librosa for arm64. You can read it up on conda forge knowledge base or search for blogposts or ask on Gitter.

I'm on mobile right now so can't properly respond. It's very easy though

**Comment by bmcfee** [comment]
> You need to rebuild librosa for arm64.

The librosa package is platform-neutral (noarch) and contains no compiled extensions.

**Comment by wolfv** [comment]
Libsndfile isn't and a migrator will migrate it on conda-forge

**Comment by wolfv** [comment]
just follow instructions here https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/ (e.g. make a PR that looks like this one: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1310)

**Comment by albertojulian** [comment]
Thanks a lot for your help @wolfv and @bmcfee. Just one question: What I have to add to osx_arm64.txt: "libsndfile" or "soundfile"?

**Comment by wolfv** [comment]
I think you can also avoid pip and install librosa from conda and not have these problems in the first place :)

**Comment by albertojulian** [comment]
In a Conda environment (miniforge) with python for arm64, if I run:
```
conda install -c conda-forge librosa
```
it doesn't find librosa.

**Comment by bmcfee** [comment]
Is this still an issue, or can we close it out?

**Comment by albertojulian** [comment]
Hi,
I could finally install librosa in my Mac M1 in arm64 mode the following way:

```
conda install numba -c conda-forge
conda install llvmlite -c conda-forge
conda install libsndfile -c conda-forge 
pip install librosa
```

So you can close the issue.

**Comment by bmcfee** [comment]
Great, thanks for confirming.

**Comment by wolfv** [comment]
@albertojulian why can you not install librosa from conda-forge?

**Comment by albertojulian** [comment]
@wolfv See previous message: librosa was not available in Conda-forge for arm64 when I had the need, one month ago.
