### ISSUE TITLE
Windows: after importing Csound, numba crashes (0xC0000005) during load/resample

### ISSUE THREAD

**Issue by Redict** [librosa/librosa#1294]
**Describe the bug**
When `librosa.load(file, sr=44100)` being called on Windows, application exits with `0xC0000005` error code

**To Reproduce**
Example:
```
import librosa

target_sr = 44100
audio, orig_sr = librosa.load(filename, sr=target_sr)
```

**Expected behavior**
File being processed correctly and program doesn't exists.

**Software versions**

```
>>> import platform; print(platform.platform())
Windows-10-10.0.19041-SP0
>>> import sys; print("Python", sys.version)
Python 3.9.2 (default, Mar  3 2021, 15:03:14) [MSC v.1916 64 bit (AMD64)]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.20.1
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.6.1
>>> import librosa; print("librosa", librosa.__version__)
librosa 0.8.0
>>>
>>> librosa.show_versions()
INSTALLED VERSIONS
------------------
python: 3.9.2 (default, Mar  3 2021, 15:03:14) [MSC v.1916 64 bit (AMD64)]

librosa: 0.8.0

audioread: 2.1.9
numpy: 1.20.1
scipy: 1.6.1
sklearn: 0.24.1
joblib: 1.0.1
decorator: 4.4.2
soundfile: 0.10.3
resampy: 0.2.2
numba: 0.53.0

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
sphinxcontrib.versioning: None
sphinx-gallery: None
pytest: None
pytest-mpl: None
pytest-cov: None
matplotlib: None
presets: None
```

**Comment by bmcfee** [comment]
Thanks for reporting this.  Could you please provide a complete traceback?  A single error-code is not enough information to diagnose the error, though I'm fairly confident it's upstream of us.

**Comment by Redict** [comment]
There is no traceback, application just crashes.

**Comment by bmcfee** [comment]
> There is no traceback, application just crashes.

That's pretty strange.

Is there anything more you can post here? A screen capture?  Anything about the file you're trying to load?

**Comment by Redict** [comment]
This is file I am trying to load: `https://dropmefiles.com/BxurK`
Its very strange, because when I do it in console its all fine, but when I execute it through function it crashes at breakpoint:
![image](https://user-images.githubusercontent.com/9623703/111847430-d410f180-8919-11eb-8396-8d1a88afe9b4.png)

**Comment by Redict** [comment]
I figured out that when you use `csound` with `librosa` it crashes, don't know what is the reason

**Comment by bmcfee** [comment]
Ok.  I'm going to chalk this up to an environment / upstream issue.

I'd be willing to bet that you'd see the same error if calling `soundfile.read` directly instead of `librosa.load`, in which case there's nothing we can do.

**Comment by Redict** [comment]
Here's issue on project where it isn't working right: https://github.com/TheSoundOfAIOSR/rg_production/issues/8

**Comment by Redict** [comment]
Ok, I've debugged Python process and noticed that somewhere deep in Numba there is null dereferencing (`rax` register is `0x0`)
![image](https://user-images.githubusercontent.com/9623703/111885467-10efed80-89d9-11eb-9785-a428dbadd12a.png)
![image](https://user-images.githubusercontent.com/9623703/111885471-19482880-89d9-11eb-827b-53001b67e90f.png)

Call stack:
![image](https://user-images.githubusercontent.com/9623703/111885474-1cdbaf80-89d9-11eb-98e3-5faa9fb6e71e.png)

**Comment by Redict** [comment]
Hi, the problem was solved and it wasn't `librosa`, it was wrong verison of `ctctsound` binding, thanks so much for the answers!

**Comment by bmcfee** [comment]
Great, glad you got it resolved.

**Comment by Redict** [comment]
Sorry, it isn't resolved. Here is reproduce steps:
1. Install Csound from official site.
2. Copy `ctcsound.py` from bin folder to `site-packages`
3. Run following code:
```python
import ctcsound
import librosa
import pathlib as pl

if __name__ == "__main__":
    ct = ctcsound.Csound()
    audio, orig_sr = librosa.load("some_sample.wav").as_posix())
    audio = librosa.resample(audio, orig_sr, target_sr)
    print("NOT CRASHED!") 
```

**Comment by bmcfee** [comment]
Does this happen if you don't load ctcsound?

At any rate, I still think this is an upstream problem, though probably within numba or llvmlite (and not soundfile as previously guessed).

**Comment by Redict** [comment]
> Does this happen if you don't load ctcsound?
No, but Csound loads fine if I dont load librosa

**Comment by lostanlen** [comment]
Thanks for the sleuthing work @Redict 
I took the liberty to rename your issue title to make it more specific (and hopefully easier to find for other users)

**Comment by Redict** [comment]
The problem was in Numba. If there is `python27.dll` in `system32` folder it fails. Thank you anyway.
