### ISSUE TITLE
Chromagrams: base_c = True not working if n_chroma is other than 12

### ISSUE THREAD

**Issue by bekemax** [librosa/librosa#1295]
**Describe the bug**
When getting a chromagram of a signal with `n_chroma` other than 12 (for example, with `n_chroma = 120` to get a "micro-tonal" chromagram, so 10 bins for each of the 12 notes in an octave instead of default 1), passing `base_c = True` to it does not produce a chroma based at C, as it should. 

**To reproduce**
Here I generate 2 tones – C4 (261.63 Hz) and A4 (440 Hz) and build chromas with `n_chroma = 120` and `base_c = True`:

```
import librosa
import matplotlib.pyplot as plt

from librosa.display import specshow

sr = 22050

# C4 is 261.63 Hz, A4 is 440 Hz
tone_C4 = librosa.tone(frequency=261.63, sr=sr, duration=1)
tone_A4 = librosa.tone(frequency=440, sr=sr, duration=1)

chroma_C4 = librosa.feature.chroma_stft(y=tone_C4, sr=sr, n_chroma=120, base_c = True)
chroma_A4 = librosa.feature.chroma_stft(y=tone_A4, sr=sr, n_chroma=120, base_c = True)

fig, ax = plt.subplots(1,2)

specshow(chroma_C4, y_axis=None, x_axis=None, ax=ax[0])
ax[0].set_title('C4')

specshow(chroma_A4, y_axis=None, x_axis=None, ax=ax[1])
ax[1].set_title('A4')

plt.show()
```
![bug](https://user-images.githubusercontent.com/32070551/111872125-c5b8e900-899e-11eb-9d8f-dbd64696f0bb.png)

**Expected behaviour**
The 0-th row of chroma `chroma[0,:]` should correspond to pitch class of C (that is, notes with main frequencies being twice-multiples of some C) – but it rather corresponds to something close to A, if `n_chroma` is big (as it is in the above example).
For the image below, I did `np.roll(chroma, -27, axis = 0)` (it is already rolled by -3, so -27-3 makes the needed -30):
![solved](https://user-images.githubusercontent.com/32070551/111872599-e97c2f00-899e-11eb-8017-3f9b0e11a9fb.png)

**Solution**
The issue is that `librosa.feature.chroma_stft` (and any other chroma-feature) passes `base_c` and `n_chroma` arguments to `librosa.filters.chroma` which builds the chroma-filterbank (`chroma_stft` then just multiplies the spectrogram by it). And in `librosa.filters.chroma`, `n_chroma` is not taken into account if `base_c = True`, it just does:
```
wts = np.roll(wts, -3, axis=0)
```
That is ok if `n_chroma=12`, since the spectrogram is built starting from A-s, and there are 3 semitones from C to A, so you just do an `np.roll` by -3 to start with C rather than A. But with `n_chroma != 12`, I suspect, you should rather do something like
```
wts = np.roll(wts, -3*(n_chroma//12), axis=0)
```

**Code patch**
In `librosa.filters`

```
@cache(level=10)
def chroma(sr, n_fft, n_chroma=12, A440=440.0, ctroct=5.0,
           octwidth=2, norm=2, base_c=True):
    
    wts = np.zeros((n_chroma, n_fft))

    # Get the FFT bins, not counting the DC component
    frequencies = np.linspace(0, sr, n_fft, endpoint=False)[1:]

    frqbins = n_chroma * hz_to_octs(frequencies, A440)

    # make up a value for the 0 Hz bin = 1.5 octaves below bin 1
    # (so chroma is 50% rotated from bin 1, and bin width is broad)
    frqbins = np.concatenate(([frqbins[0] - 1.5 * n_chroma], frqbins))

    binwidthbins = np.concatenate((np.maximum(frqbins[1:] - frqbins[:-1],
                                              1.0), [1]))

    D = np.subtract.outer(frqbins, np.arange(0, n_chroma, dtype='d')).T

    n_chroma2 = np.round(float(n_chroma) / 2)

    # Project into range -n_chroma/2 .. n_chroma/2
    # add on fixed offset of 10*n_chroma to ensure all values passed to
    # rem are positive
    D = np.remainder(D + n_chroma2 + 10*n_chroma, n_chroma) - n_chroma2

    # Gaussian bumps - 2*D to make them narrower
    wts = np.exp(-0.5 * (2*D / np.tile(binwidthbins, (n_chroma, 1)))**2)

    # normalize each column
    wts = util.normalize(wts, norm=norm, axis=0)

    # Maybe apply scaling for fft bins
    if octwidth is not None:
        wts *= np.tile(
            np.exp(-0.5 * (((frqbins/n_chroma - ctroct)/octwidth)**2)),
            (n_chroma, 1))

    if base_c:
        wts = np.roll(wts, -3, axis=0)

    # remove aliasing columns, copy to ensure row-contiguity
    return np.ascontiguousarray(wts[:, :int(1 + n_fft/2)])
```

**Software versions***
```
Python 3.7.3
librosa 0.8.0
numpy 1.16.3
matplotlib 3.1.0
```

**Comment by Germandev55** [comment]
:smirk: :smirk: :smirk: very valuable remark

**Comment by bmcfee** [comment]
Thanks for catching this!  I'm not sure how this one slipped through the cracks, but I guess it's not very often used if it made it this long before being identified.

At any rate, I agree with your proposed fix.  Anyone care to take this on?

**Comment by joonlimeecs** [comment]
Hi, I'm new here. Can I work on this issue?

**Comment by lostanlen** [comment]
Welcome @joonlimeecs. Yes of course! your help is appreciated
