### ISSUE TITLE
OSError: sndfile library not found (Github Action)

### ISSUE THREAD

**Issue by OverLordGoldDragon** [librosa/librosa#1296]
Encountered [here](https://github.com/OverLordGoldDragon/ssqueezepy/runs/2197871044), despite installing with `conda install libsndfile librosa -c conda-forge`. Unsure how else to resolve, other Issues don't address this.

**Comment by bmcfee** [comment]
This looks to me like a packaging error for libsndfile, not a librosa error?

**Comment by OverLordGoldDragon** [comment]
> If you're using `conda` to install librosa, then most audio coding dependencies (except MP3) will be handled automatically.

That's the README, so librosa's conda installer seems to not handle a dependency properly in some environments (I didn't have this problem in Travis).

**Comment by bmcfee** [comment]
Not sure what you mean by "librosa's conda installer".  The librosa conda-forge package depends on soundfile and libsndfile, and dependencies are transitive.  If one of our dependencies has a broken recipe, that needs to be fixed over there and not in librosa.

**Comment by OverLordGoldDragon** [comment]
Dependencies can lack sufficient specification across environments, causing installs to fail, making it the library's responsibility. Regardless it's possible the dependency itself is at fault, I just wonder if anyone here has a clue - may look into this sometime.

**Comment by bmcfee** [comment]
> Dependencies can lack sufficient specification across environments, causing installs to fail, making it the library's responsibility.

I don't see what exactly you mean by this.  Can you be more explicit?

Here's our recipe file:

https://github.com/librosa/librosa-feedstock/blob/master/recipe/meta.yaml

And pysoundfile's:

https://github.com/conda-forge/pysoundfile-feedstock/blob/master/recipe/meta.yaml


From a quick read through, I don't see anything wrong here.

**Comment by OverLordGoldDragon** [comment]
@bmcfee Alright, my build was at fault per following a bad template - `librosa`'s fine (I just failed to specify correct virtual env). Thanks for feedback.
