### ISSUE TITLE
stft(dtype='float32') is slower

### ISSUE THREAD

**Issue by OverLordGoldDragon** [librosa/librosa#1297]
May be [related](https://stackoverflow.com/a/66857982/10133797) (also [here](https://github.com/scipy/scipy/issues/13764#issuecomment-809786992)).

```python
import numpy as np
import librosa
from timeit import timeit as _timeit

def timeit(fn, number=10):
    return _timeit(fn, number=number) / number

x = np.random.randn(100000)
for dtype in ('float64', 'float32'):
    t = timeit(lambda: librosa.stft(x, n_fft=600, hop_length=1, dtype=dtype))
    print(dtype, t)

```
```
float64: 0.5876667099999849
float32: 0.7858876100000179
```

**Comment by OverLordGoldDragon** [comment]
Got different results after rerunning more than once, seems `float32` relies on caching somehow.  Further, `librosa` still goes for a `float64` window, making the fft `float64` regardless of `x.dtype` or `dtype`, missing out on a speedup. It also uses `np.fft`, which doesn't support `float32` fft, and is generally slower than `scipy.fft` ... any rationale for this? (On the upside, it's pretty safe against denormals)

**Comment by bmcfee** [comment]
> Further, `librosa` still goes for a `float64` window, making the fft `float64` regardless of `x.dtype` or `dtype`, missing out on a speedup.

Again, the `dtype` parameter here refers to the complex type of the output stft, not the type of the input sequence.  We should probably force the window type to match the input signal, but that's beside the point here.



> t also uses `np.fft`, which doesn't support `float32` fft, and is generally slower than `scipy.fft` ... any rationale for this?

I wouldn't say that it's "generally" slower than scipy's fft.  Sometimes it's faster and sometimes it's not -- in our benchmarks, there was a slight edge to numpy fft for the common parameterizations we see.  That said, you're totally free to switch FFT backends via `librosa.set_fftlib()`.

**Comment by OverLordGoldDragon** [comment]
@bmcfee Fair. Yes, the window's `dtype` is all that remains - I'll let you take it from here.
