### ISSUE TITLE
Lost the last beat in audio

### ISSUE THREAD

**Issue by Laotree** [librosa/librosa#1309]
***BEFORE POSTING A BUG REPORT*** Please look through [existing issues (both open and closed)](https://github.com/librosa/librosa/issues?q=is%3Aissue) to see if it's already been reported or fixed!
done, but not found

**Describe the bug**
First of all, thanks for this repository, it helps me a lot.
Here is where I am trapped:
I record a audio of 12 seconds which has 8 beat 'da', and the last beat exists after the eighth second.
but when I use the example code in [quick start](https://librosa.org/doc/main/tutorial.html#quickstart)
```
y, sr = librosa.load('path to da')

# 3. Run the default beat tracker
tempo, beat_frames = librosa.beat.beat_track(y=y, sr=sr)

print("Estimated tempo: {:.2f} beats per minute".format(tempo))

# 4. Convert the frame indices of beat events into timestamps
beat_times = librosa.frames_to_time(beat_frames, sr=sr)
```
I print out the result, it only contains 7 beat 'da', the last one was lost
```
Estimated tempo: 47.85 beats per minute
[0.62693878 1.88081633 3.11147392 4.31891156 5.54956916 6.68734694
 7.77868481]
```
I recorded different count of beats several times，each of them lost the last beat,
I use other music audio several times，each of them lost the last beat  as well.
**To Reproduce**

**Expected behavior**
point out why the last beat lost, or help me find it out.

**Screenshots**
![image](https://user-images.githubusercontent.com/16837634/114805730-16710580-9dd6-11eb-8d14-1486d5444672.png)

**Software versions***

```
Python 3.9.0 (v3.9.0:9cf6752276, Oct  5 2020, 11:29:23) 
[Clang 6.0 (clang-600.0.57)]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.20.2
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.6.2
>>> import librosa; print("librosa", librosa.__version__)
librosa 0.8.0
```
**Additional context**
env info:
MacOS Big Sur: 11.2.2
audio type: wav

**Comment by dpwe** [comment]
Did you try passing “trim =False” to beat_track?

  DAn.

**Comment by Laotree** [comment]
thanks a lot, I tried,
but now it has 9 beats. seems not correct
![image](https://user-images.githubusercontent.com/16837634/114809711-47086d80-9ddd-11eb-87a9-6f0ad02b9947.png)
```
trim=True
Estimated tempo: 66.26 beats per minute
[1.27709751 2.18267574 3.08825397 3.9938322  4.92263039 5.80498866
 6.71056689]
```

```
trim=False
Estimated tempo: 66.26 beats per minute
[0.37151927 1.27709751 2.18267574 3.08825397 3.9938322  4.92263039
 5.80498866 6.71056689 7.66258503]
```

**Comment by Laotree** [comment]
one more beat comes out : 0.37151927

**Comment by Laotree** [comment]
I print out beats and strength
```
strengths [0.02259169 1.         0.7297756  0.7591535  0.8683287  0.6150493
 0.7370527  0.67837095 0.74469775]
beat_times [0.37151927 1.27709751 2.18267574 3.08825397 3.9938322  4.92263039
 5.80498866 6.71056689 7.66258503]
```
and change some code, results is what I want, how can I get it? any param set I could do?
Thanks
```
beat_times = librosa.frames_to_time(beat_frames, sr=sr)
results = []
strengths =librosa.util.normalize(onset_env)[beat_frames]
for i in range(len(beat_times)):
    if strengths[i] > 0.2:
        results.append(beat_times[i])
```

**Comment by bmcfee** [comment]
Have you tried setting `trim=False` as described in the documentation for the beat tracker?

**Comment by dpwe** [comment]
The "trim" parameter doesn't allow you to set your own threshold.  Your
approach of applying your own threshold after getting all the detail with
trim=False seems like the best idea.

  DAn.

**Comment by Laotree** [comment]
It's not a graceful solution.
If threshold could not be passed,  
default threshold which is 0.0 when trim is False, 
may not distinguish correct beat from noise
thanks again
