### ISSUE TITLE
Documentation and code for liftering inside MFCC do not agree

### ISSUE THREAD

**Issue by mikolajpabiszczak** [librosa/librosa#1310]
**Describe the bug**
The documentation and code (main branch) for liftering inside MFCC do not agree:
 - the [doctring says](https://github.com/librosa/librosa/blob/2ea91af4d2b5ef8d805f51f480612bbcbc1a1bad/librosa/feature/spectral.py#L1772) that the liftering is calculated as:
  `M[n, :] <- M[n, :] * (1 + sin(pi * (n + 1) / lifter)) * lifter / 2`
 - whereas the [code itself](https://github.com/librosa/librosa/blob/2ea91af4d2b5ef8d805f51f480612bbcbc1a1bad/librosa/feature/spectral.py#L1856) performs:
`M *= ( 1 + (lifter / 2) * np.sin(np.pi * np.arange(1, 1 + n_mfcc) / lifter) )`
which would translate into the following dosctring:
`M[n, :] <- M[n, :] * (1 + sin(pi * (n + 1) / lifter) * lifter / 2)`

**Expected behavior**
Documentation and code shall agree. 😀

**Comment by bmcfee** [comment]
Good catch!  This ought to be an easy fix.

**Comment by mikolajpabiszczak** [comment]
Btw: (I have not delved into it really) what is wrong - the docstring or the code implementation?

**Comment by bmcfee** [comment]
The code is correct (i think!), the documentation has a misplaced closed parenthesis.  See http://www.dsic.upv.es/docs/posgrado/20/RES/materialesDocentes/alejandroViewgraphs/htkbook.pdf page 70, equation 5.12.
