### ISSUE TITLE
Phase aware HPSS or HPSS with residual separation

### ISSUE THREAD

**Issue by turian** [librosa/librosa#1315]
**Is your feature request related to a problem? Please describe.**

HPSS introduces artifacts.

**Describe the solution you'd like**

[Masuyama et al. (2019)](https://arxiv.org/pdf/1903.05600.pdf) proposes a phase-aware HPSS. I am not aware of any open source implementation, but it could be great in librosa.

Another interesting alternative is harmonic-percussive-residual separation:
[Driedger et. 2014](https://www.audiolabs-erlangen.de/resources/2014-ISMIR-ExtHPSep/2014_DriedgerMuellerDisch_ExtensionsHPSeparation_ISMIR.pdf)
[Fueg et al. 2016](https://www.audiolabs-erlangen.de/content/05-fau/professor/00-mueller/03-publications/2016_FuegNDDM_HPRStructureTensor_ICASSP.pdf)

Slide 16 of [this presentation](http://mac.citi.sinica.edu.tw/~yang/teaching/lecture10_separation.pdf) actually cites librosa and Slide 18 shares an extension of HPSS that includes residual calculation (e.g. applause).

**Describe alternatives you've considered**

Investigating other recent advances in HPSS techniques that are open-source.

**Comment by bmcfee** [comment]
I'm inclined to say no to this, mainly based on the complexity of Masuyama's algorithm (an iterative ADMM-type method), which is quite different from our HPSS implementation.

As an aside, we already support harmonic-percussive-residual separation via Driedger'14, and have for quite some time.

**Comment by turian** [comment]
@bmcfee Oh really? Where can I find the HPR separation? I was looking at the HPSS docs and didn't see it.

**Comment by bmcfee** [comment]
> @bmcfee Oh really? Where can I find the HPR separation? I was looking at the HPSS docs and didn't see it.

Are you sure you were looking at a recent version of the docs?  It's been in there since 2016, is the third line of the docstring here: https://librosa.org/doc/latest/generated/librosa.decompose.hpss.html?highlight=hpss#librosa.decompose.hpss , and most of the content of the gallery example on hpss here https://librosa.org/doc/latest/auto_examples/plot_hprss.html#sphx-glr-auto-examples-plot-hprss-py

**Comment by turian** [comment]
@bmcfee Ah got it. I didn't see it in the return statements.

**Comment by bmcfee** [comment]
> I didn't see it in the return statements.

That's right.  Residual is defined as whatever's not in harmonic or percussive.  We opted against returning it so that the call signature is preserved.
