### ISSUE TITLE
hop_length defaults to 512 instead of n_fft//4 in feature.inverse.mel_to_audio

### ISSUE THREAD

**Issue by dpwe** [librosa/librosa#1318]
When inverting a Mel spectrogram to audio using feature.inverse.mel_to_audio, the hop_length defaults to 512 samples regardless of the specified n_fft.  The function doc, however, indicates that it will default to n_fft // 4, which seems like a better choice.

As far as I can see, changing the default value of hop_length to None will allow griffinlim to choose the correct default.
https://github.com/librosa/librosa/blob/4d92350c5bb661feb196f2659dc8ff3fa60fa29b/librosa/feature/inverse.py#L96

**Comment by bmcfee** [comment]
Good catch!  I agree that this fix ought to work.
