### ISSUE TITLE
Measuring vibrato extent in librosa

### ISSUE THREAD

**Issue by giky12** [librosa/librosa#1319]
Hi, is there a way, how can I easy measure extent of vibrato of string instruments in librosa? I am junior in python in general, just started learning. 
I would like to measure size of vibrato (in cents) and speed rate in recordings of string quartet. I assume I need to work with spectrograms and constant Q transform? 

Or is there other package for python suitable for this issue?

Thank you!

**Comment by bmcfee** [comment]
Probably the easiest thing to do here is use pyin to extract the fundamental frequency contours and look at the standard deviation within voiced segments.

https://librosa.org/doc/latest/generated/librosa.pyin.html

**Comment by lostanlen** [comment]
Hello @giky12 , this is an interesting problem. We don't have a plug-and-play solution for this in librosa but the basic blocks (time-frequency analysis and periodicity analysis) are there.

Some references:

Driedger, J., Balke, S., Ewert, S., & Müller, M. (2016). Template-based vibrato analysis in music signals.

Yang, L., Rajab,  K. Z., & Chew, E. (2017). The filter diagonalisation method for  music signal analysis: frame-wise vibrato detection and estimation. Journal of Mathematics and Music, 11(1), 42-60.

Cuesta, H., Gómez Gutiérrez, E., Martorell Domínguez, A., & Loáiciga, F. (2018). Analysis of intonation in unison choir singing.
