### ISSUE TITLE
mel-spectrogram vs mel power spectrogram

### ISSUE THREAD

**Issue by n33lkanth** [librosa/librosa#1320]
What is the difference between _Mel-spectrogram_ and _Mel-power spectrogram_?
Why do we need to pass Mel-spectrogram through **librosa.power_to_db()** function [here](https://github.com/librosa/librosa/blob/main/examples/LibROSA%20demo.ipynb)  if Mel-spectrogram is already in **log scale**?

**Comment by bmcfee** [comment]
The mel scale is logarithmic in frequency.  Decibels are logarithmic in amplitude.

**Comment by n33lkanth** [comment]
> The mel scale is logarithmic in frequency. Decibels are logarithmic in amplitude.

So, do we need to convert amplitude to log scale while extraction features for training Machine learning model?

**Comment by bmcfee** [comment]
> So, do we need to convert amplitude to log scale while extraction features for training Machine learning model?

I wouldn't say "need to" -- some models are trained on decibel scale or similar logarithmic amplitude representations, and others are trained on linear magnitude spectra.  One isn't necessarily better than the other, and which works best will vary from one application to another.
