### ISSUE TITLE
Is there a CQCC feature extractor in Librosa?

### ISSUE THREAD

**Issue by hnqmz** [librosa/librosa#1343]
**Is your feature request related to a problem? Please describe.**
When working on spoofed audio detection, CQCC feature(Constant Q Cepstral Coefficients) is often used. However, there is no CQCC feature extractor written in Python. Most of them are written in Matlab.

**Describe the solution you'd like**
A CQCC feature extractor in Librosa, just like MFCC feature extractor.

**Comment by bmcfee** [comment]
No, but it would be pretty easy to assemble one from existing parts:

```python
Cmag =  np.abs(librosa.cqt(...))
cqcc = librosa.feature.mfcc(S=librosa.amplitude_to_db(Cmag))
```
