### ISSUE TITLE
How to Fixed color-bar that librosa.display.specshow

### ISSUE THREAD

**Issue by Asahi851** [librosa/librosa#1345]
I use "librosa.display.specshow". but, this color scale is different every time.
So, I want to fixed color scale to compere other color-map.
someone, plz help me. 
and this is I using code below.
![無題](https://user-images.githubusercontent.com/85866982/121974065-9527f600-cdb9-11eb-8048-4da2f09c71af.png)

**Comment by Asahi851** [comment]
![Figure 2021-06-14 110807](https://user-images.githubusercontent.com/85866982/121974122-b1c42e00-cdb9-11eb-960f-bbf9d5b8516c.png)
![Figure 2021-06-14 110907](https://user-images.githubusercontent.com/85866982/121974133-b5f04b80-cdb9-11eb-8ecb-dd0fdc41aba4.png)

**Comment by Asahi851** [comment]
NG/log504 is display -18~-4
OK/log474 is display -18~+0
so I want to set display -18~+0 all data.

**Comment by dpwe** [comment]
I think you just want plt.clim(-18, 0)

**Comment by Asahi851** [comment]
Thank you.
I will try it.

where I should insert "plt.clim(-18,0)"?
It's between plt.colorbar and plt.title?

**Comment by lostanlen** [comment]
@Asahi851 yes that would work. The `plt.clim` may appear anywhere between the call to `specshow` and the call to `plt.show()`

**Comment by Asahi851** [comment]
It's work well. very thank you.
ありがとうございます！！``
