### ISSUE TITLE
How to change the axis label and markings in librosa.specshow?

### ISSUE THREAD

**Issue by underdogliu** [librosa/librosa#1346]
**Is your feature request related to a problem? Please describe.**
I believe it is not a bug of new feature request. So I created the spectrogram via command like below:
```
fig, ax = plt.subplots(nrows=1, ncols=1, sharex=True, sharey=True, figsize=(12, 8))
img1 = librosa.display.specshow(librosa.amplitude_to_db(S, ref=np.max),
                                x_axis='time',
                                y_axis='mel', 
                                cmap=cm.jet))
```
And the y_axis shows frequency axis from 0 to 8k since the sample size is 16k. But the feature dimension is 60. I would like to change it to 60. For example, in [this link](https://librosa.org/doc/main/generated/librosa.display.specshow.html). Thanks in advance!

**Describe the solution you'd like**
Change the y axis index to actual channel/feature bin index, rather than frequencies.

**Comment by lostanlen** [comment]
Hello @underdogliu, you may use pyplot's `set_yticks` for that


```python
y, sr = librosa.load(librosa.ex("trumpet"), duration=3)
S = librosa.feature.melspectrogram(y, sr=sr, n_mels=60)
n_features = S.shape[0]

fig = plt.figure(figsize=(5, 5))
specshow(librosa.amplitude_to_db(S), x_axis="time", y_axis=None)
fig.gca().set_yticks(range(0, n_features+1, 10))
fig.gca().set_ylabel("Time (seconds)")
fig.gca().set_ylabel("Mel-frequency index")
```


<img width="487" alt="Screenshot 2021-06-21 at 10 57 14" src="https://user-images.githubusercontent.com/3943142/122735587-74f7ab80-d27f-11eb-85a8-d0c92eb4fe68.png">


P.S.: friendly reminder that `cmap=cm.jet` will affect the visual interpretation of your data in a counter-intuitive way ...
https://jakevdp.github.io/blog/2014/10/16/how-bad-is-your-colormap/

**Comment by underdogliu** [comment]
Thanks a lot for very rapid reply @lostanlen ! I did not expect this fast. 
Also thanks for the link attached. Seems like cm.jet has been an instant choice for a lot of people....
