### ISSUE TITLE
Help with vocal isolation example

### ISSUE THREAD

**Issue by gregsomm** [librosa/librosa#1352]
The example notebook that shows how to isolate vocals seems a little short in details.  For example, what do these variables mean, and what units are they expressed in?

```
margin_i, margin_v = 2, 10
power = 2
```

Also, I've tried converting the isolated vocal back to audio, and it's garbled.  Is there a good way to do that?

**Comment by bmcfee** [comment]
> For example, what do these variables mean, and what units are they expressed in?
> 

The margin quantities are unit-less.  You can think of the margin `m` as saying that the energy in (for example) the harmonic component estimate must exceed the non-harmonic component.  A large margin value means that the estimate must be very confident before it will allocate energy to a component.  In code, this is done in the softmask operation:
https://github.com/librosa/librosa/blob/d9b72af964820fc796425c55d3dccd7f6b908bf9/librosa/decompose.py#L343-L349
which computes the following:
https://github.com/librosa/librosa/blob/d9b72af964820fc796425c55d3dccd7f6b908bf9/librosa/util/utils.py#L1527-L1530
This is where the power parameter comes in: it's a scaling exponent applied to the energy values when estimating the mask.  Higher values of `power` produce sharper (more binary) masks; smaller values produce softer masks with probably more overlap between the separated components, but fewer artifacts arising from hard thresholding in the spectral domain.


> Also, I've tried converting the isolated vocal back to audio, and it's garbled. Is there a good way to do that?

Hard to answer this without more information.  Were you providing complex stft inputs, or magnitude spectra?  If the latter, you'll need to recover the phase information somehow, either by reintroducing the original phase (which the hpss function will do for you if you provide the complex input) or by running griffinlim.

More generally though, HPSS is not really a vocal separator, so you shouldn't expect perfect results here.  It can work in some cases, but really it's only intended to separate percussive or transient sounds from sustained harmonic sounds; generally speaking, vocals are neither.

If you want good vocal separation, I'd recommend to look into open-unmix, spleeter, or demucs.  These were all developed specifically to separate vocals (and other instruments) from each other.
