### ISSUE TITLE
Bug in `librosa.resample`

### ISSUE THREAD

**Issue by tanujdhiman** [librosa/librosa#1356]
### Code ::

`import librosa`
`import soundfile as sf`

`signal, rate = librosa.load('test2.wav')`
`print(signal.shape)`
`print(rate)`

`new_signal = librosa.resample(y=sig, orig_sr=rate, target_sr=44100)`

`print(new_signal.shape)`

`sf.write('data.wav', new_signal, 44100)`

`data, ra = librosa.load('data.wav')`
`print(ra)`

I try this code to increase the sample rate from 22050 to 44100 but I don't know why it is not converting ??

### Output :: 
(250631,)
22050
(501262,)
22050

**Comment by dpwe** [comment]
librosa.load resamples to 22050 by default.  You'll find that data.shape
(the size of the data read back from data.wav) is once again close to
250631.  Try librosa.load(..., sr=None) to load without resampling.

  DAn.

**Comment by tanujdhiman** [comment]
No @dpwe Actually I tried with `sr=None` but when I was converting this No results.

Can you please send me an example of real-time wav file?
* Loading
* Resampling
* Again Loading
* Printing
Thanks

**Comment by bmcfee** [comment]
> `data, ra = librosa.load('data.wav')`

This is the line that needs `sr=None`.  As the last printed out line shows, you're still loading at 22050, sr=None uses the native rate.

Also, your code interchanges `rate` (unspecified) and the constant `44100`, which may lead to inconsistencies.

**Comment by tanujdhiman** [comment]
Thanks @bmcfee It resolved !!!
