### ISSUE TITLE
librosa.display.specshow does not display the correct time scale

### ISSUE THREAD

**Issue by clare228** [librosa/librosa#1357]
When trying to display a chromagram using librosa.display.specshow, the time scale is not correct. The time scale is correct when the hop_length is its default value (512). However, it is incorrect whenever the hop_length is changed. (The input length increases as I increase the hop_length).

# Code I used to generate and plot the chromagram:
```
# 512 is the default, when this number is altered, the time scale is wrong
HOP_SIZE = 512

y, sr = librosa.load(mp3)
chroma_feature = librosa.feature.chroma_stft(y=y, sr = sr, hop_length = HOP_SIZE)

fig, ax = plt.subplots()
img = librosa.display.specshow(chroma_feature, y_axis='chroma', x_axis='time', ax=ax, sr = sr, hop_length = HOP_SIZE)
fig.colorbar(img, ax=ax)
plt.show()
```

**Comment by bmcfee** [comment]
Please give a complete example that demonstrates the behavior in question.

**Comment by clare228** [comment]
> Please give a complete example that demonstrates the behavior in question.

The mp3 input is a chord progression containing 4 chords. The correct input length is 8s. The clear change in energies are chord changes, which occurs every 2 seconds.

With HOP_LENGTH = 512:
![elect_prog_C_Am_F_G](https://user-images.githubusercontent.com/63462828/127905071-35925c9e-65af-4dee-9ad2-ff2dc618cc7a.png)

With HOP_LENGTH = 58800, the input length is shown to be more than 10 seconds, and chord changes don't occur every 2 seconds:
![elect_prog_C_Am_F_G](https://user-images.githubusercontent.com/63462828/127904970-d099ead2-16a9-470e-8507-b3197a3eaeed.png)

**Comment by bmcfee** [comment]
> Please give a complete example that demonstrates the behavior in question.

Please include the code used to make these chromagrams and subsequent figures.

**Comment by clare228** [comment]
> > Please give a complete example that demonstrates the behavior in question.
> 
> Please include the code used to make these chromagrams and subsequent figures.

Hi, the code used to generate and plot the chromagram is included in my initial post.

**Comment by bmcfee** [comment]
> Hi, the code used to generate and plot the chromagram is included in my initial post.

No it is not.  The provided code generates one plot and does not change the hop length.

I'm reasonably certain that the issue here is that you're using a different hop length for specshow and chroma_stft, but cannot verify this without a complete listing of the code.

**Comment by dpwe** [comment]
Isn't it that it's using like 2.667 (58800/22050) sec windows, so the whole
thing gets quantized to 4 columns, so at that resolution the 8 second sound
is 4 columns which displays as 10-ish seconds?
The final label on the plot looks wrong - it looks like labels every 1.5
sec, but then the final label should be 10.5, but it shows as 10.

  DAn.

**Comment by clare228** [comment]
> I'm reasonably certain that the issue here is that you're using a different hop length for specshow and chroma_stft, but cannot verify this without a complete listing of the code.

Hi, this is the complete code. I run the code multiple times with different HOP_LENGTH to get the different graphs. So on the first run, line 1 of the code is "HOP_LENGTH = 512". I save the graph, alter line 1 of the code to "HOP_LENGTH = 58800", then rerun the code to generate the second graph. Therefore for each run (therefore each plot), HOP_LENGTH for specshow and chroma_stft are the same.

**Comment by bmcfee** [comment]
> Hi, this is the complete code. I run the code multiple times with different HOP_LENGTH to get the different graphs. So on the first run, line 1 of the code is "HOP_LENGTH = 512". I save the graph, alter line 1 of the code to "HOP_LENGTH = 58800", then rerun the code to generate the second graph. Therefore for each run (therefore each plot), HOP_LENGTH for specshow and chroma_stft are the same.

Ok, thanks for clarifying.  This was not obvious.



> sn't it that it's using like 2.667 (58800/22050) sec windows, so the whole thing gets quantized to 4 columns, so at that resolution the 8 second sound is 4 columns which displays as 10-ish seconds?

That sounds plausible to me.  HOP=58800 is *enormous* (relative to the sampling rate), so there's bound to be some severe rounding errors here when converting between frame indices and times.


> The final label on the plot looks wrong - it looks like labels every 1.5 sec, but then the final label should be 10.5, but it shows as 10.

I think this could be an artifact of the visualization (meshgrid) which uses corner coordinates rather than box center coordinates.  My understanding (which might be incorrect) is that box center coordinates were only recently added in the matplotlib 3.x series, and we haven't yet updated our minimum version requirement to take advantage of that.  So for now we're stuck with corner coordinates, which are visually indistinguishable at high resolutions, but definitely drift quite a bit at low resolutions like this example.

**Comment by bmcfee** [comment]
[relevant documentation](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.pcolormesh.html) and [examples](https://matplotlib.org/stable/gallery/images_contours_and_fields/pcolormesh_grids.html) on pcolormesh and corner vs center coordinates, depending on shading modes.  Shading=nearest (and center coordinates) were added in [matplotlib 3.3.0](https://matplotlib.org/stable/users/prev_whats_new/whats_new_3.3.0.html#pcolor-and-pcolormesh-now-accept-shading-nearest-and-auto).

**Comment by bmcfee** [comment]
Ok, to summarize what's going on here:

1. We currently support matplotlib >= 2.0, which forces us to specify corner coordinates of meshgrids in displays.
2. When using `x_axis='time'`, coordinates are generated by using `frames_to_time()` with `N+1` frames for an input of dimension `N`.  This gives us the right corner of the last column of the display.  When the resolution is high, this all looks basically correct, even though the left corners are technically the positions of the center of the frames in question (assuming centered analysis).
3. When the resolution is low, the corners drift far from the centers, leading to an inaccurate axis label.

A couple of potential workarounds here:

1. Provide `x_coords=` explicitly to the display function, overriding the default calculation.  This way you can put the coordinates wherever you want them.
2. Ignore the `x_axis='time'` option and decorate the axes yourself.  (Option 1 is probably easier.)

Going forward, I think in the 0.9 series we can bump the minimum mpl to 3.3, which would allow us to drop this weird convention of relying on corners and instead set `shading='flat'` and using center coordinates.  This will probably be fine, though it might break API for the `x/y_coords=` option. (Shading='auto' might be a nice compromise here.) It might also cause some strange padding effects on the resulting images that we'll have to hack around.  But it seems doable to me.

**Comment by clare228** [comment]
Thank you for the help and explanation! I tried the first option you suggested and it worked.

**Comment by bmcfee** [comment]
Glad to hear.  I'll leave this issue open so we can address it in the next major release.
