### ISSUE TITLE
effects.trim and split should aggregate energy across channels

### ISSUE THREAD

**Issue by dafaronbi** [librosa/librosa#1369]
***BEFORE POSTING A BUG REPORT*** Please look through [existing issues (both open and closed)](https://github.com/librosa/librosa/issues?q=is%3Aissue) to see if it's already been reported or fixed!

**Describe the bug**
The function Trim and Split do not handle multichannel well. All channels are combined into one signal using core.to_mono. This is may be a problem in several types of multichannel signals (for example when the two channels are out of phase). These functions must be updated to allow for each channel's signal to be processed individually.

**Comment by bmcfee** [comment]
Implemented in f8ee28b20a3622bf331d7430146b2ff5a8adb96c ( #1351 ) by adding `aggregate=np.max` parameters to split and trim.
