### ISSUE TITLE
iOS App integration

### ISSUE THREAD

**Issue by rahul140490** [librosa/librosa#1373]
Hi,

I'll really appreciate if someone can throw some insight on how this library can be integrated into an iOS App.

**Comment by bmcfee** [comment]
I'm not an iOS developer, so take this with a grain of salt, but I don't think it would be easy.  Apple is notoriously not friendly to outside languages, preferring devs to use their own proprietary languages (eg swift) instead.  I expect that even if python can work with ios app development, the "scipy stack" is another beast entirely, so I wouldn't hold out much hope there.

Probably your best bet is to use the librosa implementations as reference and port to swift.

**Comment by dhrebeniuk** [comment]
I started special project for such tasks: https://github.com/dhrebeniuk/RosaKit

I'm try adding requested features, improvements, fixes.
