### ISSUE TITLE
librosa.effect.trim

### ISSUE THREAD

**Issue by inconnu11** [librosa/librosa#1376]
Hi, I am using the librosa.effects.trim to trim leading and trailing silence of an audio signal. The result of trimmed audio is denoted by red box. I observed that in the implement of ```trim```, it only retains the ```non silence``` . But I think maybe extra 10~20 ms  can ensure the voiced audio being not destroyed which is denoted by the green box.
![image](https://user-images.githubusercontent.com/38338826/133610053-a4e232f7-ac37-4cca-a65f-15051c006cd5.png)

**Comment by lostanlen** [comment]
Hello @inconnu11. It's unclear what you're asking. Please fill out the issue template below

```
**Describe the bug**
A clear and concise description of what the bug is.


**To Reproduce**
<!--
Example:
```
import librosa

# Generate one frame of random STFT-like energy
S = np.random.randn(1025, 1)**2

contrast = librosa.feature.spectral_contrast(S=S)
```
If the code is too long, feel free to put it in a public gist and link
it in the issue: https://gist.github.com
-->

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Software versions***
<!--
Please run the following Python code snippet and paste the output below.
```
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import librosa; print("librosa", librosa.__version__)

librosa.show_versions()
```
-->

**Additional context**
Add any other context about the problem here.
```
