### ISSUE TITLE
LFCC features

### ISSUE THREAD

**Issue by rishabh004-ai** [librosa/librosa#1378]
There is no feature extraction method for extracting lfcc features . How to do that ?

**Comment by bmcfee** [comment]
You would have to implement a linear filterbank.  Aside from that, it should roughly follow the same steps as our mfcc implementation:

https://github.com/librosa/librosa/blob/9732ae0775d359e24172bd396e98b44b7cddf19a/librosa/feature/spectral.py#L1850-L1854

That is, STFT -> magnitude -> projection (linear filterbank) -> decibel scaling -> DCT.

**Comment by rishabh004-ai** [comment]
Thanks for the prompt reply. But I am not able to find the linear filter bank in librosa.

**Comment by bmcfee** [comment]
Right, we don't provide that.  You would have to implement it.

**Comment by rishabh004-ai** [comment]
Okay, thanks. So. this can be a feature request.

**Comment by bmcfee** [comment]
I think it's fairly unlikely that we'd implement it, as it seems pretty uncommon in practice.

However, it would be trivial to do if our longest-standing issue #18 was implemented.

**Comment by rishabh004-ai** [comment]
After reading issue #18, I came to conclude that it would be great if you could implement generic filter banks.

**Comment by bmcfee** [comment]
@rishabh004-ai Pull requests are always welcome.
