### ISSUE TITLE
Librosa - Tensorflow

### ISSUE THREAD

**Issue by loukasilias** [librosa/librosa#1380]
I am using librosa along with tensorflow. More specifically, I am using a generator, where I convert audio .wav files to log-mel spectrogram, delta and delta-delta.
I have a model consisting of CNN layers.
I run the script in kaggle.
However, my model does not use the GPU. It runs on CPU and is extremely slow.
I would like to ask if librosa is compatible with tensorflow.

Thank you.

**Comment by bmcfee** [comment]
There is no incompatibility, but librosa does not depend on or use tensorflow.
