### ISSUE TITLE
Better error messages for CQT

### ISSUE THREAD

**Issue by BurningKarl** [librosa/librosa#1396]
**Is your feature request related to a problem? Please describe.**
I'm currently building a real-time audio visualization using an RGB LED strip and a Raspberry Pi. In this process, I figured out that `np.fft.fft` is not very good at turning an audio snippet into frequencies, because usually the signal is not periodic. Then, I found this library and its STFT and CQT implementations, which are designed for audio analysis. Thank you for providing this open-source library!

Back to the problem: I experimented a bit with the arguments to CQT using the following code snippet

```python
import librosa
import np

FRAMERATE = 44100
FFT_SIZE = 2 ** 13
num_octaves = 1
leds_per_octave = 10

signal = np.zeros(FFT_SIZE, dtype=np.float64)
amplitudes = np.abs(
    librosa.cqt(
        signal,
        sr=FRAMERATE,
        hop_length=FFT_SIZE * 2,  # The output should only have one frame
        fmin=min_frequency,
        n_bins=num_octaves * leds_per_octave,
        bins_per_octave=leds_per_octave,
        sparsity=0.1,
    )
).reshape(-1)
```
for different values of `min_frequency`. My understanding is that CQT will resample the audio signal for each octave and then use an STFT to get the power (I hope this is the right word) for the requested frequencies in that octave. Now, naturally this will have two limits. The minimum requested frequency `fmin` can't be too low because the length of the audio snippet `signal` is limited, but also the maximum requested frequency (determined by `fmin` and the number of octaves) can't be too high because the frame rate of the signal is limited.

Using `fmin=librosa.note_to_hz("C2")` the first kind of problem occurs and I get a warning:
```
/home/pi/Documents/LightOrgan/venv/lib/python3.7/site-packages/librosa/core/spectrum.py:224:
UserWarning: n_fft=256 is too small for input signal of length=128
```
First, I'm pretty sure this should say "is too large". Second, this is not very helpful and does not relate to the underlying problem (as I understand it) at all. I did neither provide `n_fft=256` nor a signal of `length=128`.

Using `fmin=librosa.not_to_hz("C11")` the maximum requested frequency is too high and I get an error:
```
  File "/home/pi/Documents/LightOrgan/venv/lib/python3.7/site-packages/librosa/filters.py", line 646, in constant_q_lengths
    raise ParameterError("Filter pass-band lies beyond Nyquist")
librosa.util.exceptions.ParameterError: Filter pass-band lies beyond Nyquist
```
The type of error is correct because I passed an invalid parameter combination, but again it's not helpful in figuring out the problem, at least for someone who is not an expert.

**Describe the solution you'd like**
I'd like the error messages/warnings to be a bit more descriptive. Something like "The length of the analyzed window is too short to provide an accurate constant-Q transform for an f_min value this low." and "The sample rate is too low to provide the constant-Q transform for a maximum frequency this high.". If this is not entirely accurate then feel free to adapt it, but include some hint which parameters need to be changed to make the call to `librosa.cqt` work.

**Additional context**
```
>>> import platform; print(platform.platform())
Linux-5.10.63-v7+-armv7l-with-debian-10.11
>>> import sys; print("Python", sys.version)
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.20.3
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.7.1
>>> import librosa; print("librosa", librosa.__version__)
librosa 0.8.1
```

**Comment by bmcfee** [comment]
> My understanding is that CQT will resample the audio signal for each octave and then use an STFT to get the power (I hope this is the right word) for the requested frequencies in that octave.

That's basically correct; it's not getting power exactly, but magnitude and phase of the CQT's filter responses in that octave.


> First, I'm pretty sure this should say "is too large".

That's odd, I thought we fixed that over in #1214 ?



> Second, this is not very helpful and does not relate to the underlying problem (as I understand it) at all. I did neither provide `n_fft=256` nor a signal of `length=128`.

Yeah, I agree, that's not a very helpful message in this context.  The problem is that the error comes from the underlying STFT and not the CQT.  I guess we could add some logic to catch this in advance from the CQT side and provide a more helpful message.





> I'd like the error messages/warnings to be a bit more descriptive. Something like "The length of the analyzed window is too short to provide an accurate constant-Q transform for an f_min value this low." and "The sample rate is too low to provide the constant-Q transform for a maximum frequency this high.".

Yes! I'm all for more explicit and instructive error messages.  Anyone feel like workshopping some text that we can put in here for the next release?

**Comment by BurningKarl** [comment]
Thanks @bmcfee for your very quick reply. I'm happy that you agree with my suggestion.

The thing about #1214 is that #1218 changed the wording to the correct one if `center=False`, i.e. when an error is raised, but not when `center=True`.

**Comment by bmcfee** [comment]
> The thing about #1214 is that #1218 changed the wording to the correct one if `center=False`, i.e. when an error is raised, but not when `center=True`.

Ah, thanks for catching that!  That's an easy enough fix - not sure how it slipped by the first time.
