### ISSUE TITLE
`pseudo_cqt` issues a warning if `hop_length` is too long

### ISSUE THREAD

**Issue by BurningKarl** [librosa/librosa#1397]
**Describe the bug**
I'm currently building a real-time audio visualization using an RGB LED strip and a Raspberry Pi. I'm not an audio analysis expert and only want to convert a short audio snippet (say, 200ms) into a frequency decomposition. Preferably the frequencies should be on a log-scale to get a similar resolution for low and high frequencies. From the documentation it seems that `cqt` and `pseudo_cqt` are the right tools for the job.

I found that `cqt` is too slow for my purposes and that `pseudo_cqt` works. Because this is real-time data, I want to turn one snippet of audio into one frame. By the way the signal is padded using `hop_length = len(signal)` gives two frames, one centered at sample 0 and one centered at the last sample, so I used `hop_length = 2 * len(signal)` (see code snippet below). This leads to the following warning:
```
/home/pi/Documents/LightOrgan/venv/lib/python3.7/site-packages/librosa/core/spectrum.py:224:
UserWarning: n_fft=32768 is too small for input signal of length=8192
```

On the one hand, I understand, that the docs state
> This uses a single fft size that is the smallest power of 2 that is greater than or equal to the max of:
>        1. The longest CQT filter
>        2. 2x the hop_length

On the other hand, I don't understand why this is the case or how I should go about using `pseudo_cqt` without receiving this warning and without discarding parts of my data by choosing a smaller `hop_length` and taking only one of the generated frames. The `stft` function has a `center=False` option that avoids padding and enables the use of `hop_length = len(signal)` but it does not exist for `pseudo_cqt`.

I'd like to note here that the output still looks pretty sensible to me, so maybe this less of a bug and more me not understanding how to use this library properly.

**To Reproduce**
```
import librosa
import numpy as np

FRAMERATE = 44100
FFT_SIZE = 2 ** 13

signal = np.zeros(FFT_SIZE, dtype=np.float64)
amplitudes = np.abs(
    librosa.pseudo_cqt(
        signal,
        sr=FRAMERATE,
        hop_length=FFT_SIZE * 2,
        fmin=librosa.note_to_hz("C4"),
        n_bins=10,
        bins_per_octave=2,
        sparsity=0.1,
    )
).reshape(-1)
```

**Expected behavior**
No warning should be issued, if this is an acceptable way to use `pseudo_cqt`.

**Software versions**
```
>>> import platform; print(platform.platform())
Linux-5.10.63-v7+-armv7l-with-debian-10.11
>>> import sys; print("Python", sys.version)
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.20.3
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.7.1
>>> import librosa; print("librosa", librosa.__version__)
librosa 0.8.1
>>> 
>>> librosa.show_versions()
INSTALLED VERSIONS
------------------
python: 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0]

librosa: 0.8.1

audioread: 2.1.9
numpy: 1.20.3
scipy: 1.7.1
sklearn: 0.24.2
joblib: 1.0.1
decorator: 5.0.9
soundfile: 0.10.3
resampy: 0.2.2
numba: 0.54.0

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
sphinxcontrib.versioning: None
sphinx-gallery: None
pytest: None
pytest-mpl: None
pytest-cov: None
matplotlib: None
presets: None
```

**Comment by bmcfee** [comment]
> Preferably the frequencies should be on a log-scale to get a similar resolution for low and high frequencies. From the documentation it seems that `cqt` and `pseudo_cqt` are the right tools for the job.

For your application, I think `librosa.iirt` might also be worth trying.  It will give you a logarithmically spaced frequency response, but using IIR filters rather than going through a STFT.  It's not a full transform of the signal like STFT or CQT, but it might do the job for turning on lights.  (And it should be reasonably speedy -- though I just noticed that we don't expose the resampling mode as a parameter in iirt!)


> Because this is real-time data, I want to turn one snippet of audio into one frame.

This is going to be somewhat problematic with CQT-based analyses.  Because the windows are variable length, they don't play nicely with left-aligned analyses (center=False, which is possible with STFT-based analyses).  The method essentially hacks around this by padding the signal, but that will have some ugly side-effects if you're doing stream processing.

The pseudo-cqt does basically the same thing as the regular cqt, but without the recursive downsampling.  It's not really meant as a user-facing method, but rather as a helper for the "hybrid-cqt" function that uses pseudo at the high octaves and downsampling at the low octaves (for efficiency purposes).

**Comment by BurningKarl** [comment]
Thanks for your reply. I get that CQT is not a good choice for stream processing.

I had a chance to try IIRT now, but it's pretty slow compared to `pseudo_cqt`. I reworked the `iirt` function to take the filters and sample rates as an input (so that `semitone_filterbank` does not have to be invoked every time), used `flayout="ba"` and `res_type="linear"` and got a frame rate of about 15 FPS with 50 filters. That's not too bad. I'll try to use multiprocessing to parallelize the calls to `scipy.signal.filtfilt` next and hopefully this will suffice for ~30 FPS.

I think the original issue is basically due to a misuse of CQT and therefore obsolete. Thanks again for your help.
