### ISSUE TITLE
Allow loading from file-like object instead of filename

### ISSUE THREAD

**Issue by rikrd** [librosa/librosa#140]
I have a lot of audio files in a large zip file.  I'm using Python's zipfile module to open the zip file and would like to be able to load the audio from a ZipExtFile object that ZipFile.open returns.

The current suboptimal workaround is to write the desired ZipExtFile into a temporary file, load the new file using librosa and remove the temporary file.

**Comment by bmcfee** [comment]
Good call.  I was planning to do this in this load refactor #116 , but it's not explicitly itemized anywhere.

**Comment by bmcfee** [comment]
Note: the trouble with the current implementation is that audioread only supports filename inputs, not buffers.

**Comment by dpwe** [comment]
On Fri, Jan 2, 2015 at 1:29 PM, Brian McFee <notifications@github.com> wrote:
> Note: the trouble with the current implementation is that audioread only
> supports filename inputs, not buffers.

.. and that won't be a trivial fix, since in some cases audioread
actually uses subprocesses.Popen to run ffmpeg passing the name of the
file for it to read.

We could always write our own version that only used codecs that
accept open files, but it would be some work.

  DAn.

**Comment by bmcfee** [comment]
Exactly.

Alternately, if we switch over to PySoundFile (see the comment thread in #70), this would be supported pretty easily.

**Comment by rikrd** [comment]
PySoundFile looks nice (didn't know about it).

In the specific case I reported, there is an additional issue of the
ZipExtFile not being seekable. I don't know how PySoundFile handles
non-seekable file-like objects, but one can still extract the entire wav
data from the zip file into memory, wrap it with a BytesIO and then decode
it using PySoundFile.

So having a load() taking a file-like object would still be required.


On Fri, Jan 2, 2015 at 8:18 PM, Brian McFee <notifications@github.com>
wrote:

> Exactly.
>
> Alternately, if we switch over to PySoundFile (see the comment thread in
> #70 <https://github.com/bmcfee/librosa/issues/70>), this would be
> supported pretty easily.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bmcfee/librosa/issues/140#issuecomment-68558550>.
>



-- 
ricard
http://twitter.com/ricardmp
http://www.ricardmarxer.com
http://www.caligraft.com

**Comment by bmcfee** [comment]
I'd like to close this one out, and refer people that need this functionality to use pysoundfile's [virtual IO](https://pysoundfile.readthedocs.io/en/0.8.1/#virtual-io) functionality.

Any objections?

**Comment by bmcfee** [comment]
Resolved by merging #480
