### ISSUE TITLE
dtw throws Exception: NaN Values in Cost Matrix

### ISSUE THREAD

**Issue by K3nn3th2** [librosa/librosa#1400]
Hey Folks, 

I'm using the dtw algorithm to determine some warping paths.
mostly it works out fine. but i have this pair of files that i cannot get the warping path for, i get the following error:

  File "../../evaluate_riddim.py", line 67, in generate_path
    D, wp = librosa.sequence.dtw(X=ref_specto, Y=estim_specto, metric='cosine')
  File "/home/archm4n/.local/lib/python3.7/site-packages/librosa/sequence.py", line 259, in dtw
    raise ParameterError("DTW cost matrix C has NaN values. ")
librosa.util.exceptions.ParameterError: DTW cost matrix C has NaN values. 

actually, changing the metric from 'cosine' to 'euclidean' seems to work. 
not sure which one yields better results, havent tried with other files yet.

can anyone explain why i get this error?

**Comment by bmcfee** [comment]
Probably one or both of your input arrays has a column of all zeros. When that happens, cosine similarity is undefined because each vector is divided by its length. An all zeros vector has length zero, so you get a 0/0->Nan.
