### ISSUE TITLE
Audio examples: non-musical excerpts and other concepts

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#1411]
**Is your feature request related to a problem? Please describe.**

All of our example data are musical recordings, but librosa is often used for general audio and not only music.  It seems like we ought to include some non-musical example data.  I'm mainly thinking of this with an eye toward expanding our example gallery.

Additionally, we could expand the musical data to cover more phenomena than are currently included.  #952 documents the original track selection process.  We had discussed including makam and raga tracks, but never settled on specific choices.

Here's a brief wish list of things that would complement our current example selection:

1. Speaking voices
    a. Could be helpful for demonstrating parameters restricted to human vocal range
2. Bird song and/or other bioacoustic data
    a. Could be good for showing how to modify default parameters for non-human data
3. Environmental sound / acoustic scenes
4. Solo piano
    a. Might be nice for a nmf demo
4. Solo drums
    a. For onset detection and beat tracking demos
5. Makam
    a. For continuous pitch estimation
6. Raga
    a. same, but also for demonstating Indian notation
7. Something multichannel
    a. Now that we support multichannel properly, it would be nice to demo
8. A track with an odd time signature

The same constraints as listed in #952 apply here: must be freely shareable, non-offensive, and relatively short (to minimize data footprint).

**Comment by bmcfee** [comment]
Some candidate examples:

- Drums
    - https://freesound.org/people/mcgumar/sounds/564647/
- Piano
    - https://freesound.org/people/lena_orsa/sounds/442789/
- Odd meter (waltz)
    - https://freesound.org/people/Setuniman/sounds/147793/
    - https://freesound.org/people/lucasgonze/sounds/170432/
- Birds / bioacoustic
    - https://freesound.org/people/InspectorJ/sounds/456440/
    - https://freesound.org/people/MATRIXXX_/sounds/365668/
    - https://freesound.org/people/Suso_Ramallo/sounds/525033/  -- also multichannel
- Environmental
    - https://freesound.org/people/selcukartut/sounds/504668/
    - https://freesound.org/people/Bokir26/sounds/383924/ - also multichannel

For voice samples, I'm thinking we can pull some clips out of commonvoice.  I won't hazard an attempt at makam or raga right now; I do recall that we had trouble previously identifying examples that were sufficiently short to include.

**Comment by bmcfee** [comment]
Librispeech examples:
- 3436-172162-0000.flac
- 198-209-0000.flac

**Comment by bmcfee** [comment]
One more (better) whale song example from https://www.nps.gov/glba/learn/nature/soundclips.htm : https://www.nps.gov/nps-audiovideo/audiovideo/4e34e6c7-5267-4c0b-8ff9-bf506086aa56.mp3

**Comment by bmcfee** [comment]
After spending some time with the above examples, I propose to add the following:

- https://freesound.org/people/lena_orsa/sounds/442789/ ; ragtime piano tune, should be good for NMF, harmony, possibly beat tracking
- https://freesound.org/people/Setuniman/sounds/147793/ ; synth tune in waltz time, should also be good for NMF and structure analysis
- https://freesound.org/people/InspectorJ/sounds/456440/ ; bird song (european robin), good demo for pcen and changing frame parameters
- https://www.nps.gov/nps-audiovideo/audiovideo/4e34e6c7-5267-4c0b-8ff9-bf506086aa56.mp3 ; whale song (humpback), also good for pcen
- https://freesound.org/people/Bokir26/sounds/383924/ ; environmental sound (train tracks) in 5.1.  (See below)
- Librispeech 198-209-0000 ; narration of Sense and Sensibility; median f0 ~= 190 Hz.
- Librispeech 3436-172162-0000 ; narration of Perceval and the adventure of the cart; median f0 ~= 140 Hz.  (On the fence with this one; might be nice to find an example where the narrator's at the lower end of the human vocal range.)  

We still need to get some nonwestern music examples in there, but I'm having real bear of a time trying to find content that's permissively licensed, relatively typical, and short.

**Comment by bmcfee** [comment]
Looks like there might be some reasonable Hindustani and Carnatic examples here: https://commons.wikimedia.org/w/index.php?search=raga&title=Special:MediaSearch&go=Go&type=audio and here: https://commons.wikimedia.org/w/index.php?search=raga+carnatic&title=Special:MediaSearch&go=Go&type=audio  (not necessarily full performances, but reasonable excerpts)

**Comment by bmcfee** [comment]
Following up on the above, the "Carnatic flute" example from the second wikimedia link: https://commons.wikimedia.org/wiki/File:Carnatic_flute.ogg  seems like a plausible candidate for inclusion.  It's a short performance (only 40 seconds) and perhaps not stylistically typical, but it would provide a more ecologically valid demo for both Hindustani and Carnatic notations than our current trumpet example.   (It's in `mela=15 ~= thaat='bhairav'`, where equivalence here is just in terms of included pitch classes.  IANAE but I think Sa is around E5 in this example, so that's how I'm annotating.)

Some example viz below.  These are all quick and dirty / mostly default parameters, but should illlustrate the point.

spectrogram with svara_c and f0 contour from pyin overlayed:

```python
librosa.display.specshow(librosa.amplitude_to_db(np.abs(S), ref=np.max), y_axis='fft_svara', x_axis='time', ax=ax, Sa=librosa.note_to_hz('E5'), mela=15)
ax.plot(t, f0, color='w', linestyle='--')
```
![image](https://user-images.githubusercontent.com/1190540/145075636-7da0de58-325d-4db4-8792-36ac96ae90f3.png)


chroma with svara_c:
```python
librosa.display.specshow(C, y_axis='chroma_c', x_axis='time', Sa=4, mela=15)
```
![image](https://user-images.githubusercontent.com/1190540/145075053-63edb9ce-5174-4f96-8682-3fd1b232495a.png)

rotated chroma so that Sa is at the bottom:
```python
librosa.display.specshow(np.roll(C, -4, axis=0), y_axis='chroma_c', x_axis='time', Sa=0, mela=15)
```

chroma with svara_h:
```python
librosa.display.specshow(C, y_axis='chroma_h', x_axis='time', Sa=4, ax=ax, thaat='bhairav')
```
![image](https://user-images.githubusercontent.com/1190540/145075360-14145e83-1f5a-4cd3-88b8-085303c74a17.png)

**Comment by bmcfee** [comment]
Note: once this issue is settled and new examples are added, we should do a pass of updates to the documentation and example gallery as mentioned in #1415

**Comment by bmcfee** [comment]
Following up on this, I don't expect the 5.1/ogg issue to be resolved any time soon.  I think we might have to punt that one for the time being.

**Comment by lostanlen** [comment]
very cool. I have written to Dan Stowell to hear his opinion on the bioacoustic examples. There might be important factors i'm not noticing right now

The Carnatic flute example looks great AFAICT

**Comment by sujoyrc** [comment]
@bmcfee  I am new to this so pardon my ignorance but why is the fft_svara showing only 'Sa' whereas the chroma spectra is activated across all the notes ?
