### ISSUE TITLE
unable to pip install librosa

### ISSUE THREAD

**Issue by aliafshany** [librosa/librosa#1417]
hi there

this is my log

i have no idea what went wrong

pip3 install librosa                             16:09:04 
Collecting librosa
  Using cached https://files.pythonhosted.org/packages/54/19/a0e2bdc94bc0d1555e4f9bc4099a0751da83fa6e1e6157ec005564f8a98a/librosa-0.8.1-py3-none-any.whl
Collecting decorator>=3.0.0 (from librosa)
  Downloading https://files.pythonhosted.org/packages/3d/cc/d7b758e54779f7e465179427de7e78c601d3330d6c411ea7ba9ae2f38102/decorator-5.1.0-py3-none-any.whl
Collecting scikit-learn!=0.19.0,>=0.14.0 (from librosa)
  Downloading https://files.pythonhosted.org/packages/62/7c/596ff7b32f655f379d3abdfa82607e5cb3b70f46baad4604706511cfeb85/scikit-learn-1.0.1.tar.gz (6.6MB)
     |████████████████████████████████| 6.6MB 3.0MB/s 
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/ali/.pyenv/versions/3.8.0/bin/python3.8 /Users/ali/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/r3/zr3bc1fx539d03p71v7249mc0000gn/T/pip-build-env-_8_nqv39/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'Cython>=0.28.5' 'oldest-supported-numpy; python_version!='"'"'3.7'"'"' or platform_machine=='"'"'aarch64'"'"' or platform_system=='"'"'AIX'"'"' or platform_python_implementation == '"'"'PyPy'"'"'' 'numpy==1.14.6; python_version=='"'"'3.7'"'"' and platform_machine!='"'"'aarch64'"'"' and platform_system!='"'"'AIX'"'"' and platform_python_implementation != '"'"'PyPy'"'"'' 'scipy>=1.1.0'
       cwd: None
  Complete output (241 lines):
  Ignoring numpy: markers 'python_version == "3.7" and platform_machine != "aarch64" and platform_system != "AIX" and platform_python_implementation != "PyPy"' don't match your environment
  Collecting setuptools
    Using cached https://files.pythonhosted.org/packages/40/a9/7deac76c58fa47c95360116a06b53b9b62f6db11336fe61b6ab53784d98b/setuptools-59.5.0-py3-none-any.whl
  Collecting wheel
    Using cached https://files.pythonhosted.org/packages/04/80/cad93b40262f5d09f6de82adbee452fd43cdff60830b56a74c5930f7e277/wheel-0.37.0-py2.py3-none-any.whl
  Collecting Cython>=0.28.5
    Using cached https://files.pythonhosted.org/packages/de/d0/664184c19e165a3b8c92042f4053fe22d4530fa259b9704d5513e454d5ee/Cython-0.29.25-py2.py3-none-any.whl
  Collecting oldest-supported-numpy
    Downloading https://files.pythonhosted.org/packages/5d/5c/6836df2be33be6dda65a3536194e9479296abc1a3ec4238a1005f454008b/oldest_supported_numpy-0.13-py3-none-any.whl
  Collecting scipy>=1.1.0
    Using cached https://files.pythonhosted.org/packages/61/67/1a654b96309c991762ee9bc39c363fc618076b155fe52d295211cf2536c7/scipy-1.7.3.tar.gz
    Installing build dependencies: started
    Installing build dependencies: still running...
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: still running...
      Preparing wheel metadata: still running...
      Preparing wheel metadata: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /Users/ali/.pyenv/versions/3.8.0/bin/python3.8 /Users/ali/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/r3/zr3bc1fx539d03p71v7249mc0000gn/T/tmppt742fzy
           cwd: /private/var/folders/r3/zr3bc1fx539d03p71v7249mc0000gn/T/pip-install-7rlrt2u7/scipy
      Complete output (213 lines):
      Running scipy/linalg/_generate_pyx.py
      Running scipy/special/_generate_pyx.py
      Running scipy/stats/_generate_pyx.py
      Processing scipy/cluster/_vq.pyx
      Processing scipy/cluster/_optimal_leaf_ordering.pyx
      Processing scipy/cluster/_hierarchy.pyx
      Processing scipy/ndimage/src/_cytest.pyx
      Processing scipy/ndimage/src/_ni_label.pyx
      Processing scipy/linalg/cython_lapack.pyx
      Processing scipy/linalg/_matfuncs_sqrtm_triu.pyx
      Processing scipy/linalg/_solve_toeplitz.pyx
      Processing scipy/linalg/cython_blas.pyx
      Processing scipy/linalg/_decomp_update.pyx.in
      Processing scipy/optimize/_group_columns.pyx
      Processing scipy/optimize/_bglu_dense.pyx
      Processing scipy/optimize/_trlib/_trlib.pyx
      Processing scipy/optimize/_highs/cython/src/_highs_constants.pyx
      Processing scipy/optimize/_highs/cython/src/_highs_wrapper.pyx
      Processing scipy/optimize/_lsq/givens_elimination.pyx
      Processing scipy/optimize/cython_optimize/_zeros.pyx.in
      Processing scipy/io/matlab/mio_utils.pyx
      Processing scipy/io/matlab/streams.pyx
      Processing scipy/io/matlab/mio5_utils.pyx
      Processing scipy/_lib/_ccallback_c.pyx
      Processing scipy/_lib/_test_deprecation_def.pyx
      Processing scipy/_lib/_test_deprecation_call.pyx
      Processing scipy/_lib/messagestream.pyx
      Processing scipy/special/_ufuncs_cxx.pyx
      Processing scipy/special/cython_special.pyx
      Processing scipy/special/_ellip_harm_2.pyx
      Processing scipy/special/_comb.pyx
      Processing scipy/special/_test_round.pyx
      Processing scipy/special/_ufuncs.pyx
      Processing scipy/fftpack/convolve.pyx
      Processing scipy/interpolate/interpnd.pyx
      Processing scipy/interpolate/_bspl.pyx
      Processing scipy/interpolate/_ppoly.pyx
      Processing scipy/sparse/_csparsetools.pyx.in
      warning: _cython_special_custom.pxi:9:8: Unreachable code
      warning: _cython_special_custom.pxi:13:4: Unreachable code
      warning: _cython_special_custom.pxi:21:8: Unreachable code
      warning: _cython_special_custom.pxi:25:4: Unreachable code
      warning: _cython_special_custom.pxi:33:8: Unreachable code
      warning: _cython_special_custom.pxi:37:4: Unreachable code
      warning: _cython_special_custom.pxi:45:8: Unreachable code
      warning: _cython_special_custom.pxi:49:4: Unreachable code
      Processing scipy/sparse/csgraph/_shortest_path.pyx
      Processing scipy/sparse/csgraph/_traversal.pyx
      Processing scipy/sparse/csgraph/_flow.pyx
      Processing scipy/sparse/csgraph/_tools.pyx
      Processing scipy/sparse/csgraph/_matching.pyx
      Processing scipy/sparse/csgraph/_reordering.pyx
      Processing scipy/sparse/csgraph/_min_spanning_tree.pyx
      Processing scipy/spatial/ckdtree.pyx
      Processing scipy/spatial/_voronoi.pyx
      Processing scipy/spatial/_hausdorff.pyx
      Processing scipy/spatial/qhull.pyx
      Processing scipy/spatial/transform/rotation.pyx
      Processing scipy/signal/_max_len_seq_inner.pyx
      Processing scipy/signal/_peak_finding_utils.pyx
      Processing scipy/signal/_upfirdn_apply.pyx
      Processing scipy/signal/_spectral.pyx
      Processing scipy/signal/_sosfilt.pyx
      Processing scipy/stats/_stats.pyx
      Processing scipy/stats/_qmc_cy.pyx
      Processing scipy/stats/_sobol.pyx
      Processing scipy/stats/biasedurn.pyx
      Processing scipy/stats/_boost/src/beta_ufunc.pyx
      Processing scipy/stats/_boost/src/nbinom_ufunc.pyx
      Processing scipy/stats/_boost/src/binom_ufunc.pyx
      Cythonizing sources
      lapack_opt_info:
      lapack_mkl_info:
      customize UnixCCompiler
        libraries mkl_rt not found in ['/Users/ali/.pyenv/versions/3.8.0/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
  
      openblas_lapack_info:
      customize UnixCCompiler
      customize UnixCCompiler
        libraries openblas not found in ['/Users/ali/.pyenv/versions/3.8.0/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
  
      openblas_clapack_info:
      customize UnixCCompiler
      customize UnixCCompiler
        libraries openblas,lapack not found in ['/Users/ali/.pyenv/versions/3.8.0/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
  
      flame_info:
      customize UnixCCompiler
        libraries flame not found in ['/Users/ali/.pyenv/versions/3.8.0/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
  
      atlas_3_10_threads_info:
      Setting PTATLAS=ATLAS
      customize UnixCCompiler
        libraries lapack_atlas not found in /Users/ali/.pyenv/versions/3.8.0/lib
      customize UnixCCompiler
        libraries tatlas,tatlas not found in /Users/ali/.pyenv/versions/3.8.0/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries tatlas,tatlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib
      customize UnixCCompiler
        libraries tatlas,tatlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
        NOT AVAILABLE
  
      atlas_3_10_info:
      customize UnixCCompiler
        libraries lapack_atlas not found in /Users/ali/.pyenv/versions/3.8.0/lib
      customize UnixCCompiler
        libraries satlas,satlas not found in /Users/ali/.pyenv/versions/3.8.0/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries satlas,satlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib
      customize UnixCCompiler
        libraries satlas,satlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_3_10_info'>
        NOT AVAILABLE
  
      atlas_threads_info:
      Setting PTATLAS=ATLAS
      customize UnixCCompiler
        libraries lapack_atlas not found in /Users/ali/.pyenv/versions/3.8.0/lib
      customize UnixCCompiler
        libraries ptf77blas,ptcblas,atlas not found in /Users/ali/.pyenv/versions/3.8.0/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib
      customize UnixCCompiler
        libraries ptf77blas,ptcblas,atlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_threads_info'>
        NOT AVAILABLE
  
      atlas_info:
      customize UnixCCompiler
        libraries lapack_atlas not found in /Users/ali/.pyenv/versions/3.8.0/lib
      customize UnixCCompiler
        libraries f77blas,cblas,atlas not found in /Users/ali/.pyenv/versions/3.8.0/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries f77blas,cblas,atlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib
      customize UnixCCompiler
        libraries f77blas,cblas,atlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_info'>
        NOT AVAILABLE
  
      accelerate_info:
        NOT AVAILABLE
  
      lapack_info:
      customize UnixCCompiler
        libraries lapack not found in ['/Users/ali/.pyenv/versions/3.8.0/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
  
      lapack_src_info:
        NOT AVAILABLE
  
        NOT AVAILABLE
  
      setup.py:491: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /private/var/folders/r3/zr3bc1fx539d03p71v7249mc0000gn/T/pip-install-7rlrt2u7/scipy/pip-wheel-metadata'), proceeding with generating Cython sources and expanding templates
        warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
      Running from SciPy source directory.
      /private/var/folders/r3/zr3bc1fx539d03p71v7249mc0000gn/T/pip-build-env-dis1l2zs/overlay/lib/python3.8/site-packages/numpy/distutils/system_info.py:1712: UserWarning:
          Lapack (http://www.netlib.org/lapack/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [lapack]) or by setting
          the LAPACK environment variable.
        if getattr(self, '_calc_info_{}'.format(lapack))():
      /private/var/folders/r3/zr3bc1fx539d03p71v7249mc0000gn/T/pip-build-env-dis1l2zs/overlay/lib/python3.8/site-packages/numpy/distutils/system_info.py:1712: UserWarning:
          Lapack (http://www.netlib.org/lapack/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [lapack_src]) or by setting
          the LAPACK_SRC environment variable.
        if getattr(self, '_calc_info_{}'.format(lapack))():
      Traceback (most recent call last):
        File "/Users/ali/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
          main()
        File "/Users/ali/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/ali/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 69, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/r3/zr3bc1fx539d03p71v7249mc0000gn/T/pip-build-env-dis1l2zs/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 166, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/r3/zr3bc1fx539d03p71v7249mc0000gn/T/pip-build-env-dis1l2zs/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 258, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/r3/zr3bc1fx539d03p71v7249mc0000gn/T/pip-build-env-dis1l2zs/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 631, in <module>
          setup_package()
        File "setup.py", line 627, in setup_package
          setup(**metadata)
        File "/private/var/folders/r3/zr3bc1fx539d03p71v7249mc0000gn/T/pip-build-env-dis1l2zs/overlay/lib/python3.8/site-packages/numpy/distutils/core.py", line 137, in setup
          config = configuration()
        File "setup.py", line 529, in configuration
          raise NotFoundError(msg)
      numpy.distutils.system_info.NotFoundError: No BLAS/LAPACK libraries found. Note: Accelerate is no longer supported.
      To build Scipy from sources, BLAS & LAPACK libraries need to be installed.
      See site.cfg.example in the Scipy source directory and
      https://docs.scipy.org/doc/scipy/reference/building/index.html for details.
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /Users/ali/.pyenv/versions/3.8.0/bin/python3.8 /Users/ali/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/r3/zr3bc1fx539d03p71v7249mc0000gn/T/tmppt742fzy Check the logs for full command output.
  WARNING: You are using pip version 19.2.3, however version 21.3.1 is available.
  You should consider upgrading via the 'pip install --upgrade pip' command.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/ali/.pyenv/versions/3.8.0/bin/python3.8 /Users/ali/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/r3/zr3bc1fx539d03p71v7249mc0000gn/T/pip-build-env-_8_nqv39/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'Cython>=0.28.5' 'oldest-supported-numpy; python_version!='"'"'3.7'"'"' or platform_machine=='"'"'aarch64'"'"' or platform_system=='"'"'AIX'"'"' or platform_python_implementation == '"'"'PyPy'"'"'' 'numpy==1.14.6; python_version=='"'"'3.7'"'"' and platform_machine!='"'"'aarch64'"'"' and platform_system!='"'"'AIX'"'"' and platform_python_implementation != '"'"'PyPy'"'"'' 'scipy>=1.1.0' Check the logs for full command output.

**Comment by bmcfee** [comment]
Hi,

1) This is not a librosa problem.  The log indicates that your system was unable to install numpy.
2) In general, please use the issue template and provide information about your system.  Without knowing what your system is (python version, architecture, etc) it's much more difficult to help you.

Otherwise I'll refer you to the [installation documentation](https://librosa.org/doc/latest/install.html) and generally recommend that you use the conda packages if possible.
