### ISSUE TITLE
Remove dynamic __all__ to facilitate static analysis

### ISSUE THREAD

**Issue by bluenote10** [librosa/librosa#1429]
**Is your feature request related to a problem? Please describe.**

I noticed that librosa's IDE support is a bit lacking, because pylance doesn't understand librosa's module structure very well. For instance, while this works

![image](https://user-images.githubusercontent.com/3620703/147777337-69803617-64f8-42a8-9eff-78349be2933c.png)

the top-level symbols don't work:

![image](https://user-images.githubusercontent.com/3620703/147777326-e7e41c2f-7748-434d-bb17-f0a21c911902.png)

In practice it is just a bit of a pity to have no auto-completion on the plain `librosa` module, and no jump to documentation / implementation.

**Describe the solution you'd like**

I'm mainly opening the issue for discussion of possible solutions.

**Describe alternatives you've considered**

On first glance, the way librosa re-exports symbols looks sensible to me. The fact that the dynamic wildcard exports were working in one case but not in the other suggested it was a pylance issue. I've raised an upstream issue https://github.com/microsoft/pylance-release/issues/2200, but apparently it is expected behavior, and the suggestion was to fix it on librosa side.

I'm wondering if we can come up with a solution that doesn't involve massive boilerplate / anti-DRY. Any ideas?

**Comment by bmcfee** [comment]
https://github.com/microsoft/pylance-release/issues/2200#issuecomment-1003126479 identifies the core problem: pylance does not support dynamically constructed `__all__`.  This explains why it works fine in other environments (ipython/jupyter, notably) but not pylance, which relies on static analysis for this sort of thing.

I don't necessarily think we should contort ourselves just to support one IDE - the current setup is concise, easy to maintain, and serves a very specific purpose.  Every other solution I could see here would sacrifice on one or more of those points.

That said, if we're causing general problems for all static analyzers, that's a more serious problem to consider.  Then again, we don't implement type hints, and I have no plans of doing so any time soon, so it's not obvious what other use cases there would be.

**Comment by bluenote10** [comment]
>  Then again, we don't implement type hints, and I have no plans of doing so any time soon.

It should be noted that since librosa uses a lot of default arguments in its functions, it actually has a decent level of type information already. You can check it out via `pip install mypy && cd /tmp && stubgen -p librosa`. Of course this cannot capture cases which allow for an argument to accept other types than the default value, but I'd say this is perhaps already correct for ~75% of the defaulted arguments, and would probably already add value for users that are working in a typed context.
