### ISSUE TITLE
STFT over subset of frequencies

### ISSUE THREAD

**Issue by OverLordGoldDragon** [librosa/librosa#1435]
Doable via either row-wise implementation (like CQT/CWT), or a "partial" FFT - which seems to have been [developed recently](https://github.com/snudatalab/PFT). Latter appears to be a much simpler solution, though needs a Python port.

I might do it in ssqueezepy in some future, but would be glad if anyone interested here pursued either implementation.

**Comment by bmcfee** [comment]
This isn't supported by the numpy(/scipy/fftpack/fftw) fft api, so I don't see a way to implement it efficiently without losing a considerable amount of interoperability.

**Comment by dpwe** [comment]
If the goal is computing only low-band fourier coefficients, then
downsampling and using a regular FFT should suffice.  This has the same
complexity as the PFT, i.e. O(N) for the low-pass, and O(MlogM) for the
subsequent M-point FFT.
If you want a contiguous block of frequencies away from d.c., then
demodulating those frequencies down to d.c. then low-pass and FFT should
work.
If you want a sparse set of individual Fourier coefficients, I don't think
the PFT helps.

  DAn.

**Comment by OverLordGoldDragon** [comment]
> I don't see a way to implement it efficiently without losing a considerable amount of interoperability

Fair, but perhaps not all features need to be fully interoperable

> If the goal is

All of this involves filtering, which distorts the signal and isn't a subset-equivalent.

> downsampling and using a regular FFT

This isn't equivalent even without filtering. E.g. Nyquist is still computed.
