### ISSUE TITLE
pyin decode 'E3' to 'E4'

### ISSUE THREAD

**Issue by yl8414** [librosa/librosa#1437]
***BEFORE POSTING A BUG REPORT*** Please look through [existing issues (both open and closed)](https://github.com/librosa/librosa/issues?q=is%3Aissue) to see if it's already been reported or fixed!

**Describe the bug**
I have decode a mp3 to a F0 array, but I find that pYin decode a voice 'E3' to a 'E4'

**To Reproduce**    
    y, sr = librosa.load('5.mp3')
    loginfo("librosa pyin, sr:%d" % sr)
    f0, voiced_flag, voiced_probs = librosa.pyin(y, fmin=librosa.note_to_hz('D2'), fmax=librosa.note_to_hz('D6'), sr=sr)
    # f0 = librosa.yin(y, fmin=librosa.note_to_hz('D2'), fmax=librosa.note_to_hz('D6'), sr=sr)
    loginfo("librosa f0 len:%d" % len(f0))
    times = librosa.times_like(f0)
    tempName = filepath[0:-4] + pitchpath
    savePitch(f0, voiced_flag, voiced_probs, times, tempName)

**Expected behavior**
5.mp3's url
https://duoer-test1.oss-cn-shanghai.aliyuncs.com/default/5.mp3

please check this voice's 13s ~ 14s,this pitch is a 'E3'，but I decode it with pyin as below：

13.374694,E4,True,0.984879
13.397914,E4,True,0.984879
13.421134,F4,True,1.000000
13.444354,F4,True,1.000000
13.467574,F4,True,0.984879
13.490794,E4,True,0.984879
13.514014,E4,True,1.000000
13.537234,E4,True,1.000000
13.560454,E4,True,1.000000
13.583673,E4,True,1.000000
13.606893,E4,True,1.000000
13.630113,E4,True,1.000000
13.653333,E4,True,1.000000
13.676553,E4,True,1.000000
13.699773,E4,True,1.000000
13.722993,E4,True,1.000000
13.746213,E4,True,1.000000
13.769433,E4,True,1.000000
13.792653,E4,True,1.000000
13.815873,E4,True,1.000000
13.839093,E4,True,1.000000
13.862313,E4,True,1.000000
13.885533,E4,True,1.000000
13.908753,E4,True,1.000000
13.931973,E4,True,0.984879
13.955193,E4,True,0.826669

**Software versions***
librosa 0.8.0

**Comment by bmcfee** [comment]
The pyin method is not perfect, and octave errors are the most common kind of mistake that it makes.  I don't think this is a bug.
