### ISSUE TITLE
Soundfile error from update 0.9

### ISSUE THREAD

**Issue by pianistprogrammer** [librosa/librosa#1442]
I updated my librosa pacakge on conda, and my project don't work again , I get this error
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~/opt/anaconda3/lib/python3.9/site-packages/soundfile.py in <module>
    142         raise OSError('sndfile library not found')
--> 143     _snd = _ffi.dlopen(_libname)
    144 except OSError:

OSError: cannot load library '/Users/pianistprogrammer/opt/anaconda3/bin/../lib/libsndfile.dylib': dlopen(/Users/pianistprogrammer/opt/anaconda3/bin/../lib/libsndfile.dylib, 2): Library not loaded: @rpath/libvorbis.0.4.9.dylib
  Referenced from: /Users/pianistprogrammer/opt/anaconda3/lib/libsndfile.1.0.31.dylib
  Reason: image not found

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
/var/folders/1p/80ghxr7975jgkjkyyw4l0s000000gn/T/ipykernel_40695/3998494949.py in <module>
      3 import numpy as np
      4 import matplotlib.pyplot as plt
----> 5 import librosa
      6 import librosa.display
      7 import IPython.display as ipd

~/opt/anaconda3/lib/python3.9/site-packages/librosa/__init__.py in <module>
    207 # And all the librosa sub-modules
    208 from ._cache import cache
--> 209 from . import core
    210 from . import beat
    211 from . import decompose

~/opt/anaconda3/lib/python3.9/site-packages/librosa/core/__init__.py in <module>
      4 
      5 from .convert import *  # pylint: disable=wildcard-import
----> 6 from .audio import *  # pylint: disable=wildcard-import
      7 from .spectrum import *  # pylint: disable=wildcard-import
      8 from .pitch import *  # pylint: disable=wildcard-import

~/opt/anaconda3/lib/python3.9/site-packages/librosa/core/audio.py in <module>
      6 import warnings
      7 
----> 8 import soundfile as sf
      9 import audioread
     10 import numpy as np

~/opt/anaconda3/lib/python3.9/site-packages/soundfile.py in <module>
    160         _path = _os.path.abspath(_os.path.join(_path, '..'))
    161 
--> 162     _snd = _ffi.dlopen(_os.path.join(
    163         _path, '_soundfile_data', _libname))
    164 

OSError: cannot load library '/Users/pianistprogrammer/opt/anaconda3/lib/python3.9/site-packages/_soundfile_data/libsndfile.dylib': dlopen(/Users/pianistprogrammer/opt/anaconda3/lib/python3.9/site-packages/_soundfile_data/libsndfile.dylib, 2): image not found

**Comment by bmcfee** [comment]
> is there a certain version that works with librosa?

Yes, it is specified in the package dependencies and should work automatically.  It looks like something went wrong with your local installation though, so I suggest reinstalling pysoundfile.

**Comment by pianistprogrammer** [comment]
I have tried to do this, still the same result.

**Comment by pianistprogrammer** [comment]
Thank you, that fixed the issue, installing libvorbis via conda, although I had this package there before as seen from the conda list
