### ISSUE TITLE
librosa.filters.mel function signature change?

### ISSUE THREAD

**Issue by pseeth** [librosa/librosa#1444]
**Describe the bug**
The signature for `librosa.filters.mel` appears to have changed, breaking my existing code in some way. The fix is easy in my code, but not sure why the signature seems to have changed.

**To Reproduce**

```
from librosa.filters import mel

sr = 44100
n_fft = 2048

mel(sr=sr, n_fft=n_fft) # This works in 0.9.0.
mel(sr, n_fft) # This works in 0.8.0 only.
```

The output of this is:

```
❯ python librosa_repro.py
Traceback (most recent call last):
  File "librosa_repro.py", line 7, in <module>
    mel(sr, n_fft) # this snippet works in 0.8.0.
TypeError: mel() takes 0 positional arguments but 2 were given
```

**Expected behavior**
I guess that the latter line works? The function signature seems to indicate that it should, as both `sr` and `n_mels` are positional arguments in the docs.

```python
@cache(level=10)
def mel(
    *,
    sr,
    n_fft,
    n_mels=128,
    fmin=0.0,
    fmax=None,
    htk=False,
    norm="slaney",
    dtype=np.float32,
):
```

The fix for now is just to change it to `sr=blah` etc wherever I used this function. But just wanted to flag it in case it's not intended. Maybe something is wrong in my development environment as well?

**Software versions***
```
macOS-10.16-x86_64-i386-64bit
Python 3.8.8 (default, Feb 24 2021, 13:46:16) 
[Clang 10.0.0 ]
NumPy 1.20.1
SciPy 1.6.1
librosa 0.9.0
INSTALLED VERSIONS
------------------
python: 3.8.8 (default, Feb 24 2021, 13:46:16) 
[Clang 10.0.0 ]

librosa: 0.9.0

audioread: 2.1.9
numpy: 1.20.1
scipy: 1.6.1
sklearn: 0.24.1
joblib: 1.0.1
decorator: 4.4.2
soundfile: 0.10.3
resampy: 0.2.2
numba: 0.53.0

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
sphinxcontrib.versioning: None
sphinx-gallery: None
pytest: 6.2.2
pytest-mpl: None
pytest-cov: None
matplotlib: 3.3.4
presets: None
```

**Comment by pseeth** [comment]
Nevermind, I just saw this: https://github.com/librosa/librosa/pull/1431. I didn't know about this `*` syntax. Closing this issue, as this was clearly discussed and the conclusion to change to this was made already. It did break a considerable amount of my code though, so maybe it should be elevated in the changelog a bit.

**Comment by bmcfee** [comment]
Yeah, fair point. I'd be open to updating the docs to highlight it, but I don't want to completely replicate the python documentation on keyword-only arguments.

A pr to get that started would be appreciated, as I'm a bit short on time to draft it myself right now.

**Comment by bmcfee** [comment]
Heads up, 0.9.1 release just hit pypi and shims warnings in place here instead of going directly to error.  Hopefully that helps ease the transition before the 0.10 release.
