### ISSUE TITLE
Missing list of API breakages due to keyword only

### ISSUE THREAD

**Issue by jonnor** [librosa/librosa#1448]
As discussed in #1114 many (but not all) APIs now require arguments to be passed as keywords. This was released in 0.9.0, breaking many codebases. Everyone affected will need to find out which APIs are affected in order to make the necessary changes.

The changelog only mentions this change. But does not have any information about which functions/classes are impacted (and not).

Can you please provide a list of the affected APIs? So that we can grep across our codebases and attempt to get things working with 0.9.0 again.

In a perfect world, everything would be covered by tests, but that is not always the world we live in.

**Comment by bmcfee** [comment]
> Can you please provide a list of the affected APIs?

If it was only a few, I would have done this.  Given that it's almost the entire library we're talking about here, it seemed somewhat pointless to list out all functions that were changed.

I think the simplest solution here is to keywordify any call to a librosa function.  It won't be strictly necessary in all cases, but it shouldn't break anything either.

**Comment by jonnor** [comment]
I see. Some (semi) automated way to do those changes would be useful then. I checked a few projects here, and combined they over 1000 calls to various librosa functions. And I have more projects elsewhere. And some third party dependencies that needs fixing. Others will be in the same situation.

Anyone have tips for doing the changes semi automated?. I guess it could either using an IDE, commandline tools, or some Python scripts. Regexs as a last resort... Something that can work both with .py and .ipynb files would be good.

Other libraries, like scikit-learn have recently done same kind of migration, so maybe there are tools or practices from there.

**Comment by bmcfee** [comment]
I think we'll still skip documenting the impacted functions, but #1451 should essentially resolve this for you.  Any chance you could pull that locally and let me know if it would sufficiently meet your needs?
