### ISSUE TITLE
Discussion: deprecating / removing audioread?

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#1456]
Opening a conversation here to plan out how we want to handle deprecating and removing audioread as a dependency.

## Background

When librosa development began, audioread was the best option available for handling audio input in diverse formats.  We eventually added `soundfile` (libsndfile) as a secondary option for decoding, and later promoted that to a first-class dependency.

The current state of the project is that soundfile is the primary and preferred decoder package, and we fall back to audioread only when necessary (i.e., when given a file outside of soundfile's codec support).  We now have some functionality that is *only* supported when using soundfile: notably stream processing, but there are requests for other features (e.g. #1434 ) which could expand this list.

For quite a while, we've been planning to deprecate and remove audioread as a backend, and streamline the library to only use soundfile for I/O.  The primary roadblock to this has been the lack of mp3 support in libsndfile, which should be changing soon.  So now seems like a good time to discuss how we plan to approach the deprecation.

## Audioread vs soundfile codecs

It's worth discussing what we stand to lose by abandoning audioread (and ffmpeg, gstreamer, pymad, etc).  Since soundfile's object interface is a bit richer than audioread's, I believe this entirely comes down to supported audio codecs.

Undoubtedly, the combination of gstreamer, ffmpeg, mad, and coreaudio provides greater format coverage than what is implemented directly in [libsndfile](https://libsndfile.github.io/libsndfile/formats.html).  (See, e.g, [libavcodec](https://en.wikipedia.org/wiki/Libavcodec#Implemented_audio_codecs) for ffmpeg audio codecs.) My hunch is that for the common uses of librosa, it would be exceedingly rare to encounter a format (not including mp3) that would not be supported by libsndfile.  The exception here might be pulling audio directly from audio-video streams (mp4, aac, etc).  

## Why deprecate audioread?

There are three reasons that come to (my) mind in favor of deprecation:

1. minimizing environment complexity
2. functionality (e.g. stream processing)
3. stability, speed, and (upstream) test coverage

### Environment complexity

Audioread is designed to multiplex over different decoder backends, such as gstreamer or ffmpeg.  This maximizes the supported audio codecs, but at the cost of having complex environments that are not easily managed by python.  Support also differs across platforms, which can lead to unexpected differences in behavior.  (GStreamer and ffmpeg both, in turn, multiplex over different modules, so not all environments using these packages will necessarily support the same formats.)  Because these differences can be hidden by audioread (and further obscured by librosa), it can be challenging to diagnose problems.

### Functionality

As far as I can tell, the soundfile API is strictly more complete than audioread in terms of what operations are supported.  If all I/O is conducted through soundfile, this could open up some possibilities for more functional and streamlined API from the librosa side as well.  (If nothing else, it would be more internally consistent by virtue of not needing to support multiple decoder interfaces.)

### Software health

I don't mean to suggest that audioread is unstable, but its test coverage is extremely minimal.  

Moreover, its design inherently interacts with multiple different backend libraries and programs, often through subprocess pipes.  This makes some operations like offset-based load potentially inefficient compared to soundfile's seek-based implementation.

## What timeline makes sense?

It would be great if we could have this deprecation cycle set to complete by the 1.0 release (aiming for 2023.01).  This would mean deprecation in the 0.10 series (summer 2022).  This is an aggressive timeline, but not impossible depending on how quickly things happen on the libsndfile side.

If that is not possible, I would suggest to deprecate in 1.0 and remove in a future 2.0 release.  (We haven't yet begun discussing 2.0 features, but this seems like the kind of change that would be appropriate for a major revision.)  This gives a longer runway for deprecation.

**Comment by bmcfee** [comment]
Excellent news!

**Comment by bmcfee** [comment]
Looks like soundfile 0.11 has released now (Sep 27, 2022)!  https://pypi.org/project/soundfile/0.11.0/

Packages haven't yet made their way to conda(-forge), but once they do, I think we can move ahead with the audioread deprecation with a scheduled removal in version 1.0.

**Comment by bmcfee** [comment]
The conda-forge packages have now all updated to libsndfile 1.1.0 with mp3 support on all platforms, so we can consider this unblocked.

**Comment by bmcfee** [comment]
One thing that we should be aware of here: dropping audioread will likely make it more difficult for people to directly load audio from video files.  FFmpeg and gstreamer both handle this reasonably well, libsndfile not so much.  I don't think this is a huge barrier, but we might want to build out some documentation examples for working with video files just to ease the transition.

**Comment by drscotthawley** [comment]
@bmfee, I have soundfile 0.11.0, but I'm still getting an error when trying to read MP3 file.  Maybe I've misunderstood: I was thinking that audioread was a fallback when soundfile failed.   But perhaps it's the other way around?  In any case: No MP3s for me right now: 

```
soundfile.LibsndfileError: Error opening 'examples/stereo_pewpew.mp3': File contains data in an unknown format.
...
audioread.exceptions.NoBackendError
```
when trying to read an MP3 file that I can read via other means. :-( 

```bash
$ pip list | grep -E 'librosa|soundfile|audioread'
audioread                3.0.0
librosa                  0.9.2
soundfile                0.11.0
```

```bash
$ ffmpeg --help
ffmpeg version N-63101-gc92edd969a-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
....
```

**Comment by bmcfee** [comment]
> @bmcfee , I have soundfile 0.11.0, but I'm still getting an error when trying to read MP3 file. Maybe I've misunderstood: I was thinking that audioread was a fallback when soundfile failed. But perhaps it's the other way around? In any case: No MP3s for me right now:

The first issue here is that the soundfile package has moved to its own exception classes, and librosa 0.9.2 was released before that happened so it doesn't know how to catch them.  This is why it's not falling back to audioread.  Related PR #1228 

The second issue is that while you have soundfile 0.11, it's not clear if you have libsndfile 1.1, or if you do, if it's compiled with mp3 support.  If you use the conda build of libsndfile, this should work out of the box, but if you installed libsndfile by other means it's impossible to say.

**Comment by cbenhagen** [comment]
Please follow https://github.com/libsndfile/libsndfile/issues/389 for more info on support for AAC in M4A (MP4) containers in libsndfile.
