### ISSUE TITLE
hello i would like to know how to stream binary audio data from http request for librosa analysis

### ISSUE THREAD

**Issue by xuboot** [librosa/librosa#1459]
hello i would like to know how to stream binary audio data from http request for librosa analysis
![image](https://user-images.githubusercontent.com/54123895/156960493-f9769523-7406-45b0-8bed-985346e7aa71.png)
I have the same needs as him

**Comment by xuboot** [comment]
import librosa
import io
from six.moves.urllib.request import urlopen



if __name__ == '__main__':

    url = "https://sneezoramafunction.blob.core.windows.net/usersounds/00bd9b8c914947d48724fd7e0c88041b.mp3"

    data, samplerate = librosa.load(io.BytesIO(urlopen(url).read()))


error:
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening <_io.BytesIO object at 0x000002BF66C2ADB0>: File contains data in an unknown format.
PyDev console: using IPython 7.32.0

**Comment by bmcfee** [comment]
Closing this issue due to redundant posting.
