### ISSUE TITLE
Hello, through this API, is it possible to obtain characteristic values without processing MP3 files

### ISSUE THREAD

**Issue by xuboot** [librosa/librosa#1460]
import librosa
import io
from six.moves.urllib.request import urlopen
import soundfile as sf
import io

if __name__ == '__main__':

    url = "https://sneezoramafunction.blob.core.windows.net/usersounds/00bd9b8c914947d48724fd7e0c88041b.mp3"

    #url = "https://downsc.chinaz.net/Files/DownLoad/sound1/202111/14994.wav"

    x =io.BytesIO(urlopen(url).read())

    data, samplerate = sf.read(x)

    print(data)
    print(samplerate)

error:
   RuntimeError: Error opening <_io.BytesIO object at 0x0000029859056938>: File contains data in an unknown format.

**Comment by lostanlen** [comment]
Hello,

Install FFMPEG and try using `librosa.load` instead of `sf.read`

https://github.com/librosa/librosa#audioread-and-mp3-support

**Comment by bmcfee** [comment]
@xuboot please do not post the same question multiple times in different issue threads.
