### ISSUE TITLE
Hello, big guy, librosa.load is very slow to load audio data, is there a way to optimize that, or does the community have a solution?

### ISSUE THREAD

**Issue by xuboot** [librosa/librosa#1463]
Hello, big guy, librosa.load is very slow to load audio data, is there a way to optimize that, or does the community have a solution?
For example, 3-5 minutes of audio, especially in librosa.load(data_path, sr=16000), takes more than 10 seconds，Can it still be optimized?

**Comment by lostanlen** [comment]
It might be because of resampling and conversion to mono. Try `mono=False`, `sr=None`
https://librosa.org/blog/2019/07/17/resample-on-load/

Alternatively, try `PySoundFile`

**Comment by xuboot** [comment]
Thank you, but the problem of slow loading audio data has been solved, but I will use librosa It is found in magphase (D, power = 1) that the program enters this function (this function means that the complex matrix D (F, t) is separated into a function of amplitude s and phase P, d = s * P). This function is very slow. Do you know why the upper function is librosa STFT (short time Fourier transform (STFT), which returns a complex matrix D (F, t)) takes two seconds to execute, while librosa Magphase (D, power = 1) takes 7 seconds to execute this function. Can this operation still optimize the space

**Comment by bmcfee** [comment]
magphase is certainly not slower than stft.  (Take a look at the [source](https://librosa.org/doc/latest/_modules/librosa/core/spectrum.html#magphase)).

If you don't actually need the phase information, you could shave a little time by using `np.abs(D)` instead of magphase.
