### ISSUE TITLE
In Pyqt5 application where I use Librosa, it freezes when it changes size

### ISSUE THREAD

**Issue by mvx20** [librosa/librosa#1464]
Hello,
I want to get a visual mp3 wave in matploit with libroso. When I integrate it into the desktop app, changes in app size show up as big freezes. What can I do for it ?

**Comment by bmcfee** [comment]
This sounds like a matplotlib issue, not librosa.

**Comment by mvx20** [comment]
> This sounds like a matplotlib issue, not librosa.

works fine in visual analysis outside of librosa

**Comment by bmcfee** [comment]
> works fine in visual analysis outside of librosa

Maybe, but librosa has nothing to do with drawing figures, application windows, or anything like that.  Matplotlib does, so I'm very inclined to think it's responsible.
