### ISSUE TITLE
the way used in pre-emphasis func

### ISSUE THREAD

**Issue by Haibit** [librosa/librosa#1483]
***BEFORE POSTING A BUG REPORT*** Please look through [existing issues (both open and closed)](https://github.com/librosa/librosa/issues?q=is%3Aissue) to see if it's already been reported or fixed!

**Describe the bug**
The description of the pre-emphasis func may be wrong. It is the first-order moving average method rather than first-order auto aggressive method.

y[n] -> x[n] - coef * x[n-1]

H(z) = 1 - az^(-1)

**Comment by bmcfee** [comment]
Good catch - an easy mistake to make given our convention of using y as the input variable.
