### ISSUE TITLE
FloatingPointError: underflow encountered in square

### ISSUE THREAD

**Issue by weWillGetThere** [librosa/librosa#1484]
It only happens in some audios, but it occurs frequently.
And it happens not only in just one function, but many functions like librosa.beat.beat_track() and librosa.feature.mfcc().
Below is an example of librosa.beat.beat_track().
```
---> 14 tempo, base_beats = librosa.beat.beat_track(y=base, sr=44100)
File \anaconda\lib\site-packages\librosa\util\decorators.py:88, in deprecate_positional_args.<locals>._inner_deprecate_positional_args.<locals>.inner_f(*args, **kwargs)
     86 extra_args = len(args) - len(all_args)
     87 if extra_args <= 0:
---> 88     return f(*args, **kwargs)
     90 # extra_args > 0
     91 args_msg = [
     92     "{}={}".format(name, arg)
     93     for name, arg in zip(kwonly_args[:extra_args], args[-extra_args:])
     94 ]

File \anaconda\lib\site-packages\librosa\beat.py:181, in beat_track(y, sr, onset_envelope, hop_length, start_bpm, tightness, trim, bpm, prior, units)
    172     bpm = tempo(
    173         onset_envelope=onset_envelope,
    174         sr=sr,
   (...)
    177         prior=prior,
    178     )[0]
    180 # Then, run the tracker
--> 181 beats = __beat_tracker(onset_envelope, bpm, float(sr) / hop_length, tightness, trim)
    183 if units == "frames":
    184     pass

File \anaconda\lib\site-packages\librosa\beat.py:599, in __beat_tracker(onset_envelope, bpm, fft_res, tightness, trim)
    596 beats = np.array(beats[::-1], dtype=int)
    598 # Discard spurious trailing beats
--> 599 beats = __trim_beats(localscore, beats, trim)
    601 return beats

File \anaconda\lib\site-packages\librosa\beat.py:682, in __trim_beats(localscore, beats, trim)
    679 smooth_boe = scipy.signal.convolve(localscore[beats], scipy.signal.hann(5), "same")
    681 if trim:
--> 682     threshold = 0.5 * ((smooth_boe ** 2).mean() ** 0.5)
    683 else:
    684     threshold = 0.0

FloatingPointError: underflow encountered in square
```
version: 0.9.1

**Comment by lostanlen** [comment]
Hello @weWillGetThere (nice alias)
Could you share an audio example where this error happens?
I tried to reproduce it by taking the trumpet example and attenuating it. No problem so far.

```
>>> y, sr = librosa.load(librosa.ex("trumpet"))
>>> print("\n".join([str(librosa.beat.beat_track(y=y*10**(-n), sr=sr)) for n in range(7)]))(184.5703125, array([48, 61, 74, 88]))
(184.5703125, array([48, 61, 74, 88]))
(184.5703125, array([48, 61, 74, 88]))
(184.5703125, array([48, 61, 74, 88]))
(95.703125, array([62, 89]))
(0, array([], dtype=int64))
(0, array([], dtype=int64))
```

I'm not sure how your problem can be solved, except by increasing precision:

```python
y = y.astype("double")
```

or amplifying the signal:

```python
y = (y/y.max()) * 2**63)
```

or both.

**Comment by weWillGetThere** [comment]
[vocals.zip](https://github.com/librosa/librosa/files/8748115/vocals.zip)

**Comment by lostanlen** [comment]
No problem on my machine

```
>>> import librosa
>>> import numpy as np
>>> y, sr = librosa.load("vocals.wav")
>>> librosa.beat.beat_track(y=y, sr=sr)
(234.90767045454547, array([ 381,  392,  403,  413,  423,  432,  442,  452,  462,  473,  484,
        495,  506,  517,  529,  541,  552,  563,  574,  585,  596,  607,
        618,  630,  642,  652,  663,  674,  685,  696,  707,  717,  728,
        739,  750,  762,  772,  784,  796,  807,  817,  828,  839,  850,
        861,  872,  883,  894,  905,  915,  925,  936,  947,  958,  969,
        981,  993, 1004, 1014, 1025, 1036, 1046, 1057, 1068, 1078, 1089,
       1100, 1111, 1122, 1134, 1145, 1157, 1169, 1179, 1189, 1199, 1210,
       1221, 1232, 1242, 1252, 1263, 1274, 1285, 1296, 1308, 1320, 1331,
       1342]))
```

Versions
```
>>> librosa.show_versions()
INSTALLED VERSIONS
------------------
python: 3.10.0 (default, Nov 10 2021, 11:24:47) [Clang 12.0.0 ]

librosa: 0.9.0
audioread: 2.1.9
numpy: 1.21.5
```

**Comment by weWillGetThere** [comment]
But I still have this problem.
My version:
```
INSTALLED VERSIONS
------------------
python: 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]

librosa: 0.9.1

audioread: 2.1.9
numpy: 1.21.5
scipy: 1.7.3
sklearn: 1.0.2
joblib: 1.1.0
decorator: 5.1.1
soundfile: 0.10.3
resampy: 0.2.2
numba: 0.55.1

numpydoc: 1.1.0
sphinx: 4.0.1
sphinx_rtd_theme: None
sphinxcontrib.versioning: None
sphinx-gallery: None
pytest: 7.1.1
pytest-mpl: None
pytest-cov: None
matplotlib: 3.5.1
presets: None
```

**Comment by lostanlen** [comment]
I have upgraded to `librosa==0.9.1` and still no error. 
What's your source code? 

```python
librosa.beat.beat_track(y=base, sr=44100)
```

what is in the variable `base`?

**Comment by weWillGetThere** [comment]
```
base, sr = librosa.load(filename, sr=44100)
```

**Comment by bmcfee** [comment]
Replicability here can be an issue here if the codecs are different, or even if the underlying BLAS libraries (and numpy on top) are different.  Which is to say, I believe this is a real problem, but it's going to be tricky to fully reproduce.

The simple hack solution, similar to @lostanlen's suggestion but a bit more streamlined, is to increase precision at load time:

```python
base, sr = librosa.load(filename, sr=44100, dtype=np.float64)
```

This should propagate precision through the rest of the call chain (I think?).

More generally, I wonder if we could be more numerically efficient in implementing the MSE threshold?  Perhaps replace the op `**2` by `np.square`?

**Comment by bmcfee** [comment]
I've been unable to replicate this so far.  I'm attempting the following:

```python
import numpy as np
x = np.float32(1)
y = x.copy()
for n in range(0, -2048, -1):
    y = y / 2
    print(f"{n:4}\t{y:g}\t{y**2:g}")
```
which is designed to underflow float32 precision.  It does not ever trigger the exception above.  Here's my configuration:

```python
In [11]: librosa.show_versions()
INSTALLED VERSIONS
------------------
python: 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:59) 
[GCC 10.3.0]

librosa: 0.9.1

audioread: 2.1.9
numpy: 1.21.6
scipy: 1.8.0
sklearn: 1.1.0
joblib: 1.1.0
decorator: 5.1.1
soundfile: 0.10.3
resampy: 0.2.2
numba: 0.55.1
pooch: v1.6.0
packaging: 21.3

numpydoc: 1.2.1
sphinx: 4.5.0
sphinx_rtd_theme: 1.0.0
sphinx_multiversion: 0.2.4
sphinx_gallery: 0.10.1
mir_eval: 0.6
ipython: None
sphinxcontrib-svg2pdfconverter: None
pytest: 7.1.2
pytest-mpl: None
pytest-cov: None
matplotlib: 3.5.2
samplerate: 0.1.0
soxr: 0.2.3
contextlib2: installed, no version number available
presets: 0.1.3
```
```python
In [9]: np.show_config()
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/bmcfee/miniconda/envs/py39/lib']
    include_dirs = ['/home/bmcfee/miniconda/envs/py39/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/bmcfee/miniconda/envs/py39/lib']
    include_dirs = ['/home/bmcfee/miniconda/envs/py39/include']
    language = c
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['/home/bmcfee/miniconda/envs/py39/lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/bmcfee/miniconda/envs/py39/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/bmcfee/miniconda/envs/py39/include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512CD,AVX512_KNL,AVX512_KNM,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX512_ICL
```

@weWillGetThere one thing that might be relevant here is the numpy error configuration.  Can you run `np.geterr()` in your environment and report the result?  For my installation, I have:
```python
In [12]: np.geterr()
Out[12]: {'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}
```
My guess is that your configuration might have `'under': 'raise'`.  If my guess is correct, then there's nothing really for us to do here.  The underflow is expected in this case, and ought to be harmless, so you could (temporarily) do `np.seterr(under='ignore')` (or warn, or whatever) to avoid this issue.

**Comment by weWillGetThere** [comment]
> I've been unable to replicate this so far. I'm attempting the following:
> 
> ```python
> import numpy as np
> x = np.float32(1)
> y = x.copy()
> for n in range(0, -2048, -1):
>     y = y / 2
>     print(f"{n:4}\t{y:g}\t{y**2:g}")
> ```
> 
> which is designed to underflow float32 precision. It does not ever trigger the exception above. Here's my configuration:
> 
> ```python
> In [11]: librosa.show_versions()
> INSTALLED VERSIONS
> ------------------
> python: 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:59) 
> [GCC 10.3.0]
> 
> librosa: 0.9.1
> 
> audioread: 2.1.9
> numpy: 1.21.6
> scipy: 1.8.0
> sklearn: 1.1.0
> joblib: 1.1.0
> decorator: 5.1.1
> soundfile: 0.10.3
> resampy: 0.2.2
> numba: 0.55.1
> pooch: v1.6.0
> packaging: 21.3
> 
> numpydoc: 1.2.1
> sphinx: 4.5.0
> sphinx_rtd_theme: 1.0.0
> sphinx_multiversion: 0.2.4
> sphinx_gallery: 0.10.1
> mir_eval: 0.6
> ipython: None
> sphinxcontrib-svg2pdfconverter: None
> pytest: 7.1.2
> pytest-mpl: None
> pytest-cov: None
> matplotlib: 3.5.2
> samplerate: 0.1.0
> soxr: 0.2.3
> contextlib2: installed, no version number available
> presets: 0.1.3
> ```
> 
> ```python
> In [9]: np.show_config()
> blas_info:
>     libraries = ['cblas', 'blas', 'cblas', 'blas']
>     library_dirs = ['/home/bmcfee/miniconda/envs/py39/lib']
>     include_dirs = ['/home/bmcfee/miniconda/envs/py39/include']
>     language = c
>     define_macros = [('HAVE_CBLAS', None)]
> blas_opt_info:
>     define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
>     libraries = ['cblas', 'blas', 'cblas', 'blas']
>     library_dirs = ['/home/bmcfee/miniconda/envs/py39/lib']
>     include_dirs = ['/home/bmcfee/miniconda/envs/py39/include']
>     language = c
> lapack_info:
>     libraries = ['lapack', 'blas', 'lapack', 'blas']
>     library_dirs = ['/home/bmcfee/miniconda/envs/py39/lib']
>     language = f77
> lapack_opt_info:
>     libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
>     library_dirs = ['/home/bmcfee/miniconda/envs/py39/lib']
>     language = c
>     define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
>     include_dirs = ['/home/bmcfee/miniconda/envs/py39/include']
> Supported SIMD extensions in this NumPy install:
>     baseline = SSE,SSE2,SSE3
>     found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
>     not found = AVX512F,AVX512CD,AVX512_KNL,AVX512_KNM,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX512_ICL
> ```
> 
> @weWillGetThere one thing that might be relevant here is the numpy error configuration. Can you run in your environment and report the result? For my installation, I have:`np.geterr()`
> 
> ```python
> In [12]: np.geterr()
> Out[12]: {'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}
> ```
> 
> My guess is that your configuration might have . If my guess is correct, then there's nothing really for us to do here. The underflow is expected in this case, and ought to be harmless, so you could (temporarily) do (or warn, or whatever) to avoid this issue.`'under': 'raise'``np.seterr(under='ignore')`

I've changed my numpy configuration and now it works. Thank you!

**Comment by bmcfee** [comment]
Great! I think we can safely close this one out as a wontfix.
