### ISSUE TITLE
What does the fmin and fmax mean in pitch computation?

### ISSUE THREAD

**Issue by JohnHerry** [librosa/librosa#1486]
**Is your feature request related to a problem? Please describe.**

Docuemnt

I am processing speech, the function `librosa.pyin` can compute pitch-tensor for a speech audio.  but according to its document,  I am not clear about the two parameters: fmin and fmax;   Are they the border frequency of the speech audio（eg. 0, 8000 for 16KHz speech audio）? or the probabl border values about F0 of the speech audio?

**Comment by lostanlen** [comment]
Hello @JohnHerry ,

The latter. `librosa.pyin` considers the full spectrum of the sound for its computation but will only produce candidate `f0` values between `fmin` and `fmax`. For speech, i would recommend something like `fmin = 50` and `fmax = 500`.

**Comment by JohnHerry** [comment]
> Hello @JohnHerry ,
> 
> The latter. `librosa.pyin` considers the full spectrum of the sound for its computation but will only produce candidate `f0` values between `fmin` and `fmax`. For speech, i would recommend something like `fmin = 50` and `fmax = 500`.

Thank you for the help, by the way, Is there a suggested value of 'frame_length' to process speech (for speech sr=16000)?

**Comment by lostanlen** [comment]
The original YIN paper supplies some recommended values for speech
http://audition.ens.fr/adc/pdf/2002_JASA_YIN.pdf

**Comment by JohnHerry** [comment]
Thanks for help.

> The original YIN paper supplies some recommended values for speech http://audition.ens.fr/adc/pdf/2002_JASA_YIN.pdf

Thanks for help, I will find it.
