### ISSUE TITLE
Numpy array truthiness error during effects.split

### ISSUE THREAD

**Issue by timlundy** [librosa/librosa#1489]
When loading a file and trying to run librosa.effects.split() on it, I get this error:

```
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/librosa/effects.py", line 574, in split
    if non_silent[0]:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**To Reproduce**
```
import librosa
import numpy as np

y, sr = librosa.load("path/to/file.mp3", sr=44100, mono=False)
intervals = librosa.effects.split(y, top_db=22, ref=np.max, frame_length=44100, hop_length=44100)
```

**Expected behavior**
The split effect returning an array of non-silent intervals.

**Software versions***
```
INSTALLED VERSIONS
------------------
python: 3.8.12 (default, Oct 13 2021, 06:42:42) 
[Clang 13.0.0 (clang-1300.0.29.3)]

librosa: 0.9.1

audioread: 2.1.9
numpy: 1.22.4
scipy: 1.8.1
sklearn: 1.1.1
joblib: 1.1.0
decorator: 5.1.1
soundfile: 0.10.3
resampy: 0.2.2
numba: 0.55.2

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
sphinxcontrib.versioning: None
sphinx-gallery: None
pytest: None
pytest-mpl: None
pytest-cov: None
matplotlib: None
presets: None
```

**Additional context**
This is a file I haven't touched in a while, so I apologize if it is something that is covered in a changelog somewhere. However, I was unable find any similar issues.

**Comment by bmcfee** [comment]
Thanks for reporting!  I think I understand what's going on here.  The offending code segments are:
https://github.com/librosa/librosa/blob/a19da5075663321d49afd9beca574e4ee527f5b7/librosa/effects.py#L573-L579

There are two things wrong with this when applied to multi-channel inputs:

1. `non_silent[0]` is an array, not a scalar, so we need to aggregate somehow.  This is suggested by the error message in the initial post; I would expect `any()` to be the correct aggregator here, as non-silence should be disjunctive across channels.
2. The array index should be trailing, not leading.  That is, we should have `non_silent[..., 0]`.  

Of course, this also applies to the trailing frame logic, `non_silent[..., -1]`.

I'm not sure how this one slipped past our CR for 0.9, but I guess it did.

@timlundy  Can you confirm that this error goes away if you load with `mono=True`?

**Comment by timlundy** [comment]
Using `mono=True` does solve the issue. Thanks so much for looking into it!
