### ISSUE TITLE
Vertical waveshow

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#1496]
**Is your feature request related to a problem? Please describe.**

Branching this issue out from a comment in #1370 and some offline discussions.

TLDR: it could be useful if `waveshow` could draw transposed waveforms, rather than only plotting with time as the horizontal axis.  The main use-case here is probably in things like cross-similarity plots, where it might be nice to have subplots on the top and left sides corresponding to the signals being compared.

**Describe the solution you'd like**
The API could look like `waveshow(..., orient='vertical')`, though we'd probably need to consider revising other parameter names like `offset=` and `x_axis=` to be more flexible and align with what's provided by `specshow`.

**Describe alternatives you've considered**
We could achieve some of this by an axis transformation, but given the headaches we've already seen in melodyplot with this (fill_between does not currently play nicely with axes transforms), I'd rather not.

**Comment by lostanlen** [comment]
Yes, good idea.

Is there precedent for `orient="vertical"`? `plt.xticks` has `rotation=90`, and `plt.bar` has a doppelgänger named `plt.barh`

> We could achieve some of this by an axis transformation,
Do you mean, something in the lines of this?
 https://stackoverflow.com/a/43915452

**Comment by bmcfee** [comment]
The orient argument is (I believe) a seaborn-ism, which provides a more consistent interface over matplotlib's mixture of doppelganger functions and argument swaps.

**Comment by achabotl** [comment]
Giving this a shot during the SciPy sprints.

**Comment by achabotl** [comment]
I'm gonna bail on this until @bmcfee has made changes to `AdaptiveWaveplot` as mentioned in #1532.

**Comment by achabotl** [comment]
The refactor of `AdaptiveWaveplot` is happening in #1539.

**Comment by bmcfee** [comment]
I think #1539 is done enough, but it could use a CR for the docs.
