### ISSUE TITLE
I need `librosa.downbeat_click` function

### ISSUE THREAD

**Issue by ooyamatakehisa** [librosa/librosa#1505]
**Is your feature request related to a problem? Please describe.**
I know there is `librosa.click` function to synthesize a click audio file corresponding to beat times, but I think there isn't one that can handle downbeat times as well.

**Describe the solution you'd like**
It would be useful if there is a function that synthesize clicks with octave freq (twice freq) at downbeats and with base freq at beats. I actually wrote a function myself in my project like the following. I assume the input variable `downbeats` to be the returned value from `madmom.features.downbeats.DBNDownBeatTrackingProcessor` (https://madmom.readthedocs.io/en/v0.16.1/modules/features/downbeats.html#madmom.features.downbeats.DBNDownBeatTrackingProcessor).

```Python
def downbeat_click(downbeats: np.ndarray, length: int, sr: int = 44100) -> None:
    def click(idxs: np.ndarray, is_downbeat: bool, freq: int = 1000):
        if is_downbeat:
            freq *= 2

        return librosa.clicks(
            times=idxs,
            sr=sr,
            click_freq=freq,
            length=length,
        )
    beat_idxs, downbeat_idxs = downbeats[:, 0], downbeats[downbeats[:, 1] == 1][:, 0]
    beat_idxs = np.delete(beat_idxs, np.in1d(beat_idxs, downbeat_idxs))
    return click(beat_idxs, is_downbeat=False) + click(downbeat_idxs, is_downbeat=True)
```

The following is what I created with the above function and what I need in librosa!
https://user-images.githubusercontent.com/44559556/173349429-75c7bee3-0bdf-4a7f-8c04-0a0d3488d628.mp4

**Comment by bmcfee** [comment]
The clicks function is not specific to beats; it works on any set of target times, as your example demonstrates.

Since we don't provide a downbeat estimator, I'm not sure how useful a function as specific as what you're requesting would make sense.  Your example seems fine to me though, and is more or less how I would recommend to do this kind of thing in general.
