### ISSUE TITLE
Get_window from librosa working differently than scipy.signal when using hann

### ISSUE THREAD

**Issue by jopapo** [librosa/librosa#1510]
**The Problem**
The function `librosa.core.spectrum.get_window` getting a different result from `scipy.signal.windows.hann` when using hann (the default one for fft).

get_window [docs](https://librosa.org/doc/main/generated/librosa.filters.get_window.html):

> Compute a window function.
> This is a wrapper for [scipy.signal.get_window]::(https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.get_window.html#scipy.signal.get_window) that additionally supports callable or pre-computed windows.

**To Reproduce**
Example:
```
from scipy import signal
window = signal.windows.hann(6)
print('s6:', window)
window = signal.windows.hann(7)
print('s7:', window)

from librosa import core
window = core.spectrum.get_window('hann', 6, fftbins=True)
print('l6:', window)
window = core.spectrum.get_window('hann', 7, fftbins=True)
print('l7:', window)
```

Results:
```
s6: [0.        0.3454915 0.9045085 0.9045085 0.3454915 0.       ]
s7: [0.   0.25 0.75 1.   0.75 0.25 0.  ]
l6: [0.   0.25 0.75 1.   0.75 0.25]
l7: [0.         0.1882551  0.61126047 0.95048443 0.95048443 0.61126047
 0.1882551 ]
```

**Additional Info**
python: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
librosa: 0.9.1
scipy: 1.7.3

Detected this problem while trying to reproduce the computation on Dart.

**Comment by lostanlen** [comment]
Hello @jopapo 

This is because `librosa.get_window`, like `scipy.signal.get_window`, uses `fftbins=True` by default, which implies `sym=False`. https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.get_window.html

See documentation for `fftbins` in `scipy.signal.get_window`

> If True (default), create a “periodic” window, ready to use with ifftshift and be multiplied by the result of an FFT (see also [fftfreq](https://docs.scipy.org/doc/scipy/reference/generated/scipy.fft.fftfreq.html#scipy.fft.fftfreq)). If False, create a “symmetric” window, for use in filter design.
    

See SciPy code
https://github.com/scipy/scipy/blob/v1.8.1/scipy/signal/windows/_windows.py#L2130


Pass `sym=False` to `hann` and you'll verify that the windows are the same:

```python
from scipy import signal
window = signal.windows.hann(6, sym=False)
print('s6:', window)
window = signal.windows.hann(7, sym=False)
print('s7:', window)
```

Result:

```
s6: [0.   0.25 0.75 1.   0.75 0.25]
s7: [0.         0.1882551  0.61126047 0.95048443 0.95048443 0.61126047
 0.1882551 ]
```

I hope this helps!

**Comment by jopapo** [comment]
Perfect. That's it. Thanks.
Sorry for the miss.
