### ISSUE TITLE
Standardize integer type checks

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#1519]
**Is your feature request related to a problem? Please describe.**
Not a "problem" per se, but we do have some inconsistencies in how integer type checks are performed throughout the package. For example:

https://github.com/librosa/librosa/blob/b9830b4a335b1e7e4be66ee81870573bf3d516d0/librosa/core/audio.py#L939-L940

vs

https://github.com/librosa/librosa/blob/b9830b4a335b1e7e4be66ee81870573bf3d516d0/librosa/core/audio.py#L421-L422

both do essentially the same job, but aren't identical.

**Describe the solution you'd like**
We should comb through the package and standardize this.  Or maybe write a simple helper routine to simplify the process.

I think my preference is for the second version above, i.e., using subdtype, but there may be some aspects to this that I don't fully understand.

**Comment by achabotl** [comment]
I'll give this a shot.
