### ISSUE TITLE
lazy-import for submodules

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#1523]
**Is your feature request related to a problem? Please describe.**

Way back in the past, we made the `display` submodule "optional".  This means that you can use librosa without importing any of the display submodule, or even installing its specific dependencies (ie matplotlib).  This was done primarily to avoid memory bloat, but also to keep the environment dependencies down when display is not needed, eg in embedded device applications.  The memory bloat issue is largely gone at this point due to improved usage of matplotlib, but the environment dependency issue persists.

The drawback of this optional design is that users need to explicitly import `librosa.display`.  This is a minor nuisance, but it does lead to one of our [most googled questions](https://www.google.com/search?channel=fs&client=ubuntu&q=attributeerror+module+%27librosa%27+has+no+attribute+%27display%27).  This particularly hits novice users.

**Describe the solution you'd like**

The upcoming scipy 1.9 release uses a lazy-loader to manage submodules: https://github.com/scientific-python/lazy_loader

Rather than loading everything at import time, submodules are only loaded when accessed.  This would make it possible to drop the requirement of explicitly importing `librosa.display` but maintain the benefits of not importing display if it's not needed.

Additionally, if a user *does* try to use `librosa.display` without having a proper environment for it, they'll get a slightly more useful error message that matplotlib is not installed.

**Describe alternatives you've considered**
We could leave it as is.

**Additional context**
This will add a dependency to librosa.  However, scipy 1.9 will also require the lazy-loader package, so on up-to-date environments we'll get this for free.

This may come with some performance hits - I'm not sure, as I haven't tried it out yet.

Additionally, lazy-loader could have some unpredictable interactions with my `presets` package that we might need to sort out.

This is all to say, I'm not 100% sold on this idea yet, but wanted to raise it for discussion.

**Comment by lostanlen** [comment]
as i've said elsewhere: very much in favor of making a minimal change to the behavior of programs while benefiting a maximal number of people.

at the risk of complexifying the discussion, i'll say that a complaint we've received is that librosa is difficult to port on low-resource platforms such as RPi. anyone remembers minispec? https://github.com/marl/minispec

i know that #1150 and other recent PR's have improved portability and memory footprint a great deal. but i wonder if there is overlap between low-resource installation and the current issue? For example, in the prospect of doing time-frequency decomposition on the edge, would it be possible (and beneficial) to only package `core` and `util`?

**Comment by bmcfee** [comment]
That's a great point.  I'm not yet familiar with the details of how lazy-import works though.  We might need to break things into smaller atomic modules to really get import-time gains.  I'm not opposed to this, but it will require some thought.

**Comment by bmcfee** [comment]
Circling back on this discussion:



> i wonder if there is overlap between low-resource installation and the current issue? For example, in the prospect of doing time-frequency decomposition on the edge, would it be possible (and beneficial) to only package `core` and `util`?

The PR #1579 implements lazy-loading at the top level of the module.  In principle, we could lazy-load the submodule internals as well (`core.*`, `util.*`).  It gets a little questionable how much benefit we can expect there, eg for speeding up something like `from librosa import stft` vs `import librosa; librosa.stft`.
