### ISSUE TITLE
Clarify kwargs in feature functions

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#1525]
Some of our feature functions (melspectrogram, mfcc, etc) use kwargs to pass through parameters to core functions (stft, filter construction etc).  This isn't terribly well documented, and can be a little difficult for new users to navigate and understand what the options are.

At this point, it's probably worth replacing some of these kwargs, eg
https://github.com/librosa/librosa/blob/25538adb3aed3485a06e60b6dad88be3d540f0c2/librosa/feature/spectral.py#L1767-L1769
by
```python 
def mfcc(
    *, y=None, sr=22050, S=None, n_mfcc=20, dct_type=2, norm="ortho", lifter=0,
    n_mels=128, n_fft=2048, ...
):
```

Alternatively, if we don't want to make the API totally redundant, we could at least provide more documentation in the kwarg'ed functions' docstrings to better explain what options are available.

**Comment by Embot2000** [comment]
If no one has started working on this issue I'd like to give it a try!

**Comment by bmcfee** [comment]
Awesome, thanks!

**Comment by lostanlen** [comment]
@Embot2000 thank you for taking this :)

Is the plan to copy-paste the docstring of called functions or to have some sort of dynamic formatting? 

That's what we do in Kymatio: https://github.com/kymatio/kymatio/blob/main/kymatio/scattering2d/frontend/base_frontend.py#L109=
and it kinda works: https://www.kymat.io/codereference.html#module-kymatio.torch

The advantage is that it reduces duplicate documentation and thus is easier to maintain. The disadvantage is that it becomes more difficult to read the documentation directly from the Python source.

**Comment by bmcfee** [comment]
@lostanlen Huh, I didn't know that was possible.  I was figuring to just copy-paste these explicitly, since the parameters in question are pretty standard and have not changed in years.  But I'm open to more elegant solutions as well.

**Comment by lostanlen** [comment]
i'm OK for copy-pasting. as you said, it's not like we're going to need to rephrase these docs many times in the future; and i we ever needed to, we'll just have to remember to make a search-and-replace. i just wanted to mention the other solution for completeness

**Comment by Embot2000** [comment]
@lostanlen thanks for that! Honestly my plan was to copy and paste but I will take a look at this! 

I was going to ask if the preferred fix would be option 1 in the issue description or option 2. I was leaning towards just updating the docstrings and leaving the API as is. It sounds like that's what you guys were leaning towards as well?

**Comment by bmcfee** [comment]
Yeah, that sounds good to me!

**Comment by lostanlen** [comment]
@Embot2000 yes, option 1. "Simple is better than complex" 😊 

Dynamic formatting is a cool trick but having an MFCC docstring that reads like

```
...
{n_mels_definition}
{n_stft_definition}
{win_length_definition}
...
```

will cause immense frustration for people (like me) who like to read documentation directly from the source. A frustration that isn't justified by saving 15 minutes of a maintainer's time in the next 2 years 😅 

So, copy-paste it is.

OK good luck!

**Comment by Embot2000** [comment]
OK, I went through all of the feature functions and these are what I found:

`spectral.py`
1. `zero_crossing_rate()`
2. `chroma_stft()`
3. `tonnetz()`
4. `mfcc()`
5. `melspectrogram()`

`inverse.py`
1. `mel_to_stft()`
2. `mel_to_audio()`
3. `mfcc_to_audio()`

`utils.py`
1. `delta()`
2. `stack_memory()`

Please let me know if I missed any or if any of these are not necessary to change.

**Comment by bmcfee** [comment]
Thanks @Embot2000 - that looks like a good start.  I might hold off on the last two since they're kwargs to external functions in numpy and scipy.

On the feature side, I think you have it covered.  We could also look at some other parts of the package after that, eg effects and decompose, but let's get the feature parts done first.
