### ISSUE TITLE
Speed issues with 0.9.2

### ISSUE THREAD

**Issue by MahdiRepo** [librosa/librosa#1542]
I have realized that the new 0.9.2 release is significantly slower at least on my machine. 

Performance of 0.9.2 >>> tqdm shows around 2.5 it/s

![Screenshot 2022-07-21 132158](https://user-images.githubusercontent.com/87185112/180217238-db4a3cee-1f80-4fdf-a394-dc2a69650b3f.png)

Performance of 0.9.1 >>> tqdm shows around 32 it/s

![1](https://user-images.githubusercontent.com/87185112/180217529-b3dc9893-9bd8-4d82-8a65-d36cd11a7b55.png)

Here is the function:
![2](https://user-images.githubusercontent.com/87185112/180217740-d422c6e4-9dda-45a2-a1b8-74d6d9057cc3.png)

Of course, everything else is consistant across both runs..

**Comment by bmcfee** [comment]
Please use the issue report template we provide.

I'm pretty sure that this is not a librosa issue, but instead a resampy issue.  If you had filled out the template with all the dependency versions, this would be easier to diagnose.

Meanwhile, try loading with `res_type='soxr_hq'` (if you have the soxr dependency installed) or `res_type='sinc_medium'` (if you have the samplerate dependency installed).

**Comment by bmcfee** [comment]
Closing this out from lack of activity, but it may also be a dupe/related to #1541 and other upstream issues from the 0.3.1 release of resampy.
