### ISSUE TITLE
AttributeError: module 'librosa' has no attribute 'load'

### ISSUE THREAD

**Issue by kikoooooooo** [librosa/librosa#1546]
***BEFORE POSTING A BUG REPORT*** Please look through [existing issues (both open and closed)](https://github.com/librosa/librosa/issues?q=is%3Aissue) to see if it's already been reported or fixed!

**Describe the bug**
I am trying to load a mp3 file, but I am met with the error message: `AttributeError: module 'librosa' has no attribute 'load'`.

**To Reproduce**
librosa is in it's own subdirectory & a file in the parent directory imports librosa and runs `func()`.

```
import librosa

def func():

if input == "soundtest":
    filename = "user/audio/songs/TakeB.mp3"
    y, sr = librosa.load(filename)

```

**Expected behavior**
I expected for the audio file to play

**Screenshots**

**Software versions***

```
Windows-10-10.0.19044-SP0
Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
NumPy 1.22.4
SciPy 1.9.0
librosa 0.9.2
INSTALLED VERSIONS
------------------
python: 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]   

librosa: 0.9.2

audioread: 2.1.9
numpy: 1.22.4
scipy: 1.9.0
sklearn: 1.1.1
joblib: 1.1.0
decorator: 5.1.1
soundfile: 0.10.3
resampy: 0.3.1
numba: 0.56.0
pooch: v1.6.0
packaging: 21.3

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
sphinx_multiversion: None
sphinx_gallery: None
mir_eval: None
ipython: None
sphinxcontrib-svg2pdfconverter: None
pytest: None
pytest-mpl: None
pytest-cov: None
matplotlib: None
samplerate: None
soxr: None
contextlib2: None
presets: None
```

**Additional context**
See reproduction. 
The software versions script was run within the librosa subdirectory.
librosa is installed with the pip script from the docs.

**Comment by bmcfee** [comment]
> librosa is in it's own subdirectory

You probably need to install it, not just download it in a subdirectory.  See https://librosa.org/doc/latest/install.html



> I expected for the audio file to play

load does not play the file, it only loads the data into a numpy array.

**Comment by kikoooooooo** [comment]
I installed it with pip, & moving the contents of the subdirectory into parent still returns the error message.

**Comment by bmcfee** [comment]
> I installed it with pip, & moving the contents of the subdirectory into parent still returns the error message.

If you're moving package files around after installing, that could very well cause problems like this.  I recommend to install in a clean environment using either pypi (downloading via pip and not cloning from github) or conda.

**Comment by romino666** [comment]
If i can extract non-resampled multitracks, i can choose wav or flac format.
