### ISSUE TITLE
remove "hanning" window

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#1547]
**Describe the bug**

scipy 1.9 removed the `hanning` window function.  We never use this directly, but do support it as an option in a few places.

I think it's fine to leave support in, but we'll need to remove hanning from the tests to keep things passing cleanly.

**Comment by lostanlen** [comment]
Hanning is an unfortunate pun that mixes the names of Julius von Hann and Richard Hamming. I'm pro removal from the librosa codebase (by way of deprecation)

**Comment by bmcfee** [comment]
> I'm pro removal from the librosa codebase (by way of deprecation)

I would be too.  However, it's not explicitly in librosa at all except for the following alias in the window bandwidth table:
https://github.com/librosa/librosa/blob/28217993f90c1cbe7fc079b67d12be807ec329a8/librosa/filters.py#L108

Now, we could totally remove that and it wouldn't cause any real harm.  In the worst case, if a user asks for `hanning` and is on an older scipy (<1.9) that still provides it, we would just recalculate the bandwidth on the fly instead of using the cached lookup table.

I left it in when making #1548 because the minimum supported versions still provide hanning.  Thinking it over though, it does leave us in a weird spot right now where a user on scipy 1.9 could get the window bandwidth for `hanning` but not actually be able to use it.  Perhaps I should reopen that PR and remove the cached alias?
