### ISSUE TITLE
Create a Librosa Script in Batch File

### ISSUE THREAD

**Issue by romino666** [librosa/librosa#1555]
@lostanlen Anybody can found to create a librosa script in batch file in Windows and a script in Windows PowerShell ?

**Comment by lostanlen** [comment]
Hello @romino666, please fill in the issue template.

**Is your feature request related to a problem? Please describe.**
**Describe the solution you'd like**
**Describe alternatives you've considered**

**Comment by romino666** [comment]
I didn't found solutions about create a script using batch command on Windows, if you can found an idea to create librosa script later, I can download the batch file soon.

**Comment by romino666** [comment]
And i add to create a Powershell script to install Librosa under Windows 10.

**Comment by bmcfee** [comment]
@romino666 I'm not sure what exactly you're asking, but it sounds like you want help with programming a windows gui, not with librosa.  I don't think our github issues is the appropriate forum for this kind of question.
