### ISSUE TITLE
import librosa causes flask app on IIS to 500

### ISSUE THREAD

**Issue by ebachura** [librosa/librosa#1576]
***BEFORE POSTING A BUG REPORT*** Please look through [existing issues (both open and closed)](https://github.com/librosa/librosa/issues?q=is%3Aissue) to see if it's already been reported or fixed!

**Describe the bug**
import librosa causes flask app on iis to timeout and return 500

**To Reproduce**
Not going to put all the steps here to set up a flask app on IIS/Windows but generally something like this:
https://medium.com/@dpralay07/deploy-a-python-flask-application-in-iis-server-and-run-on-machine-ip-address-ddb81df8edf3
```
#somewhere in the app have the following
import librosa
```
Your app will hang indefinitely until timeout, forcing webserver to report 500

**Expected behavior**
librosa loads without issue

**Screenshots**

**Software versions***
Windows-10-10.0.20348-SP0
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
NumPy 1.23.3
SciPy 1.9.1
librosa 0.9.2
INSTALLED VERSIONS
------------------
python: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]

librosa: 0.9.2

audioread: 3.0.0
numpy: 1.23.3
scipy: 1.9.1
sklearn: 1.1.2
joblib: 1.2.0
decorator: 5.1.1
soundfile: 0.10.3
resampy: 0.4.2
numba: 0.56.2
pooch: v1.6.0
packaging: 21.3

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
sphinx_multiversion: None
sphinx_gallery: None
mir_eval: None
ipython: None
sphinxcontrib-svg2pdfconverter: None
pytest: None
pytest-mpl: None
pytest-cov: None
matplotlib: None
samplerate: None
soxr: None
contextlib2: None
presets: None

**Additional context**
This is a difficult issue to trouble shoot because I am seeing no related errors in trace files nor logs from IIS. I've narrowed it down to exactly librosa though. I can comment out a librosa import and everything runs, but if I attempt to import the webpage will spin until it times out and returns a 500.

Environment is python 3.10, librosa was installed with pip. No virtual env at this time, only one python installion. Windows server 2019, IIS 10 (using fastcgi/wfastcgi.py as handler).

I've tested to see if an exception is being thrown but it does not appear so (the except of a try except does not appear to trigger, it simply hangs on trying to import librosa).

I've tested librosa independent of the flask/IIS context and it loads fine. FFMPeg is in path, audio analysis functions work fine.

I'm confident this has something to do with librosa need some environment variable/setting that is not being picked up by the IIS context, but for the life of me I can't figure out what that would be. I suspect this because I can force the IIS application pool to run as my login and it will work, but if I have it run as apppool then it fails. Only librosa fails to import running as apppool, every other aspect of the app works (and there are a lot of imports, from pydodbc, to pandas, to plotting pacakges, to numpy and sklearn and even some installed directly from github and custom ones not publicly availalble. It seems librosa needs some sort of environment variable to load?

Any assistance or leads would be appreciated.

**Comment by bmcfee** [comment]
This is nearly impossible to debug directly, but something you might want to try is replacing `import librosa` by `import X` for each of the core dependencies listed in the `show_versions()` (ie, audioread, numpy, etc. up to packaging).

If one of those triggers the issue, then it's likely upstream of librosa.

If all of those import cleanly, then we need to start thinking about what librosa does at import time.  There are basically two things that come to mind: 1) loading runtime data from disk (eg the example track registry), 2) numba compilation.  I expect (2) would only occur after the package is imported and you try to run certain functions (since compilation is just-in-time).  (1) could be a culprit if there are strange file permission issues to do with running inside IIS. (It's literally been decades since I've had to interact with IIS, so I'm probably no further help on that.)

**Comment by ebachura** [comment]
I just did as your requested. I tested all of them together a la:
# import librosa
import audioread
import numpy
import scipy
import sklearn
import joblib
import decorator
import soundfile
import resampy
import numba
import pooch
import packaging

It runs fine, but if I uncomment librosa, it fails as described. Again, I can make it work by forcing the application to run as my local account, but any of the built in (local system, local service, network service, applicaitonidentity) and it fails.

To be clear, it fails prior to trying to run anything, it's definitely happening on the import of librosa. BTW, might want to double check, I didn't miss any imports to test, I think I got them all.

**Comment by ebachura** [comment]
Sorry, not used to the commenting here, it made import librosa bold because I had a pound sign in front of it when I pasted it (because it was commented out on my script). First time git issue poster, go figure.

**Comment by ebachura** [comment]
Where would I need to give permissions regarding this track registry thing you mention? Also, I would have expected a file access is to throw an exception, not cause it to hang...it's not throwing an exception, which is why I'm on the struggle bus atm.

**Comment by bmcfee** [comment]
> Again, I can make it work by forcing the application to run as my local account, but any of the built in (local system, local service, network service, applicaitonidentity) and it fails.

Ah, I'd missed this on the first read-through.  You said you installed via pip, but I guess it's possible that pip installed as a user instead of the system.  This is really where a virtual environment / container would be most helpful btw.



> Where would I need to give permissions regarding this track registry thing you mention?

Not sure on windows, sorry.  You'll need to locate where librosa installed (eg `print(librosa.__file__)` and make sure your web server has access to read from that location.



> Also, I would have expected a file access is to throw an exception, not cause it to hang...it's not throwing an exception, which is why I'm on the struggle bus atm.

Yep, that sure sounds weird.  But web servers do sometimes do funny things like catch-all exception handlers. :shrug:

**Comment by ebachura** [comment]
In installed python for all users in this environment. I checked and it's in the python lib site-packages location, which is normal as far as I know.

**Comment by ebachura** [comment]
Output to confirm:

C:\Program Files\Python310\lib\site-packages\librosa\__init__.py

**Comment by ebachura** [comment]
The comment box messed up the output again, (replaced the double underscores). Sorry! Not so great at this :)

**Comment by ebachura** [comment]
I think you're probably on the right track regarding some write/read permission related issue. I thought it was maybe an environment variable thing but I read through the librosa files and didn't see anything that really stood out (other than cache management environ settings but that shouldn't stop it as far as I know).

**Comment by ebachura** [comment]
I've figured this out! I was reading through other issues and happened across this one (Number 987):

https://github.com/librosa/librosa/issues/987

The fix recommended by a5467021 is indeed the fix. Granting write/read to users on the librosa library fixes the issue. Thanks for the help!
