### ISSUE TITLE
librosa.load always get mono

### ISSUE THREAD

**Issue by magicse** [librosa/librosa#1582]
librosa.load always get mono (one channel array). 
```
>>> wav, _ = librosa.load(Path('./123.wav', mono=False ))
>>> wav
array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)
>>> wav.shape
(3154751,)
```

Pysound load this file ok, as stereo. 
```
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]] 44100
PCM_16
```
Name: librosa
Version: 0.9.2
Summary: Python module for audio and music processing
Home-page: https://librosa.org
Author: Brian McFee, librosa development team
Author-email: brian.mcfee@nyu.edu
License: ISC
Location: c:\python38\lib\site-packages
Requires: audioread, decorator, joblib, numba, numpy, packaging, pooch, resampy, scikit-learn, scipy, soundfile
Required-by:

**Comment by bmcfee** [comment]
> `>>> wav, _ = librosa.load(Path('./123.wav', mono=False ))`

This is passing the `mono=False` argument to `Path`, not `load`.

**Comment by magicse** [comment]
Thank you
```
>>> wav, _ = librosa.load('./123.wav', mono=False )
>>> wav.shape
(2, 3154751)
>>> wav
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)
>>>
```
