### ISSUE TITLE
libsndfile (soundfile) for mp3 not float32   but float64

### ISSUE THREAD

**Issue by magicse** [librosa/librosa#1583]
Audio out from libsndfile (soundfile) for mp3 not float32   but float64
Maybe it makes sense to add a check for mp3 and change the dtype for the soundfile to float64 in this case?
[audio.py](https://github.com/librosa/librosa/blob/main/librosa/core/audio.py)
```
dtype=np.float32,
```
```
 if isinstance(path, tuple(audioread.available_backends())):
        # Force the audioread loader if we have a reader object already
        y, sr_native = __audioread_load(path, offset, duration, dtype)
    else:
        # Otherwise try soundfile first, and then fall back if necessary
        try:
            y, sr_native = __soundfile_load(path, offset, duration, dtype)
```

**Comment by bmcfee** [comment]
Please use the issue template.

**Comment by magicse** [comment]
I moved it to  [Feature request](https://github.com/librosa/librosa/issues/1584)
