### ISSUE TITLE
libsndfile (soundfile) for mp3 not float32 but float64

### ISSUE THREAD

**Issue by magicse** [librosa/librosa#1584]
**Is your feature request related to a problem? Please describe.**
Audio out from libsndfile (soundfile) for mp3 not float32 but float64. 
Because of this, if we do not force the dtype=float64 , we get an empty array

**Describe the solution you'd like**
Maybe it makes sense to add a check for mp3 and change the dtype for the soundfile to float64 in this case?
In file https://github.com/librosa/librosa/blob/main/librosa/core/audio.py

**Additional context**
```
 if isinstance(path, tuple(audioread.available_backends())):
        # Force the audioread loader if we have a reader object already
        y, sr_native = __audioread_load(path, offset, duration, dtype)
    else:
        # Otherwise try soundfile first, and then fall back if necessary
        try:
            y, sr_native = __soundfile_load(path, offset, duration, dtype) <----------------- here also make check fro mp3 type
```

**Comment by magicse** [comment]
print with dtype set float32
```
[]
0
(2, 0)
tensor([], size=(2, 0))
```
print wav with dtype =float64
```
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
21182464
(2, 10591232)
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
```

**Comment by bmcfee** [comment]
The relevant code here is https://github.com/librosa/librosa/blob/5e86d5f31238b72c37c4f9758948f8b75068cc03/librosa/core/audio.py#L201-L202

Per the [soundfile documentation](https://pysoundfile.readthedocs.io/en/latest/#module-soundfile):
> dtype ({'float64', 'float32', 'int32', 'int16'}, optional) –
> Data type of the returned array, by default 'float64'. Floating point audio data is typically > in the range from -1.0 to 1.0. Integer data is in the range from -2**15 to 2**15-1 for > 'int16' and from -2**31 to 2**31-1 for 'int32'.

If soundfile is not respecting the dtype parameter, that sounds like a bug upstream of us.

**Comment by magicse** [comment]
If I didn't set dtype for librosa.load then I get empty array for mp3.

**Comment by magicse** [comment]
file for test
[abba.zip](https://github.com/librosa/librosa/files/9674303/abba.zip)

**Comment by bmcfee** [comment]
@magicse as stated above, I don't think this is our bug to fix (if it is a bug).  I would suggest to try reading from soundfile directly with the specified dtype.  I expect you'll find the same behavior.

Also, *please* use the issue template and fill out all fields.  This information is helpful to maintainers for diagnosing issues, and it really does not require much effort from your side.
