### ISSUE TITLE
Plot subtitle and ticks overlap

### ISSUE THREAD

**Issue by tcsmaster** [librosa/librosa#1585]
**Describe the bug**
In version 0.10.0, for the following functions/examples, the included example plot's subtitles and axis ticks are overlapping with each other:

https://librosa.org/doc/main/generated/librosa.sequence.dtw.html#librosa.sequence.dtw
https://librosa.org/doc/main/generated/librosa.feature.mfcc.html
https://librosa.org/doc/main/generated/librosa.filters.wavelet.html
https://librosa.org/doc/main/generated/librosa.filters.window_sumsquare.html
https://librosa.org/doc/main/auto_examples/plot_music_sync.html

In version 0.9.2, the issue is not present in any of the cases.

**Comment by bmcfee** [comment]
Thanks for catching these.  I'm not yet sure why it's happening, but it's good that it seems confined to the development builds for now.

**Comment by bmcfee** [comment]
Aha!  I see what's happening here.  It's down to this line:

https://github.com/librosa/librosa/blob/96f8beeea7253ebe0b7606d1cbec359a30ae3b6b/docs/conf.py#L101

This worked fine when the version numbers were lexically sorted (`'0.9' > '0.8'`) but fails once we get to `'0.10.0...'`.  As a result, the docs are not setting `constrained_layout`.

The good news is that this is no longer necessary, as our oldest doc build is now 0.8, so we can unequivocally set this to `True` and the problem should resolve itself.  I'll get a PR going.

**Comment by bmcfee** [comment]
Just following up that the new doc build is up and these have all been resolved.

**Comment by tcsmaster** [comment]
Thanks! I'm glad I could help out a little bit! :)

Regards

Csani

Brian McFee ***@***.***> ezt írta (időpont: 2022. okt. 11., K
21:47):
