### ISSUE TITLE
What's the relationship between "t" returned by mfcc and Duration of audio?

### ISSUE THREAD

**Issue by MinaAku** [librosa/librosa#1588]
Thank you for your contribution to the project and the spirit of open source. Your achievements have brought great help to my work!
Limited by the knowledge of language and acoustics, I shamefully ask, what is the relationship between t returned by mfcc() features and duration of audio? Thanks for answering my question!

**Comment by lostanlen** [comment]
Hello. Thank you for your kind words!
The following functions may be of use to you:

* `librosa.get_duration`
* `librosa.times_like`
* `librosa.frames_to_time`

**Comment by bmcfee** [comment]
You may also want to refer to the blog post on stream processing, which gives a thorough break down of the different time scales that arise in this kind of thing: https://librosa.org/blog/2019/07/29/stream-processing/#Samples,-frames,-and-blocks

**Comment by MinaAku** [comment]
> 
Thanks a lot! It works and totally help me.
