### ISSUE TITLE
MFCC Preemphasis 

### ISSUE THREAD

**Issue by AndreH1009** [librosa/librosa#1597]
On reading the documentation it is not clear whether librosa.feature.mfcc uses a preemphasis filter and what the default value is. In librosa.effects.preemphasis it is 0.97 but I don't see whether this flows into librosa.feature.mfcc and how it can be changed in the function call. Since most mfcc algorithms have this feature I assume I overlooked it in librosa. Any advice is appreciated.

**Comment by bmcfee** [comment]
The MFCC function does not directly implement pre-emphasis.  This is because mfcc supports both time-domain and spectrogram inputs, but pre-emphasis would only be applicable for time-domain inputs. If you want pre-emphasis, it should be applied in advance.

**Comment by AndreH1009** [comment]
Thanks for the reply. Since you mention that librosa implements mfcc to accept both time-domain and spectrogram inputs, I'm guessing that it also does not do any prior dc mean removal. Is that correct?

**Comment by bmcfee** [comment]
> I'm guessing that it also does not do any prior dc mean removal. Is that correct?

Not explicitly, though the [mel filterbank](https://librosa.org/doc/latest/generated/librosa.filters.mel.html) will put zero weight on the DC component of the STFT.  This will knock out DC in each frame individually, but does not account for very low-frequency modulations.
