### ISSUE TITLE
Sign of first MFCC

### ISSUE THREAD

**Issue by AndreH1009** [librosa/librosa#1598]
Hi, I am currently trying to reproduce the results of librosa MFCC with the C++ NatureDSP signal library implementation of Cadence/IntegrIT for Hifi 5. For identical audio input I am getting results that are roughly in the same order of magnitude, with the exception, that the first MFCC has a flipped sign in both outputs. For my audio file librosa delivers a negative first MFCC value and NatureDSP gives me a positive value. What could possibly account for that? And what is the physical meaning of the sign? The parameters in both cases are of course equally assigned. I appreciate any advice on this.

**Comment by bmcfee** [comment]
The 0th MFCC is the sum over all (mel) frequencies of the energy measured in decibels.  Decibel measurements are always relative to some comparison point, and can be positive or negative depending on whether they're louder or quieter than the reference point.  Probably librosa and naturedsp use different reference points for their decibel measurements.

There are also likely to be many other subtle differences between implementations.  As discussed elsewhere #1093 there isn't a single definition of what MFCCs do, but rather a space of design choices that all produce similar results.  If you want bit-for-bit identical outputs between implementations, it may be possible, but you'll need to spend some serious time working through the source code to see what exactly they're doing at each stage of processing (stft, mel projection, decibel scaling, DCT projection) and whether there is pre- or post-processing (eg pre-emphasis and liftering) included.

**Comment by AndreH1009** [comment]
Thanks, that answers my question.
