### ISSUE TITLE
Rainbowgram example

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#1604]
**Is your feature request related to a problem? Please describe.**

"Rainbowgrams" are a way to simultaneously visualize amplitude and (unwrapped) phase (differential); see [the NSynth paper](https://proceedings.mlr.press/v70/engel17a/engel17a.pdf) figure 2:

![image](https://user-images.githubusercontent.com/1190540/202023544-c424e300-4698-4ed2-ac6d-8ebea546399f.png)

**Describe the solution you'd like**

The following code snippet essentially implements the idea, but using an STFT instead:

```python
sr = 22050
y = librosa.chirp(fmin=32, fmax=32 * 2**5, sr=sr, duration=10, linear=True)
D = librosa.stft(y)
mag, phase = librosa.magphase(D)

plt.close('all')
fig, ax = plt.subplots()

img = librosa.display.specshow(np.diff(np.unwrap(np.angle(phase), axis=1), axis=1, prepend=0),
                         cmap='hsv', 
                         alpha=librosa.amplitude_to_db(mag, ref=np.max)/80 + 1,
                         ax=ax,
                         y_axis='log', 
                         x_axis='time')
ax.set_facecolor('#000')

cbar = fig.colorbar(img, ticks=[-np.pi, -np.pi/2, 0, np.pi/2, np.pi])
cbar.ax.set(yticklabels=['-π', '-π/2', 0, 'π/2', 'π']);
```

The resulting figure looks as follows:
![image](https://user-images.githubusercontent.com/1190540/202023957-9965ede0-da47-4f68-9f49-e388c3cbb064.png)

It's a bit of a hack, and pretty far from a generally useful API.  However, I think we could include something like this as an example in the gallery.

A couple of variations are interesting as well.  The above uses HSV colormap for phase fading to a black background.  The twilight colormap can also work here, with the caveat that it uses black to code the extremes of the map (ie 0).  We can sidestep this by using a neutral axis facecolor:

```python
img = librosa.display.specshow(np.diff(np.unwrap(np.angle(phase), axis=1), axis=1, prepend=0),
                         cmap='twilight', 
                         alpha=librosa.amplitude_to_db(mag, ref=np.max)/80 + 1,
                         ax=ax,
                         y_axis='log', 
                         x_axis='time')
ax.set_facecolor('#888')
```
![image](https://user-images.githubusercontent.com/1190540/202024549-11ef9af9-2a73-4972-9b3c-01de2ccb93d2.png)

**Additional context**

If we implement this, it might be nice to finally throw in a helper utility for unwrapped phase differentials.

**Comment by wendywang3315** [comment]
Hello, is this issue still open? If so, I can try to work on it!

**Comment by bmcfee** [comment]
Sure, please do!  To be clear, my initial post does have a fully working example, but the work left to be done is to flesh it out into an example notebook to add to the [gallery](https://librosa.org/doc/main/advanced.html).
