### ISSUE TITLE
Cochleagram

### ISSUE THREAD

**Issue by Laope94** [librosa/librosa#1605]
Greetings,

is there any way how generate cochleagram with librosa and plot it (similary to e.g. spectrogram)? 

I've found no dedicated function for this in documentation, but maybe it can be composed somehow?

**Comment by lostanlen** [comment]
Hello @Laope94 

There is no cochleagram in librosa at the moment. We have melspectrogram's and VQT's, which are some of the most commonly used time--frequency representations in speech and music processing. Cochleagrams are more targeted towards the hearing sciences and auditory neurophysiology. It's not clear to me if it's part of librosa's scope to address these use cases.

For now, let me redirect you to some well-established implementations of cochleagram in Python:

* PyCochleagram by Ray Gonzalez. Ported from Josh McDermott's MATLAB implementation
https://github.com/mcdermottLab/pycochleagram

* strf-like-model by Étienne Thoret. Ported from NSL MATLAB Toolbox
https://github.com/EtienneTho/strf-like-model/blob/main/features.py
(see `waveform2auditoryspectrogram`)

* pyNSL by Mikolaj Kegler. Ported from NSL MATLAB Toolbox
https://github.com/MKegler/pyNSL/blob/main/pyNSL/pyNSL.py
(see `wav2aud`)

I hope this helps!

**Comment by Laope94** [comment]
Thank you for answer. I've used librosa few years ago for preprocessing soundfiles and computing spectrograms which I've been feeding into neural network. Now I am playing around something similar, but I intent to use cochleagrams. PyCochleagram seems to fit my usecase.

**Comment by bmcfee** [comment]
> It's not clear to me if it's part of librosa's scope to address these use cases.

I wouldn't be opposed to adding cochleagram functionality, but it would be best if someone more familiar with prior implementations took the lead on it.
