### ISSUE TITLE
Improve documentation for the resample function 

### ISSUE THREAD

**Issue by jpaasen** [librosa/librosa#1613]
## Environment
0.10.0.dev0
https://librosa.org/doc/main/generated/librosa.resample.html

## Describe the bug
There is an inconsistency among the `res_type` options for the `resample` function. While some are safe to use without an anti-aliasing filter, others are not.

The ones that are not safe include:

- `soxr_qq`
- `polyphase`
- `linear`
- `zero_order_hold`

## To Reproduce
Run the following notebook.
https://colab.research.google.com/drive/1VNS8O494CYocHrilUc7lZ_hKltNqb_PG?usp=sharing

## Suggested fix
I suggest improving the documentation with a more explicit mention of the options that require anti-aliasing filtering. Not just stating that the quality is low. I will create a PR for this.

Sidenote: The documentation text talks about the `kaiser_best` being the default option, while the code states that `soxr_hq` is the default. This should probably be fixed in the same go.

**Comment by jpaasen** [comment]
> By default, this uses a high-quality (but relatively slow) method ('kaiser_best')

Does anyone know if this is also true for the new default (`soxr_hq`)?

**Comment by bmcfee** [comment]
> There is an inconsistency among the `res_type` options for the `resample` function. While some are safe to use without an anti-aliasing filter, others are not.

I don't think this is necessarily an "inconsistency" as the documentation never makes any specific claims about the behavior of the underlying methods.  But sure, it'd be great to expand the documentation to clarify this point.




> Sidenote: The documentation text talks about the `kaiser_best` being the default option, while the code states that `soxr_hq` is the default. This should probably be fixed in the same go.

Good catch, sorry I missed that in PR #1566 .



> Does anyone know if this is also true for the new default (`soxr_hq`)?

Do you mean to ask if soxr_hq is anti-aliasing?  The answer is yes.  (We should also drop the "relatively slow" language, since soxr_hq is quite speedy.)

**Comment by bmcfee** [comment]
Gotcha, thanks for clarifying.  Do you want to open a PR for this?

**Comment by jpaasen** [comment]
Yes. I'm on it
