### ISSUE TITLE
Plots using waveshow are not resampling when you zoom in Jupyter Lab

### ISSUE THREAD

**Issue by roballsopp** [librosa/librosa#1619]
**Describe the bug**
Calling `waveshow` should render a plot in jupyter lab that, when zoomed, resamples to show sample details as shown [here](https://github.com/librosa/librosa/issues/1207#issuecomment-841178956), but it doesn't do this. See video:

https://user-images.githubusercontent.com/6366105/206818281-959c3325-c6fe-4246-a3bf-9797f7928d0e.mp4

**To Reproduce**
```python
%matplotlib widget
import librosa
import librosa.display
from matplotlib import pyplot as plt

y, sr = librosa.load('data/train/drums-perf1-44100-mono-avatar-kit2-all.wav', sr=None)

fig, axs = plt.subplots(1, 1, figsize=(10, 3))
librosa.display.waveshow(y, sr=sr, ax=axs, label='audio')
axs.legend(loc='lower right')
fig.tight_layout()
```
...and try to zoom down to see the samples. The resulting waveform is just giant blocks. The audio in the video above is about 31 minutes long at 44.1k, so its quite large, but I tried this with a 22 second clip at 44.1k with the same effect.

**Software versions**
```shell
Windows-10-10.0.22621-SP0
Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]
NumPy 1.23.5
SciPy 1.8.0
librosa 0.9.2
INSTALLED VERSIONS
------------------
python: 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]

librosa: 0.9.2

audioread: 3.0.0
numpy: 1.23.5
scipy: 1.8.0
sklearn: 1.1.2
joblib: 1.2.0
decorator: 5.1.1
soundfile: 0.11.0
resampy: 0.4.2
numba: 0.56.4
pooch: v1.6.0
packaging: 21.3

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
sphinx_multiversion: None
sphinx_gallery: None
mir_eval: None
ipython: None
sphinxcontrib-svg2pdfconverter: None
pytest: None
pytest-mpl: None
pytest-cov: None
matplotlib: 3.6.2
samplerate: None
soxr: None
contextlib2: None
presets: None
```

Here also is a `pip freeze` of my environment, in case some of the Jupyter lib versions are relevant:
```shell
absl-py==1.3.0
ansi2html==1.8.0
anyio==3.6.2
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.2.1
astunparse==1.6.3
attrs==22.1.0
audioread==3.0.0
Babel==2.11.0
backcall==0.2.0
beautifulsoup4==4.11.1
bleach==5.0.1
cachetools==5.2.0
certifi==2022.9.24
cffi==1.15.1
chardet==4.0.0
click==8.1.3
cloudpickle==2.2.0
colorama==0.4.6
contourpy==1.0.6
cvxopt==1.3.0
cycler==0.11.0
dash==2.7.0
dash-core-components==2.0.0
dash-html-components==2.0.0
dash-table==5.0.0
debugpy==1.6.4
decorator==5.1.1
defusedxml==0.7.1
dm-tree==0.1.7
entrypoints==0.4
executing==1.2.0
fastjsonschema==2.16.2
filelock==3.8.1
Flask==2.1.3
Flask-Cors==3.0.10
flatbuffers==22.11.23
fonttools==4.38.0
gast==0.4.0
google-auth==2.15.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.51.1
gurobipy==9.5.1
h5py==3.7.0
huggingface-hub==0.10.0
idna==2.10
imageio==2.22.4
importlib-metadata==5.1.0
ipykernel==6.17.1
ipympl==0.9.2
ipython==8.6.0
ipython-genutils==0.2.0
ipywidgets==8.0.2
itsdangerous==2.1.2
jedi==0.18.2
Jinja2==3.1.2
joblib==1.2.0
json5==0.9.10
jsonschema==4.17.3
jupyter-dash==0.4.2
jupyter-server==1.23.3
jupyter_client==7.4.8
jupyter_core==5.1.0
jupyterlab==3.5.0
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.3
jupyterlab_server==2.16.3
keras==2.10.0
Keras-Preprocessing==1.1.2
kiwisolver==1.4.4
libclang==14.0.6
librosa==0.9.2
llvmlite==0.39.1
Markdown==3.4.1
MarkupSafe==2.1.1
matplotlib==3.6.2
matplotlib-inline==0.1.6
mido==1.2.9
mistune==2.0.4
nbclassic==0.4.8
nbclient==0.7.2
nbconvert==7.2.6
nbformat==5.7.0
nest-asyncio==1.5.6
networkx==2.8.8
notebook==6.5.2
notebook_shim==0.2.2
numba==0.56.4
numpy==1.23.5
oauthlib==3.2.2
opencv-python==4.5.1.48
opt-einsum==3.3.0
orjson==3.8.3
packaging==21.3
pandas==1.5.2
pandocfilters==1.5.0
parso==0.8.3
pickleshare==0.7.5
Pillow==9.0.1
platformdirs==2.5.4
plotly==5.11.0
plotly-resampler==0.8.3
pooch==1.6.0
prometheus-client==0.15.0
prompt-toolkit==3.0.33
protobuf==3.19.6
psutil==5.9.4
PuLP==2.6.0
pure-eval==0.2.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
Pygments==2.13.0
pyparsing==3.0.9
pyrsistent==0.19.2
python-dateutil==2.8.2
pytz==2022.6
PyWavelets==1.4.1
pywin32==305
pywinpty==2.0.9
PyYAML==6.0
pyzmq==24.0.1
requests==2.25.1
requests-oauthlib==1.3.1
resampy==0.4.2
retrying==1.3.4
rsa==4.9
scikit-image==0.19.1
scikit-learn==1.1.2
scipy==1.8.0
Send2Trash==1.8.0
six==1.16.0
sniffio==1.3.0
soundfile==0.11.0
soupsieve==2.3.2.post1
stack-data==0.6.2
tenacity==8.1.0
tensorboard==2.10.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.10.1
tensorflow-estimator==2.10.0
tensorflow-hub==0.12.0
tensorflow-io-gcs-filesystem==0.28.0
tensorflow-probability==0.18.0
tensorflow-text==2.10.0
termcolor==2.1.1
terminado==0.17.1
threadpoolctl==3.1.0
tifffile==2022.10.10
tinycss2==1.2.1
tomli==2.0.1
tornado==6.2
tqdm==4.64.1
trace-updater==0.0.9
traitlets==5.6.0
typing_extensions==4.4.0
urllib3==1.26.13
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.4.2
Werkzeug==2.1.2
widgetsnbextension==4.0.3
wrapt==1.14.1
zipp==3.11.0
```

**Comment by roballsopp** [comment]
If I hold a reference to the `AdaptiveWaveplot` _and_ shorten the sequence significantly, it seems to mostly work:

```python
%matplotlib widget
import librosa
import librosa.display
from matplotlib import pyplot as plt

y, sr = librosa.load('data/train/drums-perf1-44100-mono-avatar-kit2-all.wav', sr=None)

fig, axs = plt.subplots(1, 1, figsize=(10, 3))
o1 = librosa.display.waveshow(y[:1000000], sr=sr, ax=axs, label='audio')
axs.legend(loc='lower right')
fig.tight_layout()
```

https://user-images.githubusercontent.com/6366105/206823248-a65f5756-f084-4514-84e0-299a4a425613.mp4

But holding the reference doesn't seem to make it work for the full length file:

```python
%matplotlib widget
import librosa
import librosa.display
from matplotlib import pyplot as plt

y, sr = librosa.load('data/train/drums-perf1-44100-mono-avatar-kit2-all.wav', sr=None)

fig, axs = plt.subplots(1, 1, figsize=(10, 3))
o1 = librosa.display.waveshow(y, sr=sr, ax=axs, label='audio')
axs.legend(loc='lower right')
fig.tight_layout()
```


https://user-images.githubusercontent.com/6366105/206823311-ba365cbc-dcf6-4483-a9f4-bd078d462258.mp4

**Comment by roballsopp** [comment]
Ok, I think I had a misunderstanding of how this worked. I assumed the low-res envelop would be redrawn as you zoom in, but it is drawn once at a single resolution that depends on the length of the audio when waveshow is called. A little awkward, because a long signal looks blockier than a short one at the same time resolution, but it can at least be partly controlled by increasing `max_points`. I also didn't realize just how zoomed in I'd need to be for the sample drawing to kick in. All this said however, I am still seeing that a reference to `AdaptiveWaveplot` must be kept for the sample drawing to work. The example code [here](https://librosa.org/doc/latest/generated/librosa.display.waveshow.html) doesn't work as is because it doesn't hold these references. Adding them like so does work, however:
```python
import matplotlib.pyplot as plt
y, sr = librosa.load(librosa.ex('choice'), duration=10)
fig, ax = plt.subplots(nrows=3, sharex=True)
p1 = librosa.display.waveshow(y, sr=sr, ax=ax[0])
ax[0].set(title='Envelope view, mono')
ax[0].label_outer()

y, sr = librosa.load(librosa.ex('choice', hq=True), mono=False, duration=10)
p2 = librosa.display.waveshow(y, sr=sr, ax=ax[1])
ax[1].set(title='Envelope view, stereo')
ax[1].label_outer()

y, sr = librosa.load(librosa.ex('choice'), duration=10)
y_harm, y_perc = librosa.effects.hpss(y)
p3 = librosa.display.waveshow(y_harm, sr=sr, alpha=0.5, ax=ax[2], label='Harmonic')
p4 = librosa.display.waveshow(y_perc, sr=sr, color='r', alpha=0.5, ax=ax[2], label='Percussive')
ax[2].set(title='Multiple waveforms')
ax[2].legend()
```

**Comment by bmcfee** [comment]
Hi @roballsopp - thanks for the thorough report here!

I think you've landed on the correct explanation here - the envelope is generated once at a fixed rate.  The idea of doing a multi-resolution pyramid has come up before #1540 but I have not had time to really dig into it yet.



> All this said however, I am still seeing that a reference to `AdaptiveWaveplot` must be kept for the sample drawing to work. The example code [in the docs](https://librosa.org/doc/latest/generated/librosa.display.waveshow.html) doesn't work as is because it doesn't hold these references. Adding them like so does work, however

It's a little more subtle than that.  When the AdaptiveWaveplot object is constructed, it registers a callback with the axes to detect changes to the viewport.  This callback implicitly holds the reference to the object, so the user should not need to additionally store that.  However, the axes object can only handle one callback at a time (per trigger), so we can't do multiple adaptive waveplots in the same figure/axes at this time.  I believe there's an oustanding mpl issue for this (can't find it at the moment) - so there's not much we can do until that gets resolved.

**Comment by roballsopp** [comment]
Gotcha, thanks for the quick response! Guess this can be closed then. Hopefully it helps anyone else running into this in the mean time.
