### ISSUE TITLE
Clean up type annotations in documentation site

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#1629]
**Is your feature request related to a problem? Please describe.**
Since merging #1564 , the function headers on the doc site have gotten a bit unwieldy.

For example, VQT is basically unreadable:

![image](https://user-images.githubusercontent.com/1190540/207905293-ff8380c6-596d-4c7c-96ca-619a4e1bc4f5.png)

**Describe the solution you'd like**
We should find a way to clean this up, ideally from the sphinx end of things.

[sphinx-autodoc-typehints](https://pypi.org/project/sphinx-autodoc-typehints/) might do the trick, but I'm not yet sure.

**Comment by matangover** [comment]
https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_typehints

Setting `autodoc_typehints` to `none` might work

**Comment by bmcfee** [comment]
> Setting `autodoc_typehints` to `none` might work

Nice - the autodoc-typehints package seems to be pretty incompatible with numpydoc :\

It'd be great if there's a way to somehow retain the type annotations in a simplified form, but barring that, I think the docstrings do a good enough job of describing what's going on for the doc site purposes.

**Comment by bmcfee** [comment]
> Setting `autodoc_typehints` to `none` might work

Confirmed.  I'll PR later today. Thanks!
