### ISSUE TITLE
[RFC] Not doing type annotations after all (for now)

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#1633]
(Yes, this request for comments will probably make many people unhappy.  Apologies in advance.)

We recently merged PR #1587 to add type annotations throughout the package.  It seemed great, and @matangover put a ton of work into it for which I'm very appreciative.  However, I think we may have merged it too hastily, leaving things in a rather precarious spot.  So I want to ask folks for some feedback on how to proceed at this point.

PR #1587 added a CI action to run mypy on the test suite (with suitable extra annotations), but not the package itself.  I think we were operating under the assumption that this would be good enough to get started, and a full package check could be added later on.

Not happy to leave well enough alone, I started trying to get mypy to run cleanly on the full package this week, and long story short, I'm highly skeptical that it's going to work any time soon.

For the most part, the librosa code base does fairly simple things on numpy arrays.  This ought to be more or less supported by `numpy.typing`.  However, many of the things we do rely on other packages that have not made the jump into type annotation land, and this causes loads of headaches.  A few prime examples:

- Anything involving numba compilation, either via jit, vectorization, or stencils, is at the moment doomed.  Recommended solution is to ignore type checks https://github.com/numba/numba/issues/7424#issuecomment-933090198 - but this doesn't really help when we get one layer up to functions which call upon these core jit-compiled functions.
- mypy is not too clever when it comes to inferring the state of optional parameters that get overridden by dynamic defaults.  This is a very common pattern when the parameter in question has a sensible default, but its type is mutable (eg a numpy ndarray) and should not be baked into the signature.  In this case, you often get code like:
```python
def foo(..., fmin: Optional[float]=None):
    if fmin is None:
        fmin = note_to_hz("C1")
    # go on our merry way
    ...
```
(use your imagination for the mutable type version of this.)  mypy will complain later on if `fmin` is used in a floaty kind of way, and the best workaround I've seen so far is to just sprinkle `assert fmin is not None` (or similar) into the code.  Aside from my general aesthetic distaste for putting asserts (rather than exceptions) in live code, this kind of thing makes the code more difficult to read, and has no practical benefit apart from making static analysis easier.
- Related to the above, we've had to borrow some rather grungy code for abstracting away scalar/array mixtures (see `_typing.py`) .  This kind of works, but it also gets real cranky when it encounters a `float` instead of `np.floating[Any]` or `_FloatLike_co`.  Aside from being a headache to keep straight, it's resulted in some basically unreadable function signatures.  We've hidden these in the documentation site, but it still seems like there should be a better solution here.
- Almost all of our upstream dependencies do not yet implement type annotations.  As a result, we've had to put ignore markers for each one (scipy, matplotlib, sklearn, soundfile, etc etc) to make any progress here.  This makes me question the validity of our type annotations in general, and generally hints that we've tried to move too quickly here.

---

All of the above issues leave the code in a state where I would not advocate for making a release.  The 0.10 release is already several months behind schedule, and I really do not see any clear path toward resolving these issues in the short term.

So, I'll put the question bluntly: should we roll back #1587 until the state of type annotations in scientific python land is better?  (N.B.: It's possible that this never happens.)  Or are the benefits of type annotations really so important that we should sacrifice readability and maintainability?  I really am not convinced one way or the other here, but I do think we should entertain the option of rolling back.

Tagging @matangover and @bluenote10 specifically on this, as you two have been the most vocal advocates for type annotations, and I'd like your input.

**Comment by matangover** [comment]
I'll answer bluntly too:) no, we shouldn't roll it back, in my opinion. The annotations of the public interface and the type checking of the internal code are two completely different things and serve different purposes. I on purpose set out only to annotate the public interface because that was the big benefit for me as a user of librosa. I don't think there's anything precarious about the current situation. However if you choose to roll back the changes I would respect that.

**Comment by matangover** [comment]
P.s. I'm boarding a flight now and won't be responding in the next two weeks:)

**Comment by bmcfee** [comment]
Bluntness and speed are both appreciated. :grin: 



> The annotations of the public interface and the type checking of the internal code are two completely different things and serve different purposes.

I understand this perspective, and see how it can apply to something like an API wrapper (eg soundfile).  Librosa is different IMO because it's a utility library: many of its functions are accessible to outside users, as well as used internally for more complex functions.  This ultimately blurs the distinction between external API and internal functionality when it comes to type checking, and I think the only sane way through is to check everything.



> I don't think there's anything precarious about the current situation.

The precarity is in publishing code with type annotations that don't validate.  It's equivalent IMO to publishing code without test coverage.  We previously didn't have this issue because we made no explicit claims about types (other than docstrings), but now we're in this twilight zone kind of territory where we make claims that cannot be verified.

**Comment by matangover** [comment]
But that's literally the state of all libraries that publish stubs. Including stdlib

**Comment by bmcfee** [comment]
> But that's literally the state of all libraries that publish stubs. Including stdlib

Really?  None of them validate? :eyes:

**Comment by matangover** [comment]
Ummm. Yep:) that's the whole typing ecosystem. That's how it is in typescript too. If all libraries had to be fully type checked then typing could never be adopted. So it's done gradually for pragmatic reasons.

**Comment by bmcfee** [comment]
Ok, so now I really don't know what to do. I don't want to publish broken code, but it sounds like unbreaking it is probably impossible (or at least a ton of work for marginal payoff).

**Comment by matangover** [comment]
I don't think the code's any more broken than it previously was... I also don't think anyone would come complaining the code is broken because (if) a type annotation is wrong. And we made our best efforts to verify the annotations

**Comment by matangover** [comment]
I think the annotations are helpful because they give a better editing experience (code completion) which is why I originally opened the issue

**Comment by bmcfee** [comment]
> I don't think the code's any more broken than it previously was...

Sure - there's a saying that untested code is broken code. However, there's also a distinction to be made between code with type annotations and without - when they're there, we should expect them to be correct (and tested).  When there's no such expectation, it's still "broken" but also it never claimed otherwise.



> I think the annotations are helpful because they give a better editing experience (code completion) which is why I originally opened the issue

Sure, that's a fair point.  But I'm finding it also makes for a much worse editing and maintaining experience, and that should not be discounted.

That said, I'll keep plugging away at trying to get this to work, for now at least.

**Comment by bluenote10** [comment]
I'd also just sprinkle a few `# type: ignore` locally (ideally line level, not file level) or fall back to `Any` where needed etc.

Introducing type annotations is indeed a gradual process, and often 100% perfection just isn't achievable. In my opinion the crucial point is to get them right at the bigger boundaries and the outer interfaces. Of course it would be great if all internal functions could be typed precisely. But even if like 20% of internal functions cannot be typed perfectly, there is still a huge value in typing the remaining 80%:

- Benefit on user side: Serves as documentation, enables users to perform both ad-hoc and CI-based type checking, speeding up development and version update procedures.
- Benefit on librosa side: Even if the CI-based type check covers only ~80% internal functions it can still help to check consistency, find bugs, help with automated refactoring etc.

> Really? None of them validate?

I wouldn't put it that way. There are definitely (simple) projects that can achieve 100% type consistency. But I think it very common in the real world to have projects that are perhaps 80% - 90% typed.

**Comment by matangover** [comment]
> I wouldn't put it that way. There are definitely (simple) projects that can achieve 100% type consistency

I was saying specifically about the libraries that publish stubs (there are many... maybe more than those published with inline types). For these, mypy can't even check their code against their stubs (it's not a supported mypy feature). This is e.g. the situation with stdlib itself. And of course also with all packages that have separate *-stubs packages.

As a contrary example, take pytorch which does have inline types and runs mypy in CI and if you check their mypy.ini you can see a bunch of excludes there

**Comment by bmcfee** [comment]
> I was saying specifically about the libraries that publish stubs (there are many... maybe more than those published with inline types).

Right - I was thinking of these as categorically different.  -stubs packages are addons, and as such, the main distribution would not be perceived as making promises about types that don't hold up.  If we were implementing type annotations in this way, I'd be a lot more lax about things.  But that ship has more or less sailed, and I'd like to do this right.

**Comment by matangover** [comment]
To clarify, I was talking mainly about libraries that publish stubs as part of the main distribution. But anyway, these comparisons are not important... We can do with librosa whatever we want...

**Comment by bmcfee** [comment]
Closing this out - #1632 brings this up to spec (more or less), and huge thanks to @bluenote10 for helping sort out the more annoying details.
