### ISSUE TITLE
Librosa stream file reading

### ISSUE THREAD

**Issue by pearl-yu** [librosa/librosa#1641]
Just using librosa and getting the first ten seconds works fine.

```
audio, rate = librosa.load('filename.mkv', duration=10, sr = 16000)
```

But when using stream, it returns the error File contains data in an unknown format. (I'm feeding the chunks into a tokenizer.)

```
stream = librosa.stream(
        'filename.mkv',
        block_length=10,
        frame_length=16000,
        hop_length=16000
    )

for speech in stream:
  input_values = tokenizer(speech, return_tensors="pt").input_values
```

**Comment by bmcfee** [comment]
This is documented behavior.  The load function can use either audioread (backed by gstreamer, ffmpeg, etc) or libsndfile to decode.  The stream function can only use libsndfile.  Video decoding (ie for mkv format) is not supported by libsndfile.
