### ISSUE TITLE
Further explanation about license using 

### ISSUE THREAD

**Issue by Ashley123456789** [librosa/librosa#1642]
**Is your feature request related to a problem? Please describe.**

When I **import** librosa as a third-party dependency, 
- Should I comply with the LICENSE.md (i.e., ISC License)? Is the **import** action considered as **to use, copy, and/or distribute this software** in the ISC License text?
- Do I need to pay attention to **license compatibility**, i.e., can I claim a  **less strict license** than ISC License for my projects?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bmcfee** [comment]
This is a question about licensing in general, and not with librosa specifically.  I suggest to read through the explanation of licensing on https://choosealicense.com/licenses/ to understand the terms of use.

But to answer your questions: 1) yes, importing counts as use. 2) no, ISC is not a viral license.
