### ISSUE TITLE
Can't install Librosa for python 3.11.1!

### ISSUE THREAD

**Issue by Moin-Ud-Din** [librosa/librosa#1644]
I have tried all the commands for installing the librosa but it isn't working I even looked at this but to no avail [https://stackoverflow.com/questions/67331302/not-able-to-install-librosa](url)
This is the error I'm getting which means that it isn't supported for python 3.11.1 version
![image](https://user-images.githubusercontent.com/61883188/211320158-fe74c661-14c2-47ce-9086-8be67fb390e7.png)

**Comment by lostanlen** [comment]
The message is clear: your version of numba is is conflict with your version of Python.

**Comment by bmcfee** [comment]
The error message here is pretty clear: numba (a dependency for librosa) does not yet support python 3.11.  See https://github.com/numba/numba/issues/8304

**Comment by egeres** [comment]
Numba merged it's python 3.11 branch just 3 days ago, so their next release should enable librosa!
