### ISSUE TITLE
 Inconstant behavior of pyin in different version of librosa

### ISSUE THREAD

**Issue by BingliangLi** [librosa/librosa#1667]
**Describe the bug**
`f0` calaculated by version `0.8.1` is different from `0.9.2` and `0.10.0rc0` when parameter `hop_length` is used.

**To Reproduce**
```
import librosa
import librosa.display
y, sr = librosa.load(librosa.ex('trumpet'))
f0, voiced_flag, voiced_probs = librosa.pyin(y,
                                             fmin=librosa.note_to_hz('C2'),
                                             fmax=librosa.note_to_hz('C7'),
                                             hop_length=160)
times = librosa.times_like(f0)

import matplotlib.pyplot as plt
D = librosa.amplitude_to_db(np.abs(librosa.stft(y)), ref=np.max)
fig, ax = plt.subplots()
img = librosa.display.specshow(D, x_axis='time', y_axis='log', ax=ax)
ax.set(title='pYIN fundamental frequency estimation')
fig.colorbar(img, ax=ax, format="%+2.f dB")
ax.plot(times, f0, label='f0', color='cyan', linewidth=3)
ax.legend(loc='upper right')
```

**Expected behavior**
I'm not sure as I'm not a professional in this field, but for version 0.8.1, the length of `f0` is same as the time of the audio, but the other two version are not(`f0` is longer than audio). Which is correct? 

**Screenshots**
`v0.8.1`:
![image](https://user-images.githubusercontent.com/49446651/218255658-21d88588-cb00-498d-87c2-2cf5580cfab5.png)

`0.9.2` and `0.10.0rc0`:
![image](https://user-images.githubusercontent.com/49446651/218255633-520e94d5-61b5-43db-a21f-6c102e4aa6da.png)

**Software versions***
Only `librosa` version is changed during the above test.
```
Linux-5.15.0-43-generic-x86_64-with-glibc2.31
Python 3.9.15 (main, Nov 24 2022, 14:31:59) 
[GCC 11.2.0]
NumPy 1.23.5
SciPy 1.10.0
librosa 0.8.1
INSTALLED VERSIONS
------------------
python: 3.9.15 (main, Nov 24 2022, 14:31:59) 
[GCC 11.2.0]

librosa: 0.8.1

audioread: 3.0.0
numpy: 1.23.5
scipy: 1.10.0
sklearn: 1.2.0
joblib: 1.2.0
decorator: 5.1.1
soundfile: 0.11.0
resampy: 0.4.2
numba: 0.56.4

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
sphinxcontrib.versioning: None
sphinx-gallery: None
pytest: None
pytest-mpl: None
pytest-cov: None
matplotlib: 3.6.2
presets: None
```
**Additional context**

**Comment by bmcfee** [comment]
I think pyin is behaving correctly in both cases. The problem is that you're not specifying the hop length in times_like to match that of pyin.

**Comment by BingliangLi** [comment]
I dont's know there is hop_length for `time_like` as well, after set to the same hop_length the two version produced the same result. Thx!
`v0.8.1`
![image](https://user-images.githubusercontent.com/49446651/218260039-94a21fdb-7069-48bc-bba4-3fb67cf15a0c.png)

`0.10.0rc0`
![image](https://user-images.githubusercontent.com/49446651/218260080-086de90d-2bfa-4858-a33a-93a6c31719fa.png)
