### ISSUE TITLE
librosa resample issue 

### ISSUE THREAD

**Issue by Abisheksk16** [librosa/librosa#1696]
y,sr = librosa.load('goosebumps.mp3')
y = librosa.resample(y,sr, 44100)

Exception has occurred: TypeError
resample() takes 1 positional argument but 2 were given
  File "G:\python\lyrics.py", line 9, in <module>
    y = librosa.resample(sr, 44100)
TypeError: resample() takes 1 positional argument but 2 were given

help me with this isssue

**Comment by lostanlen** [comment]
Hello @Abisheksk16 , i believe it should be `y = librosa.resample(y, sr=44100)`

This kind of usage question is best suited for the librosa discussion group (https://groups.google.com/g/librosa) or for a Q&A website of your choice.
