### ISSUE TITLE
STFT inconsistencies, `win_length < n_fft`, window center aligned, or `win_length % 2 != 0`

### ISSUE THREAD

**Issue by albertz** [librosa/librosa#1701]
Related:
https://github.com/librosa/librosa/issues/596
https://github.com/librosa/librosa/issues/695
https://github.com/pytorch/pytorch/issues/100177

**Describe the bug**

While comparing `tf.signal.stft` to `torch.stft`, and then also to `librosa.stft` and `scipy.signal.stft`, I noticed that they all are somewhat inconsistent to each other.

**To Reproduce**

Call `librosa.stft` with some `win_length < n_fft` and `center=False`.

In my notation, `n_fft = fft_length`, `win_length = frame_length` and `hop_length = frame_step`.

I compare:
```python
y_lr_np = librosa.stft(
    x, n_fft=fft_length, hop_length=frame_step, win_length=frame_length,
    center=False
)
y_lr_np = y_lr_np.transpose(0, 2, 1)
```

That will use `util.pad_center` for the window. That has the effect that the phases at the beginning are ignored (all the coefficients of exp(...)).

In contrast, both TF and SciPy pad zeros to the right of the window. So the first phases are used.

The librosa implementation is the same as this:
```python
y_pt_like_np = numpy.zeros(
    (n_batch, ceildiv(n_time - fft_length + 1, frame_step), fft_length // 2 + 1), dtype="complex64")
window_np = numpy.hanning(frame_length + 1)[:frame_length]
for b in range(y_pt_like_np.shape[0]):
    for t in range(y_pt_like_np.shape[1]):
        for f in range(y_pt_like_np.shape[2]):
            for k in range(frame_length):
                y_pt_like_np[b, t, f] += (
                    window_np[k]
                    * x[b, t * frame_step + k + (fft_length - frame_length) // 2]
                    * numpy.exp(-2j * numpy.pi * f * (k + (fft_length - frame_length) // 2) / fft_length))
```

The TF implementation on the other hand is the same as this:
```python
y_tf_like_np = numpy.zeros(
    (n_batch, ceildiv(n_time - frame_length + 1, frame_step), fft_length // 2 + 1), dtype="complex64")
window_np = numpy.hanning(frame_length + 1 - frame_length % 2)[:frame_length]
for b in range(y_tf_like_np.shape[0]):
    for t in range(y_tf_like_np.shape[1]):
        for f in range(y_tf_like_np.shape[2]):
            for k in range(frame_length):
                y_tf_like_np[b, t, f] += (
                    window_np[k]
                    * x[b, t * frame_step + k]
                    * numpy.exp(-2j * numpy.pi * f * k / fft_length))
```

`ceildiv`:
```python
def ceildiv(a, b):
    return -(-a // b)
```

The full code with more comparisons can be found [here](https://github.com/albertz/playground/blob/master/tf_pt_stft.py).

There are some differences:

The output sequence length: `ceildiv(n_time - frame_length + 1, frame_step)` (TF) vs `ceildiv(n_time - fft_length + 1, frame_step)` (librosa).

But also, the coefficients (exp(...)) are different. You have the `k` with `(fft_length - frame_length) // 2` offset in librosa. Is that correct?

In case frame_length is uneven, the logic of the windowing is slightly different. TF uses the next lower even number.

Also, you ignore the first `(fft_length - frame_length) // 2` frames in librosa. Is that correct?

**Expected behavior**

I don't know. I don't really know whether one variant is more correct than the other. But this is one reason I opened this issue, to clarify this.

But then, in any case, I think the documentation could be improved, to better describe what's happening. Actually the naive pure Numpy implementation above would help a lot to exactly describe what's happening.

**Comment by bmcfee** [comment]
Thanks for the detailed summary.  It's indeed a subtle issue, and I think I would agree with the assessment that there isn't a single "correct" behavior to expect here.

The right-padding approach (tf, scipy) is equivalent to calling `(r)fft` with `n=frame_length`, eg:
```python
In [8]: x = np.random.randn(16)

In [9]: X = np.fft.rfft(x, n=32)

In [10]: Y = np.fft.rfft(np.pad(x, (0, 16)))

In [11]: np.allclose(X, Y)
Out[11]: True
```
This makes sense if you're considering left-aligned frames, so that the first STFT frame corresponds to the first `win_length` samples.

Librosa does not use left-aligned frames by default, and as you note, we left-pad with a half-frame of silence.  This way, we can say that each frame is *centered* at a particular sample index `k * hop_length`.  If we were to use right-padding of the frames, then this really wouldn't be true: the center of the analysis window would end up somewhere before sample `k*hop_length`.

Since centered windows are the default in librosa, we opted for centered windowing as well.  (This I think was also originally for compatibility with @dpwe's prior matlab implementation.)  In retrospect, I could see an argument for right-padding windows when using left-aligned windows (ie `center=False`).  At this point it would introduce some backwards compatibility issues that would be difficult to explain to users, so I'm inclined to leave it as is.

If a user *does* want left-aligned windows, it's easy enough to provide an explicitly constructed window by something like the following:
```python
>>> window = librosa.filters.get_window('hann', win_length)
>>> window = np.pad(window, (0, frame_length - win_length))
>>> D = librosa.stft(y, window=window)
```



> here are some differences:
> 
> The output sequence length: `ceildiv(n_time - frame_length + 1, frame_step)` (TF) vs `ceildiv(n_time - fft_length + 1, frame_step)` (librosa).
> 

I'm having a little difficulty parsing this because of the variable name differences across packages.  We use `n_fft` to denote the frame length (equiv. # of analysis frequencies) and `win_length` to denote the length of the window inside the frame.   I'll assume here that `frame_length` means `win_length` here (we use `frame_length` elsewhere in librosa for something slightly different), but please correct if i'm misinterpreting.


> But also, the coefficients (exp(...)) are different. You have the `k` with `(fft_length - frame_length) // 2` offset in librosa. Is that correct?
> 

Yes, I think that's fair to say.

> In case frame_length is uneven, the logic of the windowing is slightly different. TF uses the next lower even number.
> 
> Also, you ignore the first `(fft_length - frame_length) // 2` frames in librosa. Is that correct?

(I think you mean "samples" not "frames" here.)  I wouldn't say they're ignored.  The sample values will be squashed to zero by the padded window, but their positioning information will still influence the phases of the resulting DFT components.

**Comment by bmcfee** [comment]
Also related #695

**Comment by albertz** [comment]
Sorry on the difference in notation. In my notation, `n_fft = fft_length`, `win_length = frame_length` and `hop_length = frame_step`.

Here using the librosa notation, and using `T` instead of `n_time` now:

The output sequence length: `ceildiv(T - win_length + 1, hop_length)` (TF) vs `ceildiv(T - n_fft + 1, hop_length)` (librosa).

**Comment by bmcfee** [comment]
> The output sequence length: `ceildiv(T - win_length + 1, hop_length)` (TF) vs `ceildiv(T - n_fft + 1, hop_length)` (librosa).

Something like this, yes.  The details will change when padding is involved, and I think the `+1` should be outside the div, not inside.

The key distinction here is between win_length and n_fft.

In TF, I gather they're actually framing by `win_length` and then using frequency over-sampling to get the effect of right-padding (as noted above).

In librosa, we frame by `n_fft` and then pad the window to fit.

The framing operation is what dictates the length (number of frames) in the resulting STFT.

If we have a signal with `T` samples, then `librosa.util.frame()` will generate an output of size `1 + ((T - frame_length)//hop_length)`; stft calls frame with `frame_length=n_fft` (after padding, if center=True).  I expect that TF is doing the same kind of thing, just using `frame_length=win_length` instead.

And to summarize, the main reason to use the larger frame and a padded window is that it would support centering the window within the frame.  Doing it as TF does forces you to left-align the window to the frame.

**Comment by albertz** [comment]
Well, in TF/SciPy, you can always just set `win_length = n_fft` and then have any custom window, padded in whatever way. So you still have the full flexibility. Or do I misunderstand anything there?

The same for librosa, or also PyTorch. By setting `win_length = n_fft`, you can have any custom window. And to get the same output seq length as TF/SciPy, you need to add some extra zero padding to the input.

**Comment by bmcfee** [comment]
> Well, in TF/SciPy, you can always just set `win_length = n_fft` and then have any custom window, padded in whatever way. So you still have the full flexibility. Or do I misunderstand anything there?

No, that's exactly right.  The main difference is in how the underlying frame array is constructed.  There is also a slight difference in the parameterization; if you set `win_length=n_fft` then there isn't really a separate variable to control the window length anymore.  This is fine in scipy, where you can pass in an explicitly constructed window array.    TF's stft appears to only accept a callable (ie function) window constructor, so you'd need to be a little clever if you want a smaller window within a larger frame.

**Comment by bmcfee** [comment]
Picking this thread up again after a month - is there anything for us to do here? Or should we close this thread?

**Comment by albertz** [comment]
> then, in any case, I think the documentation could be improved, to better describe what's happening

So, I think this is still to be done, right? Just improving the documentation.

I'm not sure how detailed you want to have it. I personally really like to have such example code of a naive implementation, because that makes it perfectly unambiguously clear to me what's actually happening.

Maybe also the same in mathematical notation (similar as PyTorch has it). Even though it is just a duplicate of the naive Python code. But this makes it maybe easier for people who like to read math formulas.

I'm not sure if you want to have the comparison to other frameworks in the documentation. I personally find it very useful. Maybe a reference to this issue is also enough as an alternative.

**Comment by bmcfee** [comment]
> So, I think this is still to be done, right? Just improving the documentation.
> 
> I'm not sure how detailed you want to have it. I personally really like to have such example code of a naive implementation, because that makes it perfectly unambiguously clear to me what's actually happening.

Ok.  I think the minimal additional info that would be helpful here is in the `win_length` section:

https://github.com/librosa/librosa/blob/f21bda6b9fd7d9f1276749862247a6daf59e792d/librosa/core/spectrum.py#L99-L110

to be amended as

```
    win_length : int <= n_fft [scalar]
        Each frame of audio is windowed by ``window`` of length ``win_length``
        and then left- and right-padded with zeros to match ``n_fft``.
        Windows are centered within the frame.

        ...
```

I'm happy to tag that for the 0.10.1 release.



> Maybe also the same in mathematical notation (similar as PyTorch has it). Even though it is just a duplicate of the naive Python code. But this makes it maybe easier for people who like to read math formulas.

This ties into a bigger discussion around math notation in docstrings #956 #59 , wherein we made a decision against doing this back in 2019.  Yes, it can be nice in web-facing documentation, but it looks horrible in REPL views of docstrings (eg jupyter).  I don't know how much this situation has improved in the last few years, but I'd be happy to revisit this if necessary.



> I'm not sure if you want to have the comparison to other frameworks in the documentation. I personally find it very useful. Maybe a reference to this issue is also enough as an alternative.

I'm not necessarily opposed to this in principle.  However, it does introduce some potential for bit rot, and more work for us maintainers to ensure that it stays correct.  (The worst thing we could do, IMO, is propagate inaccurate documentation!)  While I don't necessarily expect radical changes in tf or torch, I also wouldn't bet on them staying exactly as they are forever.

If we *do* want to add this kind of thing, I think it's best done as an "advanced example" entry, showing how to get numerically identical results in all three frameworks while varying the key parameters of interest.
