### ISSUE TITLE
What is the equivalent function to extract Fbank compared to kaldi?

### ISSUE THREAD

**Issue by lxrswdd** [librosa/librosa#1710]
We know Kaldi provides the function `compute-fbank-feats` that extract 40 FBanks in each window by default.
Given MFCC is calculated by applying a DCT to the Fbank.
We would expect `librosa.feature.mfcc` to be calculated as `librosa.feature.melspectrogram` and indeed as suggested by Librosa source codes. Hence, I believe `librosa.feature.melspectrogram` is the `Fbank` in Kaldi.
However, Librosa also provides `librosa.filters.mel` which confuses me. What are the difference between `librosa.filters.mel` and `librosa.feature.melspectrogram`? Which one is the one I am looking for input features for machine learning?

**Comment by bmcfee** [comment]
Filters.mel just constructs the basis filters, but doesn't actually apply them to a signal. Features.melspectrogram actually applies the filters to the input signal.
