### ISSUE TITLE
n_mels inconsistency in librosa.feature.inverse.mel_to_stft

### ISSUE THREAD

**Issue by zee-1** [librosa/librosa#1711]
***BEFORE POSTING A BUG REPORT*** Please look through [existing issues (both open and closed)](https://github.com/librosa/librosa/issues?q=is%3Aissue) to see if it's already been reported or fixed!

**Describe the bug**
According to the documentation the the method mel_to_stft is defined as 
```
def mel_to_stft(
    M: np.ndarray,
    *,
    sr: float = 22050,
    n_fft: int = 2048,
    power: float = 2.0,
    **kwargs: Any,
) -> np.ndarray:
```

Documentation also states:

``` 
**kwargs : additional keyword arguments for Mel filter bank parameters
    n_mels : int > 0 [scalar]
        number of Mel bands to generate
    fmin : float >= 0 [scalar]
        lowest frequency (in Hz)
    fmax : float >= 0 [scalar]
        highest frequency (in Hz).
        If `None`, use ``fmax = sr / 2.0``
    htk : bool [scalar]
        use HTK formula instead of Slaney
    norm : {None, 'slaney', or number} [scalar]
        If 'slaney', divide the triangular mel weights by the width of
        the mel band (area normalization).
        If numeric, use `librosa.util.normalize` to normalize each filter
        by to unit l_p norm. See `librosa.util.normalize` for a full
        description of supported norm values (including `+-np.inf`).
        Otherwise, leave all the triangles aiming for a peak value of 1.0
    dtype : np.dtype
        The data type of the output basis.
        By default, uses 32-bit (single-precision) floating point.
```

As we can see n_mels are supposed to be a key word argument (kwarg). But in implementation present 

```    
# Construct a mel basis with dtype matching the input data
    mel_basis = filters.mel(
        sr=sr, n_fft=n_fft, n_mels=M.shape[-2], dtype=M.dtype, **kwargs
    )

    # Find the non-negative least squares solution, and apply
    # the inverse exponent.
    # We'll do the exponentiation in-place.
    inverse = nnls(mel_basis, M)
    return np.power(inverse, 1.0 / power, out=inverse)
```

```n_mels``` are being passed to the mel-bank from the shape of M. This ```mel_to_stft``` is used in many wrapper methods and cause ```TypeError: librosa.filters.mel() got multiple values for keyword argument 'n_mels'```.
**To Reproduce**

```
import librosa
recons_stft = librosa.feature.inverse.mel_to_stft\
 (inverse_spec,sr=sr,n_fft=1024,n_mels=72,fmin=20,fmax=20000)
```

**Expected behavior**
A simple solution for this problem is to remove the n_mels = M.shape[-2], and handle it like ``` if n_mels is not in kwargs use M.shape[-2] else use the provided one```

**Screenshots**
![image](https://github.com/librosa/librosa/assets/82804761/bf63e95c-c851-4569-818f-c6e4bce95054)

**Software versions***

```
Linux-5.15.107+-x86_64-with-glibc2.31
Python 3.10.11 (main, Apr  5 2023, 14:15:10) [GCC 9.4.0]
NumPy 1.22.4
SciPy 1.10.1
librosa 0.10.0.post2
INSTALLED VERSIONS
------------------
python: 3.10.11 (main, Apr  5 2023, 14:15:10) [GCC 9.4.0]

librosa: 0.10.0.post2

audioread: 3.0.0
numpy: 1.22.4
scipy: 1.10.1
sklearn: 1.2.2
joblib: 1.2.0
decorator: 4.4.2
numba: 0.56.4
soundfile: 0.12.1
pooch: v1.6.0
soxr: 0.3.5
typing_extensions: installed, no version number available
lazy_loader: installed, no version number available
msgpack: 1.0.5

numpydoc: None
sphinx: 3.5.4
sphinx_rtd_theme: None
matplotlib: 3.7.1
sphinx_multiversion: None
sphinx_gallery: None
mir_eval: None
ipython: None
sphinxcontrib.rsvgconverter: None
pytest: 7.2.2
pytest_mpl: None
pytest_cov: None
samplerate: None
resampy: None
presets: None
packaging: 23.1
```

**Comment by bmcfee** [comment]
Thanks for reporting this.  The code is correct, but the documentation should not include `n_mels`.



> A simple solution for this problem is to remove the n_mels = M.shape[-2], and handle it like ` if n_mels is not in kwargs use M.shape[-2] else use the provided one`

This will not work.  It will result in a basis matrix that is not compatible with the dimension of the input to be inverted.  `n_mels` does need to be inferred from `M` as it is currently implemented.
