### ISSUE TITLE
Unable to run any librosa method in Raspberry Pi

### ISSUE THREAD

**Issue by ZlaTanskY** [librosa/librosa#1725]
**Describe the bug**
Attempting to perform any method (librosa.load, creation of melspectrogram, ...) results in an LLVM error:
`LLVM ERROR: Symbol not found: __aeabi_unwind_cpp_pr0`

**To Reproduce**
OS:
```
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
```
Python 3.9 (manual install)
llvm version 11.0.1
Install requirements (scipy is installed from source, v1.8.1):
```
sudo apt-get install llvm -y
LLVM_CONFIG=/usr/bin/llvm-config pip install llvmlite
pip install librosa numpy<1.24 numba==0.56.4 (versions align with llvm 11.0)
```

Then try to load an audio file

```
import librosa

audio_path = "some_file.wav"
librosa.load(audio_path)
```

**Expected behavior**
Returning a numpy array and a sample_rate

```
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import librosa; print("librosa", librosa.__version__)
import numba; print("numba", numba.__version__)

librosa.show_versions()
```
Versions:
Linux-6.1.21-v8+-aarch64-with-glibc2.31
Python 3.9.7 (default, Mar  5 2022, 10:26:12) 
[GCC 10.2.1 20210110]
NumPy 1.23.5
SciPy 1.8.1
librosa 0.10.0.post2
numba 0.56.4

```
>>> librosa.show_versions()
INSTALLED VERSIONS
------------------
python: 3.9.7 (default, Mar  5 2022, 10:26:12) 
[GCC 10.2.1 20210110]

librosa: 0.10.0.post2

audioread: 3.0.0
numpy: 1.23.5
scipy: 1.8.1
sklearn: 1.2.2
joblib: 1.2.0
decorator: 5.1.1
numba: 0.56.4
soundfile: 0.12.1
pooch: v1.6.0
soxr: 0.3.5
typing_extensions: installed, no version number available
lazy_loader: installed, no version number available
msgpack: 1.0.5

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
matplotlib: None
sphinx_multiversion: None
sphinx_gallery: None
mir_eval: None
ipython: None
sphinxcontrib.rsvgconverter: None
pytest: 7.3.1
pytest_mpl: None
pytest_cov: None
samplerate: None
resampy: 0.2.2
presets: None
packaging: 23.1
```

**Comment by bmcfee** [comment]
Thanks for the detailed report.  However, this is definitely upstream of us:

> `LLVM ERROR: Symbol not found: __aeabi_unwind_cpp_pr0`

and is likely either llvmlite or numba-related.  Are you able to run numba code at all, eg, the examples on https://numba.readthedocs.io/en/stable/user/5minguide.html ?

**Comment by ZlaTanskY** [comment]
Thanks for your response and link. I am indeed not able to run that code, so it is numba related. Thanks for the guidance, I will look further there.
