### ISSUE TITLE
WaveShow Attribute Error About module 'matplotlib' has no attribute 'pyplot'

### ISSUE THREAD

**Issue by drjtryu** [librosa/librosa#1728]
I wrote code like below. 

import librosa
import librosa.display as test
from IPython.display import Audio

wavfilepath = "play.wav"
waveform, sample_rate = librosa.load(wavfilepath, sr=None)
test.waveshow(waveform, sr=sample_rate, label="test")

![image](https://github.com/librosa/librosa/assets/13362204/edc2ffa0-94ee-476d-8991-d05e0a43962f)

But Librosa generated Attribute Error Message "module 'matplotlib' has no attribute 'pyplot'"

Why did librosa generated that error message?

**Comment by bmcfee** [comment]
I believe this is already fixed by the recently merged #1722.

Would you be able to verify this by trying the current version from our github main branch?

**Comment by bmcfee** [comment]
Tried this out locally, and confirmed that this is already fixed by #1722 .  I'll close this out, but feel free to reopen if for some reason it persists on the main branch.
