### ISSUE TITLE
I can't get a different sized window working?

### ISSUE THREAD

**Issue by davies-w** [librosa/librosa#1735]
Hi,
 
I'm trying to vary the size of the window used by the FFT in CQT, but I can't get it to work:
```
h = sr*(i+1)
w = librosa.filters.get_window('boxcar', h, fftbins=True)
CQT = np.abs(librosa.cqt(y=y, sr=sr, bins_per_octave=12*3, n_bins=7*12*3, hop_length=h, window = w))
```

I just get this error?

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-29-dab46145a0f6>](https://localhost:8080/#) in <cell line: 19>()
     21   w = librosa.filters.get_window('boxcar', h, fftbins=True)
     22 
---> 23   CQT = np.abs(librosa.cqt(y=y, sr=sr, bins_per_octave=12*3, n_bins=7*12*3, hop_length=h, window= w))
     24   librosa.display.specshow(librosa.amplitude_to_db(CQT, ref=np.max),
     25                            y_axis='cqt_note', x_axis='time', bins_per_octave=12*3,

3 frames
[/usr/local/lib/python3.10/dist-packages/librosa/filters.py](https://localhost:8080/#) in window_bandwidth(window, n)
   1148         key = window
   1149 
-> 1150     if key not in WINDOW_BANDWIDTHS:
   1151         win = get_window(window, n)
   1152         WINDOW_BANDWIDTHS[key] = (

TypeError: unhashable type: 'numpy.ndarray'
```

Thanks in advance,
 Winton

**Comment by bmcfee** [comment]
This is because cqt uses variable length windows, so you can't pass in a previously constructed array of fixed length. You can call cqt with window='boxcar' though.

**Comment by davies-w** [comment]
Thank you - somewhat makes sense - why does it use variable length windows? Is it to do with the frequency bucketing?

**Comment by bmcfee** [comment]
The whole idea of the constant q transform is to keep the number of oscillations fixed for all basis frequencies. Low frequencies require long windows, high frequencies require short windows.

The differs from the discrete Fourier transform, which fixes the window length first so that different frequencies have different numbers of oscillations over the window duration.
