### ISSUE TITLE
Release new version to fix scipy tests

### ISSUE THREAD

**Issue by Mic92** [librosa/librosa#1737]
https://github.com/librosa/librosa/commit/12dee8eabed7df14c5622b52c05393ddfeb11f4b fixed compatibility with scipy in tests but it's not included in any release.
We rely as downstream packagers on tests to ensure all python dependencies play well together.

**Comment by bmcfee** [comment]
Thanks for the reminder on this @Mic92 - I've been meaning to reassess the remaining items on the 0.10.1 milestone and see if it makes sense to punt them to a 0.10.2 and cut 0.10.1 from the current main.  (I suspect it does make sense at this point.)

@lostanlen any thoughts?

**Comment by bmcfee** [comment]
... gave it a think, and I believe the impact on downstream tests is worth making a 0.10.1 release.

I'm currently waiting on some upstream conda-forge packages to rebuild, but I can get going on the release prep some time this week.
