### ISSUE TITLE
How can I find the Time Signature of a music file(mp3, wav) using librosa?

### ISSUE THREAD

**Issue by logesh2496** [librosa/librosa#1744]
Hi, I'm looking for an api in librosa to find the time signature from a mp3 or wav files. Please help. 
thanks

**Comment by bmcfee** [comment]
This unfortunately is out of scope for librosa, and to my knowledge, there is not an off-the-shelf solution for time signature inference.  I believe this is (frustratingly) still a open research question.

Time signature inference is closely related to downbeat estimation (locating the 1 of each bar).  The current best models for downbeat estimation (eg, TCN) are based on deep learning, and have significant statistical dependencies that place it out of scope for librosa.  Most of these models implicitly assume 4/4 time, though they can still work with 3/4 tracks much of the time. (This depends heavily on genre and instrumentation, among other things.)

Even if you can identify downbeats, there's still a bit of work to do in summarizing bar lengths into a time signature estimate.  If the time signature is constant over the track, you can probably get away with just counting the beats between downbeats, and then use a tempo threshold to determine if you're counting quarter or eighth notes.  However, it's pretty nontrivial to do this reliably in more realistic settings.

**Comment by lostanlen** [comment]
Hello @logesh2496 , i recommend you try: https://github.com/CPJKU/madmom_models/pull/18
