### ISSUE TITLE
I have a problem with the real time voice changer 

### ISSUE THREAD

**Issue by HAQ20** [librosa/librosa#1745]
I'm talking about this https://github.com/w-okada/voice-changer/blob/master/README_en.md
every time i open the start_http.bat it just shows an error for half a second and closes. I did a fast screenshot of the error

![error](https://github.com/librosa/librosa/assets/139398720/f3080078-ef2b-4735-b274-2ab2347cfece)

**Comment by bmcfee** [comment]
This is probably due to the issue described here: https://librosa.org/doc/latest/troubleshooting.html#import-librosa-hangs-indefinitely

**Comment by bmcfee** [comment]
Closing this out from lack of activity, but please reopen with more detail if my guess above was incorrect and the problem persists.

**Comment by meesssssssss** [comment]
its too hard to use
