### ISSUE TITLE
version bug with numpy 1.24 or later

### ISSUE THREAD

**Issue by oorsogood** [librosa/librosa#1752]
***BEFORE POSTING A BUG REPORT*** Please look through [existing issues (both open and closed)](https://github.com/librosa/librosa/issues?q=is%3Aissue) to see if it's already been reported or fixed!

**Describe the bug**

librosa 0.8.1 bump with numpy 1.24.3
Running pytest will occur the error as the below screenshot
But I did not use np.complex or any alias in my code that has been expired since numpy 1.24
<img width="652" alt="image" src="https://github.com/librosa/librosa/assets/87536536/2d155062-07a7-4b2b-9fb2-8fb6b55e8e1e">

**Screenshots**
<img width="604" alt="image" src="https://github.com/librosa/librosa/assets/87536536/a701f061-abc4-4e28-9ab6-6490b531616a">

**Additional context**

I am not sure what caused the pytest problem
But I somehow fix the problem by 
- locking the numpy version to 1.23.4
- locking the librosa version to 0.10.1
- assign variable wave to the y attribute
<img width="564" alt="image" src="https://github.com/librosa/librosa/assets/87536536/c8d97f6c-97d5-4d87-96ed-db60f82ee29a">

**Comment by bmcfee** [comment]
This issue #1350 was resolved two years ago #1390.
