### ISSUE TITLE
axes.get_lines.prop_cycler was made internal in matplotlib 3.8.0

### ISSUE THREAD

**Issue by mweinelt** [librosa/librosa#1754]
**Describe the bug**

The access to `axes.get_lines.prop_cycler` has been made private in matplotlib 3.8.0, thereby breaking a number of tests.

https://github.com/librosa/librosa/blob/43d4427f7a389acc79b5be3c924646701f19bb46/librosa/display.py#L2041-L2042

```
librosa> FAILED tests/test_display.py::test_waveshow_mono - AttributeError: '_process_plot_var_args' object has no attribute 'prop_cycler'
librosa> FAILED tests/test_display.py::test_waveshow_mono_trans - AttributeError: '_process_plot_var_args' object has no attribute 'prop_cycler'
librosa> FAILED tests/test_display.py::test_waveshow_mono_zoom - AttributeError: '_process_plot_var_args' object has no attribute 'prop_cycler'
librosa> FAILED tests/test_display.py::test_waveshow_mono_zoom_trans - AttributeError: '_process_plot_var_args' object has no attribute 'prop_cycler'
librosa> FAILED tests/test_display.py::test_waveshow_mono_zoom_out - AttributeError: '_process_plot_var_args' object has no attribute 'prop_cycler'
librosa> FAILED tests/test_display.py::test_waveshow_stereo - AttributeError: '_process_plot_var_args' object has no attribute 'prop_cycler'
librosa> FAILED tests/test_display.py::test_unknown_wavaxis - AttributeError: '_process_plot_var_args' object has no attribute 'prop_cycler'
librosa> FAILED tests/test_display.py::test_waveshow_unknown_wavaxis - AttributeError: '_process_plot_var_args' object has no attribute 'prop_cycler'
librosa> FAILED tests/test_display.py::test_sharex_specshow_ms - AttributeError: '_process_plot_var_args' object has no attribute 'prop_cycler'
librosa> FAILED tests/test_display.py::test_sharex_waveplot_ms - AttributeError: '_process_plot_var_args' object has no attribute 'prop_cycler'
librosa> FAILED tests/test_display.py::test_waveshow_disconnect - AttributeError: '_process_plot_var_args' object has no attribute 'prop_cycler'
librosa> FAILED tests/test_display.py::test_waveshow_deladaptor - AttributeError: '_process_plot_var_args' object has no attribute 'prop_cycler'
```

Upstream discussion: https://github.com/matplotlib/matplotlib/issues/26831
Upstream PR: https://github.com/matplotlib/matplotlib/pull/26341

**To Reproduce**

Run the test suite against matplotlib 3.8.0.

**Expected behavior**
Compatibility with matplotlib 3.8.0 as indicated by its version constraints.

**Software versions***

**Additional context**
n/a

**Comment by bmcfee** [comment]
Thanks for raising this.. we probably should have seen this coming :sweat: but I was hoping they'd implement a proper public API for this before doing a deprecation purge.

I think in the short term, we'll have to cut a post-release on 0.10.1 to upper-pin matplotlib at <3.8, and then we'll need to figure out how to replace the [offending code](https://github.com/librosa/librosa/blob/43d4427f7a389acc79b5be3c924646701f19bb46/librosa/display.py#L2041-L2042) going forward.

**Comment by bmcfee** [comment]
> and then we'll need to figure out how to replace the [offending code](https://github.com/librosa/librosa/blob/43d4427f7a389acc79b5be3c924646701f19bb46/librosa/display.py#L2041-L2042) going forward.

Gave this some thought, and I think we can get around this by revising the logic a little.  We're only accessing the cycler to get the color value so that it can be shared by the step and fill_between plots.  The logic goes like:

1. if we don't have a color, get the next color from the cycler and add it to kwargs
2. construct a step plot with kwargs
3. construct a fill_between plot with kwargs

Instead, we could imagine doing something like:
1. construct a step plot with kwargs
2. if color wasn't in kwargs already, pull the color from the newly constructed step plot and add it to kwargs
3. construct the fill_between

I think this should be a pretty simple change to make, if anyone wants to take a crack at it.  I won't have time for it myself for a few days.

**Comment by bmcfee** [comment]
> I think this should be a pretty simple change to make, if anyone wants to take a crack at it. I won't have time for it myself for a few days.

Ok, I was wrong - took a crack at this and it seems to work.  PR forthcoming.

**Comment by mweinelt** [comment]
Thanks, applied on top of 0.10.1 in nixpkgs and things are looking fine.
