### ISSUE TITLE
can use parallel resampy

### ISSUE THREAD

**Issue by mathpopo** [librosa/librosa#1757]
if sr is not None:
        y = resample(y, orig_sr=sr_native, target_sr=sr, res_type=res_type)------- parallel=True?

this function  have a resampy.resample    from  https://github.com/bmcfee/resampy/blob/main/resampy/core.py

def resample(
    x, sr_orig, sr_new, axis=-1, filter="kaiser_best", parallel=False, **kwargs
):

**Comment by bmcfee** [comment]
Please use the issue template. As this is written, it's not clear what your question is.

**Comment by mathpopo** [comment]
@bmcfee  issue like this :
[librosa](https://github.com/librosa/librosa/tree/main)/[librosa](https://github.com/librosa/librosa/tree/main/librosa)/[core](https://github.com/librosa/librosa/tree/main/librosa/core)
/audio.py

def load(
    path: Union[
        str, int, os.PathLike[Any], sf.SoundFile, audioread.AudioFile, BinaryIO
    ],
    *,
    sr: Optional[float] = 22050,
    mono: bool = True,
    offset: float = 0.0,
    duration: Optional[float] = None,
    dtype: DTypeLike = np.float32,
    res_type: str = "soxr_hq",
) -> Tuple[np.ndarray, float]:
{
.............
    if sr is not None:
        y = resample(y, orig_sr=sr_native, target_sr=sr, res_type=res_type)

.............
}

def resample(
    y: np.ndarray,
    *,
    orig_sr: float,
    target_sr: float,
    res_type: str = "soxr_hq",
    fix: bool = True,
    scale: bool = False,
    axis: int = -1,
    **kwargs: Any,
) -> np.ndarray:
{
.......................

else:
        y_hat = resampy.resample(y, orig_sr, target_sr, filter=res_type, axis=axis)
.......................
}

this function have a resampy.resample from https://github.com/bmcfee/resampy/blob/main/resampy/core.py


def resample(
x, sr_orig, sr_new, axis=-1, filter="kaiser_best", parallel=False, **kwargs
):

parallel=False  default set false, but  in your code , i donot find a param can set the "parallel", i try to set bymyself, it can work and speed up, so i doubt ,i can do this ?

**Comment by bmcfee** [comment]
I think I understand.  It's a rather complicated situation, as described in #1480 .

At this point, I generally don't recommend resampy anymore, as soxr is both faster (most of the time) and at least as accurate.  In 0.10 onward, soxr is the default resampling engine for librosa.

**Comment by mathpopo** [comment]
@bmcfee ok , I understand, i try to use soxr instead of resampy, it can work,thanks!
