### ISSUE TITLE
Librosa functions taking more time for the first time

### ISSUE THREAD

**Issue by Killshot667** [librosa/librosa#1758]
I have noticed this issue with all the librosa input functions like resample, stream, load etc. All of them take a lot of time for the first call but are extremely fast from the second call onwards. These are some of the execution time (in ms) results I have got

for _ in range(20):
    li = np.random.rand(100000)
    start = time.time()
    pi = librosa.resample(li, orig_sr=22050, target_sr=8000) 
    end = time.time()
    print((end-start)*(10**3))

Output : 

2051.5551567077637
1.8010139465332031
1.7135143280029297
1.6446113586425781
1.6410350799560547
1.6269683837890625
1.6417503356933594
1.623392105102539
1.634359359741211
1.6226768493652344
1.649618148803711
1.6248226165771484
1.6338825225830078
1.6448497772216797
1.6438961029052734
1.6536712646484375
1.6226768493652344
1.6443729400634766
1.6679763793945312
1.6582012176513672

Is there some way to solve this issue on the first call?

**Comment by bmcfee** [comment]
This is because numba is a "just in time" compiler. On the first call, functions are compiled, and the compiled version is used thereafter.

It is not avoidable in general, but it should be a one time cost after installation. Compiled functions should persist across sessions due to caching.

**Comment by bmcfee** [comment]
As an aside, please use the issue template.  You should not see this behavior in the 0.10 series, where the default sample rate converter does not use numba, but it would happen in earlier releases.

**Comment by Killshot667** [comment]
Hey @bmcfee . Thanks for the clarification. Unfortunately this issue is coming in the 0.10 series as well.

**Comment by bmcfee** [comment]
Ok.  In that case, the first-time cost is coming from lazy loader, not jit compilation.

Functions are not imported until their first attempted use, and importing always incurs a cost.  Without lazy loading, you'd pay the cost when calling `import librosa` - with lazy loading, you pay it when first using the function (`librosa.load` in this case.)  Either way, the cost is unavoidable.
