### ISSUE TITLE
Should `key_to_notes` print naturals? (♮)

### ISSUE THREAD

**Issue by lostanlen** [librosa/librosa#1760]
In the wake of #1756, i have looked more closely at `key_to_notes` today. I have a small dissatisfaction with the way we currently treat some pitch classes outside the scale or mode.

Example from the documentation:
```python
>>> librosa.key_to_notes('G#:maj')
['B♯', 'C♯', 'D', 'D♯', 'E', 'E♯', 'F♯', 'F𝄪', 'G♯', 'A', 'A♯', 'B']
```

Here's my logic: we're in G# major, so the key signature has six sharps and one double-sharp. So presumably`D` sounds like`D#` unless explicitly stated otherwise. More precisely, if a place a notehead at the `D` position on the staff, and we're in the key of `G#` major, what I hear has a pitch of `D#`, not a `D` natural.

Hence my proposal to change the output to 
```python
['B♯', 'C♯', 'D♮', 'D♯', 'E♮', 'E♯', 'F♯', 'F𝄪', 'G♯', 'A♮', 'A♯', 'B♮']
```
(note the presence of natural accidentals as suffixes to `D`, `E`, `A`, and `B`)

Here's is another, more common example: D major. We have two sharps. Current behavior:
```python
>>> librosa.key_to_notes('D:maj')
['C', 'C♯', 'D', 'D♯', 'E', 'F', 'F♯', 'G', 'G♯', 'A', 'A♯', 'B']
```

Proposed behavior
```python
>>> librosa.key_to_notes('D:maj')
['C♮', 'C♯', 'D', 'D♯', 'E', 'F♮', 'F♯', 'G', 'G♯', 'A', 'A♯', 'B']
```

Maybe this has drawbacks i haven't considered, or is considered too pedantic / redundant. I'm open to strike a compromise by introducing a new keyword argument to toggle these naturals in or out.

For the record, i do not suggest that we implement double naturals, which are prone to confusion and outdated in music notation anyway: https://en.wikipedia.org/wiki/Natural_(music)#Double_natural

**Comment by bmcfee** [comment]
One big question here is how we'd typeset things when Unicode=false.

**Comment by bmcfee** [comment]
One big question here is how we'd typeset things when Unicode=false.

.. but otherwise I'm generally in favor of this proposal. I like the idea of making it opt-in with a parameter and preserving backwards compatibility.

I asked ye olde bot for suggestions on the Unicode issue, and it suggested "n" as an accidental marker. I'm not sure i like it, but i haven't thought of anything better.

**Comment by bmcfee** [comment]
A couple more thoughts on this:

- What would be the logic for deciding which notes get a natural marker and which don't?  Can we do this in a way that doesn't introduce a dependence on `key_to_degrees`?
- Implementing this might be tricky.  #1739 introduced a recursive element to the note mapping function, which strips off accidentals from the tonic and adds them back in to the resulting notes as needed.  Probably what we should do here is make the recursive calls with `natural=False` (or whatever the parameter is called), so we don't have to worry about stripping out naturals.
- For the multiple natural question: I don't think we'd ever generate this directly, but we can parse it (eg when doing notes_to_midi).  We did make an explicit decision in #1739 that any instance of natural is a reset on the accidental counter, so multiple naturals are treated as idempotent.

**Comment by erabinov** [comment]
- If I understand correctly, @lostanlen's proposal would be to include naturals for any note which is not printed with an accidental and is not in the scale/mode designated by the `key` parameter. On the face of it, this logic seems to be to pass through `key_to_degrees`.
- If `key` has multiple accidentals, then all notes in `key_to_notes(key)` have at least one accidental, so this issue shouldn't arise. When the recursive call is made, the notes are simplified, so something like `C♮#` will be simplified to `C#`.
- Related to @bmcfee's second bullet point: we decided to be allowed to parse keys like `C##bb:maj` (as equivalent to `C:maj`), which are nonsense from the music theory standpoint (related to treating all accidentals as additive). Would that still hold for this proposed change?

**Comment by lostanlen** [comment]
> If I understand correctly, @lostanlen's proposal would be to include naturals for any note which is not printed with an accidental and is not in the scale/mode designated by the key parameter. On the face of it, this logic seems to be to pass through `key_to_degrees`

Thanks @erabinov. Yes, that's indeed what i meant to specify. You've summarized my proposal.

I'm only realizing now that another potential spelling mode would be to _remove_ accidentals that are already implied by the key signature, with G# major becoming

```
['B', 'C', 'D♮', 'D', 'E♮', 'E', 'F♯', 'F', 'G', 'A♮', 'A', 'B♮']
```

and D major becoming
```
['C♮', 'C', 'D', 'D♯', 'E', 'F♮', 'F', 'G', 'G♯', 'A', 'A♯', 'B']
```

Indeed this is how musicians talk to each other while rehearsing. If we're in D major, we say F to mean F# and say F-natural to mean F.

The spelling of notes outside of the diatonic scale is a neverending debate and ultimately a matter of preference. At some point we'd be entering the territory of pitch spelling algorithms (http://www.titanmusic.com/papers/public/ps-ircam.pdf), which have a data-driven element to them as they involve melodic context. Example: a key modulation from D major to G major might involve a pitch that is spelled as C♮, but a key modulation from D major to C# major might involve the same pitch, spelled as B#.

So, hm, yeah. I'm not so sure anymore as to when to where to draw the line between adhering to the convention of the key versus just spelling out every pitch class in the least surprising way. (https://en.wikipedia.org/wiki/Principle_of_least_astonishment)

**Comment by bmcfee** [comment]
@erabinov yeah, I think this is all correct.

High-level, I think the following strategy should work:

- Modify recursive calls to always use `natural=False`
- If `natural==True`, after applying `__simplify_note`, we call `key_to_degrees` to identify which indices are out of key.  For those out of key, any note lacking an accidental gets a natural marker attached.
- We then finish up with a unicode simplification as needed.

In looking back over this function now, it does seem to be getting pretty complex.  I wonder if it's worth simplifying a bit to remove the logic for explicitly handling minor?  We could instead treat minor a an alias of aeolian, and then all code paths would use the same logic for translating to/from relative major keys.  This might make the implementation of this natural decoration a little easier (or not - I haven't thought this through entirely yet).

**Comment by bmcfee** [comment]
> The spelling of notes outside of the diatonic scale is a neverending debate and ultimately a matter of preference. At some point we'd be entering the territory of pitch spelling algorithms (http://www.titanmusic.com/papers/public/ps-ircam.pdf), which have a data-driven element to them as they involve melodic context. Example: a key modulation from D major to G major might involve a pitch that is spelled as C♮, but a key modulation from D major to C# major might involve the same pitch, spelled as B#.

I think it's fair to say that modulations and implied context are out of scope here.  The API only ever allows for one key to be specified.

**Comment by erabinov** [comment]
> @erabinov yeah, I think this is all correct.
> 
> High-level, I think the following strategy should work:
> 
> * Modify recursive calls to always use `natural=False`
> * If `natural==True`, after applying `__simplify_note`, we call `key_to_degrees` to identify which indices are out of key.  For those out of key, any note lacking an accidental gets a natural marker attached.
> * We then finish up with a unicode simplification as needed.
> 
> In looking back over this function now, it does seem to be getting pretty complex. I wonder if it's worth simplifying a bit to remove the logic for explicitly handling minor? We could instead treat minor a an alias of aeolian, and then all code paths would use the same logic for translating to/from relative major keys. This might make the implementation of this natural decoration a little easier (or not - I haven't thought this through entirely yet).

Sounds like a good strategy. The next week or so is a bit hectic for me, but I'm happy to work on this the week of the 9th!

**Comment by bmcfee** [comment]
That'd be awesome, thanks!
