### ISSUE TITLE
AttributeError: '_process_plot_var_args' object has no attribute 'prop_cycler'

### ISSUE THREAD

**Issue by j-k** [librosa/librosa#1763]
AttributeError: '_process_plot_var_args' object has no attribute 'prop_cycler'

**Describe the bug**
The above error happens

**To Reproduce**

Example:
```
import librosa
import matplotlib.pyplot as plt
import librosa.display

y, sr = librosa.load(librosa.ex('choice'), duration=10)
fig, ax = plt.subplots(nrows=3, sharex=True)
librosa.display.waveshow(y, sr=sr, ax=ax[0])
ax[0].set(title='Envelope view, mono')
ax[0].label_outer()
```
If the code is too long, feel free to put it in a public gist and link
it in the issue: https://gist.github.com

**Expected behavior**
Display waveform

**Screenshots**

**Software versions***

Please run the following Python code snippet and paste the output below.
```
Linux-6.2.0-33-generic-x86_64-with-glibc2.37
Python 3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:34:09) [GCC 12.3.0]
NumPy 1.24.4
SciPy 1.11.2
librosa 0.10.1
INSTALLED VERSIONS
------------------
python: 3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:34:09) [GCC 12.3.0]

librosa: 0.10.1

audioread: 3.0.0
numpy: 1.24.4
scipy: 1.11.2
sklearn: 1.3.1
joblib: 1.3.2
decorator: 5.1.1
numba: 0.57.1
soundfile: 0.12.1
pooch: v1.7.0
soxr: 0.3.5
typing_extensions: installed, no version number available
lazy_loader: installed, no version number available
msgpack: 1.0.6

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
matplotlib: 3.8.0
sphinx_multiversion: None
sphinx_gallery: None
mir_eval: None
ipython: None
sphinxcontrib.rsvgconverter: None
pytest: None
pytest_mpl: None
pytest_cov: None
samplerate: None
resampy: None
presets: None
packaging: 23.1
```

**Comment by bmcfee** [comment]
This issue has already been reported and fixed. It will be included in the next release, but meanwhile you can either roll back matplotlib to 3.7, or use the development version of librosa from the GitHub repo.

**Comment by zhutoutoutousan** [comment]
TESTED Rollin' bak 2 matplotlib 3.7 also works yo champ thanks 4 fixing

**Comment by pedro-w** [comment]
Another work-around, if you don't want to roll back matplotlib or wait for the next release of librosa, is to specify the colour explicitly, for example:

    librosa.display.waveshow(stereo[0, :div], sr=sr, ax=axs[2, 0], color="blue")

of course you don't then get the automatic colour cycling if you put more than one trace on the same axes.

**Comment by bilal-grotabyte** [comment]
Tried with v3.5, 3.6, 3.7. All gave the same error: AttributeError: '_process_plot_var_args' object has no attribute 'prop_cycler'

**Comment by pedro-w** [comment]
@bilal-grotabyte that wasn't my experience.
Using matplotlib 3.6.3 and 3.7.3, I ran j-k's example with no error. 3.8.1 gave the error as described.
I tried on Windows, python 3.11.6, librosa 0.10.1
