### ISSUE TITLE
 Can you provide a library for del noise with librosa?

### ISSUE THREAD

**Issue by mathpopo** [librosa/librosa#1771]
I wonder if librosa provides an interface for removing noise?

**Comment by bmcfee** [comment]
This depends on what you mean by "noise", which is entirely dependent on your application and use case.  (Without getting too philosophical about it, I define "noise" as "whatever isn't explicitly modeled", and that's far too broad of a definition to be useful in the context of a library API.)

Librosa does provide several functions that can be used for different kinds of "noise" removal though.  Most of these live in the "decompose" module.

**Comment by mathpopo** [comment]
@bmcfee  first very thanks for your repling， the "noise" i mean: 
One person's speech mixes with the speech of those nearby， "decompose" module， have example?
