### ISSUE TITLE
Can Python 3.12 installation be supported

### ISSUE THREAD

**Issue by tianshuo78520a** [librosa/librosa#1772]
I try using`pip3.12 install librosa` is error，May I ask when we can support it
![image](https://github.com/librosa/librosa/assets/29832297/50bc21fe-1a31-41ab-9c9b-dff49073eb4d)

**Comment by bmcfee** [comment]
Your traceback provides the answer to this question: some of the dependencies (notably numba) do not yet support python 3.12, so we can't either.

**Comment by tianshuo78520a** [comment]
Understood, thank you for your reply

**Comment by GaussianWonder** [comment]
On numba [0.59 milestone](https://github.com/numba/numba/milestone/73) there is [this](https://github.com/numba/numba/issues/9197) PR open which tracks python 3.12 support. It looks like it's going to be supported soon.

**Comment by bmcfee** [comment]
Looks like there's now a release candidate for numba, so they'll beat us to the next milestone.  I've added this to the 0.10.2 docket.

**Comment by davidfraser** [comment]
Note that Python 3.12 doesn't come with setuptools installed by default, so it may be good to add that to the requirements, otherwise imports of pkg_resources will give errors.

**Comment by bmcfee** [comment]
> Note that Python 3.12 doesn't come with setuptools installed by default, so it may be good to add that to the requirements, otherwise imports of pkg_resources will give errors.

This shouldn't be necessary since we already merged #1765
