### ISSUE TITLE
librosa.load parameters misleading

### ISSUE THREAD

**Issue by davies-w** [librosa/librosa#1775]
***BEFORE POSTING A BUG REPORT*** Please look through [existing issues (both open and closed)](https://github.com/librosa/librosa/issues?q=is%3Aissue) to see if it's already been reported or fixed!

**Describe the bug**
librosa.load(filename) => ignores the metadata sample rate found in the file and downsamples to 22050.
librosa.load(filename, sr=None) => actually uses the metadata sample rate 

While not strictly speaking a bug, the semantics of this led to me losing hours of work why I tried to figure out why I had weirdnesses in my experiments.

I'd say change this so that failing to set the SR parameter has a very loud text warning and to add a sr="librosa-default" kind of option. Relying on a semantic different between Not Set and None, isn't very Pythonic (at least in my experience). IANAGSWE (I am not a  Good Software Engineer), but I thought I should say something, feel free to think of other options!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Software versions***

**Additional context**

**Comment by bmcfee** [comment]
This issue has been discussed, in depth, many times over.  As the github issue template says: please read through past discussions before starting a new one.  Thanks!
