### ISSUE TITLE
The program got stuck at librosa.load()

### ISSUE THREAD

**Issue by alioth-k** [librosa/librosa#1776]
this is screenshot
![image](https://github.com/librosa/librosa/assets/109710818/1f34bf2c-00b4-4399-819c-427bd0e4a53f
the ogg file is only five seconds long, but the program got stuck at librosa.load() for minutes 
I guess there must be some problem, it can't be simply due to slow execution

**Comment by bmcfee** [comment]
http://librosa.org/doc/latest/troubleshooting.html#import-librosa-hangs-indefinitely is probably what you're looking for.

**Comment by bmcfee** [comment]
Just for a bit more context, this is an upstream bug in numba (or possibly tempfile) as noted here: https://github.com/numba/numba/issues/8755

But the link I gave above to the troubleshooting section of the librosa docs does provide a simple workaround.

**Comment by alioth-k** [comment]
> Just for a bit more context, this is an upstream bug in numba (or possibly tempfile) as noted here: [numba/numba#8755](https://github.com/numba/numba/issues/8755)
> 
> But the link I gave above to the troubleshooting section of the librosa docs does provide a simple workaround.

Thank you very much for your help. I have set the permissions for the folder "D:\Anaconda3\envs\py39\Lib\site-packages\librosa" to allow full control for all users. Now the code can read the files properly.

**Comment by StrengthFirstF** [comment]
> > Just for a bit more context, this is an upstream bug in numba (or possibly tempfile) as noted here: [numba/numba#8755](https://github.com/numba/numba/issues/8755)
> > But the link I gave above to the troubleshooting section of the librosa docs does provide a simple workaround.
> 
> Thank you very much for your help. I have set the permissions for the folder "D:\Anaconda3\envs\py39\Lib\site-packages\librosa" to allow full control for all users. Now the code can read the files properly.

I also have this kind of Librosa function that freezes, but I haven't solved it using this method. Maybe my method is wrong. Can you tell me the specific solution

**Comment by alioth-k** [comment]
> > > Just for a bit more context, this is an upstream bug in numba (or possibly tempfile) as noted here: [numba/numba#8755](https://github.com/numba/numba/issues/8755)
> > > But the link I gave above to the troubleshooting section of the librosa docs does provide a simple workaround.
> > 
> > 
> > Thank you very much for your help. I have set the permissions for the folder "D:\Anaconda3\envs\py39\Lib\site-packages\librosa" to allow full control for all users. Now the code can read the files properly.
> 
> I also have this kind of Librosa function that freezes, but I haven't solved it using this method. Maybe my method is wrong. Can you tell me the specific solution

Sorry for the late reply.
If you are also stuck in an infinite loop somewhere on Numba, you can use my method because it is due to insufficient permissions, but your problem may not be this. I recommend you debug first to see where your program is stuck.
Here is my solution
1.Find the folder corresponding to your conda environment
2.Right click on the librosa folder to open the security tab under the properties item
3.Allow all permissions for all users (the black check mark is what I added later)
![image](https://github.com/user-attachments/assets/0981d59c-ce07-4a41-a9f0-37dbda8d2702)

**Comment by StrengthFirstF** [comment]
> > > > Just for a bit more context, this is an upstream bug in numba (or possibly tempfile) as noted here: [numba/numba#8755](https://github.com/numba/numba/issues/8755)
> > > > But the link I gave above to the troubleshooting section of the librosa docs does provide a simple workaround.
> > > 
> > > 
> > > Thank you very much for your help. I have set the permissions for the folder "D:\Anaconda3\envs\py39\Lib\site-packages\librosa" to allow full control for all users. Now the code can read the files properly.
> > 
> > 
> > I also have this kind of Librosa function that freezes, but I haven't solved it using this method. Maybe my method is wrong. Can you tell me the specific solution
> 
> Sorry for the late reply. If you are also stuck in an infinite loop somewhere on Numba, you can use my method because it is due to insufficient permissions, but your problem may not be this. I recommend you debug first to see where your program is stuck. Here is my solution 1.Find the folder corresponding to your conda environment 2.Right click on the librosa folder to open the security tab under the properties item 3.Allow all permissions for all users (the black check mark is what I added later) ![image](https://private-user-images.githubusercontent.com/109710818/382010287-0981d59c-ce07-4a41-a9f0-37dbda8d2702.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDgxODIsIm5iZiI6MTczMDcwNzg4MiwicGF0aCI6Ii8xMDk3MTA4MTgvMzgyMDEwMjg3LTA5ODFkNTljLWNlMDctNGE0MS1hOWYwLTM3ZGJkYThkMjcwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwODExMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDhjOWY4NDZmNmI1YTU5NTVlODFiNDc4YjVmZDllZTU2MWIyZGY5MGJlNmEzMGY0OTIwYTg2NjMyY2FmYjQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9i-52r88Dv4ZWX7JlYAuzBx-NvI9-KAH0iuVNeACrkw)

thank you

**Comment by StrengthFirstF** [comment]
> > > > 只是为了提供更多的上下文，这是 numba（或可能是 tempfile）中的一个上游错误，如下所述：[numba/numba#8755](https://github.com/numba/numba/issues/8755) 但是我上面给出的 librosa 文档故障排除部分的链接确实提供了一个简单的解决方法。
> > > 
> > > 
> > > 非常感谢您的帮助。我已经为文件夹“D：\Anaconda3\envs\py39\Lib\site-packages\librosa”设置了权限，以允许所有用户完全控制。现在代码可以正确读取文件。
> > 
> > 
> > 我也有这种卡顿的 Librosa 函数，但是我还没有用这种方法解决。也许我的方法错了。您能告诉我具体的解决方案
> 
> 很抱歉回复晚了。如果你也在 Numba 的某个地方陷入了无限循环，你可以使用我的方法，因为这是由于权限不足，但你的问题可能不是这个。我建议您先进行调试，看看您的程序卡在哪里。这是我的解决方案 1.找到与您的 conda 环境对应的文件夹 2.右键单击 librosa 文件夹以打开属性项下的安全选项卡 3.允许所有用户的所有权限（黑色复选标记是我后来添加的） ![图像](https://private-user-images.githubusercontent.com/109710818/382010287-0981d59c-ce07-4a41-a9f0-37dbda8d2702.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDgxODIsIm5iZiI6MTczMDcwNzg4MiwicGF0aCI6Ii8xMDk3MTA4MTgvMzgyMDEwMjg3LTA5ODFkNTljLWNlMDctNGE0MS1hOWYwLTM3ZGJkYThkMjcwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwODExMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDhjOWY4NDZmNmI1YTU5NTVlODFiNDc4YjVmZDllZTU2MWIyZGY5MGJlNmEzMGY0OTIwYTg2NjMyY2FmYjQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9i-52r88Dv4ZWX7JlYAuzBx-NvI9-KAH0iuVNeACrkw)

非常感谢，前几天我搜了一下教程，自己解决了，非常感谢你的帮助

**Comment by StrengthFirstF** [comment]
> > > > Just for a bit more context, this is an upstream bug in numba (or possibly tempfile) as noted here: [numba/numba#8755](https://github.com/numba/numba/issues/8755)
> > > > But the link I gave above to the troubleshooting section of the librosa docs does provide a simple workaround.
> > > 
> > > 
> > > Thank you very much for your help. I have set the permissions for the folder "D:\Anaconda3\envs\py39\Lib\site-packages\librosa" to allow full control for all users. Now the code can read the files properly.
> > 
> > 
> > I also have this kind of Librosa function that freezes, but I haven't solved it using this method. Maybe my method is wrong. Can you tell me the specific solution
> 
> Sorry for the late reply. If you are also stuck in an infinite loop somewhere on Numba, you can use my method because it is due to insufficient permissions, but your problem may not be this. I recommend you debug first to see where your program is stuck. Here is my solution 1.Find the folder corresponding to your conda environment 2.Right click on the librosa folder to open the security tab under the properties item 3.Allow all permissions for all users (the black check mark is what I added later) ![image](https://private-user-images.githubusercontent.com/109710818/382010287-0981d59c-ce07-4a41-a9f0-37dbda8d2702.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDg2NzUsIm5iZiI6MTczMDcwODM3NSwicGF0aCI6Ii8xMDk3MTA4MTgvMzgyMDEwMjg3LTA5ODFkNTljLWNlMDctNGE0MS1hOWYwLTM3ZGJkYThkMjcwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwODE5MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzBkNmMxMjk3MzE1MjU5ODI2MGEwZjMxZDAzYTFlODQ3YjY3YzdiZjg0ZmFmNzE1MjY0Zjc3YzkwMjhlODU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cEfTi8HF3Xezv6H0tWtX4tJ-1svXIo15xFszs60UPTY)

Thank you very much, the issue has been resolved
