### ISSUE TITLE
Cannot install librosa under virtual environment 

### ISSUE THREAD

**Issue by yasaskj** [librosa/librosa#1791]
***BEFORE POSTING A BUG REPORT*** Please look through [existing issues (both open and closed)](https://github.com/librosa/librosa/issues?q=is%3Aissue) to see if it's already been reported or fixed!

**Describe the bug**
I installed librosa under the virtual environment:
![Screenshot (50)](https://github.com/librosa/librosa/assets/132162202/be9e98cc-6819-4979-8e78-ceef7253d9b7)

I can see it in the packages list when i try pip list as well:
![Screenshot (51)](https://github.com/librosa/librosa/assets/132162202/8e32b963-ebba-480a-844f-762be9739de6)

But i cannot import it in my code:
![Screenshot (53)](https://github.com/librosa/librosa/assets/132162202/a43916cf-5e77-4b34-b46a-12a4fdb45532)

And in the packages tab also i cannot see librosa:
![Screenshot (54)](https://github.com/librosa/librosa/assets/132162202/e497ae1b-f6de-4724-8bfa-cff4a39d9a3c)

**To Reproduce**
<!--
Example:
```
import librosa


**Expected behavior**
Need a solution to why this is happening or how to install librosa properly. 



**Software versions***
Windows-10-10.0.22621-SP0
Python 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
NumPy 1.26.2
SciPy 1.11.4

**Comment by bmcfee** [comment]
Looks like a vscode problem with using the correct environment, not a librosa problem.
