### ISSUE TITLE
issue with the Numba library in  Docker container

### ISSUE THREAD

**Issue by SpeechC** [librosa/librosa#1792]
***BEFORE POSTING A BUG REPORT*** Please look through [existing issues (both open and closed)](https://github.com/librosa/librosa/issues?q=is%3Aissue) to see if it's already been reported or fixed!

**Describe the bug**
I am trying to run simple librosa code within a docker container.  The problem is librosa.load

**To Reproduce**

**Additional context**

**Comment by bmcfee** [comment]
This issue report does not have enough detail to diagnose.  The subject line indicates that it is a problem with numba though, and therefore out of scope for us.
