### ISSUE TITLE
Trimming with audio made of complete silence

### ISSUE THREAD

**Issue by giamic** [librosa/librosa#1802]
I'm using `librosa.effects.trim` to get rid of silence at both ends of a track. However, in the edge case when a track is completely silent (i.e. all its entries are exactly zero), I would expect to get an empty array back while I get a pointer to the input array.

**To Reproduce**
```
import librosa as lr
import numpy as np

x = np.zeros(22050 * 30)  # 30 seconds of silent audio at 22050 Hz
x_trimmed, boundaries = lr.effects.trim(x)

assert len(x_trimmed) == 0  # this assert fails because x_trimmed == x 
```

**Expected behavior**
The output array should be empty.

**Software versions**
```
macOS-14.3-arm64-arm-64bit
Python 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:37:07) [Clang 15.0.7 ]
NumPy 1.26.2
SciPy 1.11.4
librosa 0.10.1

INSTALLED VERSIONS
------------------

python: 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:37:07) [Clang 15.0.7 ]

librosa: 0.10.1

audioread: 3.0.1
numpy: 1.26.2
scipy: 1.11.4
sklearn: 1.3.2
joblib: 1.3.2
decorator: 5.1.1
numba: 0.58.1
soundfile: 0.12.1
pooch: v1.8.0
soxr: 0.3.7
typing_extensions: installed, no version number available
lazy_loader: installed, no version number available
msgpack: 1.0.7

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
matplotlib: 3.8.2
sphinx_multiversion: None
sphinx_gallery: None
mir_eval: None
ipython: None
sphinxcontrib.rsvgconverter: None
pytest: 7.4.3
pytest_mpl: None
pytest_cov: None
samplerate: None
resampy: None
presets: None
packaging: 23.2
```

**Comment by bmcfee** [comment]
This is actually a bit subtle, but I believe it is behaving according to spec.

The problem is that the trimming logic depends on being a certain amount (`top_db`) below a reference amplitude (`ref`).  By default, `ref` is calculated as the max over the signal.  If the signal is constant, then every frame will have the same amplitude, and none will be sufficiently below the reference to trigger the trim.

The easiest workaround here would be to use an explicit value for `ref`.  As noted above, the default is to use `np.max` to dynamically adjust the reference point based on the peak of the signal; we implemented it this way by default for consistency with other parts of the package involving decibel scaling.

**Comment by bmcfee** [comment]
I'd prefer to not introduce magic numbers, and leave the code as is. However, i agree that the documentation should be expanded to cover this point.

**Comment by giamic** [comment]
I understand your point, magic numbers are always a bit tricky and can lead to more unexpected behaviours down the line.

However, I have checked the source code and there is a clear expectation that  a signal containing only zeros should give an empty array in output. See [line 510](https://github.com/librosa/librosa/blob/8dae20c66353190749486abf6b332d93c4ab2b46/librosa/effects.py#L510) and following, especially the comment on line 530. One could introduce special cases to handle silent audio files, either inside the `trim` function or, probably more elegantly and more correctly, inside `_signal_to_frame_nonsilent`.

**Comment by bmcfee** [comment]
> I have checked the source code and there is a clear expectation that a signal containing only zeros should give an empty array in output. See [line 510](https://github.com/librosa/librosa/blob/8dae20c66353190749486abf6b332d93c4ab2b46/librosa/effects.py#L510) and following, especially the comment on line 530. One could introduce special cases to handle silent audio files, either inside the `trim` function or, probably more elegantly and more correctly, inside `_signal_to_frame_nonsilent`.

I think the comment at line 530 is perhaps misleading.  It's referring to "zeros" as detected points above the threshold, not zeros as in sample / amplitude values.  The underlying logic is to carve the signal into frames, mark each frame that's sufficiently loud as 1 and other frames as 0, then discard the leading and trailing 0 frames.
