### ISSUE TITLE
Fix strongly hardcoded BPM range for tempograms

### ISSUE THREAD

**Issue by th0ger** [librosa/librosa#1805]
**Is your feature request related to a problem? Please describe.**
Spend hours trying to produce proper tempograms with BPM ~ 550. The BPM-axis seems locked to around (16, 512).

Finally found [this](https://github.com/librosa/librosa/blob/main/librosa/display.py#L1368) being called by `specshow`:

    elif ax_type in ["tempo", "fourier_tempo"]:
        mode = "log"
        kwargs[base] = 2
        limit(16, 480)

**Describe the solution you'd like**
1. Document this hardcoded "feature" in `tempogram`/`tempogram_fourier` and/or `specshow`.
2. Make the `limit(...)` adjustable or add a note in the documentation on below workaround.

https://github.com/librosa/librosa/blob/main/librosa/display.py#L1368

**Describe alternatives you've considered**
Calling `ax[1].set_ylim(auto=True)` or `ax[1].set_ylim(8, 1024)` after `specshow` fixes the axis.

**Comment by bmcfee** [comment]
I believe this is only an issue for tempogram display, not the feature calculation. But yeah, we should expand the api to expose the min and max tempo parameters.
