### ISSUE TITLE
Enhance Docs: Copy button for code snippets

### ISSUE THREAD

**Issue by stefan-balke** [librosa/librosa#1807]
Hi everybody,

one thing that "bugged" me for some time is copying code examples from the docs.
I always remove the ">>>>" manually.
However, I have seen in other docs that they have a copy button.
I am not an expert on Sphinx and the templates but there is a little plugin called "Sphinx-copybutton" which does exactly this.
If this is accepted, I would volunteer in trying out this extension (and maybe others have better recommendations) on the librosa docs. 

What do others think? Are there better alternatives?

Best,
Stefan

**Comment by bmcfee** [comment]
This sounds good to me. 

@danagilliann - do you want to take a crack at this, since you're already in the weeds of the doc build?

**Comment by bmcfee** [comment]
@stefan-balke this turned out to be super easy, and applies retroactively to old version builds as well.  Thanks for the suggestion.
