### ISSUE TITLE
effects.trim:  top_db can be negative? doc says top_db is a number > 0.

### ISSUE THREAD

**Issue by Qubitium** [librosa/librosa#1809]
**Describe the bug**

While trying to figure out why efffects.trim is failing to trim silence I came across an old issue on same topic which had reference working code which I confirmed worked in my case of:

`librosa.effects.trim(audio, top_db=-10, ref=0.0173, frame_length=512, hop_length=1)`

Ref an older issue:
https://github.com/librosa/librosa/issues/1445

This code snippet actually works and solved my issue but I am scratching my head on how this works while doc is saying top_db should never be negative. 

So is doc wrong or incomplete?

**Expected behavior**

Crash and burn? =) The documentation explicitly says top_db is float > 0

documentation:

```
def trim(
    y: np.ndarray,
    *,
    top_db: float = 60,
    ref: Union[float, Callable] = np.max,
    frame_length: int = 2048,
    hop_length: int = 512,
    aggregate: Callable = np.max,
) -> Tuple[np.ndarray, np.ndarray]:
    """Trim leading and trailing silence from an audio signal.

    Parameters
    ----------
    y : np.ndarray, shape=(..., n)
        Audio signal. Multi-channel is supported.
    top_db : number > 0
        The threshold (in decibels) below reference to consider as
        silence
```

**Software versions**

Latest librosa

**Comment by bmcfee** [comment]
7 months with no comment.  I'll make the executive call to leave the code as is, but revise the documentation to not imply positive `top_db`.
