### ISSUE TITLE
<stdin>:1: UserWarning: PySoundFile failed. Trying audioread instead.

### ISSUE THREAD

**Issue by apiszcz** [librosa/librosa#1817]
librosa 0.10.1

Can this warning be eliminated?

```
test.py:153: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(ipath, sr=None)
lib/python3.11/site-packages/librosa/core/audio.py:183: FutureWarning: librosa.core.audio.__audioread_load
        Deprecated as of librosa version 0.10.0.
        It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
```

**Comment by bmcfee** [comment]
Please refer to the documentation section on io and audio formats.

This warning occurs when the file you're trying to load is not supported by soundfile.

**Comment by apiszcz** [comment]
the file type is aac, it appears ffmpeg is available? is it possible to request or specify that be used as a first attempt?

>>> audioread.available_backends()
[<class 'audioread.rawread.RawAudioFile'>, <class 'audioread.ffdec.FFmpegAudioFile'>]

**Comment by bmcfee** [comment]
If you know that you want to use audioread and not soundfile, you can use audioread directly, and pass the reader object into librosa.load instead of the file path.

**Comment by apiszcz** [comment]
Thank you.
I tried that and decided on ffmpeg writing wav, avoiding aac.
