### ISSUE TITLE
Cannot save stereo file

### ISSUE THREAD

**Issue by YoshioKobayashi** [librosa/librosa#1818]
**Versions*
Python: 3.7
Soundfile: 0.12.1
librosa: 0.10.1

**Describe the bug**
Opening a WAV File (16Bit, Stereo) file and then trying to save it with soundfile.write() fails.
Soundfile tries to access the channels via array.shape[1], while we are having them in shape[0].

```
def write(...)
...
    data = np.asarray(data)
    if data.ndim == 1:
        channels = 1
    else:
        channels = data.shape[1]
...
```

**To Reproduce**

[Piano C1.zip](https://github.com/librosa/librosa/files/14556458/Piano.C1.zip)

```
self.lrY, self.lrSR = self.librosa.load(self.Filename, sr=self.SampleRate, mono=False)
soundfile.write("test.wav", self.lrY, self.SampleRate, 'PCM_24')
```

Leads to:
soundfile.LibsndfileError: Error opening 'test.wav': Format not recognised.

**Expected behavior**
Not crashing.

**Comment by bmcfee** [comment]
> soundfile.LibsndfileError: Error opening 'test.wav': Format not recognised.

This look like a soundfile issue, not a librosa issue.  You should make sure that your soundfile build supports the sub-type you're requesting https://python-soundfile.readthedocs.io/en/0.11.0/#soundfile.available_subtypes

Also note that librosa uses the trailing dimension for sample index, while soundfile uses the leading dimension, so you may need to transpose the sample array (`self.lrY.T`) to make things work here.

**Comment by bmcfee** [comment]
> you may need to transpose the sample array (`self.lrY.T`) to make things work here.

Tested locally, confirmed that this is indeed the problem.  Soundfile's error message is not the most informative thing here, but I don't think there's anything else to be done so I'll close this out.
