### ISSUE TITLE
Numpy 2.0 compatibility

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#1831]
This is a place-holder issue to verify compatibility with numpy 2.0.

At present, we're unable to evaluate this due to intermediate dependency incompatibilities (sklearn, numba, soundfile, etc).  But as soon as those are sufficiently resolved, we should get on with verifying that everything works.

Linking upstream issues here so we can keep track:

- https://github.com/numpy/numpy/issues/26191 tracks general ecosystem compatibility and minimum versions

From what's currently listed there, we're looking at the following:

- :ballot_box_with_check: scipy 1.13.0
- :ballot_box_with_check: matplotlib 3.8.4
- :ballot_box_with_check: scikit-learn 1.4.2 https://github.com/scikit-learn/scikit-learn/issues/27075
- :ballot_box_with_check: numba 0.60 https://github.com/numba/numba/pull/9466
- :ballot_box_with_check: : soundfile ??? (but I expect this to work)
- :ballot_box_with_check: soxr-python 0.4.0 https://github.com/dofuuz/python-soxr/issues/28

**Comment by bmcfee** [comment]
I'm tagging this onto a 0.11.0 milestone, which we may or may not do before 1.0.  I'm leaving the possibility open in case we do need to change anything to support numpy 2.0 in a breaking way.  I can imagine there's potential for stacking up a bunch of other version bumps (including Python), and that seems appropriate for a milestone release if it takes substantial effort to get a working environment spec.

**Comment by glemaitre** [comment]
FYI: scikit-learn 1.4.2 on PyPI should be compatible and was released.

**Comment by bmcfee** [comment]
Excellent, thanks for the update!

**Comment by bmcfee** [comment]
@hagenw yes, soxr 0.4.0 is not yet released, so there's nothing we can do here.

**Comment by hagenw** [comment]
For testing things, you could already install with:

```bash
$ pip install "soxr==0.4.0b1"
```

which solved the error for me.

**Comment by hagenw** [comment]
![image](https://github.com/user-attachments/assets/69bb72b4-fd43-455f-b6e6-0f53df2b4be9)

I did not encounter any problems with `soundfile` and `numpy` 2.0 so far.

**Comment by bmcfee** [comment]
It sounds like we're unblocked!  I'm currently traveling, but will look into setting up a numpy 2.0 test environment next week toward a 0.11 release (if needed).

**Comment by bmcfee** [comment]
PR #1860 is now running tests on numpy 2.0.  The library itself required no modifications, though some of the test code had to be lightly adapted to account for expired deprecations.

**Comment by MonolithFoundation** [comment]
But librosa need numba, this lib will reinstall everything ....... Please help?
