### ISSUE TITLE
Allow definition of middle C "note" for midi number to note conversion

### ISSUE THREAD

**Issue by electricazimuth** [librosa/librosa#1836]
**Is your feature request related to a problem? Please describe.**
When calling librosa.midi_to_note the note returned is in the "Roland" standard where midi note 0 = C-1 and middle C (note 60) is considered C4.

There is an equally common alternate definition, the "Yamaha" standard where midi note 0 = C-2 and middle C (note 60) is considered C3.

Most DAWs export midi as Yamaha standard so if that data is sent to librosa.midi_to_note it get converted "incorrectly" and then if that note value is used in some another system which uses the Yamaha standard it will be off by an octave.

**Describe the solution you'd like**
Ideally some setting to allow user control of what middle C is called, this could be at a system level or even on a per call - something like midi_to_note(middle_c=C4)

**Comment by bmcfee** [comment]
There are a few issues tangled up in this question that should be clarified.  However, to cut to the chase, I think the answer is going to be that we should leave it as is.

---

Our unit converters are designed to be interoperable. Specifically, midi_to_note is a wrapper around two more fundamental converters: midi_to_hz and hz_to_note.

- `midi_to_hz` does what it says on the tin: converts midi pitch numbers (0, 1, 2,  ..., 127) to frequencies in Hz.  This conversion is well defined by the [MIDI tuning specification](https://midi.org/midi-tuning-updated-specification) (where note 0 maps to 8.1758 Hz, equivalently 69 maps to A440) and is not something we can or should change.
- `hz_to_note` similarly does what it says: converts from a frequency (in Hz) to a pitch string.  We implement this conversion according to [scientific pitch notation](https://en.wikipedia.org/wiki/Scientific_pitch_notation), and this conversion is entirely independent of MIDI.


It's worth stressing that our notation converter is not dependent on midi, and we do use it all over the place for converting arbitrary continuous frequencies (not just 12TET @ A440 midi integers).  This is why we went with SPN in the first place.

It so happens that Roland's notation agrees with SPN, and Yamaha's notation does not.  I don't think this has anything to do with the midi←→Hz conversion though, and is entirely a function of how they decided to label frequencies (not midi numbers, which unambiguously map to frequencies).

Now, to implement what you're describing, we'd need to modify the `hz_to_note` converter to allow for different standards than just SPN.  I'm extremely hesitant to do this kind of thing though, as it seems quite easy to misuse especially in the reverse direction (note_to_hz): if given a string "C3", what frequency should it be?  A user would have to know (and remember) to pass in the note standard at every call site to the conversion.  This might not sound like much of a burden when used directly, but it would also mean threading this parameter through all functions that rely on conversion, including things like `display.specshow`, various filter constructors (cqt), and so on.

My recommendation here is that if you know your data is coming in a non-standard (ie SPN) format, convert it before going into librosa functions.  I could envision adding some helper routines to adjust yamaha-style notation to SPN and vice versa (basically some simple regex shortcuts), but this seems pretty niche IMO.  Would something like that be useful?

**Comment by electricazimuth** [comment]
Thanks for the reply and overview, I wasn't aware of the SPN standard and I agree it is best to leave it as it is.

It's a trivial ( - 12) fix in my code once I'd realised the "standard" that was being displayed in Logic Audio, I can "fix" it in Logic by changing it's convention for middle C, but then that disagrees with the synth setups and other muscians start to raise issue. I thank Yamaha for their foresight when choosing their different path 40 years ago that has consumed too much of my (and your time) that it ever should and made.

I feel obliged to drop this in
[![Standards](https://imgs.xkcd.com/comics/standards.png)](https://xkcd.com/927/)
