### ISSUE TITLE
No module named 'samplerate'

### ISSUE THREAD

**Issue by todochenxi** [librosa/librosa#1840]
***BEFORE POSTING A BUG REPORT*** Please look through [existing issues (both open and closed)](https://github.com/librosa/librosa/issues?q=is%3Aissue) to see if it's already been reported or fixed!

**Describe the bug**

No module named 'samplerate'

This error is lazily reported, having originally occured in
  File /home/developer/anaconda3/envs/roleplay/lib/python3.10/site-packages/librosa-0.10.2.post1-py3.10.egg/librosa/core/audio.py, line 32, in <module>

----> samplerate = lazy.load("samplerate")
**To Reproduce**

**Comment by todochenxi** [comment]
I have solved this problem by compiling the source code
1. download samplerate source code
https://pypi.org/project/samplerate/#files
2. tar -zxvf samplerate....
3. cd samplerate 
pip install -r requirements.txt
sudo apt-get install cmake
python setup.py install
4. import samplerate

**Comment by bmcfee** [comment]
This is behaving as expected - `samplerate` is an optional dependency, so it is not automatically installed when you install librosa.  If you want to use it, you need to install it manually.

**Comment by todochenxi** [comment]
Thanks for your reply

**Comment by Tuesdaythe13th** [comment]
I uploaded this to Project IDX today. Im creating an app thats like
Notebook LLM for your voicenotes, and im not sure how to work with all
these google ai studio IDEs. I uploaded the repository directly to Project
IDX and now i dont know how to test it as a web app or make an interface
for it and could use any direction you got!




———————————————————————————————————-
𝔗𝔥𝔢 𝔠𝔬𝔫𝔱𝔢𝔫𝔱𝔰 𝔬𝔣 𝔱𝔥𝔦𝔰 𝔢𝔪𝔞𝔦𝔩 𝔪𝔢𝔰𝔰𝔞𝔤𝔢 𝔞𝔫𝔡
𝔞𝔫𝔶 𝔞𝔱𝔱𝔞𝔠𝔥𝔪𝔢𝔫𝔱𝔰 𝔞𝔯𝔢 𝔦𝔫𝔱𝔢𝔫𝔡𝔢𝔡 𝔰𝔬𝔩𝔢𝔩𝔶 𝔣𝔬𝔯
𝔱𝔥𝔢 𝔞𝔡𝔡𝔯𝔢𝔰𝔰𝔢𝔢(𝔰) 𝔞𝔫𝔡 𝔪𝔞𝔶 𝔠𝔬𝔫𝔱𝔞𝔦𝔫
𝔠𝔬𝔫𝔣𝔦𝔡𝔢𝔫𝔱𝔦𝔞𝔩 𝔞𝔫𝔡/𝔬𝔯 𝔭𝔯𝔦𝔳𝔦𝔩𝔢𝔤𝔢𝔡
𝔦𝔫𝔣𝔬𝔯𝔪𝔞𝔱𝔦𝔬𝔫 𝔞𝔫𝔡 𝔪𝔞𝔶 𝔟𝔢 𝔩𝔢𝔤𝔞𝔩𝔩𝔶 𝔭𝔯𝔬𝔱𝔢𝔠𝔱𝔢𝔡
𝔣𝔯𝔬𝔪 𝔡𝔦𝔰𝔠𝔩𝔬𝔰𝔲𝔯𝔢. ℑ𝔣 𝔶𝔬𝔲 𝔞𝔯𝔢 𝔫𝔬𝔱 𝔱𝔥𝔢
𝔦𝔫𝔱𝔢𝔫𝔡𝔢𝔡 𝔯𝔢𝔠𝔦𝔭𝔦𝔢𝔫𝔱 𝔬𝔣 𝔱𝔥𝔦𝔰 𝔪𝔢𝔰𝔰𝔞𝔤𝔢 𝔬𝔯
𝔱𝔥𝔢𝔦𝔯 𝔞𝔤𝔢𝔫𝔱, 𝔬𝔯 𝔦𝔣 𝔱𝔥𝔦𝔰 𝔪𝔢𝔰𝔰𝔞𝔤𝔢 𝔥𝔞𝔰 𝔟𝔢𝔢𝔫
𝔞𝔡𝔡𝔯𝔢𝔰𝔰𝔢𝔡 𝔱𝔬 𝔶𝔬𝔲 𝔦𝔫 𝔢𝔯𝔯𝔬𝔯, 𝔭𝔩𝔢𝔞𝔰𝔢
𝔦𝔪𝔪𝔢𝔡𝔦𝔞𝔱𝔢𝔩𝔶 𝔞𝔩𝔢𝔯𝔱 𝔱𝔥𝔢 𝔰𝔢𝔫𝔡𝔢𝔯 𝔟𝔶 𝔯𝔢𝔭𝔩𝔶
𝔢𝔪𝔞𝔦𝔩 𝔞𝔫𝔡 𝔱𝔥𝔢𝔫 𝔡𝔢𝔩𝔢𝔱𝔢 𝔱𝔥𝔦𝔰 𝔪𝔢𝔰𝔰𝔞𝔤𝔢 𝔞𝔫𝔡
𝔞𝔫𝔶 𝔞𝔱𝔱𝔞𝔠𝔥𝔪𝔢𝔫𝔱𝔰. ℑ𝔣 𝔶𝔬𝔲 𝔞𝔯𝔢 𝔫𝔬𝔱 𝔱𝔥𝔢
𝔦𝔫𝔱𝔢𝔫𝔡𝔢𝔡 𝔯𝔢𝔠𝔦𝔭𝔦𝔢𝔫𝔱, 𝔶𝔬𝔲 𝔞𝔯𝔢 𝔥𝔢𝔯𝔢𝔟𝔶
𝔫𝔬𝔱𝔦𝔣𝔦𝔢𝔡 𝔱𝔥𝔞𝔱 𝔞𝔫𝔶 𝔲𝔰𝔢, 𝔡𝔦𝔰𝔰𝔢𝔪𝔦𝔫𝔞𝔱𝔦𝔬𝔫,
𝔠𝔬𝔭𝔶𝔦𝔫𝔤, 𝔬𝔯 𝔰𝔱𝔬𝔯𝔞𝔤𝔢 𝔬𝔣 𝔱𝔥𝔦𝔰 𝔪𝔢𝔰𝔰𝔞𝔤𝔢 𝔬𝔯
𝔦𝔱𝔰 𝔞𝔱𝔱𝔞𝔠𝔥𝔪𝔢𝔫𝔱𝔰 𝔦𝔰 𝔰𝔱𝔯𝔦𝔠𝔱𝔩𝔶 𝔭𝔯𝔬𝔥𝔦𝔟𝔦𝔱𝔢𝔡.
