### ISSUE TITLE
RVC conflicts with a variety of ASIO drivers from various vendors

### ISSUE THREAD

**Issue by epictoasty** [librosa/librosa#1841]
***BEFORE POSTING A BUG REPORT*** Please look through [existing issues (both open and closed)](https://github.com/librosa/librosa/issues?q=is%3Aissue) to see if it's already been reported or fixed!

**Describe the bug**
When launching "start_http.bat", a console window opens, a grey loading dialog flashes across the screen twice, and then the console window closes. This behavior occurs with each of the 4 different versions I downloaded. It wasn't until I uninstalled every ASIO driver I had installed (Steinberg, Steinberg Low Latency, Magix ASIO, ASIO4All) that "start_http" actually succeeded in running.

Having read previous tickets with similar issues, I did try running "start http.bat" from powershell and command prompt, but neither of them displayed anything more than the initual launch script inside of start http.bat.

**To Reproduce**
Install Magix ASIO, Steinberg ASIO, ASIO4ALL, or Steinberg Low Latency ASIO, then try to launch RVC

**Additional context**
So if there was a config file or utility that allowed me to select which audio driver or device to use before installation, I could avoid this issue manually. As a music producer, I find it necessary to have a variety of ASIO drivers installed on my computer, and needing to remove them just to run RVC is a bit of an issue.

**Comment by bmcfee** [comment]
Sorry, but what is RVC?

**Comment by epictoasty** [comment]
Realtime Voice Changer...

Wait why is this posted to Librosa?

**Comment by epictoasty** [comment]
Feel free to delete this. I'm very confused. I clicked "new issue" when
looking at a previous issue for the software I'm trying to report this bug
for, but...
