### ISSUE TITLE
Problem with librosa library when parsing audio files

### ISSUE THREAD

**Issue by slvm972** [librosa/librosa#1846]
Problem Description: When trying to use the librosa library to analyze an audio file, an error occurred due to an incompatibility with the numpy library. The error occurs when the following lines of code are executed:
import librosa
audio, sr = librosa.load('path_to_audio_file.mp3')
tempo, beat_frames = librosa.beat.beat_track(y=audio, sr=sr)
chroma_stft = librosa.feature.chroma_stft(y=audio, sr=sr)
mfcc = librosa.feature.mfcc(y=audio, sr=sr)
spectral_contrast = librosa.feature.spectral_contrast(y=audio, sr=sr)
Error message:
AttributeError: module 'numpy' has no attribute 'complex'
Context:
The error occurred in the context of loading and parsing an mp3 file to extract parameters such as tempo, chroma, MFCC, and spectral contrast.

Steps to reproduce:

Import the librosa library.
Load an audio file.
Attempt to extract audio parameters using librosa functions.
Environment:
The error occurred while using ChatGPT, which is embedded in the environment provided by OpenAI.

Sample code:
import librosa
import numpy as np

# Load the mp3 file
file_path = 'path_to_audio_file.mp3'
audio, sr = librosa.load(file_path)

# Analyze the tempo and beat
tempo, beat_frames = librosa.beat.beat_track(y=audio, sr=sr)

# Extract features: chroma, mfcc, and spectral contrast
chroma_stft = librosa.feature.chroma_stft(y=audio, sr=sr)
mfcc = librosa.feature.mfcc(y=audio, sr=sr)
spectral_contrast = librosa.feature.spectral_contrast(y=audio, sr=sr)

# Summarize some features
tempo, chroma_stft.mean(), mfcc.mean(), spectral_contrast.mean()
Additional information:
Please report that the issue may be related to outdated or incompatible library versions, and specify that the issue occurs in the environment provided by OpenAI.

You can submit this report to the librosa library GitHub page or through the OpenAI support channel if the issue is related to the ChatGPT integration.

If you have any further questions or need help, please let me know!

**Comment by bmcfee** [comment]
Sounds like you have an old version of librosa, but since you didn't fill out the issue form, there's no way to know for sure.
