### ISSUE TITLE
Error analyzing MP3 files using librosa

### ISSUE THREAD

**Issue by slava972** [librosa/librosa#1847]
**Description of the problem:**
Already several times I have encountered a failure and an error message when analyzing MP3 files using the librosa library. This problem has been ongoing for a long time.

**Steps to reproduce:**
1. I upload an MP3 file to the system.
2. I start analyzing the file using the librosa library.

**Expected result:**
Successful analysis of the MP3 file.

**Actual result:**
I receive a failure and an error message.

**Additional information:**
- The problem occurred on different browsers, different accounts, and different devices.
- The problem occurred with several files.
- The exact text of the error message was not saved.
- Library name: librosa

I would like to know when this issue will be fixed as it hinders my workflow.

Thank you.

**Comment by bmcfee** [comment]
> I receive a failure and an error message.

Please report the actual error message.

**Comment by bmcfee** [comment]
Closing this one out due to lack of specificity.  Please re-open if and when you can provide more information about the error you're seeing.
