### ISSUE TITLE
csr_matrix.H in scipy has been removed

### ISSUE THREAD

**Issue by takenori-y** [librosa/librosa#1849]
The new version of scipy (1.14) removed `csr_matrix.H`.
https://docs.scipy.org/doc/scipy-1.13.0/reference/generated/scipy.sparse.csr_matrix.H.html

Could you rewrite the following line?
https://github.com/librosa/librosa/blob/cd66e10edf5fad2e95267b8289463848d54c39b7/librosa/core/constantq.py#L711

**Comment by bmcfee** [comment]
Good catch - I'm not sure how we missed this deprecation in the last round of reviewing, but this should go into a quick point release.
