### ISSUE TITLE
librosa.util.normalize() used twice in Fast Mellin Transform example

### ISSUE THREAD

**Issue by dhunstack** [librosa/librosa#1855]
Is there any particular reason for using normalize() twice in this example?
I found it odd while going through the docs. This is not a bug, but maybe could be written in a better way.

https://github.com/librosa/librosa/blob/d0a12c87cdff715ffb8ac1c7383bba1031aa71e4/librosa/core/spectrum.py#L2211
https://github.com/librosa/librosa/blob/d0a12c87cdff715ffb8ac1c7383bba1031aa71e4/librosa/core/spectrum.py#L2213

**Comment by bmcfee** [comment]
Good catch - there shouldn't be two calls here. Probably this was just a bit of careless copy-paste when i put the example code in. It's not wrong per se, but it's also not as clear as it could be.

A pr to simplify this example would be most appreciated.

**Comment by dhunstack** [comment]
I pushed a PR for this. I haven't pushed to `librosa` before, let me know if I missed something
