### ISSUE TITLE
[Bug]: librosa.load in mac os

### ISSUE THREAD

**Issue by moon920110** [librosa/librosa#1861]
### Bug summary

Loading a wav file with librosa.load('filepath', sr=None) on Mac OS does not work for some wav files.
It returns empty list [].
Same wav file is loaded successfully on Windows system in the same code.
It happens randomly for some wav files. There are some working wav files.

I found that the binary function in the `SoundFile()._cdata_io()` function of the soundfile library (soundfile.py line 1353 in soundfile version 0.12.1) returns 0 frames for the wav files (only in Mac os, not in Windows).

I think the binary function (_soundfile._cffi_backend_FFI()) is not compatible with Mac OS in some dtypes.

I solve this problem by simply adding dtype='float64' in the librosa.load argument. 

Please check this problem.

### Code for reproduction

```Python
y, sr = librosa.load('your_music.wav', sr=None)
```

### Actual outcome

[]

### Expected outcome

[list of some float numbers...]

### Additional information

Adding dtype='float64' argument to fix this problem.

### Operating system

OS/X

### software versions

librosa==0.10.2
soundfile==0.12.1
Mac OS==Sonoma 14.5

### Installation

None

**Comment by bmcfee** [comment]
This sounds like a platform issue in soundfile / libsndfile, and not a librosa problem.  It's interesting that forcing the dtype fixes this for you, but I suggest to bring this issue over to https://github.com/bastibe/python-soundfile

**Comment by bmcfee** [comment]
Closing this out due to lack of activity (and high confidence that it's not a problem we can address).  Please reopen if necessary.
