### ISSUE TITLE
[Bug]: RuntimeError with numba caching in AWS Lambda using librosa

### ISSUE THREAD

**Issue by Manishthakur2503** [librosa/librosa#1868]
### Bug summary

I created one docker image and pushed the image to AWS ECR and then using that created a lambda function and when trying to test the lambda function I'm encountering a RuntimeError related to numba caching when using librosa . The error occurs during the Lambda function execution, indicating issues with function caching in the librosa library.

### Code for reproduction

```Python
# Use the final stage directly
FROM python:3.10-slim

# Install OS-level dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libsndfile1 \
        libgl1-mesa-glx \
        ffmpeg \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy the application files
COPY . .

# Install Python dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
RUN chmod -R 777 /app

# Set runtime interface client as the default command for the container runtime
ENTRYPOINT [ "python", "-m", "awslambdaric" ]

# Pass the name of the function handler as an argument to the runtime
CMD [ "lambda_function.handler" ]
```
And this is my handler function in lambda_function.py file 
```
def lambda_handler(event, context):
    filename = event.get('filename')
    logger.info(f"Filename: {filename}")

    if not filename:
        return {'statusCode': 400, 'body': json.dumps({'error': 'filename is required'})}

    file_path = os.path.join('/temp', filename)  # Use /tmp for temporary storage

    # Validate the file extension
    file_extension = os.path.splitext(filename)[1].lower()
    if file_extension not in VALID_VIDEO_EXTENSIONS:
        return {'statusCode': 400, 'body': json.dumps({'error': f'Unsupported file format: {file_extension}. Please provide a valid video file.'})}

    # Download the file from S3
    try:
        s3.download_file(AWS_COURSE_ROLEPLAY_STORE_BUCKET_NAME, filename, file_path)
        logger.info(f"Downloaded file to {file_path}")
    except Exception as e:
        logger.error(f"Error downloading file: {str(e)}")
        return {'statusCode': 500, 'body': json.dumps({'error': 'Failed to download file from S3'})}

    # Process the file
    try:
        logger.info("Processing file for emotion prediction.")
        prediction = face_predict.predict(file_path, video_mode=True)
        logger.info(f"Prediction result: {prediction}")

        # Clean up by removing the file
        if os.path.exists(file_path):
            logger.info("Removing temporary file")
            os.remove(file_path)

        return {'statusCode': 200, 'body': json.dumps({'prediction': prediction})}

    except Exception as e:
        logger.error(f"Error occurred: {str(e)}")
        if os.path.exists(file_path):
            logger.info("Removing temporary file due to error")
            os.remove(file_path)
        return {'statusCode': 500, 'body': json.dumps({'error': str(e)})}
```

### Actual outcome

[ERROR] RuntimeError: cannot cache function '__shear_dense': no locator available for file '/usr/local/lib/python3.10/site-packages/librosa/util/utils.py'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/lambda_function.py", line 4, in <module>
    import source.face_emotion_utils.predict as face_predict
  File "/app/source/face_emotion_utils/predict.py", line 5, in <module>
    import source.audio_analysis_utils.utils as audio_utils
  File "/app/source/audio_analysis_utils/utils.py", line 7, in <module>
    import librosa
  File "/usr/local/lib/python3.10/site-packages/librosa/__init__.py", line 209, in <module>
    from . import core
  File "/usr/local/lib/python3.10/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.10/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/usr/local/lib/python3.10/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/usr/local/lib/python3.10/site-packages/librosa/util/__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.10/site-packages/librosa/util/utils.py", line 1879, in <module>
    def __shear_dense(X, *, factor=+1, axis=-1):
  File "/usr/local/lib/python3.10/site-packages/numba/core/decorators.py", line 225, in wrapper
    disp.enable_caching()
  File "/usr/local/lib/python3.10/site-packages/numba/core/dispatcher.py", line 808, in enable_caching
    self._cache = FunctionCache(self.py_func)
  File "/usr/local/lib/python3.10/site-packages/numba/core/caching.py", line 601, in __init__
    self._impl = self._impl_class(py_func)
  File "/usr/local/lib/python3.10/site-packages/numba/core/caching.py", line 337, in __init__
    raise RuntimeError("cannot cache function %r: no locator available "

### Expected outcome

The Lambda function should process the audio file using librosa without encountering a RuntimeError. Specifically, it should be able to load the file and perform operations without caching issues related to numba.

### Operating system

AWS Lambda environment (Linux-based)

### software versions

My requirement.txt is : 
```
albumentations==1.3.0
ffmpeg==1.4
ffmpeg_python==0.2.0
imutils==0.5.4
ipython==8.9.0
librosa==0.9.2
matplotlib==3.6.2
mediapipe==0.10.14
more_itertools==9.0.0
moviepy==1.0.3
nltk==3.8.1
noisereduce==2.0.1
numpy==1.23.4
opencv_python==4.5.5.62
pandas==1.5.1
Pillow==9.4.0
psutil==5.9.4
pytest==7.2.1
pytube==12.1.2
regex==2022.10.31
scikit_learn==1.2.1
scipy==1.10.0
setuptools==65.5.0
spacy==3.5.0
torch
tqdm==4.64.1
transformers==4.25.1
python-vlc==3.0.18121
hyperopt==0.2.7
flask
torchvision
en-core-web-lg @ https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.5.0/en_core_web_lg-3.5.0-py3-none-any.whl#sha256=c8ac64840c1eb3e3ca7bd38bd1e1c48fb0faeb2449d54d01d5ce629af4595775
gunicorn
memory_profiler
boto3
awslambdaric
```

### Installation

pip

**Comment by bmcfee** [comment]
This is really more of a numba issue than a librosa issue, as it comes down to JIT compilation.

Have you tried this without using lambda functions, ie defining an equivalent function using `def`?  

If it still fails without lambdas, then I suspect it might be due to the location of the numba cache as documented here: https://librosa.org/doc/latest/troubleshooting.html#import-librosa-hangs-indefinitely

**Comment by Manishthakur2503** [comment]
@bmcfee first of all thanks for your response.

I already tried this without lambda function that way it was working .

**Comment by bmcfee** [comment]
> I already tried this without lambda function that way it was working .

That seems like the obvious short-term fix.  Longer term, this is definitely a numba issue and not a librosa issue, so I suggest to try to cook up a minimal example that triggers this behavior and report the bug over there.

I also noticed that you didn't report the installed version of numba, and that your librosa install is quite old (0.9.2, 4 versions out of date).  So perhaps try updating to the most recent versions of everything to ensure that this still occurs before pursuing further.
