### ISSUE TITLE
[Bug]: Unable to install on Macos Sonoma

### ISSUE THREAD

**Issue by Youjin1985** [librosa/librosa#1884]
### Bug summary

librosa requires llvmlite
llvmlite requires llmv@9 or llvm@10
brew only can install llvm@11 or above

### Code for reproduction

```Python
pip install librosa
```

### Actual outcome

RuntimeError: Building llvmlite requires LLVM 10.0.x or 9.0.x, got '19.1.3'. Be sure to set LLVM_CONFIG to the right executable path.

### Expected outcome

expected compatibility

### Operating system

OS/x

### software versions

macOS-14.6.1-arm64-arm-64bit
Python 3.11.7 (main, Feb  4 2024, 13:15:25) [Clang 15.0.0 (clang-1500.1.0.2.5)]
NumPy 2.1.2
SciPy 1.14.1

### Installation

None

**Comment by bmcfee** [comment]
This is out of our control here. The solution would be to either get brew to update their packages, or switch to an alternative package system (ie conda). I generally recommend the latter.

**Comment by Youjin1985** [comment]
> This is out of our control here. The solution would be to either get brew to update their packages, or switch to an alternative package system (ie conda). I generally recommend the latter.

Yes, it seems to work only with conda, because it provides all required depencencies

**Comment by john-sandall** [comment]
FWIW if anyone else come across this, I have librosa working fine on macOS Sequoia using Poetry:
- Python 3.12.9
- `brew install llvm` gave me llvm 19.1.7, I had to manually add the path to my .zshrc e.g. `export PATH="/opt/homebrew/opt/llvm/bin:$PATH"`
- I ran `poetry add llvmlite@latest` which gave me llvmlite 0.44.0
- I ran `poetry add librosa` which gave me librosa 0.10.2.post1

**Comment by haibo-looki** [comment]
For anyone still running into this issue — I was able to successfully install `librosa` on macOS Sequoia using Poetry with the following setup:

```
poetry add "llvmlite@^0.34"  # Compatible with LLVM 20.x
poetry add "numpy@^2.2"      # Must be <2.3 to work with the latest version of numba (^0.61.2)
poetry add "numba@latest"  
poetry add "librosa@latest"
```
