### ISSUE TITLE
[Bug]: Can't load and play flac file

### ISSUE THREAD

**Issue by brucenielson** [librosa/librosa#1888]
### Bug summary

Here is my code:

import librosa

y, sr = librosa.load("facebook_mms-tts-eng_test_sentence.flac")

Attached file has a 'json' extension. But just change it to be 'flac' instead.
[facebook_mms-tts-eng_test_sentence.json](https://github.com/user-attachments/files/18032411/facebook_mms-tts-eng_test_sentence.json)

Error:

ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.

This is a 96k file.

### Code for reproduction

```Python
import librosa

y, sr = librosa.load("facebook_mms-tts-eng_test_sentence.flac")

Attached file has a 'json' extension. But just change it to be 'flac' instead.
[facebook_mms-tts-eng_test_sentence.json](https://github.com/user-attachments/files/18032411/facebook_mms-tts-eng_test_sentence.json)
```

### Actual outcome

ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.

### Expected outcome

Should play the file

### Operating system

Windows

### software versions

Python 3.11

### Installation

None

**Comment by lostanlen** [comment]
I can reprduce the problem. Here's the traceback
(first, download the pseudo-JSON file and rename it back to a FLAC extension. confirm that VLC can play this FLAC file)

```
Python 3.10.14 (main, May  6 2024, 14:47:20) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import librosa
>>> librosa.__version__
'0.10.2.post1'
>>> y, sr = librosa.load('facebook_mms-tts-eng_test_sentence.flac')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/miniconda3/envs/murenn/lib/python3.10/site-packages/librosa/core/audio.py", line 176, in load
    y, sr_native = __soundfile_load(path, offset, duration, dtype)
  File "/Users/user/miniconda3/envs/murenn/lib/python3.10/site-packages/librosa/core/audio.py", line 222, in __soundfile_load
    y = sf_desc.read(frames=frame_duration, dtype=dtype, always_2d=False).T
  File "/Users/user/miniconda3/envs/murenn/lib/python3.10/site-packages/soundfile.py", line 891, in read
    out = self._create_empty_array(frames, always_2d, dtype)
  File "/Users/user/miniconda3/envs/murenn/lib/python3.10/site-packages/soundfile.py", line 1323, in _create_empty_array
    return np.empty(shape, dtype, order='C')
ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.
```

**Comment by bmcfee** [comment]
This appears to be a problem upstream of us, either in libsndfile or the soundfile python package. I expect that loading directly with soundfile instead of the librosa wrapper will exhibit the same behavior, and the bug report should be migrated upstream.

**Comment by brucenielson** [comment]
I have confirmed you can get the same error in sound file.

**Comment by bmcfee** [comment]
Thanks for confirming; I'll close this out.  Hope it gets fixed!
