### ISSUE TITLE
[ENH]: Add supoort for python 13.0

### ISSUE THREAD

**Issue by baldbuffalo** [librosa/librosa#1889]
### Problem

current numba version being installed with librosa is 0.51.0 

### Proposed solution

chnage numba from 0.51.0 to 0.61.0rc1 which supports python 13.0

**Comment by jarey** [comment]
@baldbuffalo Librosa latest version already supports consuming numba 0.61.0rc1 since the package only restricts the lower bound interval:
https://github.com/librosa/librosa/blob/main/setup.cfg#L71

**Comment by bmcfee** [comment]
@jarey is correct.  We could at some point add python 3.13 to the package spec (once all upstream dependencies have updated), but there's no need to bump the minimum numba at this point.
