### ISSUE TITLE
Setting threshold for trimming detected beats

### ISSUE THREAD

**Issue by urinieto** [librosa/librosa#205]
I think it would be useful to parametrize the weight of the threshold in the `__trim_beats` function ([here](https://github.com/bmcfee/librosa/blob/master/librosa/beat.py#L428)).

Thus, users could potentially select the "strength" of the beats they want to trim. Or maybe `librosa` already does that and I just couldn't find it?

**Comment by bmcfee** [comment]
Right now, the best way to do that is to disable trimming and then do it manually after the fact.

The trimming logic is already a little heuristic imo, it might be better to make trimming a pluggable function?  That way, you could toss in your own threshold calculations, or set it to `None` to disable.

Since that would constitute a rather severe API change, it will have to wait until the next major revision.

**Comment by urinieto** [comment]
> The trimming logic is already a little heuristic imo, it might be better to make trimming a pluggable function? That way, you could toss in your own threshold calculations, or set it to None to disable.

Yes, that sounds good to me. Also, I didn't expect this to change in the current version, just something to think of for future releases. 

Thanks titan.

**Comment by bmcfee** [comment]
![image](https://user-images.githubusercontent.com/1190540/60288733-da0fa500-98e2-11e9-8086-60d88f11ecdb.png)

I think a reasonable solution here is to promote `__trim_beats` to a more generic utility function that:

1. smooths a signal
2. thresholds below rms value
3. trims leading and trailing silence

where the API allows more flexibility on these steps than the current implementation.  Then, the beat tracker can keep its own present behavior, but you can always disable trimming and do it manually as follows:

```python
onset_envelope = ...
tempo, beats = librosa.beat.beat_track(..., trim=False)
beats = librosa.util.trim(beats, onset_envelope, threshold=..., window='hann', win_length=5, ...)
```

It's a little cumbersome, but probably the best trade-off in terms of preserving existing behavior and supporting more flexible post-processing going forward.

**Comment by bmcfee** [comment]
Digging a bit into this, I think maybe we should just drop this issue.

The trimming function is pretty well entangled with the beat tracker's internal state variables, and it wouldn't be easy to extract that function as a simple post-processing step that can be applied post-hoc.

I think the best course of action here is what I originally suggested ... 4 years ago.  Any objections to closing this out?
