### ISSUE TITLE
Transfer ownership to an organization

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#240]
It's maybe a bit past the time that we should do this, but we should definitely do this.

**Comment by dpwe** [comment]
SGTM.  Let me know if you need any help identifying or talking to the
right people at an organization; I'm guessing NYU is the right choice?

  DAn.

**Comment by bmcfee** [comment]
Oh, I meant a github organization.  I'm thinking an org called "librosa" to house all related projects:
- librosa itself
- parameter optimization repo
- anything relating to distribution (eg, stuff to manage a conda channel #202 )
- higher-level libraries built on top of librosa, etc etc...

This way, they won't all live under `github.com/bmcfee`, thereby reducing our bus factor.

I'm open to naming suggestions for the org.

**Comment by dpwe** [comment]
librosa is fine by me.  The whole association to LabROSA is a bit
tangential at this point (I mean I feel a bit uncomfortable about the
glory that LabROSA might inherit from this, when it really all belongs
to you) but I think it's better to keep it as it is.

  DAn.

**Comment by stefan-balke** [comment]
Also, the repo is 550 MB big.
Couldn't we separate the test data and the examples in different repos?
This is no problem as long as the internet connection is stable.
When I was in China with an unstable connection, I wasn't able to clone the repo...

**Comment by bmcfee** [comment]
> Also, the repo is 550 MB big.
> Couldn't we separate the test data and the examples in different repos?

This issue has been brought up several times in the past.  At this point, removing the files from the main branch won't do anything to reduce the size of the repo, due to how git works.

Since cloning is a relatively infrequent activity, I'd rather just keep it as is, since it simplifies testing.


Unrelated: I've put a claim out on the `librosa` org, so migration can happen at any point now.  I'll probably wait until the current set of PRs are merged, just to keep things sane from a management perspective.

**Comment by stefan-balke** [comment]
> At this point, removing the files from the main branch won't do anything to reduce the size of the repo, due to how git works.

I haven't tried for librosa, but removing the history for a particular folder is totally possible.

**Comment by faroit** [comment]
You might want to look into [git lfs](https://git-lfs.github.com). This should work with travis as well. 

You could also split the existing unit tests into functional tests (pure python) and MATLAB compatibility tests which could use `oct2py` (in case the matlab code runs on octave) or `matlab_wrapper` to run the tests without the intermediate vectors if available on local machines. For travis obviously only `oct2py` or git lfs would work. 

I personally don't see the benefit of designing tests a against static MATLAB generated test vectors. Many scientific python users now are not using MATALB anymore and therefore do not care much about bit-exact compatible output ;-)
