### ISSUE TITLE
A logo?

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#278]
It seems like all the cool projects have a logo.  We should get one too.

**Comment by ruohoruotsi** [comment]
+1, a visual identity is a good idea! Especially for an ass-kicking library like this!

**Comment by CourtCourtGT** [comment]
<img width="224" alt="screenshot 2016-01-18 19 22 54" src="https://cloud.githubusercontent.com/assets/16710597/12406205/e98d5854-be18-11e5-9519-b194c238315b.png">

Let me know if any of these would appeal to you guys and I'll file a pull request with the appropriate files

**Comment by justinsalamon** [comment]
So here's an idea:
![librosa_logo](https://cloud.githubusercontent.com/assets/3009670/17459620/e1753338-5c0d-11e6-8470-27f2ad40f646.png)

And if you want to be more explicit:
![librosa_logo_text](https://cloud.githubusercontent.com/assets/3009670/17459621/ec98a24a-5c0d-11e6-88af-23f33cb9ae36.png)

**Comment by bmcfee** [comment]
@justinsalamon this is great! Thanks!

**Comment by stefan-balke** [comment]
@justinsalamon awesome, looks good! Only thing is if we need to do it in pink :)

**Comment by rafaelvalle** [comment]
As a suggestion, since librosa is an audio library, can the shape of the petals resemble waveforms?

**Comment by bmcfee** [comment]
I like the simple shapes we currently have. They'll make nice stickers 😁

Maybe one alternate suggestion: replace the bits with sinusoids? Maybe a nice sequence of harmonics?

But for real, we don't need to bike shed this.. pretty nice as is. Maybe we should fork out to a separate repo for media in the librosa org? I can set this up later today.

**Comment by justinsalamon** [comment]
Here's a version with a sinewave instead of the bits, let me know which one you prefer:
![librosa_logo_wave](https://cloud.githubusercontent.com/assets/3009670/17464959/4068bd4c-5cb8-11e6-922f-5ee298279e6f.png)

**Comment by dpwe** [comment]
I like this a lot.  And I think it works better at small scales than the
one with digits.

  DAn.

**Comment by bmcfee** [comment]
Agreed.  Can you push this up to the https://github.com/librosa/librosa_media repo?

**Comment by bmcfee** [comment]
BTW, I stuck a cc-by license on the media repo. Is that okay with folks?

**Comment by justinsalamon** [comment]
👍 I'll put it up on the media repo. The rose is CC-by, so (at least for the logo) we need to use CC-by anyway.

**Comment by bmcfee** [comment]
Closing this out. Thanks again!
