### ISSUE TITLE
Confidence factor for beat tracking

### ISSUE THREAD

**Issue by kacrouse** [librosa/librosa#280]
Could a confidence factor be determined for the results of the beat tracking algorithm? Perhaps a factor for each individual beat found and/or the global tempo. 

Maybe the algorithm isn't conducive to easily finding a confidence factor, but I think it would be very useful.

**Comment by bmcfee** [comment]
The beat tracking algorithm does not have a direct statistical interpretation, so labeling anything as "confidence" would be highly misleading IMO.

How exactly would you want to use such a quantity?  Depending on your application, the onset strength at selected beat frames might be a suitable proxy.  (Or, some derived quantity comparing onset strength at beats to those in the surrounding neighborhood.)

**Comment by kacrouse** [comment]
Ah, okay.

I'm looking for a way to determine how strong the beat is in a given song. Or perhaps a way to tell how easy it is to feel and track with the beat.

I think you're right, the onset strength may give me close to what I'm looking for.

**Comment by bmcfee** [comment]
I'm closing this one out -- feel free to reopen it if something new pops up on this topic.
