### ISSUE TITLE
Local contrast normalization

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#303]
[paging @ejhumphrey, and summarizing offline conversation]

We should have a reference implementation of the LCN method used by Humphrey [chapter 5, section 4.2.1](https://raw.githubusercontent.com/ejhumphrey/dl4mir-dissertation/master/pdf_snapshots/dl4mir_20150423_GM.pdf).

The API should look similar to that of `hpss`, and it should support real or complex spectrogram inputs. (The latter simply retaining the input's phased with normalized magnitudes.)

**Comment by bmcfee** [comment]
Note: I bumped this up to the 0.4.3 milestone (or 0.5.0, whichever comes first).

**Comment by bmcfee** [comment]
Meanwhile -- does this overlap at all with #297 ?  They seem related.

**Comment by ejhumphrey** [comment]
noted / thanks.

I think they might be related in terms of scope, less so in spirit.

**Comment by bmcfee** [comment]
I was thinking more in terms of grouping functionality and standardizing API (to whatever extent makes sense).  They both to localized enhancements to frequency bands, though I have no real idea how "salience" works (and to be honest, I didn't quite understand the LCN equations in your diss. either. :unamused: )

**Comment by bmcfee** [comment]
Reference code from @ejhumphrey's dissertation is [here](https://github.com/ejhumphrey/dl4mir/blob/master/dl4mir/common/lcn.py).

It mostly makes sense, but the `kernel` parameter is unclear.

**Comment by bmcfee** [comment]
I took a stab at this last night, and it seems like it will be a considerable amount of work.

Any objection to punting until 0.5?

**Comment by ejhumphrey** [comment]
none whatsoever

**Comment by bmcfee** [comment]
I'm removing this from the 0.5 milestone, since it appears that nobody has time to work on this in the foreseeable future.

**Comment by bmcfee** [comment]
Closing this one out due to lack of activity.
