### ISSUE TITLE
librosa may use plotly for just notebook instead of matplotlib (too big).

### ISSUE THREAD

**Issue by cailiang9** [librosa/librosa#314]
Or just make matplotlib optional when installing with pip. This would improve adoption of the lib.

**Comment by bmcfee** [comment]
Thanks for your comments.  It's an interesting suggestion, but I don't like the idea of switching to plotly -- we shouldn't require a remote (and proprietary) API in an open source project.

As for dropping the mpl dependency: this has been considered before (see #281 ).  There are some reasonable arguments to be made for not requiring plotting routines in an audio library.  However, I think the following outweigh them:

1. Most people working with the scipy stack (eg, anaconda users) will have matplotlib anyway, and it presents no difficulties in terms of packaging or licensing;
2. Visualization is a major part of the workflow for developing audio analyses, and is thus pretty core to librosa's intended use;
3. Making the dependency optional would require either piecemeal module import (which was discussed in #281, and I don't like), or having dynamic functionality (which we currently do for resampling, and I also don't like).
