### ISSUE TITLE
Feature Normalization

### ISSUE THREAD

**Issue by stefan-balke** [librosa/librosa#318]
I would like to add a threshold to the feature normalization.

Explanation taken from here: https://www.audiolabs-erlangen.de/content/resources/MIR/chromatoolbox/2011_MuellerEwert_ChromaToolbox_ISMIR.pdf

> To avoid random energy distributions occurring during pas- sages of very low energy (e. g., passages of silence before the actual start of the recording or during long pauses), we replace a chroma vector x by the uniform vector of norm one in case |x|p falls below a certain threshold...

Anyone against adding a this parameter to the `normalize()` function?

**Comment by bmcfee** [comment]
Sounds good, though I'd like to generalize it a little.

Currently, the logic [here](https://github.com/bmcfee/librosa/blob/master/librosa/util/utils.py#L631) looks like:

```
length[length < SMALL_FLOAT] = 1.0
return S / length
```
that is, frames with very small norm are left unnormalized.

I think two generalizations make sense:

1. User-specified threshold for this decision, instead of our current arbitrary SMALL_FLOAT constant
2. User-specified fill-value.
    - if `None`, then leave the frame as is (current behavior)
    - if `0`, then zero out the frame
    - if anything non-zero, fill with a constant and normalize (chroma toolbox behavior)

How does that sound?

**Comment by stefan-balke** [comment]
> How does that sound?

Good to me. Standard values should be the ones used at the moments so old algorithms don't break...

**Comment by stefan-balke** [comment]
Let's postpone this to 0.5 since it might not be compatible any longer...

**Comment by bmcfee** [comment]
Agreed.  I think we'll want to change the api to reverse the interpretation of axes.

**Comment by bmcfee** [comment]
For posterity: the semantics of `util.normalize` are such that `Xn = normalize(X, axis=a)` results in `scipy.linalg.norm(Xn, axis=a) == 1` (excepting thresholded/small-value cases).  That is, `a` is the axis being summed over in the norm computation, and not the axis where indexing into it means that the resulting slice has unit norm.  This is a bit counter-intuitive from the perspective of numpy ufuncs, but consistent with the behavior of `scipy.linalg.norm`.

The documentation is updated in #471, but this seemed to be a point of confusion previously.

**Comment by bmcfee** [comment]
Implemented as #471
