### ISSUE TITLE
Move static test data to a submodule

### ISSUE THREAD

**Issue by faroit** [librosa/librosa#319]
The test vectors significantly increase the repository size (See #240). I personally don't see the benefit of designing tests against static MATLAB generated test vectors. Many scientific python users now are not using MATLAB anymore and therefore identical bit-exact output is not that crucial anymore.
If you really want full MATLAB compatibility, dynamically generated vectors could better cover more test cases.

What about splitting the existing unit tests into functional tests (pure python) and MATLAB compatibility tests which could use oct2py (in case the matlab code runs on octave) or matlab_wrapper to run the tests without the intermediate vectors if available on local machines? For travis obviously only `oct2py` would work.

**Comment by bmcfee** [comment]
> I personally don't see the benefit of designing tests against static MATLAB generated test vectors.

We have unit tests in place where it makes sense, but for certain functions, regression testing on pinned parameters is really the only way to be sure that something hasn't gone unexpectedly wrong.



> What about splitting the existing unit tests into functional tests (pure python) and MATLAB compatibility tests which could use oct2py (in case the matlab code runs on octave) or matlab_wrapper to run the tests without the intermediate vectors if available on local machines? For travis obviously only oct2py would work.

I'm open to the idea, but last time I tried something like this, octave didn't fully cover all of the things that we needed.  Maybe things are different now?

At any rate, the tests are coming due for an overhaul (perhaps a rewrite with py.test), but I'm treating this as a low-priority item.




> The test vectors significantly increase the repository size (See #240).

Incidentally, wouldn't the repo have to stay the same size after removing the files, for git to be able to revert to previous checkpoints?  Or would we have to dig into deep git/back to the future 2 magic to retroactively wipe out the large files?

**Comment by faroit** [comment]
> I'm open to the idea, but last time I tried something like this, octave didn't fully cover all of the things  that we needed. Maybe things are different now?

I can run some tests next week and report about octave compatibility. 

For now I would recommend using Git LFS for the matlab vectors

> Incidentally, wouldn't the repo have to stay the same size after removing the files, for git to be able to revert to previous checkpoints? Or would we have to dig into deep git/back to the future 2 magic to retroactively wipe out the large files?

Yes, the history needs to be rewritten so maybe you want to make use of some of the available tools to do this automatically: looks like [this](https://github.com/rtyley/bfg-repo-cleaner/releases) would work

**Comment by bmcfee** [comment]
Awesome, thanks for the pointers.

As a not-totally-unrelated tangent to cleaning up the tests, I guess we ought to migrate from nose to py.test.  By doing so, we can simplify a lot of the fixture generation code and clean up the admittedly horrible generator cruft that I've piled into the test suite over the last couple of years.

This would be a huge job, but I think it fits together with the general aim of cleaning up the tests.

**Comment by faroit** [comment]
> I can run some tests next week and report about octave compatibility.

It turned out all matlab generator scripts run fine on octave 4.0 except for ```tempo2.m``` (caveats: compile octave with libsndfile and don't forget to install the signal package). However, I was unable to track down the error in ```tempo2.m```. The reported line numbers seem to be false:

```matlab
error: tempo2: operator *: nonconformant arguments (op1 is 40x129, op2 is 128x7542)
error: called from
    tempo2 at line 80 column 5
    testData>testBeat at line 390 column 28
    testData at line 63 column 5
    makeTestData at line 1 column 1
error: evaluating argument list element number 2
error: called from
    tempo2 at line 80 column 5
    testData>testBeat at line 390 column 28
    testData at line 63 column 5
    makeTestData at line 1 column 1
error: evaluating argument list element number 1
error: called from
    tempo2 at line 80 column 5
    testData>testBeat at line 390 column 28
    testData at line 63 column 5
    makeTestData at line 1 column 1
```

**Comment by bmcfee** [comment]
> error: tempo2: operator *: nonconformant arguments (op1 is 40x129, op2 is 128x7542)

That sounds like a problem in the Mel basis construction.


> It turned out all matlab generator scripts run fine on octave 4.0

Do they just run, or do they produce numerically equivalent outputs?  Since we have the pre-computed data, it's easy to check!

**Comment by faroit** [comment]
> Do they just run, or do they produce numerically equivalent outputs? Since we have the pre-computed data, it's easy to check!

I did run the ```test_core.py``` and the ```test_filters.py``` with nose against the octave generated vectors. I was expecting some numerical differences e.g. for the resampler... but: they all pass except a few of the STFT tests which do fail because of some shape errors. My guess is, that would be easy to fix.

**Comment by dpwe** [comment]
On Tue, May 3, 2016 at 8:02 AM, Brian McFee <notifications@github.com> wrote:
> error: tempo2: operator *: nonconformant arguments (op1 is 40x129, op2 is
> 128x7542)
>
> That sounds like a problem in the Mel basis construction.

Specifically, it sounds like the Octave specgram() function is
returning only fft_size/2 bins (128) instead of the fft_size/2 + 1
returned by Matlab's specgram.  Which is weird.

  DAn.

**Comment by bmcfee** [comment]
> Specifically, it sounds like the Octave specgram() function is
> returning only fft_size/2 bins (128) instead of the fft_size/2 + 1
> returned by Matlab's specgram.  Which is weird.

Yeah, from the octave docs, it says "positive frequencies" not "non-negative frequencies", so that would make sense (and be weird).

Alternately: we could clobber the builtin stft with http://www.ee.columbia.edu/~dpwe/e6820/matlab/stft.m ?

**Comment by dpwe** [comment]
I assume this one would work:
http://www.ee.columbia.edu/ln/rosa/matlab/sgram/myspecgram.m
IIRC, stft has some small differences.

  DAn.

**Comment by stefan-balke** [comment]
I know I'm warming this up but why don't we simply leave the static test vectors and put the data into a separate repo while linking back to this repo as a submodule?

**Comment by bmcfee** [comment]
> I know I'm warming this up but why don't we simply leave the static test vectors and put the data into a separate repo while linking back to this repo as a submodule?

Mostly because it's a lot of work and not a high priority item for me right now. :grin: 

Seriously though, test refactoring is a huge job that needs to be done ( #391 ), so I'm open to splitting off numerical regression tests as part of that.

**Comment by bmcfee** [comment]
This issue is back on my mind since we're doing more intensive github action workflows now.  This necessitates pushing around copies of the repo, which can get a bit costly and time-consuming.

To summarize: the proposal — from *ahem* 5 years ago — is to split `tests/data` off into a submodule and do a history-rewrite to remove purge the static files as if they were [sensitive data](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository).

We would need to also amend the CI action to pull in the submodule, and the contributor guidelines to include instructions on how to run tests.
