### ISSUE TITLE
Faster FFT implementation

### ISSUE THREAD

**Issue by carlthome** [librosa/librosa#353]
I saw that you've thought about this already (https://github.com/librosa/librosa/issues/39), @bmcfee, but I hope you'd reconsider, especially for the upcoming ICQT. A key issue with the original MATLAB CQT Toolbox is performance, and librosa could gain traction by providing a high-performing alternative.
# Proposal

Preferably all uses ([constantq.py](https://github.com/librosa/librosa/blob/f94c2229edcb251d7b58ce001f37d9548c35bcc6/librosa/core/constantq.py), [spectrum.py](https://github.com/librosa/librosa/blob/716c4f98aca77668d8fd4ea93c4aef49354b4ccd/librosa/core/spectrum.py), [audio.py](https://github.com/librosa/librosa/blob/e395cc5c0a6e126f7cfcf650322a4967fb1198a3/librosa/core/audio.py)) of FFT/IFFT should go through a fourier.py interface, that:
1. Uses [cufft](https://developer.nvidia.com/cufft) if CUDA is available, via [scikit-cuda](https://github.com/lebedov/scikit-cuda).
2. Then tries to import [pyfftw](https://github.com/pyFFTW/pyFFTW) if there's no CUDA.
3. Before finally falling back on scipy.fftpack if there's no libfftw3.

I'm short on time at the moment, but I could turn in a proposal pr in a couple of weeks if no one else has the time.

**Comment by bmcfee** [comment]
I'm open to the idea, if it can be done cleanly without making the dependency chain unduly complicated.

In the next major revision, I'm trying to pare down the optional/dynamic dependencies (scikits.samplerate and seaborn).  I'm not totally keen on the idea of adding more dynamic dependencies back in.  Maybe it could all be multiplexed out by a separate library ala audioread?

**Comment by carlthome** [comment]
I get the ambition to keep librosa clean and portable. I'll ask pyFFTW to add GPU support. https://github.com/pyFFTW/pyFFTW/issues/107 and if that goes through perhaps librosa could exchange scipy.fftpack for pyFFTW (assuming pyFFTW could fall back on numpy or scipy, also).
