### ISSUE TITLE
Audio written with librosa giving problems with HTML5 on Firefox (bitrate/encoding issue?)

### ISSUE THREAD

**Issue by justinsalamon** [librosa/librosa#361]
We're using librosa to trim some audio files, but the resulting .wav files don't load correctly in Firefox with the `<audio>` tag, which returns the following error message:
```
Media resource https://curio-media.s3.amazonaws.com/song.wav could not be decoded
```

If you open the file in Audacity and export back to disk as 16-bit signed PCM, the exported file works fine. Here's the soxi comparison of the two .wav files:
```
$ soxi song.wav                                                                                                   
soxi WARN wav: wave header missing extended part of fmt chunk
Input File     : 'song.wav'
Channels       : 2
Sample Rate    : 44100
Precision      : 25-bit
Duration       : 00:00:03.00 = 132300 samples = 225 CDDA sectors
File Size      : 1.06M
Bit Rate       : 2.82M
Sample Encoding: 32-bit Floating Point PCM

$ soxi song2.wav                                                                                                  
Input File     : 'song2.wav'
Channels       : 2
Sample Rate    : 44100
Precision      : 16-bit
Duration       : 00:00:03.00 = 132300 samples = 225 CDDA sectors
File Size      : 529k
Bit Rate       : 1.41M
Sample Encoding: 16-bit Signed Integer PCM
```

So the differences are the bitrate and sample encoding. Long story short, the problem itself is probably Firefox's implementation of the `<audio>` tag (the problem doesn't happen in Chrome), but my question for Librosa is - is there a way to set the bitrate/encoding of the audio file written with `write_wav()`? I couldn't find anything in the docs.

**Comment by justinsalamon** [comment]
Also note the soxi warning for song.wav:
```
soxi WARN wav: wave header missing extended part of fmt chunk
```

**Comment by dpwe** [comment]
>> Sample Encoding: 32-bit Floating Point PCM

.. looks pretty serious to me.  I expect many wav implementations only
support 16 bit ints.

This is of course down to the audio file interface we're using, but I
would support forcing to 16 bit ints by default, and warning on clips
or underflows, and if possible allowing float outputs via a flag.

I think I've seen python audio file interfaces that switch this based
on the dtype of the data array, but this seems a bit hacky to me.

  DAn.

**Comment by bmcfee** [comment]
Yeah, I think this is a problem for scipy, not librosa.

In the meantime, I recommend using pysoundfile for output.

**Comment by faroit** [comment]
> I think I've seen python audio file interfaces that switch this based
on the dtype of the data array, but this seems a bit hacky to me.

librosa is using ```scipy.io.wavfile``` to write wav files which in fact seems to do use the dtype to determine the PCM subformat. From the [docs](http://docs.scipy.org/doc/scipy-0.17.0/reference/generated/scipy.io.wavfile.write.html):

> The bits-per-sample will be determined by the data-type.

...so changing the dtype before writing out the file should solve this. 

```scipy.io.wavefile``` has many issues (except no dependencies), thats why I always use pysoundfile, which let you specify all the lovely details of the PCM format. It is also one of the only interfaces that reads 24bit and 32bit integer PCM files without any issues.

**Comment by bmcfee** [comment]
Two questions:

1. Would it make sense to have `write_wav` always reinterpret as `float32`?
2. If yes, should we jam this into the 0.4.3 release?

**Comment by faroit** [comment]
1. `Signed 16 bit PCM` is still the default for PCM data. 

e.g. pysoundfile uses it as well
```
import soundfile as sf
sf.default_subtype('WAV')
```
outputs `PCM_16`

Also they are [not using the data type of the data to select the data type of the written file](http://pysoundfile.readthedocs.io/en/0.8.1/#soundfile.write). Since ```write_wav``` does, I would just add a comment to the librosa documentation.

**Comment by bmcfee** [comment]
I just tried casting to `np.float16` and it doesn't seem to work.

I think we shouldn't change anything in the current implementation, and instead encourage users to use pysoundfile instead of librosa.

**Comment by faroit** [comment]
> I just tried casting to np.float16 and it doesn't seem to work.

I'm not sure if 16bit float is a valid PCM WAV format ;-) I meant `np.int16` with PCM_16...

> I think we shouldn't change anything in the current implementation, and instead encourage users to use pysoundfile instead of librosa.

I think I found the reason (looks like it's too late for the release, though):
Actually librosa does change the dtype of the audio buffer. It is because of the normalisation which is `True` by default. If you set it to `False`, the output buffer will be written out as is:

```python
rate = 44100
audio = np.random.uniform(-1, 1, rate * 3)

maxv = np.iinfo(np.int16).max

librosa.output.write_wav(
    "out32.wav", audio, rate, norm=False
)
librosa.output.write_wav(
    "out16.wav", (audio * maxv).astype(np.int16), rate, norm=False
)
```

I would therefore suggest to change the current implementation or at least throw a warning here.
Also I wonder why the int16 casting was dropped in 99e8bc67ec?

**Comment by bmcfee** [comment]
(For the record: my tests earlier today were with `norm=False` and it still didn't work.)

> Also I wonder why the int16 casting was dropped in 99e8bc6?

Because it was losing precision when saving and reloading.

**Comment by faroit** [comment]
> (For the record: my tests earlier today were with norm=False and it still didn't work.)

@bmcfee yeah, sorry. I was wrong there. Its has nothing to do with the normalisation. I've updated my comment.  But can you try to run my example on your system?

**Comment by faroit** [comment]
> Because it was losing precision when saving and reloading.

On the other hand, if you load a standard 16bit signed int wav file and save it as float32 or float64 you don't increase precision but increase the file size significantly.

So I would vote for writing out wav files as standard compliant as possible, [which is 16 or 24bit integer](https://msdn.microsoft.com/en-us/library/windows/hardware/dn653308(v=vs.85).aspx). If higher dynamic range is needed I would encourage people to pickle their numpy arrays. Anyway, why not offer the int16 casting function as an optional argument for the `write_wav` function? My feeling is that this would be helpful for a lot of users.

**Comment by dpwe** [comment]
I think float32s-in-wav is not what people generally mean by "wav file"
(i.e., many programs that read wav files don't actually accept float32
encoding), so even though int16 casting loses resolution, that's kind of
what you're asking for when you write to wav.  If we could only support one
wav format, I would prefer it was int16.

Although I see we have a backwards compatibility issue now.

  DAn.

**Comment by bmcfee** [comment]
I think the real answer here is that librosa shouldn't be in the codec business.  We provide write_wav as a convenience function, but given all the headaches involved, I'm thinking that it should be discouraged and/or deprecated.

There has been a bit of discussion in the past ( #70 #140 ) about switching all input (decoding) over to pysoundfile in the next major revision.  If we add psf as a dependency for reading, we can easily switch over output and resolve the present issue (and others) entirely.

There are a lot of positives to dropping audioread in favor of psf, and the only thing we lose in the process is mp3 (read) support.  I'd hate to lose mp3 support, and the obvious solutions to keep both working aren't all that great IMO.  Maybe others have suggestions?
