### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by xianxianzhang** [librosa/librosa#363]
Hi,

I am trying to install Librosa on my VirtualENV, but got the following error when using pip install librosa
 
x86_64-linux-gnu-gcc: error: resampy/interp.c: No such file or directory
  x86_64-linux-gnu-gcc: fatal error: no input files
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 4

COuld somebody provide me a suggestion how to solve it?

Thanks,
XIanxian

**Comment by bmcfee** [comment]
This seems like a proven in resampy, not librosa.

Could you please repost this issue over at https://github.com/bmcfee/resampy/issues with a detailed description of your environment?

**Comment by xianxianzhang** [comment]
HI,

I will try it and let you know within a week.

Thanks
xiannxian

**Comment by bmcfee** [comment]
@xianxianzhang did you get a chance to try this out?

**Comment by xianxianzhang** [comment]
Hi, Brian,

I am sorry for my later reply, but I am out of town and will be back next
week. I will try it and let you know

Thanks,
Xianxian

**Comment by bmcfee** [comment]
Since this is a resampy issue, and not a librosa issue, I'm closing this out.

**Comment by xianxianzhang** [comment]
Hi, Brian,

Thanks for checking this to me. Please feel free to close this issue.

Sorry for my late reply. Thanks again.

Xianxian
