### ISSUE TITLE
Add Key Detection Algorithms to librosa

### ISSUE THREAD

**Issue by rafaelvalle** [librosa/librosa#366]
Brian,

This is for us to discuss the addition of the following Key Detection algorithms to librosa.
1. Krumhansl, C. "Cognitive Foundations of Musical Pitch, ch. 4" (and Schmucker)
2. Madsen, S. T. and Widmer, G. "Key-Finding With Interval Profiles"
3. Temperley, David. "A Bayesian key-finding model."

**Comment by bmcfee** [comment]
@rafaelvalle Do you still have interest in implementing this?

**Comment by bmcfee** [comment]
For posterity, here's a quick prototype of the KS key detector: https://gist.github.com/bmcfee/1f66825cef2eb34c839b42dddbad49fd

**Comment by rafaelvalle** [comment]
Not anymore, Brian. Thanks for getting in touch!

**Comment by bmcfee** [comment]
I've put some thought into this over the past ... um ... 2 years.  I think it's not functionality that we should include in librosa.

Having played around with a few different models in various experiments, I'm not sufficiently satisfied with their generality or accuracy across different datasets.  Key detection generally feels more like a supervised classification kind of problem, which falls out of scope for us.

**Comment by lostanlen** [comment]
might be in scope for a yet-to-come bettina library on computational analysis of Western tonal music via piano-roll representations.
