### ISSUE TITLE
Unexpected behavior when loading audio shorter than `duration`

### ISSUE THREAD

**Issue by carlthome** [librosa/librosa#373]
I guess this might be by design but I think it's a bit dangerous that no warning or exception is raised when `load(path, duration=...)` has a duration longer than the audio file. Could the audio be padded to duration length with silence by default? Or could an exception be raised instead?

Just checking the duration after loading is fine, but looks redundant and a bit confusing, IMHO. :confused:

**Comment by bmcfee** [comment]
The documentation here does state "only load up to this much audio (in seconds)".  Could this be rephrased in a clearer way?

**Comment by carlthome** [comment]
RTFM is neat, but the problem stems from that when using librosa a bit deeper down in an application its not always clear what duration/offset is actually used in corner cases. I'm loading audio snippets that fit onto a GPU for machine learning models, for example, and it does get a bit tricky at times as data is procedurally generated, so at least a warning would be nice. Preferably, an exception by default, but padding instead iff an option is set.

**Comment by bmcfee** [comment]
I'd prefer to not change the load behavior.  If you need exact sizing, wrapping with `util.fix_length` would be an easy fix.

**Comment by carlthome** [comment]
Aw, alright. Fair enough! :smiling_imp:
