### ISSUE TITLE
Resampling docs

### ISSUE THREAD

**Issue by stefan-balke** [librosa/librosa#374]
Hey,

currently, the resampling is documented for audio signals but is implemented for any feature sequence, although it tells you that it can be `Can be mono or stereo`.
IMHO, We should talk about two things:
* Change the docs according to the functionality?
* Is it meaningful that the resample function lives in audio then?

Thanks

**Comment by bmcfee** [comment]
- Location: I guess there's no reason it couldn't move to `util`, but I don't see a strong reason for doing so either.
- `core.audio.resample` does four things:
   - validate the input as an audio buffer (finite everywhere, one or two channels)
   - resample (by scipy or resampy)
   - fix the length of the results
   - optionally rescale the result to preserve total energy
- Most of these operations only make sense for audio.  If you want to resample arbitrary data, you can use `resampy` directly.

**Comment by stefan-balke** [comment]
> Most of these operations only make sense for audio. If you want to resample arbitrary data, you can use resampy directly

Well, yes, you're right. `librosa` shouldn't solve all tasks.
