### ISSUE TITLE
compare fft of speech and noise

### ISSUE THREAD

**Issue by great-thoughts** [librosa/librosa#375]
I want to compare between the fft of two waveforms. one that belongs to noise and the other belongs to speech. I think I need some kind of normalization so that I can compare the two fft. I am not sure how to do this?

**Comment by bmcfee** [comment]
Hi,

This kind of question is really better suited for the [discussion forum](https://groups.google.com/forum/#!forum/librosa).  The github issues are intended for development and bug reports.

Could you please re-post in the forum?
