### ISSUE TITLE
MFCC feature

### ISSUE THREAD

**Issue by epratheeban** [librosa/librosa#378]
I am very new to audio field and I know basics of signal processing .

Given an audio file, I want to extract the MFCC features.

`librosa.feature.mfcc(y=none,sr=22050,S=None,n_mfcc=20,**kwargs) 
`
and returns

`(n_mfcc,t)`

How to choose the no of  n_mfcc , in my case the input data is audio file of TV series episode ? 

and it returns the (n_mfcc,t). How ` t` calculated here ? 

I tried this 

```
import numpy as np
from hmmlearn import hmm
import librosa
import matplotlib.pyplot as plt

def getPathToGroundtruth(episode):
    """Return path to groundtruth file for episode"""
    pathToGroundtruth = "../../../tbbt/TBBT/season01/Audio/" \
                        +"Episode%02d.en.wav" % episode
    return pathToGroundtruth

def getMFCC(episode):
    
    filename = getPathToGroundtruth(episode)
    
    y, sr = librosa.load(filename)  # Y gives 
    
    data = librosa.feature.mfcc(y=y, sr=sr)
    
    return data

```
```
data_m = getMFCC(1) 

>> data_m.size 
>> (20 * 56,829) 

```
Where `t = 56,829` represent the track duration in frames. is my understanding is correct ?

Thanks

Pratheeban

**Comment by bmcfee** [comment]
Hi Pratheeban,

Could you re-post this question on the [discussion forum](https://groups.google.com/forum/#!forum/librosa)?  The github issues should be used only for development purposes.

Thanks!

**Comment by epratheeban** [comment]
I will do it .

Thanks
Pratheeban
