### ISSUE TITLE
Time-domain onset_strength

### ISSUE THREAD

**Issue by carlthome** [librosa/librosa#380]
The onset detection with spectral flux is working great, but I'm wondering if there's a simple way of doing a naive `onset_detect` where `onset_strength` is done in the time domain for performance reasons. If one knows the audio has lots of clearly audible transients (lets say drums), perhaps just going by the amplitude envelope's derivative would work. How bad would that be?

**Comment by carlthome** [comment]
Peter is using spectral flux. Ragnar used the amplitude envelope. Spectral flux is more reliable. Amplitude is more efficient.

**Comment by carlthome** [comment]
For my silly purposes, something naive such as this is working just fine (though obviously it often picks zero-crossings that are not onsets at all, or harmonics and overtones during a note duration):

```Python
import librosa
import random
import numpy as np

samplerate = 44100
y = librosa.load(path, samplerate)[0]
idx = random.choice(np.where(abs(np.diff(y)) > 0))
offset = librosa.samples_to_time(idx, samplerate)
```

I don't know if it should be provided by librosa itself though. Feel free to close this issue, @bmcfee.

**Comment by bmcfee** [comment]
I think i'm a little confused about what exactly you want here.  The code snippet you pasted is going to return sample indices everywhere except perfectly constant regions, which I would not expect to have anything to do with onsets or transients.

It's worth thinking about implementing a time-domain transient detector, but that's also a separate issue from the original inquiry about note onsets.

**Comment by carlthome** [comment]
1. Yes. I just needed something fast to skip all digital silence over a signal (keeping the noise floor is still fine). Basically https://github.com/librosa/librosa/issues/360
 1. Sorry, I didn't know there was a distinction between onset and transient and I've used them synonymously to mean onset. I assume you mean onset is a note trigger, while transients could also come from noise, reverberation, echoing etc.?

**Comment by bmcfee** [comment]
I see.  I'll take this issue as redundant to #360 then.



> I assume you mean onset is a note trigger, while transients could also come from noise, reverberation, echoing etc.?

Yeah.  Onsets may or may not be transient (eg, slow-attack of a violin vs drum hit); transients may or may not be onsets (eg, noise/reverb, as you mention).  Time-domain transient detection could be independently useful, say for phase vocoding, but I'm not in any rush to jump back down that rabbit hole.
