### ISSUE TITLE
Sampling rate issue with STFT + iSTFT

### ISSUE THREAD

**Issue by josephernest** [librosa/librosa#383]
When doing a STFT, and then an inverse STFT (iSTFT) on a 16 bits 44.1 khz audio file :

    import librosa
   
    y, sr = librosa.load('test.wav', mono=False)
    y1 = y[0,]
    S = librosa.core.stft(y1)
    z1 = librosa.core.istft(S, dtype=y1.dtype)
    librosa.output.write_wav('test2.wav', z1, sr)

the output is only a 22 khz audio file. Why? Where is there the sampling rate change ?

**Comment by r9y9** [comment]
See the doc for `librosa.load`: http://librosa.github.io/librosa/generated/librosa.core.load.html#librosa.core.load

An audio signal will be resampled to 22050Hz by default. `sr=None` uses the native sampling rate.

**Comment by bmcfee** [comment]
The issue is `istft`, not `load`.  You need to specify the sampling rate for `istft` if you want something other than the default:
```python
import librosa

y, sr = librosa.load('test.wav', sr=None, mono=False)
y1 = y[0,]
S = librosa.core.stft(y1)
z1 = librosa.core.istft(S, sr=sr, dtype=y1.dtype)
librosa.output.write_wav('test2.wav', z1, sr)
```
to do everything at the native sampling rate of `test.wav`.

**Comment by josephernest** [comment]
Thanks @bmcfee !

Just ouf of curiosity, why is the default 22khz (which truncates all frequencies over 11khz !)
Why not keeping the worldwide standard 44.1 khz (or even 48) ?

Another question : is this reconstruction STFT + iSTFT bit perfect (ie input = output)) ?

Thanks again :)

**Comment by josephernest** [comment]
@bmcfee I get :

    z1 = librosa.core.istft(S, sr=sr, dtype=y1.dtype)
    TypeError: istft() got an unexpected keyword argument 'sr'

**Comment by stefan-balke** [comment]
Hey @josephernest,

please compare your function call to the docs:
http://librosa.github.io/librosa/generated/librosa.core.istft.html#librosa-core-istft

There is no parameter `sr`.

Maybe you want to try the example first?
