### ISSUE TITLE
pip install librosa fails...

### ISSUE THREAD

**Issue by hufnala** [librosa/librosa#387]
... with "unknown file type '.pyx' from ('resampy/interp.pyx'). on my opensuse 13.2 installation.
the same happens on pip3 install.

pip install pyrex failed because no ressources have been found.

any idea?

Thanks
//hufnala

**Comment by bmcfee** [comment]
This is a known [resampy issue](https://github.com/bmcfee/resampy/issues/26), not a librosa issue.

There's a pre-release up that should fix this; please let me know if it doesn't.

If you `pip3 install --pre resampy`, it should work.
