### ISSUE TITLE
Rewrite tests in py.test

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#391]
This will be a huge job, but our test suite is currently the stuff of nightmares.

**Comment by stefan-balke** [comment]
Puh, that's gonna be a lot of work. Should it cover #319? Would make sense, wouldn't it?

**Comment by bmcfee** [comment]
Yup, loads of work!

I think it makes more sense to port the tests as they currently are, and then worry about rewriting them ala #319.

**Comment by stefan-balke** [comment]
Quick thought on this:
Can we run `nosetests` and `py.test` in parallel? At least the new tests could be directly written in `py.test` and I think there are some tests where the porting will be very easy.

**Comment by bmcfee** [comment]
pytest has some trouble with yield-tests (see [here](https://docs.pytest.org/en/latest/nose.html)), but it could work.  There's no harm in trying, anyway.

**Comment by bmcfee** [comment]
This issue is about to become more pressing, as matplotlib 3.0 is dropping the (deprecated) image comparison test functionality that we use.

For now, we can pin the test dependencies to matplotlib >=1.5, <3.0, but we'll need to fix it long term.
