### ISSUE TITLE
Issues for the HAMR Sprint, 2016-08-06

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#395]
[Tagging @craffel @ejhumphrey @justinsalamon @stefan-balke -- feel free to mention anyone else that might be attending HAMR and has some interest in any of the topics below]

I'd like to do a sprint on librosa for HAMR this year.  The idea here is to get people together to work on issues slated for the next release (0.5), or help new developers ease into contributing.

Here's a list of some issues that I think we could reasonably work on over the course of a day, rated by estimated difficulty and the amount of existing preliminary work done so far.

- :smile: `[    ]` #360 : trimming and splitting
- :smile: `[++  ]` #305 : time-reassignment
- :smile: `[    ]` #278 : logo
- :smile: `[+   ]`  #359 : API change to hpss with masks
- :smile: `[++  ]`  #157 : adding numba support to tight-loop functions
- :sweat: `[    ]`  #18 : refactoring filterbank construction
- :sweat: `[+   ]`  #318 : API change to feature normalization
- :sweat:  `[++  ]` #297 : salience function
- :cold_sweat:  `[+++ ]` #165 inverse CQT
- :cold_sweat: `[    ]`  #70 #128 #140 various related IO issues
- :cold_sweat: `[++  ]`  #44 #269: variable-tempo beat tracking and API changes
- :cold_sweat: `[    ]`  #303 : local contrast normalization
- :cold_sweat: `[    ]`  #12 / #394 : improved chroma and log-frequency representations
- :cold_sweat: `[    ]`  #391 : Refactor tests

If/as people volunteer for certain tasks, I'll attach names to the issues above.

**Comment by justinsalamon** [comment]
I've always enjoyed designing logos ✏️ ✏️ ✏️

**Comment by stefan-balke** [comment]
For me it will be _HAMR on the plane_. I'll let you guys know what I'll pick up. Priority for me would be reassigned spectrogram and then harmonic summation towards salience functions.

**Comment by bmcfee** [comment]
@stefan-balke cool. I have a first cut at Harmonic summation using interpolators that might be useful to you. This also comes up in rhythm features, so I'd like it to be as generic as possible. I'll post a gist in this thread.

**Comment by bmcfee** [comment]
[harmonics gist](https://gist.github.com/d4f00c1e7e8e4faf5500eb140fd4d1f7) -- it's basically functional, but could possibly be made more efficient / robust.

**Comment by stefan-balke** [comment]
Nice, will check it out.

**Comment by bmcfee** [comment]
@stefan-balke what did you have in mind for "reassigned spectrogram"?  Something different from the existing `ifgram`?

One caveat of the gist I posted above: it assumes static frequencies.  It shouldn't be too difficult to extend it to support the `F` output from `ifgram` (ie, bin-by-time center frequencies), but I suspect it will require swapping out the interpolator for something more generic since the samples are no longer on a grid.  It might be much slower.  I think this is why I hadn't submitted a PR for harmonic summation yet.

**Comment by stefan-balke** [comment]
> @stefan-balke what did you have in mind for "reassigned spectrogram"? Something different from the existing ifgram?

No, it would take the `ifgram` and "resort" the frequencies depending on a target frequency axis (might be from lin- to log-frequency). It should be straightforward and I guess painfully slow but for the resorting we might as well add numba.

**Comment by ejhumphrey** [comment]
+100, but I may be preoccupied with a spotify hack, will keep folks posted.

**Comment by lostanlen** [comment]
I'd like to claim #18.

**Comment by stefan-balke** [comment]
I also found some reference implementation:
http://tftb.nongnu.org

But that's by no means readable code...
