### ISSUE TITLE
librosa in pyqt

### ISSUE THREAD

**Issue by brupelo** [librosa/librosa#396]
Hi,

I'd like to create a [dj live system](https://github.com/XT95/VisualLiveSystem) in pyqt using some powerful audio library which allowed me not only the basic features of any audio player (play, stop, pause, position control, mute, volume editing) but also some audio editing (effects, filtering) and audio fetching (fft, bpm), it seems librosa is a possible candidate.

Could you confirm me which file formats are supported with it and also if it's what I'm looking for?

Thanks in advance

**Comment by faroit** [comment]
librosa has many useful things for this application, but python in general can be very tricky for realtime applications. Especially for effects and filtering I would go for [pyo](http://ajaxsoundstudio.com/software/pyo/) which is written in C but has a very convenient python interface

**Comment by bmcfee** [comment]
For input, librosa supports any audio formats which can be decoded by gstreamer or ffmpeg, which is pretty much all of them.  You can also load audio with pysoundfile, which supports everything included in libsndfile (basically everything you're likely to see except for mp3/other proprietary codecs).

I agree with @faroit that librosa may not be the right tool for your application though, given it's focus on analysis (not processing or synthesis) and python's relatively poor fit for realtime applications.

If you want to stick with python, you might want to check out https://github.com/mbrucher/AudioTK .
