### ISSUE TITLE
Cache levels

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#398]
The cache decorator could have a `level` parameter, similar to logging levels, that can prioritize which functions get cached.

For example, filter banks could always be cached, but maybe CQT results aren't so important to cache.

Then we would have

```python
@cache(level=1)
def melfb(...)


@cache(level=3)
def cqt(...)
```

The active level would be set by an environment variable, similarly to all the other cache options.

**Comment by bmcfee** [comment]
Taxonomy of caching levels:

1. filters and basis functions (important, relatively static)
2. basic features derived from audio (stft, cqt, zc, and the like)
3. derived features (librosa.feature.*)
4. ???

All cached functions should have a signature in the docstring that indicates their caching level.

**Comment by dpwe** [comment]
What about 10, 20, 30 to leave space to insert things later?

**Comment by bmcfee** [comment]
floats are totally valid cache levels here, but yeah, good call.
