### ISSUE TITLE
Units for output

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#408]
Several of the librosa methods output results in non-intuitive units like frames.  For example, the output of
```python
librosa.beat.beat_track(y=y, sr=sr)
```
is beat timings in frames, at a standard but obscure (from the caller's perspective) frame rate.  Similarly for onset detection, etc.

It wouldn't be hard to add a parameter `units` that would automate the conversion to time or samples.  For example,

```python
librosa.beat.beat_track(y=y, sr=sr, units='time')
```
would produce beat timings in seconds, and 
```python
librosa.beat.beat_track(y=y, sr=sr, units='samples')
```
would produce timings in samples.

This could be automated by a general-purpose wrapper that would handle the dispatch to the proper time conversion functions.

We could do similarly for frequency (hz, midi, notes).

**Comment by stefan-balke** [comment]
Would this require knowledge of the, e.g., the `hop_length`?

If so, I would prefer to keep it explicit with a separate function call instead of doing too much things implictly.

**Comment by bmcfee** [comment]
Yes, but `beat_track` knows the hop length already, so does `onset_detect`.
