### ISSUE TITLE
display.waveplot for stereo sums to mono anyway?

### ISSUE THREAD

**Issue by carlthome** [librosa/librosa#409]
The docstring for display.waveplot states:

> If y is stereo, the curve is drawn between [-abs(y[1]), abs(y[0])], so that the left and right channels are drawn above and below the axis, respectively.

but this results in a mono waveform:

```python
import librosa
y, sr = librosa.load(librosa.util.example_audio_file(), mono=False)
assert y.ndim == 2 and y.shape[0] == 2
librosa.display.waveplot(y, sr)
```
![image](https://cloud.githubusercontent.com/assets/1595907/18715472/b0d6b8c0-8019-11e6-9390-085f1c1acb32.png)

Is something wrong with my install or my understanding of the docstring?

For reference, the version I'm using:
```sh
pip show librosa
---
Metadata-Version: 2.0
Name: librosa
Version: 0.4.3
Summary: Python module for audio and music processing
Home-page: http://github.com/librosa/librosa
Author: Brian McFee
Author-email: brian.mcfee@nyu.edu
Installer: pip
License: ISC
Location: /home/carl/anaconda3/lib/python3.5/site-packages
Requires: six, joblib, resampy, audioread, decorator, scikit-learn, scipy, numpy, matplotlib
Classifiers:
  License :: OSI Approved :: ISC License (ISCL)
  Programming Language :: Python
  Development Status :: 3 - Alpha
  Intended Audience :: Developers
  Topic :: Multimedia :: Sound/Audio :: Analysis
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
```

**Comment by bmcfee** [comment]
This is not a mono plot, and is the intended and documented behavior.  Quoth the [docs](http://librosa.github.io/librosa/generated/librosa.display.waveplot.html):

> If y is stereo, the curve is drawn between [-abs(y[1]), abs(y[0])], so that the left and right channels are drawn above and below the axis, respectively.

If you look closely, you'll see that the troughs and peaks of your figure have different amplitudes.  You can verify this by overlaying with a second plot that's just the left (or right) channel.

**Comment by carlthome** [comment]
Aha! :hamster: Cheers! :dancer:
