### ISSUE TITLE
CQT filter normalization revisited

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#412]
@ejhumphrey pointed out that the CQT filter bank is not scaled by the length of the filters when `norm=None`.  (When `norm!=None`, this doesn't matter because length scaling washes out.)

This should be easy to fix.

**Comment by ejhumphrey** [comment]
can haz assign? it won't let me do that, not being an official collaborator

**Comment by ejhumphrey** [comment]
for posterity, here's a notebook / gist I put together ... more illustrative than reproducible 😞 

http://nbviewer.jupyter.org/urls/dl.dropbox.com/s/y7bc0oh26s5yt7p/cqt-sweep.ipynb

**Comment by bmcfee** [comment]
BTW, I think you're not going to get bit-level comparison to the dl4mir implementation because librosa's filters are fractional-length, and dl4mir had rounded-length windows (as far as I can tell from a skim of the code).

**Comment by ejhumphrey** [comment]
​good point / generally aware of that fact ... wasn't going to b4b it, the
meat of the work is adding the scalar and updating ​corresponding tests.

**Comment by bmcfee** [comment]
I was just thinking about this again: would it be easier to implement this by adding length-normalization to `util.normalize`?  Then you could just call `librosa.cqt(..., norm='length')` and not have to change the cqt code at all.

**Comment by ejhumphrey** [comment]
+1

**Comment by bmcfee** [comment]
I guess it's not 100% correct since this would use the rounded filter length instead of the fractional length.  Maybe that's not a huge deal?

**Comment by bmcfee** [comment]
One more random thought: what happens if you call cqt with `norm=0`?  This ought to be very close to the length hack I suggested before, but requires no modifications to the code.

**Comment by bmcfee** [comment]
I took a hack at this (`norm='length'`), and it doesn't work because the recursive downsampling uses `scale=True`) to preserve signal energy, which I think is correct here.  Any single-octave filter renormalization will not have @ejhumphrey's desired effect.

I think the only sensible way around this is to reweight the cqt output by dividing out the filter lengths.  I don't think this should be the default behavior.

Do we still want to implement this?

**Comment by bmcfee** [comment]
Fixed by merging #417
