### ISSUE TITLE
Documenting pysoundfile

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#420]
We should add an example to the gallery that covers the following uses with pysoundfile:
- Block processing #116 
- Output compression #70 
- File-like input #140

**Comment by faroit** [comment]
I can add these. 

Let's also address #361 because the PCM subformats and their issues (especially 24bit) are typically overseen by many users.

**Comment by bmcfee** [comment]
@faroit you still up for handling this one?

**Comment by faroit** [comment]
Oops, almost forgot about this one. 😳

I put this my 2Do for the upcoming weekend. Would you prefer a notebook or a script?

**Comment by bmcfee** [comment]
Thanks!

About format: I was thinking code fragments embedded in the Sphinx docs.

**Comment by bmcfee** [comment]
Resolved by merging #480
