### ISSUE TITLE
Numpy deprecation warning in cqt

### ISSUE THREAD

**Issue by markostam** [librosa/librosa#422]
Taking the CQT of a signal will throw this deprecation warning. Not a huge deal but kind of annoying when processing large batches.
```py
[...]numpy/core/numeric.py:482: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
```
Running python 3.5.2 (anaconda) and numpy 1.11.1.

**Comment by markostam** [comment]
sure:
'''py
a = librosa.cqt(librosa.load("/path/to/file.mp3")[0], real=True)
'''
i'm running librosa 0.4.3 btw.

**Comment by bmcfee** [comment]
Thanks.

I've confirmed that this is fixed in master.
