### ISSUE TITLE
Display groundtruth time mark along with waveform

### ISSUE THREAD

**Issue by andreydung** [librosa/librosa#425]
```
librosa.display.waveplot(x, sr = fs)
plt.axvline(fs)

```
I'm trying to display vertical lines corresponding to some time marks. plt.axvline does show vertical line, but the time is not correct (it's supposed to be at 1s). How do I fix this? Should I contribute to the function in the display module?

**Comment by bmcfee** [comment]
Yes, this is an artifact of waveplot doing envelope downsampling under the hood for efficiency purposes.

This should have been fixed already in the 0.5 branch (current master) when we merged #368, which among other things, puts all plot axes on correct unit locations.

Can you try pulling from master and let me know if it behaves as you expect?

**Comment by bmcfee** [comment]
I just hacked up a demo notebook using the current branch, and it works as expected: https://gist.github.com/bmcfee/e1e7ab0b53c112fe7459df7f9c341af5

Unless there are objections, I'll close this out tonight.

**Comment by andreydung** [comment]
Thanks!
