### ISSUE TITLE
MFCC with different hop_size and n_fft

### ISSUE THREAD

**Issue by stefan-balke** [librosa/librosa#431]
Hi,

I'm doing this:
`mfcc = librosa.feature.mfcc(y=resamp, sr=samplerate, n_mfcc=n_mfcc, n_fft=n_fft, hop_size=hop_size)`

The error is that:
`TypeError: mel() got an unexpected keyword argument 'hop_size'`

Tracing it down leads to this 
https://github.com/librosa/librosa/blob/master/librosa/feature/spectral.py#L1258
and this
https://github.com/librosa/librosa/blob/master/librosa/feature/spectral.py#L1339
line.

If I would provide `S`, it would work.

The `**kwargs` are simply handed to both functions and `mel()` doesn't know all parameters.

Should we preprocess `**kwargs` before we hand it over to a function?

**Comment by bmcfee** [comment]
I think this is an error due to calling it `hop_size` and not `hop_length`?

I'd prefer to not get into kwarg-filtering.

**Comment by stefan-balke** [comment]
A f***, nevermind, just realized in the same second you answered.

I constantly confuse these two...
