### ISSUE TITLE
Rename core.harmonic.harmonics?

### ISSUE THREAD

**Issue by rabitt** [librosa/librosa#433]
Right now there is:
```core.harmonic.harmonics```
and
```effects.harmonic```

No official namespace collisions, but for clarity what about renaming one of them? Not sure to what! maybe the harmonics function could be something like `stack_harmonics`?

**Comment by bmcfee** [comment]
Yeah -- I'm not crazy about the name `harmonics`, but couldn't think of a better one.  Maybe `interp_harmonics`?

**Comment by rabitt** [comment]
👍  `interp_harmonics`
