### ISSUE TITLE
Query MFCC coefficient based on time

### ISSUE THREAD

**Issue by andreydung** [librosa/librosa#436]
How do I find the MFCC coefficients at a specific time in the audio?

For examples, librosa.util.example_audio_file() has length of 61 seconds, and running MFCC I got (20, 2647).

The relationship should be linear, so is the following correct for the MFCC at sec, for a window size of (-1, 1)?
```
mfcc = MFCC[int((sec - 1)/61*2647) : int((sec +1)/61*2647) ]
```

**Comment by bmcfee** [comment]
You can use `time_to_frames` to convert time indices to frames.

Note that the first dimension corresponds to MFCC coefficients, and the second dimension is the frame index.

[`time_to_frames`](https://librosa.github.io/librosa/generated/librosa.core.time_to_frames.html#librosa.core.time_to_frames)

I hope this helps.

(PS: this kind of question is better for the [google group](https://groups.google.com/forum/#!forum/librosa) than github.)

**Comment by andreydung** [comment]
Thanks, I'll use the mailing list next time!
