### ISSUE TITLE
cqt returns complex number even with 

### ISSUE THREAD

**Issue by polyrhythmatic** [librosa/librosa#440]
Working with the current master branch 17885667683a9c401de567494ceeb28fcac0901f and I've noticed that the CQT always returns complex numbers even with the flag "real=True" set.

I know there's been work done recently on CQT recently GH-165 and I'm wondering if this got changed along the way.

Am I doing something wrong here?

```
over_sample = 3
res_factor = 1
fmin = librosa.midi_to_hz(12)
const_q = librosa.cqt(y=y_val, sr=sample_rate, fmin=fmin, n_bins=int(8 * 12 * over_sample), filter_scale=res_factor, bins_per_octave=int(12*over_sample), hop_length=128, real=True, scale=True)
```

**Comment by bmcfee** [comment]
Good catch -- you should be getting a deprecation warning though.  Are you?

`real` is deprecated in 0.5 and will be removed in 0.6.  That it isn't working is a bug (tagged now, thanks), but you may as well future-proof by taking `np.abs(librosa.cqt(...))` instead.

**Comment by polyrhythmatic** [comment]
Here's where I admit to running the script in Node and not paying attention to stderr after getting it set up...

Thanks for the heads up and simple solution with np.abs, and thanks for the inverse cqt! Great function.
