### ISSUE TITLE
librosa 0.5.0.dev0 display not a module

### ISSUE THREAD

**Issue by polyrhythmatic** [librosa/librosa#441]
Working with the dev branch at the moment the following provides an error:

```python 
>>> import librosa
>>> librosa.display
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'display'
```

Any idea what is causing this? I can't figure it out.

**Comment by bmcfee** [comment]
You need to explicitly `import librosa.display` now.

See #343 for the discussion going into this.

**Comment by polyrhythmatic** [comment]
facepalm... I even searched. Thanks.

**Comment by bmcfee** [comment]
Sorry if that wasn't yet documented -- it's a peril of using bleeding edge rather than the stable release though.

It's on the roadmap to add pointers in the release notes for all the changes in 0.5.  In general, I do that sort of thing last to eliminate redundant work, but that means the docs are sometimes out of date compared to master.

**Comment by polyrhythmatic** [comment]
No worries, totally expected!

**Comment by bmcfee** [comment]
If you want to keep up with changes, [this query](https://github.com/librosa/librosa/pulls?q=is%3Apr+is%3Aclosed+milestone%3A0.5) shows all closed PRs tagged for 0.5.

**Comment by polyrhythmatic** [comment]
👍  will check there as well in the future. Thanks,.

**Comment by Gargosio** [comment]
Thanks for this! God bless you!

**Comment by marlon-bain** [comment]
It's worth updating the tutorial: https://librosa.github.io/librosa/generated/librosa.beat.tempo.html#librosa.beat.tempo

**Comment by lostanlen** [comment]
@marlon-bain hello, did you run into this issue while running librosa.beat.tempo's tutorial? By updating do you mean that an  `import librosa.display` statement is lacking?
