### ISSUE TITLE
cqt default: tuning=0 or None?

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#444]
By default, CQT currently does automatic tuning estimation to adapt the basis to the signal.  This is probably what you want for something like chroma, but not for other applications where the frequencies should be fixed across signals.

Does anyone object to changing the default to `tuning=0.0`?  It would be a minor API change, and the old behavior can always be recovered by `tuning=None`.

**Comment by stefan-balke** [comment]
Yeah, that's a good one. Thinking about it, maybe that influenced some of my experiments unintentionally. :)
