### ISSUE TITLE
Default fmt parameters result in slow processing times

### ISSUE THREAD

**Issue by mcartwright** [librosa/librosa#453]
The default interpolation for the fmt is 'cubic'. While this interpolation will produce the most accurate results, it is also much, much slower than 'linear' interpolation, e.g.

```
>>> import timeit
>>> timeit.timeit('librosa.fmt(np.random.random(1024), n_fmt=512, kind="linear")', setup='import librosa; import numpy as np', number=15)
0.0035851001739501953
>>> timeit.timeit('librosa.fmt(np.random.random(1024), n_fmt=512, kind="cubic")', setup='import librosa; import numpy as np', number=15)
8.289463996887207
>>> 
```

It seems that with such slow processing times with the default params that people may simply dismiss the transform. To remedy this, I propose that there should at least be a note in the documentation that mentions the tradeoff between the processing time and the accuracy and that  maybe the default should be changed to 'linear' as well.

**Comment by stefan-balke** [comment]
A hint in the docs is fine. Feel free to do a PR and we can discuss this over there.

**Comment by bmcfee** [comment]
I'm just going to roll this into the documentation audit #419.
