### ISSUE TITLE
Reopen a save file

### ISSUE THREAD

**Issue by laizpablo** [librosa/librosa#454]
I can't open a file that I have previously saved.

I'm working with big file of music and I divided into a small one.
Then I save this smalls sounds of music.
When I have to open this smalls sounds of music I can't.

Error: NoBackEndError

**Comment by stefan-balke** [comment]
Can you give more context and some code example? Otherwise I doubt that this description is enough to help you out.

**Comment by bmcfee** [comment]
This sounds to me like a problem with your audioread installation, not librosa.

**Comment by laizpablo** [comment]
For create a database I downloaded some audios from YouTube.
I sliced this audios by opened with librosa, and saving with librosa pieces of this audio.

When I try to open the file saved I have a backend Error.

Finally, I do with scipy to open and save the pieces of the audio.

Thanks for your help.

**Comment by laizpablo** [comment]
@bmcfee I don't understand why, because I can open files with librosa.
