### ISSUE TITLE
output wav as float32?

### ISSUE THREAD

**Issue by dankorg** [librosa/librosa#455]
I have 16bit input 44.1kHz. I managed to understand the sr=None to get output as 44.1khz, but
somehow the output when writing a wav always gives me 32-bit float instead of 16-bit like original input. How do I fix this?

thanks

**Comment by dankorg** [comment]
nevermind, i fixed my problem by using module soundfile for reading and writing wav files.

:)

**Comment by r9y9** [comment]
Have you tried to setting `dtype=np.int16` when you use `librosa.core.load`? The `dtype` defaults to `np.float32` (see [doc](http://librosa.github.io/librosa/_modules/librosa/core/audio.html#load)) so I wonder you got float32-valued representation of audio.

**Comment by bmcfee** [comment]
@dankorg should I close this one out then?
