### ISSUE TITLE
librosa.core.load kwarg res_type 

### ISSUE THREAD

**Issue by Cortexelus** [librosa/librosa#460]
`librosa.core.load` should take keyword argument `res_type` for `librosa.core.resample`

The default `res_type` is `kaiser_best` but usually I want `kaiser_fast` which loads about 2.7x faster  when resampling from 44100 to 22050, and doesn't harm accuracy of my tasks. For a 3-4 minute song that's 10 seconds of load time saved.

**Comment by bmcfee** [comment]
I see no problem Ruth adding that parameter. Do you want to make a pr?
