### ISSUE TITLE
TensorFlow on windows: Errors on some libraries 

### ISSUE THREAD

**Issue by Kamatio** [librosa/librosa#465]
Dear Fellows after The release of Tensorflow on windows, I can run many library functions without errors but some have failed to run and tried to search in all related areas of solution can't get solution.
Errors: Can't  **import audioTrainTest as aT** on Python Jupyter and even on window command function the error says  _Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'audioTrainTest'_ and when I tried to install it through pip install it shows me  **Could not find a version that satisfies the requirement audioTrainTest (from versions: )
No matching distribution found for utilities**. This error goes to **audioBasicIO** and **Utilities** as well. 

I would appreciate your help to correct these errors, I am using windows 10. Anaconda Python 3.5... 
Thanks a lot. 
Blessings to you all.....

**Comment by carlthome** [comment]
Hmm, is this related to librosa?

**Comment by Kamatio** [comment]
@carlthome Yes sir.

**Comment by faroit** [comment]
@Kamatio are you refering to [this](https://github.com/tyiannak/pyAudioAnalysis/blob/master/audioTrainTest.py)? I don't [see](https://github.com/tyiannak/pyAudioAnalysis/wiki/2.-General) any librosa dependencies in there.

**Comment by Kamatio** [comment]
Mr @faroit thanks, I am referring to this [https://github.com/tyiannak/pyAudioAnalysis/blob/master/audioFeatureExtraction.py](url).

**Comment by Kamatio** [comment]
I am referring to [This](https://github.com/tyiannak/pyAudioAnalysis/blob/master/audioFeatureExtraction.py) Mr. @faroit

**Comment by faroit** [comment]
k, since this is neither related to librosa nor to tensorflow -> please open an issue [here](https://github.com/tyiannak/pyAudioAnalysis/issues)

**Comment by Kamatio** [comment]
@faroit Thanks I have opened [here](https://github.com/tyiannak/pyAudioAnalysis/issues/49) Have you ever met with that error? Thanks!

**Comment by carlthome** [comment]
Please keep user issues with other projects in their respective forums and close this issue.
