### ISSUE TITLE
C2 is not 32.7 Hz?

### ISSUE THREAD

**Issue by polyrhythmatic** [librosa/librosa#466]
Sorry if this is nitpicky but appears that the docs for [chroma cqt](http://librosa.github.io/librosa/generated/librosa.feature.chroma_cqt.html) and [chroma cens](http://librosa.github.io/librosa/generated/librosa.feature.chroma_cens.html) both list C2 as 32.7 Hz. Could lead to people making a mistake when it is actually 65.41 Hz.

I'm not sure which of the two is the actual value otherwise I'd submit a PR!

**Comment by bmcfee** [comment]
Thanks for catching that!

It appears to be a typo + copypasta; it should read `'C1' ~= 32.7 Hz` in both cases.

If you want to PR a fix, I'd appreciate it.

**Comment by polyrhythmatic** [comment]
pull requested!
