### ISSUE TITLE
(power of) melspectrogram

### ISSUE THREAD

**Issue by keunwoochoi** [librosa/librosa#468]
https://github.com/librosa/librosa/blob/c9c4254b540a8cf1091c6126c1be4890c86d298c/librosa/feature/spectral.py#L1350

I might be missing something, but is there a reason that melspectrogram should output a mel-scaled **power** spectrogram?

**Comment by bmcfee** [comment]
> I might be missing something, but is there a reason that melspectrogram should output a mel-scaled power spectrogram?

Yep -- it was originally factored out of an MFCC implementation, where you want `dct(log(power))`.

If you want to compute melspec by aggregating amplitude instead of power, you can do
```python
librosa.feature.melspectrogram(S=np.abs(librosa.stft(y)))
```

**Comment by keunwoochoi** [comment]
I see.. how about add a keyword argument `power=2`? i.e. 

`def melspectrogram(y=None, sr=22050, S=None, n_fft=2048, hop_length=512, power=2,
                   **kwargs):`

I think it would help understanding, though it is well described in docstring

**Comment by bmcfee** [comment]
Sure, we could add that parameter.  I'm a little hesitant to do so because we already have a provision for doing that computation, assuming the user is willing to precompute the spectrogram.  Care to do a PR?

**Comment by keunwoochoi** [comment]
Yeah.. in terms of functionally it's just making 2 lines --> 1 line, but hopefully it makes clearer. (Just realised I've been using **4 power melspectrogram for a year..) I'll PR.

**Comment by bmcfee** [comment]
Fixed by merging #472
