### ISSUE TITLE
docstring error in frames_to_samples

### ISSUE THREAD

**Issue by justinsalamon** [librosa/librosa#469]
The docstring for the [frames_to_samples](https://github.com/librosa/librosa/blob/397c7241a0d1c0cba7b34e49651850d14e0a982f/librosa/core/time_frequency.py#L28)  method says it returns a times arrays (in seconds), but (as the method name suggests) what it actually returns is sample indices.

**Comment by bmcfee** [comment]
Good catch!  Rolling this into the documentation audit #419 .
