### ISSUE TITLE
librosa.load (audioread) breaks on this audio file, not sure why?

### ISSUE THREAD

**Issue by justinsalamon** [librosa/librosa#477]
Calling `librosa.load('101729.wav', sr=None)` ([download file here](https://drive.google.com/open?id=0B39u742eEiEqeno5cUlsUjIyUkE)) gives the following error:
```python
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-172-5d71d5777356> in <module>()
----> 1 audio, sr = librosa.load('101729.wav', sr=None)

/Users/justin/dev/miniconda3/envs/py27/lib/python2.7/site-packages/librosa/core/audio.pyc in load(path, sr, mono, offset, duration, dtype)
    121         n = 0
    122 
--> 123         for frame in input_file:
    124             frame = util.buf_to_float(frame, dtype=dtype)
    125             n_prev = n

/Users/justin/dev/miniconda3/envs/py27/lib/python2.7/site-packages/audioread/rawread.pyc in read_data(self, block_samples)
    110 
    111             # Make sure we have the desired bitdepth and endianness.
--> 112             data = audioop.lin2lin(data, old_width, TARGET_WIDTH)
    113             if self._needs_byteswap and self._file.getcomptype() != 'sowt':
    114                 # Big-endian data. Swap endianness.

error: Size should be 1, 2 or 4
```

Must be something about the file's format that causes the problem, though I'm not sure what. Here's the file info (as returned by pysox):
```python
{'bitrate': 24,
 'channels': 2,
 'duration': 84.580021,
 'encoding': 'Signed Integer PCM',
 'num_samples': 4059841,
 'sample_rate': 48000.0,
 'silent': False}
```

**Comment by justinsalamon** [comment]
update: I've found another ~300 files that won't load (all from the [UrbanSound dataset](https://serv.cusp.nyu.edu/projects/urbansounddataset/) which comprises files from freesound.org in the original format they were uploaded to the site). 

Guessing it has to do with non-standard audio formats, but all of these files load fine in audacity/essentia, so would be nice (and helpful in my case) if librosa was able to handle these.

**Comment by bmcfee** [comment]
This looks like a problem with `audioread` and not librosa.  Can you load them with pysoundfile?

**Comment by justinsalamon** [comment]
Tried the same single file and pysoundfile loads it fine. Can't try the rest just now but will do when I can and report back. 

Assuming it loads the rest of the files as well, would it be worth replacing audioread with pysoundfile as the audio loading engine? Or at least support it as an alternative?

**Comment by bmcfee** [comment]
> Assuming it loads the rest of the files as well, would it be worth replacing audioread with pysoundfile as the audio loading engine? Or at least support it as an alternative?

This has been discussed several times, check issues tagged with IO.

Replacing would mean losing mp3 support, so no. Adding soundfile as a backend has been discussed several times, but it complicates dependencies/installation, and would be a pretty major undertaking.

In general, I would recommend just using soundfile directly instead of librosa for io, if it supports the codecs you need.

**Comment by bmcfee** [comment]
I'm closing this one out, as it's not a librosa issue.

**Comment by justinsalamon** [comment]
> In general, I would recommend just using soundfile directly instead of librosa for io, if it supports the codecs you need.

Yes that's the sensible option. The collection does include mp3 so it wouldn't be a catchall, but some combination of librosa with pysoundfile as a fallback when loading fails might do the trick.

**Comment by khlukekim** [comment]
This is actually Python2's audioop.lin2lin issue, which cannot handle 3-byte input. Python3 may handle this.

**Comment by Khalidhussain1134** [comment]
Hi Bmcfee,
I got error while reading audio file using librosa.load(file.wav)

  File "D:/DECASE2017/urbansoudclassification/urban.py", line 37, in extract_features
    sound_clip, s = librosa.load(fn)

  File "C:\Users\CL_1\Anaconda3\lib\site-packages\librosa\core\audio.py", line 107, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:

  File "C:\Users\CL_1\Anaconda3\lib\site-packages\audioread\__init__.py", line 116, in audio_open
    raise NoBackendError()

NoBackendError

What type of this error will be?
Thank you

**Comment by dpwe** [comment]
To quote brmcfee, please refer to this thread
<https://groups.google.com/d/topic/librosa/Z1-HXBsHLi0/discussion>.

  DAn.

On Wed, Jul 12, 2017 at 3:53 AM, Khalidhussain1134 <notifications@github.com

**Comment by Khalidhussain1134** [comment]
I have installed decoding library  ffmpeg  as mentioned in the group "https://groups.google.com/d/topic/librosa/Z1-HXBsHLi0/discussion"  

Now it is working, thank you

**Comment by pratistha** [comment]
Hi @justinsalamon ,

I am stuck with exact same issue , can you tell how you used pyaudio for those 300 files?
As when i am trying to use pyaudio and trying extract features , it gives me error.

Please help me out.

Thanks in advanced.

**Comment by lostanlen** [comment]
@pratistha can you please share the output of `sox -i 101729.wav` ?

**Comment by justinsalamon** [comment]
@pratistha you mentioned `pyaudio`, but my solution was to use `pysoundfile` (`pip install pysoundfile`). Then loading the audio is just:
```
import soundfile as sf
data, samplerate = sf.read('existing_file.wav')
```

Hope this helps!

**Comment by pratistha** [comment]
Hi @justinsalamon , yes indeed i did the same but to extract features like mfcc , i was using same librosa library with input as data, samplerate found from pysoundfile
this gives me error.
mfccs = np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=40).T,axis=0)

Can you help me with this ?

@lostanlen  NoBackendError

**Comment by justinsalamon** [comment]
@pratistha it's a little hard for me to help without more context - when posting an issue it'd be helpful if you could include details about your operating system, python environment, a complete snippet of code (that could be run, including a link to your input audio file) and the full error report (not just the error type).

Having said that, searching for "librosa NoBackendError" led me to this issue #219 which looks like it might be relevant. Basically you might be missing some codecs needed to load the audio data you are using (is it an ogg file?). Proposed solutions mainly involve installing libraries that include the necessary codecs such as `ffmpeg`, `gstreamer` or `libav-tools` (depending on your OS). Hope this helps.

**Comment by pratistha** [comment]
@justinsalamon , Sorry for inconvenience.
Here are the details : 
 operating system - windows 7, python environment - 3.7

loading file in librosa
code: X, sample_rate = librosa.load(fn, duration=5.0)
error:
![image](https://user-images.githubusercontent.com/18647842/45439819-69dbbe00-b6d8-11e8-9917-fd6166af647d.png)

Code i am trying to run
import librosa
import soundfile as sf
X, sample_rate = sf.read(fn)
mfccs = np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=40).T,axis=0)
 
Error with above code : 
Invalid shape for monophonic audio: ndim=2, shape=(176400, 2)

I have installed ffmpeg on my pc but still it doesnt help.

I am using UrbanSound data set.

Let me know if you need any more information.

**Comment by justinsalamon** [comment]
The problem is the audio you are loading has 2 channels (stereo), but the mfcc function in librosa expects monophonic input (single channel). The solution is to downmix your audio into a single channel, where the simplest way to do this is:
```
X, sample_rate = sf.read(fn)
X = X.mean(axis=1)
```
The rest should work.

**Comment by pratistha** [comment]
@justinsalamon , Thanks for your input , it works for that error but still i am facing some error.
As well i am looking for other features as well from librosa library, can you help me to get rid of that errors as well.

Here is my code : 

try:
        X, sample_rate = librosa.load(fn, duration=5.0)
except:
        X, sample_rate = sf.read(fn)
        X = X.mean(axis=0)
stft = np.abs(librosa.stft(X))
mfccs = np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=40).T,axis=0)
chroma = np.mean(librosa.feature.chroma_stft(S=stft, sr=sample_rate).T,axis=0)
mel = np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
contrast = np.mean(librosa.feature.spectral_contrast(S=stft, sr=sample_rate).T,axis=0)
tonnetz = np.mean(librosa.feature.tonnetz(y=librosa.effects.harmonic(X),sr=sample_rate).T,axis=0)


Here are the error i am getting for with respective feature: 

tonnetz:
Input signal length=2 is too short for 7-octave CQT

stft, mfccs, mel:
data must be of type numpy.ndarray

**Comment by justinsalamon** [comment]
@pratistha this doesn't seem to be related to the issue of audio loading any more, nor is it an issue with the librosa library itself, so this is perhaps not the best venue to discuss these issues.

I recommend joining the [librosa mailing list](https://groups.google.com/forum/#!forum/librosa), where you can post questions about using librosa and there's a broader community of users that can provide assistance.

Note that you set `axis=0` instead of `axis=1` when calling `X.mean`, so that's probably the source of most of your errors. 

That said, it might be a good exercise to try and resolve these and similar issues on your own. The error messages give clear indication as to what the issues in your code are (wrong length, wrong data type) and you should be able to resolve them by examining the shape and type of your inputs/outputs and making sure they match what each function expects.



Cheers!

**Comment by pratistha** [comment]
@justinsalamon , indeed its the uses issue of librosa.
Thanks for your help , 
i resolved my errors using  librosa.resample(X, sample_rate, 22050).

**Comment by mohamed27-lab** [comment]
hi i witch all you good pleas i need help whith this error
runfile('C:/Users/younes/anaconda3/lib/site-packages/audioread/sanstitre4.py', wdir='C:/Users/younes/anaconda3/lib/site-packages/audioread')
start
end
Traceback (most recent call last):

  File "C:\Users\younes\anaconda3\lib\site-packages\audioread\sanstitre4.py", line 18, in <module>
    samples, sample_rate = librosa.load(train_audio_path+'yes/00f0204f_nohash_0.wav', sr = 16000)

  File "C:\Users\younes\anaconda3\lib\site-packages\librosa\core\audio.py", line 119, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:

  File "C:\Users\younes\anaconda3\lib\site-packages\audioread\__init__.py", line 107, in audio_open
    backends = available_backends()

  File "C:\Users\younes\anaconda3\lib\site-packages\audioread\__init__.py", line 68, in available_backends
    result = [rawread.RawAudioFile]

AttributeError: module 'audioread.rawread' has no attribute 'RawAudioFile'
i cant find a solution
