### ISSUE TITLE
Will librosa support GPU acceleration?

### ISSUE THREAD

**Issue by diggerdu** [librosa/librosa#481]

**Comment by bmcfee** [comment]
There are not currently plans to directly support GPU acceleration.

There are plans to optimize some functions with numba, which can be configured to run on a GPU.  This will not make it into the next release (0.5), but may be done by the subsequent major revision.  See #157 for details.

**Comment by vinaykumar2491** [comment]
How can I utilize Numba for librosa?

**Comment by lostanlen** [comment]
@vinaykumar2491 Hello. numba is one of librosa's required dependencies, so if you're using librosa, you're already using numba :) 
See https://github.com/librosa/librosa/blob/master/setup.py#L46

Also see this long-running agenda of "numbafying" some low-level functions in librosa to speed them up:
https://github.com/librosa/librosa/issues/157

**Comment by tyoc213** [comment]
Just found https://github.com/qiuqiangkong/torchlibrosa/issues/1

**Comment by lostanlen** [comment]
also worth mentioning is @KinWaiCheuk's nnAudio whose implementation closely matches librosa while being GPU-accelerated and trainable
https://github.com/KinWaiCheuk/nnAudio
