### ISSUE TITLE
Link documentation to the gallery

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#511]
https://github.com/librosa/librosa_gallery is, I think, good enough to link from the main documentation and homepage now.

We should include this in the 0.5 rollout.

**Comment by stefan-balke** [comment]
Maybe these can also go into the library:

* https://github.com/stefan-balke/mpa-exc/blob/master/03_music_sync/dtw_audio_sync.ipynb
* https://github.com/stefan-balke/mpa-exc/blob/master/04_music_structure/self_similarity_matrix.ipynb

**Comment by bmcfee** [comment]
Wanna PR them to the gallery repo? :grinning:

**Comment by stefan-balke** [comment]
Yeah, sure, why not. Good to have everything together.

**Comment by r9y9** [comment]
Cool! I was an audio-to-score alignment guy. I'm happy to see the example!
