### ISSUE TITLE
CQTs with identical parameters except f_min have different shapes

### ISSUE THREAD

**Issue by rabitt** [librosa/librosa#515]
I'm using librosa version `0.5.0rc0`.

The following code snippet:
```python
y, sr = librosa.load(audio_fpath, sr=22050)

for h in [1, 2, 3, 4, 5, 6]:
    cqt = librosa.cqt(
        y, sr=sr, hop_length=128, fmin=32.7*float(h),
        n_bins=120*5, bins_per_octave=120
    )
    print(cqt.shape)
```
Produces the following output:
```python
(600, 37521)
(600, 37521)
(600, 37520)
(600, 37520)
(600, 37520)
(600, 37520)
```

I wouldn't expect the minimum frequency to affect the number of time frames. This seems like a bug?

The audio file used to produce this output is [here](https://drive.google.com/file/d/0B72xIeDqCfuUa1psdVpvdkNYY2c/view?usp=sharing).

**Comment by bmcfee** [comment]
I wouldn't call this a "bug" per se, but it is non-obvious behavior.

What's going on is that CQT does recursive downsampling of the input signal.  The amount of downsampling depends on the highest frequency you're trying to measure, so the lower the frequency (eg h=1 in your example), the more downsampling you get.  Depending on the length of the input signal, rounding of sample indices might lose a frame, as you observe here.

You can probably get around this by zero-padding your signal prior to calling CQT.  Padding up to an integer number of frames (where frame length = max cqt filter length) ought to do the trick.

Alternately, if you don't need to be that precise about it, the frames should line up in your example, so dropping the last frame in the first two outputs ought to be okay.

**Comment by bmcfee** [comment]
Note: the semantics in librosa are that frame `i` is centered at sample `i * hop_length`, so dropping the last frame in your example should be totally fine.

**Comment by rabitt** [comment]
👍

**Comment by bmcfee** [comment]
@rabitt Any reason to not close this issue?
