### ISSUE TITLE
Librosa.amplitude_to_db error

### ISSUE THREAD

**Issue by AKBoles** [librosa/librosa#522]
The following code snippet gives an error:

> AttributeError: 'module' object has no attribute 'amplitude_to_db'

`y_stft1 = librosa.stft(y=y)
librosa.display.specshow(librosa.amplitude_to_db(y_stft1, ref=np.max), y_axis='log', x_axis='time')`

This happened while using version _librosa-0.5.0_. Is there a reason for this occurring?

**Comment by bmcfee** [comment]
That's strange. Can you print out `librosa.__version__` and `dir(librosa.core)` and report the results?

**Comment by AKBoles** [comment]
After re-running the pip install upgrade command, both read out with `0.5.0` and a list including the `amplitude_to_db` command. It now works correctly, do not know the error - I had run the same upgrade command before originally, perhaps it was due to my Jupyter Notebook not being reset. Regardless, all good now, thank you.
