### ISSUE TITLE
ASSIGNMENT: Contribution, new features, documentation (Uni-class project)

### ISSUE THREAD

**Issue by alevas** [librosa/librosa#525]
Good afternoon Librosa,

I am a student of the Athens University of Economics and Business, Department of Management Science & Technology. In the context of the Software Engineering in Practice course I am attending this semester, I must choose a project to contribute in it's source code.

I would like to contribute to Librosa, work on developing new features, contribute to the documentation or anything else you may have to suggest!

Thank you in advance.

Your sincerely,
Alexandros Vasileiou

**Comment by bmcfee** [comment]
Sure, any help is appreciated!

There are plenty of open issues already, and we're open to suggestions as well.  I suppose it depends on what the scope of the project should be, and your specific background and expertise.

**Comment by bmcfee** [comment]
I'm not sure if you're still interested in this, but I took some time to go through and tag some issues as `"good for beginners"`.  These issues are meant to be self-contained problems that require changes to only a small portion of the codebase.

**Comment by alevas** [comment]
Hi! Sorry for not coming back to you sooner, in the context of this class, I had to go with another project. However I am still interested in participating in this community in the immediate future (hopefully during the summer) when I will have more time. 

Hope it's OK, I appreciate you going through the trouble to tag these issues and apologize for any inconvenience :-)

**Comment by bmcfee** [comment]
> Hope it's OK, I appreciate you going through the trouble to tag these issues

No problem, it needed to be done anyway.  Shall we close this issue out?

**Comment by alevas** [comment]
Yes it shouldn't be open anymore. How should I contact you in the future?
