### ISSUE TITLE
display not included in __init__py

### ISSUE THREAD

**Issue by GPrathap** [librosa/librosa#526]
I want to use `librosa.display.specshow(self.mfcc[i], x_axis='time')` function. But I am getting an error something similler to this .
```
librosa.display.specshow(self.mfcc[i], x_axis='time')
AttributeError: 'module' object has no attribute 'display'

```
When I see the source code I see even display util is there, it hasn't been included in  __init__.py which is located in util directory. 

Environment: 0.5.0

**Comment by stefan-balke** [comment]
Yep, display module is now separate. If you want to use it call

"import librosa.display"

Am 11.03.2017 um 20:45 schrieb Geesara Prathap <notifications@github.com<mailto:notifications@github.com>>:


I want to use librosa.display.specshow(self.mfcc[i], x_axis='time') function. But I am getting an error something similler to this .

librosa.display.specshow(self.mfcc[i], x_axis='time')
AttributeError: 'module' object has no attribute 'display'



When I see the source code I see even display util is there, it hasn't been included in init.py which is located in util directory.

Environment: 0.5.0

**Comment by GPrathap** [comment]
Hi stefan,

Yes, it works, Thanks for the prompt response. You can close this issue.

Thanks,
Geesara

**Comment by lukasab** [comment]
In the documentation, this is not updated. I followed [this](https://librosa.github.io/librosa/generated/librosa.display.specshow.html) tutorial and ended up here after the import error.
