### ISSUE TITLE
Trim not working?

### ISSUE THREAD

**Issue by shaolo1** [librosa/librosa#532]
[F1.wav.zip](https://github.com/librosa/librosa/files/856795/F1.wav.zip)

I'm trying to remove silence using librosa.  The attached code shows it working with pyDub, but I can't figure out the right arguments to get libRosa do do the same thing.

```
    import pydub
    from pydub import AudioSegment

    # from http://stackoverflow.com/questions/29547218/remove-silence-at-the-beginning-and-at-the-end-of-wave-files-with-pydub
    def detect_leading_silence(sound, silence_threshold=-50.0, chunk_size=10):
        '''
        sound is a pydub.AudioSegment
        silence_threshold in dB
        chunk_size in ms

        iterate over chunks until you find the first one with sound
        '''
        trim_ms = 0
        while sound[trim_ms:trim_ms+chunk_size].dBFS < silence_threshold:
            trim_ms += chunk_size
        return trim_ms

    # pydub
    sound = AudioSegment.from_file("F1.wav", format="wav")
    start_trim = detect_leading_silence(sound)
    end_trim = detect_leading_silence(sound.reverse())
    print('start_trim', start_trim, 'end_trim', end_trim)
    duration = len(sound)
    trimmed_sound = sound[start_trim:duration-end_trim]
    print('pd old duration', len(sound)/1000, 'pd new duration', len(trimmed_sound)/1000)
    trimmed_sound.export("F1_trimmed.wav", format="wav")
    sound = AudioSegment.from_file("F1_trimmed.wav", format="wav")
    print('pd trimmed duration', len(sound)/1000)

    # librosa
    samples, sample_rate = librosa.load('F1.wav')
    delta = sample_rate // 1000 * 10
    trimmed_samples, index = librosa.effects.trim(samples) # , frame_length=delta, hop_length=delta, top_db=50)
    print('lr old duration', librosa.get_duration(samples), 'lr new duration', librosa.get_duration(trimmed_samples))

    librosa.output.write_wav('F1_trimmed_lr.wav', trimmed_samples, sr=sample_rate)
    samples, sample_rate = librosa.load('F1_trimmed_lr.wav')
    print('lr trimmed duration', librosa.get_duration(samples))

```

The trimming with pyDub removes way more than libRosa.  I tried fiddling with the top_db, frame_length, and hop_length, but just can't libRosa to trim all the silence.

My results are as follows..

```
librosa ver: 0.5.0
start_trim 490 end_trim 410
pd old duration 1.444 pd new duration 0.544
pd trimmed duration 0.544
lr old duration 1.4439909297052154 lr new duration 0.9578231292517007
lr trimmed duration 0.9578231292517007

```

As a further comparison point, I loaded the file into Audacity and used its trim silence effect supplying -50db and .01 seconds compress to 0 seconds.  The resulting file was slightly longer, but close to pyDub at 0.629 seconds.

Assuming there's not a bug, any help would be much appreciated.

**Comment by bmcfee** [comment]
I think there are two things going on here:

1. You're not supplying the `top_db` parameter to match the method you're comparing to
2. I suspect librosa uses a different (default) reference power than pydub.

With your example file, I get the following
```python
In [2]: y, sr = librosa.load('F1.wav', sr=None)

In [7]: yt, idx = librosa.effects.trim(y=y, top_db=50, ref=1)

In [8]: librosa.get_duration(yt, sr=sr)
Out[8]: 0.5688888888888889

In [11]: yt, idx = librosa.effects.trim(y=y, top_db=50, ref=np.max)

In [12]: librosa.get_duration(yt, sr=sr)
Out[12]: 0.9636281179138322
```

Note that `ref=np.max` is the default for librosa, but here I've made it explicit in the second example.  Given that setting `ref=1` (effectively disabling reference power comparison, since `log(1) == 0`) gives a pretty close answer to pydub, I think that's probably to blame.  The other minor differences (0.57 vs 0.54) probably come down to differences in the frame and hop length parameters.  If you crank those down, it looks pretty close to pydub:

```python
In [25]: yt, idx = librosa.effects.trim(y=y, top_db=50, ref=1, hop_length=64, frame_length=512)

In [26]: librosa.get_duration(yt, sr=sr)
Out[26]: 0.5471201814058957
```

**Comment by shaolo1** [comment]
Thank you so much!  I probably would have never figured out it was the ref argument.
