### ISSUE TITLE
Error with librosa.load()

### ISSUE THREAD

**Issue by lwaldner** [librosa/librosa#536]
Whenever I try to load any audiofile with librosa I get the following error:

Python 3.4.3 (default, Nov 17 2016, 01:08:31)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import librosa
>>> filename = librosa.util.example_audio_file()
>>> librosa.load(filename)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Dev/MegsAnalysis/flask/lib/python3.4/site-packages/librosa/core/audio.py", line 149, in load
    y.append(frame)
  File "/mnt/c/Dev/MegsAnalysis/flask/lib/python3.4/site-packages/audioread/ffdec.py", line 252, in __exit__
    self.close()
  File "/mnt/c/Dev/MegsAnalysis/flask/lib/python3.4/site-packages/audioread/ffdec.py", line 237, in close
    self.proc.kill()
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process

I have ffmpeg which I have verified works and all other dependencies installed. I am at a total loss of how to resolve this any could use any and all help

**Comment by lwaldner** [comment]
Using Ubuntu 14 and python3

**Comment by bmcfee** [comment]
That's a strange one, but it looks like a problem with audioread, not librosa.  Are you able to open files directly with audioread?

**Comment by lwaldner** [comment]
It appears so

Python 3.4.3 (default, Nov 17 2016, 01:08:31)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import audioread
>>> audioread.audio_open("test.wav")
<audioread.ffdec.FFmpegAudioFile object at 0x7f9ad7ac8cf8>

**Comment by bmcfee** [comment]
Can you read from the file and close it though? It looks like the error was happening at the end of reading.

**Comment by lwaldner** [comment]
yeah this error also happens when I try to close it

Python 3.4.3 (default, Nov 17 2016, 01:08:31)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import audioread
>>> obj = audioread.audio_open("test.wav")
>>> obj.close()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Dev/MegsAnalysis/flask/lib/python3.4/site-packages/audioread/ffdec.py", line 237, in close
    self.proc.kill()
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process

**Comment by bmcfee** [comment]
Okay, I think it's definitely an audioread but then. Best to take it up with them.

Meanwhile, if you can't wait for a fix and the format is just shoot anything but mp3, you could do io with pysoundfile instead.

**Comment by lwaldner** [comment]
I am running this on the Linux subsystem on Windows 10 which may be the issue. But thanks for the help!

**Comment by chausies** [comment]
@bmcfee Pysoundfile works great! Is there any reason you can't move to using pysoundfile instead of audioread? Not only does it seem to be more robust and work with a wide range of filetypes (like ogg), but for me, it's loading even wav files much much faster than `librosa.load`.

**Comment by bmcfee** [comment]
@chausies yes: libsndfile does not support mp3 (though there's an open PR now), and that's a deal-breaker for many librosa users.

When libsndfile does get mp3 support, we'll revisit the load implementation and see if it makes sense to swap out the dependencies.

**Comment by llamasoft** [comment]
This issue is officially fixed for audioread on Windows Subsystem for Linux as of today:
https://github.com/beetbox/audioread/issues/51

It may be a bit before the pypi version is updated though.
