### ISSUE TITLE
Librosa.feature.sync AttributeError

### ISSUE THREAD

**Issue by kkmcd** [librosa/librosa#541]
<img width="411" alt="sync" src="https://cloud.githubusercontent.com/assets/23444643/24580115/8aa9b600-173d-11e7-9476-fa8eafb6a4a2.png">

i am doing Librosa tutorial. but i have a problem which module 'librosa.feature' has no attribute 'sync'.
How can i solve this problem?

**Comment by bmcfee** [comment]
Eek, the tutorial must have falling out of date.  `sync` was moved from `feature` to `util`.

I'll fix this in the next revision.

**Comment by kkmcd** [comment]
yeah, thanks. I fixed this problem.
