### ISSUE TITLE
AttributeError: module 'librosa' has no attribute 'load'

### ISSUE THREAD

**Issue by XUFANCODE** [librosa/librosa#542]

**Comment by bmcfee** [comment]
That's strange.  Could you provide more information?  What version do you have installed, what is your environment, how are you importing, etc.?

**Comment by XUFANCODE** [comment]
Thinks. Problem was sovled. It happened when i want to run "https://github.com/ruohoruotsi/LSTM-Music-Genre-Classification" lstm_genre_classifier_keras.py.
