### ISSUE TITLE
librosa.feature.rmse (time-domain signal bug?)

### ISSUE THREAD

**Issue by SungkyunC** [librosa/librosa#546]
According to the [Document](https://librosa.github.io/librosa/generated/librosa.feature.rmse.html), RMSE computes root-mean-square energy of chunk (given a frame_length). 

![latex_08325a039ecfad56c2a85893b66c3488](https://cloud.githubusercontent.com/assets/26891722/24718752/1a06bab4-1a72-11e7-8a8a-1c00a02a4810.png)
, where n is the frame_length.

I was using librosa 0.5.0
>Parameters:	
y : np.ndarray [shape=(n,)] or None
>(optional) audio time series. Required if S is not input.
>
>S : np.ndarray [shape=(d, t)] or None
>(optional) spectrogram magnitude. Required if y is not input.
>
>frame_length : int > 0 [scalar]
>length of analysis frame (in samples) for energy calculation

![default](https://cloud.githubusercontent.com/assets/26891722/24719421/a80e5392-1a74-11e7-82de-0f231020819f.PNG)

The result should be (in Matlab)
![matlab_rms](https://cloud.githubusercontent.com/assets/26891722/24720001/aeb66796-1a76-11e7-9999-262b0cf79b2a.PNG)

Plz check if I'm wrong.

**Comment by karoldvl** [comment]
Your input vector has a wrong shape (it needs to be `(n,)`), plus you're using the default `hop_length` of 512. 

Try something like this instead:
```python
>>> y = np.array([.5, 0, -.5 ,1])
>>> librosa.feature.rmse(y, frame_length=2, hop_length=1)
array([[ 0.35355339,  0.35355339,  0.79056942]])
```

**Comment by SungkyunC** [comment]
@karoldvl Thanks!!!
