### ISSUE TITLE
Error Installing SciPy & Librosa

### ISSUE THREAD

**Issue by aspencerpsu** [librosa/librosa#560]
#### Description
Hi I'm trying to install the librosa through the pip package manager and come into a very long and verbose traceback error with the following recommendations:

Does it have anything to do with the math atlas lib not being found? If the package error can be resolved on the command line, sorry for such an easy problem to resolve.

#### Steps/Code to Reproduce
pip install librosa
-->

#### Expected Results
succesffully installed librosa version #

#### Actual Results
' Building wheels for collected packages: scipy\n  Running setup.py bdist_wheel for scipy: started\n  Running setup.py bdist_wheel for scipy: finished with status \'error\'\n  Complete output from command c:\\python2712\\python.exe -u -c "import setuptools    , tokenize;__file__=\'c:\\users\\user~1\\appdata\\local\\temp\\pip-build-k3hrmx    \\scipy\\setup.py\';f=getattr(tokenize, \'open\', open)(__file__);code=f.read().rep    lace(\'\r\n\', \'\n\');f.close();exec(compile(code, __file__, \'exec\'))" bdist_wheel     -d c:\\users\x07keems~1\x07ppdata\\local\temp\tmpynhpmapip-wheel- --python-tag cp27:\n  lapack_opt_info:\n  openblas_lapack_info:\n    libraries openblas not found in [\'c:\\python2712\\lib\', \'C:\\\', \'c:\\python2    712\\libs\']\n    NOT AVAILABLE\n\n  lapack_mkl_info:\n    libraries mkl_rt not found in [\'c:\\python2712\\lib\', \'C:\\\', \'c:\\python271    2\\libs\']\n    NOT AVAILABLE\n\n  atlas_3_10_threads_info:\n  Setting PTATLAS=ATLAS\n  c:\\python2712\\lib\\site-packages\numpy\\distutils\\system_info.py:639: UserWarnin    g: Specified path C:\\projects\numpy-wheels\\windows-wheel-builder\x07tlas-builds\x07t    las-3.11.38-sse2-64\\lib is invalid.\n    warnings.warn(\'Specified path %s is invalid.\' % d)\n  <class \'numpy.distutils.system_info.atlas_3_10_threads_info\'>\n    NOT AVAILABLE\n\n  atlas_3_10_info:\n  <class \'numpy.distutils.system_info.atlas_3_10_info\'>\n    NOT AVAILABLE\n\n  atlas_threads_info:\n  Setting PTATLAS=ATLAS\n  <class \'numpy.distutils.system_info.atlas_threads_info\'>\n    NOT AVAILABLE\n\n  atlas_info:\n  <class \'numpy.distutils.system_info.atlas_info\'>\n    NOT AVAILABLE\n\n  c:\\python2712\\lib\\site-packages\numpy\\distutils\\system_info.py:1532: UserWarni    ng:\n      Atlas (http://math-atlas.sourceforge.net/) libraries not found.\n      Directories to search for the libraries can be specified in the\n      numpy/distutils/site.cfg file (section [atlas]) or by setting\n      the ATLAS environment variable.\n    warnings.warn(AtlasNotFoundError.__doc__)\n  lapack_info:\n    libraries lapack not found in [\'c:\\python2712\\lib\', \'C:\\\', \'c:\\python271    2\\libs\']\n    NOT AVAILABLE\n\n  c:\\python2712\\lib\\site-packages\numpy\\distutils\\system_info.py:1543: UserWarni    ng:\n      Lapack (http://www.netlib.org/lapack/) libraries not found.\n      Directories to search for the libraries can be specified in the\n      numpy/distutils/site.cfg file (section [lapack]) or by setting\n      the LAPACK environment variable.\n    warnings.warn(LapackNotFoundError.__doc__)\n  lapack_src_info:\n    NOT AVAILABLE\n\n  c:\\python2712\\lib\\site-packages\numpy\\distutils\\system_info.py:1546: UserWarni    ng:\n      Lapack (http://www.netlib.org/lapack/) sources not found.\n      Directories to search for the sources can be specified in the\n      numpy/distutils/site.cfg file (section [lapack_src]) or by setting\n      the LAPACK_SRC environment variable.\n    warnings.warn(LapackSrcNotFoundError.__doc__)\n    NOT AVAILABLE\n\n  Running from scipy source directory.\n  non-existing path in \'scipy\\integrate\': \'quadpack.h\'\n  Traceback (most recent call last):\n    File "<string>", line 1, in <module>\n    File "c:\\users\x07keems~1\x07ppdata\\local\temp\\pip-build-k3hrmx\\scipy\\setup.py",     line 416, in <module>\n      setup_package()\n    File "c:\\users\x07keems~1\x07ppdata\\local\temp\\pip-build-k3hrmx\\scipy\\setup.py",     line 412, in setup_package\n      setup(**metadata)\n    File "c:\\python2712\\lib\\site-packages\numpy\\distutils\\core.py", line 135, in     setup\n      config = configuration()\n    File "c:\\users\x07keems~1\x07ppdata\\local\temp\\pip-build-k3hrmx\\scipy\\setup.py",     line 336, in configuration\n      config.add_subpackage(\'scipy\')\n    File "c:\\python2712\\lib\\site-packages\numpy\\distutils\\misc_util.py", line 10    00, in add_subpackage\n      caller_level = 2)\n    File "c:\\python2712\\lib\\site-packages\numpy\\distutils\\misc_util.py", line 96    9, in get_subpackage\n      caller_level = caller_level + 1)\n    File "c:\\python2712\\lib\\site-packages\numpy\\distutils\\misc_util.py", line 90    6, in _get_configuration_from_setup_py\n      config = setup_module.configuration(*args)\n    File "scipy\\setup.py", line 15, in configuration\n      config.add_subpackage(\'linalg\')\n    File "c:\\python2712\\lib\\site-packages\numpy\\distutils\\misc_util.py", line 10    00, in add_subpackage\n      caller_level = 2)\n    File "c:\\python2712\\lib\\site-packages\numpy\\distutils\\misc_util.py", line 96    9, in get_subpackage\n      caller_level = caller_level + 1)\n    File "c:\\python2712\\lib\\site-packages\numpy\\distutils\\misc_util.py", line 90    6, in _get_configuration_from_setup_py\n      config = setup_module.configuration(*args)\n    File "scipy\\linalg\\setup.py", line 20, in configuration\n      raise NotFoundError(\'no lapack/blas resources found\')\n  numpy.distutils.system_info.NotFoundError: no lapack/blas resources found\n\n  ----------------------------------------\n  Failed building wheel for scipy\n  Running setup.py clean for scipy\n  Complete output from command c:\\python2712\\python.exe -u -c "import setuptools    , tokenize;__file__=\'c:\\users\\user~1\\appdata\\local\\temp\\pip-build-k3hrmx    \\scipy\\setup.py\';f=getattr(tokenize, \'open\', open)(__file__);code=f.read().rep    lace(\'\r\n\', \'\n\');f.close();exec(compile(code, __file__, \'exec\'))" clean --all:\n\n  `setup.py clean` is not supported, use one of the following instead:\n\n    - `git clean -xdf` (cleans all files)\n    - `git clean -Xdf` (cleans all versioned files, doesn\'t touch\n                        files that aren\'t checked into the git repo)\n\n  Add `--force` to your command to use it anyway if you must (unsupported).\n\n\n  ----------------------------------------\n  Failed cleaning build dir for scipy\nFailed to build scipy\nInstalling collected packages: scipy, resampy, joblib, librosa\n  Running setup.py install for scipy: started\n    Running setup.py install for scipy: finished with status \'error\'\n    Complete output from command c:\\python2712\\python.exe -u -c "import setuptoo    ls, tokenize;__file__=\'c:\\users\\user~1\\appdata\\local\\temp\\pip-build-k3hr    mx\\scipy\\setup.py\';f=getattr(tokenize, \'open\', open)(__file__);code=f.read().r    eplace(\'\r\n\', \'\n\');f.close();exec(compile(code, __file__, \'exec\'))" install --    record c:\\users\x07keems~1\x07ppdata\\local\temp\\pip-j06txg-record\\install-record.txt     --single-version-externally-managed --compile:\n\n    Note: if you need reliable uninstall behavior, then install\n    with pip instead of using `setup.py install`:\n\n      - `pip install .`       (from a git repo or downloaded source\n                               release)\n      - `pip install scipy`   (last SciPy release on PyPI)\n\n\n    lapack_opt_info:\n    openblas_lapack_info:\n      libraries openblas not found in [\'c:\\python2712\\lib\', \'C:\\\', \'c:\\pytho    n2712\\libs\']\n      NOT AVAILABLE\n\n    lapack_mkl_info:\n      libraries mkl_rt not found in [\'c:\\python2712\\lib\', \'C:\\\', \'c:\\python2    712\\libs\']\n      NOT AVAILABLE\n\n    atlas_3_10_threads_info:\n    Setting PTATLAS=ATLAS\n    c:\\python2712\\lib\\site-packages\numpy\\distutils\\system_info.py:639: UserWarn    ing: Specified path C:\\projects\numpy-wheels\\windows-wheel-builder\x07tlas-builds\\    atlas-3.11.38-sse2-64\\lib is invalid.\n      warnings.warn(\'Specified path %s is invalid.\' % d)\n    <class \'numpy.distutils.system_info.atlas_3_10_threads_info\'>\n      NOT AVAILABLE\n\n    atlas_3_10_info:\n    <class \'numpy.distutils.system_info.atlas_3_10_info\'>\n      NOT AVAILABLE\n\n    atlas_threads_info:\n    Setting PTATLAS=ATLAS\n    <class \'numpy.distutils.system_info.atlas_threads_info\'>\n      NOT AVAILABLE\n\n    atlas_info:\n    <class \'numpy.distutils.system_info.atlas_info\'>\n      NOT AVAILABLE\n\n    c:\\python2712\\lib\\site-packages\numpy\\distutils\\system_info.py:1532: UserWar    ning:\n        Atlas (http://math-atlas.sourceforge.net/) libraries not found.\n        Directories to search for the libraries can be specified in the\n        numpy/distutils/site.cfg file (section [atlas]) or by setting\n        the ATLAS environment variable.\n      warnings.warn(AtlasNotFoundError.__doc__)\n    lapack_info:\n      libraries lapack not found in [\'c:\\python2712\\lib\', \'C:\\\', \'c:\\python2    712\\libs\']\n      NOT AVAILABLE\n\n    c:\\python2712\\lib\\site-packages\numpy\\distutils\\system_info.py:1543: UserWar    ning:\n        Lapack (http://www.netlib.org/lapack/) libraries not found.\n        Directories to search for the libraries can be specified in the\n        numpy/distutils/site.cfg file (section [lapack]) or by setting\n        the LAPACK environment variable.\n      warnings.warn(LapackNotFoundError.__doc__)\n    lapack_src_info:\n      NOT AVAILABLE\n\n    c:\\python2712\\lib\\site-packages\numpy\\distutils\\system_info.py:1546: UserWar    ning:\n        Lapack (http://www.netlib.org/lapack/) sources not found.\n        Directories to search for the sources can be specified in the\n        numpy/distutils/site.cfg file (section [lapack_src]) or by setting\n        the LAPACK_SRC environment variable.\n      warnings.warn(LapackSrcNotFoundError.__doc__)\n      NOT AVAILABLE\n\n    Running from scipy source directory.\n    non-existing path in \'scipy\\integrate\': \'quadpack.h\'\n    Traceback (most recent call last):\n      File "<string>", line 1, in <module>\n      File "c:\\users\x07keems~1\x07ppdata\\local\temp\\pip-build-k3hrmx\\scipy\\setup.py    ", line 416, in <module>\n        setup_package()\n      File "c:\\users\x07keems~1\x07ppdata\\local\temp\\pip-build-k3hrmx\\scipy\\setup.py    ", line 412, in setup_package\n        setup(**metadata)\n      File "c:\\python2712\\lib\\site-packages\numpy\\distutils\\core.py", line 135,     in setup\n        config = configuration()\n      File "c:\\users\x07keems~1\x07ppdata\\local\temp\\pip-build-k3hrmx\\scipy\\setup.py    ", line 336, in configuration\n        config.add_subpackage(\'scipy\')\n      File "c:\\python2712\\lib\\site-packages\numpy\\distutils\\misc_util.py", line     1000, in add_subpackage\n        caller_level = 2)\n      File "c:\\python2712\\lib\\site-packages\numpy\\distutils\\misc_util.py", line     969, in get_subpackage\n        caller_level = caller_level + 1)\n      File "c:\\python2712\\lib\\site-packages\numpy\\distutils\\misc_util.py", line     906, in _get_configuration_from_setup_py\n        config = setup_module.configuration(*args)\n      File "scipy\\setup.py", line 15, in configuration\n        config.add_subpackage(\'linalg\')\n      File "c:\\python2712\\lib\\site-packages\numpy\\distutils\\misc_util.py", line     1000, in add_subpackage\n        caller_level = 2)\n      File "c:\\python2712\\lib\\site-packages\numpy\\distutils\\misc_util.py", line     969, in get_subpackage\n        caller_level = caller_level + 1)\n      File "c:\\python2712\\lib\\site-packages\numpy\\distutils\\misc_util.py", line     906, in _get_configuration_from_setup_py\n        config = setup_module.configuration(*args)\n      File "scipy\\linalg\\setup.py", line 20, in configuration\n        raise NotFoundError(\'no lapack/blas resources found\')\n    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found\n\n    ----------------------------------------\nCommand "c:\\python2712\\python.exe -u -c "import setuptools, tokenize;__file__=\'c    :\\users\\user~1\\appdata\\local\\temp\\pip-build-k3hrmx\\scipy\\setup.py\';f=g    etattr(tokenize, \'open\', open)(__file__);code=f.read().replace(\'\r\n\', \'\n\');f.c    lose();exec(compile(code, __file__, \'exec\'))" install --record c:\\users\x07keems~1    \x07ppdata\\local\temp\\pip-j06txg-record\\install-record.txt --single-version-extern    ally-managed --compile" failed with error code 1 in c:\\users\x07keems~1\x07ppdata\\lo    cal\temp\\pip-build-k3hrmx\\scipy'

#### Versions
Platform - *Windows-10-10.0.14393*
Sys - *Windows-10.0.14393*
Numpy - *1.11.3*

**Comment by bmcfee** [comment]
> Does it have anything to do with the math atlas lib not being found? If the package error can be resolved on the command line, sorry for such an easy problem to resolve.

Yes, I think so.  This all appears to be problems due to getting scipy installed, and probably are not specific to librosa.  You may also hit problems with getting `resampy` installed though, see #533 .

**Comment by bmcfee** [comment]
This problem should be resolved by resampy 0.2.0.  Any other install issues will be due to unrelated problems, so I'm closing this one out.
