### ISSUE TITLE
undefined symbol: PyUnicodeUCS2

### ISSUE THREAD

**Issue by inspiralpatterns** [librosa/librosa#561]
I cannot load _librosa_ in python **2.7.13 UCS4**.
When trying to import it:

`import librosa`
`Traceback (most recent call last):`
  `File "<stdin>", line 1, in <module>`
  `File "/zhome/59/b/116311/.local/lib/python2.7/site-packages/librosa/__init__.py", line 11, in <module>`
    `from . import core
  File "/zhome/59/b/116311/.local/lib/python2.7/site-packages/librosa/core/__init__.py", line 109, in <module>`
    `from .audio import *  # pylint: disable=wildcard-import`
  `File "/zhome/59/b/116311/.local/lib/python2.7/site-packages/librosa/core/audio.py", line 12, in <module>`
    `import resampy`
  `File "/zhome/59/b/116311/.local/lib/python2.7/site-packages/resampy/__init__.py", line 7, in <module>`
    `from .core import *`
  `File "/zhome/59/b/116311/.local/lib/python2.7/site-packages/resampy/core.py", line 8, in <module>`
   ` from .interp import resample_f`
`ImportError: /zhome/59/b/116311/.local/lib/python2.7/site-packages/resampy/interp.so: undefined symbol: PyUnicodeUCS2_Format`

These are the specifics:
`Linux-2.6.32-642.15.1.el6.x86_64-x86_64-with-redhat-6.4-Carbon`
`('Python', '2.7.13 (default, Apr  6 2017, 10:22:26) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)]')`
`('NumPy', '1.12.1')`
`('SciPy', '0.19.0')`
Librosa version is **0.5.0**

**Comment by bmcfee** [comment]
This appears to be a resampy error, not a librosa error.

Are you sure that resampy was compiled with the version of python you're using?

Alternately, a quick google search popped up this: https://stackoverflow.com/questions/2584198/undefined-symbol-pyunicodeucs2-decode-whilst-trying-to-install-psycopg2

**Comment by inspiralpatterns** [comment]
Completely right.
I don't know why, but I had to reinstall lots of packages - but it works eventually.
I'm closing the issue.
Thanks for your help.
