### ISSUE TITLE
rasterize specshow

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#562]
#### Description
In 0.5, we switched `specshow` from using `imshow` under the hood to `pcolormesh`.  While this gives us a bit more flexibility for pixel layout, it does result in heavyweight figures.

I find myself manually [rasterizing](http://www.astrobetter.com/blog/2014/01/17/slim-down-your-bloated-graphics/) `specshow` plots often, to the point where I'm wondering if it should be baked in as a default option, enabled by default, but easy to override by `librosa.display.specshow(..., rasterized=False)`.

What do folks think?

**Comment by bmcfee** [comment]
Gist demonstrating the savings [here](https://gist.github.com/1c860a86d18085347dbc85aee385c755).  TLDR: a 10-second spectrogram plot gets a 98% reduction in pdf size.

I see no reason not to rasterize by default.  PR coming later today.

**Comment by stefan-balke** [comment]
Sounds good to me. Is this then the same raasterization method which is used in `imshow()`?

**Comment by bmcfee** [comment]
I don't know if it's the same exactly, since pcolormesh and imshow are pretty different under the hood.

However, since we're only rasterizing the resulting mesh, and not any of the other elements of the plot, it shouldn't have any noticeable artifacts.
