### ISSUE TITLE
Tempo Incorrect

### ISSUE THREAD

**Issue by Willian-Zhang** [librosa/librosa#568]
#### Description

Tempo Incorrect for both dynamic and non-dynamic

#### Steps/Code to Reproduce
Example:

for song [BASARA](https://www.youtube.com/watch?v=puV-8De553I)

#### Expected Results
BPM: 130

#### Actual Results
BPM: ~128

#### Fixes
see fixes PR: #567 #566

**Comment by stefan-balke** [comment]
Hey @Willian-Zhang,

thanks for your enhancements, but could you give more details?
We now have a template for filing bugs/enhancements.
And some plots would be helpful, since your PRs don't have
any unit-tests yet.

Thanks!

## Template:

```
<!-- Instructions For Filing a Bug: https://github.com/librosa/librosa/blob/master/CONTRIBUTING.md#filing-bugs -->

#### Description
<!-- Example: Error when computing spectral_contrast on a single frame-->

#### Steps/Code to Reproduce
<!--
Example:

If the code is too long, feel free to put it in a public gist and link
it in the issue: https://gist.github.com
-->

#### Expected Results
<!-- Example: contrast should have shape (1, 1)-->

#### Actual Results
<!-- Please paste or specifically describe the actual output or traceback. -->

#### Versions
<!--
Please run the following snippet and paste the output below.
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import librosa; print("librosa", librosa.__version__)
-->


<!-- Thanks for contributing! -->
```

**Comment by Willian-Zhang** [comment]
Actually I'm not sure how I can demostrate the problem without giving an real example of music. 
I think the problem is not relate to any "bugs" of code or anything relevant to my running env.

Also how I identity the problem is to compare the result with multiple musics and their meta datas. The difference is pretty trivial yet noticeable for certain needs.

**Comment by Willian-Zhang** [comment]
I posted an formula to calculate how it would builds up to rhythm game beat tracking and how much impact would result in here:
https://github.com/OSU-Mapper/osu-audio-feature-extract/issues/2

**Comment by bmcfee** [comment]
This one has been silent for over a year at this point, so I'd like to close it out.  As I understand it, @Willian-Zhang is not suggesting that there's anything "wrong" with the code, just that the estimator isn't perfect.  This might just be a matter of tuning the default parameters to work better with the content in question.  However, if @Willian-Zhang can provide some concrete suggestions for improving the tempo estimator, I'd be happy to consider revising the implementation.  Until then, I don't see much to do here.
