### ISSUE TITLE
conda package issue: Windows, Python3.6

### ISSUE THREAD

**Issue by meowklaski** [librosa/librosa#575]
#### Description
"UnsatisfiableError" when installing librosa from conda-forge, on Python 3.6-Windows environment

 
#### Steps/Code to Reproduce
Running anaconda on Windows 10, in a Python 3.6 environment, trying to install librosa in this environment:
```shell
> conda info -c conda-forge librosa
```

#### Actual Results
```shell
UnsatisfiableError: The following specifications were found to be in conflict:
  - librosa -> python 3.4*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

This is particularly strange, since I am able to install the package on a Python 3.5 anaconda environment, even though the error seems to indicate that it need Python 3.4. Was the wrong file uploaded for 3.6?

#### Versions
```shell
> conda list
...
python                    3.6.1                         2
...
```

**Comment by bmcfee** [comment]
That's interesting, thanks for reporting it.

Don't worry -- the wrong file was not uploaded for 3.6.

Looking at the [appveyor config](https://github.com/librosa/librosa-feedstock/blob/master/appveyor.yml#L16-L31) in the feedstock, it looks like we only have windows builds for 2.7 and 3.5 currently deploying.  (The 0.5.0 release had a target for 3.4.)  It appears that conda-smithy reverted out some of the other build targets.

This seems to also be the case for resampy, which librosa depends on, so I'll have to do some investigating there before pushing it up to librosa.

**Comment by benholtzman** [comment]
hi, 
had the same problem with linux (ubuntu 16), with similar errors. i haven't tried on mac. 
3.6 compatibility would be great whenever you can get to it-- 
Thanks!! 
Ben

**Comment by LLrsokl** [comment]
Any idea what the timeline will be on this? I plan on using `librosa` for a class that I am teaching this summer, and hope that students with Python 3.6 will be able to conda-install it

**Comment by bmcfee** [comment]
I'll take a stab at it tomorrow, but can't guarantee that it will be resolved immediately.

**Comment by LLrsokl** [comment]
Thanks for the quick response. It wouldn't be a show stopper for the course, since conda-installing ffmpeg takes care of the "hard part" - it would just be nice to avoid wrangling pip in the course :)

**Comment by bmcfee** [comment]
It looks like the latest conda-smithy rerender will fix this on the resampy side.  If everything builds properly :crossed_fingers: then it should deploy by next week.  (AppVeyor is such a nuisance...)  Once resampy is up, I can do the same trick on the librosa package.

**Comment by bmcfee** [comment]
Okay, the py36 builds should be up now.  Please give it a spin and let me know how it goes.

**Comment by LLrsokl** [comment]
Looks like it worked! Thanks so much. This is a great convenience to have!

**Comment by bmcfee** [comment]
Glad to hear!  For future reference, the problem was just that we had to re-render with the latest conda-smithy when the 3.6 channel was added.

I'll close this one out.
