### ISSUE TITLE
Add support for scipy polyphase resampling

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#576]
#### Description

Scipy 0.18 added a [polyphase resampler](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.signal.resample_poly.html).  We could add support for this to `core.resample`, eg:

```python
y_res = librosa.resample(y, sr_old, sr_new, res_type='polyphase')
```
#### Potential complications

1. This would up the version requirement for scipy from 0.13 to 0.18.  We could potentially make this soft.
2. We'd probably need to expose some new parameters for specifying the window.
3. We'd need a good way to determine the `up` and `down` parameters.  If the sampling rates are integer-valued, we can figure this out from the gcd.  However, the current API does not require integer sampling rates, and I'd like to keep that as flexible as possible.  Perhaps we could only require int-valued rates for this particular mode, and throw a warning / exception if fractional rates are provided.

**Comment by dpwe** [comment]
FWIW, Matlab's resample also requires integer ratios.  I wrote code to find
ratios to get arbitrarily close to a resample ratio expressed as a float (I
was resampling audio by factors very close to 1 to get time alignment
between simultaneous recordings with unsynchronized sample clocks).  See
the first block (calculating the up/down factors P and Q) in:


https://labrosa.ee.columbia.edu/projects/skewview/rewrite_aligned_audio.m.html

  DAn.

**Comment by bmcfee** [comment]
Every time...
![DAn did it](https://i.imgflip.com/1p7ar7.jpg)

**Comment by lostanlen** [comment]
PR #663 (Savitzky-Golay) bumped the scipy requirement from 0.13 to 0.14. Do we still have to make the 0.18  requirement soft to close this issue?

The MATLAB code shared by @dpwe is useful for dealing with floating-point valued `sr_old` and/or `sr_new`

```
% Find p/q s.t. p/q ~= a -- approx 1 part in 1/(a-1)
p0 = floor(1/abs(skew-1));
%disp(['p0=',num2str(p0)]);
if p0 < 2^15
  % exhaustive search for pair of integers closest to desired rate
  p = p0:(2^15);
  q = round(p./skew);
  er = (skew - p./q); 
  [ee,xx] = min(abs(er));
  P = p(xx);
  Q = q(xx);
else
  % too close to unity
  P = 1;
  Q = 1;
end
```

This `too close to unit` case implies that the input is left untouched. Does that really happen in practice? i.e. a resampling factor of less than 32768/32767 ?
That is 1.000030518509476
A seven-millisecond difference in a 4-minute song
A one-second difference in a 10-hour recording
Does this matter?

**Comment by bmcfee** [comment]
I'm inclined to punt this issue, since nobody seems to be clamoring for it, and those that specifically want polyphase resampling can easily run it themselves.  Unless someone objects, I'll close this in a few days.

**Comment by bmcfee** [comment]
note: i wound up adding this in #859 primarily to give folks the option of having fast resampling in (i)cqt if they want it.n  I opted to only implement integer rates, which are automatically reduced by GCD to minimize overhead.
