### ISSUE TITLE
Doesn't install on 3.5

### ISSUE THREAD

**Issue by bhavsarpratik** [librosa/librosa#577]
Command "c:\users\pratik\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Pratik\\AppData\\Local\\Temp\\pip-build-kgc2ayzw\\resampy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Pratik\AppData\Local\Temp\pip-ld4kfd03-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Pratik\AppData\Local\Temp\pip-build-kgc2ayzw\resampy\

**Comment by bmcfee** [comment]
This appears to be a resampy issue, not librosa.  Is it possibly redundant with https://github.com/bmcfee/resampy/issues/50 ?

**Comment by bhavsarpratik** [comment]
Right! @bmcfee 
Any workaround?

**Comment by bmcfee** [comment]
Not sure -- see the comment I just added to that issue.  (Let's move discussion over there.)
