### ISSUE TITLE
problems with the output audio's bits

### ISSUE THREAD

**Issue by MatCauthon** [librosa/librosa#578]
Hi,
I need to convert a audio with 44.1 kHz sample rate and 16 bits to a audio with 16 KHz sample rate and 16 bits.
Hence I use these codes:
x, sr_orig = librosa.load(filename, sr=16000)
librosa.output.write_wav(filepath+'test.wav', x, sr_orig)

It turns out that test.wav is 16 KHz sample rate as expected, but the bit is changed from 16 to 32 which is not wanted.
Anyone knows how to fix it? To get the output wav file with 16 KHz and 16 bits?

------------------------------------------------------------------------------------------
Well, I read the librosa.load function in audio.py and it turns out the default setting is  dtype=np.float32.  I am trying to change that value.

------------------------------------------------------------------------------------------
But it seems that dtype can only get one kind of value--- np.float32? It is very embarrassing that I change the sample rate while the bit is also changed.

**Comment by dpwe** [comment]
See https://github.com/librosa/librosa/issues/361
but basically:

maxv = np.iinfo(np.int16).max

librosa.output.write_wav(
    "out_int16.wav", (audio * maxv).astype(np.int16), rate
)

  DAn.

**Comment by bmcfee** [comment]
I'd also recommend using `pysoundfile` for this instead of librosa's writer.  PSF's writer exposes much more control over the output encoding: see [docs](https://pysoundfile.readthedocs.io/en/0.9.0/#soundfile.write).

**Comment by MatCauthon** [comment]
Thanks for your reply. I will try your suggestions though I have already solved the problem with sox.

**Comment by tobeyouth** [comment]
@dpwe Thanks for your reply, it's solve my problem!

**Comment by bmcfee** [comment]
@ZHANGGU as stated in the [documentation](https://librosa.github.io/librosa/generated/librosa.output.write_wav.html#librosa.output.write_wav), only floating-point inputs are supported.  The example listed above in this thread may be out of date.

**Comment by Xinzhu-Fang** [comment]
@bmcfee @dpwe  can you provide an updated solution?

**Comment by bmcfee** [comment]
> can you provide an updated solution?

The documentation has been updated since the 0.7.0 release back in June.  The recommended solution is to use soundfile directly, rather than librosa.output.write_wav.

**Comment by Xinzhu-Fang** [comment]
> > can you provide an updated solution?
> 
> The documentation has been updated since the 0.7.0 release back in June. The recommended solution is to use soundfile directly, rather than librosa.output.write_wav.

 Thank you! that solved my bits problem
