### ISSUE TITLE
Doing CQT online results in extra frames

### ISSUE THREAD

**Issue by carlthome** [librosa/librosa#579]
https://gist.github.com/carlthome/5e207fbfdaab461ec5e1c45c77dda944

If I divide an audio signal into chunks of size `n * hop_length` samples where `n` is some integer, shouldn't the result of calling CQT per chunk and then stacking them give the same coefficients as calling CQT once for the entire audio file? What's happening at the signal ends?

**Comment by carlthome** [comment]
I find it particularly interesting that the number of splits `x` for `duration = chunk_size * x` seems to give precisely `x - 1` extra frames.

**Comment by bmcfee** [comment]
> If I divide an audio signal into chunks of size n * hop_length samples where n is some integer, shouldn't the result of calling CQT per chunk and then stacking them give the same coefficients as calling CQT once for the entire audio file?

Short answer is no, because CQT has a non-uniform frame size.  To keep frames aligned and centered, each STFT is [padded](https://github.com/librosa/librosa/blob/master/librosa/core/constantq.py#L585-L593) to cover the largest frame length within the octave.

**Comment by carlthome** [comment]
Thanks! I suppose this is what sliCQ was intended to solve. Artifacts become especially apparent with oversampling:

![image](https://cloud.githubusercontent.com/assets/1595907/26318045/fdbe5e80-3f19-11e7-91f2-9d4aa8efd842.png)

![image](https://cloud.githubusercontent.com/assets/1595907/26318048/001d3cd2-3f1a-11e7-8cca-3bae198ef07c.png)

Is there interest in getting streaming audio to work?

**Comment by bmcfee** [comment]
> Is there interest in getting streaming audio to work?

In general, yes, but that's a much larger problem for librosa than just CQT.  If we're going to tackle streaming analyses, I'd like to have a coherent plan for it across the whole package.  (I imagine it would look like some kind of generator / object interface on top of the underlying functions, though it will probably take a bit of refactoring to keep this all efficient and eliminate redundant work.)

Back to your immediate problem though: you should be able to calculate the amount of padding that occurs at the top octave, and use that to determine a valid block size within a cqt patch.  You might have to dig into the guts of cqt to do this though (eg, compute the early downsampling factor).

**Comment by carlthome** [comment]
> calculate the amount of padding that occurs at the top octave, and use that to determine a valid block size within a cqt patch

I think I'm getting LibROSA's CQT, but I'm unsure what you mean by CQT _patch_. Decomposing audio into overlapping frames with as much overlap as the longest time-domain padding in the CQT and then averaging the librosa.cqt outputs?

**Comment by carlthome** [comment]
I got a real-time processing version with LibROSA's CQT working decently by slicing in the time-domain as described in https://arxiv.org/abs/1210.0084

https://gist.github.com/carlthome/5e207fbfdaab461ec5e1c45c77dda944

![image](https://user-images.githubusercontent.com/1595907/27299108-79a8da6c-552b-11e7-8e9e-4dbdb8d89fc9.png)

**Comment by bmcfee** [comment]
@carlthome this looks great!  Any interest in writing it up as an example for the [gallery](https://librosa.github.io/librosa_gallery/)?
