### ISSUE TITLE
librosa.dtw with subseq=True is not symmetric w.r.t. its inputs

### ISSUE THREAD

**Issue by craffel** [librosa/librosa#581]
cc @stefan-balke 

My expectation for subsequence matching is that implies that either `X` can be matched to a subsequence of `Y` or `Y` can be matched to a subsequence of `X`.  `librosa.dtw` doesn't exhibit this behavior:

```Python
In [1]: import librosa
In [2]: import numpy as np
In [3]: X = np.array([10., 10., 0., 1., 2., 3., 10., 10.]).reshape([1, -1])
In [4]: Y = np.arange(4).astype(float).reshape([1, -1])
In [5]: librosa.dtw(X, Y, subseq=True)
Out[5]:
(array([[ 10.,   9.,   8.,   7.],
        [ 20.,  18.,  16.,  14.],
        [ 20.,  19.,  18.,  17.],
        [ 21.,  19.,  19.,  19.],
        [ 23.,  20.,  19.,  20.],
        [ 26.,  22.,  20.,  19.],
        [ 36.,  31.,  28.,  26.],
        [ 46.,  40.,  36.,  33.]]), array([[7, 3],
        [6, 3],
        [5, 3],
        [4, 2],
        [3, 1],
        [2, 1],
        [1, 1],
        [0, 1]]))
In [6]: librosa.dtw(Y, X, subseq=True)
Out[6]:
(array([[ 10.,  10.,   0.,   1.,   2.,   3.,  10.,  10.],
        [ 19.,  19.,   1.,   0.,   1.,   3.,  12.,  19.],
        [ 27.,  27.,   3.,   1.,   0.,   1.,   9.,  17.],
        [ 34.,  34.,   6.,   3.,   1.,   0.,   7.,  14.]]), array([[3, 5],
        [2, 4],
        [1, 3],
        [0, 2]]))
```

This is in contrast to `djitw`'s behavior (my expected behavior, obviously ;)
```Python
In [7]: import djitw

In [8]: import scipy

In [9]: djitw.dtw(scipy.spatial.distance.cdist(X.T, Y.T))
Out[9]: (array([2, 3, 4, 5]), array([0, 1, 2, 3]), 0.0)

In [10]: djitw.dtw(scipy.spatial.distance.cdist(Y.T, X.T))
Out[10]: (array([0, 1, 2, 3]), array([2, 3, 4, 5]), 0.0)
```

What is the motivation for making it non-symmetric?  We should at least document it more specifically, saying that `subseq=True` allows for a subsequence of `Y` to be matched to the entirety of `X` but not vice-versa.

**Comment by stefan-balke** [comment]
For a sequence X with N elements and Y with M elements, we normally assume for subsequence matching that M >> N. Maybe we should add a parameter check for that.

**Comment by craffel** [comment]
> For a sequence X with N elements and Y with M elements, we normally assume for subsequence matching that M >> N. Maybe we should add a parameter check for that.

Yes, and add it to the docstring.  But if you allow subsequence matching in either direction and M >> N, it's extremely unlikely that Y will be matched to a subset of X because that would imply that traversing the entirety of Y is cheaper than traversing the entirety of X.

But more than that, I don't think it's good to make that assumption.  If I have a random MIDI which is a transcription of some audio recording, it's not terribly uncommon that the MIDI will have some events at the beginning which are not in the audio file (metronome lead-in rimshots or something), or that the audio recording has some stuff not transcribed in the MIDI (a non-musical intro).  Or, the audio recording has a long fade-out outro which the MIDI didn't transcribe, etc.  So you generally don't know whether X is a subsequence of Y or Y is a subsequence of X, and you want to allow for subsequence matching.  It would result in some ugly code if you had to check which one was longer, pass them in in the correct order, and then reverse the order after DTW.

**Comment by stefan-balke** [comment]
Alright, that is what your "gullying" parameter was for, right?
So you're doing global DTW and not subsequence in `djitw`, aren't you?

I think, I need to do a toy example to see what it actually means...

**Comment by craffel** [comment]
> Alright, that is what your "gullying" parameter was for, right?
So you're doing global DTW and not subsequence in djitw, aren't you?

No, djitw does subsequence matching (see the toy example at the beginning of this post, this is with gully=1, which is equivalent to normal DTW).  The "gully" just means that you only have to match up to gully% of either sequence, which you can safely ignore here.

**Comment by stefan-balke** [comment]
Yeah, I think I got you.

I guess it's this line:
https://github.com/librosa/librosa/blob/master/librosa/core/dtw.py#L337
`cur_idx = (D_steps.shape[0] - 1, D_steps.shape[1] - 1)`

For subsequence DTW we do note necessarily start in the upper right corner of the accumulated cost matrix D, rather in `np.argmin(D[-1, :])`.

Not sure if this solves the symmertry but let me fix that first since that's a severe bug...

**Comment by stefan-balke** [comment]
Oh no, that's already handled in https://github.com/librosa/librosa/blob/master/librosa/core/dtw.py#L228

Sorry, it's super warm in Germany :)

**Comment by stefan-balke** [comment]
Here we go:
https://github.com/craffel/djitw/blob/master/djitw/dtw.py#L231

This causes the symmetry.

I'm a little concerned that this adds too much implicit behaviour to the algorithm. I'm okay with adding it if we find a way to make this explicit, maybe an extra parameter?

**Comment by craffel** [comment]
> I'm a little concerned that this adds too much implicit behaviour to the algorithm. I'm okay with adding it if we find a way to make this explicit, maybe an extra parameter?

I would argue the opposite actually, having "symmetric" mean that only one of the two arguments can have a subsequence matched is strong implicit behavior.

**Comment by stefan-balke** [comment]
![img_2625](https://cloud.githubusercontent.com/assets/7326732/26542679/33e55950-445b-11e7-8d68-13404e563b9f.jpg)

Quick sketch here with the two cases (should have flipped both). (b) is what you strive for and for me also fine to implement.

(a) has problems since only a subsequence of our "query" is matched to a subsequence of  the "database". Maybe that goes back to the definition of a subsequence. For me it's the subsequence in the database where the query matches completely.

So if we would check if `n > m` and the do `np.argmin(D[-1, :])` or `np.argmin(D[:, -1])` I'm good. What do you think @craffel?

**Comment by craffel** [comment]
Yes, I think (a) is bad, (b) is the goal.  A simple way to state this is that we always want the entirety of one sequence to be matched, e.g. the alignment path either includes indices `[0, 1, ... M - 1]` or `[0, 1, ... N - 1]`.

> So if we would check if n > m and the do np.argmin(D[-1, :]) or np.argmin(D[:, -1]) I'm good. What do you think @craffel?

Wouldn't this allow (a)?  I think we need to check if n > m or m > n and then conditionally start the alignment path from the "bottom' or the "left" of the distance matrix (in your drawings), in addition to changing the argmin order.

Of course another option (I think?) would be to check if n > m and if so, transpose everything before proceeding, use the code as-is, then reverse the transposing once we're done.

**Comment by stefan-balke** [comment]
Yes, and in addition we have to swap the intitialization of the D matrix. So, let's do the transposition and use the code as is.

I'm gonna make a PR! Maybe you can CR then?

**Comment by craffel** [comment]
> I'm gonna make a PR! Maybe you can CR then?

Great.  I'll give it the ol' CR CR.

**Comment by bmcfee** [comment]
@stefan-balke you still planning on this one?  (Trying to triage issues for the 0.6 milestone.)

**Comment by stefan-balke** [comment]
Yes. Sorry. Trying to squeeze it in next week.

Am 01.09.2017 um 19:45 schrieb Brian McFee <notifications@github.com<mailto:notifications@github.com>>:


@stefan-balke<https://github.com/stefan-balke> you still planning on this one? (Trying to triage issues for the 0.6 milestone.)
