### ISSUE TITLE
command line tool

### ISSUE THREAD

**Issue by chanansh** [librosa/librosa#582]
Is anyone planning a command line tool for librosa such as the one in [yaafe](http://yaafe.github.io/Yaafe/manual/quickstart.html)?
If not I will be happy to help

**Comment by bmcfee** [comment]
Not as such, but it sounds like a great idea!

**Comment by chanansh** [comment]
I have problems running the tests on the master branch. I am trying to
follow the contribution guide but cannot make the nose test run.

On May 26, 2017 5:57 PM, "Brian McFee" <notifications@github.com> wrote:

Not as such, but it sounds like a great idea!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/librosa/librosa/issues/582#issuecomment-304304875>, or mute
the thread

**Comment by lostanlen** [comment]
I'm thinking about this issue again and i don't really see a compelling use case for it. Given how easy it is to call Python scripts from the command line, is this really needed? I feel like it would add a lot of boilerplate code on our end.

**Comment by bmcfee** [comment]
I agree with @lostanlen -- librosa is not intended to be the end-point of audio analysis, but rather the set of building blocks that you would use to make such a thing.  Any command-line application that we design around the library will undoubtedly fail to meet the needs of most users, so I think it's best that we stay out of that space.
