### ISSUE TITLE
Window width and frame stride when calculating MFCC

### ISSUE THREAD

**Issue by TarAll** [librosa/librosa#584]
Hello,

I can't find anywhere the width of frames and strides used by librosa to extract MFCC.
Is it possible to configure them.

Thanks in advance.

**Comment by stefan-balke** [comment]
Hi TarAll,

the `**kwargs` are your friends:
http://librosa.github.io/librosa/generated/librosa.feature.mfcc.html

There you can define `hop_length` and `n_fft`.

**Comment by TarAll** [comment]
Hello stefan, thank you for your help.What are the options possible for **kwargs??
And do you have any idea about the default width windiw and stride size ??

**Comment by stefan-balke** [comment]
As said in the docu, `**kwargs` is forwarded to `melspectrogram`.

Here you can find the standard settings:

http://librosa.github.io/librosa/generated/librosa.feature.melspectrogram.html#librosa.feature.melspectrogram
`librosa.feature.melspectrogram(y=None, sr=22050, S=None, n_fft=2048, hop_length=512, power=2.0, **kwargs)`

**Comment by TarAll** [comment]
Hello stefan,
I tried to figure out the arguments but i must be missing something.I think the best solution will be giving an example.
How to get a window width of 25 ms  and a stride of 10 ms?
thanks in advance.

**Comment by stefan-balke** [comment]
You mean something like that?

```
y, sr = librosa.load(librosa.util.example_audio_file())
librosa.feature.mfcc(y=y, sr=sr, hop_length=int(sr/10), n_fft=int(sr/25))
```

Maybe you want to checkout the examples in the gallery to get started with the library:
https://librosa.github.io/librosa_gallery/

Also the documentation provides lots of examples.

**Comment by TarAll** [comment]
Now i figured it out, to set a window width to 25 ms and the stride to 10 ms you just need to do the following:
y, sr = librosa.load(audio_file, sr=None) // sr is none so librosa can sample the audion using the convenient sr
 mfccs = librosa.feature.mfcc(y, sr, n_mfcc=13, hop_length=int(0.010*sr), n_fft=int(0.025*sr))
 But still have a question : 
the shape of mfccs is (13,210)
do i have to transpose mfccs to get coefficients of each frame??

**Comment by stefan-balke** [comment]
You mean this?

`mfccs[:, 15]`

-> will give you the coefficients for frame with idx=15.

**Comment by TarAll** [comment]
yes this is exactly what i'm searching for , thank you a lot for your help.

Just a clarification for the code example you gave me:
-To set the width of window to 25 ms you have tu multiply the sr and 0.025.The reason behind that is that sr is the number of samples in one second. so to get the number of samples in 25ms you have to multiply by 0.025.
-same thing for the stride, to get a stride of 10 ms, you need to multiply the sr and 0.010.
will close this now as i found the solution.
Thanks for your help.

**Comment by ranjal** [comment]
Hi Stefan, Greetings of the Day!!
I have a small doubt. Please help me.
I want to extract mfcc of non-speech signal . First I used **python_speech_features** library of jameslyons. 
But my Professor said Can you prove it is standard result? He want library should be standard which must be site in any paper.
Then I do some stuff and I got many paper cited Librosa for extracting feature. Then I extracted mfcc with librosa.
To satisfy my professor , I also extracted mfcc in Matlab using Malcolm Slaney's Auditory Toolbox to match the result and I got MFCC result different. 

My Questions are:
1) Each libray is giving different MFCC in python and matlab. How to decide which is standard?
2) When I am using to read the wave file  **scipy.io.wavfile** as wav and **librosa.load** again I am getting different result for same audio. Which should I use ?
3) Scipy is giving dtype =int16 on reading wavefile , librosa.load is giving dtype=float32 and 
 matlab is giving dtype=double. Which should I use?

From my side to match the result of read wavefile of matlab and scipy. I converted int16 data into double by sig/max(abs(sig)). Then it is matched. 

But I am unable to match the result of scipy waveread and librosaload reading.

Its my humble request kindly reply if you can help me.
Thanks in Advance
Sorry for the poor english.

**Comment by lostanlen** [comment]
Hello @ranjal 

1. sadly, there is more than one standard. Two of the most widespread presets are "HTK" and Malcolm Slaney's "Rastamat" toolbox. Librosa replicates both of those, and allows for further customization. Whether this is coded in Python or MATLAB does not really matter; but there is no hope in trying to get *the* standard MFCC. It's always necessary to specify which standard you're talking about. Personally I use RASTAMAT. So `htk=False`.

2. This is probably because `librosa.load` resamples to 22,050 Hz by default, contrary to `scipy.io.wavfile`. I suggest you read the discussion in this issue: https://github.com/librosa/librosa/issues/509

3. I recommend `dtype=float32`.

I hope this helps

**Comment by bmcfee** [comment]
Regarding bit depth on load, you should also see the recent issue and pr #813.  My general advice is that if you really care about high-precision bit-for-bit accuracy in IO, use `soundfile` instead of `audioread` and `librosa.load`.

**Comment by dpwe** [comment]
For more discussion of varieties of MFCCs, see

https://labrosa.ee.columbia.edu/matlab/rastamat/mfccs.html

  DAn.

**Comment by ranjal** [comment]
Thankyou @dpwe 
But I want to know what is the fft size Librosa taking and how can I change it into 2048.

**Comment by Glastond** [comment]
X, sample_rate = librosa.load('../RawData/'+y, res_type='kaiser_fast',duration=2.5,sr=22050*2,offset=0.5)


for 25s window and 5s offset

**Comment by Fazankabir** [comment]
Thank you @TarAll  for coming up with such an important question. And thank you @stefan-balke  for your contribution and support. You guys are life savers.

**Comment by Nyble23** [comment]
I am trying to find mfcc features for audio clips of different lengths. Due to this I am getting different shape of the matrix returned by the function "librosa.feature.mfcc()". But I want that the features extracted are of same shape because I have to feed these to a classifier. How can I resolve this?

**Comment by padisarala** [comment]
> Now i figured it out, to set a window width to 25 ms and the stride to 10 ms you just need to do the following:
> y, sr = librosa.load(audio_file, sr=None) // sr is none so librosa can sample the audion using the convenient sr
> mfccs = librosa.feature.mfcc(y, sr, n_mfcc=13, hop_length=int(0.010_sr), n_fft=int(0.025_sr))
> But still have a question :
> the shape of mfccs is (13,210)
> do i have to transpose mfccs to get coefficients of each frame??

YES. You need to transpose to get (210,13) which is number of frames and features for each frame

**Comment by padisarala** [comment]
> Thank you so much @bmcfee & @lostanlen for responding my queries.
> 
> My audio has sampling rate of 16kHz, I want window size of 100ms(1600 samples) and overlapping 50%(800 samples) for mfcc extraction. For this I used below command.
> 
> **speech,sr = librosa.load("s26.wav", sr=None)
> speech1 = speech/max(abs(speech))
> **mfccs_speech1 = librosa.feature.mfcc(y=speech1, sr=16000, n_mfcc=13, hop_length=800, n_fft=1600)**
> 
> But my last question is how Librosa is deciding the size of FFT for calculation ???
> Like in Matlab code we have to put manually FFT size according to our window size.
> Here we are not giving the size of FFT, it should be 2048(in powers of 2).
> So Is Librosa automatically adjust FFT _size in powers of 2 or it will consider n_fft as FFT_size.
> Is FFTsize is same as window length in Librosa ?
> 
> It's my humble request please reply me @bmcfee and @lostanlen .
> 
> Thanks in Advance

The window size and overlap you are using is correct. It is as simple as this convention
If sampling rate is 16000Hz, window size is 100ms, for one second there are 16000 samples, so for 100ms the number of samples is 100ms X 16000 = 1600 samples, overlap size is 50% then samples are 800 samples. 
n_fft is actually the FFT window size according to the documentation.

**Comment by lemon-reddy** [comment]
`win_length` attribute can be used to specify the window size in number of samples present. `n_fft`, FFT size is usually taken in powers of 2 for FFT computation optimisation. 
The window will be of length win_length and then padded with zeros to match n_fft. If unspecified, defaults to win_length = n_fft.
