### ISSUE TITLE
Failed to install in Python 3.5

### ISSUE THREAD

**Issue by ntsd** [librosa/librosa#590]
Command `py -3.5 -m pip install librosa`
Os: Windows 8.1 x64

I path cl.exe from `C:\\Users\\Jiravat\\AppData\\Local\\Programs\\Common\\Micros
oft\\Visual C++ for Python\\9.0\\VC\\bin\\amd64\\`

```  Failed building wheel for resampy
  Running setup.py clean for resampy
Successfully built librosa
Failed to build resampy
Installing collected packages: resampy, librosa
  Running setup.py install for resampy ... error
    Complete output from command "C:\Program Files\Python35\python.exe" -u -c "i
mport setuptools, tokenize;__file__='C:\\Users\\Jiravat\\AppData\\Local\\Temp\\p
ip-build-t152nm69\\resampy\\setup.py';f=getattr(tokenize, 'open', open)(__file__
);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'ex
ec'))" install --record C:\Users\Jiravat\AppData\Local\Temp\pip-f9md00on-record\
install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.5
    creating build\lib.win-amd64-3.5\resampy
    copying resampy\core.py -> build\lib.win-amd64-3.5\resampy
    copying resampy\filters.py -> build\lib.win-amd64-3.5\resampy
    copying resampy\version.py -> build\lib.win-amd64-3.5\resampy
    copying resampy\__init__.py -> build\lib.win-amd64-3.5\resampy
    creating build\lib.win-amd64-3.5\resampy\data
    copying resampy\data\kaiser_best.npz -> build\lib.win-amd64-3.5\resampy\data

    copying resampy\data\kaiser_fast.npz -> build\lib.win-amd64-3.5\resampy\data

    running build_ext
    building 'resampy.interp' extension
    creating build\temp.win-amd64-3.5
    creating build\temp.win-amd64-3.5\Release
    creating build\temp.win-amd64-3.5\Release\resampy
    C:\Users\Jiravat\AppData\Local\Programs\Common\Microsoft\Visual C++ for Pyth
on\9.0\VC\bin\amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:\Program Fil
es\Python35\lib\site-packages\numpy\core\include" "-IC:\Program Files\Python35\i
nclude" "-IC:\Program Files\Python35\include" /Tcresampy/interp.c /Fobuild\temp.
win-amd64-3.5\Release\resampy/interp.obj
    interp.c
    c:\program files\python35\include\pyconfig.h(68) : fatal error C1083: Cannot
 open include file: 'io.h': No such file or directory
    error: command 'C:\\Users\\Jiravat\\AppData\\Local\\Programs\\Common\\Micros
oft\\Visual C++ for Python\\9.0\\VC\\bin\\amd64\\cl.exe' failed with exit status
 2```

**Comment by bmcfee** [comment]
This is a resampy issue, not librosa.  Please refer to https://github.com/bmcfee/resampy/issues/50 and https://github.com/bmcfee/resampy/issues/22 .

**Comment by ZhukIvan** [comment]
have this issue in ubuntu

Collecting resampy
  Using cached resampy-0.1.5.tar.gz
Requirement already up-to-date: numpy>=1.10 in /home/sprocketus/.local/lib/python3.5/site-packages (from resampy)
Requirement already up-to-date: scipy>=0.13 in /home/sprocketus/.local/lib/python3.5/site-packages (from resampy)
Requirement already up-to-date: six>=1.3 in /home/sprocketus/.local/lib/python3.5/site-packages (from resampy)
Requirement already up-to-date: Cython>=0.23 in /home/sprocketus/.local/lib/python3.5/site-packages (from resampy)
Building wheels for collected packages: resampy
  Running setup.py bdist_wheel for resampy ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lq8myu26/resampy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmph2j3136dpip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/resampy
  copying resampy/filters.py -> build/lib.linux-x86_64-3.5/resampy
  copying resampy/core.py -> build/lib.linux-x86_64-3.5/resampy
  copying resampy/version.py -> build/lib.linux-x86_64-3.5/resampy
  copying resampy/__init__.py -> build/lib.linux-x86_64-3.5/resampy
  creating build/lib.linux-x86_64-3.5/resampy/data
  copying resampy/data/kaiser_best.npz -> build/lib.linux-x86_64-3.5/resampy/data
  copying resampy/data/kaiser_fast.npz -> build/lib.linux-x86_64-3.5/resampy/data
  running build_ext
  building 'resampy.interp' extension
  creating build/temp.linux-x86_64-3.5
  creating build/temp.linux-x86_64-3.5/resampy
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/sprocketus/.local/lib/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m -c resampy/interp.c -o build/temp.linux-x86_64-3.5/resampy/interp.o
  resampy/interp.c:24:20: fatal error: Python.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for resampy
  Running setup.py clean for resampy
Failed to build resampy
Installing collected packages: resampy
  Running setup.py install for resampy ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lq8myu26/resampy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xu5ferlt-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/resampy
    copying resampy/filters.py -> build/lib.linux-x86_64-3.5/resampy
    copying resampy/core.py -> build/lib.linux-x86_64-3.5/resampy
    copying resampy/version.py -> build/lib.linux-x86_64-3.5/resampy
    copying resampy/__init__.py -> build/lib.linux-x86_64-3.5/resampy
    creating build/lib.linux-x86_64-3.5/resampy/data
    copying resampy/data/kaiser_best.npz -> build/lib.linux-x86_64-3.5/resampy/data
    copying resampy/data/kaiser_fast.npz -> build/lib.linux-x86_64-3.5/resampy/data
    running build_ext
    building 'resampy.interp' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/resampy
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/sprocketus/.local/lib/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m -c resampy/interp.c -o build/temp.linux-x86_64-3.5/resampy/interp.o
    resampy/interp.c:24:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lq8myu26/resampy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xu5ferlt-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-lq8myu26/resampy/
