### ISSUE TITLE
Some  question when extracting MFCC features

### ISSUE THREAD

**Issue by JinmingZhao** [librosa/librosa#595]
The audio information:
Input File     : 'aa.wav'
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Duration       : 00:00:00.64 = 10160 samples ~ 47.625 CDDA sectors
File Size      : 20.4k
Bit Rate       : 257k
Sample Encoding: 16-bit Signed Integer PCM

when use the "frame length=25ms, frame shift=10ms" , number of frames should be 
(10160-240)/160=62frames.  and get 62 frame in kaldi.

But use librosa to extract the MFCC features, I  got 64 frames:

sr = 16000
n_mfcc = 13
n_mels = 40
n_fft = 512
win_length = 400 # 0.025*16000
hop_length = 160 # 0.010 * 16000
window = 'hamming'
fmin = 20
fmax = 4000
y, sr = librosa.load(wav_file, sr=16000)
print(sr)
D = numpy.abs(librosa.stft(y, window=window, n_fft=n_fft, win_length=win_length, hop_length=hop_length))**2 
S = feature.melspectrogram(S=D, y=y, n_mels=n_mels, fmin=fmin, fmax=fmax)
feats = feature.mfcc(S=librosa.power_to_db(S), n_mfcc=n_mfcc)
print(feats.shape)  

OR 

feats = feature.mfcc(y=y, n_mfcc=n_mfcc, n_fft=n_fft, n_mels=n_mels, fmin=fmin, hop_length=hop_length)

all of the two librosa code will result in (13,64) shape. 

Another question, in the feature.mfcc() function:
Could I directly given the window_length, window,  hop_length parameters?

Look forward to your reply.

Thanks
Jinming

**Comment by JinmingZhao** [comment]
Add：
The result of using sidekit is also 62 frames. 

import sidekit
import numpy

def make_mfcc_feats(uttList, input_file_list, output_feat_list, nj=1,
                    sampling_frequency=16000, lower_frequency=20, higher_frequency=3700,
                    filter_bank_size=24, window_size=0.025, shift=0.01, ceps_number=20,
                    save_param=["cep"]):

    extractor = sidekit.FeaturesExtractor(audio_filename_structure=None,
                                          feature_filename_structure=None,
                                          sampling_frequency=sampling_frequency,
                                          lower_frequency=lower_frequency,
                                          higher_frequency=higher_frequency,
                                          filter_bank='log',
                                          filter_bank_size=filter_bank_size,
                                          window_size=window_size,
                                          shift=shift,
                                          ceps_number=ceps_number,
                                          pre_emphasis=0.97,
                                          save_param=save_param,
                                          )

    print("Start extracting the features")
    channel_list = numpy.zeros(len(uttList), dtype='int')
    extractor.save_list(show_list=uttList, channel_list=channel_list, audio_file_list=input_file_list,
                        feature_file_list=output_feat_list, num_thread=nj)


def get_feature_server(feature_filename_structure, delta=False, double_delta=False,
                       dataset_list=["cep"], feat_norm="cmvn",
                       keep_all_features=False):
    server = sidekit.FeaturesServer(feature_filename_structure=feature_filename_structure,
                                    dataset_list=dataset_list,
                                    mask=None,
                                    feat_norm=feat_norm,
                                    delta=delta,
                                    double_delta=double_delta,
                                    rasta=True,
                                    context=None,
                                    keep_all_features=keep_all_features)
    return server

uttList = ['aa']
input_file_list = ['./aa.wav']
output_file_list = ['./aa.h5']
make_mfcc_feats(uttList, input_file_list, output_file_list)
feature_filename_structure = './{}.h5'
server = get_feature_server(feature_filename_structure)
cep = server.load(uttList[0])[0]
print(cep.shape) 

(62, 20)

**Comment by bmcfee** [comment]
This might be an artifact if using centered frames (librosa's default) instead of left-aligned frames. What happens if you call stft with `center=False`?

**Comment by JinmingZhao** [comment]
@bmcfee  
If I call stft with "center=false", the frames is 61. 

And if I directly call the mfcc(y=y,..) function, I can't given the
 'center win-length window' parameters.

**Comment by dpwe** [comment]
As you give, the number of complete frames is 1 + floor( (n_samples -
window_length) / hop_length)
(i.e., one complete window, then one more frame for each addition
hop_length samples we can pull from the input).

In a simple implementation without padding (e.g., Kaldi) that gives 1 +
floor((10160 - 400)/160) = 1 + floor(9760/160) = 1 + 61 = 62 frames

Although you specify your window as 400 points, librosa actually pads this
out to n_fft points, so the window_length internally is 512 points.  With
padding, this doesn't change the number of frames (or their centering).
With default center=True, librosa effectively adds window_length/2 zeros at
each end of the signal, so the number of frames becomes
1 + floor( ((n_samples + 2*window_length/2) - window_length) / hop_length)
= 1 + floor(10160 / 160) = 1 + 63 = 64, as you observed.

So this is WAI.

Now, if you call stft with center=False, you only get 61 frames.  This is
because with the  window length being used is the 512 pt n_fft, so the
number of frames is 1 + floor((10160 - 512)/160) = 61

However, I take the point here that we're not supporting center=False very
"sensitively".  If we're given a win_length which is smaller than n_fft, I
think there's a good case, when center=False, for padding with (n_fft -
win_length)/2 at each end.  This would give the 62 frames that a naive
unpadded win/hop combination gives.

And, yes, melspectrogram and mfcc don't support passing additional kwargs
to the underlying spectrogram, because they use extra args as the mel
filter bank definition.  You need to pass in the spectrogram of your own
construction, as in your example code.

  DAn.

**Comment by bmcfee** [comment]
> However, I take the point here that we're not supporting center=False very
> "sensitively".  If we're given a win_length which is smaller than n_fft, I
> think there's a good case, when center=False, for padding with (n_fft -
> win_length)/2 at each end.  This would give the 62 frames that a naive
> unpadded win/hop combination gives.

This sounds reasonable, but API-breaking.  I'd be okay with slating this for the 0.6 release.

**Comment by dpwe** [comment]
I think it's just

diff --git a/librosa/core/spectrum.py b/librosa/core/spectrum.py

index d276127..1b6f7c0 100644

--- a/librosa/core/spectrum.py

+++ b/librosa/core/spectrum.py

@@ -153,6 +153,9 @@ def stft(y, n_fft=2048, hop_length=None,
win_length=None, window='hann',

     if center:

         util.valid_audio(y)

         y = np.pad(y, int(n_fft // 2), mode='reflect')

+    elif n_fft > win_length:

+        util.valid_audio(y)

+        y = np.pad(y, int((n_fft - win_length) // 2), mode='constant')



     # Window the time series.

     y_frames = util.frame(y, frame_length=n_fft, hop_length=hop_length)

@@ -294,7 +297,10 @@ def istft(stft_matrix, hop_length=None,
win_length=None, window='hann',

     y[approx_nonzero_indices] /= ifft_window_sum[approx_nonzero_indices]



     if center:

-        y = y[int(n_fft // 2):-int(n_fft // 2)]

+        pad_length = n_fft // 2

+    else:

+        pad_length = (n_fft - win_length) // 2

+    y = y[pad_length:-pad_length]



     return y

but I haven't put this into a PR (yet).

  DAn.

**Comment by JinmingZhao** [comment]
There is a explanation with compute-mfcc-feats tool.
  --snip-edges    : If true, end effects will be handled by outputting only frames that completely fit in the file, and the number of frames depends on the frame-length.  If false, the number of frames depends only on the frame-shift, and we reflect the data at the ends. (bool, default = true)
if set "--snip-edges=false", will get 64 frames.

Thanks,
Jinming

**Comment by zkl99999** [comment]
well learned

**Comment by xxoospring** [comment]
楼主问题解决了吗？我现在也是碰到这个问题，不仅帧数不一样，数值也是不一样的，不知道为啥

**Comment by lostanlen** [comment]
superseded by #596
