### ISSUE TITLE
Problems installing on Window 10 

### ISSUE THREAD

**Issue by sayyoume** [librosa/librosa#608]
[root@bogon home]# pip install librosa
Collecting librosa
  Using cached librosa-0.5.1.tar.gz
Collecting audioread>=2.0.0 (from librosa)
  Using cached audioread-2.1.5.tar.gz
Collecting numpy>=1.8.0 (from librosa)
  Using cached numpy-1.13.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting scipy>=0.13.0 (from librosa)
  Using cached scipy-0.19.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting scikit-learn>=0.14.0 (from librosa)
  Using cached scikit_learn-0.18.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting joblib>=0.7.0 (from librosa)
  Using cached joblib-0.11-py2.py3-none-any.whl
Requirement already satisfied: decorator>=3.0.0 in /usr/lib/python2.7/site-packages (from librosa)
Requirement already satisfied: six>=1.3 in /usr/lib/python2.7/site-packages (from librosa)
Collecting resampy>=0.1.2 (from librosa)
  Using cached resampy-0.1.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-XlFpGq/resampy/setup.py", line 6, in <module>
        import numpy as np
    ImportError: No module named numpy
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-XlFpGq/resampy/

**Comment by bmcfee** [comment]
This is a known install issue with [resampy](https://github.com/bmcfee/resampy), not librosa.  If you install numpy first, then it ought to work.

**Comment by bmcfee** [comment]
Resampy 0.2.0 should resolve this issue, so I'll close it out.
