### ISSUE TITLE
DTW test/error/ resampy.filters.get_filter

### ISSUE THREAD

**Issue by apiszcz** [librosa/librosa#611]
I'm getting an error, it may be related to my environment, however this case appears to indicate get_filter is not returning the expected arguments

```
---> 23 BW_BEST = resampy.filters.get_filter('kaiser_best')[2]
IndexError: tuple index out of range
```

```
import librosa
D, wp = librosa.dtw(x, y, subseq=True)
print(d)



---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-5-af09122d8261> in <module>()
----> 1 import librosa
      2 D, wp = librosa.dtw(x, y, subseq=True)
      3 print(d)

C:\g\test\lib\librosa\__init__.py in <module>()
     10 # And all the librosa sub-modules
     11 from . import cache
---> 12 from . import core
     13 from . import beat
     14 from . import decompose

C:\g\test\lib\librosa\core\__init__.py in <module>()
    107 
    108 from .time_frequency import *  # pylint: disable=wildcard-import
--> 109 from .audio import *  # pylint: disable=wildcard-import
    110 from .spectrum import *  # pylint: disable=wildcard-import
    111 from .pitch import *  # pylint: disable=wildcard-import

C:\g\test\lib\librosa\core\audio.py in <module>()
     21 
     22 # Resampling bandwidths as percentage of Nyquist
---> 23 BW_BEST = resampy.filters.get_filter('kaiser_best')[2]
     24 BW_FASTEST = resampy.filters.get_filter('kaiser_fast')[2]
     25 

IndexError: tuple index out of range
```

**Comment by bmcfee** [comment]
I'm guessing you have an outdated `resampy` -- how did you install lirosa?

Please include the results of `librosa.show_versions()` to help sort this out.

**Comment by apiszcz** [comment]
Install, unzip tar and place in a lib folder.

INSTALLED VERSIONS
------------------
python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit
(AMD64)]

librosa: 0.5.1

audioread: 2.1.5
numpy: 1.13.1
scipy: 0.19.1
scikit-learn: None
joblib: 0.10.0
decorator: 4.0.10
six: 1.10.0
resampy: 0.1.5

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
sphinxcontrib-versioning: None
matplotlib: 2.0.2
numba: 0.34.0

**Comment by bmcfee** [comment]
Very strange; that version of resampy should work.

When you say "install", what exactly do you mean?  `pip install`?  `setup.py install`?  You appear to be missing the sklearn dependency, so not everything is going to work, but that shouldn't affect DTW or file i/o.  Still, if you installed by the setup script (or pip), then there should be no missing dependencies.

Does resampy work if you load it directly?  E.g., does this work:

```python
>>> import resampy
>>> import numpy as np
>>> x = np.random.randn(22050)
>>> y = resampy.resample(x, 22050, 44100)
>>> len(y)
44100
```

**Comment by apiszcz** [comment]
Yes, resampy is fine as far as I can tell.


my output

>>> import numpy as np
>>> x = np.random.randn(22050)
>>> y = resampy.resample(x, 22050, 44100)
>>> len(y)
44100


One more note:
scikit-learn is typically sklearn on windows
>>> import sklearn
>>> sklearn.__version__

**Comment by apiszcz** [comment]
Here is what the line in core\audio.py returns

[image: Inline image 1]

**Comment by apiszcz** [comment]
It was my error on the input format of the sound signal/array, all set.
Thank you.

**Comment by bmcfee** [comment]
> It was my error on the input format of the sound signal/array, all set.

Glad to hear!  This does seem like a failing of our exception handling / input checking though. Would you mind providing a minimal (self-contained) example that triggers the above behavior so we can detect it going forward and provide a more useful error message?


> scikit-learn is typically sklearn on windows

Yes, but we report package names to match their pypi name, not the python package name.

**Comment by apiszcz** [comment]
y=np.random.randint(0,255,(1024,1))
rosadisp.specshow(librosa.stft(y), y_axis='linear')

Two problems here, #1 integer not float, #2 and passed through resampy

Possibly a dimension check at core/audio.py here may warn the user and
exit/error out.
BW_BEST = resampy.filters.get_filter('kaiser_best')[2]
BW_FASTEST = resampy.filters.get_filter('kaiser_fast')[2]

**Comment by bmcfee** [comment]
Thanks!  I'll stick that on the todo list.
