### ISSUE TITLE
librosa.dtw : question on allowable input data dimensions

### ISSUE THREAD

**Issue by apiszcz** [librosa/librosa#613]
I'm getting a column dimension error when they are both (1)
(12, 1) (3, 1)
Is this shape input allowed?

```
-> dtwval, path = librosa.dtw(siga, sigb, subseq=True)
(Pdb) siga
array([[  4.],
       [ 30.],
       [ 52.],
       [ 32.],
       [ 54.],
       [ 22.],
       [ 28.],
       [ 22.],
       [ 12.],
       [ 30.],
       [ 16.],
       [ 18.]])
(Pdb) sigb
array([[ 46.],
       [  6.],
       [ 14.]])
ValueError: XA and XB must have the same number of columns (i.e. feature dimension.)
```

**Comment by bmcfee** [comment]
Looks like a typo in that exception: the data need to match in the number of rows, not columns. The docs appear to be correct on this though: https://librosa.github.io/librosa/generated/librosa.core.dtw.html?highlight=dtw#librosa.core.dtw

[tagging @stefan-balke to confirm]

**Comment by stefan-balke** [comment]
This one is thrown by `scipy.spatial.distance.cdist`
https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html

Strictly speaking, @apiszcz has a one-dimensional feature, so the `siga` and `sigb` need to be (1, n) and (1,m) respectively.

In the tests we have a working 1D-example:
https://github.com/librosa/librosa/blob/master/tests/test_dtw.py#L33

The question is if we want to catch that exception and replace it with our own error message?

**Comment by apiszcz** [comment]
I'm also testing fastdtw and dtw, the row constraint does not apply. Hmm. Tx

**Comment by apiszcz** [comment]
Is this the correct response? (I'm not sure it is)

```
from scipy.spatial.distance import cdist

# Example taken from:
# Meinard Mueller, Fundamentals of Music Processing
X = np.array([[1, 3, 3, 8, 1]])
Y = np.array([[2, 0, 0, 8, 7, 2]])

# Precompute distance matrix.
C = cdist(X.T, Y.T, metric='euclidean')
gt_D = np.array([[1., 2., 3., 10., 16., 17.],
                 [2., 4., 5., 8., 12., 13.],
                 [3., 5., 7., 10., 12., 13.],
                 [9., 11., 13., 7., 8., 14.],
                 [10, 10., 11., 14., 13., 9.]])
# Supply precomputed distance matrix and specify an invalid distance
# metric to verify that it isn't used.
mut_D, _ = librosa.dtw(C=C, metric='invalid')
assert np.array_equal(gt_D, mut_D)
```



```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-56-97fe45c71da1> in <module>()
     15 # Supply precomputed distance matrix and specify an invalid distance
     16 # metric to verify that it isn't used.
---> 17 mut_D, _ = librosa.dtw(C=C, metric='invalid')
     18 assert np.array_equal(gt_D, mut_D)
     19 

TypeError: dtw() got an unexpected keyword argument 'C'
```

**Comment by stefan-balke** [comment]
> I'm also testing fastdtw and dtw, the row constraint does not apply.

Maybe they are only expecting 1D-input? This implementation is focusing on getting multidimensional input sequences. When you only provide a one dim. sequence, you still have to follow the shape rules. No problem IMHO.

Try this:

```Python
import librosa
import numpy as np


X = np.array([[1, 3, 3, 8, 1]])
Y = np.array([[2, 0, 0, 8, 7, 2]])

librosa.dtw(X, Y)
```

Should result in this here:
```
Out[8]: 
(array([[  1.,   2.,   3.,  10.,  16.,  17.],
        [  2.,   4.,   5.,   8.,  12.,  13.],
        [  3.,   5.,   7.,  10.,  12.,  13.],
        [  9.,  11.,  13.,   7.,   8.,  14.],
        [ 10.,  10.,  11.,  14.,  13.,   9.]]), array([[4, 5],
        [3, 4],
        [3, 3],
        [2, 2],
        [1, 1],
        [0, 0]]))
```

**Comment by bmcfee** [comment]
@stefan-balke 1d-input seems like a pretty common use-case, in retrospect.  Maybe it's worth adding a `np.atleast_2d` into our dtw to handle this gracefully?

**Comment by stefan-balke** [comment]
Yeah, sure, it's already in there:
https://github.com/librosa/librosa/blob/master/librosa/core/dtw.py#L189

But we then plug it into `scipy.cdist` as the transposed version thus messing up dimensions for the 1d case. If we catch the `ValueError` and exchange "columns" against "rows" should help the users.

**Comment by apiszcz** [comment]
Thank you for giving this issue some review. Is it possible to modify librosa.dtw to work with different size 1D arrays? The 'perceived performance' of librosa.dtw from my limited tests show that it is fast. The NUMBA implementation may be the reason, I hope to measure performance in my application and beyond the simple test below. I posted this elsewhere, but worth repeating. It would be great to use librosa.dtw with 1D varying length arrays.
 
x=np.random.randint(0,2,(1000,1))
y=np.random.randint(0,2,(1000,1))

![image](https://user-images.githubusercontent.com/1430861/29328724-88415cf8-81c1-11e7-9a16-53004544cbd0.png)

**Comment by bmcfee** [comment]
> Is it possible to modify librosa.dtw to work with different size 1D arrays?

I don't think it's necessary?  Can't you just do something like:

```python
librosa.dtw(x[np.newaxis, :], y[np.newaxis, :], ...)
```
to make it artificially 2D?  Or am I missing something?

Otherwise: your table of results looks impressive, perhaps too good to be true?  I'm guessing that librosa's dtw is terminating early because your two input signals have exactly the same length, so there's no choice in how to align them.  I suggest doing timing tests for multiple `y` arrays with varying lengths.

**Comment by apiszcz** [comment]
I would like to get the distance returned, with your suggestion I'm getting two arrays


```
import numpy as np
x = np.array([1,1,2,2,1,1,3,3])
y = np.array([0,0,1,1,2,2,3,3])
import librosa
librosa.dtw(x[np.newaxis, :], y[np.newaxis, :], metric='euclidean')

Out[4]:
(array([[  1.,   2.,   2.,   2.,   3.,   4.,   6.,   8.],
        [  2.,   2.,   2.,   2.,   3.,   4.,   6.,   8.],
        [  4.,   4.,   3.,   3.,   2.,   2.,   3.,   4.],
        [  6.,   6.,   4.,   4.,   2.,   2.,   3.,   4.],
        [  7.,   7.,   4.,   4.,   3.,   3.,   4.,   5.],
        [  8.,   8.,   4.,   4.,   4.,   4.,   5.,   6.],
        [ 11.,  11.,   6.,   6.,   5.,   5.,   4.,   4.],
        [ 14.,  14.,   8.,   8.,   6.,   6.,   4.,   4.]]), array([[7, 7],
        [6, 6],
        [5, 5],
        [4, 4],
        [3, 4],
        [2, 4],
        [1, 3],
        [0, 2]]))
```

**Comment by stefan-balke** [comment]
`dtw()` returns the accumulated cost matrix `D` and the warping path.

The alignment cost is stored in the entry `D[-1, -1]`.

**Comment by apiszcz** [comment]
whoa, I definitely missed that in the documentation page.

Thank you.

https://librosa.github.io/librosa/generated/librosa.core.dtw.html

**Comment by apiszcz** [comment]
Results at bottom for cost.

```
import librosa,mlpy
from scipy.spatial.distance import euclidean
from fastdtw import fastdtw
from dtw import dtw

x = np.array([1,1,2,2,1,1,3,3])
y = np.array([0,0,1,1,2,2,3,3])
D,wp=librosa.dtw(x[np.newaxis, :], y[np.newaxis, :], metric='euclidean')
cost=D[-1,1]
print('librosa',cost)

cdist,cost,acc,path=dtw.dtw(x.reshape(-1, 1), y.reshape(-1, 1), dist=lambda x, y: norm(x - y, ord=1))
print('dtw',cdist)

xf=x.flatten()
yf=y.flatten()
dist, cost, path = mlpy.dtw_std(xf, yf, dist_only=False)
print('mlpy',dist)

distance, path = fastdtw(x, y, dist=euclidean)
print('fastdtw',distance)
```

```
librosa 14.0
dtw 0.25
mlpy 4.0
fastdtw 4.0
```

**Comment by apiszcz** [comment]
Here is a test with 1024, mlpy is the leader, thank you for the assistance.

```
import librosa,mlpy
from scipy.spatial.distance import euclidean
from fastdtw import fastdtw
from dtw import dtw

x=np.random.randint(0,255,(1024,))
y=np.random.randint(0,255,(1024,))
%timeit D,wp=librosa.dtw(x[np.newaxis, :], y[np.newaxis, :], metric='euclidean')
cost=D[-1,-1]
print('librosa',cost)

%timeit cdist,cost,acc,path=dtw.dtw(x.reshape(-1, 1), y.reshape(-1, 1), dist=lambda x, y: norm(x - y, ord=1))
print('dtw',cdist)

xf=x.flatten()
yf=y.flatten()
%timeit dist, cost, path = mlpy.dtw_std(xf, yf, dist_only=False)
print('mlpy',dist)

%timeit distance, path = fastdtw(x, y, dist=euclidean)
print('fastdtw',distance)
```
```
64.9 ms ± 604 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
librosa 13.0
8.91 s ± 491 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
dtw 0.590909090909
6.49 ms ± 343 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
mlpy 13.0
517 ms ± 29.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
fastdtw 13.0
```

**Comment by stefan-balke** [comment]
I get the feeling that you don't have `numba` installed.

```
In [8]: %timeit D,wp=librosa.dtw(x[np.newaxis, :], y[np.newaxis, :], metric='euclidean')
1.05 ms ± 15.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

**Comment by apiszcz** [comment]
It is available, not a conventional install.
