### ISSUE TITLE
librosa.effects.split() returns out-of-bound index

### ISSUE THREAD

**Issue by fredyjl** [librosa/librosa#617]
#### Description

As title, librosa.effects.split() returns index exceeding the input length. With few tests, I found it happens when the input is not silent on the boundary.
#### Steps/Code to Reproduce
```
import librosa
# len(x) == 886661
voiced_intervals = lbrosa.effects.split(x, top_db=30, frame_length=1024, hop_length=80)
# voiced_intervals[-1][1] == 886784

x[voiced_intervals[-1][1]]
```
```
IndexError: index 886784 is out of bounds for axis 0 with size 886661
```

#### Versions

Darwin-16.4.0-x86_64-i386-64bit
('Python', '2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]')
('NumPy', '1.12.1')
('SciPy', '0.19.0')
('librosa', '0.5.1')

**Comment by bmcfee** [comment]
That's interesting, thanks for bringing it up.  I suspect it has something to do with the conversion of frames to samples that happens after the analysis.

For completeness and to speed up debugging, can you post a minimal audio example, or code to generate a synthetic example that triggers this behavior?

Thanks!

**Comment by bmcfee** [comment]
Confirmed problem case:
```python
import numpy as np
import librosa

sr = 22050
y = np.ones(10 * sr)

print(librosa.effects.split(y))
print(len(y))
```
Produces:
> [[     0 220672]]
> 220500

The amount of bounds violation depends on the framing parameters.  This should be an easy fix.
