### ISSUE TITLE
Remove scikit-learn from setup.py?

### ISSUE THREAD

**Issue by carlthome** [librosa/librosa#618]
Like how matplotlib was made optional, here's a thought: sklearn is a _really big_ dependency and the only place where it's used in LibROSA is in [this function](https://github.com/librosa/librosa/blob/a41361c6629e5163f162bd2e20399b886812f714/librosa/decompose.py#L30-L187) that only serves as a slim wrapper around [sklearn.decomposition](http://scikit-learn.org/stable/modules/classes.html#module-sklearn.decomposition).

Unless there are plans to depend more on sklearn in the future, perhaps it should be removed from the dependencies, and the wrapper function should be deprecated and made into a docstring example or just added to the gallery?

Again, just a thought, but pulling sklearn on every CI build is a minor annoyance. :panda_face:

**Comment by bmcfee** [comment]
It's also used within the segment module for clustering, and we use the nearest neighbor data structures for fast recurrence matrix generation.  I suppose those aren't core functions, but I really dislike having a hodge podge of optional dependencies.

**Comment by carlthome** [comment]
My bad, their KNN and HCA is also used in librosa.segment which makes more sense. Don't know how I didn't catch that. :stuck_out_tongue_winking_eye:

**Comment by carlthome** [comment]
> It's also used within the segment module for clustering, and we use the nearest neighbor data structures for fast recurrence matrix generation. I suppose those aren't core functions, but I really dislike having a hodge podge of optional dependencies.

Yeah, sorry! I agree that a monolith is easier to distribute/install.

**Comment by beasteers** [comment]
Sorry to comment on an old closed issue, but I've been thinking about this a bit lately. It ends up being a problem in docker containers and on raspberry pis (I'm currently waiting on a docker container that's taking forever).

I agree that users shouldn't have to opt in to install sklearn, but it would be nice if users had a method of opting out. 

e.g. `pip install librosa[lite]`

I've been trying to research how to do this, but I haven't found a way to do basically the inverse of `extras_require` to optionally omit packages (can't do `extras_require={'lite': ['!sklearn']}` :/ ). Idk if anyone has experience about whether this is possible?

**Comment by bmcfee** [comment]
AFAIK this isn't possible with python packaging.  If you know what you're doing, you could always install with `--no-deps` and just cover the other hard requirements manually (eg in a requirements.txt file).  It's not ideal, but it ought to work.

**Comment by beasteers** [comment]
Agh that's unfortunate. I've thought about that but you'd still have to deal with the ImportErrors. You might be able to hack it with a lazy importer that taps into the import mechanics but that's a bit.. 😬😬😬

None of the other options I can think of are very clean either. There's so much useful stuff in librosa but sometimes it can be clunky. It's too bad 😢 putting librosa_lite on my wishlist haha

**Comment by bmcfee** [comment]
> you'd still have to deal with the ImportErrors

mock is great for this.
