### ISSUE TITLE
Should docs suggest generating fake audio with np.random.randn?

### ISSUE THREAD

**Issue by greaber** [librosa/librosa#635]
I noticed examples like this in the docs:

```
import numpy as np
import librosa

rate = 44100
data = np.random.randn(rate * 10, 2)

maxv = np.iinfo(np.int16).max
librosa.output.write_wav(
    "out_int16.wav", (audio * maxv).astype(np.int16), rate
)
```

I realize it is just a toy example, but shouldn't `data` be generated in some way that ensures it is restricted to [-1,1]?  (Also, either `audio` should be change to `data` or `data` should be changed to `audio`.)

**Comment by bmcfee** [comment]
Thanks @greaber for spotting those issues.  I agree with your assessment that those are bad example snippets that could be improved.  Was this only in the [advanced i/o page](https://librosa.github.io/librosa/ioformats.html?highlight=randn)?  Or are there other instances of this?

**Comment by greaber** [comment]
As far as I know, only there, but I didn't do a thorough search.

**Comment by siddhugolu** [comment]
Hello!
I would like to work on this issue. I'm still understanding the whole process of open-source development though, so might need some help :)

**Comment by faroit** [comment]
Oops... this was bluntly copied from http://pysoundfile.readthedocs.io/en/0.9.0/#soundfile.write 
@siddhugolu maybe you can make a PR there as well... ;-)
