### ISSUE TITLE
RFC: Viterbi decoding?

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#639]
#### Description

It seems like there isn't currently an easy to use, self-contained viterbi decoder package in python.  (Am I wrong?  Did I miss something obvious?)

Viterbi does seem to be in scope, if librosa is intended to be a library of useful things for audio analysis.  It's certainly no further afield than, say, dtw.  So, what do folks think about adding this in a future version?

Some desirable features from my point of view:

- Focus on the discriminative case (ie., linear chain crf), not the generative case (ie., hmm).  This means that I would want something that consumes a matrix of state likelihoods over time (not emission probabilities).
- Helper functions to construct simple transition matrix priors (uniform, self-loop, clock, etc).
- Optional initial state distribution.
- Numerically stable.
- Numba-friendly.

Anything else?  FWIW, I have a prototype that checks about half of these boxes, but I don't intend to get it polished in time to make it into 0.6.  (Maybe 0.6.1 or 0.7.0.)

**Comment by stefan-balke** [comment]
Sounds good to me. At the moment I'd take the DTW for that and have the transition matrix as my `C` matrix. However, I don't know exactly to which Viterbi parameters this corresponds.

**Comment by bmcfee** [comment]
> At the moment I'd take the DTW for that and have the transition matrix as my C matrix. However, I don't know exactly to which Viterbi parameters this corresponds.

I'm not sure there is a correspondence -- they're solving different kinds of problems.

One more desired property:

- The ability to support multi-label decoding (with binary as a special case)

**Comment by bmcfee** [comment]
Thinking a bit more about the design goals here:

- We could easily support the generative case with an optional state scaling parameter, since `P[Y|X] = P[X|Y] * P[Y] / P[X]`.  If we say the input likelihoods encode `P[X|Y]` by default, we could let `P[Y]` default to the uniform distribution, in which case we get the same solution path as assuming the inputs encoded `P[Y|X]`.  If the user then wants to specify some other marginal distribution for `Y`, they can do so.
- Initial-state distribution support can be handled by padding the input, solving, and truncating the result, but this is inefficient for memory consumption due to the copy.
- Do we want to return the likelihoods as well as solution paths?  Always, or optionally?  What would that look like for the multi-label case?

**Comment by bmcfee** [comment]
Quick summary of the proposed api:

- `librosa.sequence.viterbi` - standard viterbi algorithm.
  - Inputs:
    - conditional obsevation likelihood `prob[s, t] = P[X(t) = x | State(t) = s]`
    - transition matrix `transition[i, j] = P[State(t+1) = j | State(t) = i]`
    - (optional) initial state distribution `p_init[s] = P[State(0) = s]` (uniform by default)
  - Outputs:
    - `path[t]` maximum likelihood state sequence
- `librosa.sequence.viterbi_d` - discriminative viterbi.  *(Suggestions for a better name?)*
  - Inputs:
    - conditional state likelihood `prob[s, t] = P[State(t) = s | X(t) = x]`
    - transition matrix as above
    - (optional) marginal distribution `p_state[s] = P[State = s]` 
  - Outputs: as above
  - Implementation uses Bayes rule on the likelihoods, then reduces to `viterbi` to compute the solution path.  (actually, both functions will use a common, private inference function, but the idea is the same.)
- `librosa.sequence.viterbi_ml` - multi-label viterbi.  Like `viterbi_d`, except the states are not mutually exclusive.  (Image, say, instrument detection as a collection of on/off estimates).
  - Inputs:
    - conditional state likelihoods `prob[s, t] = P[State_s(t) = 1  | X(t)]`
    - transitions are broadly defined here.  Can be any of the following:
      - scalar in `[0, 1]`, indicating the (shared) probability of a state change
      - vector of length `2`, indicating the off-diagonals of a common transition matrix (diagonals are inferred), on->off and off->on
      - array of shape `(m, 2)`, indicating separate off-diagonals for each state.
    - (optional) marginal distribution as in `viterbi_d`
  - Outputs:
    - `active[s, t]` indicator of whether state `s` is active at time `t

Transition generators:
- uniform: `ones(m)/m`
- spike/uniform: self-loops with given probability `p`, and the remaining `1-p` is spread uniformly among the other `n-1` states.  `p` can be a scalar or a vector of length `m`.
- cycle: self-loops with given probability, and move to the next state with `1-p`.
- anything else?
