### ISSUE TITLE
librosa.output.write_wav doesn't accept int16 typed arrays

### ISSUE THREAD

**Issue by r9y9** [librosa/librosa#640]
#### Description

`librosa.output.write_wav` doesn't accept int16 typed arrays, while it worked before. I found this is caused by #616, https://github.com/librosa/librosa/commit/f3114f280f5f9eaee5f2a69f90d3771b3d0eb5fa. Is this an intentional change or a bug?

#### Steps/Code to Reproduce

```py
In [1]: import librosa; import numpy as np

In [2]: librosa.__version__
Out[2]: '0.5.1'

In [3]: x, sr = librosa.load(librosa.util.example_audio_file(), sr=None)

In [4]: librosa.output.write_wav("test.wav", (x * 32768).astype(np.int16), sr)
---------------------------------------------------------------------------
ParameterError                            Traceback (most recent call last)
<ipython-input-4-9736a6fc3adb> in <module>()
----> 1 librosa.output.write_wav("test.wav", (x * 32768).astype(np.int16), sr)

/home/ryuichi/Dropbox/python/librosa/librosa/output.py in write_wav(path, y, sr, norm)
    214 
    215     # Validate the buffer.  Stereo is okay here.
--> 216     util.valid_audio(y, mono=False)
    217 
    218     # normalize

/home/ryuichi/Dropbox/python/librosa/librosa/util/utils.py in valid_audio(y, mono)
    157 
    158     if not np.issubdtype(y.dtype, np.float):
--> 159         raise ParameterError('data must be floating-point')
    160 
    161     if mono and y.ndim != 1:

ParameterError: data must be floating-point
```

#### Expected Results

No errors.

#### Actual Results

As shown above.

#### Versions

```py
In [5]: librosa.show_versions()
INSTALLED VERSIONS
------------------
python: 3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

librosa: 0.5.1

audioread: installed, no version number available
numpy: 1.13.3
scipy: 0.19.1
sklearn: 0.19.1
joblib: 0.11
decorator: 4.0.11
six: 1.11.0
resampy: 0.2.0

/home/ryuichi/anaconda3/lib/python3.6/site-packages/sphinx/util/compat.py:40: RemovedInSphinx17Warning: sphinx.util.compat.Directive is deprecated and will be removed in Sphinx 1.7, please use docutils' instead.
  RemovedInSphinx17Warning)
numpydoc: installed, no version number available
sphinx: 1.6.3
sphinx_rtd_theme: 0.2.4
sphinxcontrib.versioning: 2.2.1
matplotlib: 2.0.2
numba: 0.35.0+10.g143f70e90
```

**Comment by bmcfee** [comment]
Thanks for catching this.  It's ultimately a consequence of the strict dtype-checking issue that you linked to, and [this normalization issue](https://github.com/librosa/librosa/issues/415) from a while back.

I think we hadn't fully considered the consequences of strengthening the validation function to only allow floating point types, and I'm curious for more input and opinions on that before we finalize the 0.6 release.

I'm inclined to keep it as it currently is for the sake of consistency, but simplify the norm check in write_wav and improve the docs accordingly.

What do folks think?

**Comment by bmcfee** [comment]
Somehow this one slipped through the cracks.  @r9y9 @carlthome @stefan-balke have any thoughts on this?

**Comment by carlthome** [comment]
IMO write_wav is too specific and should be deprecated in favor of a new `librosa.save` function that mirrors `librosa.load` (by piggybacking of [pysoundfile](https://github.com/bastibe/SoundFile/tree/0.9.0#readwrite-functions)). The API symmetry would look sweet.

**Comment by carlthome** [comment]
And then if libsndfile gets their mp3 support going, maybe pysoundfile could even handle all of audioread's current duties in librosa.load (as discussed all over the GitHub issues :D)

**Comment by bmcfee** [comment]
@carlthome sure, but that's already in the long-term plans.  The question right now: should we relax validation for `write_wav` to allow integer output, or keep it strict?  Either is fine -- the former will take a bit of work -- but I'd like input from y'all.

**Comment by stefan-balke** [comment]
I would keep it as is. If people need more flexibility they could use `pysoundfile`...maybe we should document that? :)

**Comment by r9y9** [comment]
Could this have changelog entry? This breaks some user code. e.g., https://github.com/keithito/tacotron/blob/8edcd55b3f08f0492340e8b3ee60a693138f5473/util/audio.py#L16

**Comment by bmcfee** [comment]
> Could this have changelog entry? This breaks some user code. e.g.,

Yes! Sorry for that -- it's linked in updated changelog for rc1, but I'll make it more explicit for the final distribution.  Note that doc build/deployment takes several hours, so you won't see it right away in the main documentation.
