### ISSUE TITLE
Cite original literature

### ISSUE THREAD

**Issue by stefan-balke** [librosa/librosa#642]
Hey,

it happened to me that I want to know more about a particular feature–what a surprise.
However, we are often missing citation to the original literature.
For instance, `mel` filters (https://github.com/librosa/librosa/blob/master/librosa/filters.py#L259), what or who is "Stanley"? Stanley Smith Stevens?
However, adding a literature remark would clarify this and also could document if we deviate with our implementation from that.

What do you think, worth the effort?

**Comment by bmcfee** [comment]
> what or who is "Stanley"? Stanley Smith Stevens?

[This guy](http://www.slaney.org/malcolm/pubs.html)

But yes, there should be a reference to the [auditory toolbox](http://www.slaney.org/malcolm/pubs.html) in the docs there.

**Comment by lostanlen** [comment]
I couldn't believe that this issue had been unresolved for five months so I wrote a piece of doc in `mel_frequencies` (PR #701) in an attempt to close it.

**Comment by lostanlen** [comment]
can we close this now?
