### ISSUE TITLE
Error when trimming an array containing only zeros

### ISSUE THREAD

**Issue by naktinis** [librosa/librosa#645]
#### Description
Error when trimming an array containing only zeros

#### Steps/Code to Reproduce
    import librosa
    librosa.effects.trim(np.zeros(1), ref=1)

#### Expected Results
Should return an empty array and range of length zero.

#### Actual Results
    Traceback (most recent call last):
        ...
        librosa.effects.trim(np.zeros(1), ref=1)
      File ".../python3.6/site-packages/librosa/effects.py", line 478, in trim
        start = int(core.frames_to_samples(nonzero[0], hop_length))
    IndexError: index 0 is out of bounds for axis 0 with size 0

#### Versions
Linux-4.13.0-16-generic-x86_64-with-Ubuntu-17.10-artful
Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0]
NumPy 1.13.3
SciPy 1.0.0
librosa 0.5.1

**Comment by bmcfee** [comment]
Thanks for catching that!  It should be an easy fix (add a bounds check at [this line](https://github.com/librosa/librosa/blob/master/librosa/effects.py#L475)) if you're interested in making a PR.
