### ISSUE TITLE
Spectral flatness

### ISSUE THREAD

**Issue by keunwoochoi** [librosa/librosa#647]
I just started to wonder why don't we have spectral flatness in `librosa.feature`. Is there any historical reason? I can PR if it'd be useful.

**Comment by bmcfee** [comment]
Because nobody implemented it :grin: 

But seriously, a PR would be great.

**Comment by keunwoochoi** [comment]
Cool, few things to confirm. 
* It's based on a power spectrum, but the API would still wants `S=None` to be spectrogram magnitude for consistency with other `spectral_` siblings?

* Which way would you prefer, either `scipy.stats.mstats.gmean(S, axis=1)` or `np.exp(np.mean(np.log(X), axis=1))`?

..anything else?

**Comment by bmcfee** [comment]
> It's based on a power spectrum, but the API would still wants S=None to be spectrogram magnitude for consistency with other spectral_ siblings?

Yeah, it should match the styling of the other `spectral_` functions.



> Which way would you prefer, either scipy.stats.mstats.gmean(S, axis=1) or np.exp(np.mean(np.log(X), axis=1))?

Definitely not `log(S)` for stability reasons.  I assume (but have not checked) that scipy's `gmean` is numerically stable.  If not, we might want to just code it directly with a noise floor parameter to prevent underflow.

**Comment by keunwoochoi** [comment]
Seems like it's not?
```python
def gmean(a, axis=0):
    a, axis = _chk_asarray(a, axis)
    log_a = ma.log(a)
    return ma.exp(log_a.mean(axis=axis))
```

`amin=1e-10` as done in `power_to_db` seems the consistent choice. To summarise,

```python
def spectral_flatness(y=None, S=None, n_fft=2048, hop_length=512, amin=1e-5): # seems like we don't need sr and freq
    if S is None: compute S using y, n_fft, hop_length
    # few sanity check for S
    # sanity check for amin
    gmean = np.exp(np.mean(np.log(np.maximum(amin, S ** 2)), keepdims=True))
    amean = np.mean(np.maximum(amin, S ** 2), keepdims=True)
    return  gmean / amean

```

**Comment by keunwoochoi** [comment]
Ok writing test code doesn't seem very easy, but will try. But what should I do to put the images in the documentation? (Is it automatic?!)

**Comment by bmcfee** [comment]
> Ok writing test code doesn't seem very easy, but will try.

Do you have a reference implementation to compare against?  Most of the tests, aside from error checking, are just regression tests against old matlab code.



> But what should I do to put the images in the documentation? (Is it automatic?!)

It is automatic, but the doc build is not currently done by CI because it takes far too much compute resources to build.  Just follow the examples from the other functions, and if it's not quite right, we can clean it up during the documentation audit for the next release.

**Comment by keunwoochoi** [comment]
* I checked out [pymir](https://github.com/jsawruk/pymir/blob/master/pymir/Spectrum.py#L112), it's actually too similar to our implementation though. 
* Sure. I'll PR soon, perhaps I wanna add some more info like the range of the returned values etc.
