### ISSUE TITLE
How to open network path?

### ISSUE THREAD

**Issue by Shirley-Ji** [librosa/librosa#652]
I deployed tacotron onto Google Cloud ML to run. In it there is a step using librosa to open file, and I put the file onto Google Storage due to the reason that the program is running as a job scheduling to cloud, but librosa put a 'user_dir' ahead of the file path "IOError: [Errno 2] No such file or directory: '/user_dir/gs:/valid-reflector-xxx-mlengine/tacoron/WEB/Genesis/Genesis_8-15.wav'", then it does not recognize the path. Do I need to set any environment variables for librosa so that it can recognize the gs:// path?
In addition to this, there is another issue. librosa is using audioread to open the file, audioread is using buildin "open" method which cannot recognize the network path, "gs:// path". I tried to change it as file_io.FileIO(hp.text_file, mode='r'), then it works.

Is this an issue belonging to librosa, or I should use other methods to access/open this network path?

**Comment by bmcfee** [comment]
librosa uses [audioread](https://github.com/beetbox/audioread) under the hood to load files, and it doesn't support URL loading.  You might have to swap in [soundfile](https://github.com/bastibe/SoundFile) as is done in the [advanced I/O section](https://librosa.github.io/librosa/ioformats.html#read-file-like-objects) of the docs, and use the [GCS library](https://pypi.python.org/pypi/google-cloud-storage) to provide a file-like handle which you can then load through soundfile.  If you're only dealing with wavs (or other codecs supported by libsndfile) this shouldn't give you any trouble.

**Comment by Shirley-Ji** [comment]
Thanks @bmcfee for the comments, it is very helpful. For now, I will change to use soundfile or copy the files into local position and read it.
