### ISSUE TITLE
Ideas for GSOC-2018

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#653]
This issue is intended to collect and discuss projects for this year's Google Summer of Code.

## Numba acceleration

The primary issue for this topic is #157.  The goal of this project would be to improve the efficiency of core librosa routines by using [numba](numba.pydata.org) acceleration.  This is a substantial undertaking, as it touches many parts of the code-base.  However, this project does not require domain-specific knowledge (eg, music or dsp), since it focuses on improving efficiency and not developing new methods.

## Enhanced support for non-western systems

Primary issue is #641.  Most of librosa's pitch analysis functions (eg, chroma, cqt, and plotting) assume equal-temperament western scales, but this limits its use in non-western domains (Indian, Chinese, etc.).  An outline of the issues has been started in #641 with a focus on Indian music as a first step.

## Variable-Q transform

Mentioned in #342 , we currently only support constant-Q transforms, but the implementation could be generalized to support variable-Q as well.  This would improve the temporal precision of low-frequency signals, and broaden the applicability of the package.

## Other ideas?

Please comment below!

**Comment by stefan-balke** [comment]
On my list on "cool things in librosa" would be:

* Spectrogram Reassignment #394 (could be used for a MELODIAish salience representation)
* More sophisticated TSM methods #517

I have no experience with GSOC but I see your point in moving things to more general computer science task such as runtime optimization. I think even GPU support with `numba` could be tested. Having some nice benchmarks on the different task would be awesome.

**Comment by bmcfee** [comment]
We didn't make GSOC this year, so I'll close this one out.  (The primary issues we linked to will stay open, of course.)
