### ISSUE TITLE
getting problem in audioread in python using librosa

### ISSUE THREAD

**Issue by Awaisasghar154** [librosa/librosa#654]
audio_path=librosa.util.example_audio_file()
x, u = librosa.load(audio_path)
​
print(type(y) , type(sr))
print(y.shape , sr)

## it give the Error like that, i am using window 8.1 
 
NoBackendError                            Traceback (most recent call last)
<ipython-input-11-f3acd7b64d48> in <module>()
      1 audio_path=librosa.util.example_audio_file()
----> 2 x, u = librosa.load(audio_path)
      3 
      4 #print(type(y) , type(sr))
      5 #print(y.shape , sr)

C:\ProgramData\Anaconda3\lib\site-packages\librosa\core\audio.py in load(path, sr, mono, offset, duration, dtype, res_type)
    105 
    106     y = []
--> 107     with audioread.audio_open(os.path.realpath(path)) as input_file:
    108         sr_native = input_file.samplerate
    109         n_channels = input_file.channels

C:\ProgramData\Anaconda3\lib\site-packages\audioread\__init__.py in audio_open(path)
    114 
    115     # All backends failed!
--> 116     raise NoBackendError()

NoBackendError: 

any one can help me to spot this problem

**Comment by bmcfee** [comment]
Please fill out all fields in the issue form template.  This makes it much easier for us to diagnose your problem.  Thanks!

**Comment by Awaisasghar154** [comment]
i am new to github.  i can't be able to understand issue template.  please help me in this regads i totally stuck in above mention problem.

**Comment by bmcfee** [comment]
The quick answer here is that you have a problem with audioread, not librosa.  This has come up many times before, see: https://github.com/librosa/librosa/issues/589 https://github.com/librosa/librosa/issues/536  https://github.com/librosa/librosa/issues/219 and more.

You might find this comment useful: https://github.com/librosa/librosa/issues/390#issuecomment-359517517 as it seems to isolate this problem on windows platforms.  If that doesn't work for you, I suggest asking the audioread devs: https://github.com/beetbox/audioread
