### ISSUE TITLE
Getting sr from file

### ISSUE THREAD

**Issue by lonce** [librosa/librosa#659]
#### Description

core.load()  does not read the sr from file

#### Steps/Code to Reproduce

sig=[0,0,0,0,0,0]
writeSR=16000
librosa.output.write_wav("foofile", sig, sr=writeSR)
_,readSR = librosa.core.load("foofile")

#### Expected Results
readSR == writeSR 

#### Actual Results
readSR = 22050 # the default

#### Versions
librosa 0.5.1

**Comment by r9y9** [comment]
https://github.com/librosa/librosa/issues/383#issuecomment-230320315

An audio signal will be resampled to 22050Hz by default. sr=None uses the native sampling rate.

In other words, with 

```py
_,readSR = librosa.core.load("foofile", sr=None)
```
you will get expected results.

**Comment by bmcfee** [comment]
While this is well known behavior, the documentation for `load` should be more obvious about it.

I'll flag it for 0.6.
