### ISSUE TITLE
Problem Installing Librosa

### ISSUE THREAD

**Issue by xexuew** [librosa/librosa#661]
Hi i have a problem installing librosa in my virtual env:
Error:

> Failed building wheel for llvmlite
> `Command "/home/i42tohej/neuralnetwork/ENV/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-l5yu5m/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-aVAJVc-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/i42tohej/neuralnetwork/ENV/include/site/python2.7/llvmlite" failed with error code 1 in /tmp/pip-build-l5yu5m/llvmlite/
> `

**Comment by bmcfee** [comment]
This looks like an error in llvmlite, not librosa.  Probably best to take it up with https://github.com/numba/llvmlite
