### ISSUE TITLE
db_to_amplitude(amplitude_to_db(S)) doesn't preserve peak amplitude?

### ISSUE THREAD

**Issue by carlthome** [librosa/librosa#662]
#### Description
I'd expect roughly the same peak amplitude when decibel scaling a spectrogram, and then going back to linear amplitudes before the inverse spectral transform. Am I missing something obvious?

#### Steps/Code to Reproduce
```python
import librosa as lr

y = lr.load(lr.util.example_audio_file(), None)[0]
S = lr.amplitude_to_db(lr.stft(y))
y2 = lr.istft(lr.db_to_amplitude(S))
print(y.max(), y2.max())
```

#### Expected Results
> 0.64982605 0.64982605

#### Actual Results
> 0.64982605 0.16012064

#### Versions
Linux-4.4.0-92-generic-x86_64-with-debian-stretch-sid
Python 3.6.3 |Anaconda, Inc.| (default, Nov 20 2017, 20:41:42) 
[GCC 7.2.0]
NumPy 1.14.0
SciPy 1.0.0
librosa 0.5.1

**Comment by bmcfee** [comment]
Strange.  We have integration tests for `amplitude_to_db` and `db_to_amplitude`, and a quick check verifies that they work as expected:
```python
In [5]: D = lr.stft(y)

In [6]: S = lr.amplitude_to_db(D, top_db=None)

In [7]: Dinv = lr.db_to_amplitude(S)

In [10]: np.max(np.abs(D))
Out[10]: 215.17365

In [11]: np.max(np.abs(Dinv))
Out[11]: 215.17369
```

Whatever is going on must be down to `i/stft`, probably a windowing artifact?

**Comment by bmcfee** [comment]
Aha, it's down to phase loss.  You're reconstructing from just the magnitudes, so you're missing out on some constructive interference:

```python
>>> y, sr = librosa.load(librosa.util.example_audio_file())
>>> D = librosa.stft(y)
>>> Smag, p = librosa.magphase(D)
>>> S = librosa.amplitude_to_db(Smag, top_db=None)
>>> Sinv = librosa.db_to_amplitude(S)
>>> y2 = librosa.istft(Sinv * p)
>>> y3 = librosa.istft(D)
>>> print(y.max(), y2.max(), y3.max())
0.650596 0.650596 0.650596
```

**Comment by carlthome** [comment]
Ah, thanks! 🐤  🐨 

Maybe we could have a warning in `amplitude_to_db` when the input is dtype complex about that phase will be discarded.

**Comment by bmcfee** [comment]
@carlthome can you squeeze that warning pr into the next few days to make it into the 0.6.0 release?  NBD if not.
