### ISSUE TITLE
pip install fails on pypy on Mac

### ISSUE THREAD

**Issue by combacsa** [librosa/librosa#665]
#### Description
pip install fails on pypy on Mac

#### Steps/Code to Reproduce
```
$ pip install librosa --no-cache-dir
Collecting librosa
  Downloading librosa-0.5.1.tar.gz (1.5MB)
    100% |████████████████████████████████| 1.5MB 656kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<module>", line 1, in <module>
      File "/private/var/folders/8d/lctqm_y56xn7yxs6t27h8g1m0000gn/T/pip-build-9WgOH9/librosa/setup.py", line 5, in <module>
        version = imp.load_source('librosa.version', 'librosa/version.py')
      File "librosa/version.py", line 5, in <module>
        import sys
      File "librosa/__init__.py", line 7, in <module>
        from .version import version as __version__
    ImportError: cannot import name 'version'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/8d/lctqm_y56xn7yxs6t27h8g1m0000gn/T/pip-build-9WgOH9/librosa/
```

#### Expected Results
Successfully install librosa

#### Actual Results
Install fail

#### Versions
Darwin-17.4.0-x86_64-i386-64bit
Python 2.7.13 (84a2f3e6a7f8, Oct 03 2017, 18:46:00)
[PyPy 5.9.0 with GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)]
pip 9.0.1 from /Users/khbyun/.pyenv/versions/pypy2.7-5.9.0/site-packages (python 2.7)

**Comment by bmcfee** [comment]
That's really strange.  We don't test on pypy, but I see no obvious reason for this specific failure. Side note: I'm not sure that all of our dependencies will work in pypy anyway, but it's worth checking.

For a bit of background, this is not coming from the librosa package itself, but from the setup script, which uses the `imp` module to pull librosa's version string out of the source code prior to installation.  We do this to avoid having duplicate copies of the version string lying around.  Something appears to be going wrong with `imp` here, perhaps due to local/relative imports?

**Comment by bmcfee** [comment]
I made a local pypy install, and can confirm this behavior on linux (ubuntu).

It would be nice to get the install script working on pypy.  However, several upstream dependencies do not yet work according to http://packages.pypy.org/, including `matplotlib`, `sklearn`, and `scipy`, so even if we sort this out, it wouldn't result in a usable package.

**Comment by combacsa** [comment]
Glad(?) to hear that it behavior was confirmed on linux(ubuntu). Don't know how to modify setup script to work properly on pypy though...

**Comment by bmcfee** [comment]
If you really want, you can hack the version import out of the setup.py, and hard code it to 0.6.  However, it's still not going to work in pypy because the upstream dependencies don't work.

**Comment by bmcfee** [comment]
Closing this out, since any fix is beyond our direct control.
