### ISSUE TITLE
scikits.samplerate dependency

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#67]
The `scikits.samplerate` dependency in librosa is a soft dependency, meaning that it will fall back gracefully (and slowly) on `scipy.signal`'s resampler.

The reason for the soft dependency is that the pypi package does not automatically install `libsamplerate` from source, so the entire install chain for `librosa` fails.

**Comment by dpwe** [comment]
Since this is the page you get if you Google "librosa scikits.samplerate", it would be a good place to describe how to resolve this dependency.

For me (Ubuntu 14.04) the following:

sudo apt-get install libsamplerate0-dev
sudo pip install scikits.samplerate

.. seems to have done the trick.

**Comment by dela3499** [comment]
This worked for me as well. Thanks for posting it!

**Comment by bmcfee** [comment]
One more piece of clarification: the main distribution of `scikits.samplerate` found in pip does not support python 3.  There's a fork that does fix the problem though, which can be easily installed by saying

```bash
[sudo] pip install git+https://github.com/gregorias/samplerate.git
```

**Comment by ejhumphrey** [comment]
I know the issue is closed, but I'd like to up-vote that this little nugget of wisdom be migrated to the mainpage `README.md` ... I'm (finally) trying to get on the py3 wagon, and this just bit me (the "fallback" didn't work so well for `librosa.load`).

**Comment by bmcfee** [comment]
Adding this to the to-do list when compiling 0.4.2 release notes.

What we really ought to do, though, is find some enterprising young upstart to write a pip-friendly numba (or cython) implementation of sinc resampling.

**Comment by mmeloon** [comment]
Thanks @dpwe ! My code was hung on a call to scipy.signal.resample in librosa's resample() function. When I followed your instructions to install scikits.samplerate, it worked like a charm! Don't know what's the deal with the scipy one, but sure glad to find an alternative!

**Comment by bmcfee** [comment]
> Thanks @dpwe ! My code was hung on a call to scipy.signal.resample in librosa's resample() function. When I followed your instructions to install scikits.samplerate, it worked like a charm! Don't know what's the deal with the scipy one, but sure glad to find an alternative!

As of today, this should not be an issue.  librosa now depends on resampy, which operates similarly to `scikits.samplerate` but installs automatically.

**Comment by dela3499** [comment]
Glad to hear it, good sir!

**Comment by acdclab** [comment]
Thanks @dpwe . That trick worked for me on Linux machine. But I can't install libsamplerate on windows. Can you please help me on this?

**Comment by stefan-balke** [comment]
@acdclab no longer necessary. resampy does this job for you know.
Maybe update your version of librosa and give it a try.

Installing libsamplerate on Windows only works with prebuild dlls so far.
