### ISSUE TITLE
Add simple time series plotting function

### ISSUE THREAD

**Issue by stefan-balke** [librosa/librosa#676]
Hey,

I just thought of adding a little helper function to the `display` module which simply plots a time series.
Basically a `plt.plot()` but uses the `librosa.display.TimeFormatter`. I have this already as a helper function and it comes in handy in times where you might have 1d-features with different sampling rate and want to compare them...whatever, no big deal. Is this interesting as a general function?

## Code

```
import numpy as np
import matplotlib.pyplot as plt

import librosa
import librosa.display


sr = 10

x = np.random.rand(100)

plt.figure(figsize=(10, 6))
times = librosa.samples_to_time(np.arange(len(x)), sr=sr)
plt.plot(times, x)
plt.gca().xaxis.set_major_formatter(librosa.display.TimeFormatter(lag=False))
plt.gca().xaxis.set_label_text('Time')

plt.show()
```
![example](https://user-images.githubusercontent.com/7326732/36314024-d093f67e-1333-11e8-897f-647d9b477454.png)

**Comment by bmcfee** [comment]
I see how this could be handy, but I'm a little worried about it becoming a slippery slope toward wrapping all kinds of matplotlib functions (not just plot, but stem, step, scatter, etc).

What if, instead, we had a display helper that could probe `gca()` to get the data extent, and given a sample rate, adds an appropriate time decorator to the chosen axis?  Then you could do all sorts of things beyind `plot()`, and still get the same benefits.  For example:

```python
>>> plt.stem(x)
>>> librosa.display.time_axis(sr=10, axis='x')
```

**Comment by stefan-balke** [comment]
Yes, I see your point.

Your solution sounds like a good way to handle this!

**Comment by bmcfee** [comment]
I'm not sure how easy it is to pull off -- it might require adding an axis transformation change units from samples to seconds, prior to adding the time decorator.  [Relevant mpl docs](https://matplotlib.org/2.0.0/users/transforms_tutorial.html)

**Comment by lostanlen** [comment]
Color-code the waveform according to a perceptual audio feature (e.g. spectral brightness à la Traktor) and you've got a unique viz in the Pythonic landscape here ☺️

**Comment by bmcfee** [comment]
I propose that this feature be rolled into #1207
