### ISSUE TITLE
librosa becomes slower the longer it runs

### ISSUE THREAD

**Issue by albertz** [librosa/librosa#681]
#### Description
My code is basically:

```
for fn in lots_of_flac_files:
  audio, sample_rate = librosa.load(fn, sr=None)
  mfccs = librosa.feature.mfcc(
    audio, sr=sample_rate,
    n_mfcc=40,
    hop_length=int(0.01 * sample_rate), n_fft=int(0.025 * sample_rate))
```

All files are about the same length. I added some simple code to estimate the remaining time.
The strange thing is that this estimation did not went down, but went up only in the beginning, i.e. it became slower and slower. How could that be?
Also, I noticed that the memory consumption seems to slowly increase all the time.

#### Expected Results
Every call to `load` and `mfcc` takes about the same time.

#### Actual Results
The time to execute `load` and `mfcc` always increases. (Maybe only one of them; I didn't tested.)

#### Versions

```
>>> import platform; print(platform.platform())
Linux-4.9.0-3-amd64-x86_64-with-debian-9.3
>>> import sys; print("Python", sys.version)
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.14.1
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.0.0
>>> import librosa; print("librosa", librosa.__version__)
librosa 0.6.0
>>> 
```

**Comment by albertz** [comment]
@bmcfee Is this a question? I would say this is a serious bug.

**Comment by bmcfee** [comment]
That's strange, but probably not a librosa issue per se.  Nothing we do has global scope, so I see no avenue for leakage. How exactly are you profiling this to demonstrate a slow-down?  Are you tracking memory as well as running time? Some example output here might be helpful.

At any rate, I suspect one of two things:

1. python's garbage collector is not running frequently enough, hence increased memory usage.  This shouldn't translate to slow-down unless you're hitting swap, but the details will vary significantly depending on your system.
2. Audioread might be leaking file handles.  This might depend on which decoder backend it's using to handle flac.

Option 2 would be easy to test by swapping out audioread for pysoundfile, and see if the behavior persists.  Option 1 is a bit more thorny, as you'd have to manually trigger the gc.

**Comment by bmcfee** [comment]
> Is this a question? I would say this is a serious bug.

The question is "why does this happen?"  I wouldn't tag it as `bug` unless it's demonstrated to be caused specifically by librosa.

**Comment by albertz** [comment]
Actually, I think you are right in the assumption that it's not librosa related.
I was working with the [LibriSpeech](http://www.openslr.org/12/) data. [Here](https://gist.github.com/albertz/4b8874a5f9aa9bce88180871b5aef8f6) is a small demo script.
It seems as if the files are ordered in such a way that the average audio length slowly increases.
See this output:

```
albert@wc4:~/data-local/corpora/asr/LibriSpeech$ python3 iter-corpus-rosa.py
num files: 10000
current: 1/10000 (0.01%) (0:09:33) total estimated: 0:09:33 avg audio len: 225360.0
1000/10000 (10.00%) (0:05:04) [|||||||                              10.00%                                     ]current: 1001/10000 (10.01%) (0:05:04) total estimated: 0:05:38 avg audio len: 193628.37562437562
2000/10000 (20.00%) (0:04:30) [||||||||||||||                       20.00%                                     ]current: 2001/10000 (20.01%) (0:04:30) total estimated: 0:05:38 avg audio len: 196291.17691154423
3000/10000 (30.00%) (0:03:54) [|||||||||||||||||||||                30.00%                                     ]current: 3001/10000 (30.01%) (0:03:54) total estimated: 0:05:34 avg audio len: 197733.15828057315
4000/10000 (40.00%) (0:03:23) [||||||||||||||||||||||||||||         40.00%                                     ]current: 4001/10000 (40.01%) (0:03:23) total estimated: 0:05:39 avg audio len: 197672.58310422394
5000/10000 (50.00%) (0:02:50) [|||||||||||||||||||||||||||||||||||| 50.00%                                     ]current: 5001/10000 (50.01%) (0:02:50) total estimated: 0:05:40 avg audio len: 198231.5544891022
6000/10000 (60.00%) (0:02:15) [|||||||||||||||||||||||||||||||||||| 60.00% |||||||                             ]current: 6001/10000 (60.01%) (0:02:15) total estimated: 0:05:39 avg audio len: 197896.80436593902
7000/10000 (70.00%) (0:01:42) [|||||||||||||||||||||||||||||||||||| 70.00% ||||||||||||||                      ]current: 7001/10000 (70.01%) (0:01:42) total estimated: 0:05:42 avg audio len: 199781.65490644192
8000/10000 (80.00%) (0:01:08) [|||||||||||||||||||||||||||||||||||| 80.00% |||||||||||||||||||||               ]current: 8001/10000 (80.01%) (0:01:08) total estimated: 0:05:41 avg audio len: 199545.1073615798
9000/10000 (90.00%) (0:00:34) [|||||||||||||||||||||||||||||||||||| 90.00% ||||||||||||||||||||||||||||        ]current: 9001/10000 (90.01%) (0:00:34) total estimated: 0:05:43 avg audio len: 199601.44961670926
Done. Total time: 0:05:43                                                                                       
```

If I shuffle the file names randomly, this doesn't seem to happen.
However, what I still see is the increase in memory consumption. This is just by watching htop or so.
It starts very low (under 100MB), but over the whole data, it ends up with over 8GB.

**Comment by albertz** [comment]
I just tried with PySoundFile instead of librosa.load (i.e. audioread) and it seems as if the memory leak is gone. Memory consumption mostly stays constant.
Actually, I also had other problems with audioread. It uses glib/gst in my case. But that mainloop it installs breaks the sig-int handling. Also, the ca_available() check it does on every call was very costly. See [my script](https://gist.github.com/albertz/4b8874a5f9aa9bce88180871b5aef8f6) for some ugly monkey patches to fix both things.
But as it also has the memory leak, and PySoundFile works just fine, and also is faster in this demo, I will just switch to that.
Why don't you use that by default? Maybe audioread should also add that and then even try that one first.

**Comment by bmcfee** [comment]
> Why don't you use that by default?

Because libsndfile does not support mp3 yet.  When it does, we'll switch over.

**Comment by bmcfee** [comment]
@albertz It seems like this is resolved for now -- can I close it out?

**Comment by albertz** [comment]
Well, not totally resolved, but we can say that it is not a librosa bug, so yes, this can be closed.

**Comment by bmcfee** [comment]
Thanks!
