### ISSUE TITLE
Specify axis instance in plotting functions

### ISSUE THREAD

**Issue by choldgraf** [librosa/librosa#683]
I noticed that there's no option to say "plot this spectrogram on this specific axis object". The code just uses `plt.gca`. Would you be friendly to `specshow(..., ax=myaxis)`. And under the hood it'd do `if ax is None: axis = plt.gca`?

**Comment by bmcfee** [comment]
Good catch -- I've implemented that exact thing in related packages (jams, mir_eval), but somehow never did it for librosa.  And yeah, a pr for this would be great!

**Comment by bmcfee** [comment]
Closed by merging #687
