### ISSUE TITLE
 module 'librosa' has no attribute 'logamplitude'

### ISSUE THREAD

**Issue by georgiazhang** [librosa/librosa#693]
Hello all,
How to solve the problem of "AttributeError: module 'librosa' has no attribute 'logamplitude'"
I can't find any solutions on the Internet.

**Comment by lostanlen** [comment]
Thank you for your question.
`librosa.core.logamplitude` has been removed in v0.6 (PR #627) and has now been replaced by `amplitude_to_db`.

**Comment by msaadsadiq** [comment]
cannot import name amplitude_to_db, please suggest

**Comment by lostanlen** [comment]
@msaadsadiq make sure you're running the latest stable version of librosa
