### ISSUE TITLE
pip install fails on NVIDIA Jetson TX2

### ISSUE THREAD

**Issue by whaoer** [librosa/librosa#697]
#### Description
pip install fails on NVIDIA Jetson TX2

#### Steps/Code to Reproduce
```
unzip librosa-0.6.0.zip
cd librosa-0.6.0.zip
sudo pip install -e .

running install
    running build
    got version from file /tmp/pip-install-ZUciLA/llvmlite/llvmlite/_version.py {'version': '0.22.0', 'full': '46b4b5e288f3a175332ad68d8c3745c63fbb5701'}
    running build_ext
    /usr/bin/python /tmp/pip-install-ZUciLA/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-install-ZUciLA/llvmlite/ffi/build.py", line 141, in <module>
        main()
      File "/tmp/pip-install-ZUciLA/llvmlite/ffi/build.py", line 131, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-ZUciLA/llvmlite/ffi/build.py", line 94, in main_posix
        "to the path for llvm-config" % (llvm_config,))
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/usr/bin/python' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ZUciLA/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-v_Ud9g/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-ZUciLA/llvmlite/
```

#### Expected Results
Successfully install librosa

#### Actual Results
Install fail

#### Versions
ubuntu16.04
python 2.7.12

**Comment by bmcfee** [comment]
This appears to be an llvmlite issue, not librosa.  There are apparently no llvmlite wheels for your platform, so it's trying to build from source.  You don't appear to have the LLVM development package installed, so it fails to build.  Python packages cannot specify dependencies to ubuntu packages, so this is kind of unavoidable.

My guess is that you could fix this by apt-get installing `llvm-dev` and trying again.

**Comment by pfriesch** [comment]
`lvm-dev` did not work for me on `ubuntu 16.04`.

```Dockerfile

# install llvm & llvmlite for librosa
RUN apt-get install -y wget
RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -

RUN echo deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main >> /etc/apt/sources.list
RUN echo deb-src http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main >> /etc/apt/sources.list

RUN apt-get update && apt-get install -y llvm-6.0

RUN update-alternatives --install \
        /usr/bin/llvm-config       llvm-config      /usr/bin/llvm-config-6.0  200 \
--slave /usr/bin/llvm-ar           llvm-ar          /usr/bin/llvm-ar-6.0 \
--slave /usr/bin/llvm-as           llvm-as          /usr/bin/llvm-as-6.0 \
--slave /usr/bin/llvm-bcanalyzer   llvm-bcanalyzer  /usr/bin/llvm-bcanalyzer-6.0 \
--slave /usr/bin/llvm-cov          llvm-cov         /usr/bin/llvm-cov-6.0 \
--slave /usr/bin/llvm-diff         llvm-diff        /usr/bin/llvm-diff-6.0 \
--slave /usr/bin/llvm-dis          llvm-dis         /usr/bin/llvm-dis-6.0 \
--slave /usr/bin/llvm-dwarfdump    llvm-dwarfdump   /usr/bin/llvm-dwarfdump-6.0 \
--slave /usr/bin/llvm-extract      llvm-extract     /usr/bin/llvm-extract-6.0 \
--slave /usr/bin/llvm-link         llvm-link        /usr/bin/llvm-link-6.0 \
--slave /usr/bin/llvm-mc           llvm-mc          /usr/bin/llvm-mc-6.0 \
--slave /usr/bin/llvm-mcmarkup     llvm-mcmarkup    /usr/bin/llvm-mcmarkup-6.0 \
--slave /usr/bin/llvm-nm           llvm-nm          /usr/bin/llvm-nm-6.0 \
--slave /usr/bin/llvm-objdump      llvm-objdump     /usr/bin/llvm-objdump-6.0 \
--slave /usr/bin/llvm-ranlib       llvm-ranlib      /usr/bin/llvm-ranlib-6.0 \
--slave /usr/bin/llvm-readobj      llvm-readobj     /usr/bin/llvm-readobj-6.0 \
--slave /usr/bin/llvm-rtdyld       llvm-rtdyld      /usr/bin/llvm-rtdyld-6.0 \
--slave /usr/bin/llvm-size         llvm-size        /usr/bin/llvm-size-6.0 \
--slave /usr/bin/llvm-stress       llvm-stress      /usr/bin/llvm-stress-6.0 \
--slave /usr/bin/llvm-symbolizer   llvm-symbolizer  /usr/bin/llvm-symbolizer-6.0 \
--slave /usr/bin/llvm-tblgen       llvm-tblgen      /usr/bin/llvm-tblgen-6.0


RUN pip3 install llvmlite
###
```

I don't know if all the `update-alternatives` are necessary though

**Comment by pfriesch** [comment]
The `apt-get` install seems to work again for me. @whaoer

**Comment by saquibntt** [comment]
Hello,

It seems that llvm-dev is installed, but librosa is still having problems with installing tx2. Below is the terminal output

`nvidia@tegra-ubuntu:/opt/nvidia$ pip install librosa
Collecting librosa
Requirement already satisfied: six>=1.3 in /usr/lib/python2.7/dist-packages (from librosa) (1.10.0)
Collecting numba>=0.38.0 (from librosa)
Collecting audioread>=2.0.0 (from librosa)
Requirement already satisfied: decorator>=3.0.0 in /usr/lib/python2.7/dist-packages (from librosa) (4.0.6)
Collecting resampy>=0.2.0 (from librosa)
Collecting scikit-learn!=0.19.0,>=0.14.0 (from librosa)
Requirement already satisfied: scipy>=0.14.0 in /usr/lib/python2.7/dist-packages (from librosa) (0.17.0)
Requirement already satisfied: numpy>=1.8.0 in /usr/local/lib/python2.7/dist-packages (from librosa) (1.14.2)
Collecting joblib>=0.7.0 (from librosa)
  Using cached https://files.pythonhosted.org/packages/4f/51/870b2ec270fc29c5d89f85353da420606a9cb39fba4747127e7c7d7eb25d/joblib-0.11-py2.py3-none-any.whl
Requirement already satisfied: singledispatch in /home/nvidia/.local/lib/python2.7/site-packages (from numba>=0.38.0->librosa) (3.4.0.3)
Requirement already satisfied: enum34 in /usr/local/lib/python2.7/dist-packages (from numba>=0.38.0->librosa) (1.1.6)
Collecting llvmlite>=0.23.0dev0 (from numba>=0.38.0->librosa)
  Using cached https://files.pythonhosted.org/packages/c6/0f/d33ec3d030d4de01ba251c7dcf1051cb9f558221d64421439a61b0d81020/llvmlite-0.23.0.tar.gz
Requirement already satisfied: funcsigs in /usr/local/lib/python2.7/dist-packages (from numba>=0.38.0->librosa) (1.0.2)
Building wheels for collected packages: llvmlite
  Running setup.py bdist_wheel for llvmlite ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-wnX_gp/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-AwKwkG --python-tag cp27:
  running bdist_wheel
  /usr/bin/python /tmp/pip-install-wnX_gp/llvmlite/ffi/build.py
  LLVM version... 3.8.0
  
  Traceback (most recent call last):
    File "/tmp/pip-install-wnX_gp/llvmlite/ffi/build.py", line 143, in <module>
      main()
    File "/tmp/pip-install-wnX_gp/llvmlite/ffi/build.py", line 133, in main
      main_posix('linux', '.so')
    File "/tmp/pip-install-wnX_gp/llvmlite/ffi/build.py", line 105, in main_posix
      raise RuntimeError(msg)
  RuntimeError: Building llvmlite requires LLVM 6.0.x. Be sure to set LLVM_CONFIG to the right executable path.
  Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.
  
  error: command '/usr/bin/python' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite, numba, audioread, resampy, scikit-learn, joblib, librosa
  Running setup.py install for llvmlite ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-wnX_gp/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-EbjXKZ/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    got version from file /tmp/pip-install-wnX_gp/llvmlite/llvmlite/_version.py {'version': '0.23.0', 'full': 'a924507857937369bdeb795a0f2d0a85ee27a0c1'}
    running build_ext
    /usr/bin/python /tmp/pip-install-wnX_gp/llvmlite/ffi/build.py
    LLVM version... 3.8.0
    
    Traceback (most recent call last):
      File "/tmp/pip-install-wnX_gp/llvmlite/ffi/build.py", line 143, in <module>
        main()
      File "/tmp/pip-install-wnX_gp/llvmlite/ffi/build.py", line 133, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-wnX_gp/llvmlite/ffi/build.py", line 105, in main_posix
        raise RuntimeError(msg)
    RuntimeError: Building llvmlite requires LLVM 6.0.x. Be sure to set LLVM_CONFIG to the right executable path.
    Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.
    
    error: command '/usr/bin/python' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-wnX_gp/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-EbjXKZ/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-wnX_gp/llvmlite/
`
