### ISSUE TITLE
General match_intervals improvements

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#706]
#### Description
In auditing `match_intervals` in preparation for numbafication #157, I noticed a couple of undocumented / undefined behaviors that should be made explicit.  I'm tagging these as "bug" because they are definitely not intended behavior, and could silently cause some strange behaviors down the road.

1. What should happen when a query interval has no overlap with any of the targets?  The current logic for this is [here](https://github.com/librosa/librosa/blob/master/librosa/util/utils.py#L837), which would amount to argmax over an all zeros vector.  `np.argmax` breaks ties in favor of the first maximal element, which in this case, would be 0 (the first target interval).  This seems bad and wrong here.

  Some suggested alternative behaviors:

  - Use a null value.  `None` seems reasonable, but it would require returning a list of ints instead of a `ndarray(dtype=int)`.  `NaN` also seems reasonable, but would require `dtype=float`, which would not work with fancy indexing.
  - Throw an exception.  At the very least, we should throw a warning when this happens.
  - Map to the "closest" non-overlapping interval [in the set sense](https://en.wikipedia.org/wiki/Distance#Distances_between_sets_and_between_a_point_and_a_set).
  - Maybe have a user-supplied option to switch between some of these modes?

2. How should we break ties?  The current interval scoring uses the [raw intersection](https://github.com/librosa/librosa/blob/master/librosa/util/utils.py#L835) between intervals, and then selects the first maximal target as the match.  This seems wrong / under-determined when there are overlapping intervals.  I think [Jaccard similarity](https://en.wikipedia.org/wiki/Jaccard_index) is a better selection criterion, being a proper metric and all.  This would break ties in favor of the "tightest" matching interval, which I think is sensible.

### A note on candidate filtering

@danagilliann and I worked out a slightly faster matching algorithm than what we currently have.  It's still `O(nm)` in the worst case, but in the average case, should behave more like `O(m log m + n log m)`.

Here's some simplified pseudo-code of the current method (brute-force quadratic search):
```python
output = []
for query in from_intervals:
   best_score = 0
   best_idx = 0
   for idx, candidate in enumerate(to_intervals):
      score = similarity(query, candidate)
      if score > best_score:
          best_score, best_idx = score, idx
   output.append(best_idx)
```

The acceleration idea is to quickly filter out any intervals which we know to not intersect the query.  This can be done using two sorted arrays, one for the interval starts and one for the interval ends.  Any interval with `start > query_end` will have `score==0`; likewise for any interval with `end < query_start`.  Therefore, we only need to search over intervals with `start <= query_end` and `end >= query_start`, which can each be found in time `O(log m)`.

The accelerated version of the algorithm looks as follows:
```python
output = []
start_index = np.argsort(to_intervals[:, 0])  # sort index of the interval starts
end_index = np.argsort(to_intervals[:, 1])  # sort index of the interval ends

start_sorted = to_intervals[start_index, 0]  # and sorted values of starts
end_sorted = to_intervals[end_index, 1]  # and ends

for query in from_intervals:
   # Find the intervals that start after our query ends
   after_query = np.searchsorted(start_sorted, query[1], side='right')
   # And the intervals that end after our query begins
   before_query = np.searchsorted(end_sorted, query[0], side='left')

   candidates = set(start_index[:after_query]) & set(end_index[before_query:])

   # Proceed as before
   best_score = 0
   best_idx = 0
   for idx in candidates:
      score = similarity(query, to_intervals[idx])
      if score > best_score:
          best_score, best_idx = score, idx
   output.append(best_idx)
```

The speedup here comes from the fact that we expect the `candidates` set to be small most of the time (much less than the entire `to_intervals` set).

As a side note, we can re-use these sorted arrays to quickly find the closest interval in the candidate set is empty, if that fallback mode is desired.

**Comment by bmcfee** [comment]
I thought this one over a bit more, and I think the following are sensible:

1. Define two different distance metrics over intervals.
  - The first is just the Jaccard distance `(1 - intersection / union)`.  Call this `dJ(int1, int2)`
  - The second is Jaccard + set distance using `|x-y|` as the underlying metric over elements.  For disjoint intervals `[a,b], [c, d]`, the set distance amounts to `min(|a - d|, |c - b|)`.  Call the combined metric `dH` (hybrid).
2. Let the user select which metric to use: `jaccard` or `hybrid`.  If using Jaccard, and we encounter any from intervals that have 0 overlap with all `to` intervals, then throw an exception.

This implementation has the following benefits:

1. We never have to worry about encoding match failures.  Everything either succeeds or fails.
2. All behavior is well-defined, since both `jaccard` and `hybrid` are proper distance metrics.  There may still be "ties" under both of the proposed metrics, which can break arbitrarily (eg using the sort order in the accelerated implementation).
3. A user can decide whether or not to allow non-overlapping matches.  This is not currently possible.
4. We can recover the hybrid metric using the implementation I outlined above: we don't need to compute the hybrid metric to all target intervals to efficiently find nearest intervals.

**Comment by bmcfee** [comment]
(one more update)

Alternately, we could just use [Hausdorff distance](https://en.wikipedia.org/wiki/Hausdorff_distance) to support overlapping and disjoint calculations generally.  This might rule out our efficiency hack above though.

**Comment by bmcfee** [comment]
Summarizing offline conversation with @danagilliann from yesterday:

- The choice of metric will be determined by a new parameter: `strict=True` uses Jaccard distance, and `strict=False` uses the hybrid distance.
- Still on the fence about what the default value for `strict` should be.
  - Argument for `True`: it would expose bugs in downstream systems (because they would stop working if depending on undefined behavior).
  - Argument for `False`: strict matching would be a breaking change.
- If @danagilliann doesn't have time to implement this, I'll probably take it over.

**Comment by lostanlen** [comment]
> Still on the fence about what the default value for strict should be.
>  Argument for True: it would expose bugs in downstream systems (because they would stop working if depending on undefined behavior).
> Argument for False: strict matching would be a breaking change.

A few quotes for the Zen of Python:

Explicit is better than implicit. 
Simple is better than complex.
Errors should never pass silently.
Now is better than never.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.

**Comment by bmcfee** [comment]
I agree with all of that in principle, but it gets tricky when those principles need to be reconciled with semantic versioning requirements and practical considerations of not changing things too rapidly for people to keep up with.  I generally like to keep about a year between releases with breaking changes so that people have time to observe warnings and adjust code, but it's only been 3 months since 0.6.

That said, a bug is a bug, and I definitely prefer fixing it and alerting people to reliance on undefined behavior.  I suspect this is all pretty academic anyway, since I'm not sure anyone even uses `match_intervals`.  From what I can tell by a quick github code search, it's only used in our test code, some demo notebooks, my segmenter, msaf, and slag (so: all MARL projects).

This makes me lean toward `strict=True` by default, inside a minor revision, even if it is a breaking change in the strictest possible sense.

**Comment by lostanlen** [comment]
Thanks for the reply. It's true that versioning come into the Equation here for such a large userbase project as librosa.
I would say that any contribution that brings us closer to 1.0 is worth having sooner than later, but that's a matter of strategy on which I don't have much insight.
