### ISSUE TITLE
pip install fails 

### ISSUE THREAD

**Issue by hunaa** [librosa/librosa#711]
#### Expected Results
librosa installed
#### Actual Results
pillow 4.0.0 requires olefile, which is not installed.
Installing collected packages: llvmlite, numba, resampy, librosa
  Found existing installation: llvmlite 0.15.0
Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we can
not accurately determine which files belong to it which would lead to only a par
tial uninstall.

#### Versions
Python 3.6.0 Windows 8.1

**Comment by bmcfee** [comment]
This appears to be a problem with llvmlite, and not librosa.  I suggest taking it up with the llvmlite maintainers.

**Comment by golyalpha** [comment]
You need to remove llvmlite, or maybe force it to install. Had similar issue with some other lib in another project. (-I/--ignore-installed switch in your case)

**Comment by hunaa** [comment]
Thanks for your responses.

Turned out, updating llvmlite and installing the missing pillow for Python 3.6 resolved the issue for me

**Comment by shreyasose** [comment]
manually uninstall/delete the all llvmlite file from c drive or ananconda folder site packages.
