### ISSUE TITLE
times_like, samples_like helpers

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#717]
#### Description

I often find myself needing to compute the time array corresponding to a particular feature matrix.  For example, if we have a mel spectrogram `M` computed ast some `sr` and `hop_length`, then we need to generate something like
```python
librosa.frames_to_time(np.arange(M.shape[-1]), sr=sr, hop_length=hop_length)
```
which is kind of a lot of boilerplate.

What I'd like is a simple helper that can generate the time grid easily:
```python
times = librosa.times_like(M, sr=sr, hop_length=hop_length, axis=-1)
```
with defaults aligned to the librosa defaults.  It could also easily take a scalar value `n`, in which case it would generate times for frames `0..n-1`.

All of the above applies equally well to `samples`.

I think this shouldn't amount to much more than a handy wrapper for functions we already have, but it would make a lot of downstream code easier to read.

**Comment by lostanlen** [comment]
Excellent. If #342 ever gets closed, the multi-phase CQT will be slightly counter-intuitive, but aside from that caveat, I see no reason of not doing it
