### ISSUE TITLE
hanning -> hann

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#719]
#### Description
scipy.signal.hanning is deprecated, and should be replaced by `hann`.

We currently use this in `chroma_cens`.

**Comment by bmcfee** [comment]
Note: i grepped the build logs for deprecationwarnings and found no others.  This should be the only thing in need of update.

**Comment by lostanlen** [comment]
Good. Hanning is such an unfortunate pun on Hamming, which only causes confusion.

**Comment by bmcfee** [comment]
Oops, sorry @michael-the1, I patched this on master without noticing that you were already working on this!

**Comment by michael-the1** [comment]
Aah, no problem. I had 10 minutes to spare and thought I'd fix this, but I had to leave before I could actually make the pull request.

While I'm at it, let me thank you for all the work on this library. I'm using it for my Msc. thesis. Hope to show some cool results soon.

**Comment by lostanlen** [comment]
@michael-the1 welcome to librosa! I'm glad to hear that you're using it in your own research.
If you feel like contributing to librosa on your spare time, #717 is still up to grabs ... :)
