### ISSUE TITLE
Get mean, maximum and minimum frequency

### ISSUE THREAD

**Issue by Alex-2018** [librosa/librosa#720]
Hi
How can I get mean, maximum and minimum frequency of a .WAV file?

**Comment by lostanlen** [comment]
Hello. It sounds like what you need is a pitch tracker, that is, a system that converts the WAV file into a time series which gives the fundamental frequency as a function of time. Then you can extract some summary statistics of that time series by turning it into a numpy array.
The state of the art in monophonic pitch tracking of music is held by a convolutional neural network called "crepe": github.com/marl/crepe
Another option is the pYIN algorithm, which does not use any machine learning but is based on the autocorrelation function of the waveform.

However, none of this will not very well is the music is polyphonic (has multiple notes played at once by the same instrument or multiple instruments).
If I did not understand correctly, please clarify your question.

**Comment by bmcfee** [comment]
(Note: in general, this kind of question is better suited to the [google group](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/librosa)).

I endorse @lostanlen's answer if what you're after is pitch tracking.  But more generally, it's not obvious what is meant by "minimum" or "mean" frequency in a wav file.  Every frequency (up to Nyquist, half the sampling rate) is present in any signal, but what matters is how much energy is associated with each frequency.  So it will be helpful to think about how much energy you want to consider as "present" in the .wav, if you're interested in things like minimum, mean, and maximum.

A couple of other functions that you might find useful:

- [spectral_centroid](https://librosa.github.io/librosa/generated/librosa.feature.spectral_centroid.html) computes the "average" frequency at each frame, where frequencies are weighted relatively by their energy.
- [spectral_bandwidth](https://librosa.github.io/librosa/generated/librosa.feature.spectral_bandwidth.html) similar to centroid, but for variance (or other moments).
- [spectral_rolloff](https://librosa.github.io/librosa/generated/librosa.feature.spectral_rolloff.html) essentially the maximum: finds the frequency `f` such that almost all of the energy (by default, 85%) in the frame is at frequencies below `f`.  If you set the roll-off to a small fraction (say, 10%), this would give you an estimate of the effective minimum frequency.

**Comment by bmcfee** [comment]
Following up on this, I noticed that the docstring for `spectral_rolloff` doesn't actually explain what roll-off is or how to use it.

If anyone wants to go in and expand the docs on this, it would be greatly appreciated!

**Comment by ZiyaoWei** [comment]
I'm interested in contributing - can I take this one? At least I will not break the build :-)

**Comment by bmcfee** [comment]
@ZiyaoWei by all means!  If you're worried about breakage, consult the [contributing guidelines](https://github.com/librosa/librosa/blob/master/CONTRIBUTING.md) to see how to test the code before submitting the PR (though travis will run the tests anyway).
