### ISSUE TITLE
hello，the speech dataset link is expired，could you share a valid link?

### ISSUE THREAD

**Issue by zkl99999** [librosa/librosa#721]
http://pannous.net/files/spoken_numbers_wav.tar
http://pannous.net/files/spoken_numbers_pcm.tar
http://pannous.net/files/spoken_numbers_spectros_64x64.tar

**Comment by bmcfee** [comment]
Please fill out the template when reporting issues.  This helps us keep track of versions and diagnose errors more effectively.

Otherwise, I don't know what speech dataset you're referring to, or where it is linked in librosa.
