### ISSUE TITLE
Tutorials and docs call amplitude_to_db and power_to_db with complex inputs

### ISSUE THREAD

**Issue by lostanlen** [librosa/librosa#723]
#### Description
Since PR #671 (which closed issue #662), the example code for `specshow` uses `librosa.amplitude_to_db` on the output of `stft`, which raises a `UserWarning` in the absence of a `magphase` transformation.
Searching for `amplitude_to_db` reveals other example codes where the same situation happens: `plot_hprss`, `plot_segmentation`, `segment.py` docstring, `constantq.py` docstring.

#### Steps/Code to Reproduce
copy-pasting example from specshow docs
```
import matplotlib.pyplot as plt
y, sr = librosa.load(librosa.util.example_audio_file())
plt.figure(figsize=(12, 8))

D = librosa.amplitude_to_db(librosa.stft(y), ref=np.max)
plt.subplot(4, 2, 1)
librosa.display.specshow(D, y_axis='linear')
plt.colorbar(format='%+2.0f dB')
plt.title('Linear-frequency power spectrogram')

```

#### Expected Results
no warning :)

#### Actual Results
```
~/miniconda3/lib/python3.6/site-packages/librosa/core/spectrum.py:959: UserWarning: amplitude_to_db was called on complex input so phase information will be discarded. To suppress this warning, call amplitude_to_db(magphase(D)[0]) instead.
  warnings.warn('amplitude_to_db was called on complex input so phase '
```

#### Versions
```
Linux-3.10.0-514.10.2.el7.x86_64-x86_64-with-centos-7.3.1611-Core
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
NumPy 1.13.1
SciPy 0.19.1
librosa 0.6.1rc0
```

**Comment by lostanlen** [comment]
I should add that this issue also affects the example codes that use `power_to_db`, for the same reason. I changed the title to reflect this.

Can we put an `0.6.2` milestone to this? I know that this problem does not affect the codebase itself, and that the fix is rather easy, but it's quite embarassing that, in its current state, the `LibROSA demo.ipynb` IPython notebook raises a warning, as well as the docs of `specshow`.

**Comment by bmcfee** [comment]
> Can we put an 0.6.2 milestone to this?

Sure!  0.6.2 will need a very fast turnaround, so it'll have to get done quickly.
