### ISSUE TITLE
get_duration result different for spectrogram 

### ISSUE THREAD

**Issue by nehz** [librosa/librosa#726]
#### Description
In docs:
```
>>> # Load the example audio file
>>> y, sr = librosa.load(librosa.util.example_audio_file())
>>> librosa.get_duration(y=y, sr=sr)
61.44
```
```
>>> # Or compute duration from an STFT matrix
>>> y, sr = librosa.load(librosa.util.example_audio_file())
>>> S = librosa.stft(y)
>>> librosa.get_duration(S=S, sr=sr)
61.44
```

Actual:
```
>>> # Load the example audio file
>>> y, sr = librosa.load(librosa.util.example_audio_file())
>>> librosa.get_duration(y=y, sr=sr)
61.45886621315193
```
```
>>> # Or compute duration from an STFT matrix
>>> y, sr = librosa.load(librosa.util.example_audio_file())
>>> S = librosa.stft(y)
>>> librosa.get_duration(S=S, sr=sr)
61.44
```

#### Versions
Linux-4.13.0-26-generic-x86_64-with-Ubuntu-16.04-xenial
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]
NumPy 1.14.3
SciPy 1.0.1
librosa 0.6.1

**Comment by bmcfee** [comment]
Discrepancy confirmed on my end, I suspect this was just a bad copypasta from my terminal when making the docstring.  Thanks for noting this!

**Comment by nehz** [comment]
Why is the duration slightly shorter for `S` btw ? I would of thought the original signal get padded a little for the last frame, making the reconstructed duration slightly longer.

Also probably good idea to document that if `S` is provided, that the duration is a estimate ?

**Comment by bmcfee** [comment]
> Why is the duration slightly shorter for S btw ? I would of thought the original signal get padded a little for the last frame, making the reconstructed duration slightly longer.

If the `center=` flag is true (default), it assumes that the signal has been padded, and subtracts off the padding.  However, going from audio -> padding -> integer frame count is lossy due to flooring, so it has to be approximate.

> Also probably good idea to document that if S is provided, that the duration is a estimate ?

Yup, I'd definitely support that!
