### ISSUE TITLE
Make smoothing optional in chroma_cens

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#728]
#### Description
`chroma_cens` applies two post-processing steps to chroma features:

1. non-linear amplitude warping by quantization
2. temporal smoothing

Much of the functionality is hard-coded into the implementation right now, but could be exposed to give the user more flexibility.  Specifically, I'm thinking of allowing the user to bypass the smoothing operation (`win_len_smooth=None`), and/or override the default window function (`hann`) by a user-specified descriptor.  Setting `win_len_smooth=1` doesn't exactly work because it gets expanded by 2 before convolution.

This way, you can easily measure the changes due to quantization and smoothing.

(tag @stefan-balke for commentary)

**Comment by stefan-balke** [comment]
Yeah, sure, I'm all for giving more power to the user, although I tend to use CENS as a kind of "standard" feature, e.g., 9/2 CENS is something which we use a lot for retrieval...

**Comment by kyungyunlee** [comment]
I can help with this one!
