### ISSUE TITLE
Signal generators: tone and chirp

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#736]
#### Description
It's often useful to be able to synthesize a pure sine tone, or either a linear or exponential sine sweep.  It's not hard to implement these by hand, but it would be nice to have them as primitives in the library, much like we currently have ``librosa.click``.

For signatures, I'm thinking:

```python
tone(frequency, sr, length=None, duration=None)
```
- The first two are obvious (Hz)
- `length` would be in samples, as in `istft`, `click`, or the effects module.
- `duration` would allow the user to specify the duration in seconds rather than samples, though `length` would take priority.  At least one of `lenth` or `duration` must be provided.

```python
chrip(fmin, fmax, sr, length=None, duration=None, linear=False)
```
- The first 5 are as above
- `linear` is a boolean that toggles between linear and exponential sweep.

**Comment by ZiyaoWei** [comment]
I'm interested in doing this since a) it'll include actual code changes b) I've just finished the book Think DSP which does similar things and c) it seems mostly standalone. I assume "good for beginners" means this issue is up for grabs?

**Comment by stefan-balke** [comment]
Yes, perfect, give it a shot. We are here to support you!
