### ISSUE TITLE
Display settings

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#738]
#### Description

librosa has some sensible default settings for plotting in notebook environments, but maybe different defaults are appropriate for printed material.  Would it make sense to add some kind of static `rcParams` type feature, as in matplotlib or seaborn, which would allow a user to set the style at runtime (or in an rc file)?  Something like

```python
librosa.display.style('paper')
```
would change all the cmap settings to `gray_r`, for instance.

Would this be worth having?  Should we try to piggyback off matplotlib styles?  What else would make sense to configure for different environments?

Anyone have opinions on this?  @justinsalamon maybe?

**Comment by justinsalamon** [comment]
I like the idea of supporting styles mainly because people end up having their own preferences and if one could store said preferences once somewhere and easily invoke them that would be cool.

I'm actually not too moivated by the paper example specifically - journals requiring b/w images are a ghost of the past and most people read papers online (or print them on their own printers), meaning most papers PDFs include color plots nowadays.

**Comment by bmcfee** [comment]
> 'm actually not too moivated by the paper example specifically - journals requiring b/w images are a ghost of the past and most people read papers online (or print them on their own printers), meaning most papers PDFs include color plots nowadays.

Journals, yes, but books still exist and printing costs are real.  Think of `'paper'` as the physical material, not the form.

**Comment by justinsalamon** [comment]
Fair point, though in that case it might be best to be on the nose with the naming, e.g. `bw`. In any case, providing some defaults would be nice, but allowing users to create their own is what I find most attractive.

**Comment by bmcfee** [comment]
> it might be best to be on the nose with the naming, e.g. bw.

I like that idea.  The flip side of it is consistency with existing conventions in matplotlib/seaborn, but we can sort that out.

**Comment by lostanlen** [comment]
Beyond the color maps, one feature that would be really nice to have would be to adjust figure width, font family, and font size to a given publication style. IEEE comes to mind of course (both with column-wide and text-wide variants).

**Comment by bmcfee** [comment]
This really seems like the job of a matplotlib style, and out of scope for librosa.

**Comment by lostanlen** [comment]
I just found out about `SciencePlots`, whose development began in August 2018 (shortly after this issue was opened) and has now reached a mature state.


Here is the result:
```
import librosa
import librosa.display
from matplotlib import pyplot as plt
import numpy as np
plt.style.use(['science', 'nature'])

y, sr = librosa.load(librosa.ex('trumpet'))
D = librosa.stft(y)  # STFT of y
S_db = librosa.amplitude_to_db(np.abs(D), ref=np.max)
fig, ax = plt.subplots(figsize=(8, 4))
img = librosa.display.specshow(S_db, x_axis='time', y_axis='linear', ax=ax)
ax.set(title='Now with labeled axes!')
fig.colorbar(img, ax=ax, format="%+2.f dB")
```

![Uploading Screenshot 2022-05-24 at 08.42.53.png…]()

And with `["science", "ieee"]`:
<img width="463" alt="Screenshot 2022-05-24 at 08 43 01" src="https://user-images.githubusercontent.com/3943142/169976016-861d61a1-8418-4dcb-90af-265b4d4e2ea2.png">

**Comment by bmcfee** [comment]
> It remains to be seen if/how we might adjust the spectrogram colormap accordingly.

This one's subtle if we want to retain the (very useful, IMO) functionality of selecting colormaps based on the type of data being displayed through the `librosa.display.cmap` function.  The three (at present) options are set by the default kwargs for sequential, diverging, and binary data respectively.  I don't see an easy`*` way to make this stateful / configurable outside of a rewrite of this function.  The question then becomes: how would we make it interact with other styling packages?  (This is really the only styling that is governed by librosa, everything else inherits from the matplotlib context.)

If we want to be purists about this, we should punt all styling out of librosa and into matplotlib / seaborn / scienceplots / some other package where contextual style is in scope.  This would generally be my preferred solution, except that I do really like having the ability to automatically select an appropriate colormap.


## Disabling auto-cmaps?

One way we could reconcile this is to expand the `specshow` API a bit.  At present, we allow an explicit `cmap=` to pass through, and if none is provided, we use the helper function to infer an appropriate default.  This of course would override any choices set by the matplotlib context.  (A good thing in general, but a bad thing if the user is trying to style figures explicitly through a context manager.)

We could add a bit of logic here to force *not* setting a cmap, eg by saying:

```python
librosa.display.specshow(..., cmap=None)
```
which would then fall back to whatever the matplotlib context says to use without having to explicitly copy the cmap name when calling speccshow.  This seems relatively painless to me.

The caveat here is that we'll need to be a little careful in how the API is defined.  To ensure automatic colormapping (current behavior), we would need to omit `cmap` from the kwargs.  (I thought about having `cmap='auto'` be an option, but since colormaps can be identified by strings, this could conflict if someone has a colormap named "auto".)

The current logic:
https://github.com/librosa/librosa/blob/7ac022a8496126e95b46a7d56ad880a328359bda/librosa/display.py#L853
would then be expanded to something like:

```python
if 'cmap' in kwargs and kwargs['cmap'] is None:
    # Remove cmap from the pcolormesh kwargs
    kwargs.pop('cmap')
else:
    # No cmap is specified, so guess one from the data properties
    kwargs.setdefault("cmap", cmap(data))

...

out = axes.pcolormesh(x_coords, y_coords, data, **kwargs)
```

Of course, if we go this route, it means that we can't have style-dependent choices for sequential/diverging/binary colormaps since they'll be configured outside of librosa.  However, I kind of figure that anyone going to the trouble to use a matplotlib style would be okay with setting an explicit cmap anyway if the default is not suitable for their purposes.

Thoughts?

---

`*` One easy way to do this would be to use the presets package to rewrite default kwargs.  But I don't think anyone actually uses presets. :cry:
