### ISSUE TITLE
Fourier tempogram, PLP beat tracking

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#739]
#### Description

(Related to #44, but different)

The current `tempogram` uses windowed autocorrelation to determine periodicity, but it can also be done in the frequency domain by applying STFT to the onset envelope. The [PLP beat tracker](https://ieeexplore.ieee.org/abstract/document/5654580/) uses the phase from the resulting analysis to do local tempo estimation and pulse alignment.

It would be a nice complement to have in the `feature.rhythm` module, though it could raise some issues around naming and interpretation of the axis scales, e.g., in `tempo_frequencies` or `specshow(y_axis='tempo')`.

Otherwise, the call signature would look much the same as -- identical to? -- the existing auto-correlation tempogram.

**Comment by bmcfee** [comment]
Looking into this, I noticed that our implementation of autocorrelation tempograms uses the autocorrelation of the windowed signal, ie, `(w * x) xcorr (w * x)`.  This is slightly different from [Grosche, Mueller and Kurth](http://domino.mpi-inf.mpg.de/intranet/ag4/ag4publ.nsf/93832a04987390a3c12567530068622d/94779f9f00f541a7c12577540055b43d/$FILE/2010_GroscheMuellerKurth_TempogramCyclic_ICASSP.pdf) (eq 6), where the windowing is applied only once.  Equivalently, `(w * x) xcorr x` or the above with a sqrted window.

This doesn't make a huge qualitative difference, but it would be nice to fix this in 0.7 for consistency with the literature.  A couple of thoughts on how to do this:

- Change the behavior to always sqrt.  If a user wants to maintain the previous behavior, they can construct a custom window with squared values and pass it in as `window=...`.
- Add a flag (true by default) which controls whether the window is square-rooted or not.  This changes the default behavior going forward, but makes it easy to recover the old behavior for backwards compatibility.
- Over-engineer things to provide a family of "square-root windows" that are automatically constructed by our `filters.get_window`.  For example, `filters.get_window('hann_sqrt', 2048)` could detect the `_sqrt` suffix, construct a 2048-point hann window, and then square-root the window before returning it to the user.  In tempogram, we'd then be able to just change the default window from `hann` to `hann_sqrt` to get GMK2010 behavior, and revert to `window='hann'` to get librosa 0.6 behavior.

sqrt windows pop up in other places as well (e.g., Ron Weiss's cqt implementation used sqrt-hann by default), so it's not totally out of left field to want to make this behavior easy.

Anyone have thoughts?  @stefan-balke @lostanlen ?  I'll admit to leaning toward the over-engineered solution because it's A) not that complex, B) makes the behavior easy to revert, and C) does not inflate the parameter count.

**Comment by bmcfee** [comment]
I spent some time hacking on this today.  Some comments:

- The PLP algorithm can be simplified (practically, anyway) a bit as follows:
  - 1. compute onset env
  - 2. compute STFT of oenv with hop=1 and an appropriate window length (3 sec in the original, but it doesn't matter).  This gives the fourier tempogram `F`.
  - 3. Find the peak bin in `F` restricted to a given "frequency" (tempo) range (eg 30-300 bpm)
  - 4. Suppress all non-peaks in `F`, call it `F^`
  - 5. `plp = istft(F^)_+`
- The above saves us from having to do too much bpm conversion math, and handles overlap-add in the right way using existing functions.
- It seems to work pretty well.  It doesn't consistently improve over the existing beat tracker, but there are some cases where it seems to help.

We could treat `plp` as a post-processing of `oenv` and feed it into the DP tracker, or just take the peaks immediately as beat estimates.  If using the dp tracker, it seems reasonable to drop the `tightness` parameter substantially since local consistency is already baked into the input signal; but this can just be a recommendation in the docs.

One weak point of the above (and in the original paper) is that it depends on a single peak at each frame to estimate the local tempo.  We can strengthen this a bit by throwing viterbi decoding onto the local tempo peak estimator to enforce continuity, but that can also be an endless rabbit hole.

At this point, I have a reasonably simple prototype notebook, but it's not obvious how to put this into a coherent API with the existing library.  One option is to add `beat.plp`, which takes an onset envelope and produces a PLP, without exposing any fourier tempogram implementation.  This would be relatively simple (API wise), as it prevents us from having to extend the existing tempo interfaces (display, frequencies, etc) to support frequency-based axis.

**Comment by bmcfee** [comment]
Took some time to think about this one a bit more.  In light of #872, I could see `plp` being a nice alternative to the DP beat tracker when working on streams, since it only requires local inference.  Given that, I don't think it makes a whole lot of sense to try to shoe-horn in Viterbi decoding / sequential modeling to the instantaneous tempo estimation.  I'm happy to keep it close to the original method, and peak-pick the max frequency within a range.

To summarize the above thread, I propose the following API:

- `feature.rhythm.fourier_tempogram`, like the existing `tempogram` but returns the (complex) fourier tempogram.  Interface would approximately follow `tempogram` except where `autocorrelate` differs from `stft`.
- `beat.plp`: can operate on `(y, sr)`, `S`, or `onset_envelope` (as in the beat tracker).  Computes the fourier tempogram and reconstructs the PLP curve using the frame-wise max decoding.  If at some point, we want to add viterbi decoding, this would be the place to do so.
    - docstring examples would include one for estimating beat positions: one using localmax of the plp curve, and one using the DP tracker.

Does this sound like a reasonable plan?

**Comment by lostanlen** [comment]
closed by #894
