### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#740]
#### Description

In discussing with folks at the [CCRMA MIR workshop](https://ccrma.stanford.edu/workshops/mir-2018), it seems like there's a legitimate need for an easy way to access data for development / debugging purposes.  I don't think it makes sense to ship more than one or two tracks in the main librosa package itself, but I'm open to the idea of having some kind of dataset module akin to those found in sklearn, nltk, etc.

I suspect most people will agree that this would be useful in the abstract, but there's a lot of details to sort out before such a thing could be reasonably implemented.  A few points to kick off the discussion:

1. Should this even be a librosa function?  e.g., `librosa.data.install('gtzan')`?  Or should it live in an entirely different project (`librosa_data`)?
1. Where should data be hosted?  I could imagine things getting rather large.  Would figshare be reasonable?
1. Where should datasets be indexed?  Internally to librosa, or should it have a remote index hosted on the web so that we can add new datasets out of cycle with librosa releases?
1. What format should data be stored in?  I'm thinking ogg or flac for audio.  What about annotations?  I'd obviously lean toward jams, but there are some floating issues around collection management that I think should be sorted out before we go down that road.  This also adds considerable (but, I believe in the long-run, reasonable) complexity overhead to getting directly at the raw data (via jams objects).
1. How are collections accessed once installed?  Unlike standard UCI machine learning datasets, MIR data does not have a nice, fixed-dimensional tabular form in general, so we can't just have a pair of X/Y arrays.  This issue might resolve itself if we go ahead with jams after implementing some collection-management utilities, but it's worth considering in advance.

(tag @justinsalamon @stefan-balke @jongwook)

**Comment by justinsalamon** [comment]
Some off-the-cuff thoughts:

> 1. Should this even be a librosa function? e.g., librosa.data.install('gtzan')? Or should it live in an entirely different project (librosa_data)?

If the goal is convenience (which I think it is), I'd include it in librosa directly, much like `keras.datasets`and `sklearn.datasets` (consistency yay).

> 3. Where should datasets be indexed? Internally to librosa, or should it have a remote index hosted on the web so that we can add new datasets out of cycle with librosa releases?

The goal is to provide *some* data so people can prototype against, right? Not to actually provide complete datasets for people to do research on? Assuming it's the former, I don't think there's a strong need to be able to add datasets off-cycle.

> 5. How are collections accessed once installed? Unlike standard UCI machine learning datasets, MIR data does not have a nice, fixed-dimensional tabular form in general, so we can't just have a pair of X/Y arrays. This issue might resolve itself if we go ahead with jams after implementing some collection-management utilities, but it's worth considering in advance.

A pair of audio/jams arrays?

**Comment by meinardmueller** [comment]
Rather than having audio-based datasets within librosa, it would be nice to have at least some feature respresentations for well-known datasets within the context of certain applications. For example, for a chord labeling applications, it would be nice to have chroma-based features for the Beatles dataset (along with frame-based annotations that match the feature representation), which can then be used to illustrate how chord labeling may work on a medium-sized dataset. 'gtzan' with some standard spectral features along with some genre classification application would be another example ... These datasets then serve more for illustration purposes (rather than for eactual research) ...

**Comment by stefan-balke** [comment]
I think this is great for beginners but certainly (useless) overhead for advanced users.

My main question is: What is the gain of having this compared to Jupyter Notebooks we already have or compared to the examples in the documentation? If `librosa` was meant to be a self-contained package for education I would directly say "do it"...but in my opinion we should keep this separate and use notebooks instead...

**Comment by jongwook** [comment]
Just to throw in another hosting option, a detached Github branch would work for <100MB files: https://github.com/marl/crepe/tree/models

**Comment by bmcfee** [comment]
> What is the gain of having this compared to Jupyter Notebooks we already have or compared to the examples in the documentation?

Quick-starting newbies for educational purposes.  Getting datasets into a usable shape for even a simple experiment (eg, genre recognition on fma-8k) is still much more work than can be reasonably accomplished by a newbie.  SKlearn and NLTK solved this nicely by providing data downloaders and importers to quickly get content into the environment and skip over the tedious parts.

**Comment by justinsalamon** [comment]
quick thought: providing pre-computed features would allow learners to jump straight into model building (whether via manual engineering or using ML), but isn't that already covered by e.g. sklearn? If the goal is to help newcomers learn the ropes of `librosa`, then surely you'd primarily wish to provide the raw audio for a dataset (or sample of), so that people can practice feature extraction. Right?

**Comment by bmcfee** [comment]
> If the goal is to help newcomers learn the ropes of librosa, then surely you'd primarily wish to provide the raw audio for a dataset (or sample of), so that people can practice feature extraction. Right?

Yes.  I think I'd go a step further and say that any data we package should have full rights to the underlying audio content.  This might limit the sources of data we can provide, but will be more useful in the long run.

**Comment by stefan-balke** [comment]
Well, if someone is willing to program and host this...I think it will add a lot of overhead to the library. IMHO, a generalized and separate "Jams + Data + Pumpp ?" framework could be better suited...

**Comment by bmcfee** [comment]
Possibly relevant: http://www.leouieda.com/blog/introducing-pooch.html

**Comment by justinsalamon** [comment]
>Possibly relevant: http://www.leouieda.com/blog/introducing-pooch.html

`GOODBOY.fetch("gravity-data.csv")` 🤣

**Comment by keunwoochoi** [comment]
> I think it will add a lot of overhead to the library

Agreed, I think if it's really necessary we can do it in a different project - for probably not too many datasets but only a few of them, some super-popular ones.

**Comment by lostanlen** [comment]
update: @magdalenafuentes, @rabitt and colleagues have started the `mirdata` project. There is no official release yet, but it seems mature enough already to be considered a solid candidate for us to close this issue, and defer to her for our data-intensive debugging/development/demonstration/education/reproducibility purposes.

https://github.com/mir-dataset-loaders/mirdata

note that `mirdata` has virtually zero dependencies, if we leave aside those needed for compatibility (`six`, `future`) and testing (`pytest`, `testcontainers`). It's distributed in PyPI and the source code has a BSD-3 license. So although i don't see the need to make `mirdata` a dependency of `librosa`, i would be totally in favor of extensively using `mirdata` in our demos and tutorials for how to use `librosa` beyond a single audio track (good old Kevin MacLeod ...)

**Comment by bmcfee** [comment]
> i would be totally in favor of extensively using `mirdata` in our demos and tutorials for how to use `librosa` beyond a single audio track (good old Kevin MacLeod ...)

I like that idea.  I think it makes sense to build out those tutorials independently of the librosa documentation, for two reasons:

1. Keep our main documentation build dependencies "light"
2. Allow faster iteration on tutorial development

Which is to say, I don't think we need to lock this into a milestone on the main repo.  What do you think?

**Comment by lostanlen** [comment]
> Which is to say, I don't think we need to lock this into a milestone on the main repo. What do you think?

That's a fair point. Now that we've decided that this issue belongs outside of the librosa codebase, then no milestone is necessary. I originally did put it as 0.7.1 to mean "not required for 0.7.0". But it can happen anytime, really.

I suggest we close this issue once mirdata makes its first stable release.

**Comment by bmcfee** [comment]
> I suggest we close this issue once mirdata makes its first stable release.

:+1:

**Comment by lostanlen** [comment]
closed by https://github.com/mir-dataset-loaders/mirdata/pull/150
many thanks to @rabitt, @drubinstein, @magdalenafuentes, @andreasjansson, @keunwoochoi, and everyone who contributed dataset loaders.
