### ISSUE TITLE
Getting errors just getting started from Librosa Tutorial even if everything is updated.

### ISSUE THREAD

**Issue by AnthonyTheKoala** [librosa/librosa#743]
I am just learning librosa going through the first tutorial.
When I do the following commands:
<pre>
from __future__ import print_function
import librosa
filename= librosa.util.example_audio_file()
y,sr = librosa.load(filename)
</pre>

As soon as I invoke librosa.load(filename) I get:

<pre>
Traceback (most recent call last):
  File "<pyshell#112>", line 1, in <module>
    y,sr = librosa.load(filename)
  File "C:\Python36\lib\site-packages\librosa\core\audio.py", line 112, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "C:\Python36\lib\site-packages\audioread\__init__.py", line 93, in audio_open
    if _gst_available():
  File "C:\Python36\lib\site-packages\audioread\__init__.py", line 37, in _gst_available
    import gi
  File "C:\Python36\lib\site-packages\gi\__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(url)?
</pre>

I tried 
<pre>
pip install audioread --upgrade     #As seen in another posting
</pre>
To no avail.

What is the cause of the error?
Python: v3.6.5
Bits: 64 bit
OS: MS Win 7, 64 bit

Thank you,
Anthony of Sydney

**Comment by bmcfee** [comment]
That's very weird.  It's a resurgence of a known issue due to a package namespace collision.  If you `pip uninstall gi` it should work, or at least, not crash on load.

**Comment by AnthonyTheKoala** [comment]
Unfortunately, de-pipping gi did not work.
Replicating the commands:
<pre>
from __future__ import print_function  
import librosa  
filename = librosa.util.example_audio_file()
y, sr = librosa.load(filename)
</PRE>
Then I get
<pre>	  
Traceback (most recent call last):
  File "<pyshell#122>", line 1, in <module>
    y,sr = librosa.load(filename)
  File "C:\Python36\lib\site-packages\librosa\core\audio.py", line 112, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "C:\Python36\lib\site-packages\audioread\__init__.py", line 116, in audio_open
    raise NoBackendError()
audioread.NoBackendError
 </pre> 
With reference to another posting which said that audioread.NoBackendError() due to ffmpeg, I checked that ffmpeg was in my windows path, it was in my windows path. So ffmpeg was available to python.

Any other idea?

Thank you,
Anthony from Sydney NSW

**Comment by bmcfee** [comment]
Looks like you're now running into [this issue](https://github.com/beetbox/audioread/issues/54) ?

**Comment by AnthonyTheKoala** [comment]
Problem has been 'cured'. 
In sum, when setting the correct the path for ffmpeg, **ensure that the Idle window or python console is NOT RUNNING!** The same goes for installing other packages and uninstalling <pre> pip uninstall gi </pre>. That is make sure the python console or the Idle programs are not running. Yes sometimes installing packages can be done with python console or Idle. In this situation it is not case.

So a summary of installation of librosa to be operable is:
<pre>
pip install audioread --upgrade 
pip install librosa 
# if there are any errors during the librosa installation, there may be some additional packages 
#which may need to be installed.  Just do:    pip install _missing package(s) listed in traceback_
</pre>
ffmpeg: Make sure that the paths in your Win machine are included.
Here is an example from my experience on installing environment variables and path.
For your Win 7 (say), 
i. Start Button,
ii. Move your mouse to "Computer", right click and select "Properties"
iii, Click on left side "Advanced System Settings"
iv. Click environment variables.

The following is not a program, but rather the environment variables and path.  When setting environment variables, you have to fill in separate boxes. Click "new" for setting environment variables but for PATH, click and append PATH.
<pre>
ffmpeg         c:/ffmpeg               #new var, note the slash is / NOT \ in case packages only recognize /
ffmpeg_bin   %ffmpeg%/bin       #new var, note the slash is / NOT \ in case packages only recognize /
PATH            %ffmpeg_bin%; _c:/whatever; c:/whatever2/bin_    #ffmpeg is append to the front.
</pre>

Result: When I entered the code listed in the first page of the librosa tutorial, there were no runtime errors!  An interesting observation is the temporary appearance of the ffmpeg console window.

Looking forward to use the rest of the package.

Regards
Anthony of Sydney NSW
