### ISSUE TITLE
ImportError: cannot import name cache in python2.7

### ISSUE THREAD

**Issue by anitair** [librosa/librosa#744]
Importing librosa in python2.7 runs into this error:

import librosa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/librosa/__init__.py", line 11, in <module>
    from . import cache
ImportError: cannot import name cache

It's been suggested elsewhere to install the package using conda /Anaconda or clone and install the repository to solve this issue, but in my particular working conditions I need to install it via pip.

Checking the source code, I've managed to make it work by modifying line 49 in cache.py from:
if self.cachedir is not None and self.level >= level:
to
if self.location is not None and self.level >= level:

Does this make any sense?

Thanks!

**Comment by bmcfee** [comment]
The cachedir/location issue #729 has already been fixed #730, and will be included in the 0.6.2 release.  The discussion in #729 and #732 describes how to work around the problem.

**Comment by msaadsadiq** [comment]
This is still a problem and not solved with 0.6.2
