### ISSUE TITLE
python 3.7 osx (scikit-learn breaking)

### ISSUE THREAD

**Issue by caseybasichis** [librosa/librosa#746]
librosa is not installing through pip3.  Seems to be an issue with scikit-learn

Is there a workaround?  Can I build without scikit?

  1 warning and 15 errors generated.
  error: Command "clang++ -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/lib/python3.7/site-packages/numpy/core/include -I/usr/local/lib/python3.7/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c sklearn/cluster/_dbscan_inner.cpp -o build/temp.macosx-10.11-x86_64-3.7/sklearn/cluster/_dbscan_inner.o -MMD -MF build/temp.macosx-10.11-x86_64-3.7/sklearn/cluster/_dbscan_inner.o.d" failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for scikit-learn
  Running setup.py clean for scikit-learn
  Running setup.py bdist_wheel for numba ... error

**Comment by bmcfee** [comment]
As this appears to be an issue with `sklearn` and not librosa, I'm marking as `upstream/wontfix`.

That said, you can bypass dependencies with `pip install --no-deps`, but many things will not work.  I'd advise waiting a few days for everyone to catch up to the 3.7 release.

Relatedly, we just pushed up noarch builds on conda-forge, so 3.7 support will come for free there once all of our dependencies are up to date.

**Comment by bmcfee** [comment]
It looks like sklearn and numba have wheels for py3.7 now.   @caseybasichis can you check if this is still an issue?

**Comment by bmcfee** [comment]
Since we have CI on py3.7 now, I think this is sufficiently resolved.
