### ISSUE TITLE
Marginal difference between dot(Mel(htk=True, norm=True), D and enorm*dot(Mel(htk=true, norm=False), D)

### ISSUE THREAD

**Issue by rafaelvalle** [librosa/librosa#748]
#### Description
This probably is just a byproduct of numerical precision after the dot product. 
Reporting for sanity checking.

#### Steps/Code to Reproduce

```
import numpy as np
import librosa

# load audio and power spectrogram
y, sr = librosa.load(librosa.util.example_audio_file())
y = y[:sr*2]
D = np.abs(librosa.stft(y))**2

# define params
htk = True
fmin = 0.0
fmax = 8000
n_mels = 80
nfft = 2048

# Build mel filters with and without normalization.
mel_fil_nonorm = mel(sr, nfft, nmels, fmin, fmax, htk=htk, norm=None)
mel_fil_norm = mel(sr, nfft, nmels, fmin, fmax, htk=htk, norm=1)

#  Build energy normalization vector
mel_f = mel_frequencies(n_mels + 2, fmin=fmin, fmax=fmax, htk=htk)
enorm = 2.0 / (mel_f[2:n_mels+2] - mel_f[:n_mels])        

# Project spectrogram to mel-basis
melspec_nonorm = np.dot(mel_fil_nonorm, D)
melspec_norm = np.dot(mel_fil_norm, D)

# Scale mel-spectrogram with energy normalization
melspec_postnorm = melspec_nonorm * enorm[:, None]

# Compute sum of differences between norm and postnorm
residual = np.sum(melspec_norm - melspec_postnorm)
```

#### Expected Results
residual = 0

#### Actual Results
residual = -1.2919472544229937e-13

#### Versions
Darwin-17.6.0-x86_64-i386-64bit
Python 3.6.3 (default, Oct  4 2017, 06:09:38) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
NumPy 1.14.0
SciPy 1.0.0
librosa 0.5.1

**Comment by bmcfee** [comment]
Yeah, I think this is almost certainly a numerical precision issue, but thanks for noting it.

I'd prefer to leave this as is, but note that #18, if we ever get around to it, might change the behavior as the normalization code would have to be rewritten.

**Comment by rafaelvalle** [comment]
Sounds good! Closing.

**Comment by lostanlen** [comment]
For future reference, I should point out that the residual should be `np.norm`, not `np.sum`.

**Comment by rafaelvalle** [comment]
Yes! Thanks for pointing out! I'm glad the terms didn't cancel our in the sum!
