### ISSUE TITLE
Conflict in number of frames for the given signal in Librosa

### ISSUE THREAD

**Issue by shubhadeepti** [librosa/librosa#752]
The following code extracts the time/fequencydomain features for the given signal

mfccs = (librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=20).T)
print("np.shape(mfcc)", np.shape(mfccs))
chroma = (librosa.feature.chroma_stft(S=stft, sr=sample_rate).T)
print("np.shape(chroma)", np.shape(chroma))
mel = (librosa.feature.melspectrogram(X, sr=sample_rate).T)
print("np.shape(mel)", np.shape(mel))

 Above code prints 

('np.shape(mfcc)', (33, 20))
('np.shape(chroma)', (33, 12))
('np.shape(mel)', (33, 128))

It means the given signal we are getting 33 frames (default frame length-2048 and hop length-512).

But when we call directly  util.frame method for the same signal ,its giving the 29 frames.

frames = (librosa.util.frame(X).T)
print("****frames.size****", np.shape(frames))

Above code prints 
('****frames.size****', (29, 2048))

Can some one help us to understand Why the frame length is differing for librosa.feature.**(signal) and librosa.util.frame(signal).

Thanks in advance.

**Comment by stefan-balke** [comment]
Hey,

yes, if you go to this line:
https://github.com/librosa/librosa/blob/master/librosa/core/spectrum.py#L154

You will see that `stft()` is calling `pad_center()` which adds zeros at the beginning and the end such that the considered windows are centered around the frame's time position. This will result in more frames consequentely...

**Comment by BeniaminK** [comment]
Well, actually, additional frames are added in this line:
https://github.com/librosa/librosa/blob/18083a73acd6a351b98da6a2830ff9a589d05f98/librosa/core/spectrum.py#L163

you cannot change the "center" parameter during feature extraction, because all the kwargs from the mfcc call are passed to `melspectrogram` function and dissapear (are unwinded) in the _spectogram call. I think this is an issue, that should be corrected...

**Comment by stefan-balke** [comment]
> Well, actually, additional frames are added in this line

Yup, that's true. Thanks for the correction!

**Comment by bmcfee** [comment]
> I think this is an issue, that should be corrected...

In general, the feature extractors allow you some limited control over the construction of the underlying stft to cover the most common things one would want to change.  If you need more control than that, this is why we also allow you to provide a pre-computed STFT.  It's a tricky thing to balance flexibility and usability here, and I'd prefer to keep the API as it currently is on this point.  I'm open to adding documentation / examples that will make this more clear to users though.

**Comment by bmcfee** [comment]
This was resolved by #834.
