### ISSUE TITLE
librosa 0.6.1 install fails during set-up of llvmlite 0.24.0

### ISSUE THREAD

**Issue by mweber-ovt** [librosa/librosa#757]
#### Description

sudo pip install librosa fails while setting up llvmlite.

I realize this is not a librosa issue per se, but the librosa install REQUIRES llvmlite > 0.24.0, and there apparently is no easy way to install that version of llvmlite except for first building llvm from source which is difficult and I have not been successful yet.

Does librosa really require llvmlite 0.24.0 or would 0.15.0 work which installs without problems?

#### Steps/Code to Reproduce

It should be possible to reproduce this on any system that doesn't yet have llvmlite installed.
The error is the same as when installing llvmlite stand-alone:
sudo pip install llvmlite

#### Versions

Raspberry Pi
Newest version of Stretch
Python 3.5.3

**Comment by bmcfee** [comment]
Thanks for noting this -- I'm sorry that the dependency chain isn't universally up to date across all the platforms that we'd like.

Librosa itself does not directly require an llvmlite version, this dependency is inherited through numba.  The numba version requirement is currently 0.38, and as I recall, is the minimum version that supports certain functions that we use in the accelerations for event matching.  So I don't think this dependency can be directly lowered.

That said, if you can get numba installed and running, then librosa should work happily.  You might have to install with --no-deps to do so, but it ought to work.

**Comment by mweber-ovt** [comment]
I was able to install librosa on my Raspberry Pi 3B+ only after building llvm from source.  With llvm 6.0.1 present, llvmlite 0.24.0 will install.  It was quite an ordeal to get llvm build.  The instructions here are helpful but require some tweaking:
https://releases.llvm.org/6.0.1/docs/CMake.html#frequently-used-cmake-variables

Building llvm for a Raspberry Pi 3 required a few modifications to the base system:
1.) 64GB SD card - else the build runs out of disk space
2.) 2GB swap file - else the linker runs out of memory

Assuming the llvm sources have been downloaded and extracted into this directory:
~/Downloads/llvm-6.0.1.src

Create a build directory, e.g.
`$ mkdir llvm_build_dir`
`$ cd llvm_build_dir`

Use the following command from inside the build directory to configure the llvm build (I am not sure the `sudo` is necessary but didn't have the patience to try without):

`sudo cmake ~/Downloads/llvm-6.0.1.src -DLLVM_TARGETS_TO_BUILD="ARM" -DCMAKE_BUILD_TYPE="Release"`

Use the following build command to build and link using all four CPUs:
`$ sudo cmake --build .  -- -j4`
This will take several hours.

The build should go through but if the linker runs out of memory, refer to this website:
https://stackoverflow.com/questions/25197570/llvm-clang-compile-error-with-memory-exhausted
The following worked for me:
`sudo ln -s `which gold` /usr/local/bin/ld` 

After build completes, install with
`sudo cmake --build . --target install`

Now llvmlite 0.24.0 will install without error:
`pip3 install llvmlite`

Now librosa 0.61 will install without error:
`pip3 install librosa`

However, this is still not quite enough: when trying to import librosa, it still throws and error, namely 

> ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

The error is fixed with:
`sudo apt-get install libatlas-base-dev`


It should be possible at this stage to remove the llvm source and build directory to free up many GB on the SD card, but I haven't tested that yet.

Hopefully sharing this will be useful for other people.  Maybe in the future somebody comes up with an easier way to install llvmlite that doesn't require building llvm first, but for the time being this works.

**Comment by mweber-ovt** [comment]
Or maybe the llvmlite people fix their installation:
http://llvmlite.pydata.org/en/latest/admin-guide/install.html
pip install llvmlite doesn't work, at least not on Raspian.

**Comment by stuartarchibald** [comment]
This is similar to the effort gone through by the Numba engineers when working on armv7l, so well done for getting something that works :) You may be interested to know that the Numba channel on https://anaconda.org now ships `llvmlite` for armv7l (it's built on an RPi with berryconda). Numba itself is also very close to being able to ship as a conda package.
```
$ CONDA_SUBDIR=linux-armv7l conda search -c numba llvmlite
Loading channels: done
# Name                  Version           Build  Channel             
llvmlite              0.7.0.dev         py34_21  numba               
llvmlite              0.26.0rc1          py27_0  numba               
llvmlite              0.26.0rc1          py35_0  numba               
llvmlite              0.26.0rc1          py36_0  numba               
llvmlite                 0.26.0          py27_0  numba               
llvmlite                 0.26.0          py35_0  numba               
llvmlite                 0.26.0          py36_0  numba  
```
Further, the next release of Numba will be based on LLVM 7 and as always it's recommended that the `llvmlite` installation guide is followed as there are important patches to LLVM that should be applied as per: http://llvmlite.pydata.org/en/latest/admin-guide/install.html#compiling-llvm

**Comment by stuartarchibald** [comment]
Numba 0.42 is [now supported on RPi with berryconda](https://groups.google.com/a/continuum.io/d/msg/numba-users/mXpks0pAjg8/PmTVdRa6CQAJ).

**Comment by mweber-ovt** [comment]
I don’t think I saw a segmentation error but I got another error.  Here is the procedure I used to install librosa on a Raspberry Pi.

Install librosa:

Prerequisite - Build LLVM:
https://releases.llvm.org/6.0.0/docs/CMake.html#frequently-used-cmake-variables
http://releases.llvm.org/download.html#6.0.1
See also
https://github.com/librosa/librosa/issues/757#issuecomment-411277975

Use the following command to configure build (from inside build directory)

sudo cmake ~/Downloads/llvm-6.0.1.src -DLLVM_TARGETS_TO_BUILD="ARM" -DCMAKE_BUILD_TYPE="Release"

Use the following build command, to build with all four CPUs:sudo
$ sudo cmake --build .  -- -j4

Must use linker gold in order to avoid running out of memory.
https://stackoverflow.com/questions/25197570/llvm-clang-compile-error-with-memory-exhausted

Two ways to involve gold:
1.) cmake option -DLLVM_USE_LINKER=gold.
2.) sudo ln -s `which gold` /usr/local/bin/ld

After build completes, install with

sudo cmake --build . --target install

Now llvmlite 0.24.0 will install without error:
pip3 install llvmlite

Now librosa 0.61 will install without error:
pip3 install librosa
However, when trying to import librosa, it still throws and error, namely
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory
Googling this error indicated this would fix it:
sudo apt-get install libatlas-base-dev
And it did; apparently, this installs the missing library.python3

After that, no errors when testing:
pi@raspberrypi:~ $ python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170124] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import librosa
>>>

On Jan 22, 2019, at 8:48 AM, Corgi <notifications@github.com<mailto:notifications@github.com>> wrote:


I already complied LLVM7.0 and install librosa(0.6.1).
But when I import librosa in python3
Having error
Segmentation fault.
I don't know how to do.
@mweber-ovt<https://github.com/mweber-ovt>

**Comment by lostanlen** [comment]
@mweber-ovt thank you so much for describing the sequence of steps that you used to install librosa on a Raspberry Pi. Do you think it would be worth to make a special section of the installation instructions about this?

**Comment by mweber-ovt** [comment]
@lostanlen yeah but I don't know how to create a special section.  Also, building llvm is really tedious...there's got to be some alternative way?

**Comment by stuartarchibald** [comment]
If you use [berryconda](https://github.com/jjhelmus/berryconda) you can simply:
```
$ conda install numba
```
and it will just work. The LLVM 7 build needed for llvmlite and Numba to work correctly also requires source level patching as described here https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#compiling-llvm.

CC: @seibert @sklam

**Comment by seibert** [comment]
We (the Numba team) have been getting some feedback that ARMv7 wheels of llvmlite (the hardest part of the build) would be useful.  Are there thoughts on where the best venue for us to post them?  Can ARM wheels go to PyPI?  Do we need to get them posted to [Piwheels](https://www.piwheels.hostedpi.com/)?  Something else?

**Comment by mweber-ovt** [comment]
I think PyPI would be preferred

On Jan 23, 2019, at 8:10 AM, Stan Seibert <notifications@github.com<mailto:notifications@github.com>> wrote:


We (the Numba team) have been getting some feedback that ARMv7 wheels of llvmlite (the hardest part of the build) would be useful. Are there thoughts on where the best venue for us to post them? Can ARM wheels go to PyPI? Do we need to get them posted to Piwheels<https://www.piwheels.hostedpi.com/>? Something else?

**Comment by civilman628** [comment]
pip3 install llvmlite
Collecting llvmlite
  Using cached https://files.pythonhosted.org/packages/d3/59/8f0c20cd6197b3e535b6eb6513b2f1264c77fd343347e520dd4eab425962/llvmlite-0.27.0.tar.gz
Building wheels for collected packages: llvmlite
  Building wheel for llvmlite (setup.py) ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-5vg8eg3c/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-_et3co3g --python-tag cp35:
  running bdist_wheel
  /usr/bin/python3 /tmp/pip-install-5vg8eg3c/llvmlite/ffi/build.py
  LLVM version... 3.8.0
  
  Traceback (most recent call last):
    File "/tmp/pip-install-5vg8eg3c/llvmlite/ffi/build.py", line 167, in <module>
      main()
    File "/tmp/pip-install-5vg8eg3c/llvmlite/ffi/build.py", line 157, in main
      main_posix('linux', '.so')
    File "/tmp/pip-install-5vg8eg3c/llvmlite/ffi/build.py", line 119, in main_posix
      raise RuntimeError(msg)
  RuntimeError: Building llvmlite requires LLVM 7.0.x. Be sure to set LLVM_CONFIG to the right executable path.
  Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.
  
  error: command '/usr/bin/python3' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite
  Running setup.py install for llvmlite ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-5vg8eg3c/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-zpup5plk/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    got version from file /tmp/pip-install-5vg8eg3c/llvmlite/llvmlite/_version.py {'full': '894a1ddab60091869424f697cc56ecfee8156e31', 'version': '0.27.0'}
    running build_ext
    /usr/bin/python3 /tmp/pip-install-5vg8eg3c/llvmlite/ffi/build.py
    LLVM version... 3.8.0
    
    Traceback (most recent call last):
      File "/tmp/pip-install-5vg8eg3c/llvmlite/ffi/build.py", line 167, in <module>
        main()
      File "/tmp/pip-install-5vg8eg3c/llvmlite/ffi/build.py", line 157, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-5vg8eg3c/llvmlite/ffi/build.py", line 119, in main_posix
        raise RuntimeError(msg)
    RuntimeError: Building llvmlite requires LLVM 7.0.x. Be sure to set LLVM_CONFIG to the right executable path.
    Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.
    
    error: command '/usr/bin/python3' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-5vg8eg3c/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-zpup5plk/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-5vg8eg3c/llvmlite/

**Comment by kim-sunghoon** [comment]
Thanks mweber-ovt,
I installed librosa 0.6.1 with llvmlite 7.0.1 

However, the following error occurs when import librosa, like Unable to find target for this triple (no targets are registered).
How can I solve it?

Thank you. 
env : ubuntu 18.04, python3.6, ARM, nvidia jetson nano board 
---------------------------------------------------------------------------------------------
log
---------------------------------------------------------------------------------------------
shkim at csdl-nano1 in ~ $
→ pip3 install librosa==0.6.1
Collecting librosa==0.6.1
Collecting numpy>=1.8.0 (from librosa==0.6.1)
Collecting scipy>=0.14.0 (from librosa==0.6.1)
Collecting decorator>=3.0.0 (from librosa==0.6.1)
  Using cached https://files.pythonhosted.org/packages/5f/88/0075e461560a1e750a0dcbf77f1d9de775028c37a19a346a6c565a257399/decorator-4.4.0-py2.py3-none-any.whl
Collecting resampy>=0.2.0 (from librosa==0.6.1)
Collecting numba>=0.38.0 (from librosa==0.6.1)
Collecting joblib>=0.7.0 (from librosa==0.6.1)
  Using cached https://files.pythonhosted.org/packages/cd/c1/50a758e8247561e58cb87305b1e90b171b8c767b15b12a1734001f41d356/joblib-0.13.2-py2.py3-none-any.whl
Collecting scikit-learn!=0.19.0,>=0.14.0 (from librosa==0.6.1)
Collecting six>=1.3 (from librosa==0.6.1)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting audioread>=2.0.0 (from librosa==0.6.1)
Collecting llvmlite>=0.28.0dev0 (from numba>=0.38.0->librosa==0.6.1)
Installing collected packages: numpy, scipy, decorator, llvmlite, numba, six, resampy, joblib, scikit-learn, audioread, librosa
Successfully installed audioread-2.1.7 decorator-4.4.0 joblib-0.13.2 librosa-0.6.1 llvmlite-0.28.0 numba-0.43.1 numpy-1.16.3 resampy-0.2.1 scikit-learn-0.21.1 scipy-1.3.0 six-1.12.0

shkim at csdl-nano1 in ~ $
→ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import librosa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shkim/.local/lib/python3.6/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/home/shkim/.local/lib/python3.6/site-packages/librosa/core/__init__.py", line 104, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/home/shkim/.local/lib/python3.6/site-packages/librosa/core/time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "/home/shkim/.local/lib/python3.6/site-packages/librosa/util/__init__.py", line 69, in <module>
    from .matching import *  # pylint: disable=wildcard-import
  File "/home/shkim/.local/lib/python3.6/site-packages/librosa/util/matching.py", line 16, in <module>
    @numba.jit(nopython=True)
  File "/home/shkim/.local/lib/python3.6/site-packages/numba/decorators.py", line 174, in wrapper
    **dispatcher_args)
  File "/home/shkim/.local/lib/python3.6/site-packages/numba/dispatcher.py", line 541, in __init__
    self.targetctx = self.targetdescr.target_context
  File "/home/shkim/.local/lib/python3.6/site-packages/numba/targets/registry.py", line 50, in target_context
    return self._toplevel_target_context
  File "/home/shkim/.local/lib/python3.6/site-packages/numba/utils.py", line 357, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/shkim/.local/lib/python3.6/site-packages/numba/targets/registry.py", line 34, in _toplevel_target_context
    return cpu.CPUContext(self.typing_context)
  File "/home/shkim/.local/lib/python3.6/site-packages/numba/targets/base.py", line 250, in __init__
    self.init()
  File "/home/shkim/.local/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/shkim/.local/lib/python3.6/site-packages/numba/targets/cpu.py", line 47, in init
    self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
  File "/home/shkim/.local/lib/python3.6/site-packages/numba/targets/codegen.py", line 608, in __init__
    self._init(self._llvm_module)
  File "/home/shkim/.local/lib/python3.6/site-packages/numba/targets/codegen.py", line 613, in _init
    target = ll.Target.from_triple(ll.get_process_triple())
  File "/home/shkim/.local/lib/python3.6/site-packages/llvmlite/binding/targets.py", line 195, in from_triple
    raise RuntimeError(str(outerr))
RuntimeError: Unable to find target for this triple (no targets are registered)

**Comment by mweber-ovt** [comment]
@kim-sunghoon , sorry I don't know what this error means.  Below are the steps I use to get librosa to work.  Note that there are additional steps after installing llvm (i.e. install llvmlite), and after installing librosa.  Good luck and let me know if this works for you!

Use the following command to configure build (from inside build directory)
sudo cmake llvm-7.0.1.src -DLLVM_TARGETS_TO_BUILD="ARM" -DCMAKE_BUILD_TYPE=“Release"

Use the following build command, to build with two CPUs:
sudo cmake --build .  -- -j2
This will take several hours.  With j4 my system keeps hitting the swap file and becomes unresponsive.

After build completes, install with
sudo cmake --build . --target install

Now llvmlite 0.24.0 will install without error:
pip3 install llvmlite==0.24.0

Now librosa 0.61 will install without error:
pip3 install librosa==0.6.1
However, when trying to import librosa, it still throws an error, namely 
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory
Googling this error indicated this would fix it:
sudo apt-get install libatlas-base-dev
And it did; apparently, this installs the missing library.python3
Then there is another message from Numba about a package called colorama.  The following fixes that:
pip3 install colorama

After that, no errors when testing:
pi@raspberrypi:~ $ python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170124] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import librosa
>>>

**Comment by kim-sunghoon** [comment]
@mweber-ovt, thank you for instruction.
however, same runtime error occurs like below 

--- log ---
after sudo cmake --build . -- -j2 & sudo cmake --build . --target install 

pip3 install llvmlite==0.24.0
Collecting llvmlite==0.24.0
  Cache entry deserialization failed, entry ignored
Installing collected packages: llvmlite
Successfully installed llvmlite-0.24.0

shkim at csdl-nano1 in ~/Downloads/llvm7.0_build_dir $
→ pip3 install librosa==0.6.1
Collecting librosa==0.6.1
  Cache entry deserialization failed, entry ignored
Collecting six>=1.3 (from librosa==0.6.1)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting resampy>=0.2.0 (from librosa==0.6.1)
  Cache entry deserialization failed, entry ignored
Collecting decorator>=3.0.0 (from librosa==0.6.1)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/5f/88/0075e461560a1e750a0dcbf77f1d9de775028c37a19a346a6c565a257399/decorator-4.4.0-py2.py3-none-any.whl
Collecting numba>=0.38.0 (from librosa==0.6.1)
  Cache entry deserialization failed, entry ignored
Collecting joblib>=0.7.0 (from librosa==0.6.1)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/cd/c1/50a758e8247561e58cb87305b1e90b171b8c767b15b12a1734001f41d356/joblib-0.13.2-py2.py3-none-any.whl
Collecting scikit-learn!=0.19.0,>=0.14.0 (from librosa==0.6.1)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/57/5c/133b464c8d0be7ac8c9414b6ff2ae848808a35ce03b146fc2c43777e51f9/scikit-learn-0.21.2.tar.gz (12.2MB)
    100% |████████████████████████████████| 12.2MB 41kB/s 
Collecting numpy>=1.8.0 (from librosa==0.6.1)
Collecting audioread>=2.0.0 (from librosa==0.6.1)
  Cache entry deserialization failed, entry ignored
Collecting scipy>=0.14.0 (from librosa==0.6.1)
Collecting llvmlite>=0.28.0dev0 (from numba>=0.38.0->librosa==0.6.1)
Building wheels for collected packages: scikit-learn
  Running setup.py bdist_wheel for scikit-learn ... done
  Stored in directory: /home/shkim/.cache/pip/wheels/58/f0/f6/27e0c1fb17f342b9aeef7b2592f1e7ed96fd2536f71a90bb16
Successfully built scikit-learn
Installing collected packages: six, numpy, scipy, llvmlite, numba, resampy, decorator, joblib, scikit-learn, audioread, librosa
Successfully installed audioread-2.1.7 decorator-4.4.0 joblib-0.13.2 librosa-0.6.1 llvmlite-0.28.0 numba-0.43.1 numpy-1.16.3 resampy-0.2.1 scikit-learn-0.21.2 scipy-1.3.0 six-1.12.0

shkim at csdl-nano1 in ~/Downloads/llvm7.0_build_dir $
→ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import librosa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shkim/.local/lib/python3.6/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/home/shkim/.local/lib/python3.6/site-packages/librosa/core/__init__.py", line 104, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/home/shkim/.local/lib/python3.6/site-packages/librosa/core/time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "/home/shkim/.local/lib/python3.6/site-packages/librosa/util/__init__.py", line 69, in <module>
    from .matching import *  # pylint: disable=wildcard-import
  File "/home/shkim/.local/lib/python3.6/site-packages/librosa/util/matching.py", line 16, in <module>
    @numba.jit(nopython=True)
  File "/home/shkim/.local/lib/python3.6/site-packages/numba/decorators.py", line 174, in wrapper
    **dispatcher_args)
  File "/home/shkim/.local/lib/python3.6/site-packages/numba/dispatcher.py", line 541, in __init__
    self.targetctx = self.targetdescr.target_context
  File "/home/shkim/.local/lib/python3.6/site-packages/numba/targets/registry.py", line 50, in target_context
    return self._toplevel_target_context
  File "/home/shkim/.local/lib/python3.6/site-packages/numba/utils.py", line 357, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/shkim/.local/lib/python3.6/site-packages/numba/targets/registry.py", line 34, in _toplevel_target_context
    return cpu.CPUContext(self.typing_context)
  File "/home/shkim/.local/lib/python3.6/site-packages/numba/targets/base.py", line 250, in __init__
    self.init()
  File "/home/shkim/.local/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/shkim/.local/lib/python3.6/site-packages/numba/targets/cpu.py", line 47, in init
    self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
  File "/home/shkim/.local/lib/python3.6/site-packages/numba/targets/codegen.py", line 608, in __init__
    self._init(self._llvm_module)
  File "/home/shkim/.local/lib/python3.6/site-packages/numba/targets/codegen.py", line 613, in _init
    target = ll.Target.from_triple(ll.get_process_triple())
  File "/home/shkim/.local/lib/python3.6/site-packages/llvmlite/binding/targets.py", line 195, in from_triple
    raise RuntimeError(str(outerr))
RuntimeError: Unable to find target for this triple (no targets are registered)

**Comment by mweber-ovt** [comment]
@kim-sunghoon , everything seems to install properly yet you get this error.  I cannot reproduce it since I am on a Raspberry and everything works, as described.  The only idea I have is that something went wrong in the llvm build:
sudo cmake llvm-7.0.1.src -DLLVM_TARGETS_TO_BUILD="ARM" -DCMAKE_BUILD_TYPE=“Release"
Double-check you have the right target specified.
I don't think this is a librosa issue.  You might want to post your question on a llvm-related forum.

**Comment by bmcfee** [comment]
Any objection to closing this out?

**Comment by mweber-ovt** [comment]
You can close it,

even though I don’t think there is a satisfactory solution - it is still necessary to go through the pain of build llvm to get llvmlite - but that’s not a librosa issue.

Michael

On Jul 5, 2019, at 16:01, Brian McFee <notifications@github.com<mailto:notifications@github.com>> wrote:


Any objection to closing this out?

**Comment by bmcfee** [comment]
Ok, thanks!

**Comment by sundar19** [comment]
@mweber-ovt  sir, If it is not wrong , I am sorry if this sounds bad for you. Can you please share the OS image file with librosa? As in the current situation I cant purchase 64GB SD card 
Thanks!

**Comment by mikechen66** [comment]
Solution to librosa installation: 

You can install LLVM 7 from the Ubuntu apt repo, you do need to build it from source. The simple method is listed as follows.  

$ sudo apt-get install llvm-7 llvm-7-dev
$ export LLVM_CONFIG=/usr/bin/llvm-config-7
$ pip install librosa 

It is much more elegant and straightforward.

Cheers,

Mike

**Comment by sundar19** [comment]
@mikechen66 Sir, I get these errors
pi@raspberrypi:~ $ sudo apt-get install llvm-7 llvm-7-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package llvm-7
E: Unable to locate package llvm-7-dev

**Comment by dpwe** [comment]
I’ve never used berryconda, but it sounds like they have a working numba
for r-pi. See this post:

https://github.com/numba/numba/issues/3670

  DAn.

**Comment by Path-A** [comment]
Berryconda is currently not being maintained, unfortunately. My workaround is installing numba 0.38 and Librosa 0.7.0 . I cannot get the newer Librosa versions after that.
