### ISSUE TITLE
BibTeX entry on Zenodo has some non-standard author names

### ISSUE THREAD

**Issue by lostanlen** [librosa/librosa#758]
#### Description
I'm citing librosa 0.6.1 in a paper today and use the BibTeX file automatically generated by Zenodo. Frustratingly, it is not a "plug and play" experience: some authors do not follow a "Firstname (Middlename) Lastname" template. I would prefer if they did.
After talking with @bmcfee, he told me that:
`Seth` is `Seth Kranzler`
`Erik` is `Erik Peterson`
`JackieWu` is `Jackie Wu`

Other manual change that were necessary were for authors with non-ASCII characters in their name:
`Carl Thomé`, `Fabian-Robert Stöter`, `João Felipe Santos`.

I imagine that this is largely an `upstream` issue to Zenodo, and possibly a `wontfix`, but is there any way we can hack into our database of past contributors and make the relevant changes before it gets scraped by Zenodo?

Even if this is not the case, the issue is worth raising, if only because it gives me an opportunity to share the expected BibTeX entry, with manual fixes applied (see below), for everyone to use.

#### Steps/Code to Reproduce
Link: https://zenodo.org/record/1252297

#### Expected Results
```
@misc{brian_mcfee_2018_1252297,
  author       = {Brian McFee and
                  Matt McVicar and
                  Stefan Balke and
                  Carl Thom\'{e} and
                  Colin Raffel and
                  Dana Lee and
                  Oriol Nieto and
                  Eric Battenberg and
                  Dan Ellis and
                  Ryuichi Yamamoto and
                  Josh Moore and
                  Rachel Bittner and
                  Keunwoo Choi and
                  Pius Friesch and
                  Fabian-Robert St\"{o}ter and
                  Vincent Lostanlen and
                  Siddhartha Kumar and
                  Simon Waloschek and
                  Seth Kranzler and
                  Rimvydas Naktinis and
                  Douglas Repetto and
                  Curtis ``Fjord'' Hawthorne and
                  CJ Carr and
                  Waldir Pimenta and
                  Petr Viktorin and
                  Paul Brossier and
                  Jo\~{a}o Felipe Santos and
                  Jackie Wu and
                  Erik Peterson and
                  Adrian Holovaty},
  title        = {librosa/librosa: 0.6.1},
  month        = may,
  year         = 2018,
  doi          = {10.5281/zenodo.1252297},
  url          = {https://doi.org/10.5281/zenodo.1252297}
}
```

#### Actual Results
```
misc{brian_mcfee_2018_1252297,
  author       = {Brian McFee and
                  Matt McVicar and
                  Stefan Balke and
                  Carl Thomé and
                  Colin Raffel and
                  Dana Lee and
                  Oriol Nieto and
                  Eric Battenberg and
                  Dan Ellis and
                  Ryuichi Yamamoto and
                  Josh Moore and
                  Rachel Bittner and
                  Keunwoo Choi and
                  Pius Friesch and
                  Fabian-Robert Stöter and
                  Vincent Lostanlen and
                  Siddhartha Kumar and
                  Simon Waloschek and
                  Seth and
                  Rimvydas Naktinis and
                  Douglas Repetto and
                  Curtis "Fjord" Hawthorne and
                  CJ Carr and
                  Waldir Pimenta and
                  Petr Viktorin and
                  Paul Brossier and
                  João Felipe Santos and
                  JackieWu and
                  Erik and
                  Adrian Holovaty},
  title        = {librosa/librosa: 0.6.1},
  month        = may,
  year         = 2018,
  doi          = {10.5281/zenodo.1252297},
  url          = {https://doi.org/10.5281/zenodo.1252297}
}
```

#### Versions
librosa v0.6.1

**Comment by bmcfee** [comment]
> I imagine that this is largely an upstream issue to Zenodo, and possibly a wontfix, but is there any way we can hack into our database of past contributors and make the relevant changes before it gets scraped by Zenodo?

That's a good question.  I suspect there's not much we can do, since Zenodo scrapes this info directly from the contributors' github profiles, but I'll ask around.

**Comment by lostanlen** [comment]
Somewhat related: in the last commit of v0.6.2, @bmcfee updated the list of authors in `AUTHORS.md`

https://github.com/librosa/librosa/commit/a4c98ca35a9eb34a2c4bda2ca6bfb2b0f75b8be4

This list is ASCII, and therefore
"Carl Thomé" has become "Carl Thome"
while
"Fabian Robert-Stöter" has become "Fabian Robert-Stoeter".

Tagging @nehz: Hi! could you please share your full name publicly so that we can acknowledge your contribution to librosa (PR #727) in the list of authors?

**Comment by nehz** [comment]
@lostanlen  Sure, it is "Zhen Wang"

**Comment by lostanlen** [comment]
@nehz Thanks. We put your full name in `AUTHORS.md` after this commit: https://github.com/librosa/librosa/commit/9e59626ee8907739ec6cd4cab53d1d7697c837d4
