### ISSUE TITLE
librosa.cqt error reporting error

### ISSUE THREAD

**Issue by MRrollingJerry** [librosa/librosa#759]
Following the instructions (hop_length must be a positive integer multiple of 2^8 for 9-octave CQT), I set the hop_length as 2**9, 512. However, the script still reports the same error. Is it possible there is another error, but that is misrecognized?

**Comment by bmcfee** [comment]
Thanks for reporting this.

Please fill out the issue template and provide a minimal code example to reproduce the error.

**Comment by lostanlen** [comment]
Haven't heard from the OP in ten months. Closing.
