### ISSUE TITLE
Outdated `write_wav` code example in advanced I/O docs

### ISSUE THREAD

**Issue by ZHANGGU** [librosa/librosa#761]
#### Description

Can not write a 16b wav
#### Steps/Code to Reproduce
import numpy as np
import librosa

rate = 44100
audio = np.random.uniform(-1, 1, size = (rate * 10, 2))

maxv = np.iinfo(np.int16).max
librosa.output.write_wav(
    "out_int16.wav", (audio * maxv).astype(np.int16), rate
)

#### Expected Results

A wav file will be written as 16b wav

#### Actual Results
![2018-08-21_07-20-38](https://user-images.githubusercontent.com/8365180/44382012-76268e00-a513-11e8-81c8-e738b6cc42c9.png)

#### Versions
Windows-10-10.0.10586-SP0
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)]
NumPy 1.13.1
SciPy 1.1.0
librosa 0.6.1

**Comment by lostanlen** [comment]
Hello, I can't reproduce the problem. See screenshot attached
What exactly are you pointing at in your "actual results"?
Could this be Windows-specific?


<img width="259" alt="screen shot 2018-08-21 at 2 01 16 am" src="https://user-images.githubusercontent.com/3943142/44383261-241b4380-a4e6-11e8-86a2-8c1ba764288d.png">

**Comment by bmcfee** [comment]
@ZHANGGU The documentation for [write_wav](https://librosa.github.io/librosa/generated/librosa.output.write_wav.html#librosa.output.write_wav) does state that only floating point inputs are supported, so I think this behaving according to spec.

If you want to directly write 16bit wav from quantized samples, I suggest using scipy.io or soundfile, rather than librosa's wav writer.

**Comment by ZHANGGU** [comment]
@bmcfee Plz update the documentation especially example. Following your suggestion, it will not write 16b wave as integer is not supported. Of course, I shifted to another package. Bye wavio.

**Comment by lostanlen** [comment]
@ZHANGGU thank you for clarifying. There is indeed an issue of outdated documentation here:
https://github.com/librosa/librosa/blob/223c6b1842470451d1c68479d638d6442f7facf0/docs/ioformats.rst#L111
