### ISSUE TITLE
hz_to_midi returns negatives

### ISSUE THREAD

**Issue by Magurosenbei** [librosa/librosa#763]
#### Description
I am not that familiar with all the mathematics behind all these signals formulation but I would like to convert a given audio time series or audio buffer into midi

I am encountering this problem of having negative values and large numbers beyond 0-127 as the result and thus unable to create a physical midi file to listen to test or my procedures are just plainly wrong in the first place?

Would be great if anybody would be able to explain these as well:
1. Handling of overlapping frames for midi, could setting hop_length=fft_length as my parameters be a solution?
2. Suppose I manage to get my array of midi notes, how do I go about obtaining the duration to play the specific note? How much time is represented between the indices of the returned midi note array?

#### Steps/Code to Reproduce
```
import librosa
import numpy as np

signal, sampleRate = librosa.load(path="sound.wav", sr=None, mono=True, dtype=np.float32)
melspec = librosa.feature.melspectrogram(y=signal, sr=sampleRate, n_fft=1024, hop_length=1024, n_mels=128)
freq = librosa.mel_to_hz(melspec)
midi = librosa.hz_to_midi(freq)
print(midi)
```

#### Expected Results
[[int]] with elements' values between 0 to 127

#### Actual Results
```
[[-287 -130 -105 ... -118 -134 -117]
 [-292 -144 -110 ... -117 -131 -110]
 [-301 -144 -127 ... -111 -122  -98]
 ...
 [-329 -327 -332 ... -334 -322 -272]
 [-328 -330 -333 ... -325 -348 -271]
 [-332 -340 -323 ... -325 -332 -273]]
```

**Comment by bmcfee** [comment]
I think this stems from a misunderstanding of what these functions do.

`mel_to_hz` converts mel bin *indices* to their corresponding frequencies.  It does not operate on the values contained in a mel spectrogram array.

**Comment by Magurosenbei** [comment]
@bmcfee Do you have any suggestion on how I should be approaching this problem? 
Essentially I am trying to analyze the accuracy of a vocal recording with a musical score (midi) in terms of pitch and tone etc.
