### ISSUE TITLE
AttributeError: 'librosa' has no module 'icqt'

### ISSUE THREAD

**Issue by songeater** [librosa/librosa#764]

**Comment by songeater** [comment]
sorry posted before finished typing (on cell because github is behind firewall at work).

I can use cqt etc when running librosa but icqt does not work and gives a module not found error.  I have tried importing librosa, librosa.core, librisa.core.constantq etc - no avail.  Again other functions from constantq.py work fine.

**Comment by bmcfee** [comment]
Please fill in the fields of the issue template --- especially software versions --- so that we can diagnose the problem.

**Comment by songeater** [comment]
Hi - really sorry, but the whole error has changed as i try to replicate.  Earlier it was an inability to find icqt(), now it seems to have an error with numba.  I am using the latest version of librosa (used pip to upgrade to latest versions and dependencies).
Thank You!

[1m
File "..\..\..\..\AppData\Roaming\Python\Python35\site-packages\librosa\core\constantq.py", line 857:[0m
[1mdef __activation_fill(x, basis, activation, hop_length):  # pragma: no cover
    <source elided>
        sample = i * hop_length
[1m        x[sample:min(n, sample + n_fft)] += activation[i] * basis[:max(0, min(n_fft, n - sample))]
[0m        [1m^[0m[0m

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

**Comment by bmcfee** [comment]
> I realize this may not have been the best way to describe the error but i apologize.

That's okay, but please follow the instructions in the issue template so that we know exactly what versions we're dealing with.
