### ISSUE TITLE
wrong time labels for recurrence matrix

### ISSUE THREAD

**Issue by ShunyaWatanabe** [librosa/librosa#781]
#### Description

When hop_length is specified for the features (such as rmse and chroma) that are used in the recurrence matrix, the time labels for both x- and y-axis become different when (I think) they should remain the same.

#### Steps/Code to Reproduce

```
from __future__ import print_function
import librosa
import librosa.display
import matplotlib.pyplot as plt

filename = "./songs/WaitingForLove.mp3"
y, sr = librosa.load(filename, sr=22050)

rmse = librosa.feature.rmse(y=y, frame_length=2048*8, hop_length=512*4)
R = librosa.segment.recurrence_matrix(rmse)

plt.figure(figsize=(8, 8))
librosa.display.specshow(R, x_axis='time', y_axis='time')
plt.title('Similarity Matrix')
plt.show()
```

#### Expected Results

with hop_length=512, python kept on crashing, so I don't have a photo of the graph, but the original time length is 3:50.

#### Actual Results

The photo below is a result for hop_length=512x2
It shows 1:45 on the right most label.
[https://ibb.co/cLVevA](url)

The photo below is a result for hop_length=512x4
It shows 54 on the right most label.
[https://ibb.co/eEvCFA](url)

#### Versions

Darwin-18.2.0-x86_64-i386-64bit
Python 2.7.10 (default, Aug 17 2018, 17:41:52) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
NumPy 1.15.1
SciPy 1.1.0
librosa 0.6.2

**Comment by bmcfee** [comment]
To get the correct axis labels, you need to provide the timing parameters (frame length, hop length) to `specshow` so that it knows how to interpret the dimensions of its input.  If you call `librosa.display.specshow(R, x_axis='time', y_axis='time', hop_length=512*4)` it should provide the correct result.

**Comment by ShunyaWatanabe** [comment]
I see. Thanks!
