### ISSUE TITLE
Add feature fluctogram

### ISSUE THREAD

**Issue by shayenne** [librosa/librosa#782]
There is interest in the implementation of the fluctogram in the librosa?

I have seen some articles [1] using this feature to perform Singing Voice Detection, and I was wondering if it is useful for other tasks in MIR. 

This feature uses two reliability indicators: Spectral Contraction and Spectral Flatness. 

Since the Spectral Flatness is already implemented in the library, we could check if it fits the one proposed in the article. Then, we could add the Spectral Contraction feature.

What do you recommend?

[1] Lehner, Bernhard, Gerhard Widmer, and Reinhard Sonnleitner. "On the reduction of false positives in singing voice detection." Acoustics, Speech and Signal Processing (ICASSP), 2014 IEEE International Conference on. IEEE, 2014.

**Comment by bmcfee** [comment]
Yeah, that sounds like a useful feature to add.  Would you be interested in taking the lead on a first cut at implementation?

**Comment by shayenne** [comment]
Yes! Some colleagues here in my research group are interested in contributing too.

**Comment by stefan-balke** [comment]
That sounds good!

Here is a starting point for you!

https://gist.github.com/stefan-balke/6c6a78e59a084ebbbca4bb0b22eb0235

![screen shot 2018-11-13 at 14 31 58](https://user-images.githubusercontent.com/7326732/48416676-22fa5b00-e751-11e8-9b08-9973eede4bdd.png)

**Comment by stefan-balke** [comment]
I think the gist corresponds to the ICASSP 14 implementation, but I'm not sure...

Coming up with unit-tests will be the hardest part I guess...

**Comment by lostanlen** [comment]
@shayenne thank you for taking the lead on this. You are right that it is a good idea to implement contraction first, and then fluctogram by means of a function that calls both flatness and contraction

**Comment by kyungyunlee** [comment]
@shayenne I have contacted the author of the paper above while working on my ISMIR paper this year, and he kindly sent the link of his matlab code to us and the ismir mailing list.
The link he gave us for code is [(here)](https://www.dropbox.com/s/nqv388coriklely/svd2018.7z?dl=0), where the main file is `extractICASSP2014ForRNNfeatures.m` with the functions inside directories. I used it to extract features as well. 
So if you need a reference, I think you can compare your implementation with this matlab code to see if things are working correctly :)

**Comment by shayenne** [comment]
> @shayenne I have contacted the author of the paper above while working on my ISMIR paper this year, and he kindly sent the link of his matlab code to us and the ismir mailing list.
> The link he gave us for code is [(here)](https://www.dropbox.com/s/nqv388coriklely/svd2018.7z?dl=0), where the main file is `extractICASSP2014ForRNNfeatures.m` with the functions inside directories. I used it to extract features as well.
> So if you need a reference, I think you can compare your implementation with this matlab code to see if things are working correctly :)

@kyungyunlee We started our implementations and we found that the spectral contraction implemented in the matlab code is different from the described in the article. We want to implement exactly as described in the article. What do you think we should do?

**Comment by kyungyunlee** [comment]
@shayenne Oh, could you specify which part is different? You are referring to the code in `extractSpecNormSpecDispFeatures.m` ?

**Comment by shayenne** [comment]
@kyungyunlee Yes, do you know why it makes the convolution with the Chebychev with the spectrum before square the spectrum?

**Comment by kyungyunlee** [comment]
@shayenne In the paper they mention that they convolve with the chebychev window, which functions as the "weighting" window. From my understanding, convolving with the chebychev window (especially with high attenuation - means narrow window) will mean that the spectral center will be given more weight and the frequencies near the two ends will be given very small weight. Thus overall, if the energy is concentrated in the center, the spectral  contraction value will be larger. 
I am not 100% sure my interpretation is correct, but I didn't think that the implementation was different from the paper. 
Let me know if there's something I am missing :)

**Comment by stefan-balke** [comment]
Again, sorry for just dropping code here but maybe this helps.

```Python

def bandwise_contraction(X_log, freq_ax_log, f_start=164, f_end=10548, n_bands=17, bandwith=240, bands_offset=30):
        # get indices for frequency range E3 (164 Hz) to E9 (10548 Hz)
        f_start_idx = np.argmin(np.abs(freq_ax_log - f_start))
        f_end_idx = np.argmin(np.abs(freq_ax_log - f_end))
        X_log = X_log[f_start_idx:f_end_idx+1, :]

        bw_contraction = np.zeros((n_bands, X_log.shape[1]))

        # extract the subbands
        for cur_band_idx in np.arange(n_bands):
            cur_band_start = cur_band_idx * bands_offset
            cur_band_end = cur_band_start + bandwith

            # assign the subbands
            cur_band = X_log[cur_band_start:cur_band_end, :].copy()

            # Call standard spectral contraction for each band
            bw_contraction[cur_band_idx, :] = spectral_contraction(cur_band)

        return bw_contraction


def spectral_contraction(X_mag):
    """Spectral Contraction measure.

       As suggested in _[1].

    Parameters
    ----------
    X_mag : ndarray
        Magnitude spectrum of a time frame.

    Returns
    -------
    spectral_contraction :

    References
    ----------
    .. [1] Bernhard Lehner, Gerhard Widmer, Reinhard Sonnleitner
           "ON THE REDUCTION OF FALSE POSITIVES IN SINGING VOICE DETECTION",
           ICASSP 2014

    """
    window = chebwin(X_mag.shape[0], 200)
    if X_mag.ndim > 1:
        window = np.tile(window, (X_mag.shape[1], 1)).T

    spectral_contraction = np.sum(X_mag * window, axis=0) / (np.sum(X_mag, axis=0) + np.finfo(float).eps)

    return spectral_contraction


def bandwise_flatness(X_log, freq_ax_log, f_start=164, f_end=10548, n_bands=17, bandwith=240, bands_offset=30):
        f_start_idx = np.argmin(np.abs(freq_ax_log - f_start))
        f_end_idx = np.argmin(np.abs(freq_ax_log - f_end))
        X_log = X_log[f_start_idx:f_end_idx+1, :]

        bw_flatness = np.zeros((n_bands, X_log.shape[1]))

        # extract the subbands
        for cur_band_idx in np.arange(n_bands):
            cur_band_start = cur_band_idx * bands_offset
            cur_band_end = cur_band_start + bandwith

            # assign the subbands
            cur_band = X_log[cur_band_start:cur_band_end, :].copy()

            # Call standard spectral flatness for each band
            bw_flatness[cur_band_idx, :] = spectral_flatness(cur_band)

        return bw_flatness


def spectral_flatness(X_mag):
    """Spectral Flatness measure.

    We use the log-spec version e use the log-spec version as suggested by _[1].

    Parameters
    ----------
    X_mag : ndarray
        Magnitude spectrum of a time frame.

    Returns
    -------
    spectral_flatness :

    References
    ----------
    .. [1] Alexander Lerch, "Audio Content Analysis"

    """
    # geometric mean
    spectral_flatness = np.exp(np.mean(np.log(X_mag + np.finfo(float).eps), axis=0))

    # divided by arithmetic mean
    spectral_flatness /= np.mean(X_mag, axis=0) + np.finfo(float).eps

    return spectral_flatness
```

**Comment by bernhardlehner** [comment]
> There is interest in the implementation of the fluctogram in the librosa?
> 
> I have seen some articles [1] using this feature to perform Singing Voice Detection, and I was wondering if it is useful for other tasks in MIR.
> 
> This feature uses two reliability indicators: Spectral Contraction and Spectral Flatness.
> 
> Since the Spectral Flatness is already implemented in the library, we could check if it fits the one proposed in the article. Then, we could add the Spectral Contraction feature.
> 
> What do you recommend?
> 
> [1] Lehner, Bernhard, Gerhard Widmer, and Reinhard Sonnleitner. "On the reduction of false positives in singing voice detection." Acoustics, Speech and Signal Processing (ICASSP), 2014 IEEE International Conference on. IEEE, 2014.

Hi, this is the author of the paper/implementation.
It's nice to see that people are interested in my work.
Let me clarify a few things first:
- the latest iteration of the Fluctogram is described in the TASLP paper "Online, Loudness-invariant Vocal Detection in Mixed Music Signals"
- always stick to the reference implementation in Matlab if you want to get the same performance. Due to limited space in the papers, we were not always able to describe it exactly.
- I also tried it for speech detection and even speech/singing discrimination, and it worked quite well
- the chebyshev window was selected in this configuration, since it puts a relatively high weight near the center. A triangle window would be too sensitive to fluctuations (e.g. vibrato). There might be an even better suited window function, but I never found the time to revisit this again.

best,
Bernhard

**Comment by bernhardlehner** [comment]
> @shayenne In the paper they mention that they convolve with the chebychev window, which functions as the "weighting" window. From my understanding, convolving with the chebychev window (especially with high attenuation - means narrow window) will mean that the spectral center will be given more weight and the frequencies near the two ends will be given very small weight. Thus overall, if the energy is concentrated in the center, the spectral contraction value will be larger.
> I am not 100% sure my interpretation is correct, but I didn't think that the implementation was different from the paper.
> Let me know if there's something I am missing :)

You are right. It is not only about how narrow the window is, but also about the shape of it in the vicinity of the center.

best,
Bernhard

**Comment by bernhardlehner** [comment]
> @shayenne I have contacted the author of the paper above while working on my ISMIR paper this year, and he kindly sent the link of his matlab code to us and the ismir mailing list.
> The link he gave us for code is [(here)](https://www.dropbox.com/s/nqv388coriklely/svd2018.7z?dl=0), where the main file is `extractICASSP2014ForRNNfeatures.m` with the functions inside directories. I used it to extract features as well.
> So if you need a reference, I think you can compare your implementation with this matlab code to see if things are working correctly :)

As far as I remember, there is another file with 2018 in the name, and this is the version that uses the reliability indicators to post-process the fluctogram (remove some false positive fluctuations). Plus, the frequency range is different, but it works as well as the previous version while still being lower in dimensionality.

There should be reference features from a jamendo song for both versions included.
Please check if your implementation output matches those values.

best,
Bernhard

**Comment by shayenne** [comment]
@kyungyunlee Thank doubt was related with the power to square in the chebychev window, but now we understand that it was an optimization choice.

**Comment by shayenne** [comment]
@stefan-balke Thank you for the code! It helps a lot! :)

We would like to understand what need to be passed in this parameter:  **freq_ax_log**
> ```python
> def bandwise_contraction(X_log, freq_ax_log, f_start=164, f_end=10548, n_bands=17, bandwith=240, bands_offset=30):
>         # get indices for frequency range E3 (164 Hz) to E9 (10548 Hz)
>         f_start_idx = np.argmin(np.abs(freq_ax_log - f_start))
>         f_end_idx = np.argmin(np.abs(freq_ax_log - f_end))
>         X_log = X_log[f_start_idx:f_end_idx+1, :]
> 
> ```

We will use this code as reference and to correspond the IEEE 2018 article by @bernhardlehner .

**Comment by shayenne** [comment]
Thank you for your answers @bernhardlehner!

We find a code with 2017 in the name, do you think is this the one?

**Comment by bernhardlehner** [comment]
> Thank you for your answers @bernhardlehner!
> 
> We find a code with 2017 in the name, do you think is this the one?

Yes, that should be it. The 2014 version extracts Fluctogram, SC, and SF (from the same 17 bands each), as well as MFCCs and their deltas (30 each). All in all, a 111-dim vector.

The 2017 version extracts 11 Fluctogram values and 18 MFCC deltas, all in all a 29-dim vector.

best,
Bernhard

**Comment by stefan-balke** [comment]
> @stefan-balke Thank you for the code! It helps a lot! :)
> 
> We would like to understand what need to be passed in this parameter: **freq_ax_log**
> 
> > ```python
> > def bandwise_contraction(X_log, freq_ax_log, f_start=164, f_end=10548, n_bands=17, bandwith=240, bands_offset=30):
> >         # get indices for frequency range E3 (164 Hz) to E9 (10548 Hz)
> >         f_start_idx = np.argmin(np.abs(freq_ax_log - f_start))
> >         f_end_idx = np.argmin(np.abs(freq_ax_log - f_end))
> >         X_log = X_log[f_start_idx:f_end_idx+1, :]
> > ```
> 
> We will use this code as reference and to correspond the IEEE 2018 article by @bernhardlehner .

It's the frequency values in Hz which correspond to your spectral bins in `X_log`.
It is used to get the needed start and end indices for the loop since the set of frequencies provided my be larger than the ones we actually need.

**Comment by stefan-balke** [comment]
Any chances that you open a PR so that we can discuss and help?

**Comment by bernhardlehner** [comment]
Can we puch this to after my defense?

best,
Bernhard



>>> Stefan Balke <notifications@github.com> 12/07/18 1:48 PM >>>
Any chances that you open a PR so that we can discuss and help?

**Comment by stefan-balke** [comment]
Sure, this was more a question to @shayenne and colleagues.

**Comment by bmcfee** [comment]
Waking this thread up: are people still interested in working on this?

**Comment by shayenne** [comment]
Hi, sorry for the delay. I just sent a pull-request with some code. If someone is still interested, I would like to work together.

**Comment by bmcfee** [comment]
I'm punting this up to the 0.8 milestone, mainly because 0.7.1 is already getting pretty heavy and there's nothing explicitly depending on this feature to move forward.

**Comment by bmcfee** [comment]
Removing this from the 0.8 milestone, unless someone can step up to finish it in the near future (next month or so).

**Comment by bmcfee** [comment]
Closing this issue out due to inactivity.  If anyone feels like reviving it and working on a PR, we can discuss reopening it.
