### ISSUE TITLE
Remove assertions from library

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#784]
#### Description
@lostanlen noticed recently that there are a few spots in the code with `assert` statements that should really be exceptions.  This is bad practice because it makes downstream error handling difficult and non-diagnostic.  Replacing these assertions with exceptions ought to be easy.

Offending lines:

https://github.com/librosa/librosa/blob/c9c1b6d74a06afec9aad07425b6e59fd39bdb364/librosa/core/audio.py#L367

https://github.com/librosa/librosa/blob/27174ba111faa859f67cbb22f0ec3bc646196da6/librosa/core/spectrum.py#L1265

#### Versions
0.6.2 and below.

**Comment by lostanlen** [comment]
@bmcfee thank you for doing this :)
