### ISSUE TITLE
MAINT `imp.load_source` is deprecated

### ISSUE THREAD

**Issue by lostanlen** [librosa/librosa#788]
#### Description
The `imp` module is deprecated (https://docs.python.org/3/library/imp.html) at the profit of `importlib`
Yet librosa calls `imp.load_source` to load a `version` and a `short_version` in `setup.py` and `conf.py`
It would be good to get rid of this deprecation

#### Steps/Code to Reproduce
https://github.com/librosa/librosa/blob/e2d33b0c81f459c50f351f5db496274d75e5e986/setup.py#L5

https://github.com/librosa/librosa/blob/223c6b1842470451d1c68479d638d6442f7facf0/docs/conf.py#L169

#### Versions
v0.6.2

**Comment by bmcfee** [comment]
Weirdly, `version.py` already uses importlib instead of imp.  I'll patch this up shortly.

**Comment by bmcfee** [comment]
See comment thread in #790 for why this is tricky.
