### ISSUE TITLE
import porblem

### ISSUE THREAD

**Issue by red-lighting** [librosa/librosa#789]
I install the 0.6.2 version by pip. While I import librosa, it have the  error that "AttributeError: 'module' object has no attribute '__version__' ". I try to figure it out, maybe it is relative to the numba module. Could you give me some advices?

**Comment by red-lighting** [comment]
it is '__version__' like this

**Comment by bmcfee** [comment]
That's hard to diagnose without more information.  Could you please fill out the questions in the issue template so that we know what the other dependency versions are?  And, if possible, paste a capture of the exact error message and backtrace?

Thanks.
