### ISSUE TITLE
Audio mixing function

### ISSUE THREAD

**Issue by kyungyunlee** [librosa/librosa#798]
I was wondering if it would be useful to have a function to mix two audio samples with a given ratio.
(e.g. Mix two audio with 0.5/0.5 or 0.2/0.8 ratio).
Usually as far as I know, mixing audio is adding audio samples and clipping. Or it could be normalized by the number of audio being mixed. 

I have been naively mixing audio with ratio, `r` by :
` mixed_audio = r * audio_A + (1-r) * audio_B ` but the result normally doesn't quite match my expectation as you can easily imagine. 
So some time ago I came across this [paper](https://arxiv.org/pdf/1711.10282.pdf) and [code](https://github.com/mil-tokyo/bc_learning_sound/blob/master/utils.py) about using A-weighting that takes into consideration the human perception to improve the naive method for real auditory experience, and I am still referring to this paper/code till now. 

Mixing function that allows both basic and a-weighted method would be helpful in various situations like data augmentation and creation. 
Any thoughts on implementing a simple mixing function in librosa? :)
Thanks!

**Comment by lostanlen** [comment]
Hi @kyungyunlee!

1. At NYU MARL we are already maintaining a library for musical data augmentation named muda (MUsical Data Augmentation).
I you haven't already done so, please see ISMIR 2015 paper by McFee and Bello:
http://bmcfee.github.io/papers/ismir2015_augmentation.pdf
It features a `BackgroundNoise` object-oriented interface for mixing two signals with random weights, one belonging to a pool of "foreground" sounds and the other belonging to a pool of "background" sounds:
https://muda.readthedocs.io/en/latest/deformers.html#muda.deformers.BackgroundNoise

2. If you have more than one foreground sound to mix over the background, I would recommend using Justin Salamon's soundscape generator library `scaper`:
https://github.com/justinsalamon/scaper
See his paper from WASPAA 2017

3. From a deterministic standpoint, this can be achieved with a `Combiner` from Rachel Bittner's `pysox`:
https://pysox.readthedocs.io/en/latest/api.html#module-sox.combine
See her paper from ISMIR-LBD 2016

I personally am a user (and occasional contributor) to each of these three libraries so unless there is a compelling use case for it that is not covered by any of them, I would tend to prefer avoiding porting it to `librosa`.

Does that make sense?

**Comment by kyungyunlee** [comment]
Oh thank you for the pointers. 
pysox Combiner `build` function is what I was looking for to get simple mixing done. 
I was hoping something a little bit more sophisticated as in mixing with ratio that aligns with auditory perception, like using a-weighting mentioned above. 
This way, we can easily mix two tracks with weights and get some reasonably sounding ratio. 
But if it is of not much use then I am happy to just use customized functions 😄 
Thanks again!

**Comment by kyungyunlee** [comment]
It is indeed and it was still open haha
Excuse me for not going through the issues thoroughly enough 😭
Thank you!

**Comment by lostanlen** [comment]
that's ok! there's no need to weep :) 
let's redirect this discussion to #463

**Comment by justinsalamon** [comment]
@kyungyunlee if you're interested in perceptually motivated mixing, in [scaper](github.com/justinsalamon/scaper) we use [LUFS](https://en.wikipedia.org/wiki/LKFS) to estimate the loudness of each signal for mixing :)

**Comment by kyungyunlee** [comment]
@justinsalamon ah I see it! I think scaper is great for what I am working on right now, it will make my life easier :) :)  Thanks!!

**Comment by justinsalamon** [comment]
@kyungyunlee great, glad to hear it, and cheers @lostanlen for the shout out :)
