### ISSUE TITLE
Extend MFCC docs

### ISSUE THREAD

**Issue by stefan-balke** [librosa/librosa#804]
The question of non-default hop sizes etc. for MFCC extraction comes up frequently.

Maybe we should add an example to the MFCC docs where we vary the `melspectrogram` parameters.

**Comment by bmcfee** [comment]
Since #834 merged, this section of the documentation will be much easier to write. *hint hint* :grin:

**Comment by bmcfee** [comment]
I started looking into the HTK implementation in more detail, and there are a few things that make this a bit of a pain to replicate directly.  Specifically, we don't have liftering or pre-emphasis, so they'd have to be rolled in explicitly.

I think I'll punt on including a notebook for replicating HTK (and Slaney) mfcc's for now, but those would be good features to add later on.

That said, I'm expanding the mfcc docs to show hop length, htk, and centering.

**Comment by bmcfee** [comment]
Note: this [repo](https://github.com/danijel3/PyHTK) gives a pretty thorough replication of HTK.  I haven't tested it (registration wall on HTK, ugh) but it seems well done.
