### ISSUE TITLE
Maybe a better Implementation of Method "pitch_tuning" in librosa/core/pitch.py

### ISSUE THREAD

**Issue by Robrib** [librosa/librosa#806]
#### Versions

librosa ›
--
 
Maybe a better Implementation of Method "pitch_tuning" in librosa/core/pitch.py

In librosa/core/pitch.py, line 157, "bins = np.linspace(-0.5, 0.5, int(np.ceil(1./resolution)), endpoint=False)"  is written. However, I reckon that it is better to be written like this: "bins = np.linspace(-0.5, 0.5, int(np.ceil(1./resolution))+1)" .

Here is my reason:

![image](https://user-images.githubusercontent.com/37358510/50464260-e023d800-09ca-11e9-801d-6e68f20e33dc.png)

When you use **bins1** as an input of **np.histogram()**, it has actually 9 bins: [-0.5, -.0.4), ... [0.2, 0.3), [0.3, 0.4]. So any elements > 0.4 in **residuals** will not be counted(see **counts1**). Even if you set the **resolution** as 0.01, any elements > 0.49 in **residuals** will not be counted, which means the range of the **pitch_tuning()**'s return is [-0.5, 0.49], instead of [-0.5, 0.5).

However, look at **bins2** and **counts2**. When put **bins2** in **np.histogram()**, it has actually 10 bins: [-0.5, -.0.4), ... [0.3, 0.4), [0.4, 0.5], and all elements in **residuals** will be counted(because all elements in residuals is between[-0.5, 0.5) ). Now the range of the **pitch_tuning()**'s return is  [-0.5, 0.5), it is more in accordance with the method's description.

**Comment by bmcfee** [comment]
Thanks for posting this.  I've tagged it for the upcoming 0.6.3 release, so it should be fixed soon.  A PR would be most welcome, but I can take care of it if you don't have the time to give it a shot.

**Comment by Robrib** [comment]
I have made a PR

在 2018年12月28日，上午1:18，Brian McFee <notifications@github.com<mailto:notifications@github.com>> 写道：


Thanks for posting this. I've tagged it for the upcoming 0.6.3 release, so it should be fixed soon. A PR would be most welcome, but I can take care of it if you don't have the time to give it a shot.
