### ISSUE TITLE
Remove unnecessary import *

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#810]
#### Description
Linting the code base recently turned up quite a few instances of `from .[somewhere] import *`.  These are generally unnecessary (except for submodule imports), and can confuse code health tools.

I think it shouldn't be too much work to replace these with explicit imports for the needed components, but I want to hold off on doing so because it might produce some accidental API breakage.

**Comment by lostanlen** [comment]
Should we take this opportunity to also remove `from`, and only use imports of the form
`import X.Y`
(rather than `from X import Y as Z`)?

Or are you OK with `from` as long as `Y` is not `*`?

**Comment by bmcfee** [comment]
I'm fine with `from` imports in general, just not unnecessary wildcard imports.  Some wildcard imports are intentional though (eg when exposing submodule functions at the package level).

I'll take a crack at this now that 0.6.3 is done.

**Comment by bmcfee** [comment]
Actually, upon closer inspection, it seems like all of the wildcard imports are submodule exports (ie imports within `__init__.py` files), so I think there's nothing to do here.
