### ISSUE TITLE
Precision of reading WAV files

### ISSUE THREAD

**Issue by hagenw** [librosa/librosa#811]
#### Description

The precision of the magnitude of a loaded WAV file is lower than expected.

#### Steps/Code to Reproduce

Create a WAV file with specified magnitude and load it with `librosa` and `soundfile`.

```python
import librosa
import soundfile as sf
import numpy as np

magnitude = 0.1

rate = 44100
t = np.linspace(0, 10, rate * 10)
audio = magnitude * np.sin(2 * np.pi * 100 * t)
wav_file = 'test.wav'
sf.write(wav_file, signal, sampling_rate, subtype='PCM_32')

audio_sf, _ = sf.read(wav_file)
audio_lr, _ = librosa.load(wav_file, sr=None, mono=False)
```

#### Expected Results

I would expect that `librosa` has a similar precision in getting the correct magnitude than `soundfile`.

#### Actual Results
But, this is not the case:
```python
>>> max(np.abs(audio_sf))
0.10000000009313226

>>> max(np.abs(audio_lr))
0.1000061
```

This might be related to #796.

#### Versions
Linux-4.15.0-43-generic-x86_64-with-Ubuntu-16.04-xenial
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609]
NumPy 1.15.4
SciPy 1.2.0
librosa 0.6.2

**Comment by bmcfee** [comment]
Thanks for noting this.  This is (mostly) a result of dtype conversion in load, which by default casts down to float32.  If you load the data with `dtype=np.float64`, you get the following:

```python
In [9]: audio_lr2, _ = librosa.load(wav_file, sr=None, mono=False, dtype=np.float64)

In [10]: max(np.abs(audio_lr))
Out[10]: 0.1000061

In [11]: max(np.abs(audio_lr2))
Out[11]: 0.100006103515625
```
Still not matching exactly what you're seeing out of soundfile, but that could be down to different codec implementations under audioread.

At any rate, I'd generally defer to `soundfile` here.

**Comment by hagenw** [comment]
I was using `soundfile` before, but now I needed also the possibility to read MP3 files. This is [not yet included](https://github.com/erikd/libsndfile/issues/258) in `libsndfile` and hence also not in `soundfile`. 

After a few tests, I would say it seems to be the safest option to stay with `soundfile` for WAV or FLAC, and use `librosa` only for MP3.

As the underlying problem is most probably `audioread` related and cannot easily be fixed in `librosa`, it would be fine with me to close this issue.

**Comment by bmcfee** [comment]
Great, thanks for confirming.
