### ISSUE TITLE
Doc request: warning about bit truncation for core.load

### ISSUE THREAD

**Issue by woodshop** [librosa/librosa#813]
#### Description
Librosa uses `scipy.io.wavfile.write` for writing wav files and `audioread` for reading audio files. By design, Librosa writes wav files as floating point, which could be half, single, or double precision. This is enforced by a call to `util.valid_audio` and the behavior of `scipy.io.wavfile.write`:
https://github.com/librosa/librosa/blob/master/librosa/output.py#L225
https://github.com/librosa/librosa/blob/master/librosa/util/utils.py#L158
https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.wavfile.write.html#scipy.io.wavfile.write

The most widely-used precision for wav files is 16-bit integer, but I think the fact that Librosa allows other precisions is OK. Additional precision may be useful to preserving processing that's been applied to a lower-precision signal (e.g., resampling).

Yet `audioread` **always silently truncates audio to a sample width of 2**.
E.g., for integer PCM formats:
https://github.com/beetbox/audioread/blob/master/audioread/rawread.py#L135

And for floating point PCM formats:
https://github.com/beetbox/audioread/blob/master/audioread/ffdec.py#L124

(The latter, which is what is induced by Librosa via `scipy.io.wavfile.write`, uses the FFMPEG decoder to convert/truncate the data to 16-bit PCM)

There's a section in "Advanced I/O Use Cases" that warns users specifically about loading 32-bit floating point audio:
https://github.com/librosa/librosa/blob/master/docs/ioformats.rst

I don't think that this documentation is sufficient, especially considering that the simple of act of writing and loading the same wav file through Librosa will result in bit-truncation for anything over 16-bit int. I recently fell into this trap because I assumed that a write/read cycle would either be lossless or trigger a warning. I should have searched the docs for this specific scenario, but I didn't.

I'd love for the documentation of `core.load` to include a one-line warning about this behavior. It can be similar to the following:

> Warning: This method relies on `audioread`, which silently truncates audio to a sample width of 2. Please refer to "Advanced I/O Use Cases" for alternate methods of loading audio.

#### Versions
I'm using `0.6.2`. This issue is probably relevant to all versions.

**Comment by bmcfee** [comment]
Thanks for the detailed description of the issue here!  I agree with your points, and in particular, I didn't know about this one:

> Yet `audioread` **always silently truncates audio to a sample width of 2**:

I'd support a PR to expand the documentation as  you describe.  I'm not sure a run-time warning is the best way to do so, since inferring whether the current parameters and file being loaded will trigger the issue is non-trivial and probably beyond librosa's pay grade.  (Like so many other IO headaches, this will go away once libsndfile gets mp3 support...)

**Comment by woodshop** [comment]
@bmcfee Despite your comment I investigated providing a runtime warning. Unfortunately `audioread` doesn't expose native sample width when using the FFMPEG decoder. There's no easy way to tell what the original sample width was unless we start adding additional dependencies to Librosa. The above pull request just adds a short note to the docs, as you suggested.

--Andy

**Comment by bmcfee** [comment]
Thanks!
