### ISSUE TITLE
specshow representation

### ISSUE THREAD

**Issue by rohan7797** [librosa/librosa#815]
#### Description

I want to know the exact meaning of what the tonnetz specshow diagram indicates
[https://librosa.github.io/librosa/generated/librosa.feature.tonnetz.html](url)

**Comment by lostanlen** [comment]
Hello @rohan7797,
This is explained in the documentation at the link you pointed.

```
tonnetz : np.ndarray [shape(6, t)]
    Tonal centroid features for each frame.
    Tonnetz dimensions:

            0: Fifth x-axis
            1: Fifth y-axis
            2: Minor x-axis
            3: Minor y-axis
            4: Major x-axis
            5: Major y-axis
```

If you are not already familiar with tonal centroid features, I recommend you read the paper of Harte et al. 2006
http://www.ofai.at/~martin.gasser/papers/oefai-tr-2006-13.pdf

**Comment by rohan7797** [comment]
Hi thank you for the quick response I read the papers but I still can't understand what the scale represents on the right hand side of the tonal diagram

**Comment by lostanlen** [comment]
@rohan7797 which diagram? could you please share your code and its output?

**Comment by rohan7797** [comment]
![image](https://user-images.githubusercontent.com/31583020/52179446-c911aa80-2800-11e9-9cd0-6bba04249dc7.png)

**Comment by lostanlen** [comment]
@rohan7797 i don't understand the question "how does it signify the change in harmonics". Equation 3 of the paper i shared above describes precisely how these features are computed, and what their positive and negative values indicate. I invite you to reach out to Christopher Harte for further clarifications. In any case, i don't see this issue as requiring a necessary change to the codebase of librosa, so i propose to close it.
