### ISSUE TITLE
Allow for streaming per-channel energy normalization (PCEN)

### ISSUE THREAD

**Issue by daemon** [librosa/librosa#816]
#### Description
AFAIK, the current implementation of PCEN (`librosa.core.pcen`) is non-streaming. This is an issue, since applications in, for example, speech recognition and keyword spotting depend on streaming computation of spectrogram features. My [PyTorch PCEN implementation](https://github.com/daemon/pytorch-pcen) supports streaming audio (and trainable weights), but it's probably slower on the CPU than LibROSA's implementation.

**Comment by lostanlen** [comment]
Thanks @daemon for raising this issue and for sharing a PyTorch implementation of PCEN under MIT license! :)

I don't have any experience with streaming, but yes this would be a great addition. I guess that the way we close this issue depends on the decisions we end up taking re: #101.
I agree with @bmcfee that hooking into the initial filter state (zi) is the way to go for the IIR filter. Very neat idea 👍
