### ISSUE TITLE
spectral contrast output shape

### ISSUE THREAD

**Issue by rohan7797** [librosa/librosa#817]
#### Description

Why does spectral contrast output n_bands+1
I read the paper and it suggested it only had 6 bands so why the extra band in the output

**Comment by bmcfee** [comment]
The implementation was designed to match the reference matlab implementation provided by the Drexel METLab.  Looking over the source, I think the idea was to provide an extra band that catches everything up to Nyquist.  If you want to discard the last band to get exactly `n_bands` octaves starting from `fmin`, that should give you something more in line with the original article.

**Comment by rohan7797** [comment]
Thanks a lot for the prompt response !!

**Comment by lostanlen** [comment]
@rohan7797 can we close this issue?

**Comment by rohan7797** [comment]
Yeahh sure. Thanks!!
