### ISSUE TITLE
use rfft in stft/ifgram/fmt?

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#818]
#### Description
In reviewing `core/spectrum.py`, I noticed that we use full FFTs in places where we can almost certainly get away with rffts.  I believe this is a holdover from the initial matlab port, which as noted in #521, involved some unnecessary conjugations.  Places where this comes up:

- STFT: input is assumed to be real, and output is always the non-negative spectrum.  No reason not to use rfft here.
- ISTFT: same as above: we're assumed to be computing a real-valued output, so the conjugate symmetry assumption is enforced anyway.
- IFGRAM: again, same as above, provided we're careful about slicing the phase differential correcly
- FMT: this one's an oddball.  It's technically never stated that we're assuming realness (or conjugate symmetry), but we slice out the non-negative spectrum anyway, so there's no reason not to.

Changing these over to rfft shouldn't impact the outputs.  The runtime will probably be comparable: I don't expect a factor-2 speedup.  However, it would significantly cut down on intermediate storage, which can easily blow up on us with long signals.

As a bonus ask: while implementing this, we should keep an eye out for other optimizations (eg in-place scalings) that could cut down on copies.

#### Versions
librosa <= 0.6.3

**Comment by bmcfee** [comment]
I just took a quick stab at a few different options for this, and here are findings so far.

1. `fftpack.rfft` returns interleaved real values, rather than proper complex values.  So if we use fftpack, the outputs need to be translated into complex values, and this incurs an additional memory copy.
2. `np.fft.rfft` behaves as expected.

I tried a few different methods here, using either numpy or scipy.fftpack, different ways of repacking the real values into complex values, and blocking vs full batch processing.  Each configuration was tested on the included example track at 44100, truncated to different lengths.  I did not vary the frame length.

Before rfft (baseline, 0.6.3 implementation)
```python
In [1]: import librosa                                                                        

In [2]: y, sr = librosa.load(librosa.util.example_audio_file(), sr=None)                      

In [3]: %timeit librosa.stft(y[:sr])                                                          
2.74 ms ± 6.86 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [4]: %timeit librosa.stft(y[:2*sr])                                                        
4.12 ms ± 15.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [5]: %timeit librosa.stft(y[:4*sr])                                                        
6.9 ms ± 16 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [6]: %timeit librosa.stft(y[:30*sr])                                                       
42.9 ms ± 137 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [7]: %timeit librosa.stft(y)                                                               
101 ms ± 534 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
Using `np.fft.rfft`:
```python
After rfft

In [8]: %timeit librosa.stft(y[:sr])                                                          
2.19 ms ± 135 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [9]: %timeit librosa.stft(y[:2*sr])                                                        
2.59 ms ± 162 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [10]: %timeit librosa.stft(y[:4*sr])                                                       
3.09 ms ± 11.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [11]: %timeit librosa.stft(y[:30*sr])                                                      
15.6 ms ± 143 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [12]: %timeit librosa.stft(y)                                                              
44.3 ms ± 202 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
`np.fft.rfft` without blocking:
```python
1-shot rfft

In [15]: %timeit librosa.stft(y[:sr])                                                         
1.77 ms ± 8.77 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [16]: %timeit librosa.stft(y[:2*sr])                                                       
2.46 ms ± 36.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [17]: %timeit librosa.stft(y[:4*sr])                                                       
3.81 ms ± 21.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [18]: %timeit librosa.stft(y[:30*sr])                                                      
35 ms ± 2.41 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [19]: %timeit librosa.stft(y)                                                              
63.6 ms ± 642 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
`fftpack.rfft` with complex-interleaving in python:
```python
fftpack.rfft with repacking (python)

In [49]: %timeit librosa.stft(y[:sr])                                                         
3.79 ms ± 307 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [50]: %timeit librosa.stft(y[:sr])                                                         
3.2 ms ± 42.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [51]: %timeit librosa.stft(y[:2*sr])                                                       
4.84 ms ± 15.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [52]: %timeit librosa.stft(y[:4*sr])                                                       
8.1 ms ± 51 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [53]: %timeit librosa.stft(y[:30*sr])                                                      
56.2 ms ± 3.97 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [54]: %timeit librosa.stft(y)                                                              
126 ms ± 989 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
`fftpack.rfft` with numba repacking
```python
In [55]: %timeit librosa.stft(y[:sr])                                                         
3.11 ms ± 125 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [56]: %timeit librosa.stft(y[:sr])                                                         
3.09 ms ± 71.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [57]: %timeit librosa.stft(y[:2*sr])                                                       
4.91 ms ± 11.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [58]: %timeit librosa.stft(y[:4*sr])                                                       
7.48 ms ± 12.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [59]: %timeit librosa.stft(y[:30*sr])                                                      
46 ms ± 519 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [60]: %timeit librosa.stft(y)                                                              
107 ms ± 394 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
`fftpack.rfft` with numba repacking, no blocking
```python
In [62]: %timeit librosa.stft(y[:sr])                                                         
3.02 ms ± 38.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [63]: %timeit librosa.stft(y[:2*sr])                                                       
5.61 ms ± 94.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [64]: %timeit librosa.stft(y[:4*sr])                                                       
9.02 ms ± 25.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [66]: %timeit librosa.stft(y[:30*sr])                                                      
126 ms ± 5.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [67]: %timeit librosa.stft(y)                                                              
294 ms ± 1.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

The winner, so far, is keeping the block processing, and switching from `fftpack.fft` to `np.fft.rfft`.  This makes sense, as it should be the minimally memory-intensive implementation that gives complex output.  (It also passes regression tests, so we're okay on that front.)

The only dangling question here is whether dropping fftpack is a good idea in general.  Most of what I've seen suggests that it's generally faster than the numpy implementations.  Of course, if we really want speed, then this should be using `fftw` as noted here #379 , and that reopens that whole discussion.  I imagine the best possible thing will be fftw with the interface shim to mimic `np.fft.rfft`'s API.  How, exactly, to make this happen in a license-compatible way is a bit of a mystery, but perhaps we could add some API to make it easier to drop in pyfftw's interface at run-time without breaking license compatibility?

Pinging @carlthome for input on this.

**Comment by bmcfee** [comment]
Added some quick benchmarks using `pyfftw` and didn't see any improvement over `numpy.fft.rfft` here, either with batch or blocking mode.  (Comes out about the same or slightly slower than scipy fftpack, and much slower than numpy.)

I didn't dig too much into optimizing `fftw` configuration here though, so someone with more experience might have some useful insight.

**Comment by bmcfee** [comment]
I spent a bit more time on this with different fftw configurations, and am still not seeing any real improvement.

I think the most sensible thing to do here is roll back to numpy fft, and if a user specifically wants to use fftw, we can provide documentation in the advanced examples gallery on how to monkey-patch it using the numpy fft interface shim.  This ought to be as simple as saying `librosa.core.spectrum.fft = pyfftw.interfaces.numpy_fft` and everything should work seamlessly (assuming pyfftw is set up properly).

What do folks think?

**Comment by stefan-balke** [comment]
Hey Brian,

I like the interface design. `pyfftw` ninjas can then do whatever speeds things up for them!
