### ISSUE TITLE
ModuleNotFoundError: No module named 'librosa'

### ISSUE THREAD

**Issue by inbaral** [librosa/librosa#823]
Hey,
I installed Librosa with pip in python 3.7. Everything seemed to be successful, but then when I try importing it in Spyder, I get the error "ModuleNotFoundError: No module named 'librosa'".
The weird part is that when I do it PyCharm the import doesn't cause an error but librosa.load causes:
in audio_open raise NoBackendError()
audioread.NoBackendError

Any idea what the problem could be?
Thank you, Inbar

**Comment by lostanlen** [comment]
Hello, please see this issue
https://github.com/librosa/librosa/issues/219

**Comment by inbaral** [comment]
I did see this issue before and tried installing ffmpeg, but it didn't change anything.. The file is of type mp3 by the way

**Comment by lostanlen** [comment]
does `librosa.util.example_audio_file()` terminate successfully?

**Comment by inbaral** [comment]
It does

**Comment by lostanlen** [comment]
ok, thanks. can you load a non-MP3 file?

**Comment by lostanlen** [comment]
also, the reason why it may work in PyCharm but not in Spyder is probably due to the fact that these two IDEs are not using the same pip, and therefore not the same python.
My advice would be to install miniconda, activate a virtual environment in it, and finally link both spyder and pycharm to this miniconda distribution.

**Comment by inbaral** [comment]
> ok, thanks. can you load a non-MP3 file?

I tried mp3, mp4, ogg, wav and avi, nothing works :(

**Comment by bmcfee** [comment]
Is this resolved / was the problem actually environment issues?

**Comment by inbaral** [comment]
Hey,
It was resolved after I put the ffmpeg somewhere specific and changed the path.

Thank you for the help

**Comment by firaoll** [comment]
pip install librosa

**Comment by jeetshah0303** [comment]
doesn't work for me as well "ModuleNotFoundError: No module named 'librosa'"
after I used pip install librosa
on Anaconda

**Comment by lostanlen** [comment]
@jeetshah0303 the first thing you should try is `conda install -c conda-forge librosa`
And then `conda list` to see if conda is within the list of installed packages


Also, don't forget to activate your conda environment before launching Python
You can check whether the conda environment is active with a shell command such as `which python`

**Comment by AkiKagura** [comment]
@lostanlen Yes, you reminded me. My python and python3 commands do not use the same environment.Thanks!
