### ISSUE TITLE
melspectrogram of float32 array returns float64 array

### ISSUE THREAD

**Issue by lostanlen** [librosa/librosa#825]
#### Description
The transformation of an windowed Fourier spectrogram into a mel-frequency spectrogram returns a numPy array in double precision (type `numpy.float64`) even when this windowed Fourier spectrogram is encoded in single precision (type `numpy.float32`). The same happens when computing the mel-frequency spectrogram directly from a single-precision waveform.

Making `melspectrogram` return a numeric `dtype` that is the same as its first positional argument would reduce the memory footprint of librosa and possibly also improve speed. This is all the more crucial that `melspectrogram` is one of the most widely used functions in the library, and that having more than 32 bits of floating point precision is rarely needed in machine listening applications.

The overestimation of precision propagates to all functions that call `melspectrogram`, including, of course, `mfcc`.

#### Steps/Code to Reproduce
```
import librosa

# Load audio file
y, sr = librosa.load(librosa.util.example_audio_file())

# Compute squared modulus of short-term Fourier transform
S = np.abs(librosa.stft(y, dtype='complex64'))**2

# Extract melspectrogram from STFT squared modulus
M_from_S = librosa.feature.melspectrogram(S=S, sr=sr)

# Extract melspectrogram from waveform
M_from_y = librosa.feature.melspectrogram(y=y, sr=sr)

# Print type of all intermediate computations
print(y.dtype, S.dtype, M_from_y.dtype, M_from_S.dtype)
```

#### Expected Results
```float32 float32 float32 float32```

#### Actual Results
```float32 float32 float64 float64```

#### Versions
```
Linux-3.10.0-514.10.2.el7.x86_64-x86_64-with-centos-7.3.1611-Core
Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 21:41:56) 
[GCC 7.3.0]
NumPy 1.15.2
SciPy 1.1.0
librosa 0.6.2
```

**Comment by bmcfee** [comment]
I'll tack onto this issue that all of our filterbank constructors (mel, chroma, cq_to_chroma, cqt) should have dtype parameters, and we can roll that into the PR.
