### ISSUE TITLE
Unhelpful error message in recurrence_matrix [formerly: Load Small Duration Error]

### ISSUE THREAD

**Issue by PatrickDuncan** [librosa/librosa#827]
#### Description
I have a project that has to occasionally deal with very small audio file segments. These segments can be less than 2 seconds long. _pydub_ handles small segments correctly, but _librosa_ crashes.

#### Steps/Code to Reproduce
```
import librosa

librosa.load(file_path, sr=None, duration=1, offset=10)
```

#### Expected Results
I expected to be able to load the offset to duration length of the file

#### Actual Results
```
...
  File "/Users/patrick/anaconda3/lib/python3.6/site-packages/librosa/decompose.py", line 503, in nn_filter
    rec = segment.recurrence_matrix(S, axis=axis, **kwargs)
  File "/Users/patrick/anaconda3/lib/python3.6/site-packages/librosa/segment.py", line 216, in recurrence_matrix
    rec.setdiag(0, diag)
  File "/Users/patrick/anaconda3/lib/python3.6/site-packages/scipy/sparse/base.py", line 1143, in setdiag
    raise ValueError("k exceeds matrix dimensions")
ValueError: k exceeds matrix dimensions
```

#### Versions
```
Darwin-18.2.0-x86_64-i386-64bit
Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
NumPy 1.14.3
SciPy 1.1.0
librosa 0.6.2
```

**Comment by lostanlen** [comment]
Dear Patrick Duncan,
Can I ask you why you are using `offset=10` if the file is 2 seconds long?

**Comment by bmcfee** [comment]
I think @lostanlen is hitting on the answer here: it's crashing because the signal is empty.

Probably the loader should at warn when the offset exceeds the track duration and the output is empty, but I think the behavior is correct / expected (if not entirely obvious from the user perspective).  I'll tag this for the next release.

**Comment by PatrickDuncan** [comment]
@bmcfee @lostanlen Sorry for the late reply, the song is a few minutes long so the signal is not empty. The tool I'm using breaks up a song into small segments so having [that] offset is fine.

If I put a duration of 2 the result is as expected, which made me believe that getting an error when putting 1 as the duration is a bug.

**Comment by bmcfee** [comment]
> If I put a duration of 2 the result is as expected; which made me believe that getting an error when putting 1 as the duration is a bug.

Ok, that's pretty weird!  I'm inclined to doubt that it's a bug in the loader; if duration=2 works, then so should 1 (and I use this quite often).

Your example is incomplete though -- what's happening between load and the code that triggers the error?  I looks like you're doing something with the recurrence matrix generator, which can suppress the main diagonal for a given window duration.  If that window is longer than your signal, I would expect an error like the above.

**Comment by PatrickDuncan** [comment]
@bmcfee It appears that this call was causing the issue when I just tried to reproduce the error:
```
    return librosa.decompose.nn_filter(
        magnitude, aggregate=numpy.median, metric='cosine', width=width)
```

I must have observed the stack trace incorrectly a few days ago. Closing the ticket, thanks!

**Comment by bmcfee** [comment]
Great, thanks for checking back on it!  I expect that the culprit here is the `width` parameter, which is passed through to `recurrence_matrix` and documented here: https://librosa.github.io/librosa/generated/librosa.segment.recurrence_matrix.html#librosa.segment.recurrence_matrix .  I don't know what you currently have it set to, but dropping it down to something smaller should resolve the problem.

**Comment by bmcfee** [comment]
Note: I'm re-opening this issue and flagging it for 0.7 so that we improve the documentation in the recurrence matrix function.
