### ISSUE TITLE
RQA and Smith-Waterman 

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#837]
#### Description
(Forking this issue off from #741 , since it's pretty different from the initial idea there.  Tagging @ctralie for input though.)

librosa does not currently implement much in the way of recurrence quantification analysis, beyond standard DTW.  It would be easy to provide some basic functions for recurrence post-processing, such as the L/S/Q methods described by [Serra et al., 2009](http://iopscience.iop.org/article/10.1088/1367-2630/11/9/093017/meta), and [Smith-Waterman](https://en.wikipedia.org/wiki/Smith%E2%80%93Waterman_algorithm).

The L-method simply accumulates diagonals, and resets the counter whenever there's a gap (`R[i,j] = 0`).

The S-method accumulates diagonals, but allows for gaps of length 1 by considering the max over the immediate diagonal and knight's moves away from `R[i, j]`.

The Q method is closely related to Smith-Waterman, with the following modifications:
- only gaps of length 1 are directly computed
- instead of diagonal/horizontal/vertical, the gaps are diagonal and knight's moves
- different gap penalties are applied depending on whether an entry introduces a new gap or extends an existing one.

While Q and SW are related, I don't see a clean way to implement both with the same underlying function.  I think it would be simpler to have two independent functions for these.
Q and S can be simply implemented though: as noted by Serra et al., when the gap penalties become large, the Q method simplifies to the S method (all gaps instigate a reset).
Likewise, if we make knight's moves a toggle, then it's easy to restrict Q down to L (with large penalties and knight moves disabled).

As mentioned in the previous thread, I've prototyped these already with numba, and they're pretty fast.  The only remaining challenges are:
1. supporting sparse input
2. making a generic API to encapsulate all of the above methods
3. generalize to accumulate link strength rather than counting steps.  With binary input, this recovers the original implementation.

**Comment by bmcfee** [comment]
Update: here's a [notebook](https://gist.github.com/6455be3a6a248721247f15912c66f2a8) with my prototype implementations.  The API is rough, and there's still no sparse matrix support, but otherwise it provides three basic implementations (L, S, Q) and a generic implementation (enhance) that subsumes all three.  Soft affinities are supported.

**Comment by bmcfee** [comment]
I gave this some thought, and I'm not sure that it makes sense to support sparse (csr_matrix) recurrence matrices directly here.  The output will be generally dense (at least as dense as the input), and requires iterating over all entries `R[i,j]` (not just the non-zeros) to support gaps.

It would be possible, though incredibly ugly, to support sparse input, dense output, using numba by directly working in the index/data fields of the `csr_matrix` (like we do in `nn_filter`), but I don't think it would be worth the effort.

Additionally, after digging a bit more, it seems that the Q method described above is equivalent to SW with a particular choice of affine gap penalty.  So maybe we don't need a separate method after all, assuming we're willing to take that restriction on the form of the gap penalty.

Unless anyone else wants to chime in on this, I'll polish it up and PR it some time in the next couple of weeks.

**Comment by bmcfee** [comment]
Catching up on this, two API design questions come to mind:

1. My notebook implementation (and most RQA literature I've seen) treats the problem as a maximization of similarity.  OTOH, our current DTW implementation minimizes cost (distance), and it would be nice if the two APIs could be consistent.  Anyone have thoughts on this?

2. For returning the path, I'd like to keep the same API as the dtw implementation.  This should be easy enough to do, but it does raise a side question of which path to return.  By default, the point which maximizes the score would make sense, but perhaps others do as well?

**Comment by ctralie** [comment]
For 1. You could have min or max be a function handle 

For 2. In some cases you might have to break ties.  But otherwise, DTW always traces back from the end to the beginning, and Smith Waterman does usually trace back from the max anywhere.  Subsequence DTW traces from the top to the bottom (where cross-similarity matrix is subsequence along the rows and full sequence along the columns).  So maybe it is good to try to be flexible with where you start tracing and what your stopping conditions are.

**Comment by ctralie** [comment]
Okay, so a quick note on speed not directly related to your musings but still relevant.  I wanted to see how numba would compare to Cython on a constrained version of Smith Waterman I'd coded up before (not exactly like any of the versions in your notebook, but similar, from a Serra 2008 paper on "binary chroma similarity").  I made a repo here:

https://github.com/ctralie/pySeqAlign

For a 1000x1000 matrix, I'm seeing the following times
Time elapsed Cython 0.0175 seconds, ans = 12.4
Time elapsed Numba: 0.426 seconds, ans = 12.4
Time elapsed Raw Python: 14.9 seconds, ans = 12.4

So numba is a huge improvement over raw Python, but Cython is a huge improvement over numba.  And Cython is nearly 3 orders of magnitude faster than raw python.
Thoughts on this?  Am I missing something with numba?  This might still be fast enough for your purposes, avoiding potential compilation headaches for Cython, but in some of my small scale algorithms I run a set of all pairwise alignments in a database of songs, so the difference between Numba and Cython makes a huge difference for me.

**Comment by bmcfee** [comment]
> For 1. You could have min or max be a function handle

Function handles won't play nicely with numba jitting.  There are ways to hack around this, but I'd prefer to avoid them.



> Thoughts on this? Am I missing something with numba?

Your timing code uses timestamp diffs, which are not entirely robust for a variety of reasons.  Most relevant here is that numba code gets compiled the first time it's called, so you're including that overhead in the numba benchmarks.  It's also only running once, when really it should be aggregating over multiple runs.  The `timeit` package makes this sort of thing relatively easy to do, though I usually just invoke it in notebooks by the `%timeit` magic.

**Comment by ctralie** [comment]
Ah nice, "just in time."  Thanks

Okay, I updated the code to use timeit with 1000 reps of each.  See if you agree with my experiment now.  Here's what I got:

Cython Time: 15.9, ans=12.4
Numba  Time: 77.5, ans=12.4

So numba is indeed substantially faster after having compiled, and the gap is closer, but Cython is still faster by about 5x.  Perhaps this isn't surprising, since I could write such specialized code in pure C?

**Comment by ctralie** [comment]
(btw, I am not planning to release a package on sequence alignment...this is purely for experimentation, since I need these algorithms for some large scale experiments I'm doing)

**Comment by bmcfee** [comment]
> Okay, I updated the code to use timeit with 1000 reps of each. See if you agree with my experiment now. Here's what I got:
> 
> Cython Time: 15.9, ans=12.4
> Numba Time: 77.5, ans=12.4

That looks much more reasonable :grin:   If you want to close that a little more, it might help to warm-start each function once before runing the timing experiment, since the average time will be thrown off by one outlier (compilation).

The other thing is that you're reporting "5x", but you can't conclude that from a single input size; the time difference could just as well be 60ms independent of input size.  That's probably not the case, and I expect the truth is somewhere in between.  But really what would be best is to sweep over a range of input sizes to characterize the relation between the two implementations.  (It has to be linear, but the question is what's the slope.  I know, benchmarking is a total pain!)

At any rate: even if numba does turn out to be slower, which makes sense since it's running in JVM, it's much easier to write, maintain and package for distribution than cython code is.  And that's a huge plus.

**Comment by ctralie** [comment]
Great point!  Thanks for keeping me honest.  It looks more like a factor of 3:

![Numba_Vs_Cython](https://user-images.githubusercontent.com/1270246/54939239-713d1900-4efe-11e9-9cb9-aee39d8e118f.png)

Anyway, I'm excited about two things here
1) How simple numba is, and how much better it is than raw Python (never used it before)
2) That there's still a 3x factor to be had for people like me who are doing large scale experiments

I've been having an absolute nightmare getting cython to work cross platform in another project, so I'll definitely look into numba

**Comment by bmcfee** [comment]
Nice!  That phase transition between 10 and 20 is interesting; I wonder what's all about.

You might also find jakevdp's post on non-uniform FFT implementations interesting: https://jakevdp.github.io/blog/2015/02/24/optimizing-python-with-numpy-and-numba/ as it touches on some of these issues.

**Comment by lostanlen** [comment]
can we bump this to 0.8.0?

**Comment by bmcfee** [comment]
We could, but it I do have a 90% functional implementation in a notebook that just needs to be ported over and cleaned up.  (It also needs backtracking, but nbd.)

**Comment by bmcfee** [comment]
Circling back on this, a few final thoughts before I start the PR:

1. For now, I'm going to keep the optimization as a maximization problem.  At some point in the future, it might be nice to add the option to both this and DTW to switch between max and min, but it seems non-essential here.
2. Unlike DTW, my notebook implementation *only* supports input in the form of a cost/value matrix (ie a recurrence matrix or cross-similarity matrix).  DTW supports both this form and a pair of inputs that are compared using a metric.  I prefer the simplicity of keeping distance / similarity calculations out of the alignment algorithm, but it does lead to some API inconsistencies.  I'm okay with the inconsistency for now, but maybe a future PR could standardize the interface to do cross-similarity calculation under the hood as well.

Aside from those points, the only remaining issue for me is: what should we name this method?  It's not exactly smith-waterman (but it's very close).  The presentation in Serra's paper doesn't have give the various methods descriptive names.  Are people okay with `librosa.sequence.rqa`?  Other suggestions?
