### ISSUE TITLE
segmentation fault when increase n_mels to 80

### ISSUE THREAD

**Issue by shawnthu** [librosa/librosa#838]
librosa version 0.6.3
numpy version 1.13.3

code:
```python
audio, rate = librosa.load(full_stem + '.wav', sr=None); 
feature = librosa.feature.melspectrogram(audio, rate,
n_fft=int(25*rate/1000),hop_length=int(10*rate/1000), n_mels=60, fmin=80, fmax=7600)
```
when I set n_mels=80, it raises segmentation fault! 
Then I debug and find that `np.dot` function raise the above except! But in fact this function can handle much larger matrix! I don't know why

**Comment by bmcfee** [comment]
Please fill out the issue template, including all dependency versions.

**Comment by shawnthu** [comment]
> Please fill out the issue template, including all dependency versions.

Hi, bmcfee. it's a very simple procedure. You can choose any short wav file (just a few seconds) and calculate its mel spectrogram. And you will find that when you set n_mels larger than 60, numpy.dot will raise segmentation fault!

**Comment by bmcfee** [comment]
Hi, shawn.  librosa is written in python, and does not directly do any memory allocation.  Any segfaults must be coming from up-stream in the dependency chain.  So please fill out the issue template so we know what your specific dependency chain is.

Also, the default `n_mels` is 128, which is larger than 60.

**Comment by shawnthu** [comment]
> Hi, shawn. librosa is written in python, and does not directly do any memory allocation. Any segfaults must be coming from up-stream in the dependency chain. So please fill out the issue template so we know what your specific dependency chain is.
> 
> Also, the default `n_mels` is 128, which is larger than 60.

I just updated my numpy to version 1.16.2, which is the latest one. Now everything is ok! Thank you all the same!
