### ISSUE TITLE
Griffin-Lim, inverse mel, inverse mfcc

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#843]
#### Description
This issue is mostly inspired by commentary on #434, and a narrowing of scope.

Specifically, I'd like to add the following functions and a `librosa.feature.inverse` submodule:

- `core.griffinlim` for linear magnitude spectra --> time domain signal
- `feature.inverse.mel_to_stft` invert a mel power spectrogram (with or without dB) --> linear spectrogram
- `feature.inverse.mel_to_audio` invert a mel power spectrogram (with or without dB) --> audio
- `feature.inverse.mfcc_to_mel` invert mfcc -> mel power spectrogram
- `feature.inverse.mfcc_to_audio` -> mfcc to audio

Once GL is in place, the rest can be implemented using least squares / pseudo-inversion of the filters, and the existing `db_to_amplitude` function.

Unit testing this will be a bit of a pain: we can use probe signals centered exactly at mel frequencies for part of it, but it will get pretty dicey for mfcc inversion.

**Comment by keunwoochoi** [comment]
This is great!
