### ISSUE TITLE
Use soundfile for primary IO, fall back on audioread in emergencies

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#845]
#### Description
As noted too many times in the issues to keep track of, the current `audioread`-based loader is both inefficient and somewhat finnicky across platforms and with varying back-end codec configurations.
My recommendation has long been to use `soundfile` unless mp3 support is absolutely necessary, and plan to eventually switch over to soundfile in librosa once mp3 support is merged.

That said, there's no reason we couldn't have a soft dependency on `soundfile` as a first-pass attempt to load the data, and only fall back to audioread if soundfile fails for some reason (not installed, missing codec, etc).  This would basically have librosa doing audioread's job (multiplexing over decoding backends), but this is only a temporary situation until mp3 support arrives.  In the meantime, we'd get faster loading and a more stable backend.

What do folks think?

**Comment by bmcfee** [comment]
Note: the other place audioread gets used is in `get_duration`, but soundfile also provides this functionality: `sf.info(filepath).duration`.

**Comment by faroit** [comment]
I think thats a great idea. 

It would probably be even better if some one would come up with a CFFI interface for ffmpeg, since mp4 support might become more important in the future. But libsndfile is probably not going anywhere, so... lets do this!

I would also love to see seeking support since this can be handled by soundfile as well. But then this would not be possible to do with audioread.

**Comment by bmcfee** [comment]
> I would also love to see seeking support since this can be handled by soundfile as well. But then this would not be possible to do with audioread.

What use case do you have in mind?  soundfile doesn't always handle seeking, and it depends on where the underlying bytestream comes from.

That said, there's nothing stopping you from using soundfile outside of librosa; it returns numpy arrays, so everything plays nicely together.  The `librosa.load` interface would really just be a shim for API compatibility.

**Comment by faroit** [comment]
> What use case do you have in mind? 

feature extraction of files that don't fit into RAM

> soundfile doesn't always handle seeking, and it depends on where the underlying bytestream comes from.

didn't know about these issues. Lets stay away from this, then

**Comment by bmcfee** [comment]
> feature extraction of files that don't fit into RAM

We already have some docs on how to do this with sf: https://librosa.github.io/librosa/ioformats.html

sf exposes an API to test if a particular "file" is seekable: https://pysoundfile.readthedocs.io/en/0.9.0/#soundfile.SoundFile.seekable

**Comment by faroit** [comment]
> We already have some docs on how to do this with sf: https://librosa.github.io/librosa/ioformats.html

yes, sure, I knew about this. What I meant is exactly how you implemented it in #847: rely on `soundfile` when it comes to seeking, thus avoid the outer loop.  👍

**Comment by faroit** [comment]
Another thing: since `soundfile` is in as a dependency, we could replace `scipy.io.wavfile` for the output module. I could do a PR once the load/read is finished.

**Comment by bmcfee** [comment]
Sure, though I think I'd prefer to handle that by implementing a new function `core.save` and deprecating the output module, so it'd be a bit more work than is currently in #847.
