### ISSUE TITLE
Unable to install librosa for python 3.6.7 in windows 10 with virtual environement

### ISSUE THREAD

**Issue by murali-vutti** [librosa/librosa#848]
I am trying to install librosa for a project with python 3.6.7. But I'm receiving following error. I'm installing librosa in a virtual environment. My pip version is 19.0.3. I'm using windows 10 64 bit system

(env) D:\directory\projectName>pip install librosa
Collecting librosa
  Using cached https://files.pythonhosted.org/packages/e9/7e/7a0f66f79a70a0a4c163ecf30429f6c1644c88654f135a9eee0bda457626/librosa-0.6.3.tar.gz
Requirement already satisfied: audioread>=2.0.0 in d:\salcitpython3virtualenv\env\lib\site-packages (from librosa) (2.1.6)
Requirement already satisfied: numpy>=1.8.0 in d:\salcitpython3virtualenv\env\lib\site-packages (from librosa) (1.16.2)
Requirement already satisfied: scipy>=1.0.0 in d:\salcitpython3virtualenv\env\lib\site-packages (from librosa) (1.2.1)
Requirement already satisfied: scikit-learn!=0.19.0,>=0.14.0 in d:\salcitpython3virtualenv\env\lib\site-packages (from librosa) (0.20.3)
Requirement already satisfied: joblib>=0.12 in d:\salcitpython3virtualenv\env\lib\site-packages (from librosa) (0.13.2)
Requirement already satisfied: decorator>=3.0.0 in d:\salcitpython3virtualenv\env\lib\site-packages (from librosa) (4.3.2)
Requirement already satisfied: six>=1.3 in d:\salcitpython3virtualenv\env\lib\site-packages (from librosa) (1.12.0)
Collecting resampy>=0.2.0 (from librosa)
  Using cached https://files.pythonhosted.org/packages/14/b6/66a06d85474190b50aee1a6c09cdc95bb405ac47338b27e9b21409da1760/resampy-0.2.1.tar.gz
Collecting numba>=0.38.0 (from librosa)
  Using cached https://files.pythonhosted.org/packages/e6/45/d1c15c431d3361f074a25dcb278e79367b34ee44b6ca1bc2b7992e2382aa/numba-0.42.1.tar.gz
Collecting llvmlite>=0.27.0dev0 (from numba>=0.38.0->librosa)
  Using cached https://files.pythonhosted.org/packages/31/6a/2af9e150c053c194c751060b904ce9bdbb588ae3c6ce95569f95a2004884/llvmlite-0.27.1.tar.gz
Installing collected packages: llvmlite, numba, resampy, librosa
  Running setup.py install for llvmlite ... error
    Complete output from command d:\salcitpython3virtualenv\env\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-t2tacdjy\\llvmlite\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\user\AppData\Local\Temp\pip-record-lbvbni7w\install-record.txt --single-version-externally-managed --compile --install-headers d:\salcitpython3virtualenv\env\include\site\python3.6\llvmlite:
    running install
    running build
    got version from file C:\Users\user\AppData\Local\Temp\pip-install-t2tacdjy\llvmlite\llvmlite/_version.py {'version': '0.27.1', 'full': 'f008359c1f9ee5e8a6a98f2095ea460f09f57edb'}
    running build_ext
    d:\salcitpython3virtualenv\env\scripts\python.exe C:\Users\user\AppData\Local\Temp\pip-install-t2tacdjy\llvmlite\ffi\build.py
    Trying generator 'Visual Studio 14 2015 Win64'
    Traceback (most recent call last):
      File "C:\Users\user\AppData\Local\Temp\pip-install-t2tacdjy\llvmlite\ffi\build.py", line 167, in <module>
        main()
      File "C:\Users\user\AppData\Local\Temp\pip-install-t2tacdjy\llvmlite\ffi\build.py", line 155, in main
        main_win32()
      File "C:\Users\user\AppData\Local\Temp\pip-install-t2tacdjy\llvmlite\ffi\build.py", line 88, in main_win32
        generator = find_win32_generator()
      File "C:\Users\user\AppData\Local\Temp\pip-install-t2tacdjy\llvmlite\ffi\build.py", line 76, in find_win32_generator
        try_cmake(cmake_dir, build_dir, generator)
      File "C:\Users\user\AppData\Local\Temp\pip-install-t2tacdjy\llvmlite\ffi\build.py", line 28, in try_cmake
        subprocess.check_call(['cmake', '-G', generator, cmake_dir])
      File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 286, in check_call
        retcode = call(*popenargs, **kwargs)
      File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 267, in call
        with Popen(*popenargs, **kwargs) as p:
      File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 997, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    error: command 'd:\\directory\\env\\scripts\\python.exe' failed with exit status 1

    ----------------------------------------
Command "d:\directory\env\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-t2tacdjy\\llvmlite\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\user\AppData\Local\Temp\pip-record-lbvbni7w\install-record.txt --single-version-externally-managed --compile --install-headers d:\directory\env\include\site\python3.6\llvmlite" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-install-t2tacdjy\llvmlite\

**Comment by bmcfee** [comment]
This error is due to llvmlite, and is upstream of librosa.  I suggest checking the llvmlite and numba project documentation to see if there's a work around for your platform.

**Comment by lostanlen** [comment]
@murali-vutti  did you sort out your issue?

**Comment by lostanlen** [comment]
Haven't heard back from the OP in three months. Again, it seems like this installation error is related to LLVM, and not to librosa. Closing.
