### ISSUE TITLE
Text to speech (TTS) based on librosa?

### ISSUE THREAD

**Issue by mrgloom** [librosa/librosa#850]
Does librosa support Text to speech (TTS), if not maybe you can suggest some project that can do TTS and that is based on librosa?

**Comment by bmcfee** [comment]
TTS, and generally speaking, trained models with statistical dependencies, are out of scope for librosa.  You might want to check out kaldi or [mozilla deepspeech](https://github.com/mozilla/DeepSpeech) for an off-the-shelf solution.

**Comment by mrgloom** [comment]
[Kaldi](https://github.com/kaldi-asr/kaldi) and [mozilla deepspeech](https://github.com/mozilla/DeepSpeech) is not for text to speech, it's for speech to text.

Howewer mozila have [mozilla TTS](https://github.com/mozilla/TTS).

As I understand librosa is more low level lib.

**Comment by bmcfee** [comment]
Ah, sorry!  Total brainfart on my end reading that, but you're correct.

**Comment by rafaelvalle** [comment]
NVIDIA has recently put together a nice tutorial on how to build a TTS system using Tacotron 2 and WaveGlow
https://ngc.nvidia.com/catalog/model-scripts/nvidia:tacotron_2_and_waveglow_for_pytorch/quickStartGuide
