### ISSUE TITLE
PCEN should not initialize with silence

### ISSUE THREAD

**Issue by lostanlen** [librosa/librosa#851]
#### Description
Adapted from https://github.com/librosa/librosa/issues/615#issuecomment-473009124, initially raised by @4p0pt0Z 

When using the current implementation of the PCEN, artifacts appear due to the filter initialization. Currently, the filter is created with
`S_smooth = scipy.signal.lfilter([b], [1, b - 1], ref, axis=axis)`

When the initial conditions for the filter are not specified, initial rest is assumed.
See documentation of `zi` at this address: https://docs.scipy.org/doc/scipy-1.2.1/reference/generated/scipy.signal.lfilter.html

The initialization to zero is equivalent to assuming that the signal is preceded by an infinitely long silence. This is not realistic and causes numerical artifacts in the earliest timestamps of the PCEN-gram, especially in the most active bands.

#### Expected Results vs. Actual Results

Thanks to @f0k and @bmcfee, we already have a plan for a workaround:
* expose the `zi` as a kwarg parameter in the prototype of `pcen`
* `zi` defaults to `None`, in which case it gets automatically set as in steady-state.

This is how we plan to do it: https://docs.scipy.org/doc/scipy-1.2.1/reference/generated/scipy.signal.lfilter_zi.html#scipy.signal.lfilter_zi

Top: current results (with zero initialization of `zi`). Bottom: expected results (with: steady-state initialization of `zi`).

![54450887-dbe49c80-4727-11e9-9777-e39f1e059aa8 (1)](https://user-images.githubusercontent.com/3943142/54458075-6eda0280-4739-11e9-8cba-9b681b196634.png)

#### Versions
```
librosa 0.6.3
scipy 1.2.1
```

**Comment by f0k** [comment]
Note that this will simply result in `scipy.signal.lfilter([b], [1, b - 1], ref, axis=0, zi=(1 - b)*ref[:1])`, which is actually equivalent to my implementation in https://gist.github.com/f0k/c837bcf0bfde189ca16eab63637839cb#file-pcenlayer-py-L93: It will ensure that the first Smoother frame equals the first input frame. Go for it! But warn users that the default behavior has changed.

**Comment by bmcfee** [comment]
Yeah, the fix for #816 will involve a new flag to control whether `zf` is returned.
