### ISSUE TITLE
Length-aware icqt and istft are unnecessarily slow

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#854]
#### Description

Inverse transforms support a `length=` parameter which ensures that the output has a specific number of samples.  This is primarily used to extend reconstructed signals to match an input signal's length when the transform (eg STFT) discards any samples that don't fill up an entire window at the end of the signal.

If the user specifies a much shorter length than the inversion would otherwise produce, the reconstructed signal is truncated down to the given length.  This results in a lot of wasted computation.

A simple optimization would be to trim the input feature down to the minimum number of frames necessary to reconstruct the target length.  This wouldn't change the result, only make the inversion methods faster for partial reconstruction.

**Comment by lostanlen** [comment]
brought up during CR of #852
