### ISSUE TITLE
MFCC calculation

### ISSUE THREAD

**Issue by rohan7797** [librosa/librosa#858]
Hi, My question is a theoretical question.
While using the MFCC coefficients what is the exact mathematical way by which they are calculated i.e any type of bloack diagram or an overview of the method explaing how they are calculated will do.
Thank You

**Comment by bmcfee** [comment]
Please post this kind of question to the [discussion group](https://groups.google.com/forum/#!forum/librosa), as it does not specifically relate to issues with the software.  Thanks!
