### ISSUE TITLE
down pitch shifting causes small magnitude of high frequency components in log Mel-spectrogram

### ISSUE THREAD

**Issue by jjsgsk** [librosa/librosa#860]
#### Description
I believe this is how `pitch_shift` works, but I don't know much about it. As titled, in the below are three log Mel-spectrogram; from left to right: original, up-shifted by 2 steps, down-shifted by 2 steps.

The magnitude of specific high frequency components is extremely low in the down-shifted sample, which does not happen in the up-shifted sample in this particular case. 
I found this has something to do with `fmax` in `feature.melspectrogram`, though I am not sure how it works. The audio `sr` is 22050, and setting a high `fmax` seems to cause the issue, and it actually happens for both up- and down-shifted samples. I guess it is related to `resample`, could someone please shed light on it?
![image](https://user-images.githubusercontent.com/40157529/55279749-f5f0c280-5356-11e9-8f6b-0ac2b994c058.png)

#### Steps/Code to Reproduce
[test.wav]()
    import sys
    import numpy as np
    import librosa
    x, sr = librosa.core.load('test.wav')
    x_d2 = librosa.effects.pitch_shift(x, sr, -2)
    S = np.log(librosa.feature.melspectrogram(x, sr, n_mels=256, fmin=27, fmax=11000) + sys.float_info.epsilon)
    S_d2 = np.log(librosa.feature.melspectrogram(x_d2, sr, n_mels=256, fmin=27, fmax=11000) + sys.float_info.epsilon)

in this case, change `fmax=9000` doesn't lead the issue.

Linux-4.4.0-116-generic-x86_64-with-debian-stretch-sid
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0]
NumPy 1.16.2

SciPy 1.2.1
librosa 0.6.3

**Comment by bmcfee** [comment]
Short summary: this is expected behavior.

What's happening here is that the original signal is band-limited to `fmax=sr/2 = 11025 Hz` (when `sr=22050`).  That means that it has no energy at frequencies above 11025.  When you pitch-shift downward, it's going to bring in energy from those frequencies above the band limit, which leads to the low energy you see in the top bands on the third plot.  For example, when you pitch shift downward by 2 semitones, the energy you see at, say, 10000 Hz would originally have been at 10000 * 2^(2/12) ~= 11225 Hz, which is above `sr/2`.

This doesn't happen when up-shifting because the band limits are assumed to go all the way down to 0, which you'll never go past when scaling a frequency `f>0` by a positive factor.

The short high-energy bursts you see in the high frequencies at the beginning and ends of the signal are probably due to transients associated with the start and end of the recording.

I hope that clears things up.

**Comment by jjsgsk** [comment]
Yes it helps a lot! Thanks for your prompt and thorough response.
Just to make sure, it is an expected behavior when `fmax` goes past frequencies that were originally outside of the band limit which is decided by `sr`, is it?

So if I understand correctly, depends on the number of steps down, say `d`, the theoretical good choice of `fmax` would be the solution to `fmax * 2^(d/12) = sr/2`.

**Comment by bmcfee** [comment]
> Just to make sure, it is an expected behavior when `fmax` goes past frequencies that were originally outside of the band limit which is decided by `sr`, is it?

Yup!



> So if I understand correctly, depends on the number of steps down, say `d`, the theoretical good choice of `fmax` would be the solution to `fmax * 2^(d/12) = sr/2`.

Yeah, if your goal is to hide any high-frequency artifacts introduced by downshifting your signal.

**Comment by lostanlen** [comment]
Will close at the end of this week if there are no further comments to make

**Comment by mrgloom** [comment]
I wonder how ideal pitch shift should look like on spectrogram? should it look like only like scaling on frequency Y axis of spectrogram? Should it change range of Y axis of spectrogram? Should it change sampling rate or length of audio?

Here is original audio:
https://google.github.io/tacotron/publications/tacotron2/demos/romance_gt.wav

Example of pitch shift using ffmpeg:
```

ffmpeg -i ffmpeg_effect/romance_gt.wav

Input #0, wav, from 'ffmpeg_effect/romance_gt.wav':
  Duration: 00:00:01.36, bitrate: 384 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 24000 Hz, mono, s16, 384 kb/s

ffmpeg -i ffmpeg_effect/romance_gt.wav -af asetrate=24000*3/4,atempo=4/3 ffmpeg_effect/romance_gt_down.wav
ffmpeg -i ffmpeg_effect/romance_gt.wav -af atempo=3/4,asetrate=24000*4/3 ffmpeg_effect/romance_gt_up.wav

ffmpeg -i ffmpeg_effect/romance_gt_down.wav

Input #0, wav, from 'ffmpeg_effect/romance_gt_down.wav':
  Metadata:
    encoder         : Lavf58.20.100
  Duration: 00:00:01.38, bitrate: 288 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 18000 Hz, mono, s16, 288 kb/s


ffmpeg -i ffmpeg_effect/romance_gt_up.wav

Input #0, wav, from 'ffmpeg_effect/romance_gt_up.wav':
  Metadata:
    encoder         : Lavf58.20.100
  Duration: 00:00:01.34, bitrate: 512 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 32000 Hz, mono, s16, 512 kb/s
```

ffmpeg changes sampling rate and length of audio and Y range of spectrogram.

Spectrogram for romance_gt.wav: 
![romance_gt_spectrogram](https://user-images.githubusercontent.com/4003908/58995254-1d9f5380-87fc-11e9-8af9-c83be16331e5.png)

Spectrogram for romance_gt_down.wav: 
![romance_gt_down_spectrogram](https://user-images.githubusercontent.com/4003908/58995286-4889a780-87fc-11e9-82d3-e8f62bdbbf92.png)

Spectrogram for romance_gt_up: 
![romance_gt_up_spectrogram](https://user-images.githubusercontent.com/4003908/58995294-52aba600-87fc-11e9-8758-9ccff9b0cee7.png)


Here is example using librosa:
```
import os
import argparse

import librosa

def apply_pitch_shift(input_wav_filepath):
    shift_list = [-4,-2,2,4]
    for shift in shift_list:
        y, sr = librosa.load(input_wav_filepath)
        y_new = librosa.effects.pitch_shift(y, sr, n_steps=shift, bins_per_octave=12)
        filepath = os.path.splitext(input_wav_filepath)[0]+'_'+str(shift)+'.wav'
        librosa.output.write_wav(filepath, y_new, sr)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('input_wav_filepath')
    args = parser.parse_args()

    apply_pitch_shift(args.input_wav_filepath)
```

I can see that Y range is changing to 11kHz, is it desired effect? Also with `-4` parameter seems something strange on right top corner.

romance_gt_spectrogram.png
![romance_gt_spectrogram](https://user-images.githubusercontent.com/4003908/58995685-e29e1f80-87fd-11e9-87a9-62f6f2f3eb1a.png)

romance_gt_2_spectrogram.png
![romance_gt_2_spectrogram](https://user-images.githubusercontent.com/4003908/58995700-f053a500-87fd-11e9-9290-a87e730db7f0.png)

romance_gt_4_spectrogram.png
![romance_gt_4_spectrogram](https://user-images.githubusercontent.com/4003908/58995710-fba6d080-87fd-11e9-8fd0-3d8c9deb1fe2.png)

romance_gt_-2_spectrogram.png
![romance_gt_-2_spectrogram](https://user-images.githubusercontent.com/4003908/58995720-05c8cf00-87fe-11e9-8306-dd1cc757332a.png)

romance_gt_-4_spectrogram.png
![romance_gt_-4_spectrogram](https://user-images.githubusercontent.com/4003908/58995731-124d2780-87fe-11e9-9a5c-44472ec18d9d.png)

Here is an example using rubberband:

```
import os
import argparse
import librosa

import soundfile as sf
import pyrubberband as pyrb

def apply_pitch_shift(input_wav_filepath):
    shift_list = [-4,-2,2,4]
    for shift in shift_list:
        y, sr = sf.read(input_wav_filepath)
        y_shift = pyrb.pitch_shift(y, sr, shift)
        filepath = os.path.splitext(input_wav_filepath)[0]+'_'+str(shift)+'.wav'
        librosa.output.write_wav(filepath, y_shift, sr)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('input_wav_filepath')
    args = parser.parse_args()

    apply_pitch_shift(args.input_wav_filepath)
```

romance_gt_spectrogram.png
![romance_gt_spectrogram](https://user-images.githubusercontent.com/4003908/58995921-c353c200-87fe-11e9-83d2-9b9393e9db25.png)

romance_gt_2_spectrogram.png
![romance_gt_2_spectrogram](https://user-images.githubusercontent.com/4003908/58995934-cd75c080-87fe-11e9-857b-b55b43cd4441.png)

romance_gt_4_spectrogram.png
![romance_gt_4_spectrogram](https://user-images.githubusercontent.com/4003908/58995938-d36ba180-87fe-11e9-8cf0-4c1c71ba809e.png)

romance_gt_-2_spectrogram.png
![romance_gt_-2_spectrogram](https://user-images.githubusercontent.com/4003908/58995961-e9796200-87fe-11e9-969b-7175a30cd66c.png)

romance_gt_-4_spectrogram.png
![romance_gt_-4_spectrogram](https://user-images.githubusercontent.com/4003908/58995965-ee3e1600-87fe-11e9-8c02-3210fab3e665.png)

**Comment by bmcfee** [comment]
> I wonder how ideal pitch shift should look like on spectrogram? should it look like only like scaling on frequency Y axis of spectrogram? 

To a first approximation, yes, but it's more complex than that (pun intended) due to phase.  The librosa phase vocoder is extremely naive, and does nothing special to preserve transients.  Rubberband does a much better job of this, as you can see in the last set of examples.

> Should it change range of Y axis of spectrogram? 

The Y axis of the spectrogram depends on the sampling rate and frame length of your analysis, and does not depend on the input signal.

> Should it change sampling rate or length of audio?

Typically these things will change during the process, but the output of the pitch shift should preserve the signal length and sampling rate.  This is handled automatically by the `librosa.effects` wrapper function, as well as the `pyrubberband` interface.
