### ISSUE TITLE
"write_wav" generates files in double size

### ISSUE THREAD

**Issue by ahmed-fau** [librosa/librosa#866]
Hi,

I would like to know what is the reason for writing wav files in double size with "librosa.output.write_wav".

example:

`
x, _= librosa.load('test_input.wav',sr=16000)
librosa.output.write_wav("test_output.wav",xx,sr=16000 )
`

size of _test_input.wav_: 2.1 MB
size of _test_output.wav_: 4.1 MB

I am working on a Linux Debian machine with python 3.6 and librosa version 0.6.3

Thanks in advance

**Comment by bmcfee** [comment]
It's probably saving as float32 rather than int16.  If you want more control over bit depth, I suggest using `soundfile` instead.

**Comment by ahmed-fau** [comment]
Thanks, I have just read this answer after reading some other issues. "soundfile" indeed keeps the file size unchanged. Sorry for spamming.
