### ISSUE TITLE
librosa.sequence.dtw(C=C, subseq=True) fails with "AttributeError: 'NoneType' object has no attribute 'shape'"

### ISSUE THREAD

**Issue by viktorAndreevichMorozov** [librosa/librosa#869]
#### Description

librosa.sequence.dtw(C=C, subseq=True) fails with "AttributeError: 'NoneType' object has no attribute 'shape'"

#### Steps/Code to Reproduce

```python
import librosa.sequence
import scipy.spatial.distance
C = scipy.spatial.distance.cdist([[1, 2], [3, 4]], [[5, 6], [1, 2], [3, 4], [7, 8]])
costs, path = librosa.sequence.dtw(C=C, subseq=True)
print(path)
```

#### Expected Results
```
[[1 2]
 [0 1]]
```
#### Actual Results
```
Traceback (most recent call last):
  File "issue.py", line 4, in <module>
    costs, path = librosa.sequence.dtw(C=C, subseq=True)
  File "/home/viktor/p/librosa/librosa/sequence.py", line 229, in dtw
    if subseq and (X.shape[1] > Y.shape[1]):
AttributeError: 'NoneType' object has no attribute 'shape'
```
#### Versions

Linux-4.15.0-47-generic-x86_64-with-Ubuntu-18.04-bionic
Python 3.7.1 (default, Oct 22 2018, 11:21:55) 
[GCC 8.2.0]
NumPy 1.16.3
SciPy 1.2.1
librosa 0.6.3

**Comment by lostanlen** [comment]
@viktorAndreevichMorozov hi! thanks for reporting. it seems like that you already wrote a patch to fix this? 
https://github.com/viktorAndreevichMorozov/librosa/commit/d49ebf5e585173af6ffb641296dd9dff081e149a
how is it working for you?
