### ISSUE TITLE
RFC: drop reviewable?

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#873]
It seems like people are using a mixture of github review comments and reviewable for feedback.  This can get a little confusing to wrangle.

For my $2e-2, github review comments are still a bit lacking in functionality compared to reviewable, but this appears to be the way the wind is blowing.

Should we remove reviewable?  Or do people not care?

**Comment by lostanlen** [comment]
I feel targeted ... :D 

I must say i've never really taken the time to learn how reviewable works. Whenever i use it, i just frantically fill in text boxes and click on buttons until i'm led to the last stage. On the other hand, i really like the simplicity of the GitHub review system: approve/comment/request changes.

So yes, i'd be in favor of dropping it, for simplicity and consistency.

Other thoughts?

**Comment by bmcfee** [comment]
> i feel targeted ... :D

Not at all!  I think most people ignore the reviewable link now that the github CR is more integrated with the flow.

> On the other hand, i really like the simplicity of the GitHub review system: approve/comment/request changes.

The plus for me with reviewable has always been the ability to thread comments / and approve or block on threads.  I guess github CR does this too, but it doesn't seem quite as natural to me.  But let's give it a shot.

**Comment by bmcfee** [comment]
Removed it for now, let's see how it goes.
