### ISSUE TITLE
Improve documentation on spectral features

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#874]
#### Description

Some of the spectral features have minimal documentation that doesn't really explain what the feature does.  (I'm looking at you, `spectral_contrast`!)

We should conduct a thorough audit of feature functions and expand documentation where possible.

**Comment by lostanlen** [comment]
Yes. Speaking of documentation, there are some subtle but annoying inconsistencies in the way docstrings are formatted. Some of these inconsistencies are relatively mundane (e.g. capitalization, punctuation, passive 3rd person vs. active 3rd person vs. imperative), while others are more serious (e.g. `n_fft` does not have the same definition across the same library: it is either referred to as an "FFT window length", a "number of bins to use", or a "number of samples per frame") 

 I would love to see an official standard on how we document our functions.

**Comment by bmcfee** [comment]
At one point (maybe around 0.4) I did a thorough audit of docstrings for content and style, but we're long overdue for another audit.

**Comment by bmcfee** [comment]
As a side note, we should also revise and expand the glossary section of the documentation.
