### ISSUE TITLE
create many processes when freeze script by pyinstaller

### ISSUE THREAD

**Issue by eezprince** [librosa/librosa#877]
#### Description
create many processes when freeze script by pyinstaller if librosa is imported.

I suspect that it is caused by some function doesn't do the freeze support like:
https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing

Does anyone has any idea?

#### Steps/Code to Reproduce
pip3 install pyinstaller

create a test.py file which context is:
import librosa
print("hello world")

#### Expected Results
result of "python3 test.py" is expected.

#### Actual Results
"pyinstaller test.py", "./dist/test/test" will create many processes, even if I added the hidden imports for the error.

#### Versions
Linux-4.15.0-1041-azure-x86_64-with-Ubuntu-16.04-xenial
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609]
NumPy 1.16.3
SciPy 1.2.1
librosa 0.6.3
pyinstaller 3.4

**Comment by bmcfee** [comment]
Sorry, but I don't understand the issue being reported.



> "pyinstaller test.py", "./dist/test/test" will create many processes, even if I added the hidden imports for the error.

What is "the error" here?  Can you post a log?

**Comment by bmcfee** [comment]
This sounds like a bug in pyinstaller, but without any concrete output to look through, it's impossible for me to tell.

**Comment by eezprince** [comment]
resolved, just do this link said. https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing
