### ISSUE TITLE
Missing figures in Documentation

### ISSUE THREAD

**Issue by AlexMetsai** [librosa/librosa#883]
I noticed that in the docs some figures are missing from the plotted examples. I don't know if this is a known issue, but these are:

In 'Temporal segmentation':
recurrence_matrix
recurrence_to_lag
lag_to_recurrence
timelag_filter
subsegment

In 'Sequential modeling':
viterbi_discriminative, both features/prediction_map and results figures

In Utilities:
sync
axis_sort
peak_pick

I saved the figures in case auto-generation is not possible. I'm uploading them if someone needs to add them manually. They're named appropriately. If github changes naming tell me so, I'll upload them elsewhere.

Edit: yes, github changed the filenames. I'm uploading a zip.

[figures.zip](https://github.com/librosa/librosa/files/3182403/figures.zip)

**Comment by bmcfee** [comment]
Thanks for documenting that -- I did know about it, but didn't bother making an issue yet because I was going to roll it into the general docstring audit for the 0.7 release.

**Comment by bmcfee** [comment]
I just did a local build, and everything seems to be working as expected.  This won't reflect on the website until I push up a new doc build (which takes several hours), but I think we can consider this fixed.
