### ISSUE TITLE
lr.load giving FileNotFoundError: [Errno 2] No such file or directory: 'avconv': 'avconv'

### ISSUE THREAD

**Issue by raghavrathi10** [librosa/librosa#886]
data_dir = '/Users/raghav/Desktop/FSU/summer_research'
audio_files = glob(data_dir + '/*.wav')
audio_files[0]

I can see that there the names of all the .wav files in the audio_files list but when I load the file i want using librosa 'audio, sfreq = lr.load(audio_files[0])' it is giving me file not found error. 

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-18-e1b9ecc43701> in <module>
----> 1 audio, sfreq = lr.load(audio_files[0])
      2 # time = np.arrange(0,len(audio))/sfreq

/usr/local/lib/python3.7/site-packages/librosa/core/audio.py in load(path, sr, mono, offset, duration, dtype, res_type)
    117 
    118     y = []
--> 119     with audioread.audio_open(os.path.realpath(path)) as input_file:
    120         sr_native = input_file.samplerate
    121         n_channels = input_file.channels

/usr/local/lib/python3.7/site-packages/audioread/__init__.py in audio_open(path, backends)
    105     """
    106     if backends is None:
--> 107         backends = available_backends()
    108 
    109     for BackendClass in backends:

/usr/local/lib/python3.7/site-packages/audioread/__init__.py in available_backends()
     84 
     85     # FFmpeg.
---> 86     if ffdec.available():
     87         result.append(ffdec.FFmpegAudioFile)
     88 

/usr/local/lib/python3.7/site-packages/audioread/ffdec.py in available()
    106         stdout=subprocess.PIPE,
    107         stderr=subprocess.PIPE,
--> 108         creationflags=PROC_FLAGS,
    109     )
    110     proc.wait()

/usr/local/lib/python3.7/site-packages/audioread/ffdec.py in popen_multiple(commands, command_args, *args, **kwargs)
     92         cmd = [command] + command_args
     93         try:
---> 94             return subprocess.Popen(cmd, *args, **kwargs)
     95         except OSError:
     96             if i == len(commands) - 1:

/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    773                                 c2pread, c2pwrite,
    774                                 errread, errwrite,
--> 775                                 restore_signals, start_new_session)
    776         except:
    777             # Cleanup if the child failed starting.

/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
   1520                         if errno_num == errno.ENOENT:
   1521                             err_msg += ': ' + repr(err_filename)
-> 1522                     raise child_exception_type(errno_num, err_msg, err_filename)
   1523                 raise child_exception_type(err_msg)
   1524 

FileNotFoundError: [Errno 2] No such file or directory: 'avconv': 'avconv'

**Comment by nervouna** [comment]
Same issue here.

**Comment by raghavrathi10** [comment]
> Same issue here.

https://stackoverflow.com/questions/56246836/librosa-load-file-not-found-error-on-loading-a-file
@nervouna  I found the solution. it is working for me now.

**Comment by raghavrathi10** [comment]
> Thanks for commenting @raghavrathi10
> 
> Just to clarify, this problem is upstream of librosa, and comes from the `audioread` package not having all of its dependencies satisfied.

@bmcfee Thank for the info. Its a really great tool.

**Comment by iver56** [comment]
Upgrading `audioread` to 2.1.8 fixed this issue for me
