### ISSUE TITLE
Window derivative in ifgram

### ISSUE THREAD

**Issue by scjs** [librosa/librosa#888]
#### Description

The window derivative `d_window` that is calculated in `ifgram()` is appropriate for the default Hann window, but not for other analysis windows.

#### Steps/Code to Reproduce

https://github.com/librosa/librosa/blob/65cbc8291cc265b93236b871727d2a4ec9cf3d06/librosa/core/spectrum.py#L469-L472

These lines in `librosa.core.ifgram()` create an array with the window derivative. They don't use the `window` argument to `ifgram()` to calculate the derivative, but they do produce the (negative) window derivative when the default Hann window is used:

```
import numpy as np

n_fft = 1024

freq_angular = np.linspace(0, 2 * np.pi, n_fft, endpoint=False) 
d_window = np.sin(-freq_angular) * np.pi / n_fft

np.allclose(d_window, -np.gradient(np.hanning(n_fft)), atol=2e-5)
# True
```

But the calculation for `d_window` doesn't lead to the derivative for other windows:

```
np.allclose(d_window, -np.gradient(np.blackman(n_fft)), atol=2e-5)
# False

import matplotlib.pyplot as plt

x = np.arange(n_fft)

plt.plot(x, d_window, c="black")
plt.scatter(x, -np.gradient(np.hanning(n_fft)), s=0.1, c="red")
plt.scatter(x, -np.gradient(np.blackman(n_fft)), s=0.1, c="blue")
plt.show()
```

`d_window` is used for `diff_stft` on these lines:

https://github.com/librosa/librosa/blob/65cbc8291cc265b93236b871727d2a4ec9cf3d06/librosa/core/spectrum.py#L479-L481

This is described in section 2 of the paper referenced in the docstring (Abe, Kobayashi, & Imai 1995), or equation 5.20 of Flandrin, Auger, & Chassande-Mottin (2002).

I might be misunderstanding, but I think that `d_window` should be using `np.gradient()` or another numerical derivative of the `window` argument. Flandrin et al. have an alternative calculation with MATLAB code for the window derivative in section 5.3.1.3 that might be better at the edges than `np.gradient()`.

#### Versions
```
Python 3.6.5
NumPy 1.14.5
SciPy 1.1.0
librosa 0.6.1
```

Abe, T., Kobayashi, T., & Imai, S. (1995). Harmonics tracking and pitch extraction based on instantaneous frequency. 1995 International Conference on Acoustics, Speech, and Signal Processing, 1, 756–759. https://doi.org/10.1109/ICASSP.1995.479804

Flandrin, P., Auger, F., & Chassande-Mottin, E. (2002). Time-Frequency reassignment: from principles to algorithms. In Applications in Time-Frequency Signal Processing (Vol. 10, pp. 179–204). CRC Press.

**Comment by bmcfee** [comment]
Thanks @scjs for the detailed report!

I'll admit to not having thought too deeply about this point, as the current implementation is a more-or-less direct translation of a previous matlab implementation.  I hadn't read Flandrin et al.'s article before, but in hindsight I agree with you.

For completeness in this PR, here's the output of your plot (slightly reformatted): 
![image](https://user-images.githubusercontent.com/1190540/58422443-9403bf00-8060-11e9-836a-77416de0bcf1.png)

It seems to me that the simplest fix, as you suggest, is to just replace `d_window = -np.gradient(fft_window)` here: 

https://github.com/librosa/librosa/blob/65cbc8291cc265b93236b871727d2a4ec9cf3d06/librosa/core/spectrum.py#L464-L472


> Flandrin et al. have an alternative calculation with MATLAB code for the window derivative in section 5.3.1.3 that might be better at the edges than `np.gradient()`.

Is that intended to help at the edges, or to smooth over sampling errors?  I'd be generally supportive of adding that, unless there's a simpler / better way to achieve the same effect.

Tagging related issues: #394 and potentially interested parties @dpwe @stefan-balke @lostanlen

**Comment by bmcfee** [comment]
A couple of quick notes about edge effects here.

The post above uses `np.hanning`, which is not exactly the same as the `hann` window used by default in librosa, as the latter operates with `fftbins=True` to create a periodic window when `n_fft` is even.  This is a minor point, but it becomes relevant when calculating window derivatives at the boundaries.

`np.gradient` does not have a clean way to handle periodic domains, and it does a bit of extrapolation magic at the edges to compute the nth-order differences.  Plotting the difference between the explicitly constructed sine window and the estimated window derivative (for hann) shows that the errors are entirely due to this effect:
![image](https://user-images.githubusercontent.com/1190540/58481314-258b3380-812a-11e9-9395-9feac292a1eb.png)

Rather than roll our own gradient calculator, we can force periodicity by using wrap padding before gradient calculation, and then slicing out:

```python
def cyclic_gradient(x, edge_order=1, axis=-1):
    
    padding = [(0, 0)] * x.ndim
    padding[axis] = (edge_order, edge_order)
    xpad = np.pad(x, padding, mode='wrap')
    
    grad = np.gradient(xpad, edge_order=edge_order, axis=axis)
    
    slices = [slice(None)] * x.ndim
    slices[axis] = slice(edge_order, -edge_order)
    return grad[tuple(slices)]
```

**Comment by bmcfee** [comment]
I have an implementation of this working locally, except that the regression tests fail for low frame lengths (256, 512).  This should be expected because the first-order difference becomes less accurate for smaller `n_fft`.

I suppose the question now is: how do we want to deal with that?  Should we just drop the small-n_fft cases from the regression tests?

**Comment by scjs** [comment]
Thanks for getting to this so quickly.

> Is that intended to help at the edges, or to smooth over sampling errors? I'd be generally supportive of adding that, unless there's a simpler / better way to achieve the same effect.

Ah, you might be right. I realized that I was actually looking at a different approximation of the window derivative (Fulop & Fitz 2006, page 366). The method in Fulop & Fitz 2006 looks to be better at the edges than `np.gradient()`. I thought it was similar to the method in Flandrin et al. 2002, since they mentioned that paper, but that's not the case.

This is the Python version of the window derivative calculation in Fulop & Fitz 2006:

```python
def window_derivative(window, scale=2 * np.pi):
    half_width = len(window) // 2
    
    if len(window) % 2:
        weights = np.arange(-half_width, half_width + 1)
    
    else:
        weights = np.arange(0.5 - half_width, half_width)

    weights = np.roll(weights, -half_width) / len(window)

    return -np.imag(np.fft.ifft(weights * np.fft.fft(window))) * scale
```

The function that you suggest looks like a good solution.

I guess that moving to the approximate gradient calculation is a regression, but I don't think there would be another way to support arbitrary window functions, and `ifgram()` currently returns incorrect results for those without this change. I'm using this for voice spectrum analysis with short windows, and Fulop 2011 (p. 132-135) argues that a Kaiser window is best for that purpose. I appreciate your help in fixing this!


Fulop, S. A., & Fitz, K. (2006). Algorithms for computing the time-corrected instantaneous frequency (reassigned) spectrogram, with applications. The Journal of the Acoustical Society of America, 119(1), 360. https://doi.org/10.1121/1.2133000

Fulop, S. A. (2011). The Reassigned Spectrogram. In S. A. Fulop, Speech Spectrum Analysis (pp. 127–165). https://doi.org/10.1007/978-3-642-17478-0_6

**Comment by bmcfee** [comment]
> I guess that moving to the approximate gradient calculation is a regression, but I don't think there would be another way to support arbitrary window functions, and `ifgram()` currently returns incorrect results for those without this change.

Agreed.  I would guess that anyone who really cares about precision here wouldn't be using a small frame anyway, so it's not a regression that's likely to matter in practice.

Otherwise, I think the fix is ready to merge, but a second set of eyeballs would be much appreciated.
