### ISSUE TITLE
Changing Gain and Sensitivity

### ISSUE THREAD

**Issue by ZER-0-NE** [librosa/librosa#893]
On changing the gain and sensitivity using Audacity, a free software, there are some cases where the spectrogram images for some .wav files show whale call (a particular kind of change in frequency) distinctly (as shown below) while for others it does not. Is there a way that in a similar way like audacity, we can change the gain and sensitivity of the audio file using librosa?

- Whale call:
<img width="1450" alt="w" src="https://user-images.githubusercontent.com/19359908/58760976-61742d80-855c-11e9-8f34-ba964e5377e9.png">

- Non-whale call: 
<img width="1478" alt="nw" src="https://user-images.githubusercontent.com/19359908/58760980-6507b480-855c-11e9-934c-53c5a3ae54e9.png">

I'm attaching some images to show how the changes in Gain and Sensitivity have allowed the whale call to be displayed rather distinctly.
 
<img width="1471" alt="5" src="https://user-images.githubusercontent.com/19359908/58760864-4c4acf00-855b-11e9-8f02-45ba79e9f67e.png">

<img width="1430" alt="2" src="https://user-images.githubusercontent.com/19359908/58760865-4d7bfc00-855b-11e9-9bbb-78b81653d286.png">

<img width="1466" alt="3" src="https://user-images.githubusercontent.com/19359908/58760867-51a81980-855b-11e9-9236-e628b6556f1b.png">

<img width="1478" alt="4" src="https://user-images.githubusercontent.com/19359908/58760868-553ba080-855b-11e9-89e9-7343ed72b014.png">

<img width="1486" alt="1" src="https://user-images.githubusercontent.com/19359908/58760898-b5cadd80-855b-11e9-995e-c2123bdaec9c.png">

**Comment by bmcfee** [comment]
>  Is there a way that in a similar way like audacity, we can change the gain and sensitivity of the audio file using librosa?

You might want to look into the docs for [`amplitude_to_db`](https://librosa.github.io/librosa/generated/librosa.core.amplitude_to_db.html?highlight=amplitude_to_db#librosa.core.amplitude_to_db), and specifically the `top_db` parameter.
