### ISSUE TITLE
Is there an efficient way to split audio files into fixed size chunks using librosa?

### ISSUE THREAD

**Issue by ZER-0-NE** [librosa/librosa#897]

**Comment by lostanlen** [comment]
yes! see `librosa.stream` which was added last month: 
https://github.com/librosa/librosa/pull/872

you'll have to install the latest unreleased version of librosa to use it. It will be included in librosa 0.7.0

If all you want is some I/O, and not loading these waveforms into numpy arrays, you should checkout pysox, which does the bulk of audio trimming and import/export for you:
https://github.com/rabitt/pysox
