### ISSUE TITLE
Features for replicating HTK: pre-emphasis and liftering

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#902]
#### Description
In looking at #804, I noticed that HTK's implementation of MFCCs has a few steps that we don't currently implement, notably pre-emphasis and liftering.  These would be easy to add, but it's worth considering how exactly to structure the API.

Liftering I think makes the most sense as an optional parameter to `feature.mfcc`, which could be 0 by default.

Pre-emphasis is a little thornier from the API perspective.  HTK seems to implement this inside the STFT (eg as a window function), but I could see arguments for doing it as an effect (in the time domain) or as a feature enhancement (in the spectral domain).  The effect view keeps the API relatively simple: load, pre-emph, feature-extract.  But maybe there are good arguments for doing it in the spectral domain?

**Comment by lostanlen** [comment]
Related to #573 and #682

**Comment by bmcfee** [comment]
Gave this a bit more thought, and I think pre-emphasis should be implemented in `effects` and operate on the time-domain signal.

My reasoning here is as follows:

1. pre-emph is implemented by a very small convolutional filter, and is efficient to implement.  Spectrogram-based pre-emphasis would be relatively inefficient. 
2. conceptually, it's a signal transformation (effect) not a derived feature.  There's no obvious place in the library for spectral effects; `decompose` is the closest we have, but this effect is not a decomposition.

So the proposed changes for this issue should be:

- `librosa.effects.preemphasis(y, coef=0.97)`: with `0 < coef < 1` is the pre-emphasis coefficient: `y -> y * [1, -coef]`
- `librosa.feature.mfcc(..., lifter=0)`: where the new parameter `lifter >= 0` has the effect: `m[i, :] -> m[i, :] * (1 + lifter / 2 * sin(pi * i / lifter)`
