### ISSUE TITLE
ERROR: Cannot uninstall 'joblib'

### ISSUE THREAD

**Issue by KafeelBasha** [librosa/librosa#905]
Hello

Tried installing librosa using pip and conda installation by referring the documentation but getting below error.

ERROR: Cannot uninstall 'joblib'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

Any suggestion will be helpful.

**Comment by lostanlen** [comment]
Hello, please see: 
https://github.com/blockstack/blockstack-core/issues/504
and
https://github.com/pypa/pip/issues/5247

**Comment by KafeelBasha** [comment]
Thanks. Uninstalled joblib using below command then installed librosa

`pip install --ignore-installed joblib`
