### ISSUE TITLE
Phase vocoder doc should point to pyrubberband

### ISSUE THREAD

**Issue by lostanlen** [librosa/librosa#906]
#### Description
As evidenced by #900, it's difficult for users to realize that librosa's built-in vocoder is extremely basic, and is primarily intended as a reference implementation for educational purposes. In all cases, the rubberband library returns an audio input of better quality. Rubberband also support variable-rate phase vocoding (#517).

@bmcfee himself has written a Python wrapper for rubberband, named pyrubberband (pyrb). Perhaps we can write a blurb in the docstrings of `librosa.effects` to advertise for pyrubberband?

#### Versions
librosa 0.6.3

**Comment by bmcfee** [comment]
Good thinking -- I'll roll this into the release PR for 0.7.
