### ISSUE TITLE
An error occurred, when librosa.resample() with the return value of the sf.read().

### ISSUE THREAD

**Issue by bs111** [librosa/librosa#915]
#### Description
An error occurred, when resamping with the return value of the sf.read() function.
what's different, between  librosa.load()  and sf.read().
how can i get it work, when read RAW file.

#### Steps/Code to Reproduce
I have two sound documents with similar parameters,Need to re-sampling. 
One is in wav format and the other is in pure raw format.

The raw format cannot be loaded using librosa.load().
Then changed to soundfile.read () read, but when  call librosa.resample(), got an error.

I have attached the relevant attachments and documentation. Please help with the science...
I check the pcm file ,it can be replayed in AdobeAudition.
![code](https://user-images.githubusercontent.com/38519076/60718374-12ecf100-9f57-11e9-93c4-464c250b4366.PNG)

Here are the relevant documents.    [HaveException.zip](https://github.com/librosa/librosa/files/3362437/HaveException.zip)

# Content
```python
import librosa                     #librosa                0.6.3
import librosa.display
import matplotlib.pyplot as plt    #matplotlib             3.1.0
import numpy as np                 #numpy                  1.16.2
import soundfile as sf             #PySoundFile            0.9.0.post1

showPictures=True

sourceFileName ="chineseRecord2Stereo.wav"
destFileName="16bitMono16K.wav"
DATA, SR = librosa.load(sourceFileName,sr=48000,mono=False,dtype=np.float32)
# work fine.

sourceFileName = 'Call_streamout.pcm.0.AudioALSAStreamOut.pid400.tid8131_48K2Stero32PCM.pcm'
destFileName="16bitMono16K.wav"
DATA,SR = sf.read(sourceFileName, channels=2, samplerate=48000,dtype=np.float32,
                               subtype='PCM_32',format="RAW",endian='LITTLE')
# work failed

DATA_16k = librosa.resample(DATA,SR,16000)
DATA_16k_mono=librosa.to_mono(DATA_16k)
sf.write(destFileName, DATA_16k_mono, 16000, subtype='PCM_16')
```

#### Expected Results
No Error

#### Actual Results
Error
ValueError: Input signal length=2 is too small to resample from 48000->16000

#### Versions
>>> import platform; print(platform.platform())
Windows-10-10.0.18362-SP0
>>> import sys; print("Python", sys.version)
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.16.2
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.3.0
>>> import librosa; print("librosa", librosa.__version__)
librosa 0.6.3
>>>

**Comment by bmcfee** [comment]
`soundfile` returns the audio buffer transposed from how `librosa` expects it to be shaped, so librosa.resample thinks the channels axis (2, left and right) is the time axis and vice versa.

Transposing the data after loading in `soundfile` should fix it:



> DATA,SR = sf.read(sourceFileName, channels=2, samplerate=48000,dtype=np.float32,
> subtype='PCM_32',format="RAW",endian='LITTLE')

```python
>>> DATA,SR = sf.read(sourceFileName, channels=2, samplerate=48000,dtype=np.float32,
...                     subtype='PCM_32',format="RAW",endian='LITTLE')
>>> DATA = DATA.T
>>> # continue as before
```

Note that in librosa 0.6.3, the backend audio decoder is `audioread`, but in 0.7 we switch over to `soundfile` (at least for this format).  You might want to try the 0.7.0rc1 release, where you shouldn't have to talk to soundfile directly and librosa.load should work as expected.

**Comment by bs111** [comment]
I add the DATA = DATA.T  after Data read it from sf.read().
I can save the audio ,it works. Thanks.

but ，at the librosa.display.waveplot() ,it faild.I have to comment it out.

![1](https://user-images.githubusercontent.com/38519076/60750731-97835200-9fdf-11e9-9442-6bc3538af848.PNG)

otherwise,Have a Exception->ParameterError
Traceback (most recent call last):
  File "G:/MyPython/Studty/63多媒体_声音边界检测/webrtcvad-new/HaveException.py", line 35, in <module>
    librosa.display.waveplot(DATA, 48000) 
  File "D:\Python36\lib\site-packages\librosa\display.py", line 460, in waveplot
    y = np.vstack([__envelope(_, hop_length) for _ in y])
  File "D:\Python36\lib\site-packages\librosa\display.py", line 460, in <listcomp>
    y = np.vstack([__envelope(_, hop_length) for _ in y])
  File "D:\Python36\lib\site-packages\librosa\display.py", line 354, in __envelope
    return util.frame(x, hop_length=hop, frame_length=hop).max(axis=0)
  File "D:\Python36\lib\site-packages\librosa\util\utils.py", line 98, in frame
    raise ParameterError('Input buffer must be contiguous.')
librosa.util.exceptions.ParameterError: Input buffer must be contiguous.

**Comment by bmcfee** [comment]
>  librosa.util.exceptions.ParameterError: Input buffer must be contiguous.

The last line here tells you what the problem is.  When you transpose an audio buffer out of soundread, its in-memory layout does not change, so samples from the left and right channels are interleaved -- in other words, the channels are not contiguous.  Certain functions in librosa require channel contiguity to avoid extra memory copies, which is why you're seeing the error.

You can force contiguity on a buffer by saying `DATA = np.ascontiguousarray(DATA)`.

**Comment by bs111** [comment]
OK ,Thanks very much.

**Comment by Vladislav2018** [comment]
Hi everyone! I have this problem too.

Сertain files are successfully resampled, but others: for some reason not.

My metthod: 

`
def downsample_mono(path, sr):
    obj = wavio.read(path)
    wav = obj.data.astype(np.float32, order='F')
    rate = obj.rate
    try:
        tmp = wav.shape[1]
        wav = to_mono(wav.T)
    except:
        pass
    try:
        wav = resample(wav, rate, sr)
#here I get the error and I don't know what to do with it
    except ValueError:
        pass
    wav = wav.astype(np.int16)
    return sr, wav
`
This is my stacktrace:

`
Traceback (most recent call last):
  File "D:\prog\PyCharm Community Edition 2020.2.2\plugins\python-ce\helpers\pydev\pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\prog\PyCharm Community Edition 2020.2.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/prog/Audio-Classification-master/Audio-Classification-master/clean.py", line 192, in <module>
    split_wavs(args)
  File "D:/prog/Audio-Classification-master/Audio-Classification-master/clean.py", line 130, in split_wavs
    rate, wav = downsample_mono(src_fn, args.sr)
  File "D:/prog/Audio-Classification-master/Audio-Classification-master/clean.py", line 96, in downsample_mono
    wav = resample(wav, rate, sr)
  File "D:\prog\datascience\anaconda\lib\site-packages\librosa\core\audio.py", line 584, in resample
    y_hat = resampy.resample(y, orig_sr, target_sr, filter=res_type, axis=-1)
  File "D:\prog\datascience\anaconda\lib\site-packages\resampy\core.py", line 97, in resample
    raise ValueError('Input signal length={} is too small to '
ValueError: Input signal length=1 is too small to resample from 81920->16000
`

![This is a debug information of normal file that resamples successfully](https://user-images.githubusercontent.com/35165941/98393836-eb39fb80-206a-11eb-88e6-2480e831acd9.png)


![This is a debug information of problem file](https://user-images.githubusercontent.com/35165941/98393628-9bf3cb00-206a-11eb-84f9-0d4ed8349f5e.png)

What's wrong with this file?

**Comment by lostanlen** [comment]
Hello @Vladislav2018, from your screenshots it sounds like your array is a 409600x1 matrix and needs to be raveled into a vector
https://numpy.org/doc/stable/reference/generated/numpy.ravel.html

**Comment by bmcfee** [comment]
> matrix and needs to be raveled into a vector

or you could transpose it.  Resample, like all librosa functions, wants the time-like index to trail and not lead.

**Comment by applepieiris** [comment]
> `soundfile` returns the audio buffer transposed from how `librosa` expects it to be shaped, so librosa.resample thinks the channels axis (2, left and right) is the time axis and vice versa.
> 
> Transposing the data after loading in `soundfile` should fix it:
> 
> > DATA,SR = sf.read(sourceFileName, channels=2, samplerate=48000,dtype=np.float32,
> > subtype='PCM_32',format="RAW",endian='LITTLE')
> 
> ```python
> >>> DATA,SR = sf.read(sourceFileName, channels=2, samplerate=48000,dtype=np.float32,
> ...                     subtype='PCM_32',format="RAW",endian='LITTLE')
> >>> DATA = DATA.T
> >>> # continue as before
> ```
> 
> Note that in librosa 0.6.3, the backend audio decoder is `audioread`, but in 0.7 we switch over to `soundfile` (at least for this format). You might want to try the 0.7.0rc1 release, where you shouldn't have to talk to soundfile directly and librosa.load should work as expected.

If i want to rewrite the audio ndarry into .wav file. Should i need to transpose the result of `resample() function`?
`
import librosa                     #librosa                0.6.3
import librosa.display
import matplotlib.pyplot as plt    #matplotlib             3.1.0
import numpy as np                 #numpy                  1.16.2
import soundfile as sf             #PySoundFile            0.9.0.post1

showPictures=True

sourceFileName ="chineseRecord2Stereo.wav"
destFileName="16bitMono16K.wav"
DATA, SR = librosa.load(sourceFileName,sr=48000,mono=False,dtype=np.float32)


sourceFileName = 'Call_streamout.pcm.0.AudioALSAStreamOut.pid400.tid8131_48K2Stero32PCM.pcm'
destFileName="16bitMono16K.wav"
DATA,SR = sf.read(sourceFileName, channels=2, samplerate=48000,dtype=np.float32,
                               subtype='PCM_32',format="RAW",endian='LITTLE')

DATA = DATA.T

DATA_16k = librosa.resample(DATA,SR,16000)


DATA_16k = DATA_16K.T

sf.write(destFileName, DATA_16k, 16000, subtype='PCM_16')
`

**Comment by bmcfee** [comment]
> If i want to rewrite the audio ndarry into .wav file. Should i need to transpose the result of `resample() function`?

Yes probably.  Consult the soundfile documentation to see what exactly it expects.
