### ISSUE TITLE
Deprecate the output module?

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#917]
#### Description

The output module has three functions: 

- `annotation`
- `times_csv`
- `write_wav`

`write_wav` is now entirely redundant since we depend on `soundfile`.

The first two are convenience wrappers for saving (labeled) intervals and (labeled) events, respectively.  While these can be handy, they're also extremely limited, and redundant with other more robust output utilities (pandas, jams, etc).  Notably, they provide no means for encoding additional metadata, and for that reason I think their use should be discouraged.

What do folks think about deprecating this module entirely in 0.7 and removing it in 0.8?

**Comment by bmcfee** [comment]
As an alternate, we could for now just deprecate `write_wav` and punt the annotation deprecations til much later, since the docs/tutorials/example scripts rely on them.

**Comment by lostanlen** [comment]
Yes. I suspect that write_wav appears much more frequently among user-end code than annotation or times_csv

**Comment by bmcfee** [comment]
> Yes. I suspect that write_wav appears much more frequently among user-end code than annotation or times_csv

I'm sure that's the case, which is part of why I think it makes sense to deprecate the whole module.  What do you think?

**Comment by lostanlen** [comment]
Sure. The annoying thing is that this implies that running some of our examples in doc will print some deprecation warning messages. But that's always something we can did in 0.7.1. So yes, deprecating the whole module seems the best to me

**Comment by k3ybladewielder** [comment]
With write_wav deprecated, how will the numpy array be saved as a wav file?

**Comment by coco12315** [comment]
> punt

I have the same question

**Comment by k3ybladewielder** [comment]
@bmcfee thanks
