### ISSUE TITLE
C/C++ implementation for melspectrogram function in librosa

### ISSUE THREAD

**Issue by rameshkunasi** [librosa/librosa#921]
Hi,

I want to use melspectrogram function from librosa. But I want to use C/C++ version. If anyone has the C/C++ version of librosa function proved me, otherwise let me know how to implement melspectrogram function in C/C++.

Thanks

**Comment by lostanlen** [comment]
Hi @rameshkunasi. We recommend that you use the Essentia library, from our colleagues at the Music Technology Group in Barcelona.

source code: https://github.com/MTG/essentia

documentation: https://essentia.upf.edu/documentation/reference/std_MelBands.html

**Comment by JanSo19** [comment]
@lostanlen I'm sorry if I open up this question again, but I just want to make something sure.
Are the results from librosa.feature.mfcc similar to the MelBands from essentia?

I'm using librosa.feature.mfcc in python to train a trigger-word detector (CNN1D/LSTM) and want to use the model in Android. 
I therefore need a library that is really compatible with librosa.feature.mfcc (very similar-looking mfccs). 

As there is such a wide variety of mfcc-implementations I wanted to be sure about their compatibility. And I apologize if the question was already answered, I don't want to waste your time :)

**Comment by kcoul** [comment]
For anyone else coming across this issue, you can also try this: https://github.com/ewan-xu/LibrosaCpp
