### ISSUE TITLE
Leaked semaphores

### ISSUE THREAD

**Issue by PetrochukM** [librosa/librosa#924]
#### Description

Importing `librosa` causes semaphores to leak.

#### Steps/Code to Reproduce

```python
import multiprocessing as mp

import librosa


def w():
    pass


def main():
    ps = [mp.get_context('spawn').Process(target=w) for _ in range(4)]
    for p in ps:
        p.daemon = True
        p.start()
    for p in ps:
        p.join()


if __name__ == '__main__':
    p = mp.get_context('spawn').Process(target=main)
    p.start()
    p.join()
```

#### Expected Results

```bash
$ python3 blah.py
/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
$
```

#### Actual Results

```bash
$ python3 blah.py
$
```

#### Versions

```python
>>> import platform; print(platform.platform())
Darwin-18.6.0-x86_64-i386-64bit
>>> import sys; print("Python", sys.version)
Python 3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.16.3
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.2.1
>>> import librosa; print("librosa", librosa.__version__)
librosa 0.6.3
>>> 
```

**Comment by PetrochukM** [comment]
This issue is a follow up from: https://github.com/pytorch/pytorch/issues/23117

**Comment by PetrochukM** [comment]
That said, I think this is coming from `numba` and not `librosa`. `librosa` doesn't have any `multiprocessing` or `threading` dependencies.

**Comment by bmcfee** [comment]
It's also possible, though unlikely, that it came in through joblib, which we use in the cache module.

**Comment by PetrochukM** [comment]
@bmcfee For some of these upstream dependencies, it may be useful to incorporate lazy loading.

Example:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/util/lazy_loader.py

Then, if the module is not used, then it won't be imported. This would solve the basic use case of starting a process that has nothing to do with `librosa`.

**Comment by bmcfee** [comment]
That's true, but you also wouldn't have discovered the problem. I generally think it's better to avoid lazy imports unless there's a very strong and specific reason to use them -- pyplot with import-time backend activation is the only compelling case I can think of in our current dependencies.
