### ISSUE TITLE
ImportError: cannot import name 'lombscargle'

### ISSUE THREAD

**Issue by nikigre** [librosa/librosa#927]
Hello!
I installed Librosa using sudo pip3 install librosa.
I get this:
```
Requirement already satisfied: librosa in /home/nikigre/.local/lib/python3.6/site-packages
Requirement already satisfied: audioread>=2.0.0 in /home/nikigre/.local/lib/python3.6/site-packages (from librosa)
Requirement already satisfied: numpy>=1.8.0 in /home/nikigre/.local/lib/python3.6/site-packages (from librosa)
Requirement already satisfied: six>=1.3 in /home/nikigre/.local/lib/python3.6/site-packages (from librosa)
Requirement already satisfied: decorator>=3.0.0 in /home/nikigre/.local/lib/python3.6/site-packages (from librosa)
Requirement already satisfied: joblib>=0.7.0 in /home/nikigre/.local/lib/python3.6/site-packages (from librosa)
Requirement already satisfied: scipy>=0.13.0 in /home/nikigre/.local/lib/python3.6/site-packages (from librosa)
Requirement already satisfied: scikit-learn>=0.14.0 in /home/nikigre/.local/lib/python3.6/site-packages (from librosa)
Requirement already satisfied: resampy>=0.1.2 in /home/nikigre/.local/lib/python3.6/site-packages (from librosa)
Requirement already satisfied: numba>=0.32 in /home/nikigre/.local/lib/python3.6/site-packages (from resampy>=0.1.2->librosa)
Requirement already satisfied: llvmlite>=0.29.0 in /home/nikigre/.local/lib/python3.6/site-packages (from numba>=0.32->resampy>=0.1.2->librosa)
```
But when I try using it in deepvoice3_pytorch, I get this [error](https://github.com/r9y9/deepvoice3_pytorch/issues/167).

```
Python 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform; print(platform.platform())
Linux-4.4.0-17763-Microsoft-x86_64-with-Ubuntu-18.04-bionic
>>> import sys; print("Python", sys.version)
Python 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.16.4
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.3.0
>>> import librosa; print("librosa", librosa.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nikigre/.local/lib/python3.6/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/home/nikigre/.local/lib/python3.6/site-packages/librosa/core/__init__.py", line 109, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "/home/nikigre/.local/lib/python3.6/site-packages/librosa/core/audio.py", line 10, in <module>
    import scipy.signal
  File "/home/nikigre/.local/lib/python3.6/site-packages/scipy/signal/__init__.py", line 305, in <module>
    from .spectral import *
  File "/home/nikigre/.local/lib/python3.6/site-packages/scipy/signal/spectral.py", line 10, in <module>
    from ._spectral import lombscargle
ImportError: cannot import name 'lombscargle'
```
I tried `sudo pip3 install lombscargle` But it does not exists (`requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/lombscargle/`)
How can I repair this?
Thank you!

**Comment by lostanlen** [comment]
That's quite strange. I can't reproduce the problem on my machine. Python 3.7 on a Darwin OS.

```python
Python 3.7.3 (default, Mar 27 2019, 16:54:48)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform; print(platform.platform())
Darwin-18.6.0-x86_64-i386-64bit
>>> import sys; print("Python", sys.version)
Python 3.7.3 (default, Mar 27 2019, 16:54:48)
[Clang 4.0.1 (tags/RELEASE_401/final)]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.16.4
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.3.0
>>> import librosa; print("librosa", librosa.__version__)
librosa 0.7.0
```

The crux problem seems to lie at `import scipy.signal`. Can you re-run Python and just type this command: `import scipy.signal`, see if the error still happens?

`lombscargle` is not a module but a function within the `scipy.signal.spectral` module. It's been there since at least 2012 or 2013 (scipy v0.13), if not earlier.
https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.lombscargle.html

**Comment by nikigre** [comment]
Hi!
I got the same error:
Python 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy.signal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File
"/home/nikigre/.local/lib/python3.6/site-packages/scipy/signal/__init__.py",
line 305, in <module>
    from .spectral import *
  File
"/home/nikigre/.local/lib/python3.6/site-packages/scipy/signal/spectral.py",
line 10, in <module>
    from ._spectral import lombscargle
ImportError: cannot import name 'lombscargle'
Lep pozdrav
Nik Grebovšek


V V sre., 24. jul. 2019 ob 13:31 je oseba Vincent Lostanlen <
notifications@github.com> napisala:

**Comment by lostanlen** [comment]
OK. In a sense, that's good. It means that the issue is circumscribed to an installation problem of `scipy`. Perhaps you began installing it via `pip` and aborted the installation procedure while it was linking modules together. My suggestion is to uninstall `scipy` and re-install it from scratch.

Worse comes to worse, install miniconda3, create an environment, and install librosa with `conda install -c conda-forge librosa`.

**Comment by nikigre** [comment]
Okay. I reinstalled it. And it looks like it works now.
```
Python 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import librosa; print("librosa", librosa.__version__)
librosa 0.5.1
```
Now the error I get is this:
```
Traceback (most recent call last):
  File "train.py", line 10, in <module>
    from datasets.datafeeder import DataFeeder
  File "/mnt/d/tacotron-master/datasets/datafeeder.py", line 8, in <module>
    from text import cmudict, text_to_sequence
ImportError: cannot import name 'text_to_sequence'
```
But this error is probably not connected to Librosa.
Thank you for quick help!

**Comment by bmcfee** [comment]
> But this error is probably not connected to Librosa.
> Thank you for quick help!

I'm glad it's working now!



> >>> import librosa; print("librosa", librosa.__version__)
> librosa 0.5.1

That version is several years out of date now, but upgrading to 0.7 should work fine if your dependency chain is settled now.
