### ISSUE TITLE
lil_matrix construction raises FutureWarning (numpy #12609)

### ISSUE THREAD

**Issue by lostanlen** [librosa/librosa#935]
#### Description
Constructing a `scipy.sparse.lil_matrix` in `sparsify_rows` raises a Lil Warnin'*

```
/Users/vl238/miniconda3/envs/gl/lib/python3.7/site-packages/scipy/sparse/lil.py:504: FutureWarning: future versions will not create a writeable array from broadcast_array. Set the writable flag explicitly to avoid this warning.
  if not i.flags.writeable or i.dtype not in (np.int32, np.int64):
```

Dependency chain:

* call site in `sparsify_rows`: 
https://github.com/librosa/librosa/blob/master/librosa/util/utils.py#L1087

* `lil_matrix` (linked list sparse matrix) class:
https://github.com/scipy/scipy/blob/master/scipy/sparse/lil.py#L23

* warning point in `scipy.sparse._prepare_index_for_memoryview`:
https://github.com/scipy/scipy/blob/master/scipy/sparse/lil.py#L504

* scipy PR https://github.com/scipy/scipy/pull/10379

* scipy issue https://github.com/scipy/scipy/issues/10405 

* numpy PR https://github.com/numpy/numpy/pull/12609

* numpy issue https://github.com/numpy/numpy/pull/2705

NB: there is another use case of `lil_matrix` in `librosa.segment.recurrence_to_lag`. Not sure if it is affected.

#### Steps/Code to Reproduce
Found during CR of #934.

#### Versions
```
Darwin-18.6.0-x86_64-i386-64bit
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
NumPy 1.17.0
SciPy 1.3.0
librosa 0.7.0
```

*pun intended: https://www.youtube.com/watch?v=5_Mtgo9WOL0

**Comment by bmcfee** [comment]
Thanks for flagging this.

I might be rewriting `recurrence_to_lag` in the near future (relating to #907 ), so that one might go away.

`sparsify_rows` will need to be fixed though.

**Comment by bmcfee** [comment]
I took a look into this: I'm not sure this is something we can fix from librosa?  It might be purely down to scipy being a little out of step wit the latest numpy release.

**Comment by lostanlen** [comment]
I tried to create a separate conda environment with latest master branches of numpy, scipy, and librosa, in order to see if the warning would disappear. I would guess that it would, in the wake of scipy/scipy#10379. But i did not succeed in installing scipy from source.

```
 scipy/fft/_pocketfft/pypocketfft.cxx:15:10: fatal error: 'pybind11/pybind11.h' file not found
```

I don't know why this happens.

**Comment by bmcfee** [comment]
It looks like scipy 1.3.1 has fixed this one for us.

**Comment by lostanlen** [comment]
Great! Glad this is resolved. I don't think there is a need to include this in the release notes of 0.7.1
