### ISSUE TITLE
Library like librosa for videos?

### ISSUE THREAD

**Issue by aSafarpoor** [librosa/librosa#938]

**Comment by aSafarpoor** [comment]
hi
do you know any library like libRosa for videos?
please tell me if  you know

**Comment by lostanlen** [comment]
Hello @aSafarpoor,
Please check out:
* https://github.com/scikit-video/scikit-video
* https://github.com/scikit-image/scikit-image
* https://github.com/Zulko/moviepy

I hope this helps!
