### ISSUE TITLE
File objects work with librosa.load but not librosa.stream

### ISSUE THREAD

**Issue by carlthome** [librosa/librosa#941]
#### Description
Loading a WAV file via tf.gfile.GFile works with `librosa.load` but not `librosa.stream`. Interestingly the same error appears regardless of if it is a bucket path or a local path.

#### Steps/Code to Reproduce
```py
import librosa as lr
import tensorflow as tf

path = 'gs://my-bucket/example.wav'

# Loading the entire file works as expected.
with tf.gfile.GFile(path, 'rb') as f:
    lr.load(f, 48000)

# The streaming method crashes.
with tf.gfile.GFile(path, 'rb') as f:
    assert f.seekable() is True
    for waveforms in lr.stream(f, 128, 1024, 512):
        print(waveforms.shape)
```
#### Expected Results
No errors.

#### Actual Results
> RuntimeError: Error opening : File contains data in an unknown format.

#### Versions
```
import platform; print(platform.platform())...
Linux-4.9.0-9-amd64-x86_64-with-debian-9.9
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516]
NumPy 1.17.0
SciPy 1.3.0
librosa 0.7.0
```

**Comment by carlthome** [comment]
And super curiously, this will work fine

```py
import soundfile as sf

with tf.gfile.GFile(path, 'rb') as f:
    for waveform in sf.blocks(f, blocksize=1024):
        pass
```

so perhaps it's something with the overlapping blocks.

**Comment by lostanlen** [comment]
Thanks for reporting. `librosa.stream` is a wrapper around `sf.blocks` so you're hitting at the problem here. I don't know the inner workings of `tf.gfile.GFile`, so i can't comment further for the time being. But it's something worth investigating.

**Comment by carlthome** [comment]
Setting `overlap` in `sf.blocks` still works so I'll have to dig a bit deeper in how _exactly_  librosa.stream and soundfile.blocks differ. :thinking:

**Comment by lostanlen** [comment]
The plot thickens!

For future reference, our call site is at:
https://github.com/librosa/librosa/blob/6e537b476cfdfe2a34124a3aa1d2916d3c64ebbf/librosa/core/audio.py#L213

The called function is at:
https://github.com/bastibe/SoundFile/blob/161e930da9c9ea76579b6ee18a131e10bca8a605/soundfile.py#L319

**Comment by carlthome** [comment]
Found the problem.

`soundfile.info` doesn't reset the open file's read pointer and librosa calls that for converting `duration` and `offset` into sample indices here: https://github.com/librosa/librosa/blob/6e537b476cfdfe2a34124a3aa1d2916d3c64ebbf/librosa/core/audio.py#L354

In other words, this pure PySoundFile MCVE crashes too
```py
with tf.gfile.GFile(path, 'rb') as f:

    sf.info(f)

    # TODO Reset read pointer.
    # f.seek(0)

    for waveform in sf.blocks(f, 1024):
        pass
```
presumably because `soundfile.blocks` and `soundfile.read` expects an audio file header to skip ahead to the start frame and so on.

**Proposed fix:**
1. Require a sample rate to be input into `librosa.stream` and remove the `sf.info` call.
2. Check if `path` is a file object and call `path.seek(0)` after `sf.info` (hacky).
3. Update PySoundFile's `sf.info` function to reset the pointer (perhaps unwanted behaviour, but cannot think of reasons why).

I think I personally prefer 1. because `librosa.stream` already has a tiny gotcha with not defaulting to resampling like `librosa.load` which is an inconsistent public API. The current UX is that the user will notice that `block_length`, `frame_length`, `hop_length` are required and then hopefully notice why in the docstring. Perhaps it would be easier to just require a `sr` as well if `offset` and `duration` should still be in seconds like for `librosa.load`.

**Comment by carlthome** [comment]
This goes beyond `tf.gfile.GFile` by the way, and applies even to the builtin `open()` in Python. I just happened to use `tf.gfile` while working.

**Comment by bmcfee** [comment]
Thanks for tracking this down!



> * Require a sample rate to be input into `librosa.stream` and remove the `sf.info` call.
> 

I don't like this option, because it connotes that an automatic sampling rate conversion would be invoked.  If you give the wrong sampling rate in the call, there's no obvious recourse.

> * Check if `path` is a file object and call `path.seek(0)` after `sf.info` (hacky).
> 

I agree that this is hacky, but I think it might be the best option.

> * Update PySoundFile's `sf.info` function to reset the pointer or defensively copy its argument (perhaps unwanted behaviour, but cannot think of reasons why).

That's a tricky one.  Maybe it would be worth discussing with the soundfile devs?
