### ISSUE TITLE
AttributeError: module 'inspect' has no attribute 'isgenerator'

### ISSUE THREAD

**Issue by ThomasJIKim** [librosa/librosa#947]
The latest version of librosa seems to errors out at import. Below is the full error message I get on pycharm

> `Traceback (most recent call last):
>   File "C:/Users/tkim1/.PyCharmCE2018.2/config/scratches/SpecCen.py", line 1, in <module>
>     import librosa
>   
> File "C:\Users\tkim1\PycharmProjects\Attempt1\venv\lib\site-packages\librosa\__init__.py", line 11, in <module>
>     from . import cache
>   
> File "C:\Users\tkim1\PycharmProjects\Attempt1\venv\lib\site-packages\librosa\cache.py", line 7, in <module>
>     from joblib import Memory
>   
> File "C:\Users\tkim1\PycharmProjects\Attempt1\venv\lib\site-packages\joblib\__init__.py", line 112, in <module>
>     from .memory import Memory, MemorizedResult, register_store_backend
>  
>  File "C:\Users\tkim1\PycharmProjects\Attempt1\venv\lib\site-packages\joblib\memory.py", line 15, in <module>
>     import pydoc
>   
> File "C:\Users\tkim1\AppData\Local\Programs\Python\Python37\lib\pydoc.py", line 62, in <module>
>     import inspect
>   
> File "C:\Users\tkim1\.PyCharmCE2018.2\config\scratches\inspect.py", line 3, in <module>
>     import twitter_scraper as module
>   
> File "C:\Users\tkim1\PycharmProjects\Attempt1\venv\lib\site-packages\twitter_scraper.py", line 2, in <module>
>     from requests_html import HTMLSession, HTML
>   
> File "C:\Users\tkim1\PycharmProjects\Attempt1\venv\lib\site-packages\requests_html.py", line 2, in <module>
>     import asyncio
>   
> File "C:\Users\tkim1\AppData\Local\Programs\Python\Python37\lib\asyncio\__init__.py", line 8, in <module>
>     from .base_events import *
>   
> File "C:\Users\tkim1\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 39, in <module>
>     from . import events
>   
> File "C:\Users\tkim1\AppData\Local\Programs\Python\Python37\lib\asyncio\events.py", line 787, in <module>
>     from _asyncio import (_get_running_loop, _set_running_loop,
> 
> AttributeError: module 'inspect' has no attribute 'isgenerator'`

I tried to rollback to previous versions of librosa to see if that would solve anything but did not have any luck

**Comment by bmcfee** [comment]
This problem is not coming from librosa, but seems to be due to pycharm (or your pycharm configuration).

**Comment by srubenacker** [comment]
I'm having the same problem.  I open up a terminal, run `python3`, then attempt to `import librosa`, but it fails.  I just upgraded from `librosa (0.5.1)` to `librosa (0.7.0)`:

```
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import librosa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/librosa/__init__.py", line 13, in <module>
    from . import core
  File "/usr/local/lib/python3.5/dist-packages/librosa/core/__init__.py", line 114, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.5/dist-packages/librosa/core/time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "/usr/local/lib/python3.5/dist-packages/librosa/util/__init__.py", line 68, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.5/dist-packages/librosa/util/utils.py", line 112, in <module>
    def valid_audio(y, mono=True):
  File "/usr/local/lib/python3.5/dist-packages/librosa/_cache.py", line 53, in wrapper
    if self.memory.location is not None and self.level >= level:
AttributeError: 'Memory' object has no attribute 'location'
```

**Comment by bmcfee** [comment]
@srubenacker that looks like a different error, and my guess is that your installed version of joblib is out of date.

In general, it would be better if you could provide system details by filling out the issue template when reporting this kind of thing, since it cuts down on guesswork from our end.

**Comment by lostanlen** [comment]
@srubenacker upgrading from 0.5.1 to 0.7.0 is a pretty huge leap, so you are going to have to make sure that all of the other installed packages are also upgraded accordingly. In a conda environment, this would be automatic. My guess is that your installation of librosa interferes with other packages (in this case joblib). My advice is to always install librosa in a conda environment, unless you have a really compelling reason not to do so.
If i were to debug your installation, the first command i would try is:
`which python3`

and if it's a pip python:
`pip freeze`

**Comment by srubenacker** [comment]
@lostanlen You were right, my issue was caused by an old version of `joblib (0.11)`.  I upgraded it to `0.13.2` and now `librosa 0.7.0` works.  Thanks for your help.  I will definitely look into using conda from now on.
