### ISSUE TITLE
Ability to provide initial phase to Griffin-Lim

### ISSUE THREAD

**Issue by f90** [librosa/librosa#948]
FEATURE REQUEST

Librosa has a Griffin-Lim implementation to reconstruct audio from spectrogram magnitudes. As far as I can see, it takes only the magnitudes and estimates the phase from scratch in the process:

https://librosa.github.io/librosa/generated/librosa.core.griffinlim.html

But in tasks such as source separation, often the solution converges much more quickly/becomes better when using the mixture phase for the estimation of the source audio output. So it would be cool if another parameter could be added to the function allowing you to optionally pass in an initial guess of the phase:

```
y, sr = librosa.load(librosa.util.example_audio_file(), duration=5, offset=30)
# Get the magnitude spectrogram
mag, phase = librosa.core.magphase(librosa.stft(y))
# Invert using Griffin-Lim starting with phase as initial phase estimate
y_inv = librosa.griffinlim(mag, initial_phase=phase)
```

**Comment by bmcfee** [comment]
Excellent point. I'd support extending the api to support initial phase.

**Comment by lostanlen** [comment]
Good thinking @f90. This is definitely needed.
However, in terms of functional prototype, i wonder whether `initial_phase` is the best we could do ? Can't we dispatch on the type of `mag`? if it's complex-valued, use this as an initial phase. If it's real-valued, use a random initial guess for the phase.
Or is my fondness for type dispatch out of place here? :D

**Comment by bmcfee** [comment]
@lostanlen your suggestion is actually what I had in mind initially.  It's the most elegant solution, since it allows you to resume GL from a previous output.
