### ISSUE TITLE
Heisenbug: tests sometimes fail audio buffer validation

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#951]
#### Description

I've noticed that some of our CI tests seem to randomly fail with audio buffer validation errors, only to pass correctly when restarted.  I don't have any explanation for this, and I doubt it's due to anything in librosa.

It seems to have started after the switch to soundfile as the primary decoder, and it may be indicative of a bug deep in the guts of libsndfile, if not in the python bindings.  Any help diagnosing this would be much appreciated!

**Comment by lostanlen** [comment]
Is there a bruteforce procedure to trigger the Heisenbug with (1-ε) probability ?

**Comment by bmcfee** [comment]
> Is there a bruteforce procedure to trigger the Heisenbug with (1-ε) probability ?

I haven't found any reproducible trigger for it, no.  I can't get it to happen on my local installation either.

**Comment by lostanlen** [comment]
(7 weeks later)
is this still happening?

**Comment by bmcfee** [comment]
I haven't seen it lately, but I also haven't been running tests very often.

**Comment by lostanlen** [comment]
Would be nice to keep an eye on this in the wake of #1064

**Comment by bmcfee** [comment]
> Would be nice to keep an eye on this in the wake of #1064

Indeed.  FWIW i haven't seen it happen lately, and certainly not since rewriting the test fixtures.  I think it's probably clear, but let's hold off on closing this out until we're ready to push 0.8 (ie after having merged a bunch of PRs and run lots of tests).

**Comment by bmcfee** [comment]
This came back at us in #1120 -- a reboot of the build image fixed it.  So it's definitely still active.

**Comment by bmcfee** [comment]
Aha!  I think I've figured this one out.

Some of our safety checks (eg length checks or error cases) that use dummy input audio (because the content doesn't matter) use `np.empty` to construct the buffer.  If we get unlucky with the uninitialized data, it can parse as nan/inf and fail the `valid_audio` checks.

I'll create a PR to remove `np.empty` from all test cases shortly.
