### ISSUE TITLE
RFC: more example tracks?

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#952]
It's been mentioned on numerous occasions that our current example track, catchy as it may be, is not great for demonstrating many of the functions of librosa.  In offline discussions, @lostanlen and I have talked about extending the included audio content to have several tracks, which could be used to demonstrate different functionality.  So I want to kick this out to the community: what do you want to see in our examples?  By this I mean: please recommend specific recordings.

To prevent this discussion from becoming an infinite bike shed, I'm going to lay down some ground rules for inclusion:

1. Content must be CC-licensed or public domain.
2. Total content should not bloat the package too much; I think 10MB is a reasonable upper bound, and this functionally limits us to between 5 and 10 total recordings.
3. No single track should be too long.  It's okay to have some very short examples.
4. The total collection should be diverse in terms of style, instrumentation, polyphony, etc.  If possible, I'd like to include some non-western recordings as well.
5. Any lyrical content should not be offensive, for some reasonable definition of offensive which is compatible with our [CoC](https://github.com/librosa/librosa/blob/master/CODE_OF_CONDUCT.md).  I don't expect any problems here, but I'll reserve executive privilege here to veto anything that could be problematic.
6. Familiarity would be a bonus, for making the examples and documentation more immediately accessible.

With all of that out of the way, let's talk about things not currently demonstrated by our current example.  We don't have to hit all of these, and I'm sure I'm missing some, but we should aim to hit most of them.

* Monophonic audio: we should have at least one solo instrument recording that can be used to demonstrate things like pitch tracking.  Maybe a raga or makam could be good here?  This could also be good for demonstrating onsets.
* Interesting harmony: the current example is pretty boring, harmonically speaking.  Maybe a jazz recording would be appropriate here?  Maybe something with some key changes as well.
* Non-percussive rhythmic elements: something classical (strings) would be nice to have for demonstrating onset and beat tracking with soft attacks.
* Different time signatures: examples with 4/4, 3/4, and maybe a 5/4 or 7/8 would be nice for demonstrating some of the rhythmic features (tempogram, fmt)
* Vocals and instrumentals: we should have at least one track with vocals.
* Non-musical audio: do we need/want this?  Speech?  Environmental sound?  Librosa gets used for these things, so it might be worth considering their inclusion.

Some other discussions that we can have around this:

- Should we have a multi-track / stem set as one of the examples?
- What kind of genre coverage should we strive for?
- How does this issue interact with #641 (non-western systems in display)?  Is #641 a pre-requisite for including non-western examples?  (I'd argue that it should be, and that this would be a good motivating factor for finally doing it.)

Finally, the examples gallery already includes a few candidate options [here](https://github.com/librosa/librosa/tree/master/docs/examples/audio).  We can take some, all, or none of these, but whatever we decide on including should serve as plausible replacements for them and the example notebooks should be revised afterward.

**Comment by lostanlen** [comment]
Thank you for opening this. I concur with these principles. In my opinion, familiarity is crucial for demonstrations like chroma or structure analysis. It really helps to be able to recognize that something is an ABA or an AABA without having to listen to the recording itself.

The reason why i spurred this issue in the first place is that our current example track ("Vibe Ace") is essentially  2-bar ostinato with small variations in instrumentation throughout. Harmonically speaking, it's I -> IV -> I -> IV. Melodically speaking, it's restricted to only four pitch classes: E, G#, A, and B. Lastly, and no offense to Kevin MacLeod, it's really hard to eyeball the feature representation of "Vibe Ace" (for any feature, really) and say: "yes, i recognize it, it's Vibe Ace!". Worse, it's difficult to test or troubleshoot one's pipeline with this example track.

I wholeheartedly second the idea of having non-European audio data shipped with librosa. Raga and makam are both very relevant ideas. Chinese traditional too. If you permit, i will reach out to Changhong Wang, Tejaswinee Kelkar, and Carlos Guedes for that.

Of course, the criterion of familiarity still holds: whatever tunes we end up choosing for Indian / Arab / Chinese / other music, these tunes should be foundational in the cultural history of these traditions. Ideally, the kind of tunes that every child sings along to. And ideally, a tune that transcends the boundary between "erudite" and "popular". If i were to choose one for France (the only geographical folklore i would be comfortable assessing), i would say "Ah ! vous dirai-je, maman".

Jazz recordings are going to be difficult to find. Pretty much all of commercial jazz was composed after 1923, and is therefore not obviously in the public domain. For the rest, it's a case-by-case basis. One famous jazz artist that is entirely public domain AFAICT is Thomas "Fats" Waller. So i guess we could use "Ain't Misbehavin'".

For the onset detection with strings, i would say "Bach Cello Suite no. 1". But i admit that it's quite boring. Perhaps we could mandate Claire Pelofi for this choice. She has impeccable taste in classical music.

Choosing a non-4/4 tune is tricky. For a minute i thought "Stravinsky's Rite of Spring". But that's way too hard for a simple-minded beat tracker. It might also not be public domain. Perhaps that's our chance to select another European tune? I'm pretty sure there are loads of notorious tunes with uneven time signatures in Balkanic, Carnatic, and Malagasy music. But we're going to need an informant to choose it.

Non-musical audio: yes!!! I will think more about this and propose an animal. Ideally one that is found on all continents.

For speech and environmental sounds, i'll defer the responsibility to others.

Note that our current release contains:

* an uncredited, resampled version of "Boz Scaggs — Lowdown":
https://github.com/librosa/librosa/blob/master/tests/data/test2_8000.wav
* a short guitar excerpt by band Texas Music Forge named "Dandelion"
* http://freemusicarchive.org/music/We_Is_Shore_Dedicated/Smiley/12_Sometimes_With_Friends
* http://freemusicarchive.org/music/Karissa_Hobbs/Age_of_Flowers/09_Lets_Go_Fishin
* http://freemusicarchive.org/music/Kevin_MacLeod/Classical_Sampler/Danse_Macabre_-_Sad_Part
* https://www.jamendo.com/track/1316074/stargazer-from-texas
* http://freemusicarchive.org/music/Cheese_N_Pot-C/The_Raps_Well/16_-_The_Raps_Well_Clean_Album_Version
* `sir_duke_slow.mp3` and `sir_duke_fast.mp3` were recorded by Stefan Balke and are released under CC BY 4.0. They are excerpts of a Stevie Wonder track. 

We will definitely be keeping the latter two. They are a perfect, self-contained demonstraton of DTW. GJ @stefan-balke !

I will return with some more.

**Comment by bmcfee** [comment]
> Note that our current release contains:

Minor correction: test and docs examples are not included in the release.  The only data that actually ships with the package is Vibe Ace.

**Comment by lostanlen** [comment]
Oh, i see. I stand corrected.

**Comment by sertansenturk** [comment]
Sorry for being late to the discussion (I knew I forgot to do something in the summer time)...

For the makam/raga & compound meters, there are many gems in the CompMusic corpora. Having said that there are very few CC/public domain recordings which match your criteria. 

For the makam music side, there are no CC recordings. The most representative resource would be the recordings and videos published as a result of Robert Garfias' fieldwork ([metadata in MusicBrainz](https://musicbrainz.org/artist/d7e8c73c-66bc-4200-af5e-cac351cdab15/relationships)). 

We obtained written permission from Prof. Garfias to use the recordings in CompMusic circa 2015. The [webpage](http://www.socsci.uci.edu/~rgarfias/films.html) did not show any license information in the past and it seems to be dead now. Nevertheless, the recordings & videos are still accesible if you follow the links in MusicBrainz, so I would argue these recordings are public domain.

If you really want to be safe, the University of Washington uploaded some of the [videos](https://archive.org/search.php?query=Robert%20Garfias&and[]=creator%3A%22garfias%2C+robert%22&and[]=creator%3A%22garfias%2C+robert%3B+margolis%2C+garry%22) to archive.org with a CC license even though none of them are makam music.

If you think the above suggestion may be problematic and or not adequate, I would suggest to contact @barisbozkurt for additional leads. For Indian music traditions, @kaustuvkanti could probably give some directions.

**Comment by bmcfee** [comment]
Hey everyone, reviving this issue since it's been dormant for a while.  I spent a bit of time crawling the internet for usable audio, and have come up with a few options.  I'm mainly optimizing for duration, complexity, and utility here:

- https://freemusicarchive.org/music/Kevin_MacLeod/Classical_Sampler/Dance_of_the_Sugar_Plum_Fairy
   - Familiar
   - More interesting harmony
   - Mixed instrumentation
   - Nontrivial structure
- https://musopen.org/music/43805-hungarian-dance-no-5-in-f-sharp-minor-woo-1-string-orchestra-arr/
   - Familiar
   - Strings (soft onsets, relatively)
   - Tempo changes
- https://archive.org/details/cd_turn-on-the-heat-the-fats-waller-piano-sol_fats-waller/disc1/01.04.+Fats+Waller+-+Ain't+Misbehavin'.flac
    - Familiar
    - Solo piano, but complex
    - Finding high-quality Waller recordings is kind of a pain.  The above is just a 30sec preview, which is actually fine for us, but a full song would be better.
- https://freesound.org/people/SpliceSound/sounds/369873/
    - Simple (monophonic)
    - Needs some editing (but it's cc0, so we can do that)
    - Funny (always a plus)
    - good for pitch tracking and onset detection demos

Things that would still be good to have:

- Speech / voice data
- Non-western music
- Anything not on a pitch grid.  I tried looking for violin or trombone glissando samples, but didn't find anything I liked.

**Comment by sertansenturk** [comment]
Hi @bmcfee,

Quoting from my earlier comment, do you think anything below may be useful for non-western examples? If yes, I can scour for some good examples.

I will also make an amendment on CompMusic corpora: There are three **fully open** collections: *Carnatic CC, Hindustani CC*, and *Arab Andalusian*, which are easy to access/download from Dunya ([link](https://dunya.compmusic.upf.edu/developers/)).

> Sorry for being late to the discussion (I knew I forgot to do something in the summer time)...
> 
> For the makam/raga & compound meters, there are many gems in the CompMusic corpora. ~~Having said that there are very few CC/public domain recordings which match your criteria.~~
> 
> For the makam music side, there are no CC recordings. The most representative resource would be the recordings and videos published as a result of Robert Garfias' fieldwork ([metadata in MusicBrainz](https://musicbrainz.org/artist/d7e8c73c-66bc-4200-af5e-cac351cdab15/relationships)).
> 
> We obtained written permission from Prof. Garfias to use the recordings in CompMusic circa 2015. The [webpage](http://www.socsci.uci.edu/~rgarfias/films.html) did not show any license information in the past and it seems to be dead now. Nevertheless, the recordings & videos are still accesible if you follow the links in MusicBrainz, so I would argue these recordings are public domain.
> 
> If you really want to be safe, the University of Washington uploaded some of the [videos](https://archive.org/search.php?query=Robert%20Garfias&and%5B%5D=creator%3A%22garfias%2C+robert%22&and%5B%5D=creator%3A%22garfias%2C+robert%3B+margolis%2C+garry%22) to archive.org with a CC license even though none of them are makam music.
> 
> If you think the above suggestion may be problematic and or not adequate, I would suggest to contact @barisbozkurt for additional leads. For Indian music traditions, @kaustuvkanti could probably give some directions.

**Comment by bmcfee** [comment]
> Quoting from my earlier comment, do you think anything below may be useful for non-western examples? If yes, I can scour for some good examples.

Oh absolutely!  I think the challenge will be finding clips that are either sufficiently short, or that we can legally modify (excerpt) for distribution.

I tried to peruse the link you posted, but it doesn't appear to be OA. (Still waiting for account confirmation. :shrug: )

The other question I wanted to bring up: if we want to have a more capacious example gallery, would it make sense to move it into an archive that you have to download explicitly, like sklearn does with standard datasets? This seems like a good idea to me, as I don't want to contribute to the heat death of the universe by shipping a bunch of data around if it's not going to be used.

Given the above, would it make sense to deprecate our example audio track in favor of having users download the librosa mixtape?  We could deprecate in 0.8 and remove in 0.9 if so.

**Comment by bmcfee** [comment]
Relevant thread to the above: #740 - could easily be done with the pooch library.

**Comment by bmcfee** [comment]
Gave this a bit more of a think today.  How's this sound for a plan?

1. Deprecate `librosa.util.example_audio_file()` in 0.8, remove in 0.9.
2. Add the following functions in core:
  - `librosa.fetch_examples()` - downloads the mixtape via pooch.  More on this below.
  - `librosa.list_examples()` - prints out a manifest of the available example clips
  - `librosa.example(id)` - return the file path to the selected example

``fetch_examples()``
- Downloads the archive of example tracks from the internets (either github directly or a zenodo mirror)
- Archive includes a manifest file with text descriptions of all tracks (to make the example list)
- Each track is provided in both a low-quality (22K mono) and original-quality version (if available)
- I want to use pooch for this -- mirdata is not an option because it would introduce a circular dependency, and pooch seems pretty stable.

``list_examples()``
- Nothing major here, just pretty-printing the manifest, a bit like `show_versions()`

``example(id)``
- Works basically like `util.example_audio_file()`, so you'd still have to load the audio.  I prefer to do it this way (rather than return the audio buffer directly) so that users have the option to stream or load, or load fragments, etc.

**Comment by bmcfee** [comment]
It'd also be great to have an example that can show off hpss / source separation.  Maybe a simple jazz trio?  A drum and bass loop?  What do y'all think?

**Comment by lostanlen** [comment]
@bmcfee what's `id` ?

**Comment by kaustuvkanti** [comment]
This sounds great indeed!
Best,Kaustuv
    On Monday, 25 May, 2020, 11:31:04 pm GMT+4, Brian McFee <notifications@github.com> wrote:  
 
 


It'd also be great to have an example that can show off hpss / source separation. Maybe a simple jazz trio? A drum and bass loop? What do y'all think?

**Comment by bmcfee** [comment]
> @bmcfee what's `id` ?

I was thinking a short keyword to identify the example, maybe by composer?  Eg `tchaikovsky`, `brahms`, `waller`, etc.  Then we can suffix the keys to get the high quality examples: `waller_hi`, `brahms_hi`.  IDs would be listed by `list_examples()`.

**Comment by sertansenturk** [comment]
Sorry for my sporadic answers.

> Oh absolutely! I think the challenge will be finding clips that are either sufficiently short, or that we can legally modify (excerpt) for distribution.
Last weekend, we caught up with @kaustuvkanti. We plan to come up with some examples by next weekend.

> I tried to peruse the link you posted, but it doesn't appear to be OA. (Still waiting for account confirmation. shrug )
Although there is open access content, your account has to be approved to enter the website. In the past, the wait time was minimal but if you haven't received approval yet, I'd suggest writing to Alastair Porter or Xavier Serra.

> The other question I wanted to bring up: if we want to have a more capacious example gallery, would it make sense to move it into an archive that you have to download explicitly, like sklearn does with standard datasets? This seems like a good idea to me, as I don't want to contribute to the heat death of the universe by shipping a bunch of data around if it's not going to be used.
>
>Given the above, would it make sense to deprecate our example audio track in favor of having users download the librosa mixtape? We could deprecate in 0.8 and remove in 0.9 if so.

Not sure if my feedback is needed, but at this scale decoupling the data makes complete sense to me. Likewise, the functions you listed in next comment also look good.

**Comment by bmcfee** [comment]
Thanks for the comments and feedback on this.  At this point, I think we can start moving forward with this one.

I think the best way to do this will be to create a new repo under the librosa organization on github that's just dedicated to hosting audio data.  I'm not entirely comfortable with using github as a primary data store (one never knows!), but I think it should be possible to rig up a zenodo integration so that we can publish revisions to the dataset, and have librosa (via pooch) grab the data from zenodo instead of github.

Getting this indirection to work properly might be a bit delicate, and require some version tag synchronization across the repos.  TBH i haven't seen pooch used in this way before, so I'm not sure if there's precedent for it, but I'll try to sort it out before fully committing to this approach.

**Comment by bmcfee** [comment]
Starting to build up the dataset now: https://github.com/librosa/librosa-data

For each recording, we'll have three files:
- 22KHz mono (default)
- high/original quality audio (`_hq` suffix)
- text file including licensing and attribution.

The data repository will include a script that traverses the collection to build a pooch registry and data manifest, which can be transferred over to the librosa source code as package resources.  The separate manifest file will be used to associate metadata files with the audio files at runtime.

The entire repo currently weighs about 15MB (using ogg vorbis), but one benefit of using pooch is that an end user doesn't download all of the data at once, so theoretically we can build this out to be pretty comprehensive.  I still want to keep it minimal to keep maintenance easy, but the total package size should no longer be a consideration for us.

**Comment by bmcfee** [comment]
For a short, mono example, how about https://freesound.org/people/sorohanro/sounds/77711/ ?

**Comment by bmcfee** [comment]
> Although there is open access content, your account has to be approved to enter the website.

My account is approved, but I don't see how to access the CC collections?

**Comment by bmcfee** [comment]
Wound up writing a script to crawl the CC collections directly.

Here's a short one (45sec) out of carnatic-CC: https://dunya.compmusic.upf.edu/carnatic/recording/59d56022-1617-443d-9e92-e21257958883/pavamaana-suthudu-pattu

**Comment by barisbozkurt** [comment]
Sorry that I could not follow this thread. I just wanted to drop a note
just in case its useful, sorry if this is out of context.

Here is a notebook with which one can download a large collection CC
recordings from MTG-Dunya server:
https://github.com/MTG/MIRCourse/blob/master/notebooks/Lecture4_1_downloadAllSARAGAContent.ipynb
(a user token is required)

A copy of that collection is also available for download here:
https://zenodo.org/record/1256127#.XtqSHZ4zbfY
(no need for user token)

**Comment by bmcfee** [comment]
Thanks @barisbozkurt ! 

I was able to mostly get the carnatic and hindustani CC collections; makam-open didn't work at all.  C- and H- had a few dead / broken ids that gummed up the works, but I think I have enough to go on.

**Comment by barisbozkurt** [comment]
I did not know there exists makam-open :)

On Freesound, under ottoman tag there exists some CC recordings:
https://freesound.org/browse/tags/ottoman/
(mostly not music though, the ones I had uploaded were mainly percussion
patterns)

Ssome makam recordings are available on archive.org:
https://archive.org/search.php?query=subject%3A%22Ottoman%20classical%20music%22%20OR%20subject%3A%22Turkish%20classical%20music%22%20OR%20subject%3A%22Turkish%20makam%20music%22
They are mostly bootleg recordings, not sure about the copyright.

If required and not found, I can contact my musician friends to get some CC
recordings.

**Comment by bmcfee** [comment]
A short one for hindustani: https://dunya.compmusic.upf.edu/hindustani/recording/acae4dcf-e5e7-4c8f-b17c-bfec74cabcc1/raag-sohani



> Ssome makam recordings are available on archive.org:

Yeah, but as you mention, archive.org is real spotty about declaring licensing, so I'm preferring to go through a more authoritative source first.

**Comment by bmcfee** [comment]
> Was just reading this, concerning an example multi-track file, feel free to use the one used for [stempeg](https://github.com/faroit/stempeg/tree/add_new_ffmpegprocess#usage).

Thanks @faroit !  I think this one should wait until the 0.9 series and #1130 , but I'll keep it in mind.

**Comment by bmcfee** [comment]
Thanks again for everyone's input on this.

I'd like to wrap up a v1 of the demo track corpus in the next few days.  Before I commit any more updates to the collection, I'm wondering if anyone (@kaustuvkanti ?) could chime in on whether or not the following examples are useful and appropriate?

- https://dunya.compmusic.upf.edu/carnatic/recording/59d56022-1617-443d-9e92-e21257958883/pavamaana-suthudu-pattu
- https://dunya.compmusic.upf.edu/hindustani/recording/acae4dcf-e5e7-4c8f-b17c-bfec74cabcc1/raag-sohani

My main consideration in these is file size -- selecting short excerpts means we don't have to make edits to the source material.  However, I recognize that these two tracks might be unusually short relative to their genre conventions, so I want to make sure we're not picking severe outliers here.

The use-cases I envision here are probably around demonstrating some upcoming features (#1063 #641 ) and maybe as a replacement demo track for the vocal separation example.

**Comment by kaustuvkanti** [comment]
@bmcfee I'm afraid these indeed sound not-so-representative of the genre. If we are concerned about melodic features only, we can choose short 'alap'/'alaapana' (non-metered vocal) excerpts from the Dunya CC collection. If you have any criterion on file size, I can assist you to find a couple of short excerpts.

As of the vocal separation example, do you mean vocal and percussive instruments, please? In that case, we would have to choose metered sections. Otherwise, the drone (tanpura) and the melodic accompaniment (harmonium/violin) are present throughout.

**Comment by bmcfee** [comment]
> I'm afraid these indeed sound not-so-representative of the genre. If we are concerned about melodic features only, we can choose short 'alap'/'alaapana' (non-metered vocal) excerpts from the Dunya CC collection. If you have any criterion on file size, I can assist you to find a couple of short excerpts.

Ok, thanks - glad I asked!

I don't have strict requirements on file size, but a preference for keeping things small and minimizing network traffic in the long run.



> As of the vocal separation example, do you mean vocal and percussive instruments, please?

I was thinking more of [this example](https://librosa.github.io/librosa/auto_examples/plot_vocal_separation.html#sphx-glr-auto-examples-plot-vocal-separation-py) which (loosely) re-implements REPET-SIM.  Then again, this example isn't so useful anymore now that we have pre-trained vocal extractors that work, so perhaps it's time to sunset that one.

**Comment by sertansenturk** [comment]
Hi there,

Had a quick catch-up with @kaustuvkanti last weekend. I have worked with alap/alapnas in the CC corpora, so I will be able to select the excerpts. Next, I will verify them with Kaustuv. The idea is to select crop one non-metered section and one metered section from Hindustani and Carnatic repertoire -> 4 short excerpts with "good" audio quality.

Between the ISMIR review deadline and day job, I cannot work on it this weekend but the next one. @bmcfee is it ok with you?

For the makam music side, I cannot provide any recording with unambiguous licenses, so I will leave the discussion to @barisbozkurt, if it's good for everyone.

**Comment by bmcfee** [comment]
> Between the ISMIR review deadline and day job, I cannot work on it this weekend but the next one. @bmcfee is it ok with you?

That'd be great, thanks!
