### ISSUE TITLE
reassign_spectrogram docstring is slow and uninformative

### ISSUE THREAD

**Issue by lostanlen** [librosa/librosa#955]
#### Description
This issue comes in the wake of PR #926, which closed #394.

First of all, let me express how happy i am that time-frequency reassignment eventually made its way into a wide-audience library such as librosa. Huge thanks to @scjs for his work.

That being said, the current docstring example for reassign_spectrogram technically works, but it's built upon a 2-second example of Vibe Ace at 22050 Hz sample rate. The result is not very compelling in terms of the capabilities of time-frequency reassignment. In particular, it's not at all clear that time-frequency reassignment alleviates the Heisenberg time-frequency tradeoff. At first glance, what seems to happen looks more like a threshold-based sparsification of STFT magnitudes. I'm afraid we might convey the wrong kind of message with this example.

Furthermore, this example is quite slow: ~5 seconds on my laptop, including display in a Jupyter notebook.

Please let me know if you want me to make a PR.

#### Steps/Code to Reproduce
```python
y, sr = librosa.load(librosa.util.example_audio_file())
y_zoom = y[27 * sr : 29 * sr]
freqs, times, mags = librosa.reassigned_spectrogram(
    y=y_zoom, sr=sr, hop_length=16, n_fft=64, ref_power=1e-4
)
db = librosa.amplitude_to_db(mags, ref=np.max)
import matplotlib.pyplot as plt
plt.figure()
plt.subplot(2, 1, 1)
librosa.display.specshow(
    db, x_axis="s", y_axis="linear", sr=sr, hop_length=16
)
plt.title("Spectrogram")
plt.subplot(2, 1, 2)
plt.scatter(times, freqs, c=db, s=0.1, cmap="magma")
plt.title("Reassigned spectrogram")
plt.xlim([0, 2])
plt.xticks([0, 0.5, 1, 1.5, 2])
plt.ylabel("Hz")
plt.subplots_adjust(
    left=0.1, bottom=0.05, right=0.95, top=0.95, hspace=0.5
)
plt.show()
```

#### Actual Results
![reassign_vibe_ace](https://user-images.githubusercontent.com/3943142/63063282-02bb2080-beca-11e9-84ad-8535140b38a7.png)

#### Expected Results
I would prefer to see a faster and more pedagogical example, even if it's synthetic.
For example this:

![reassigned_synth](https://user-images.githubusercontent.com/3943142/63063527-1024da80-becb-11e9-96b0-31bf226beae3.png)

Runs in 75 milliseconds on my laptop.

Code:

```python
sr = 4000
y = 2e-1 * librosa.clicks(times=[0.1], sr=sr, click_duration=1.0, click_freq=2400.0, length=8000) +\
    1e-1 * librosa.clicks(times=[1.2], sr=sr, click_duration=0.5, click_freq=400.0, length=8000) +\
    1e-2 * librosa.chirp(300, 1600, sr=sr, duration=2.0, linear=True) +\
    1e-3 * np.random.randn(2*sr)

freqs, times, mags = librosa.reassigned_spectrogram(
    y=y, sr=sr, n_fft=64, ref_power=1e-2)
db = librosa.amplitude_to_db(mags, ref=np.max)

plt.figure(figsize=(8,8))
plt.subplot(2, 1, 1)
librosa.display.specshow(
    db, x_axis="s", y_axis="linear", sr=sr, hop_length=16)
plt.title("Spectrogram")
plt.gca().set_xticklabels([])
plt.gca().set_xlabel(None)
plt.subplot(2, 1, 2)
plt.scatter(times, freqs, c=db, s=0.1, cmap="magma")
plt.title("Reassigned spectrogram")
plt.xlabel("Time (s)")
plt.xlim(0, 2)
plt.xticks([0, 0.5, 1, 1.5, 2])
plt.ylabel("Hz")
plt.ylim(0, 2000)
```

#### Versions
latest master (0.7.1-dev)

**Comment by bmcfee** [comment]
The revised example looks great! The only caveat I'd add is an explanation of the white background, which is not used elsewhere in spectrogram displays in librosa.

I wonder if it might make sense in the future to expand specshow to have a more obvious background pattern for transparency, like what's used in image editing software?

**Comment by lostanlen** [comment]
We are not using specshow to display the TFR here, but `plt.scatter` + some custom matplotlib tinkering for axes.

**Comment by bmcfee** [comment]
> We are not using specshow to display the TFR here, but `plt.scatter` + some custom matplotlib tinkering for axes.

Ah, very good!  I hadn't noticed that when skimming on my phone, but it makes much more sense to do it that way.

**Comment by bmcfee** [comment]
As an aside, I could imagine mpl's scatter getting unwieldy for this sort of thing pretty quickly when there's a lot of energy.  mpl-scatter-density might be a better option in those scenarios: https://pypi.org/project/mpl-scatter-density/

**Comment by lostanlen** [comment]
That's true. It's also that, by definition, there will be many points over a tiny surface, often so thin as to resemble a line.

**Comment by bmcfee** [comment]
>  often so thin as to resemble a line.

That's the hope, anyway!  I guess my point here is to clarify that the poor running time you report for the current example is almost certainly due to scatter being over-worked, and not due to inefficiency in our implementation.  Scatter-density plot would be much faster in that case, but it doesn't help with the content interpretability problem.

At the risk of bike-shedding, I might suggest enlarging the scatter points (and using squares) so that the actual data is a bit more visible.

**Comment by lostanlen** [comment]
![reassigned_synth_v-3](https://user-images.githubusercontent.com/3943142/63064852-6137cd00-bed1-11e9-98b3-c59515500930.png)


```python
sr = 4000
y = 1e-3 * librosa.clicks(times=[0.1], sr=sr, click_duration=1.0, click_freq=1200.0, length=8000) +\
    1e-3 * librosa.clicks(times=[1.4], sr=sr, click_duration=0.5, click_freq=400.0, length=8000) +\
    1e-3 * librosa.chirp(200, 1600, sr=sr, duration=2.0) +\
    1e-6 * np.random.randn(2*sr)

freqs, times, mags = librosa.reassigned_spectrogram(
    y=y, sr=sr, n_fft=64)
mags_db = librosa.power_to_db(mags)

plt.figure(figsize=(8,8))
plt.subplot(2, 1, 1)
librosa.display.specshow(
    mags_db,
    x_axis="s", y_axis="linear", sr=sr, hop_length=16)
plt.title("Spectrogram")
plt.gca().set_xticklabels([])
plt.gca().set_xlabel(None)
plt.subplot(2, 1, 2)
librosa.display.specshow(
    librosa.power_to_db(0*mags),
    x_axis="s", y_axis="linear",
    sr=sr, hop_length=16)
plt.scatter(times, freqs, c=mags_db, marker='s', cmap="magma")
plt.clim(np.min(mags_db), np.max(mags_db))
plt.title("Reassigned spectrogram")
```

I made the chirp nonlinear. It's more interesting to look at in terms of spectral leakage.

**Comment by lostanlen** [comment]
setting `alpha=0.1` helps convey the message that most reassigned TF bins are in the regions of stationary phase

![reassign_synth_v-4](https://user-images.githubusercontent.com/3943142/63064970-0baff000-bed2-11e9-8abf-2edba97e2d50.png)

**Comment by lostanlen** [comment]
with a lower SNR (10dB instead of 30), we begin to see the limitation of the method. Which is a good thing IMO.
![reassign_synth_v-5](https://user-images.githubusercontent.com/3943142/63065023-4b76d780-bed2-11e9-8676-75c68a112b14.png)

**Comment by lostanlen** [comment]
Coming to think more about this, i beileve that the only reasonable colormap for `reassign_spectrogram` is `gray` with a white background and some alpha value for the TF bins. Only that way do we have a visual effect of accretion of energy near the ridge. We need a colormap that  is not only sequential, but additive in terms of contrast and constant in terms of hue.

**Comment by lostanlen** [comment]
```python
sr = 4000
amin = 1e-10
y = 1e-3 * librosa.clicks(times=[0.3], sr=sr, click_duration=1.0,
                          click_freq=1200.0, length=8000) +\
    1e-3 * librosa.clicks(times=[1.5], sr=sr, click_duration=0.5,
                          click_freq=400.0, length=8000) +\
    1e-3 * librosa.chirp(200, 1600, sr=sr, duration=2.0) +\
    1e-6 * np.random.randn(2*sr)

freqs, times, mags = librosa.reassigned_spectrogram(y=y, sr=sr, n_fft=64)
mags_db = librosa.power_to_db(mags, amin=amin)
background = np.zeros_like(mags) - 10*np.log10(amin)

plt.subplot(2, 1, 1)
librosa.display.specshow(mags_db, x_axis="s", y_axis="linear", sr=sr,
                         hop_length=16, cmap="gray_r")
plt.title("Spectrogram")
plt.gca().set_xticklabels([])
plt.gca().set_xlabel(None)
plt.subplot(2, 1, 2)
librosa.display.specshow(background, x_axis="s", y_axis="linear",
                         cmap="gray_r", sr=sr, hop_length=16)
plt.scatter(times, freqs, c=mags_db, alpha=0.05, cmap="gray_r")
plt.clim(-100, 0)
plt.title("Reassigned spectrogram")
```

![reassign_synth_v-6](https://user-images.githubusercontent.com/3943142/63065754-4c5d3880-bed5-11e9-8339-d51eafd6ae19.png)

**Comment by lostanlen** [comment]
shorter by putting the reassigned spectrogram on top. Note that i'm no longer using a background image.


```python
sr = 4000
amin = 1e-10
y = 1e-3 * librosa.clicks(times=[0.3], sr=sr, click_duration=1.0,
                          click_freq=1200.0, length=8000) +\
    1e-3 * librosa.clicks(times=[1.5], sr=sr, click_duration=0.5,
                          click_freq=400.0, length=8000) +\
    1e-3 * librosa.chirp(200, 1600, sr=sr, duration=2.0) +\
    1e-6 * np.random.randn(2*sr)

freqs, times, mags = librosa.reassigned_spectrogram(y=y, sr=sr, n_fft=64)
mags_db = librosa.power_to_db(mags, amin=amin)

plt.subplot(2, 1, 1)
plt.scatter(times, freqs, c=mags_db, alpha=0.05, cmap="gray_r")
plt.ylim(0, 2000)
plt.yticks([0, 500, 1000, 1500, 2000])
plt.xlim(0, 2)
plt.xticks([])
plt.clim(10*np.log10(amin), 0)
plt.title("Reassigned spectrogram")
plt.subplot(2, 1, 2)
librosa.display.specshow(mags_db, x_axis="s", y_axis="linear", sr=sr,
                         hop_length=16, cmap="gray_r")
plt.title("Spectrogram")
```

which one do you prefer?

**Comment by bmcfee** [comment]
That's beautiful.

**Comment by lostanlen** [comment]
Hahaha thanks! But which code style do you prefer?
(1) subplot 1, specshow spectrogram, remove xticks, remove xticklabels; subplot2, specshow background, scatter
(2) subplot 1, scatter, adjust xlim and ylim, define xticks and yticks; subplot 2, specshow spectrogram

**Comment by bmcfee** [comment]
I think having the spectrogram on top makes a bit more sense, but I don't have a strong opinion.

One more nitpick: if you shareax between the subplots, then we can be sure that the coordinates line up between the two. It looks correct as is, but may as well demonstrate good style.
