### ISSUE TITLE
RFC: math formulae in docstrings?

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#956]
#### Description
In preparing #954, I've been fixing up some other docstrings, and noticed that #926 introduced some latex notation to the docstring for defining reassigned spectra.

This looks great when rendered in the compiled documentation, but is pretty illegible if you're reading docs in a repl like ipython or jupyter notebook.  This is why I've avoided using formal math notation in the docstrings so far, even though they do look nice, and there's precedent for it from the scipy package.  However, we never really made a formal decision about how docstrings should be styled for this sort of thing, so I'm raising the issue now.

I think there are good arguments in both directions.  Here's a quick summary of pros and cons from my perspective:

**Pro**

- Looks nice on the website
- Most people will read docs through the website anyway
- Easier to relate to literature
- Docstrings will have sphinx restructured text anyway, so we may as well lean into it

**Con**

- Looks bad in the repl
- Could wreak havoc on screen-readers
- Harder to relate to code, especially when subscripts and non-standard operators are involved
- ReST in docstrings is usually not too bad, but we should keep it minimal

**Comment by lostanlen** [comment]
*Con*: scikit-learn doesn't do it. I would tend to think that we ought not try to outsmart scikit-learn.

**Comment by bmcfee** [comment]
> (https://github.com/librosa/librosa/search?q=%22..+math%3A%3A%22&unscoped_q=%22..+math%3A%3A%22)

I have no problem with latex in the gallery examples because you can never encounter those through repl -- they're intended to be rendered in the documentation page.

**Comment by lostanlen** [comment]
Oh, that's my point. 
I meant to paste this:

https://github.com/scikit-learn/scikit-learn/search?p=3&q=%22..+math%3A%3A%22&unscoped_q=%22..+math%3A%3A%22

**Comment by bmcfee** [comment]
I guess we decided to remove ReST from the docstrings?

**Comment by lostanlen** [comment]
What do you mean? My PR removes the ReST-LateX equations that were introduced by #926. It seems like we agreed to follow the example of scikit-learn here.

**Comment by bmcfee** [comment]
> It seems like we agreed to follow the example of scikit-learn here.

The discussion above didn't seem resolved to me, but I was leaning in this direction anyway.

**Comment by lostanlen** [comment]
Oh, OK. If you think that ReST-LaTeX is here to stay, feel free to close my PR. No hard feelings :)

**Comment by bmcfee** [comment]
Nah, I'm happy to remove it, at least for now.

It would be nice to have equations in the doc build but not in the repl, but I don't think there's a clean way to achieve that right now.
