### ISSUE TITLE
soundfile raises OSError due to missing libsndfile dependency

### ISSUE THREAD

**Issue by lostanlen** [librosa/librosa#970]
#### Description
Originally in: https://github.com/bastibe/SoundFile/issues/118
Related: #847 which closed #845

#### Steps/Code to Reproduce
Described by @r9y9 in #969

#### Versions
https://github.com/librosa/librosa/tree/b1e41e83a9d177d7ca83bf7e0160c5e3c4177e3b#soundfile
librosa 0.7.0

**Comment by lostanlen** [comment]
closed by @r9y9 in #969

**Comment by bmcfee** [comment]
As I mentioned over in #972, I don't think we can or should fix this.  soundfile is a hard dependency, so if it's throwing an error at import time, we should fail noisily.

**Comment by r9y9** [comment]
Well, I thought that soundfile is a soft dependency at the moment (if I understand https://github.com/librosa/librosa/issues/845#issue-419244978 correctly).

> That said, there's no reason we couldn't have a soft dependency on soundfile as a first-pass attempt to load the data, and only fall back to audioread if soundfile fails for some reason (not installed, missing codec, etc).

My concern is that the breaking change from 0.6.x to 0.7.0: `import librosa` doesn't work if libsndfile is not installed, while the exact same code worked as is before. I'm not sure if there's a doc for our deprecation policy, but I have been seeing that librosa is great at backward compatibility (one *huge* reason why I like librosa btw); e.g. trying to keep breaking changes minimal as possible. I think bumping 0.6.x to 0.7.0 means that we have some breaking changes, but I was hoping that we can still try to minimize breaking changes if possible.

That said, I'm okay that #972 cannot be accepted. I just hit a rare situation where libsndfile is not installed and I didn't have a permission to run `apt-get install libsndfile-dev`.

**Comment by bmcfee** [comment]
> Well, I thought that soundfile is a soft dependency at the moment (if I understand [#845 (comment)](https://github.com/librosa/librosa/issues/845#issue-419244978) correctly).

Ah, I see what you mean.  That comment is no longer accurate (was written before #847 ).  As of 0.7, soundfile is the primary loader and a hard dependency -- sorry for the mixup.



> My concern is that the breaking change from 0.6.x to 0.7.0: `import librosa` doesn't work if libsndfile is not installed, while the exact same code worked as is before. I'm not sure if there's a doc for our deprecation policy, but I have been seeing that librosa is great at backward compatibility (one _huge_ reason why I like librosa btw); e.g. trying to keep breaking changes minimal as possible. I think bumping 0.6.x to 0.7.0 means that we have some breaking changes, but I was hoping that we can still try to minimize breaking changes if possible.

I agree with all of that.  Deprecation cycles for code is pretty easy to manage with our helpers, but there isn't good tooling in place for managing dependency changes.



> That said, I'm okay that #972 cannot be accepted. I just hit a rare situation where libsndfile is not installed and I didn't have a permission to run `apt-get install libsndfile-dev`.

Ok, thanks for understanding.  My recommendation there is to use the conda package if possible, otherwise compile your own libsndfile locally.  (Or plead with the sysadmin for mercy. :grin: )
