### ISSUE TITLE
Scaling issue in RMS computation

### ISSUE THREAD

**Issue by ashispati** [librosa/librosa#978]
#### Description
Scaling issue in RMS computation `librosa.feature.rms` when the input is the magnitude spectrogram (specifying `S`)

#### Steps/Code to Reproduce

Example:
```
import librosa
fs = 48000
block_size = fs // 4
hop_size = fs // 8
x = np.linspace(start=0, stop=10 * fs, num=10 * fs)
y = np.sin(2.0 * np.pi * 200.0 * x / fs)

# compute RMS from spectrogram
S, _ = librosa.magphase(librosa.stft(y, n_fft=block_size, hop_length=hop_size, center=True, window=np.ones))
rms_spec = librosa.feature.rms(S=S)   # rms value  is approx. 77.45

# compute RMS from samples
rms_samp = librosa.feature.rms(
    y, 
    frame_length=block_size, 
    hop_length=hop_size, 
    center=True
)  # rms value is approx. 0.707 which is expected (rms for sine wave is 1/sqrt(2))
```

#### Expected Results
The RMS of a unit sine wave should ideally be `1/sqrt(2) = 0.707`. 

#### Actual Results
`rms_time` gives the correct results whereas `rms_spec` seems to scaled by a factor of `sqrt(N)` where `N` is the fft-length. I use a rectangular window to ensure this is not due to windowing effects. 

#### Versions

Darwin-18.7.0-x86_64-i386-64bit
Python 3.6.8 (default, Jun 12 2019, 17:04:27) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)]
NumPy 1.16.4
SciPy 1.2.0
librosa 0.6.3

**Comment by bmcfee** [comment]
Excellent point, thanks for catching that.  The cause here is that the forward FFT is unnormalized (rather than `mode='ortho'`).

Note that you're example will still be off by a bit because the STFT uses padding to center the frames, and the time-domain implementation does not.

**Comment by ashispati** [comment]
Not sure if I am missing something here, but STFT doesn't seem to have a `mode` argument. 
Also, the I thought the `center=True` argument in `librosa.feature.rms` also uses padding to center the frames.

**Comment by bmcfee** [comment]
> but STFT doesn't seem to have a `mode` argument.

it doesn't, but the underlying `fft` implementation does, at least in numpy >= 1.10.



> Also, I thought the `center=True` argument in `librosa.feature.rms` also uses padding to center the frames.

Ah, you're correct.  For some reason, my eye glanced over that in your second call to rms.

**Comment by ashispati** [comment]
> it doesn't, but the underlying `fft` implementation does, at least in numpy >= 1.10.

Understood. Thanks for the quick reply.
