### ISSUE TITLE
Locating a recording music on a whole music

### ISSUE THREAD

**Issue by JoeyChuuichi** [librosa/librosa#980]
#### Description

My application needs some functions which can help locate a music segment onto original
The music segment is like recording while other devices are playing the original music, which means it has some information loss, but the features should be the same.
Is there any idea how to solve the problem by librosa?

**Comment by dpwe** [comment]
You might want to look at a fingerprinting solution e.g.
https://github.com/dpwe/audfprint
Disclosure: I am the author.

  DAn.

**Comment by JoeyChuuichi** [comment]
@dpwe 
Great! It looks good! 
I will try it and give you feedback

**Comment by JoeyChuuichi** [comment]
@dpwe 
Though I have not precisely checked the accuracy, the fingerprinting tracking solution works quite well under my manual check: the error should be within 0.5 sec. I will check more precisely later.

BTW, do you have any publication with that repo? I may want to write a paper later by using your function, I am thinking that I should cite your great contribution. Thx!

**Comment by dpwe** [comment]
If you have issues with the time accuracy, you can try increasing the
density (e.g. --density 100) and reducing the quantile at which the match
range is called (e.g. --time-quantile 0.02).  A smaller time quantile means
that it will report the beginning of the match closer to the start of
landmarks matching, but runs the risk of making a large error if a small
number of random landmark matches happen to line up too.

The only publication associated with this code is the abstract I wrote for
the MIREX 2014 evaluation:
https://www.music-ir.org/mirex/abstracts/2014/DP1.pdf .

  DAn.
