### ISSUE TITLE
any c++ source sbout librosa.stft/librosa.istft

### ISSUE THREAD

**Issue by ucasiggcas** [librosa/librosa#982]
hi,
if I want to use the C++ to get the stft, how could I do ?
any reference ?

could U help me ?
thx

**Comment by lostanlen** [comment]
Hello @ucasiggcas, it's unclear what you're asking.
But if what you want is a C++ implementation of STFT, then librosa is not the way to go. Librosa is written 100% in Python.
That being said, there are equivalent implementations of STFT in other libraries, among which:
* Essentia https://github.com/MTG/essentia
* YAAFE: https://github.com/Yaafe/Yaafe

I hope this helps!
