### ISSUE TITLE
how to resolve the path problem

### ISSUE THREAD

**Issue by mmmmayi** [librosa/librosa#985]
When  I run the source code on my computer just like `~/proj/librosa-master/librosa/core$ python spectrum.py `, a error happened:
`ImportError: cannot import name 'time_frequency' from '__main__' (spectrum.py)
`
I know I can change the code in each source code to obtain the result, but it is too time- consuming, can you help me to resolve it? Thank you for reading the issue
#### Versions
import platform: Linux-4.15.0-55-generic-x86_64-with-debian-buster-sid
import sys: 3.7.3
import numpy: 1.16.2

**Comment by bmcfee** [comment]
The problem here is that you appear to be trying to execute one of the module files as if it was a script, and it is not.  Please refer to the documentation for installation and usage instructions.

**Comment by mmmmayi** [comment]
> The problem here is that you appear to be trying to execute one of the module files as if it was a script, and it is not. Please refer to the documentation for installation and usage instructions.

I know how to use it and successfully used it in python, but now i want to rewrite the function of STFT in java, so I just want to check some detail, such like print the shape of stft_matrix or figure out how the loop work

**Comment by lostanlen** [comment]
@mmmmayi If what you want is to delve into the implementation, your best option is to use a debugger, such as `pdb`. Note that Python debugging tools are included in IDE, such as Atom (https://atom.io/packages/python-debugger), vim (https://vi.stackexchange.com/questions/17962/python-debugging), or PyCharm (https://www.jetbrains.com/help/pycharm/debugging-your-first-python-application.html).

In any case, this isn't an issue that warrants any change in the librosa codebase, so i'm going to close it.

I hope this helps!
