### ISSUE TITLE
Acceleration for window-less STFT

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#986]
#### Description

The STFT implementation operates by chunking the input signal into blocks, broadcast-multiplying the window across the block, and then computing the (r)fft.  See https://github.com/librosa/librosa/blob/master/librosa/core/spectrum.py#L236-L237

This invokes a temporary allocation/copy for the intermediate multiplication result.  In general, this is unavoidable, and the desired behavior for the default window configuration.

However, we sometimes want to compute an STFT without a window, eg, the CQT relies on several calls to `stft` with a rectangular (all-ones) window, as windowing is implemented by the filter basis.  In this case, the intermediate windowed result is identical to the input signal, but it still invokes an array copy, which is inefficient.

The suggested change is to detect and bypass the all-ones window multiplication and operate on the signal directly.  This should provide a modest bump in throughput.

**Comment by ZiyaoWei** [comment]
This looks fun  - can I give it a try? Maybe it's my chance of redemption for dropping the ball with #527.

**Comment by bmcfee** [comment]
Absolutely, thanks for volunteering!

**Comment by lostanlen** [comment]
Preliminary benchmarks by @ZiyaoWei have demonstrated that, alas, this is far from a `good for beginners` issue :D
