### ISSUE TITLE
python hangs when importing librosa without admin rights

### ISSUE THREAD

**Issue by philgzl** [librosa/librosa#987]
Librosa version: 0.7.0
OS: Windows 10
Python version: 3.7.4

So I just installed a clean version of Windows and installed python in 'C:\Program Files\Python37'. Since it's in 'C:\Program Files' I need admin rights to install packages, so I always run 'cmd' as administrator before calling 'pip install'. I installed librosa using 'pip install librosa' without any errors.

But now when trying to import librosa when I am NOT running python as administrator, python hangs. No errors, just stuck, as if loading forever. When I am running python as administrator, it works.

**Comment by LZ-QWQ** [comment]
I also met this problem !!! in Windows10 librosa 0.7.0 Python 3.6.6（from Visual Studio 2017）

**Comment by lostanlen** [comment]
@LZ-QWQ try installing librosa from scratch using miniconda.
Please see: https://docs.conda.io/projects/conda/en/latest/user-guide/install/windows.html

**Comment by leon-thomm** [comment]
Same problem here - Windows 10. Starting Python as admin works. I didn't try miniconda though; would be great if it would also work through pip install.

**Comment by a5467021** [comment]
I also met this problem. I think this may be caused by some kind of access violation. Grant the permission of `Modify` and `Write` to `Users` on the `librosa` package folder may be a workaround, and this worked for me.
