### ISSUE TITLE
np.asscalar(a) deprecation warning

### ISSUE THREAD

**Issue by Alge** [librosa/librosa#988]
Steps to reproduce:

```
import numpy as np
import librosa

filename = librosa.util.example_audio_file()

y, sr = librosa.load(filename)

y_harmonic, y_percussive = librosa.effects.hpss(y)

tempo, beat_frames = librosa.beat.beat_track(y=y_percussive,
                                             sr=sr)
```
this outputs:

.../env/lib/python3.7/site-packages/librosa/beat.py:309: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  hop_length=hop_length))

#### Versions
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.4 (default, Jul  9 2019, 18:13:23)
[Clang 10.0.1 (clang-1001.0.46.4)]
NumPy 1.17.2
SciPy 1.3.1
librosa 0.7.0

**Comment by bmcfee** [comment]
Thanks for noting this.  We use asscalar in several places throughout the package, so it will take a thorough audit to clean up.

**Comment by lostanlen** [comment]
I would be in favor of bundling this with the 0.7.1 release. It's embarassing to have deprecation warnings in the example code of a stable release.

**Comment by bmcfee** [comment]
Agreed, so long as it doesn't raise our minimum supported numpy version.

**Comment by lostanlen** [comment]
I'm pretty sure that `.item()` has been around since at least numpy v1.8 (~2014)
see https://github.com/numpy/numpy/issues/4701
