### ISSUE TITLE
`librosa.load()` silently ignores the `duration` parameter if it is a string

### ISSUE THREAD

**Issue by tasercake** [librosa/librosa#996]
#### Description
When using `soundfile`, `librosa.load()` silently ignores the `duration` parameter if it is a string.
I haven't tested other input types, but passing `"4"` as the `duration` should either work as expected or raise an exception rather than silently being ignored,

#### Steps/Code to Reproduce
1. Ensure you're loading a format supported by `soundfile` (eg. WAV or FLAC)
2. Pass a string as the `duration` parameter of `librosa.load()`:
```python
audio, sr = librosa.load('file.flac', duration="4")  # Note that `duration` is a string
print((len(audio) / sr) == 4)
```
This generally comes out `False` since the `duration` parameter is ignored and the whole file is loaded.

#### Expected Results
The duration of the loaded audio should be 4 seconds (if the string is castable to an int), OR a `TypeError` (or some other exception) should be raised.

#### Versions
```python
>>> import platform; print(platform.platform())
Windows-10-10.0.18362-SP0
>>> import sys; print("Python", sys.version)
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.16.4
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.3.1
>>> import librosa; print("librosa", librosa.__version__)
librosa 0.7.0
```

**Comment by konoikon** [comment]
I do not believe that it is being ignored. In fact, there is something more interesting going on. Here's a part of `load()`:

```python
if duration is not None:
	frame_duration = int(duration * sr_native)
```

When `duration="4"` is passed, the string is multiplied and results in a frame duration of a `sr_native` number of 4s. Does that seem right?

**Comment by bmcfee** [comment]
> When `duration="4"` is passed, the string is multiplied and results in a frame duration of a `sr_native` number of 4s. Does that seem right?

Indeed!  So you'll end up with a string of 44100 "4"s in a row, which then gets cast to `int`.  Seems like this should throw an overflow error or something.  At any rate, I think the best thing is to check up front that `duration` is a non-negative number before moving into any calculations.

**Comment by konoikon** [comment]
One solution (and in my opinion the right one) is to use type hints according to [PEP-484](https://www.python.org/dev/peps/pep-0484/), but they are not used elsewhere in the codebase.
Another option is to include an `assert(type(duration)=="float" and duration>0)` or put that in an if-statement.

**Comment by lostanlen** [comment]
This issue is quite embarassing, if amusing. Would be good to have a type check at runtime for v0.7.1.

@konoikon it's true that the type hint could make sure that `duration` is a number. But we'd also like to raise an exception if `duration<=0` and i don't think we can do that at type inference time (whatever "type inference time" means in a dynamical language such as Python).

**Comment by tasercake** [comment]
Perhaps it would make sense to do something like this?

```python
try:
    duration = float(duration)
except (TypeError, ValueError):
    raise TypeError("Expected duration to be a number, got '{}'".format(type(duration))
```

This has the advantage of allowing strings that can be cast to numbers, which might be useful for passing values directly from `argparse` and similar libraries.

**Comment by konoikon** [comment]
I'm working on it :)

**Comment by lostanlen** [comment]
@konoikon i'm not a big fan of try-catch statement unless absolutely necessary. They are difficult to specify, difficult to test, and difficult to maintain. I am also wary of implicit type conversions at runtime. I would prefer a simple `if` statement on the type and value and duration with a clear error message, thereby deferring the responsibility of supplying the correct type to the user.
