### ISSUE TITLE
wrong frame count with mfcc ??

### ISSUE THREAD

**Issue by cxy200927099** [librosa/librosa#997]
#### Description
I think the mfcc shape are not right, the input signal data y, len(y) is 4491
then calculate the mfcc by follow parameters

#### Steps/Code to Reproduce

```python
    file = 'flute.novib.ff.A4.wav'
    y, sr = librosa.load(file, sr=None)
    print("y_lenth=", len(y), " sampleRate=", sr)
    # extract mfcc
    mfccs = librosa.feature.mfcc(y=y,
                                 sr=sr,
                                 n_mfcc=40,
                                 n_fft=2048,
                                 hop_length=512,
                                 win_length=2048,
                                 center=False,
                                 fmin=30,
                                 fmax=3000,
                                 window='hamming',
                                 # norm=None
                                 )
    print(mfccs.shape)
```

#### Expected Results
I think the mfccs.shape should be (40, 6)
when calc stft the y signal data should be sliced to  a time series into overlapping frames;
And every frame length should be win_length(2048), the step size is 512, 
so the final frame count
     frame_count = 1 + (len(y) - win_length) /hop_length + (1  if (len(y) - win_length) %hop_length != 0 else  0 )
ie, frame_count = 1 + (4491 - 2048)/512 + 1 = 1 + 4 +1 = 6 

when (len(y) - win_length) %hop_length != 0, it will fill 0 to the frame fit to win_length

#### Actual Results
but the actual Results mfccs.shape is (40, 5)

#### Versions
```
>>> import platform; print(platform.platform())
Linux-4.9.184-linuxkit-x86_64-with-Ubuntu-16.04-xenial
>>> import sys; print("Python", sys.version)
Python 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.17.2
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.3.1
>>> import librosa; print("librosa", librosa.__version__)
librosa 0.7.0
```

**Comment by lostanlen** [comment]
I would recommend that you use `center=True` unless there is a compelling reason to do otherwise.
This will result in `ceil(len(y)/hop_length) = ceil(8.18359375) = 9` columns, independently of `win_length`.

**Comment by cxy200927099** [comment]
> Hello @cxy200927099, welcome to librosa.
> 
> I would recommend that you use `center=True` unless there is a compelling reason to do otherwise.
> This will result in `ceil(len(y)/hop_length) = ceil(8.18359375) = 9` columns, independently of `win_length`.
> 
> I hope this helps!

ok，thank you
