### ISSUE TITLE
specshow causes Python to run out of memory

### ISSUE THREAD

**Issue by bjourne** [librosa/librosa#999]
Here is code that reproduces the problem:
```
import numpy as np
from librosa import amplitude_to_db, load, stft
from librosa.display import specshow

y, sr = load('07074066.wav', sr = None, mono = True)
hop_length = round(sr * 0.01)
n_fft = round(sr * 0.5)
print(hop_length, n_fft)
x = stft(y, n_fft = n_fft, hop_length = hop_length)
s = amplitude_to_db(np.abs(x))
specshow(s, y_axis = 'linear', x_axis = 'time',
         sr = sr, hop_length = hop_length)
```
The audio file can be found here http://bbcsfx.acropolis.org.uk/assets/07074066.wav `specshow` hangs and consumes more and more memory until the Python process is killed by the os.  Librosa 0.7.0, numpy 1.17.2, python 3.7.4.

**Comment by bmcfee** [comment]
Your spectrogram has 22K frequency bands, and your frame overlap is 98%.  A quick calculation shows that this would take approximately just to store the STFT coefficients, let alone render them in color.

I suggest sticking to the default analysis parameters unless you have a strong reason to change them.
